### PR TITLE
Warn on initial render when style contains a NaN value.

### LINKED ISSUE #5773: Warn if style value is NaN
Passing a value of NaN as the value of a css style seems to indicate an error.  Turns out that we don't warn on initial render, and give a confusing error on update (because `NaN != NaN` as per spec).  Discovered in https://github.com/facebook/react/issues/4877#issuecomment-168471074

```
ReactDOM.render(<div style={{marginLeft: NaN}} />, document.getElementById('container'));
ReactDOM.render(<div style={{marginLeft: NaN}} />, document.getElementById('container'));
```

Anyway, we should probably warn if someone passes in `NaN` on initial render, and not warn on update if both previous/next values are NaN.

### PR DESCRIPTION
**Pull request by rickbeerendonk**
Fixes #5773

### CODE REVIEW

**Comment by syranide** [comment]
Isn't `isNaN` already available on all browsers? Also, `value !== value` is not a sufficient test.

**Comment by jimfb** [comment]
@syranide `isNaN` is available everywhere, but it has some nasty edge cases.  For instance, the String "NaN" will return true.  `Number.isNaN` is much better, but is not yet supported on all browsers.  `value !== value` is one of the recommended polyfills - why is it not sufficient?

**Comment by syranide** [comment]
@jimfb Oh wow that's interesting, didn't know about that. Yeah my bad, it's correct. I was thinking of `0 !== -0` from the `Object.is` polyfill, but my brain fooled me, it was the other way around. :+1:

**Comment by syranide** [comment]
However, we don't want to polyfill `Number.isNaN` in the global namespace. We should require users to have the polyfill or make the polyfill internal.

**Comment by zpao** [comment]
All the same things I said in #5811. We should pick one

**Pull request closed without merging**
