### PR TITLE
[rcr] Re-export useMemoCache in top level React namespace

### PR DESCRIPTION
**Pull request by poteto**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #31110
* #31055
* #31054
* #31053
* #31052
* #31051
* __->__ #31050

In order to support using the compiler on versions of React prior to 19,
we need the ability to statically import `c` (aka useMemoCache) or
fallback to a polyfill supplied by `react-compiler-runtime` (note: this
is a separate npm package, not to be confused with
`react/compiler-runtime`, which is currently a part of react).

To do this we first need to re-export `useMemoCache` under the top level
React namespace again, which is additive and thus non-breaking. Doing so
allows `react-compiler-runtime` to statically either re-export
`React.__COMPILER_RUNTIME.c` or supply a polyfill, without the need for
a dynamic import which is finicky to support due to returning a promise.

In later PRs I will remove `react/compiler-runtime` and update the
compiler to emit imports to `react-compiler-runtime` instead.

### CODE REVIEW

**Comment by josephsavona** [comment]
> To do this we first need to re-export useMemoCache under the top level React namespace again

Can you clarify this bit? I'm assuming it's so that we can do the feature detection, but why doesn't it work to check for  `react/compiler-runtime`? It would just be really really nice to keep this out of the main public API.

**Comment by poteto** [comment]
for backwards compatibility we can't inject something like `import * as ... from 'react/compiler-runtime'` since that module wouldn't exist. we could use a dynamic import instead but that's not ergonomic for codegen since it returns a promise. and CJS wouldn't work either since it wouldn't play well with ESM-only bundlers. 

if we export this from the main API (could also rename?) then it makes the import always work and then it's trivial to do the check and fallback

**Comment by josephsavona** [comment]
Ahh that makes sense. I’m too used to require(). In that case, how about naming more generically and put this behind an object so that we could add other compiler runtime apis there later? Eg React.__compilerRuntume.c for the memo cache.

**Review by josephsavona — CHANGES_REQUESTED** [review]
Let's export an object so we have a single place to check for various runtime APIs we may add over time

**Comment by poteto** [comment]
> Let's export an object so we have a single place to check for various runtime APIs we may add over time

Done!

**Review by josephsavona — APPROVED** [review]

**Pull request closed without merging**
