### PR TITLE
feat(chore): Minor refactor

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Replaced the `if-else` ladder with ternary operator thereby resulting in a more concise form.

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @gaearon

**Comment by gaearon** [comment]
Hi, we generally avoid stylistic changes like this. It also won't work because requires need to be static.

**Comment by gaearon** [comment]
(Thanks for PR though!)

**Comment by jamesgeorge007** [comment]
@gaearon It would be great if you could point me to a perfect one to go for.

**Pull request closed without merging**
