### PR TITLE
Fixed typo and jsdoc

### PR DESCRIPTION
**Pull request by seunggabi**
I fixed typos and jsdoc.
I remove unused variable (`cancelWork`) in `schedule/index.html`

### CODE REVIEW

**Comment by seunggabi** [comment]
@vikaskyadav 
I looked up `cancelWork` in project all directory.
I don't find it. I found `cancelWorkTimer` instead.

So, I think `cancelWork` is not used.

**Comment by vikaskyadav** [comment]
Then. It is good to go. Good work!

**Comment by react-linter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  node` failed.
  </td>
    </tr>
  </tbody>
</table>



### Log


```sh
Error:  { FetchError: invalid json response body at http://react.zpao.com/builds/master/_commits/0040efc8d85923d64bee1fdf7e9029d65d01b751/results.json reason: Unexpected token < in JSON at position 0
    at /home/circleci/project/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'FetchError',
  message: 'invalid json response body at http://react.zpao.com/builds/master/_commits/0040efc8d85923d64bee1fdf7e9029d65d01b751/results.json reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }

```

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by seunggabi** [comment]
I don't know why ci failed.

**Comment by NE-SmallTown** [comment]
See https://github.com/facebook/react/pull/13509#issuecomment-417880186

**Comment by seunggabi** [comment]
@vikaskyadav Excuse me.. Do you know when this will be merged? I'm curious.
If you know, tell me~ thanks!

**Comment by seunggabi** [comment]
@vikaskyadav 
I think, this PR don't need
So I close this PR.

Thank you about your review :)

**Pull request closed without merging**
