### PR TITLE
Debug render-phase side effects in "strict" mode

### LINKED ISSUE #12089: Debug render-phase side effects in strict-mode for DEV
Relates to PR #12083

Currently we double-invoke component `constructor`, `render`, `static getDerivedStateFromProps` and `setState` reducer functions if the `debugRenderPhaseSideEffects` feature flag is on. We should also do this if we're inside of a `StrictMode` subtree.

However, it is likely that the new `StrictMode` element will be present in production apps, so I believe it is important that it not negatively impact performance.

Strict warnings (like all warnings) only impact dev mode, but up until now the double-invoked lifecycles impact both dev and prod. This is actually a good thing at Facebook, since it helps us identify potential bugs in production and we can easily limit it to only impact developers, but I think it would complicate the story for external users because of the negative performance impact.

I propose that we continue to observe the `debugRenderPhaseSideEffects` flag for dev and prod (since this impacts Facebook only) but only double-invoke for "strict" mode in dev.

Enabling this behavior greatly complicates our incremental rendering tests ([see below](https://github.com/facebook/react/issues/12089#issuecomment-360517198) so I will also be converting these to be internal so they can explicitly override the feature-flag before running. I think this is okay since the tests that break all use the noop-renderer which is not published to NPM.

### PR DESCRIPTION
**Pull request by bvaughn**
Resolves #12089

A new feature flag has been added, `debugRenderPhaseSideEffectsForStrictMode`. When enabled, `StrictMode` subtrees will also double-invoke lifecycles in the same way as `debugRenderPhaseSideEffects`.

By default, this flag is enabled for `__DEV__` only. Internally we can toggle it with a GK.

This breaks several of our incremental tests which make use of the noop-renderer. Updating the tests to account for the double-rendering in development mode makes them significantly more complicated. The most straight forward fix for this will be to convert them to be run as internal tests only. I believe this is reasonable since we are the only people making use of the noop renderer.

### CODE REVIEW

**Comment by bvaughn** [comment]
This change breaks the following tests:
* `ReactCallReturn-test`
* `ReactNewContext-test.internal`
* `ReactIncremental-test`
* `ReactIncrementalErrorHandling-test`
* `ReactIncrementalErrorLogging-test.internal`
* `ReactIncrementalReflection-test`
* `ReactIncrementalScheduling-test`
* `ReactIncrementalSideEffects-test`
* `ReactIncrementalUpdates-test`
* `ReactIncrementalTriangle-test`

Two of them are internal and so will be easy to fix. The rest of them are incremental tests, built with the (private) noop-renderer, and so should be okay to make internal-only. The only exception is `ReactCallReturn-test` which also uses the noop-renderer.

**Comment by gaearon** [comment]
>The rest of them are incremental tests, built with the (private) noop-renderer, and so should be okay to make internal-only. 

That seems a bit unfortunate to me. They describe the async behavior in detail and I intentionally worked to get the noop renderer to build in a way that this behavior is testable.

Technically this used to verifiy that our custom renderer infrastructure (which I changed noop renderer bundle to use) is working. Making those tests internal defies that somewhat.

I understand it's important to unblock this but I hope we can go back to running them on the bundles before we break something else and it becomes a lot of work again.

**Comment by bvaughn** [comment]
Hm. Interesting perspective, Dan.

It seems odd to me that we had tests (arguably some of our most complex tests) running against a production bundle of something that we never actually ship anywhere. And since this twice-invoking behavior adds _significant complexity_ it felt like the right trade-off.

> Technically this used to verifiy that our custom renderer infrastructure

Maybe we can achieve the same goal with tests that aren't so complex?

**Comment by sebmarkbage** [comment]
Testing the noop renderer seems fine for testing the custom renderer, but I think the async tests specifically is not the right way of doing that since they have all these special quirks that you wouldn't test for in user tests or maybe even experience.

**Comment by bvaughn** [comment]
> Testing the noop renderer seems fine for testing the custom renderer infrastructure, but I think the async tests specifically is not the right way of doing

Sure, but noop renderer is always async:

https://github.com/facebook/react/blob/d3b183c32326cacc29efea43ca9300a17ed4aca0/packages/react-noop-renderer/src/ReactNoop.js#L345

https://github.com/facebook/react/blob/d3b183c32326cacc29efea43ca9300a17ed4aca0/packages/react-noop-renderer/src/ReactNoop.js#L365

So any test would have to account for the double lifecycles in DEV. Granted, some of them are pretty straight forward though.

**Comment by gaearon** [comment]
I think the confusing part here is that testing custom renderer infra and testing async are two unrelated activities but they happen to be combined here.

I think both are valuable to do against the bundles:

* Testing custom renderers is important so we don’t regress there with silly mistakes.

* Testing async is important because normal ReactDOM tests don’t cover a lot of behaviors in the reconciler. If we move forward with more sophisticated compilation (or even if Rollup or GCC has a bug) we won’t catch anything that’s not in the synchronous path unless we run those tests on bundles.

**Comment by bvaughn** [comment]
Agreed.

**Pull request merged**
