### PR TITLE
Fix muted prop not being shown as an attribute for video elements

### PR DESCRIPTION
**Pull request by antoniopacheco**
## Summary

Fixes: https://github.com/facebook/react/issues/10389

## Test Plan

Currently there is an issue with jest so whenever we try to test <video muted/.> we get a
`Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering ` found on:
https://github.com/testing-library/react-testing-library/issues/470

in order to fix this bug we need to have a muted attribute in the element before we set the prop, that's why you can see the timeout. so it won't detect a change in the volume once the prop is set.

### CODE REVIEW

**Comment by atnpcg** [comment]
any love for this PR?

**Comment by iHildy** [comment]
Any hope for this PR?

**Comment by swissspidy** [comment]
bump

**Comment by vctqs1** [comment]
bump

**Comment by viclafouch** [comment]
Bummmmmmmp

**Pull request closed without merging**
