### PR TITLE
refactor: remove redundant conditional statements

### PR DESCRIPTION
**Pull request by lyhper**
duplicate conditional statements

### CODE REVIEW

**Comment by react-linter** [comment]
<details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: f6fb03edffcc5918ad2f37ed45bdc7c0c3b3d199...b4475553244a956ec2f3298fde80c5eb5120164e</p>


  
## schedule
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
schedule.development.js | n/a | n/a | 0 B | 19.17 KB | 0 B | 5.74 KB | UMD_DEV
**schedule.production.min.js** | **n/a** | **n/a** | **0 B** | **3.16 KB** | **0 B** | **1.53 KB** | **UMD_PROD**

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by NE-SmallTown** [comment]
IMO, you should not remove this check, instead, remove the topper check like [this](https://github.com/facebook/react/blob/03ab1efeb4dde9e07b93ff038c87cc4fa443abf4/packages/react-reconciler/src/ReactFiberScheduler.js#L1747)

**Comment by lyhper** [comment]
@nhunzaker done

**Comment by lyhper** [comment]
The file has been refactored, I will close this pull request. thanks🙂 @nhunzaker

**Pull request closed without merging**
