### PR TITLE
Fetch DOM node lazily for updates

### PR DESCRIPTION
**Pull request by spicyj**

### CODE REVIEW

**Comment by spicyj** [comment]
wtf hub.

**Comment by syranide** [comment]
Not sure how much we care but the argument isn't even mentioned in the docblock https://github.com/spicyj/react/blob/lazy-node/src/renderers/dom/shared/ReactDOMComponent.js#L823

**Comment by syranide** [comment]
`node = node || ReactMount.getNode(this._rootNodeID);` would lessen the noise :shrug:

**Comment by spicyj** [comment]
I don't really care but I'll update the docblock anyway.

**Comment by spicyj** [comment]
@zpao r?

**Comment by zpao** [comment]
r+

**Pull request merged**
