### PR TITLE
Fixing jQuery, Velocity compatibility

### PR DESCRIPTION
**Pull request by MichaelCereda**
this fixes https://github.com/facebook/react/issues/5296

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by MichaelCereda** [comment]
CLA signed

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by jimfb** [comment]
Potential alternate fix is https://github.com/facebook/react/pull/6710 which appears to be a superset of this PR.

**Comment by spicyj** [comment]
Closing in favor of #6710.

**Pull request closed without merging**
