### PR TITLE
Fixes autofocus does not work when the dialog has opened

### LINKED ISSUE #23301: Bug: autoFocus broken inside <dialog />
React version: 17 and 18.0.0-rc.0-next-27b569969-20220211

## Steps To Reproduce

1. render `<input /><input autoFocus />` inside `<dialog />`
2. execute the `showModal()` method of the dialog
3. you will notice that react will not set focus to the correct input element

DialogAutoFocus

Link to code example:

https://codesandbox.io/s/dreamy-meninsky-460wbr?file=/src/App.tsx

## The current behavior

In Chrome and Safari TP the element with `autofocus="true"` will receive focus.  
However the element with `autoFocus={true}` will not receive focus.

## The expected behavior

From https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus

> The autofocus [global attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) is a Boolean attribute indicating that an element should be focused on page load, or when the [`<dialog>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) that it is part of is displayed

Therefore `autoFocus={true}` should also set the focus similar to `autofocus="true"` for elements inside `<dialog />`

### PR DESCRIPTION
**Pull request by MustafaEminn**
## Summary
Fixes #23301. Dialog elements already have been rendered when the open props value has changed. 

## How did you test this change?

I have tried the dispatchEvent but that can't render properly. The important point is the input element should have autoFocus={true} property before open the dialog.

### CODE REVIEW

**Comment by MustafaEminn** [comment]
@rickhanlonii can you review this please

**Review by gaearon — CHANGES_REQUESTED** [review]
The code in CommitWork is not platform-specific and shouldn't include concepts like "dialog". Can you briefly describe what you're trying to do?

**Comment by MustafaEminn** [comment]
My purpose focus to the element which has autoFocus prop when a dialog opens. dialog is rendering on the first mount even if not visible. React is looking to elements that have autoFocus property only first mount. I look up again to children that have autoFocus property when the dialog has opened.

**Comment by MustafaEminn** [comment]
Can I do that? Where do I put begin and complete methods?
image

**Pull request closed without merging**
