### PR TITLE
Unshare not actually shared files

### PR DESCRIPTION
**Pull request by sebmarkbage**
This moves some files out of shared that are not actually shared with isomorphic. They're specific to the renderers. Some of these could be thought of as generic but are probably bad practice anyway such as forEachAccumulated.

### CODE REVIEW

**Comment by spicyj** [comment]
Isn't ReactComponentTreeDevtool shared? Otherwise good.

**Comment by sebmarkbage** [comment]
Yea, I moved ReactComponentTreeDevtool to isomorphic because it is shared.

**Comment by spicyj** [comment]
I mean shouldn't it be in src/shared? Since it is used by both isomorphic and renderers. Maybe I don't understand your folder structure.

**Comment by sebmarkbage** [comment]
This and ReactCurrentOwner are stateful modules so they need to have a single source of truth which is isomorphic. The src/shared folder is duplicated.

**Pull request merged**
