### PR TITLE
Warn when element is missing in devtool

### PR DESCRIPTION
**Pull request by spicyj**
Follow-up to #6867.

### CODE REVIEW

**Comment by spicyj** [comment]
@gaearon

**Comment by gaearon** [comment]
Thanks, can you add a test for it please?

**Comment by kujon** [comment]
Would you mind shedding some light on when exactly this warning is raised? Started getting it when doing:
```javascript
componentWillMount() {
  if (process.env.BROWSER) {
    this.context.clientOnlyProperty();
  }
}
```
and struggling to understand how to address it.

**Comment by gaearon** [comment]
It's against internal bugs in React, it's not meant for users. If you see it please file a bug with an example that reproduces it.

**Comment by adamryvola** [comment]
Hello,
I had a react project (without any warring) and today i've installed this project on friend's pc and i get too many warrings. I think it is caused by react-bootstrap. In IDE console warn is: `Warning: ReactComponentTreeDevtool: Missing React element for debugID 1 when building stack`
Here is screen of console in browser
https://drive.google.com/open?id=0BzAI-U4-wrvCbTlCV3JuazZBUHc


PS: really sorry for my english

**Comment by keyanzhang** [comment]
Hey @adamryvola,

Have you got a chance to take a look at https://fb.me/react-unknown-prop?

**Comment by gaearon** [comment]
@adamryvola The warning on your screenshot does not match the warning in your comment. If you can reproduce `Warning: ReactComponentTreeDevtool: Missing React element for debugID` please create an issue linking to a project that can reproduce it.

**Comment by adamryvola** [comment]
@keyanzhang I am reading it just right now, thanks!

@gaearon Thanks for  fast answer. You are right, these two warring are not the same. I thought they are, because there were no warrings before. When I replace react-bootstrap `<Button>` with standard `<button>`, browser console is clear and `ReactComponentTreeDevtool` warn is still there (in server console). I will try reproduce this warn in another small project and then create issue.

Thank you for help.

**Pull request merged**
