### PR TITLE
feat(devtools): add preset for open in editor url

### PR DESCRIPTION
**Pull request by moonrailgun**
## Summary

Add preset  url for feature `open in editor url`
- vscode
- jetbrain

and fix incorrected url parse problem

## How did you test this change?

image
image

### CODE REVIEW

**Comment by napiraz** [comment]
RATIO !!!!!

**Comment by moonrailgun** [comment]
Is anyone can review its pr?

**Comment by Biki-das** [comment]
> Is anyone can review its pr?

Wait a few days, React is quite a busy project, expect maintainers to come as they find time to reflect on . :-)

**Comment by moonrailgun** [comment]
sad

**Pull request closed without merging**
