### PR TITLE
Update error codes and results.json

### PR DESCRIPTION
**Pull request by flarnie**
Preparing to do an RC, just updating these files.

### CODE REVIEW

**Comment by bvaughn** [comment]
Is this what we want to do right before an RC? (Update the Yarn lockfile, that is?)

Should we maybe only update our deps (not dev deps):
```json
    "fbjs": "^0.8.9",
    "loose-envify": "^1.1.0",
    "object-assign": "^4.1.0",
    "prop-types": "^15.5.6"
```

**Comment by flarnie** [comment]
I'm not sure about how we want the Yarn lockfile updated - it's in the docs for doing releases, but we should decide what makes sense.

I'll remove that commit from this PR so we can get the error code and bundle size changes in faster.

**Comment by gaearon** [comment]
@flarnie 

Which docs are you looking at? I included different instructions about Yarn in the new guide: https://github.com/facebook/react/issues/10620. Please don't use the old instructions as a reference, they weren't right.

**Comment by sophiebits** [comment]
Agree. loose-envify doesn't matter either way for our built bundles but upgrading those four makes sense to me.

**Comment by gaearon** [comment]
Did lockfile update get lost? I don't see it in the PR now.

**Pull request merged**
