### PR TITLE
Russian translation of tips

### PR DESCRIPTION
**Pull request by ivanzotov**
- [x] Type of the Children props
- [x] Value of null for Controlled Input
- [x] componentWillReceiveProps Not Triggered After Mounting
- [x] Props in getInitialState Is an Anti-Pattern

### CODE REVIEW

**Comment by ivanzotov** [comment]
@gaearon How about review? :)

**Comment by gaearon** [comment]
@ivanzotov As I mentioned earlier, we're in the process of completely rewriting these section in #7864, and the separate "tips" top-level menu might get scrapped. We'll likely move some of that material somewhere but it's not yet clear what survives and what doesn't. Sorry about that!

**Comment by ivanzotov** [comment]
@gaearon I got it, thanks, just didn't see that PR

**Comment by gaearon** [comment]
Closing, sorry for wasted work.

We plan to use a different process from now on to make translation contributions easier and independent of core team. You can track this in #8063.

**Pull request closed without merging**
