### PR TITLE
Rename hover props in experimental event API and write unit tests

### PR DESCRIPTION
**Pull request by behzad888**
Note: this is for an experimental event API and writing tests.

 - `onHoverIn` -> `onHoverStart`
 - `onHoverOut` -> `onHoverEnd`
 - Write unit tests

### CODE REVIEW

**Comment by behzad888** [comment]
> Thank you for this contribution – it's awesome! It all looks good to me. I'm also a bit surprised to be honest that people externally are playing with this API. I'd be interested to know how it works out for you too. :)

LGTM.
I'm trying to prepare a blog about react experimental event API. In that, I want to how to use and how it works out.

**Comment by gaearon** [comment]
You'll want to be *very* clear it's completely experimental and not really usable outside of this repository yet. We might scrap the whole thing altogether.

**Comment by trueadm** [comment]
Like Dan said, this isn’t to be used right now and is likely to change in API frequently too. Furthermore, we might not even use it. I’d recommend holding off for now. :)

**Comment by behzad888** [comment]
Ok. Thank you for your response.

**Pull request merged**
