### PR TITLE
Move warnings into under DEV conditions

### PR DESCRIPTION
**Pull request by koba04**

### CODE REVIEW

**Comment by flarnie** [comment]
Thanks for doing this - I'm not sure we need that though, since the `warning` function itself is a no-op outside of `__DEV__`. See https://github.com/facebook/fbjs/blob/e66ba20ad5be433eb54423f2b097d829324d9de6/packages/fbjs/src/__forks__/warning.js#L25

If anything, the extra checks for `__DEV__` in React might be unnecessary.

**Comment by koba04** [comment]
@flarnie Thanks! I think it makes sense for dead code elimination in a production build.

**Comment by gaearon** [comment]
I'm not sure if `warning` gets automatically wrapped in `__DEV__` with a Babel plugin. I think it does but might be wrong. I don’t mind the explicitness though.

**Comment by koba04** [comment]
Thanks!

**Pull request merged**
