### PR TITLE
Move React.js -> react.js & switch to @providesModule react

### PR DESCRIPTION
**Pull request by gabelevi**
I replaced all `require('React')` with `require('react')`. I looked for occurrences of `React.js` in the codebase. I fixed the things that broke the jest and grunt tests. I'm not too familiar with this code base so please advise if you think there's something I missed.

Test plan:
```bash
grunt build
grunt test
grunt lint
npm test
```

The lint showed 15 errors. I check master and I still saw those 15 errors.

### CODE REVIEW

**Comment by zpao** [comment]
I think we should update https://github.com/facebook/react/blob/master/npm-react/react.js for consistency as well.

**Comment by gabelevi** [comment]
Good catch. Should I also update any older docs that mention capital R react? Like when grepping for `"/React[^a-zA-Z]"` I saw `var React = require('react-tools/build/modules/React');` in [this file](https://github.com/facebook/react/blob/master/docs/_posts/2013-12-30-community-roundup-13.md)

**Comment by sebmarkbage** [comment]
Not sure what this actually solves when this change is within the React package. If we switch to CommonJS, these will all become relative paths instead of providesModule, which will presumably break Flow inside React Core anyway. Where will the `providesModule React` alias go internally?

**Comment by sebmarkbage** [comment]
I guess this could be an incremental step, but to make this a magic dir CommonJS package, we shouldn't refer to our own package name internally. To avoid name conflicts with any internal aliases, we could renamed this providesModule to `ReactClassic` or something.

Then we expose this package "main" as `react`. Either through a magic dir or just an internal alias.

**Comment by gabelevi** [comment]
For typing React Core we probably don't want to use the library definition of React, but rather use what we can infer from React Core. Ideally we'd have some way to verify that the library definition matches what we see. But I'm sort of ok not solving that problem until a little later. You're right though, we will need a way to keep Flow from getting confused.

> Where will the providesModule React alias go internally?

The `providesModule React` alias will have to go somewhere that it doesn't get clobbered by the deploy. 

> I guess this could be an incremental step, but to make this a magic dir CommonJS package, we shouldn't refer to our own package name internally. To avoid name conflicts with any internal aliases, we could renamed this providesModule to ReactClassic or something.

> Then we expose this package "main" as react. Either through a magic dir or just an internal alias.

Sounds good to me

**Comment by gabelevi** [comment]
I'm not 100% sure what the status is here. Are you guys ok taking this PR or is there something you need from me?

**Comment by spicyj** [comment]
@zpao @sebmarkbage Did we want this in 0.13? Milestoning so we don't forget.

**Comment by nmn** [comment]
Any update on this??

**Comment by spicyj** [comment]
@nmn Why is this relevant to you?

**Comment by spicyj** [comment]
(Didn't mean that to sound combative – just didn't think this was causing problems for anyone and would like to know what you're experiencing.)

**Comment by nmn** [comment]
@spicyj Not relevant to me really. I had a problem with flow, and I found an issue. That issue mentioned another issue, which mentioned this issue, so I asked for updates.

**Comment by jimfb** [comment]
@spicyj Is this still on our todo list, or is this something that we don't care about / there is no reason to fix?  Can we close out the issue?

**Comment by zpao** [comment]
it's on the todo list

**Comment by gaearon** [comment]
We’re trying to close stale PRs and get better at being decisive and reviewing them quickly. I am closing because we recently created #6336 to track this, and if we decide to proceed, this PR would need significant updates anyway. Cheers!

**Pull request closed without merging**
