### PR TITLE
Issue #5839. Added onError event to the <source>

### PR DESCRIPTION
**Pull request by alunyov**
This should fix onError event for the `<source>` element.

According to this article: http://www.w3schools.com/tags/tag_source.asp `<source>` tag supports the events attributes in HTML. It's pretty close to an `` tag.

### CODE REVIEW

**Comment by gaearon** [comment]
Something happened to the PR. Do you mind cleaning it up so there’s just a single commit?

**Comment by alunyov** [comment]
@gaearon Sure, I will fix it.

**Comment by gaearon** [comment]
Hmm, this still doesn’t look right.

**Comment by alunyov** [comment]
@gaearon Sorry for that, I just pressed the wrong button :-). Now it should be fine.

**Comment by gaearon** [comment]
Tagging this as to be reviewed after 15.0 release. If everything is fine we’ll get this some time during 15.x. Thanks!

**Comment by facebook-github-bot-5** [comment]
@alunyov updated the pull request.

**Comment by alunyov** [comment]
Close it as https://github.com/facebook/react/pull/6941 has been merged.

**Pull request closed without merging**
