### PR TITLE
Route a debug path (parent node path) for use in debugging messages.  Use it in one of the warnings

### PR DESCRIPTION
**Pull request by jimfb**
Route a debug path (parent node path) for use in debugging messages.  Use it in one of the warnings (more to come in the next couple PRs - in particular, the future PR that will solve #140 for us).

### CODE REVIEW

**Comment by jimfb** [comment]
@spicyj @sebmarkbage Ping.

**Comment by jimfb** [comment]
@spicyj @sebmarkbage Ping.

**Comment by sebmarkbage** [comment]
We should pass a pointer. This won't work with re parenting and windowing reuse.

**Comment by jimfb** [comment]
Yeah, pointers are a bit complicated because you can't have a pointer to the parent instance, since stateless components won't have an instance.  And the point will become moot if we pull warnings (and related contextual tracking) into devtools before we actually implement reparenting/windowing.

**Comment by jimfb** [comment]
Ok, updated to use pointers to debug path nodes, which should be easier to update if/when we implement reparenting/windowing.  @sebmarkbage @spicyj

**Comment by jimfb** [comment]
Ping @sebmarkbage @spicyj

**Comment by spicyj** [comment]
Why not just store a pointer to the parent? This seems unnecessarily complicated.

Also, when is the parent path significantly more useful? I had developed something like this originally for the DOM nesting warning and @sebmarkbage convinced me that the owner list is equally useful.

**Comment by jimfb** [comment]
@spicyj The parent path is most useful when you have a single component that renders to non-trivial markup, and it becomes difficult to figure out exactly which element is firing.  Ideally I would give line numbers, but the full parent path is the next best thing.

**Comment by spicyj** [comment]
Maybe we should make line numbers instead then, like https://github.com/facebook/react/pull/4596.

**Comment by jimfb** [comment]
I agree, but that's a whole other can of worms.  As of today, we don't have line number information and we do have parent information.  Once source information is available, I'm happy to help migrate this to line numbers.  In the mean time, this is a valuable bit of contextual information that we can provide.

**Comment by jimfb** [comment]
Replaced by new devtools API.

**Pull request closed without merging**
