### PR TITLE
packages\react-debug-tools\src\__tests__\ReactHooksInspectionIntegration-test.js   -----> fixed code structure

### PR DESCRIPTION
**Pull request by Biki-das**
found a chunk of objects having broken structure comparing to the other objects in the same file

### CODE REVIEW

**Comment by Biki-das** [comment]
Not related to this PR,  @bvaughn , i have a query actually , i am facing these isssue , the issue is i always mess up my local repo , what will be the best way to keep my local repo in sync with the react repo, also i tried by upstreaming but whenever i do a PR after upstreaming , everything including yarn test, yarn prettier and yarn linc runs fine but after PR the circle CI build  usually fails. anything you want to suggest, i dont need step by step solutions just giving me an overall idea to approach this will be fine and enough for me. looking forward

**Comment by akgupta0777** [comment]
Best way to sync your repo is via upstream and the mistake you are doing is you are committing all your changes on single branch `main`. Every time you commit make a new branch and push it to facebook main branch.

**Comment by Biki-das** [comment]
> Best way to sync your repo is via upstream and the mistake you are doing is you are committing all your changes on single branch `main`. Every time you commit make a new branch and push it to facebook main branch.

thanks a lot

**Comment by Biki-das** [comment]
> This is automatically formatted by prettier, I'm actually surprised that we don't have a lint test to catch this. Going to close because as soon as someone with prettier configured saves this file, it will change it back.

thanks for the feedback

**Pull request closed without merging**
