### PR TITLE
yarn prettier runs a too long command for OS windows

### PR DESCRIPTION
**Pull request by lamo2k123**
fixed issue #9500

### CODE REVIEW

**Comment by gaearon** [comment]
Seems like CI integration failed, can you take a look at what happened?

**Comment by lamo2k123** [comment]
@gaearon everything is fine, I forgot to launch `yarn prettier` :)

**Comment by gaearon** [comment]
I wonder if there's any speed difference here. What does Prettier recommend?
cc @vjeux

**Comment by vjeux** [comment]
Instead of expanding the glob pattern in the call site, you can pass the glob pattern to prettier for it to expand it. This way you don't pass huge numbers of file paths through different programs.

**Comment by gaearon** [comment]
Closing per lack of response.

**Pull request closed without merging**
