### PR TITLE
Added badge for react documentation

### PR DESCRIPTION
**Pull request by rajendraarora16**
Added badge for react documentation in Readme.md

### CODE REVIEW

**Comment by nhunzaker** [comment]
This seems fine to me. @gaearon any thoughts? Is this real-estate precious?

**Comment by rajendraarora16** [comment]
@nhunzaker I apologize for the delayed response, Github never showed me the notification. I will update this ASAP.

**Comment by rajendraarora16** [comment]
@nhunzaker updated!

**Comment by nhunzaker** [comment]
Great, thanks!

**Comment by gaearon** [comment]
Sorry I missed this. I don’t feel very strongly but we were trying to avoid adding more badges in the past. The more there is, the less people look at them.

Why is it linking to Reference specifically? Is it more important than all other doc sections? Is it the entry point we want people to land on? Or did the badge just say “reference” and we made the link match it without intentionally designing this experience? 🙂

**Comment by nhunzaker** [comment]
No worries, sorry for the trouble!

> Why is it linking to Reference specifically? 

Specifically because the badge mentioned "reference" and that seemed like a reasonable entry way into the API reference. If we wanted to think about this more as the initial landing point for getting started, this probably isn't great.

We could just remove the badge if their isn't a good answer .

**Comment by gaearon** [comment]
I think I would prefer people to scroll a bit down to the Documentation header where we have links to all sections. I’m not sure I understand why having a “reference” badge is helpful but I might be wrong.

**Comment by gaearon** [comment]
I think it’s cool if it’s a common convention. Do other popular libraries do this?

**Comment by rajendraarora16** [comment]
@gaearon Thanks for your response! I have many applications on github provides the badges for documentation/reference. For e.g:
https://github.com/tensorflow/tensorflow

Since added this badge for react. Let me know if we are not good to go?

**Comment by gaearon** [comment]
In both cases above they point to the entry point of the docs. I think it’s pretty subjective but I would prefer to remove the badge as we already have plenty and they just become noise at some point. Are you worried people might miss the documentation link? We could try to solve this in some other way.

**Comment by rajendraarora16** [comment]
@gaearon Thanks for pointing me. I will remove this one badge as it slows down. I also want to add one suggestion, can we put the badges in new line instead of making in single something like below in screenshot:
Screenshot

**Comment by gaearon** [comment]
There might’ve been a reason why did we this. I don’t remember. I think it might be because otherwise GH cuts off the intro bullet point list on mobile.

**Comment by rajendraarora16** [comment]
@gaearon Thanks for confirming! I have raised a [PR](https://github.com/facebook/react/pull/12424) to remove this badge. Request you to review and merge.

Also, `npm version` and `coverage` badge are broken, looks like links are too slow. Since wanted to update the badges below:

**Npm:** `[npm version](https://badge.fury.io/js/react)`

**Coverage:** `[Coverage Status](https://coveralls.io/github/facebook/react?branch=master)`

Can I add those?

**Pull request merged**
