### PR TITLE
Move renderSubtreeIntoContainer into ReactDOMClient

### PR DESCRIPTION
**Pull request by zpao**
This is super easy but I was talking with @sebmarkbage about it as we discussed shipping addons separately.

I'm not really thrilled with this, but it's super easy so I'll let you decided what goes where and how we want to expose it.

### CODE REVIEW

**Comment by jimfb** [comment]
Does this mean we're officially supporting it now?  I thought this was a temporary hack until we figured out a proper story around portals.  Context isn't even supported yet, and this function makes no sense without `context`.

**Comment by spicyj** [comment]
Maybe that's why it has an underscore? :)

**Comment by sebmarkbage** [comment]
We're getting rid of addons so we have to put it somewhere. It doesn't make sense to have a different package since all the code is already in this one. Same with batchedUpdates. An underscore is as good as any other solution. :)

**Comment by jimfb** [comment]
Yep, ok, I didn't see the underscore and thought I might have missed some crucial decision regarding this function.  Underscored is fine by me.

**Comment by zpao** [comment]
`batchdUpdates` to DOMClient as well (I left my note on this at the office)?

**Pull request merged**
