### PR TITLE
Remove one extraneous backtick from line 116 of 'codebase-overview.md' (#8724).

### PR DESCRIPTION
**Pull request by richiethomas**
*Before* submitting a pull request, please make sure the following is done...

1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`) - we've done our best to make sure these rules match our internal linting guidelines.
6. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

### CODE REVIEW

**Comment by gaearon** [comment]
@aweary Want to run the doc syncing script?

**Comment by gaearon** [comment]
I documented the process [here](https://github.com/facebook/react/blob/master/scripts/release-manager/Readme.md) (read all sections until "Updating the Documentation" inclusively)

**Comment by gaearon** [comment]
The only caveat is that I think the tool doesn't recognize merge commits now. But you could contribute that to the release manager :-)

**Comment by aweary** [comment]
@gaearon done! I can definitely look into supporting merge commits soon 👍

**Pull request merged**
