### PR TITLE
Use const/let in more places (#11467)

### PR DESCRIPTION
**Pull request by raphamorim**
* Convert BeforeInputEventPlugin to const/let
* Convert BrowserEventConstats to const/let
* Convert ChangeEventPlugin to const/let
* Convert DOMEventPluginOrder to const/let
* Convert EnterLeaveEventPlugin to const/let
* Convert FallbackCompositionState to const/let
* Convert getEventCharCode to const/let
* Convert getEventKey to const/let

### CODE REVIEW

**Comment by gaearon** [comment]
I'd prefer if we did this in an automated way rather than by hand. I recall @forbeslindesay sent a PR with a codemod. Maybe now's a good time to get that in.

**Comment by gaearon** [comment]
Ah no that was @cpojer

**Comment by gaearon** [comment]
I'd rather revive https://github.com/facebook/react/pull/6097. I'll ask @cpojer if he's interested.

**Comment by raphamorim** [comment]
Make more sense @gaearon

**Comment by raphamorim** [comment]
I'll close it then.

**Pull request closed without merging**
