### PR TITLE
Remove disableNewFiberFeatures flag

### PR DESCRIPTION
**Pull request by gaearon**
🔥 🔥 🔥 🔥 🔥

### CODE REVIEW

**Comment by gaearon** [comment]
These tests now fail with Stack because it has a different message. I was too lazy to fix up the message for both cases since Stack is not used.

**Comment by sophiebits** [comment]
I didn't think this commit affects Stack though. I must be missing something.

**Comment by gaearon** [comment]
The flag defaulted to `false` in tests.
So the tests that explicitly wanted the new code path to run had to opt in.

The message when returning `undefined` from component is different depending on the flag.
Some tests (that didn't opt into the new code path) asserted the old message gets thrown.

Now that there is no flag, and new code path always runs, these tests assert on the wrong message.
I changed them to assert the new message.
However, the Stack code still always emits the old message.

I could write conditionals like

```js
expectDev(message).toContain(
  useFiber ?
    '...' :
    '...'
)
```

but I figured it's easier to gate the whole test (and later remove the gate).

What does this change have to do with `useFiber` flag though?
Well, now the only code path with old message is Stack one.
Fiber now always uses the new code path.

**Comment by sophiebits** [comment]
Ahhhhh sorry I missed that the message changed.

**Pull request merged**
