### PR TITLE
Silly PR to test if CodeSandbox CI works

### PR DESCRIPTION
**Pull request by acdlite**
It works! https://codesandbox.io/s/awesome-murdock-ld2fm

### CODE REVIEW

**Comment by acdlite** [comment]
Yay 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

@CompuIves This is exactly the workflow I wanted last year when you first told me about CodeSandbox CI. Thanks so much for building this and for responding to our feature requests!

**Comment by CompuIves** [comment]
Yay!!! 🎉 🎉 🎉 

This makes me really happy, I can't wait to see how this will work out for the team!

I saw that the latest build failed, I think this is related to the force push, I'll take a look together with Bogdan what this could be!

**Comment by lbogdan** [comment]
I don't exactly get what happened, as replaying the GitHub pull request webhook (so with the same payload) just worked. 🤷‍♂️ Anyway, I'll keep an eye on it, in case it happens again.

**Comment by lbogdan** [comment]
@sebmarkbage We also just deployed preventing building PRs that don't have a CodeSandbox CI config, like it happened here: https://ci.codesandbox.io/status/facebook/react/pr/17225/builds/745 .

**Pull request closed without merging**
