### PR TITLE
Add React Riot hackathon

### PR DESCRIPTION
**Pull request by sakinac**
React Riot is the first online worldwide hackathon for React! No cost to enter and teams can win some cool prizes. It's a community event to build the best React app in 48 hours.

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`).
6. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run prettier`).
7. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
8. If you added or removed any tests, run `./scripts/fiber/record-tests` before submitting the pull request, and commit the resulting changes.
9. If you haven't already, complete the CLA.

### CODE REVIEW

**Comment by nhunzaker** [comment]
Awesome. Thanks!

**Comment by gaearon** [comment]
Sorry I didn't chime in before. I'm not sure about this one—it's not a conference, but the page is specifically for conferences. If we merge this hackathon, then everybody doing React hackathons will send PRs, and the conferences will drown in the list. Could you please revert?

(The hackathon itself looks great! Just probably not fitting for this page.)

**Comment by nhunzaker** [comment]
No problem at all! That's good to know. I'll send up a revert commit.

**Comment by gaearon** [comment]
No worries—sorry I didn’t catch it earlier. I meant to comment and forgot.
I hope this doesn’t discourage you from merging other PRs.

@sakinac Sorry about the confusion too! Maybe in the future we’ll have a more appropriate page for this, and we can put it there.

**Comment by sakinac** [comment]
Ok thanks anyways. Hoping for another page soon where these things could be listed! :)

**Pull request merged**
