### PR TITLE
Fix missed warning when passing a function (issue 16573)

### PR DESCRIPTION
**Pull request by simbathesailor**
This PR fixes: [https://github.com/facebook/react/issues/16573](https://github.com/facebook/react/issues/16573).

1. Added one more visitor function to handle expressions.
2. Added test cases for the same

I have followed all the pre requisites to create this pull request. It's my first PR to the Reactjs . . Putting it in PR to get further feed back.Please let me know the problems if any with this pr, so that i can fix them.
Thanks

### CODE REVIEW

**Comment by threepointone** [comment]
Thanks for this! I'll review it later this week

**Comment by simbathesailor** [comment]
@threepointone Let me know, if this pr makes sense when you get time. I can work on reviews comments if done.

**Comment by simbathesailor** [comment]
> Thanks for the PR. This duplicates the logic quite a bit but I don't see a compelling reason to do it. Can you please reuse the existing code where possible?

Thanks , Let me revisit it and remove the duplicate code.

**Comment by simbathesailor** [comment]
@gaearon I removed some duplication. Let me know , what else can be done here with this pr.  If you have any specific advice, I can discuss and implement the same. 
Thanks

**Comment by gaearon** [comment]
Hey! I tried to merge it in but there were many more cases I wanted to handle better, so I ended up going with a different approach: https://github.com/facebook/react/pull/18435. I wouldn't have started work on this without your PR though, so thank you for that!

**Comment by simbathesailor** [comment]
Hey no problem Dan . I will.surely see your pr and try to learn what you did. I will try to fix other issues on reactjs in future.

**Comment by gaearon** [comment]
Yes please! :D

**Pull request closed without merging**
