### PR TITLE
shallowEqual: bail if either argument is falsey

### LINKED ISSUE #3316: Calling setState without getInitialState throws when using PureRenderMixin
Without `getInitialState`, `this.state` is `null`, which causes this line in `shallowEqual` to throw.

```js
if (objB.hasOwnProperty(key) && !objA.hasOwnProperty(key)) {
```

Fix is to make shallowEqual bail if either argument is falsey (or not an object if we want to be very safe).

### PR DESCRIPTION
**Pull request by ianobermiller**
Also add some unit tests.

Fixes #3316

### CODE REVIEW

**Comment by jsfb** [comment]
I like this PR, especially since it is predominantly adding unit tests.  I'm going to mark it as accepted, but pinging @spicyj just in case I missed something (the semantics of javascript falsey expressions are subtle).  We are in a code-freeze for the 0.13 release, so ETA for a merge is a week-ish.

**Comment by syranide** [comment]
This seems weird to me I think, why do we want this behavior?

**Comment by spicyj** [comment]
@syranide Why not?

**Comment by jsfb** [comment]
@syranide returning false (if one object is null and the other is not) seems more correct than throwing an unexpected exception.

**Comment by syranide** [comment]
@jsfb Ok, after reading it a bit more I'm kind of OK with it, but it's not super obvious, I'd say it could make more sense to make it `objA == null || objB == null` for clarity? `shallowEqual(1, 2) === true`. `props` and `state` can indeed be non-objects too, although perhaps that is being restricted.

**Pull request merged**
