### PR TITLE
Update Flow

### PR DESCRIPTION
**Pull request by gaearon**
See individual commits.

I had to explicitly annotate ReactDOM host config because otherwise the inference wasn’t good enough.

I actually kind of like it this way because in the past it was often unclear where the inference failed.
Now it’s explicit.

I can update other renderers too if you want but this is enough to get it passing.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Annotating the host config is a no-go imo. Updating renderers downstream that way is such a pain to maintain since the generic list is so big and difficult to update. Especially when you get it wrong

It's probably an indicator that something is not properly expressed in the host config itself. I'd like to look at that a bit further. I'd rather express that we'll in the host config types and solve it for all downstreams.

**Comment by gaearon** [comment]
I spent an hour and a half there and couldn't get it to work. If you can, please do 😛 

The most I could narrow it down is that typing `getNextHydratableSibling` and `getFirstHydratableChild` as returning `any` cuts each ~8 issues (with both going down to 0). Something's up with those `I | CI` types and how they flow into everything else.

**Comment by gaearon** [comment]
>Annotating the host config is a no-go imo. Updating renderers downstream that way is such a pain to maintain since the generic list is so big and difficult to update. Especially when you get it wrong

I disagree. I found the opposite to be true: if there's a subtle error in some return type, the messages are so cryptic I need to go through the whole file and check every generic type by hand anyway. I prefer to see it explicitly and thus aid Flow in better messages. Since if I create a renderer I want to be aware of the exact contract I'm implementing, and my types as well.

**Comment by gaearon** [comment]
Rolled into https://github.com/facebook/react/pull/11493.

**Pull request closed without merging**
