### PR TITLE
Fix suspense replaying forwardRefs

### LINKED ISSUE #26385: Bug: Component is not a function when using Suspense and forwardRef
React version: 18.3.0-next-3ba7add60-20221201

## Steps To Reproduce

I haven't been able to create a minimal example yet, if needed I will spend more time on it. However, it only seems to occur when Suspending components rerender in a specific order.

## Description

The `Component is not a function` error is thrown when using Suspense and forwardRef together in a specific way.

It seems like react-reconciler doesn't properly handle forwardRefs in either `renderWithHooksAgain`, `replaySuspendedComponentWithHooks`, `replayFunctionComponent` or `replaySuspendedUnitOfWork`. The `Component` variable is not a function in this case, but a `{ $$typeof: Symbol(react.forward_ref), render: (props, ref) => any }`. `renderWithHooksAgain` tries to execute `Component(props, secondArg)`, which throws this error.

I'm not too familiar with React internals, if you can tell me how to trigger this codepath I can make a minimal reproduction more easily.

Screenshot 2023-03-14 at 14 55 13

### PR DESCRIPTION
**Pull request by hansottowirtz**
@acdlite Fixes #26385

### CODE REVIEW

**Comment by hansottowirtz** [comment]
@acdlite Should be good to go apart from maybe the location/name/content of the test, let me know.

**Comment by hansottowirtz** [comment]
Please don't merge yet, this also caused #26419. I will update the PR.

**Comment by hansottowirtz** [comment]
Gonna need some help here, `replayFunctionComponent` is passing `context` to `replaySuspendedComponentWithHooks`'s `secondArg` argument. However `context` seems to be an empty object, and I'm not sure where to get the ref from. I added a failing test.

**Comment by eps1lon** [comment]
Can you rebase that onto master? Then CI should run

**Comment by hansottowirtz** [comment]
I rebased, but it seems like there's some kind of circleci config missing.

**Comment by hansottowirtz** [comment]
Running the test locally still fails. The underlying issue is quite clear (suspense replay logic for ForwardRef was just not implemented) but I'm not sure how to fix it. 
@acdlite sorry for pinging again, but would it be possible to take another look at this?

**Comment by hansottowirtz** [comment]
I took another look at it and I think I fixed it, so it should be good to go.

**Comment by eps1lon** [comment]
Try creating a branch and request a pull request from there instead of using your `main` branch. That may be why CircleCI is having issues.

**Comment by hansottowirtz** [comment]
Replaced by #26535

**Pull request closed without merging**
