### PR TITLE
Update Rollup

### PR DESCRIPTION
**Pull request by gaearon**
Seems like we'll need to do this to get a new option that was added in 0.43. I updated to 0.49 as it was out for a while, and doesn't have the regressions from more aggressive 0.50.

The size has *increased* but the reason seems to be mostly duplication of `'use strict'` that's now added in the bundle many times (for every module?). I don't understand why yet. We'll get rid of them with ES modules though (I think) so maybe not a big deal.

screen shot 2017-11-02 at 01 03 32

screen shot 2017-11-02 at 01 05 17

Diff: https://gist.github.com/gaearon/8de8c9d5f47c76061a900e16c938872c

### CODE REVIEW

**Comment by gaearon** [comment]
It's not great to inflate bundle size because of it though. I'll land it only if I verify the ES modules PR gets rid of it when laid on top.

**Comment by nhunzaker** [comment]
Ah, that was where I was at. That the ES Module update would collapse the closures around the CJS modules and Uglify (or Rollup) would clean up.

Assuming those assumptions are correct...

**Comment by gaearon** [comment]
It doesn't help by itself, no. But I was hoping it will let us delete `use strict` in *our* source (since it's implicitly strict in modules) and hopefully there'll then be nothing for Rollup to duplicate.

**Comment by gaearon** [comment]
Regarding use strict, seems intentional: https://github.com/rollup/rollup/pull/1591.

Maybe we should just do a pass and remove it ourselves since we know the whole bundle has it anyway.

**Comment by nhunzaker** [comment]
Sounds laborious, but maybe just a project replace. Okay if I take a stab? Should I base that off of this branch, or the ES Module branch?

**Comment by nhunzaker** [comment]
Sent out a PR with a basic script to do this en-mass, happy to pick it up again tomorrow. https://github.com/gaearon/react/pull/2

**Pull request merged**
