### PR TITLE
Experimental event API: Focus module

### PR DESCRIPTION
**Pull request by behzad888**
Note: 
determine eventData and pointerType 
```
{
  pointerType: 'mouse' | 'pen' | 'touch' | 'keyboard'
}
```

Ref #15257

### CODE REVIEW

**Comment by matthargett** [comment]
What about ‘gaze’ for AR/VR?l, and directional pad for TV remote/game controller?

**Comment by necolas** [comment]
We're still figuring things out. Not sure it's worth your time submitting PRs for experimental APIs that are in flux.

**Comment by jhampton** [comment]
> What about ‘gaze’ for AR/VR?l, and directional pad for TV remote/game controller?

Agreed @matthargett .  At the risk of being a pedant, perhaps a `dwell` or `hover` could be an analog for the same intent?

**Comment by necolas** [comment]
Thanks for taking interest in this work. But I'm closing this PR as master has diverged quite a lot and we're still figuring out event data internally. This approach doesn't work either as native `focus`/`blur` events do not contain `pointerType` information on the event object.

**Pull request closed without merging**
