### PR TITLE
Fix travis after_script

### PR DESCRIPTION
**Pull request by brigand**
Way at the bottom of the travis output:

```
1571: curl: (26) couldn't open file "build/react.tgz"
```

This seems to be broken since 12c9fee94ed97dee1ae0dad701c03d4fc14ca0a7

I'm guessing the server this posts to also needs to be updated, so this PR is mostly informational.

### CODE REVIEW

**Comment by spicyj** [comment]
I think the server doesn't actually need to be changed. Can we move this script into the main script section (either still as the current `TEST_TYPE=test` or maybe with a new `TEST_TYPE=build`) with `set -e` like build_website has so that we fail the build next time this happens?

**Comment by brigand** [comment]
Changes:
 - moves after_script to script
 - adds `set -e`
 - creates a seperate matrix 'build'

**Comment by spicyj** [comment]
Looks pretty good. What do you think about combining it into the existing if statement?

```
elif [ "$TEST_TYPE" = build ]; then
  if ["$SERVER"]; then
    ...
  fi
else
```

Right now it runs grunt build twice (which isn't the end of the world, just a little clowny).

**Comment by brigand** [comment]
Heh, completely missed that. Updated.

**Comment by spicyj** [comment]
Looks good, will merge if Travis passes. Thanks!

**Comment by spicyj** [comment]
curl: (26) couldn't open file "build/packages/react-codemod.tgz"

**Comment by spicyj** [comment]
I'll just drop that one.

**Pull request merged**
