### PR TITLE
Re-enable UMD build for TestUtils

### LINKED ISSUE #11111: Consider providing a UMD build for TestUtils again
I noticed we stopped providing it, but a bunch of fiddles for old bugs use it.
I wonder if we should add it back, e.g. as `react-dom-test-utils.development.js`.

Let’s hear what people have to say.

### PR DESCRIPTION
**Pull request by andydavies92**
Fixes #11111.

### CODE REVIEW

**Comment by gaearon** [comment]
Have you verified they work?

**Comment by andydavies92** [comment]
I have, our test suite works again now and all our tests pass. Thanks for the swift responding today, been a huge help!

**Comment by gaearon** [comment]
Awesome, thanks.

**Comment by nhunzaker** [comment]
@gaearon sorry, haha. I should have said something to confirm this. I pulled this into the test fixtures and was able to manipulate React inputs:

change

**Pull request merged**
