### PR TITLE
add Portal support to React.Children calls

### PR DESCRIPTION
**Pull request by MatteoVH**
Solves #11373

Not sure if Portals should expose their children to the `React.Children` call or just the portal itself. Right now it's set up to expose the portal.

### CODE REVIEW

**Comment by gaearon** [comment]
Now that I think about it, maybe this is actually a breaking change and we can't get it in. Since existing Children users don't assume portals will be there (with different object shape).

**Comment by MatteoVH** [comment]
Well, the `React.Children` documentation says:

> Invokes a function on every immediate child contained within children

And since Portals are included in the `instance.children` data structure I'd argue that this is a bug that should be fixed, not a breaking change. Right now `React.Children` errors when a Portal is inside of the `children` passed into it.

```
    Invariant Violation: Objects are not valid as a React child (found: object with keys {$$typeof, key, children, containerInfo, implementation}). If you meant to render a collection of children, use an array instead.null

      at invariant (node_modules/fbjs/lib/invariant.js:42:15)
      at traverseAllChildrenImpl (packages/react/src/ReactChildren.js:200:25)
      at traverseAllChildren (packages/react/src/ReactChildren.js:234:10)
      at Object.forEachChildren [as forEach] (packages/react/src/ReactChildren.js:286:3)
      at Object.<anonymous> (packages/react/src/__tests__/ReactChildren-test.js:64:20)
```

That being said, I'm still not that knowledgable in this code base, so I understand if you think differently.

**Comment by gaearon** [comment]
Oh I assumed we skip over it. In this case it seems fine to make this work.

Maybe it'd be nice if we also released https://github.com/facebook/react/pull/11279 with this. So that people have a way to check if something is a portal when iterating over children.

**Comment by MatteoVH** [comment]
Yeah, good idea! I agree. I was hesitant to expose `Portal`s right to the React.Children call because I wasn't sure how to differentiate them from other components, but that seems like a good way to solve that.

**Comment by gaearon** [comment]
Let's also support `Call` and `Return` in a followup PR, if you'd like to send one?

**Comment by MatteoVH** [comment]
Great, I'll take care of that!

**Pull request merged**
