### PR TITLE
Refactor object_assign

### PR DESCRIPTION
**Pull request by iam-frankqiu**
## Summary

[According to the benchmark](https://github.com/sindresorhus/object-assign/blob/master/bench.js). The assign function is better performance than the `object. assign` function. I use an assign function to replace the `object-assign` module. It can lessen the dependency of `react`. make it more stable. I hope it can be zero dependencies finally. 

## Test Plan
All tests have been passed.

### CODE REVIEW

**Comment by robertpiosik** [comment]
I'm not sure but it could be here because of IE11.

**Comment by iam-frankqiu** [comment]
> I'm not sure but it could be here because of IE11.

I think the function might have made the compatibility for IE11.

**Comment by robertpiosik** [comment]
> > I'm not sure but it could be here because of IE11.
> 
> I think the function might have made the compatibility for IE11.

Yes it does but for example doesn't use native assign when available as [object-assign implementation](https://github.com/sindresorhus/object-assign/blob/master/index.js).

You will likely end up copying object-assign lib into the codebase to avoid having additional dependency and I could agree on that having in mind how small this piece of code is.

**Comment by rickhanlonii** [comment]
Thanks for your work, but these benchmarks for an isolated function without context are often [misleading](https://mrale.ph/blog/2014/12/24/array-length-caching.html). Happy to revisit if you can show that this function is the bottleneck in this code.

**Pull request closed without merging**
