### PR TITLE
Update readme to latest React description

### PR DESCRIPTION
**Pull request by sotojuan**
Just copied the stuff from #7012 to the readme. Also deleted the line about React Native since it'd be redundant.

Let me know if I need to fix anything!

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by sotojuan** [comment]
Signed!

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by zpao** [comment]
Thanks for catching this :)

We followed up with a bit more wordsmithing in #7022. Could you update to pick that up too?

**Comment by sotojuan** [comment]
Done!

**Comment by facebook-github-bot-5** [comment]
@sotojuan updated the pull request.

**Comment by jimfb** [comment]
Thanks!

**Pull request merged**
