### PR TITLE
ReactTestInstance to expose toJSON() method for focused snapshots

### LINKED ISSUE #14539: reactTestInstance.toJSON() serializer
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

`ReactTestInstance` objects cannot currently be serialized to JSON, which prevents them from being used with Jest's `toMatchSnapshot` when wanting to capture a partial tree snapshot

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

```js
const testRenderer = TestRenderer.create(<MyComponent />)
const testInstance = testRenderer.root
const subComponent = testInstance.findByType('SubComponent')
expect(subComponent).toMatchSnapshot()
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

The latest version. I've checked the source code, and it may just be a case of exporting this function: https://github.com/facebook/react/blob/master/packages/react-test-renderer/src/ReactTestRenderer.js#L79-L121

### PR DESCRIPTION
**Pull request by mdjastrzebski**
## Summary

Allow calling `toJSON` on any `ReactTestInstance` in order to be able to make focused snapshots when writing tests using React Test Renderer or [React Native Testing Library](https://github.com/callstack/react-native-testing-library/).

Currently Test Renderer only exposes parameterless `toJSON()` as a result to `ReactTestRenderer.create()` function call but that function can only output whole component tree, which frequently result in very long snapshots that are hard to work with. 

Additionally, we plan to use this new function to improve implementation of various internal elements from React Native Testing Library, like `getByText` query algorithm, focused `debug()` function, etc.

This PR adds `toJSON()` method to `ReactTestInstance` class, so that users can generate JSON tree for any node. Implementation works by calling internal `toJSON` method if given node is host component, otherwise it recursively calls `toJSON()` on its children and returns collected JSON trees as array.

Resolves #14539

## How did you test this change?

I've added additional assertions to all relevant `ReactTestRenderer-test.internal.js` tests. The new assertions verify that `renderer.root.toJSON()` output is the same as `renderer.toJSON()` output. These tests cover different component tree structures and lifecycle changes.

### CODE REVIEW

**Comment by gaearon** [comment]
On the web, we've moved away from recommending the test renderer, and instead recommended to query the native tree. I wonder if instead of expanding the API surface of the Test Renderer, whether we've considered to do something similar on RN. I don't mean literally running Android/iOS, but more like whether we can expose something on the RN tree level and use that as the way forward. We've been adding some test selector APIs (https://github.com/facebook/react/pull/18607) which aren't used anywhere yet but I think they should also (?) work on RN.

**Comment by mdjastrzebski** [comment]
@eps1lon I've added tests for more complex tree structure with mixed host & composite elements, re-using existing arrangement from traversal tests. I used `toEqual` matcher instead of `toMatchSnapshot/InlineSnapshot` to be consistent with existing root-level `toJSON()` tests.

@gaearon sounds like an interesting idea to consider, yet quite complex one, as its appears to work on lower level of abstraction than Test Renderer. One aspect that bothers me though is the "experimental" status of these queries. Will research more on that, and discuss with other RNTL maintainers. 

Meanwhile, I would argue that merging this PR would still benefit the existing RN projects using RNTL/Test Renderer with immediate benefit of focused snapshot testing. Using Test Renderer is currently the main solution for writing component & TL-style integration tests in RN world, with a lot of projects being heavily invested in creating their automated tests. While the cost is relatively minor addition to Test Renderer package.

**Comment by gaearon** [comment]
> One aspect that bothers me though is the "experimental" status of these queries

It's implemented. The only reason they're called experimental is because we never deployed or exposed them anywhere so they're just... kind of there.

**Comment by thymikee** [comment]
@gaearon is there any recommendation of moving from react-test-renderer to test selector API? Some plans to deprecate it maybe? If you could confirm whether this approach works with RN or not, that would be great 👍🏼

**Comment by mdjastrzebski** [comment]
@eps1lon I've added more tests for `toJSON()` method as you requested. Is there anything more I can do/change/implement to move forward this PR?

**Comment by mdjastrzebski** [comment]
It's me again, I wanted to check with the React team, if this PR has chances to move forward.

To give you some more context, React Test Renderer is the primary solution used for testing in the React Native ecosystem, so while it might seem a bit odd to use in on the web, there are a lot of RN apps that use it directly or through React Native Testing Library, which I maintain, to provide solid integration & component test coverage. This PR would really bring value to RN space. 

I believe that having `toJSON()` implementation inside React Test Renderer is the best place as it uses the internal fiber APIs, which are encapsulated through TestRenderer and ReactTestInstance types.

@eps1lon, @gaearon pls help

**Comment by stevehanson** [comment]
Curious if there has been any movement on this. I'm a React Native developer, and these changes would be a huge benefit to my testing workflow if this were merged and React Native Testing Library were able to take advantage of this. Thanks all!

**Comment by brittanyvaldez** [comment]
would also like to see this implemented

**Comment by mdjastrzebski** [comment]
bump

**Pull request closed without merging**
