### PR TITLE
Fix "null" instead of the component stack in a warning

### PR DESCRIPTION
**Pull request by gaearon**
Fixes https://github.com/facebook/react/issues/10831.

(Note: the warning itself is still legit. This just fixes it to print the component stack instead of `null` in some cases.)

See individual commit messages for more info on what we did wrong and why this helps.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
There are so many places this gets reset. I have no confidence in whether this was needed or not and how it's supposed to work. 😕

**Comment by sebmarkbage** [comment]
Are there other cases this could be `null`? Shouldn't we print a better message than "null" incase it gets to be null.

**Comment by gaearon** [comment]
Okay, I can restructure it a bit to make it clearer. I think it's actually not complicated, but the `unstable_renderIntoSubtree` special case makes it confusing.

**Comment by gaearon** [comment]
Why don't you just trust me, Sebastian

**Pull request merged**
