### PR TITLE
Update AUTHORS for 0.14

### PR DESCRIPTION
**Pull request by zpao**
We're getting close to that time of the release cycle so time to update the authors. If I mentioned you below, it would be good to hear if I made the right decision (either selecting an email address or name) or if you'd like something changed.

I'll run this all again right before we ship to catch anybody else that comes in. But as of right now we have *186* new names since we cut 0.13. Thank you to all of you who have contributed over the past few months.

* * *

### I pulled name from your GH profile. Is that ok?
- [x] @Wildhoney
- [x] @codesuki
- [x] @oluckyman
- [x] @mheiber (well, I figured it out from your email address)
- [x] @katzoo
- [x] @himkt
- [x] @eriklharper (ditto on email address)
- [x] @Smert

### Your names mostly match your GH username. Would you like to use a different name? (non-latin characters ok!):
- [ ] @Youmoo
- [x] @yiminghe
- [x] @xmo-odoo 
- [x] @thorn0
- [x] @sugarshin
- [x] @matchu
- [x] @lili21
- [x] @laiso
- [x] @jiyeonseo
- [x] @iamdoron
- [x] @wibud
- [x] @mbrookes
- [x] @zhangjg
- [x] @jw-00000

### You had commits from multiple email addresses. Are you ok with email address I mapped to (first one in `.mailmap`)?
- [x] @AnSavvides
- [x] @bhamodi
- [x] @jeffchan
- [x] @KevinTCoughlin
- [x] @Yeti-or
- [x] @mmoss 
- [x] @mihaip
- [x] @MichelleTodd
- [ ] @undernewmanagement

### CODE REVIEW

**Comment by himkt** [comment]
:+1:

**Comment by bhamodi** [comment]
Thanks for doing this @zpao. I'd prefer to use my uwaterloo email address because I'll be losing the optimizely email address after my internship ends.

**Comment by KevinTCoughlin** [comment]
:+1: first e-mail listed (gmail) is fine, ty

**Comment by matchu** [comment]
Ya know what? You've inspired me to finally attach my actual identity to this Github account. What a day!

Let's use the name "Matt Dunn-Rankin" for me, please. I've also made mdunnrankin@gmail.com the new primary email address on this Github account, so that's probably the best contact address for me :)

Thanks! It's always excited to be listed as an author for a two-word contribution xD

**Comment by codesuki** [comment]
:+1: 
Thank you for doing this! Must be tiresome work :)

**Comment by laiso** [comment]
:+1: & :clap:

**Comment by sugarshin** [comment]
:ok: :+1:

**Comment by Yeti-or** [comment]
:+1:

**Comment by Wildhoney** [comment]
Thanks! All good :+1:

**Comment by thorn0** [comment]
Please change my name to Georgii Dolzhykov. Thanks.

**Comment by oluckyman** [comment]
:+1:

**Comment by syranide** [comment]
@zpao Lots of duplicates.

**Comment by xmo-odoo** [comment]
If you could use "Xavier Morel" for me that'd be great. Thanks.

**Comment by Smert** [comment]
OK. Thank

**Comment by katzoo** [comment]
It's fine, thanks! :+1:

**Comment by yasaricli** [comment]
:+1:

**Comment by mmoss** [comment]
(y)

**Comment by zpao** [comment]
Thanks for the heads up about the dupes @syranide. I only found a couple obvious ones (dupe name or dupe email) with https://gist.github.com/zpao/788bca0a4ea29b703b8c, but let me know if there were others you saw. "A bunch" implies to me that you might have seen more than 3.

Let me know if I made good choices!
- @mihaip
- @MichelleTodd
- @undernewmanagement

**Comment by MichelleTodd** [comment]
yep, first email is good!

**Comment by iamdoron** [comment]
:+1:

**Comment by AnSavvides** [comment]
Thanks @zpao - `asavvides@twitter.com` will do the trick :)

**Comment by mheiber** [comment]
(y) thanks!

**Comment by mheiber** [comment]
:+1: thanks!

**Comment by mmoss** [comment]
Can I possibly get <MMoss@cainc.com> <mmoss@users.noreply.github.com> (lines ~84 & 85) removed from the list? One was just the internal-github email response address, and the other is an internal corporate address. Thanks!

**Comment by mihaip** [comment]
:+1:

**Comment by jiyeonseo** [comment]
Change mine to "Jiyeon Seo" :+1:

**Comment by zpao** [comment]
@mmoss those are in hie maul

**Comment by zpao** [comment]
Ughh mobile is hard…

@mmoss those are in there to map the commits with those email addresses back to a single entry with the correct email address in the authors file

**Comment by mmoss** [comment]
@zpao realized that before I had a chance to delete my comment... sorry! (pretty obvious).

**Comment by syranide** [comment]
@zpao 

```
Alex Pien <alexpien@gmail.com>
Alex Pien <alexpien@gmail.com> <pien@pien-mbp.dhcp.thefacebook.com>
Alex Pien <alexpien@gmail.com> <pien@pien-mbp.local>
Andreas Savvides <asavvides@twitter.com> <AnSavvides@users.noreply.github.com>
Andreas Savvides <asavvides@twitter.com> <andreas@nibbli.com>
Ben Alpert <ben@benalpert.com> <balpert@fb.com>
Ben Alpert <ben@benalpert.com> <spicyjalapeno@gmail.com>
Christoph Pojer <christoph.pojer@gmail.com>
Christoph Pojer <christoph.pojer@gmail.com> <cpojer@fb.com>
Daniel Gasienica <daniel@gasienica.ch> <daniel@fiftythree.com>
Daniel Gasienica <daniel@gasienica.ch> <dgasienica@zynga.com>
Jeff Morrison <jeff@anafx.com> <Jeff@anafx.com>
Jeff Morrison <jeff@anafx.com> <jeffmo@fb.com>
Jeff Morrison <jeff@anafx.com> <lbljeffmo@gmail.com>
Jim Sproch <jsproch@fb.com>
Jim Sproch <jsproch@fb.com> <jsfb@github>
Jordan Walke <jordojw@gmail.com>
Jordan Walke <jordojw@gmail.com> <jordanjcw@fb.com>
Murray M. Moss <murray@mmoss.name> <MMoss@cainc.com>
Murray M. Moss <murray@mmoss.name> <mmoss@users.noreply.github.com>
Pete Hunt <floydophone@gmail.com>
Pete Hunt <floydophone@gmail.com> <pete.hunt@fb.com>
Pete Hunt <floydophone@gmail.com> <pete@instagram.com>
Pete Hunt <floydophone@gmail.com> <phunt@instagram.com>
Petri Lievonen <plievone@cc.hut.fi>
Petri Lievonen <plievone@cc.hut.fi> <petri.lievonen@tkk.fi>
Steven Luscher <react@steveluscher.com> <github@steveluscher.com>
Steven Luscher <react@steveluscher.com> <steveluscher@instagram.com>
Steven Luscher <react@steveluscher.com> <steveluscher@users.noreply.github.com>
Vasiliy Loginevskiy <Yeti.or@gmail.com>
Vasiliy Loginevskiy <Yeti.or@gmail.com> <yeti-or@yandex-team.ru>
Vjeux <vjeuxx@gmail.com>
Vjeux <vjeuxx@gmail.com> <vjeux@fb.com>
```

```js
var people = [];
var data = `...authors...`;
data.split('\r?\n').forEach(function(line) {
  var name = line.split('<')[0];
  people[name] = line;
});
for (var key in people) {
  console.log(people[key]);
}
```

If you want to automate it :)

**Comment by lili21** [comment]
:+1: Thanks

**Comment by yiminghe** [comment]
:+1:

**Comment by wibud** [comment]
:+1:

OK, Thanks~

**Comment by zpao** [comment]
@syranide That's the `.mailmap`, it needs to be duplicated. Standalone lines (eg `Alex Pien <alexpien@gmail.com>`) make sure commits with the same email but different names get mapped to a single name. The lines with multiple email addresses make sure commits that were done with the 2nd email are mapped to the first one. Here's what happens when I remove his entries: https://gist.github.com/zpao/78a447ed1a26d37bf598

**Comment by syranide** [comment]
@zpao Oh :)

**Comment by mbrookes** [comment]
Um, uh - really don't think my "contribution" warrants a mention! Name is good in any case.

**Comment by zpao** [comment]
Every bit helps!

**Comment by zhangjg** [comment]
:+1: 

OK, and thanks!

**Comment by bhamodi** [comment]
Ship it! :shipit:

**Comment by jeffchan** [comment]
:+1: my email address looks good!

**Comment by jw-00000** [comment]
:+1:

**Comment by eriklharper** [comment]
@zpao username and email is correct.

**Comment by zhangjg** [comment]
@zpao Is there some things wong using my GH name zhangjg?

**Comment by zpao** [comment]
Nothing wrong, just wanted to give the opportunity to use something else if
you wanted!

**Comment by Youmoo** [comment]
:+1:  thanks

**Comment by undernewmanagement** [comment]
whatever you have for me is good!

**Pull request merged**
