### PR TITLE
Disable coverage on Travis

### PR DESCRIPTION
**Pull request by spicyj**
cc @zpao

### CODE REVIEW

**Comment by zpao** [comment]
It doesn't look like it worked… but do whatever it takes

**Comment by facebook-github-bot-7** [comment]
@spicyj updated the pull request.

**Comment by gaearon** [comment]
It used to work 😞 What happened?

**Comment by spicyj** [comment]
¯\_(ツ)_/¯ want to dig into it?

**Comment by keyanzhang** [comment]
Last time I checked, the `./coverage` folder contains nothing after running `jest --coverage`. It might be related to https://github.com/facebook/jest/issues/433

**Comment by keyanzhang** [comment]
Looking at travis logs, it seems that the coverage stopped working after #6620. 
If I remove `'--runInBand'` from our [grunt task](https://github.com/facebook/react/blob/master/grunt/tasks/jest.js#L77) then it generates coverage correctly. Am I on the right path @zpao @cpojer? :)

**Comment by spicyj** [comment]
That sounds believable. I think not using runInBand was making the tests flakier. Maybe because of the extra memory overhead? Not sure. So the issue is that jest might not support coverage with runInBand properly. I haven't looked into it at all, but that might not be too hard to fix.

**Comment by keyanzhang** [comment]
Yeah, Jest doesn't generate coverage when used with runInBand.

**Comment by cpojer** [comment]
That is weird and seems like a bug in Jest. It is probably a silly thing that's easy to fix.

**Comment by zpao** [comment]
Going to bring this over to 15-stable. We already don't run coverage there but want to try to keep these in sync.

**Pull request merged**
