### PR TITLE
v16.8.4 [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by bvaughn**
Let CI build a release candidate for v16.8.4

This branch was created [following our documented patch release process](https://github.com/facebook/react/blob/master/scripts/release/README.md#creating-a-patch-release). Specifically, I included the following changes:
```sh
git checkout -b 16.8.4 v16.8.3
git cherry-pick 8c19665 # package.json versions
git cherry-pick 4186952 # hooks order bug-fix
```

### CODE REVIEW

**Comment by gaearon** [comment]
If you do a release pls don't overwrite ESLint plugin with version from cherry pick branch since that would undo the changes I already released.

**Comment by bvaughn** [comment]
> If you do a release pls don't overwrite ESLint plugin with version from cherry pick branch since that would undo the changes I already released.

Oh gosh. Good point. Uh... I could either mark that package `private` or (probably better) cherry pick its commits into this branch in case we need to do a future patch release. Preference?

**Comment by acdlite** [comment]
Can you put this in draft mode so we don't accidentally merge it? :D

**Comment by bvaughn** [comment]
CI is failing because of something to do with sizebot:
screen shot 2019-03-05 at 2 49 49 pm

[react.zpao.com is returning an error](http://react.zpao.com/builds/master/_commits/29b7b775f2ecf878eaf605be959d959030598b07/results.json) for commit [29b7b77](https://github.com/facebook/react/commit/29b7b775f2ecf878eaf605be959d959030598b07). Fortunately this happens _after_ the CI artifacts have been stored, so I've been able to publish a canary from this PR (which excludes the ESLint package).

```
✓ You are about the publish the following packages under the tag canary
• create-subscription 0.0.0-741aa17a3
• jest-react 0.0.0-741aa17a3
• react 0.0.0-741aa17a3
• react-art 0.0.0-741aa17a3
• react-dom 0.0.0-741aa17a3
• react-is 0.0.0-741aa17a3
• react-reconciler 0.0.0-741aa17a3
• react-test-renderer 0.0.0-741aa17a3
• scheduler 0.0.0-741aa17a3
```

**Comment by bvaughn** [comment]
I verified the hooks ordering / devtools fix by updating the original failing repo to use the new canary release: https://mom9o7p39y.codesandbox.io/

Looking at the diff of `latest` vs `canary` shows no changes in react and only the hooks validation change in react-dom. I _think_ we should be okay to promote this.

**Comment by bvaughn** [comment]
Stable release versions:
```
create-subscription 16.8.4
• react ^16.3.0 peer

jest-react 0.6.4
• react ^16.0.0 peer
• react-test-renderer ^16.0.0 peer

react 16.8.4
• scheduler ^0.13.4 dependency

react-art 16.8.4
• scheduler ^0.13.4 dependency
• react ^16.0.0 peer

react-dom 16.8.4
• scheduler ^0.13.4 dependency
• react ^16.0.0 peer

react-is 16.8.4

react-reconciler 0.20.2
• scheduler ^0.13.4 dependency
• react ^16.0.0 peer

react-test-renderer 16.8.4
• react-is ^16.8.4 dependency
• scheduler ^0.13.4 dependency
• react ^16.0.0 peer

scheduler 0.13.4
```

**Comment by bvaughn** [comment]
I cherry picked the `package.json` and `CHANGELOG.md` updates (d8a73b5) into master as a9aa24e.

**Comment by bvaughn** [comment]
I think we're done here.

**Pull request closed without merging**
