### PR TITLE
temporarily fixes printWasted abnormality

### PR DESCRIPTION
**Pull request by JaeHunRo**
No longer prints wasted time for newly created DOM nodes 
any feed back is greatly appreciated

### CODE REVIEW

**Comment by tomocchino** [comment]
@spicyj or @sebmarkbage, any feedback on this?

See also Jae's awesome blog posts about optimizing React perf here:
http://jaero.space/blog/react-performance-1/
http://jaero.space/blog/react-performance-2/

**Comment by sebmarkbage** [comment]
The `mountComponent` call of ReactDOMComponent also gets measured.

https://github.com/facebook/react/blob/master/src/renderers/dom/shared/ReactDOMComponent.js#L512

You could intercept it similarly to this:

https://github.com/facebook/react/blob/master/src/test/ReactDefaultPerf.js#L209

That should let you log the ID of newly mounted DOM nodes without needing to parse the HTML content. That's a bit safer. We're also actively trying to get rid of both IDs in the DOM and generating innerHTML content so that solution would help a lot.

**Comment by JaeHunRo** [comment]
I'm not sure if you meant to actually intercept the mounts in the measure function, but I did, and it works for my test cases. Too good to be true?

**Comment by spicyj** [comment]
Does it work equally well if you call `_recordWrite(rootNodeID, 'mount', 0, [])`? If so, I think that's a little cleaner since you don't need to introduce a separate list to track. If not, this way is okay too.

I can merge this if you squash your commits.

**Comment by JaeHunRo** [comment]
printdom
By utilizing ```ReactDefaultPerf._recordWrite```, it works properly but also displays the "mount"s in ```printDOM```. This could be beneficial because it shows users which exact components are being newly mounted as opposed to ```setInnerHTML``` and having to look through ```args``` to find child id's in the markup, but the amount of table rows in ```printDOM``` could quickly get out of hand especially when considering a multitude of nested components for larger applications. Also, would the ```fnName``` be ```'mount'``` necessarily or ```'mountImageIntoNode'```?

**Comment by spicyj** [comment]
I agree that that is pretty noisy. Let's keep it how you have it – mind squashing your commits into one?

**Comment by JaeHunRo** [comment]
I'm having some trouble squashing my commits because I pulled and merged from ```upstream``` in between my commits. How should I go about squashing the commits?

**Comment by spicyj** [comment]
Try: `git rebase -i upstream/master`, then change all but the first line to read "squash" instead of "pick". After rebasing you'll need to force-push to your fork.

**Comment by JaeHunRo** [comment]
interestingly, I'm getting a ```noop```. Would it be okay to close this pr and open a new with a single commit? Also, on a separate branch, I squashed to [this](https://github.com/JaeHunRo/react/commit/4f2a9acc8fe771456479cb277e1531a4b307f6c0) which doesn't seem right because it squashed all commits including ones made by facebook that got thrown in there by my pull/merge

**Comment by spicyj** [comment]
Looks like you figured it out.

**Comment by spicyj** [comment]
(Thank you!)

**Pull request merged**
