### PR TITLE
Update gitignore to use gitignore.io

### PR DESCRIPTION
**Pull request by baer**
This PR removes all ad-hoc gitignores in favor of gitignore.io which generates a complete gitignore  files based off of https://github.com/github/gitignore.

### CODE REVIEW

**Comment by zpao** [comment]
This is way overkill and actually worse as it moves things that are specific to our project to generic sections which don't apply (eg `build/` is definitely not something we ignore because of RubyMotion). I'd take something drastically simpler that just groups things better in the existing file and adds comments (eg "Ignore common editor-specific files").

Let me know if you'd like to do that - you can update this PR. Otherwise I'll close this out.

**Comment by baer** [comment]
My apologies on the build dir - that was an oversight on my part. Actually, I'd like to propose an alternative. All OSX and IDE specific excludes should be in a user's global `.gitignore`. In my experience ignoring OSX or sublime specific files in a project's `.gitignore` is more of a protection against sloppiness that can creep up in a large team. So yes, I'm in agreement that this is overkill, but I prefer it to telling people to please clean up their PRs.

React, however, is a bit of an outlier in that has so many eyes on it that I suspect that any `.DS_Store` files and the like would get caught in code review. What if I remove not just the gitignore.io additions but all of the IDE and environment specific additions that belong elsewhere anyway.

Happy to simplify or close out.

**Comment by zpao** [comment]
I wholeheartedly agree that those really should be in users' global configs but like you said, it's about protection. I don't want to spend time educating people (we did enough of that pointing people to directions on how to use rebase) and as you can probably see with outstanding PRs & issues, we just don't have the time for that (and it's noisy to even have others doing that review).

I think we're pretty well covered on files that popular editors generate but if there's something we're missing we can add that. Otherwise I think cleanup is really all I want to do to that file right now - we don't need to add every possible thing that might be ignored in random, unrelated setups/frameworks.

**Comment by baer** [comment]
lol about the rebasing. Good on you for trying to keep a clean history. I've seen all the "progress..." commits I need for a lifetime. I guess github finally helped out with the squash+merge button. I'm going to close this one out for now. If it gets bigger it would maybe be worth documenting but for now, it's probably fine.

**Pull request closed without merging**
