### PR TITLE
Rename host-y things to be "host" not "native"

### PR DESCRIPTION
**Pull request by spicyj**
For clarity.

I left "native event" as-is because there's a lot of it, it's not particularly ambiguous, and SimulateNative/nativeTouchData are public API in ReactTestUtils.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
While you're at it. rootNodeID/tag/domID/nodeHandle are a bit overloaded and unused on composite component. :)

It is possible something might be used by the devtools/RN still not sure. I think these are mostly isolated now.

**Comment by spicyj** [comment]
Maybe another time. :)

**Comment by zpao** [comment]
Do we need to make any changes to RN or anything else for this? I know ReactART needs 1 change but want to make sure there's nothing else. This is likely to go into a 15.y.0 (mostly for cherry-picking ease).

**Comment by spicyj** [comment]
There's two uses of .getNativeNode in RN but I think that's it. If we merge #6775 then we don't strictly need to update React ART now.

**Comment by zpao** [comment]
So if we took this into 15.1 but RN cuts RC tomorrow, then we would be break them. But if we also take #6775 as is (with the fallback for the old getNativeNode method) then this would be safe without fixing RN now?

**Comment by spicyj** [comment]
No, RN calls getNativeNode in one place (whereas React ART only defines it for React to call). Basically we need to update that RN code when we land the next React update to RN that includes this commit.

**Comment by sebmarkbage** [comment]
Ugh. Debug tools and their dependencies on internals... sigh. We need that public debug API.

**Comment by pke** [comment]
This PR breaks `CSSPropertyOperations.setValueForStyles` when called without a `component`. Calling it without a component was fine before. Now, because of additional debugging code (for native?) apps the code does not check for non-null `component`

**Comment by gaearon** [comment]
@pke I left a comment about this in https://github.com/adambbecker/react-style-transition-group/issues/1#issuecomment-224902367.

**Pull request merged**
