### PR TITLE
fix exponential search in getHostSibling function

### PR DESCRIPTION
**Pull request by guojin-long**
## Summary
 avoid exponential search in getHostSibling function, if multiple placements or insertions are done in a row.

## How did you test this change?
No new features are added, use the old test case will be fine.

### CODE REVIEW

**Comment by gaearon** [comment]
Can you come up with a synthetic stress test / benchmark demonstrating the pathological case and how this fixes it?

**Comment by guojin-long** [comment]
@gaearon  Yes, this is an [example](https://codesandbox.io/s/hungry-knuth-mcl36?file=/src/App.js). 

Steps to reproduce:
1. click the toggle button, then manually change the item's length to 1E5 or 1E6, depending on the performance of your computer. 
2. open the browser's console(not the codesandbox's ) to check the output,

You'll notice that as you add more items, the time it takes to update them increases significantly, and soon the browser will get stuck.



How this fixes it?
Cache the path to the next stable sibling that has been found..

After the fix, the browser still remains responsive even when the length of items reach to 1E6.

**Comment by gaearon** [comment]
Do we have a sense of how much overhead this adds for the common case?

**Comment by guojin-long** [comment]
Reversing the list is an extreme case, but this fix also includes the case where multiple nodes are inserted at the end of the list (this is very common). Although there is no performance test for this yet, I think it will improve the performance in theory.

This modification is somewhat related to the reconcile children algorithm that I am currently working on. According to the test, the overall performance is slightly improved.


image
（A new reconcile children algorithm is used on the left）

**Pull request closed without merging**
