### PR TITLE
Update tutorial18.js

### PR DESCRIPTION
**Pull request by bunnyc1986**
React.findDOMNode doesn't seem exist in React 0.12.2. I followed the tutorial, but received undefined exception.
So I used getDOMNode() instead. It works for me now.

### CODE REVIEW

**Comment by bunnyc1986** [comment]
Just signed the Contributor License Agreement.

**Comment by vsiao** [comment]
You should use React 0.13 (just released today), which has React.findDOMNode.

**Comment by jsfb** [comment]
@vsiao is correct, your version of React is out of date.

**Comment by zpao** [comment]
While we encourage you to upgrade, if you'd like to continue using 0.12, the docs for that version are available on github - https://github.com/facebook/react/blob/0.12-stable/docs/docs/tutorial.md

**Pull request closed without merging**
