### PR TITLE
Use 'document.createEvent' not 'new Event'

### LINKED ISSUE #5153: JSX listeners broken in React 0.14 for Android LTE 4.3 with NODE_ENV='development'
I'm still quite new to React, but I guess this is a bug in the React framework introduced in 0.14. Seems like all listeners attached with JSX are broken in native Android browser for Android LTE 4.3, when compiling code with NODE_ENV development. Everything works fine with NODE_ENV production compilation.

I've tracked it down to being related to ReactErrorUtils, that in development mode do guards on events. The source code:
https://github.com/facebook/react/blob/0.14-stable/src/shared/utils/ReactErrorUtils.js#L58-L74

If I simply remove that part of code after compiling the React app, the listeners starts working again. I guess this is not intentional, but instead a bug?

To reproduce problem in Android LTE 4.3 (code that works in e.g. Chrome Browser):
- Using the pre-compiled Getting Started lib https://facebook.github.io/react/downloads/react-0.14.0.zip:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello React!</title>
    <script src="build/react.js"></script>
    <script src="build/react-dom.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js"></script>
  </head>
  <body>
    <div id="example"></div>
    <script type="text/babel">
      console.log('Script init');
      var testClick = function (e) {
        e.preventDefault();
        console.log('test click!');
      };

      ReactDOM.render(
        <div>
          <a href="#" onClick={testClick}>JSX onClick!</a><br />
          <a href="#" id="manual-attach">Manually attached onClick</a>
        </div>,
        document.getElementById('example')
      );

      document.getElementById('manual-attach').addEventListener('click', function (e) {
        e.preventDefault();
        console.log('test manual click attach!');
      })
    </script>
  </body>
</html>
```

### PR DESCRIPTION
**Pull request by spicyj**
Fixes #5153.

This seems to work in all browsers I tested, including old Android and all IE > 8 which didn't work before.

### CODE REVIEW

**Comment by spicyj** [comment]
@sebmarkbage

**Comment by jimfb** [comment]
Looks reasonable to me.

**Comment by sebmarkbage** [comment]
The only reason I didn't use this to begin with is because of the scary deprecation notice on MDN.

Can you confirm you're not getting a deprecation warning?

Also add a feature test for createEvent just in case.

**Comment by spicyj** [comment]
No deprecation warning in Firefox or Chrome.

createEvent is supported in everything since IE9 as far as I can tell. It was introduced in the same spec as dispatchEvent was. I can add a feature test if you really want one though?

**Comment by sebmarkbage** [comment]
Yea. I'm concerned that they would want to deprecate initEvent but not Event and dispatchEvent since that's what the documentation says. Not that I think browsers would but at least if we're careful they can't blame us for it.

**Comment by spicyj** [comment]
#5166

**Pull request merged**
