### PR TITLE
Remove in-browser unit testing

### PR DESCRIPTION
**Pull request by zpao**
Rely on jest for now until we get a better and less hacky solution to running tests in the browser, probably a totally different test suite with different behavior/goals.

For some additional context, I've already spent a bunch of time in #4167 trying to make things work with populist+jasmine. It's been pretty painful and really not something we need to be investing in right now.

### CODE REVIEW

**Comment by dcousens** [comment]
@zpao it may be hacky,  but is out right removal a better option than living with what we have?
I'm guessing the maintenance burden of these is greater than the value they're giving?

**Comment by zpao** [comment]
Yea, at least to me the burden isn't worth it. We're only looking at the instance run in phantomJS (old, not a real browser, even with shims (though honestly the jsdom we have isn't much to speak of)). We've had failures in the "modern browser" saucelabs run for a long long time, AFAIK not actually due to any bugs in our code but some infra-related issue. Not that we've looked because we said that was an allowable failure. We stopped running the saucelabs tests in other browsers.

Trying to shoehorn the same tests written for a framework with features that extend beyond what we can do easily in the browser has been painful and not entirely reliable. I'd rather not spend a single second looking at all of that and figure out a solution that will hopefully be more maintainable. Perhaps Jest will become runnable in the browser or we'll just write proper-webdriver-but-not-jasmine tests. We'll upgrade Jest soon (0.5 is coming with iojs, new jsdom).

**Comment by zpao** [comment]
@sebmarkbage told me he was ok with this, so I'm just going to merge it.

**Comment by jdalton** [comment]
I'd like to :+1: adding back some form of browser runnable suite. The Microsoft Edge team uses the browser runnable tests of various frameworks and libraries to spot regressions and we'd love to add React to the suite of regression tests.

**Comment by sebmarkbage** [comment]
@jdalton Having an easy to use automated browser test runner that work on TravisCI would be helpful. Presumably you have a set up if you could run this. Anyway it can be open sourced (or explained if it is) and made work with common CI tools?

We'd be happy to maintain the test suite itself but the headless browser tooling was too much of a burden.

**Comment by jdalton** [comment]
> Having an easy to use automated browser test runner that work on TravisCI would be helpful. Presumably you have a set up if you could run this. Anyway it can be open sourced (or explained if it is) and made work with common CI tools?

We're open to open sourcing it though don't have it prioritized at the moment. Our set up isn't super elegant at the moment, requiring scaffolding for each test suite to enable WebDriver automation.

Lib authors have test runners automated through SauceLabs, BrowserStack, Browserling.
For example [Backbone](https://saucelabs.com/u/backbonejs), [Angular](https://saucelabs.com/u/angular), [Lodash](http://saucelabs.com/u/lodash), [Underscore](https://saucelabs.com/u/underscorejs), [Ember](https://saucelabs.com/u/ember-ci).

**Comment by cesarandreu** [comment]
Have you tried zuul? https://github.com/defunctzombie/zuul

You can use a free saucelabs account and run your tests across multiple browsers with very little configuration or hassle.

For example, in one project my `.zuul.yml` config looks like this:

```yaml
ui: mocha-bdd

server: ./bin/server.js

browsers:
  - name: chrome
    version: -2..latest
  - name: firefox
    version: -2..latest
  - name: safari
    version: 5..latest
  - name: ie
    version: 6..latest
```

And the command to run in CI is just:

```sh
$ zuul --concurrency 1 -- test/*.spec.js
```


Zuul is by far the best tool for automatically running tests across browsers that I've tried, and it works with jasmine out of the box.

**Comment by zpao** [comment]
For anybody coming in from Twitter…

This is not as simple as just hooking into saucelabs. Due to the fact that our code in original source form is a custom module system and that there are jest-isms (on top of Jasmine) in our tests, we're currently tied to using Jest. We had a more complex testing build-step which did work in the browser and did run on saucelabs but it was fragile, slow, not entirely accurate, and wasn't really used as a result. Without significant investment, we wouldn't have been able to upgrade to newer Jest nor start using Node v4, putting us at another disadvantage for contributors. We've considered making it such that Jest can start a server and do the module resolution and other stuff while actually running the tests in the browser, but it's pretty low priority for us.

**Comment by jdalton** [comment]
>  We've considered making it such that Jest can start a server and do the module resolution and other stuff while actually running the tests in the browser, but it's pretty low priority for us.

Sounds complicated though I'm not sure it has to be. Maybe testing with built version of react, react-dom, react-with-addons using something build task before the tests are run.

I think browser runnable tests would increase confidence in React and ensure it supports what it claims to as there are plenty of browser bug fixes and workarounds in the source that aren't currently being tested.

Once the initial scaffolding is in place I could see the community pitching in to increase coverage. Maybe even CodeSchools having assignments to contribute tests for the APIs they use (@nickbalestra).

**Comment by sebmarkbage** [comment]
The reason we felt comfortable removing them is because there wasn't much gain from having them. It didn't catch bugs that we had, didn't help refactoring and whenever we changed the behavior we resulted to manual testing. Whenever we do a major change thousands of people and real use cases immediately test a variety of use cases on Facebook. Those catch problems every once in a while. That provides a level of confidence to the changes.

It is not as good as rigorously writing Web Driver tests for every edge case but a lot easier and cheaper. We could do it to be nice citizens but honestly it was that important to us.

Perf regression tests would be more interesting.

**Comment by jdalton** [comment]
> The reason we felt comfortable removing them is because there wasn't much gain from having them. It didn't catch bugs that we had, didn't help refactoring and whenever we changed the behavior we resulted to manual testing.

Having untested code is ripe for regressions. I'm not sure saying "We're Facebook and we use our users as unit tests" is the way to go here.

**Comment by gaearon** [comment]
I think @sebmarkbage may have been referring to internal product tests catching those cases rather than users.

**Comment by jdalton** [comment]
I'm not sure that makes it better.

**Comment by sebmarkbage** [comment]
> You mean nice citizens to developers right?

I mean a nice citizen to browser developers because you wanted it track your own regressions.

> They take the hit when you don't test.

As I said, over two years, it didn't catch anything and was distracting for other better testing that was catching problems. It's simple priorities. We have a very small team.

No need to debate this. Time will prove whether it was time well not spent when we find a regression.

I've been wanting to extract more of the tests from the DOM renderer and run it against a noop renderer. It is important that we retain the internals working for other environments like React Native which has even less testing.

Then we could have have a separate test suite for the DOM rendering alone which would make it easier to test browser quirks as a separate test suite.

**Comment by jdalton** [comment]
> I mean a nice citizen to browser developers because you wanted it track your own regressions.

Regardless of browser vendors I still think unit tests are important. I've already mentioned how they can be of value to those contributing to React.
 
> As I said, over two years, it didn't catch anything and was distracting for other better testing that was catching problems. It's simple priorities. We have a very small team.

That could point to an issue in your test coverage or maybe you're lucky. I know when I've touched and refactored code, especially around older environment support, unit tests have saved me plenty of grief.

> No need to debate this. Time will prove whether it was time well not spent when we find a regression.

Maybe though I do find it odd that a lib whose major scenario is working with the DOM isn't tested in browsers.

> It is important that we retain the internals working for other environments like React Native which has even less testing.

:fearful: 

> Then we could have have a separate test suite for the DOM rendering alone which would make it easier to test browser quirks as a separate test suite.

Rock!

**Comment by sebmarkbage** [comment]
I think it is because almost all of the work we're doing right now is in the internals of React and the things that touches the DOM is pretty small and stable. If that shifts, it is likely we'd have to restore browser testing. For example, we currently do very little shimming work. We might want to start automatically prefixing inline style properties. That would probably require cross-browser unit tests.

Believe me, I'm as surprised as you are. Growing up in a world of ever changing browsers and quirks something feels off about it. :)

**Comment by jdalton** [comment]
> I think it is because almost all of the work we're doing right now is in the internals of React and the things that touches the DOM is pretty small and stable

Untested code could very well be stable or broken who knows because there's no tests.

**Comment by sebmarkbage** [comment]
I want to apologies for my tone earlier. I didn't mean that we shouldn't do this nor that it wouldn't be valuable. I felt that it was important to add context to why this decision was made and @zpao totally made the right call at the time. However, @jdalton is also completely right that this would be useful to have regardless. My snarky comments didn't help. Sorry about that. I created a new issue to track this #5703

**Comment by subtleGradient** [comment]
Boo! Hiss!
#dislike

**Pull request merged**
