### PR TITLE
Fixed Copyright year from 2014 to 2015 in 3 files

### PR DESCRIPTION
**Pull request by brianpchsu**
Change copyright year from 2014 to 2015 in react.js, ReactDOMIframe.js, and setTextContent.js. All changes are in comments and won't affect original codes.

### CODE REVIEW

**Comment by syranide** [comment]
Two of the licenses are even the wrong/old ones (brought in by my pre-2015 PRs :S). Could you update those to use the BSD-license as well?

**Comment by brianpchsu** [comment]
Sure. I just updated those two files as well.

**Comment by brianpchsu** [comment]
I updated the last line of those two file. Are those the format you want? Or I should just delete the last line if it's not really necessary to be there?

**Comment by syranide** [comment]
Only the license should be updated, any `@`-directives must be left as-is.

**Comment by brianpchsu** [comment]
Hi Andreas, I changed the file's last line (@- directives) to the origin state.

**Comment by zpao** [comment]
Can you rebase? This doesn't merge cleanly (I fixed the license on 1 of the files yesterday as part of #3133).

**Comment by brianpchsu** [comment]
Hi Paul, I rebased to the newer commit and update the copyright year to that file as well. Thanks.

**Comment by brianpchsu** [comment]
I found my commit combined all the previous version of commit. I'm fixing it now.

**Comment by brianpchsu** [comment]
Sorry I did something stupid in rebase. I made another pull request 
https://github.com/facebook/react/pull/3139
and will close this one.

**Pull request closed without merging**
