### PR TITLE
Lint for ReactART

### PR DESCRIPTION
**Pull request by koba04**
This PR is for adding ReactART into ESLint targets and fixing ESLint errors.

### CODE REVIEW

**Comment by Aweary** [comment]
ReactART also lives in its own repository, confusingly https://github.com/reactjs/react-art/

**Comment by koba04** [comment]
@Aweary 
Thanks, I didn't know the repository...
Can we remove ReactART renderer in this repository?

**Comment by Aweary** [comment]
I have no clue, I'm not sure what the reasoning behind it is. cc @zpao

**Comment by zpao** [comment]
ART is here for improved testing but primarily lives in its own repo. The copy here isn't really for editing, just testing, at least for now and as such we don't need to lint it. Maybe one day we'll go full mono-repo on this.

**Comment by koba04** [comment]
Thanks!
It would be nice if there was a comment about that or moved to its `__tests__` directory.

**Pull request closed without merging**
