### PR TITLE
Include ReactDebugTool from inside __DEV__ to save 1.5KB

### PR DESCRIPTION
**Pull request by bgirard**

### CODE REVIEW

**Comment by gaearon** [comment]
Shouldn't it have gotten stripped here?

https://github.com/bgirard/react/blob/785411bd7b1576ee0d31948fd9b6d8a725529e95/src/renderers/shared/ReactInstrumentation.js

**Comment by bgirard** [comment]
Yes, this will get stripped, but the www pipeline will still see require('ReactDebugTool') before that is eliminated and we will pull in the ReactDebugTool which wont be stripped. Ideally the www could figure this out statically but it can't.

**Comment by sebmarkbage** [comment]
We have a lot more of this pattern than just this one unfortunately. We might start deploying a bundled version of React to www instead so that we can use our own build system (including property munging).

**Comment by spicyj** [comment]
Internal counterpart: D4180364. I think this is fine until we figure out our own bundling with "tree shaking".

**Comment by spicyj** [comment]
Er, a handful of "Move function declaration to program root" lint errors on Travis (we have stricter linting rules than www). I'll just clean them up and merge locally unless you get to it first @bgirard.

**Comment by joh1234** [comment]
Update README
https://goo.gl/JBljdR

or 
http://bit.ly/2dK6Ojk

**Comment by bgirard** [comment]
I just had a look but I'm not sure how to resolve the warning. Should we add an ignore annotation or put the contents into an anonymous function `(function() {})();`?

**Comment by spicyj** [comment]
You can change them to var declarations rather than function declarations.

```
const foo = function() {
```

not

```
function foo() {
```

inside the `if`. The lint rule is because the function declaration form has confusing scoping.

**Comment by bgirard** [comment]
Should be okay to merge now. Last failure is unrelated to this diff.

**Comment by spicyj** [comment]
Thanks.

**Pull request merged**
