### PR TITLE
Redirect users from the old gh-pages (Jekyll website) to reactjs.org

### PR DESCRIPTION
**Pull request by bvaughn**
Proposed alternative to #10856; continuation of #10936.

### Goals

* Redirect people visiting existing links to the new website. These links are scattered throughout documentation, other websites, DevTools, etc.
* Redirect search engine crawlers from the old gh-pages site to reactjs.org without harming our ranking.
* Preserve functionality of tools that depend on query params (like the error decoder).
* Preserve anchor tags if possible.

### Testing

Spot checking a few of the generated pages seems to work. For example I tried the following URL patterns:

category | type
:---|:---
root url | https://bvaughn.github.io/react/
no .html | https://bvaughn.github.io/react/docs/installation
nested url | https://bvaughn.github.io/react/blog/2017/05/18/whats-new-in-create-react-app.html
non-markdown | https://bvaughn.github.io/react/blog/all.html
query params | https://bvaughn.github.io/react/docs/error-decoder.html?invariant=109&args[]=Foo
anchors | https://bvaughn.github.io/react/tutorial/tutorial.html#lifting-state-up

### New Approach

Add a `CNAME` pointer to redirect to custom domain.

### Old Approach

First I deleted the old Jekyll website.

Then I generated a list of all unique URLs used in the website by logging them in `gatsby-node.js`. Then I ran those URLs through the following script:

```js
const {existsSync, mkdirSync, writeFileSync} = require('fs');
const {join} = require('path');

const urls = `...`; // From gatsby-node.js

const createPage = path => `
<html>
  <head>
    <meta http-equiv="refresh" content="0; url=https://reactjs.org/${path}">
    <link rel="canonical" href="https://reactjs.org/${path}">
  </head>
  <body>
    Redirecting to <a href="https://reactjs.org/${path}">https://reactjs.org/${path}</a>...
  </body>
</html>
`;

urls.trim().split('\n').forEach(path => {
  let bound = 0;
  while (true) {
    const index = path.indexOf('/', bound);

    if (index >= 0) {
      let subpath = path.substr(0, index);
      subpath = join(__dirname, subpath);

      if (!existsSync(subpath)) {
        mkdirSync(subpath);
      }

      bound = index + 1;
    } else {
      break;
    }
  }

  writeFileSync(
    join(__dirname, path),
    createPage(path)
  );
});
```

### CODE REVIEW

**Comment by gaearon** [comment]
What about query arguments and fragments? For example for the error decoder. Seems like we'd still need JS "progressive enhancement" to respect them?

**Comment by bvaughn** [comment]
> What about query arguments and fragments?

I added the JavaScript redirect for the error page (only) and `<meta>` tags for all others. (I don't think it's possible to use `<meta>` to redirect _with_ query params.)

**Comment by gaearon** [comment]
Ah I see. I was thinking we could have a script on each page that takes control first and thus provides better experience for the browsers (as opposed to the crawlers). 

In particular I'd love if we can keep fragments working. We have many links to particular sections (e.g. "Use the production build") of pages and I'd prefer if they keep working. Although now that I think of it I remember Gatsby has a different fragment slug generation behavior.

**Comment by bvaughn** [comment]
> Ah I see. I was thinking we could have a script on each page that takes control first and thus provides better experience for the browsers (as opposed to the crawlers).

I'm not sure how this would work. You mean, leave the `<meta>` tag in place for crawlers, but have a JavaScript snippet that blocks it in favor of what the `error-decoder.html` file is doing? 🤔 

> In particular I'd love if we can keep fragments working. We have many links to particular sections (e.g. "Use the production build") of pages and I'd prefer if they keep working. Although now that I think of it I remember Gatsby has a different fragment slug generation behavior.

Yeah, anchor tags might be tricky to fully support to be honest. And they're bound to get out of sync as time goes on and the new website changes.

**Comment by gaearon** [comment]
>You mean, leave the <meta> tag in place for crawlers, but have a JavaScript snippet that blocks it in favor of what the error-decoder.html file is doing? 🤔

Yep. I would expect that even if the meta tag starts doing its thing, a JS script would be able to override what it's doing. Progressive enhancement.

>And they're bound to get out of sync as time goes on and the new website changes.

I understand. But just best effort attempt would go a long way.

**Comment by gaearon** [comment]
(If there's no easy way to do it then let's forget about this :-)

**Comment by bvaughn** [comment]
Well I could certainly update my Node script to change the template string I'm rendering. That part's easy. 😄 

https://support.google.com/webmasters/answer/2721217?hl=en

> Using JavaScript to redirect users can be a legitimate practice. For example, if you redirect users to an internal page once they’re logged in, you can use JavaScript to do so. When examining JavaScript or other redirect methods to ensure your site adheres to our guidelines, consider the intent. Keep in mind that 301 redirects are best when moving your site, but **you could use a JavaScript redirect for this purpose if you don’t have access to your website’s server.**

Maybe JS-redirects are okay after all?

**Comment by gaearon** [comment]
I'm thinking about other search engines (e.g. Russian, Chinese) that may not be as smart as Google. Using both methods wouldn't hurt, no?

**Comment by bvaughn** [comment]
> I'm thinking about other search engines (e.g. Russian, Chinese) that may not be as smart as Google.

Yeah, for sure.

> Using both methods wouldn't hurt, no?

I actually have no idea. Maybe it would. Search engines can choose to de-rank based on arbitrary criteria.

**Comment by browniefed** [comment]
Have you thought about asking Github nicely?

**Comment by gaearon** [comment]
I guess let's just do it without the anchors. We can add them later if we figure out a good way to. We also now have a TOC on each page which we didn't before.

**Comment by zpao** [comment]
Idea: use CNAME on the github pages to point to the new domain. GitHub will do a 301 redirect. Then for anything that doesn't match up (presumably most everything) you can use Netlify to do another 301 with the same generated mapping it sounds like you have: https://www.netlify.com/docs/redirects/

**Comment by sophiebits** [comment]
If the GitHub CNAME file works, let's definitely do that. Else, lets add window.location.replace call in JS like any other PR had to maintain query string and hash and make sure it doesn't add a history entry.

**Comment by bvaughn** [comment]
Updated the PR with a `CNAME` file and pushed it to my `gh-pages` branch too (so we can test via bvaughn.github.io/react). Unless I'm missing something, it seems to work fine.

**Comment by bvaughn** [comment]
Thanks @zpao!

**Pull request merged**
