### PR TITLE
react-devtools\OVERVIEW.md --> fixed typos

### PR DESCRIPTION
**Pull request by Biki-das**
decsendants --> descendants
dehyration --> dehydration

### CODE REVIEW

**Comment by Biki-das** [comment]
stucked in ci sandbox seems like an issue

**Comment by rickhanlonii** [comment]
@Biki-das thanks for your interest in React and for creating so many PRs! It looks like you're creating and closing a lot of PRs though, which adds noise for our notifications and makes it harder to maintain. Is it possible to hold off creating those PRs until they're ready, or testing in your fork instead of the main repo? Note that we don't typically merge PRs for subjective changes like grammar or language. If you have a more substantial change, I'm happy to review!

**Comment by Biki-das** [comment]
> @Biki-das thanks for your interest in React and for creating so many PRs! It looks like you're creating and closing a lot of PRs though, which adds noise for our notifications and makes it harder to maintain. Is it possible to hold off creating those PRs until they're ready, or testing in your fork instead of the main repo? Note that we don't typically merge PRs for subjective changes like grammar or language. If you have a more substantial change, I'm happy to review!

thanks for the feeback and i am sorry for the continuos PR , will keep that in mind @rickhanlonii

**Comment by rickhanlonii** [comment]
@Biki-das what I do is set my local git repos as:

```
$ git remote -v
origin  git@github.com:rickhanlonii/react.git (fetch)
origin  git@github.com:rickhanlonii/react.git (push)
upstream        git@github.com:facebook/react.git (fetch)
upstream        git@github.com:facebook/react.git (push)
```

So my origin is my fork, and upstream is the main repo. Then, when I want to update with the facebook repo, I do:

```
git checkout main
git pull upstream main
git push origin main
```

**Comment by Biki-das** [comment]
@rickhanlonii  and when you push something do you create another branch or do it through the main only

**Comment by rickhanlonii** [comment]
@Biki-das I create a new branch in my fork and push it to my origin.

**Comment by Biki-das** [comment]
> @Biki-das I create a new branch in my fork and push it to my origin.

@rickhanlonii  oh now i got it you push it like --> git push origin branch name

**Pull request closed without merging**
