### PR TITLE
Mixins Considered Harmful - Add mixins property to context example

### PR DESCRIPTION
**Pull request by fhelwanger**
First of all, very nice post about mixins! Thanks @gaearon and everyone involved :smile: 

I think that the `Link` component `mixins` property is missing.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by syranide** [comment]
As far as I can tell it's correct as it is. It's explicitly about how you solve it without mixins.

**Comment by syranide** [comment]
Bah sorry, it seems you are correct, I was looking at the wrong place in the final document.

**Comment by gaearon** [comment]
Thank you!

**Pull request merged**
