### PR TITLE
ReactDOMComponent should throw error when provided children for void elements

### PR DESCRIPTION
**Pull request by jonhester**
Fix for https://github.com/facebook/react/issues/3367. I removed the ```if(__DEV__)`` block since it's throwing an error now and updated the tests.

### CODE REVIEW

**Comment by syranide** [comment]
Putting all children-logic (`createContentMarkup`, `updateDOMChildren`, etc) behind the same check should make sense I think, no point in going through the children-logic if there cannot be children.

**Comment by jsfb** [comment]
Well, maybe the proposed `if` check should be `if(props.children == null && props.dangerouslySetInnerHTML == null)`, since void elements don't have a monopoly on not having children.

@jonhester Thanks for fixing this one so quickly :).  Just note that, as per the conversation in https://github.com/facebook/react/issues/3367, we need to keep it a warning for the 0.14 release, so this probably won't be mergable until 0.15

**Comment by syranide** [comment]
@jsfb That's tricky because you have to consider prev/next children as well and in a sense what the "children logic" is doing internally already, whereas void components will never have children so you can simply skip that part entirely with a single stateless check.

**Comment by jonhester** [comment]
@jsfb Right, not worried about when it will be merged, and I'm guessing this pull request may need some changes before it's merged, even without merge conflicts. I'm new to contributing to this project, and contributing to open source in general and have been watching the ```good-first-bug``` label to try to get some familiarity with the project.

**Comment by jsfb** [comment]
@syranide Ah, absolutely correct.  If such a check is added (to this commit or a future commit), @syranide's logic is correct, we can't just check for the current presence of children, but we could do a void-element check.  Probably wouldn't be blocking, but I'm a little curious what @zpao @spicyj would think about the performance vs. simplicity trade-off.

@jonhester Ok, awesome!  Glad to have you be a part of the community!  Let me know if there is anything we can do to help!

**Comment by jimfb** [comment]
@jonhester We're merging 0.15 stuff now.  As expected, there are a few merge conflicts.  Do you want to rebase and we can get this PR ready to be merged?

**Comment by jonhester** [comment]
@jimfb I'll take care of this now.

**Comment by jonhester** [comment]
@jimfb Good to go.

**Pull request merged**
