### PR TITLE
update create-react-class package.json to use latest react

### PR DESCRIPTION
**Pull request by elijahsmith**
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`).
6. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run prettier`).
7. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
8. If you added or removed any tests, run `./scripts/fiber/record-tests` before submitting the pull request, and commit the resulting changes.
9. If you haven't already, complete the CLA.

### CODE REVIEW

**Comment by elijahsmith** [comment]
this is an attempt to address https://github.com/facebook/react/issues/9750. 

The issue is that the create-react-class npm package has been built with an old version of React in it, which causes GCC to choke when it tries to compile anything that uses it.  I'm not sure how the npm package is generated -- the command isn't in the package.json, for instance -- but this PR updates the versions of the react packages that are referenced in the package.json.  

I'm not sure what needs to happen with the yarn.lock file -- should I update that as well?

**Comment by gaearon** [comment]
I believe I fixed this in https://github.com/facebook/react/pull/9933.

**Comment by elijahsmith** [comment]
I saw that -- I wasn't convinced that would address the issue but I'm hoping I'm wrong.  

To find out -- can you please republish the create-react-class npm package with these changes in it?

**Comment by gaearon** [comment]
Not yet. We'll publish it soon after 15.6. If something's missing by then I'm happy to follow up.
I'm pretty sure this will address the issue though. (The addon is using a copy of that code, changing it in React or bumping React package will have no effect.)

**Comment by elijahsmith** [comment]
ok thank you for the clarification.

**Pull request closed without merging**
