### PR TITLE
Deprecate test utils mock component follow up

### PR DESCRIPTION
**Pull request by bvaughn**
Follow up for PR #13193

* Add de-duplication for deprecation warning
* Added fb.me URL to warning text

### CODE REVIEW

**Comment by gaearon** [comment]
Let's not forget to link fb.me before merging.
Just a personal profile gist is fine — I don't think this deserves a website page.

**Comment by bvaughn** [comment]
Of course not :) I'm writing the  Gist now.

**Comment by bvaughn** [comment]
https://fb.me/test-utils-mock-component

**Comment by Arissablue** [comment]
😎

**Pull request merged**
