### PR TITLE
Remove IE8 property expansion workaround

### PR DESCRIPTION
**Pull request by gaearon**
We don’t support it anymore.
Just need to verify IE9 is not affected.

### CODE REVIEW

**Comment by jquense** [comment]
Yeeees 🔪🔪

**Comment by aweary** [comment]
Looks like you need to remove the `CSSPropertyOperations` and `ExecutionEnvironment` imports since they're unused now.

**Comment by gaearon** [comment]
Does anybody want to test if it breaks IE9?

If this is a one-off for IE8 I don't think it deserves a fixture.

**Comment by aweary** [comment]
@gaearon it may have been included for IE8, but there's no guarantee that a fix isn't directly or indirectly preventing a break in other browsers as well, which is why I recommended a broad fixture for style properties.

I say that because I thought that it had happened to me before, and it turns out it was when I tried to do this exact same thing in https://github.com/facebook/react/pull/9294 😄 

This was breaking iOS 4 and Android 4.1 for me, so I dropped it since I wasn't sure what our browser support guidelines were (https://github.com/facebook/react/issues/9301)

**Comment by nhunzaker** [comment]
Based on @aweary's experience, it sounds like we need to determine if are dropping support for iOS4 Safari and Android 4.1 Browser. [caniuse](http://caniuse.com/usage-table) indicates 0% usage of iOS 4 Safari and 0.11% usage of Android 4.1 Browser globally. still, I do not know how representative this is of Facebook's audience.

So do we drop these browsers?

**Comment by gaearon** [comment]
IIRC our guideline is > 1% of our audience. But @sophiebits can confirm whether I remember it right.

**Comment by nhunzaker** [comment]
Did some quick visual QA in IE8-11 and Android 4.2. Some of my best design work, of course:

screen shot 2017-09-24 at 9 02 02 pm

This also looked great on the Galaxy S3's native browser which makes me wonderif I'm missing a key step in QA based on @aweary's experience. 

But this looks good to me otherwise, 👍.

**Comment by aweary** [comment]
@nhunzaker I believe I had issues with Android 4.1, not 4.2. it's also totally possible I messed up the QA last time somehow 😉

**Comment by nhunzaker** [comment]
@aweary sorry, I missed a key detail: The Galaxy S3 I tested on was Android 4.1. 

I just did another check to very that styles can be toggled on or off, which, I think, covers the shorthand bug style clearing case. I've published that here:

http://react-shorthand-style.surge.sh/

For whatever it's worth, this _does_ work on Android 4.1. I think we should move forward with this change.

**Comment by gaearon** [comment]
We’ll wait for after 16 before landing. Since we’ll probably land a few PRs that increase the bundle size (e.g. new unstable APIs) and I want to have something to balance that.

**Comment by aweary** [comment]
I verified the @nhunzaker's fixture works as expected in Android 4.1, so this LGTM whenever we want to merge 👍

**Pull request merged**
