### PR TITLE
shallow render: fix setState in componentWillMount

### LINKED ISSUE #4461: calling setState on componentWillMount in Shallow Render results in TypeError: Cannot read property '_currentElement' of null
Calling `setState` on `componentWillMount` in a component being Shallow Rendered will result in the error `TypeError: Cannot read property '_currentElement' of null` being thrown. I set up a test case:

```javascript
var expect = require('chai').expect;                                             
                                                                                 
describe('testing state', function() {                                           
                                                                                 
  beforeEach(function() {                                                        
    var Window = require('domino/lib/Window');                                   
    var domino = require('domino');                                              
                                                                                 
    global.document || (global.document = domino.createDocument());              
    global.window = new Window(global.document);                                 
    global.navigator = global.window.navigator;                                  
  });                                                                            
                                                                                 
  it('should handle having initial state', function() {                          
    // this passes                                                               
    var React = require('react');                                                
    var ReactTestUtils = require('react/lib/ReactTestUtils');                    
                                                                                 
    var Sample = React.createClass({displayName: "Sample",                       
      getInitialState: function() {                                              
        return {                                                                 
          groovy: 'doovy'                                                        
        };                                                                       
      },                                                                         
                                                                                 
      render: function() {                                                       
        return React.createElement("div", null, this.state.groovy);              
      }                                                                          
    });                                                                          
                                                                                 
    var renderer = ReactTestUtils.createRenderer();                              
    renderer.render(React.createElement(Sample, null), this);                    
    var result = renderer.getRenderOutput();                                     
    expect(result.props.children).to.equal('doovy');                             
  });                                                                            
                                                                                 
  it('should handling set state on componentWillMount', function() {             
    // this fails                                                                
    var React = require('react');                                                
    var ReactTestUtils = require('react/lib/ReactTestUtils');                    
                                                                                 
    var Sample = React.createClass({displayName: "Sample",                       
      componentWillMount: function() {                                           
        return this.setState({                                                   
          groovy: 'doovy'                                                        
        });                                                                      
      },                                                                         
                                                                                 
      render: function() {                                                       
        return React.createElement("div", null, this.state.groovy);              
      }                                                                          
    });                                                                          
                                                                                 
    var renderer = ReactTestUtils.createRenderer();                              
    renderer.render(React.createElement(Sample, null), this);                    
    var result = renderer.getRenderOutput();                                     
    expect(result.props.children).to.equal('doovy');                             
  });                                                                            
});    
```

### PR DESCRIPTION
**Pull request by graue**
Fixes #4461

Just combining the fix @neelance submitted as #5247 with the relevant unit test @drabinowitz wrote in #4461. Thanks to both of you! (Looks like you both signed the CLA. :+1: )

@spicyj, per your comment on #5247, the test here covers checking that the state update went through.

### CODE REVIEW

**Comment by drabinowitz** [comment]
Thank you so much that's fantastic to hear!

**Comment by spicyj** [comment]
I actually prefer not having nested describes because it makes it more difficult to add new tests. Can you revert that so the only test change is adding the new test? Otherwise this is good – feel free to merge after fixing.

**Comment by graue** [comment]
Womp womp. Done. For later, maybe a better refactor would be to move the shallow renderer out to its own file (and own test file)?

**Comment by spiralman** [comment]
What build of React 0.14.x will this fix be made available in? Still getting the issue in 0.14.6.

**Comment by graue** [comment]
Should be in the next one, since this now has the 0.14.x milestone on it (look up):

> zpao added this to the 0.14.x milestone 15 days ago

**Comment by stuartsan** [comment]
Sweet, I'm also waiting for this to land. Thanks @graue

**Comment by graue** [comment]
This is in the new 0.14.7 release, for folks watching the thread.

**Pull request merged**
