### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by hejld**
`iff the the selection` -> `if the selection` & 80 character line length

### CODE REVIEW

**Comment by yangshun** [comment]
iff can mean "if and only if". might not be a typo

**Comment by hejld** [comment]
That is not something you use in everyday language. Also it is now what the author intended to say here - check out the `canTriggerTransfer` method.

**Comment by jimfb** [comment]
Well, the good news is, we can ask the original author ( @spicyj ) what he meant.  But for the record, @yangshun is correct, the term "iff" is used pretty commonly in formal mathematics and computer science.  If I had to guess, I'd say the use of "iff" there was intentional rather than an unfortunate typo.

I'll let @spicyj make the final call on this one, since he is the original author.  My intuition is that it is correct as-is and we can close this out.

**Comment by spicyj** [comment]
Yes, "iff the selection" please.

**Comment by spicyj** [comment]
(Also I don't think I actually wrote this.)

**Comment by hejld** [comment]
Awesome :+1:

**Comment by spicyj** [comment]
Thanks!

**Pull request merged**
