### PR TITLE
add srcLang DOM attribute

### PR DESCRIPTION
**Pull request by revolunet**
Added missing srclang attribute, useful when rendering video <tracks> elements.

Thanks !

### CODE REVIEW

**Comment by revolunet** [comment]
signed

**Comment by zpao** [comment]
Are there any other `<video>` related markup DOM properties/attributes that can also be added? #2094 attempted to add some (and some non-markup related ones which is why it didn't get off the ground).

**Comment by revolunet** [comment]
yes, if you're okay i can add volume, kind, default, plabackRate

(default indicates if its the default subtitle)

**Comment by syranide** [comment]
http://www.w3.org/TR/html-markup/video.html#video-attributes

**Comment by revolunet** [comment]
@syranide : thanks, can you please explain the implication of `MUST_USE_ATTRIBUTE` ? cant find any comment on this in the code

**Comment by zpao** [comment]
By default React does `node.property = newValue`. However that doesn't work for everything and for some you must actually do `node.setAttribute('name', newValue)`. `MUST_USE_ATTRIBUTE` tells React to do the latter here. The inverse is also true where some must be set with the property and will never work with the attribute so we specify `MUST_USE_PROPERTY`. https://github.com/facebook/react/blob/master/src/renderers/dom/shared/DOMProperty.js#L22-L61 has some comments about this.

**Pull request closed without merging**
