### PR TITLE
minor correction to context doc

### PR DESCRIPTION
**Pull request by davidatthepark**
This sentence confused me a little while reading about context. It seems like the logic should be:

"If you know Redux or MobX, don't use context."

### CODE REVIEW

**Comment by sophiebits** [comment]
The intent is "If you don't know Redux + MobX, you are not qualified to decide to choose context over them and you should learn them first. If you do and still think you want context, maybe context is the right thing."

**Comment by sophiebits** [comment]
I'm going to close this but feel free to send a PR to make this clearer if you want.

**Comment by davidatthepark** [comment]
I see. That makes sense now. Thanks!

**Comment by sophiebits** [comment]
You're welcome!

**Pull request closed without merging**
