### PR TITLE
Basic SSR support for error boundaries

### LINKED ISSUE #6689: Error boundaries crash on server rendering
`ReactServerRenderingTransaction` doesn’t have a `checkpoint()`, so any component with `handleError()` crashes during server rendering. I tested on 15, but pretty sure this is in master as well.

Fiddle: https://jsfiddle.net/un1nqs0w/

cc @jimfb

### PR DESCRIPTION
**Pull request by jimfb**
Basic SSR support for error boundaries.  Fixes #6689.

### CODE REVIEW

**Comment by jimfb** [comment]
cc @gaearon

**Comment by jimfb** [comment]
@sebmarkbage

**Comment by gaearon** [comment]
Looks good to me but I don’t know about how checkpoint abstraction is supposed to be used so deferring to @sebmarkbage.

**Comment by facebook-github-bot-6** [comment]
@jimfb updated the pull request.

**Comment by gaearon** [comment]
I don’t see any issues with this, and it fixes a crash, so let’s get it in.

**Comment by gaearon** [comment]
I’m tagging as 15.0.x to emphasize it’s a patch, but we can probably rename this to 15.1.x after 15.1 alpha is shipped as won’t do more 15.0.x releases.

**Pull request merged**
