### PR TITLE
Add table of attribute behavior

### PR DESCRIPTION
**Pull request by acdlite**
There are many "special cases" of attributes that React may recognize and treat in different ways. For each of these cases, we must consider common mis-capitalizations and alternative formats for the attribute name. For all possible value types, we need to verify that any changes between React 15 and 16 are intentional and understood.

This is an *unpolished MVP* of a fixture to compare the behavior between React 15 and 16 for every possible value type for each attribute name.

This will be useful for verifying and understanding the changed made in:
https://github.com/facebook/react/commit/2999811b07a5eb9e04680457a0b56195abd7e08c
https://github.com/facebook/react/commit/5ba1803ba2bf8581c2605247f3cf50aebacce1c4
https://github.com/facebook/react/commit/35859df9418e3161130d267a27602fc263979a1f

### CODE REVIEW

**Comment by gaearon** [comment]
😮

**Comment by gaearon** [comment]
Should this live in `fixtures` rather than `scripts`?

**Comment by acdlite** [comment]
Probably, I just threw it together. It's pretty messy right now. We're trying to get the simplest, most MVP version complete for the release.

**Comment by gaearon** [comment]
Yea, fair enough, didn’t mean it’s important 😛

**Comment by acdlite** [comment]
Originally it was going to be a normal node script that printed out a table until we realized that we'd have to special case every single attribute :D

**Pull request merged**
