### PR TITLE
Remove the codes relating to jshint

### PR DESCRIPTION
**Pull request by koba04**
react is using ESLint for lint now, so I removed the codes relating to jshint.

In addition, I refactored some DOM components, because I found the below comment.

https://github.com/facebook/react/blob/master/src/browser/ui/dom/components/ReactDOMForm.js#L35-L37
```
    // TODO: Instead of using `ReactDOM` directly, we should use JSX. However,
    // `jshint` fails to parse JSX so in order for linting to work in the open
    // source repo, we need to just use `ReactDOM.form`.
```

Are these changes unnecessary?

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
https://github.com/facebook/react/pull/3123#issuecomment-73958538
BTW don't know if FB still use jshint internally

**Comment by PiPeep** [comment]
@koba04 We've got full eslint coverage now, so I disabled jshint for react at FB internally. Do you still have time/interest to work on this? Can you rebase it?

**Comment by koba04** [comment]
@PiPeep 
Thank you, I've rebased it!

I didn't remove it from `vendor/browser-transforms.js` because I found this comment.
https://github.com/facebook/react/pull/3834#issuecomment-100051365

Also,

>>
// TODO: Instead of using `ReactDOM` directly, we should use JSX. However,
// `jshint` fails to parse JSX so in order for linting to work in the open
// source repo, we need to just use `ReactDOM.form`.

Should I convert to use JSX?
JSX needs to have `React.createElement` in scope. I should use `var React = require('ReactElement');` if I use JSX in React internal?

**Comment by zpao** [comment]
> I didn't remove it from `vendor/browser-transforms.js`

You can change that one. My previous comment was about `vendor` in `src`. This one isn't synced with anything else.

> Should I convert to use JSX?

No, leave those alone.

**Comment by zpao** [comment]
This lgtm. Any comments from you @PiPeep?

**Comment by PiPeep** [comment]
The commit lgtm, pending `vendor/browser-transforms.js`. I checked it against `ag jshint -p .eslintignore`, and it seems to cover everything.

@zpao, are we simply avoiding jsx altogether in the react source, excluding `__tests__` and `src/addons`?

**Comment by zpao** [comment]
Currently that is correct (except we also don't use it in src/addons).

**Comment by PiPeep** [comment]
Oh, sorry. I think I was accidentally looking at code within comments.

**Comment by koba04** [comment]
@zpao @PiPeep 
Thank you for your feedback!
I removed it from `vendor/browser-transforms.js`.

**Comment by zpao** [comment]
Thanks!

**Comment by koba04** [comment]
Thank you!!

**Pull request merged**
