### PR TITLE
Updated link and text for beginner friendly in how-to-contribute

### PR DESCRIPTION
**Pull request by ivikash**
Hey, I am trying to update the necessary links for `beginner friendly bugs` in `gh-pages`.  cc: @acdlite

### CODE REVIEW

**Comment by gaearon** [comment]
cc @acdlite, please make sure to update the docs if you change the labels 😉 . There's been a few PRs fixing this up in a few different places.

**Comment by aweary** [comment]
The source file was updated in https://github.com/facebook/react/pull/9429/files, so this change should be included the next time the docs are generated 👍

**Comment by gaearon** [comment]
Ah okay, thanks!

**Comment by ivikash** [comment]
👍

**Pull request closed without merging**
