### PR TITLE
[Fizz] Implement Legacy renderToString and renderToNodeStream on top of Fizz

### PR DESCRIPTION
**Pull request by sebmarkbage**
I use a separate build from the main Fizz build because it uses a slightly different configuration. This adds a custom StreamConfig that only uses strings and pushes to a readable-like API.

I enabled the new builds in experimental/modern.

This variant of Fizz uses an infinite progressiveChunkSize and it always waits until everything is completed until starting to write. The effect of this is that the output should never include any scripts and always just render HTML.

Suspending works in both but renderToString switches to client rendering for those cases. renderToNodeStream waits to start writing anything to the stream until they all resolve.

renderToNodeStream will have very different performance characteristics because this new variant will eagerly build up as much HTML as possible as aggressively as possible. This is the new strategy we're going after. If that's not good, then adding more suspense breaks it up. This API should be deprecated and switching to the Fizz model is preferred. While the previous approach of renderToNodeStream is somewhat valid, it's not inline with the future strategy so I don't plan on having a true replacement for CPU throttled. Instead, we could use some level of time slicing at suspense boundary levels in the full Fizz.

This now uses a wrapper around the FormatConfig. This allows us to do custom overrides of the HTML for legacy purposes. This also supports static markup generation (not hydratable HTML). Static mark up isn't legacy per se but the newer version might use something like an optimization of Server Components rather than its own mode. For now, renderToStaticMarkup and renderToStaticNodeStream mode is supported.

### CODE REVIEW

**Comment by curtcurt871** [comment]
sebmarkbage:fizzlegacy

**Comment by curtcurt871** [comment]
#21276

**Comment by sebmarkbage** [comment]
The way this set up works, the stable tests doesn't actually run against stable because jest doesn't use the entry point override thing. That's only set up for builds. Tests against builds run against stable though. But basically because of this, I can't use the test gating feature.

The other issue is that I want to expose both this legacy build and unstable-fizz on a single export. Because when migrating you shouldn't need to migrate to a new name and then back later.

So we'll need to put some significant build/test infra work in to land this.

**Comment by wood1986** [comment]
Hey @sebmarkbage, I have questions about `Readable` in `ReactMarkupReadableStream`. Instead of using `Readable`, is `ReactMarkupReadableStream` possible to extends from web stream [`ReadableStream`](https://nodejs.org/api/webstreams.html#class-readablestream) in the future?

Currently, I am trying to use cloudflare worker to do the SSR rendering. I have my own webpack plugin to build the js for cloudflare worker to run. My own plugin currently needs to specify the fallback for two dependencies `stream` and `util` with `stream-browserify` and `util`. They will be included in SSR js and I do not want that.

If `ReactMarkupReadableStream` extends [`ReadableStream`](https://nodejs.org/api/webstreams.html#class-readablestream), then I do not need to specify the fallback. `stream-browserify` and `util` will not be included in my SSR js for cloudflare to run.

**Pull request merged**
