### PR TITLE
Pull all docs updates from 15-stable into 15.6-dev

### PR DESCRIPTION
**Pull request by flarnie**
In order to ensure consistency between the 15-stable and 15.6 branches, we found all the diffs present only in 15-stable and cherry-picked them onto 15.6-dev.

These are 100% documentation updates, which is why we didn't bother cherry-picking them in the first place, but having them on the 15.6-dev branch makes the two branches more consistent and that is better.

- Nobody will accidentally see outdated docs on the 15.6-dev branch
- these diffs won't somehow be lost or overwritten when we combine the branches to release 15.6.

**Test Plan:**
Manually tested the docs, looking at many of the updated pages. Also ran all tests etc.

### CODE REVIEW

**Comment by gaearon** [comment]
Are you sure this was necessary?

I’m worried this can create confusion and potential issues later on when merging `15.6` into `15-stable`. Because now these are two separate “branches” with the same content stuffed into commits (one squashed commit on `15.6-dev` from this PR versus many separate commits on `15-stable`). Since these commits are technically different, git won’t recognize them as “the same” commit, and so merging `15.6-dev` into `15-stable` will now likely produce conflicts.

I tried this locally and indeed `git merge 15.6-dev` while I’m on `15-stable` creates conflicts:

screen shot 2017-06-08 at 00 05 02

>these diffs won't somehow be lost or overwritten when we combine the branches to release 15.6.

I don't think this would happen though. We always release from the stable branch. So I presume that releasing would involve merging `15.6-dev` into `15-stable`. This would apply 15.6-specific commits to it, but would not touch any changes to docs that already happened on `15-stable`.

Since git won’t revert anything by itself, only if you tell it to during conflict resolution (which likely wouldn’t happen because `15.6-dev` shouldn’t touch docs). But this only works if we don’t cherry-pick them back (which we did in this PR).

I tried resetting `15.6-dev` to the version before this PR was merged, and indeed it can be merged into `15-stable` without conflicts:
screen shot 2017-06-08 at 00 07 28


If this makes sense I would probably recommend force-pushing e5b3554edc4d20ac0e046db620c8aa8bbd2f47f4 onto `15.6-dev` to restore the state before this commit.

Sorry if I’m missing something!

**Comment by flarnie** [comment]
> If this makes sense I would probably recommend force-pushing e5b3554 onto 15.6-dev to restore the state before this commit.

This does make sense - asking how we actually do the release was next on my list, and knowing that we will rebase the 'dev' branch onto the 'stable' one means this should be reverted. I'll do what you suggested, thanks for writing this up.

**Comment by gaearon** [comment]
In terms of the order in which branches get merged into each other [this page](https://github.com/facebook/react/blob/master/scripts/release-manager/Readme.md) should give a good approximation, although the parts about Release Manager can be ignored since we’ve diverged too much (and it only picks things from master).

**Comment by gaearon** [comment]
I imagine we’ll want to:

* Merge `15-stable` into `15-dev` (to bring it to the same level since previous release)
* Merge `15.6-dev` into `15-dev` (to add upcoming stuff there)
* Perhaps cut another RC from `15-dev`
* When ready, merge `15-dev` into `15-stable`
* Finally, release from `15-stable`

We could also skip `15-dev` completely since `15.6-dev` kinda plays the same role now, but it's a bit confusing to leave it behind because it still exists.

**Pull request merged**
