### PR TITLE
Add capture to supported attributes

### LINKED ISSUE #3948: Missing `capture` attribute in `<input type="file" />`
Consider following snippet:

```
var UploadImage = React.createClass({
  render: function() {
    return (
      <input type="file" multiple={true} capture={true} accept="image/*" />
    );
  }
});
```

**Expected DOM**

```
<input type="file" multiple capture accpet="image/*" />
```

**Current behaviour**

```
<input type="file" multiple accpet="image/*" />
```

Demo: [jsbin](http://jsbin.com/yoguti/1/edit?html,js)
W3C Specs: [http://www.w3.org/TR/html-media-capture/](http://www.w3.org/TR/html-media-capture/)

### PR DESCRIPTION
**Pull request by cody**
Fixes #3948

### CODE REVIEW

**Comment by syranide** [comment]
:+1: http://www.w3.org/TR/html-media-capture/#the-capture-attribute

**Comment by chicoxyzzy** [comment]
@syranide can you explain what is the difference between `MUST_USE_ATTRIBUTE ` and `MUST_USE_PROPERTY ` and why for example `checked` and `multiple` are `MUST_USE_PROPERTY | HAS_BOOLEAN_VALUE` and `capture` should be `MUST_USE_ATTRIBUTE | HAS_BOOLEAN_VALUE `?
I don't see any difference between [`input type=text`](http://www.w3.org/TR/html-markup/input.text.html#input.text-interface)'s, [`input type=checkbox`](http://www.w3.org/TR/html-markup/input.checkbox.html#input.checkbox-interface)'s and others' attributes and [input's capture](http://www.w3.org/TR/html-media-capture/#the-capture-attribute) attribute
that's why I made [PR](https://github.com/facebook/react/issues/3949) where capture is `MUST_USE_PROPERTY | HAS_BOOLEAN_VALUE`

**Comment by syranide** [comment]
@chicoxyzzy Some only exist as HTML-attributes whereas some also exist as JS-properties. I assume `capture` is a JS-property too, but since React is rather naive in this area right now it does not recognize that older browsers have no concept `capture` and thus have no JS-property for it. So it's only setting the attribute that works consistently cross-browser (it has no effect, but keeps the DOM correctly synchronized).

**Comment by chicoxyzzy** [comment]
this makes sense. should I close #3849 ?

**Comment by zpao** [comment]
@cody have you tested this in a React component that changes from true -> false & vice versa to ensure the DOM gets updated appropriately?

**Comment by cody** [comment]
@zpao I had only done some tests in the console. Now I have made a proper test with a React component. I tested in Chrome, Firefox and Safari on the desktop. And also in Android's Chrome. Adding and removing the attribute works fine. (On Android it was a bit creepy, because it opens the camera without asking.)

**Comment by zpao** [comment]
:thumbsup: Thanks for testing! Should be good to go then.

**Pull request merged**
