### PR TITLE
Remove missing link.

### PR DESCRIPTION
**Pull request by koba04**
Where is the sophisticated example?

Does it mean the MarkdownEditor?
http://facebook.github.io/react/index.html

### CODE REVIEW

**Comment by kassens** [comment]
@jsfb You made this change in 6f44f6049edfd7a66448ac50cd4415f6c26fd4b5. What page did you mean to link?

**Comment by kassens** [comment]
The same bad link is on http://facebook.github.io/react/tips/dangerously-set-inner-html.html and should be updated/removed.

**Comment by koba04** [comment]
@kassens Thank you for your comments!

It seems
* Remove the link from http://facebook.github.io/react/tips/children-undefined.html
* The link in http://facebook.github.io/react/tips/dangerously-set-inner-html.html should be `/react/`.

If correct, I'm going to fix that together.

**Comment by jsfb** [comment]
Oh, just realized this was a PR instead of an open issue.  All I saw was that @spicyj assigned it to me :).  Oh well.

Yeah, I think the line about the sophisticated example was supposed to move from docs/docs/ref-07-special-non-dom-attributes.md to 19--dangerouslySetInnerHTML.md, but somehow (erroneously) replaced the last line of children-undefined.

**Comment by spicyj** [comment]
We'll go with #3723 – @koba04 thanks for bringing this up!

**Comment by koba04** [comment]
Thanks!

**Pull request closed without merging**
