### PR TITLE
Remove redundant initial of isArray

### PR DESCRIPTION
**Pull request by behnammodi**
All test passed

@sebmarkbage @gaearon

### CODE REVIEW

**Comment by behnammodi** [comment]
Also, I can separate these items:

```
Number.NaN
Number.MAX_VALUE
Number.POSITIVE_INFINITY
Number.NEGATIVE_INFINITY
Number.isNaN

String.fromCharCode

Array.from

Object.getOwnPropertySymbols
Object.getOwnPropertyNames
Object.getOwnPropertyDescriptor
Object.defineProperty
Object.defineProperties
Object.freeze
Object.keys
Object.assign
Object.create
Object.getPrototypeOf
Object.entries
Object.preventExtensions
Object.seal
```

**Comment by behnammodi** [comment]
@sebmarkbage Did you see my last comment?

**Comment by sebmarkbage** [comment]
A lot of those are only used in DEV mode or tooling which are less size/perf sensitive so they matter less.

**Comment by behnammodi** [comment]
All of them?

**Comment by sebmarkbage** [comment]
I'm not sure why it looked like CI was passing on this PR but looks like Flow got broken because it can no longer figure out that isArray should use refinement.

**Comment by behnammodi** [comment]
Yeah I see that and test all test in local everything works!

**Comment by behnammodi** [comment]
@sebmarkbage These files have problems

```
packages/react-devtools-shared/src/backend/utils.js
packages/react-reconciler/src/ReactFiberReconciler.new.js
packages/react-reconciler/src/ReactFiberReconciler.old.js
packages/react-server/src/ReactFizzServer.js
packages/react/src/ReactChildren.js
```

I got this error and I don't know why!

Screen Shot 2021-04-02 at 1 03 57 AM

**Comment by behnammodi** [comment]
@sebmarkbage Hi, do we have any updates about this issue?

**Comment by behnammodi** [comment]
@sebmarkbage Thanks and I think this PR needs to reland https://github.com/facebook/react/pull/21165

**Pull request merged**
