### PR TITLE
Delete PATENTS

### LINKED ISSUE #10191: Consider re-licensing to AL v2.0, as RocksDB has just done
Hi there,

The Apache Software Foundation Legal Affairs Committee [has announced][1] that the so-called 'Facebook BSD+Patents License' is no longer allowed to be used as a direct dependency in Apache projects.

This has lead to a lot of upset and frustration in the Apache community, especially from projects requiring similarly-licensed code as direct dependencies - the chief of these being RocksDB.

However, we (the Apache Software Foundation) have just received word that [RocksDB will be re-licensing their code under the dual Apache License v2.0 and GPL 2 licenses][2]. 

As a user of React.JS in an ASF top-level project (Apache CouchDB), please consider re-licensing React.JS under similar terms. Otherwise, many ASF projects such as our own will have to stop relying on and building with React.

A previous bug (#9760) suggested I mention @lacker in this issue when asking licensing questions, so I'm doing so.

Thank you kindly for your consideration.

[1]: https://issues.apache.org/jira/browse/LEGAL-303?focusedCommentId=16088663&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16088663
[2]: https://issues.apache.org/jira/browse/LEGAL-303?focusedCommentId=16088730&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16088730

### PR DESCRIPTION
**Pull request by jdrago999**
Resolves #10191

### CODE REVIEW

**Comment by webhat** [comment]
:+1:

**Comment by empressplay** [comment]
👍

**Comment by LeoNatan** [comment]
👍

**Comment by gaearon** [comment]
Sorry but this is not productive.

These decisions are taken by our legal department. We will link them to these discussions, as we have always done.

But as maintainers we have no power to change or delete legal files.

**Comment by gaearon** [comment]
We’re relicensing React, Jest, Flow, and Immutable.js under the MIT license. 
I hope that this addresses your concerns.

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

**Pull request closed without merging**
