### PR TITLE
Keep value of controlled number fields upon action

### LINKED ISSUE #29862: [React 19] Controlled number input does not update defaultValue when value prop has changed
## Summary

Controlled inputs with the `type=number` are not setting the `defaultValue` when the value state is altered. This causes the state and value to become out of sync when a form is reset (for instance after a form action is sent).

Screenshot 2024-06-11 at 1 12 08 PM

https://codesandbox.io/p/github/BrendonSled/react-19-controlled-input-number-bug/

### PR DESCRIPTION
**Pull request by vordgi**
## Summary

Currently, React changes the defaultValue for number fields not on every change, but on blur. The reasons are described in issue #7253.

Now this bug is not reproducible in Chrome. Just to be sure, I checked that it was fixed specifically in Chrome, and not with some React update (_I ran React v15.2 in modern Chrome and there were no issues from the task there either_).

I extended the `EventPlugin`, making the replacement of `defaultValue` not only on blur, but also on submit (_since you can press Enter without leaving the field and the form will be submitted_). But I did it specifically on the `keypress` event, so that it works before reset and on the submit itself without a submitter (_this is, for example, when calling `requestSubmit()`_).

Added a "`force`" option in `setDefaultValue`, because a numeric field can be in focus (_and on submit, the value needs to be changed always_).

I honestly tried to cover this with tests, but couldn't find a way to trigger submit by simulating a key press...

Fixes #29862
Closes #29862

## How did you test this change?

Before fix:

https://github.com/user-attachments/assets/d6dcc871-9c50-4dbe-a1b9-00f97e8e6a91

After fix:

https://github.com/user-attachments/assets/b2886a6c-77e8-4b5f-ab8d-322d24165b72

### CODE REVIEW

**Comment by vordgi** [comment]
Fixes #29862
Closes #29862

**Comment by sebmarkbage** [comment]
This makes sense to me but maybe needs another pair of eyes. I'm not sure this is exhaustive since you can trigger actions and resets in arbitrary way - such as based on a different keystroke.

Ideally maybe it would sync it right before resetting.

**Review by sebmarkbage — APPROVED** [review]

**Comment by sophiebits** [comment]
I don't really like doing it in keypress, that seems too clever given that it's not exhaustive… should we do it in the `submit` event handler only?

**Comment by vordgi** [comment]
_Working on another solution with more changes_

**Comment by vordgi** [comment]
Opened a new PR with different solution (_which I think is more correct_) - #30752

**Comment by vordgi** [comment]
_Closing this, as there is a more suitable solution in #30752_

**Pull request closed without merging**
