### PR TITLE
Add FB_WWW_MODERN bundle types

### PR DESCRIPTION
**Pull request by gaearon**
So that we can start testing slimmer builds internally.

Currently these are 100% matching the FB_WWW classic builds. I verified by building both modes and diffing them. In a follow-up PR, I will fork the feature flags and make some other changes for them.

### CODE REVIEW

**Comment by gaearon** [comment]
That was exactly what I suggested to Seb, but he said he wants another feature flag file instead. Either I misunderstood what he was proposing, or we might want to chat about this all together.

**Comment by gaearon** [comment]
That said, I find the idea of “experimental” meaning different things in fbsource and WWW scary. That’s why I scoped it to clearly be a WWW only thing.

**Comment by acdlite** [comment]
Might have been a misunderstanding. @sebmarkbage and I chatted offline. Let’s discuss at the meeting!

**Comment by gaearon** [comment]
Cool, no worries! Just want to make sure we agree 100% before I rewrite :-)

**Comment by gaearon** [comment]
>The names of all the files are identical except for which subdirectory they live in.

We'll have to enable Haste packages for this to work, right? I guess you need to either way because of the "two Reacts" thing.

**Pull request closed without merging**
