### PR TITLE
[fabric] Forked ReactNativeInjection and skip RCTEventEmitter for Fabric

### PR DESCRIPTION
**Pull request by fkgozali**
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. Run `yarn` in the repository root.
3. If you've fixed a bug or added code that should be tested, add tests!
4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.
5. Run `yarn test-prod` to test in the production environment. It supports the same options as `yarn test`.
6. If you need a debugger, run `yarn debug-test --watch TestName`, open `chrome://inspect`, and press "Inspect".
7. Format your code with [prettier](https://github.com/prettier/prettier) (`yarn prettier`).
8. Make sure your code lints (`yarn lint`). Tip: `yarn linc` to only check changed files.
9. Run the [Flow](https://flowtype.org/) typechecks (`yarn flow`).
10. If you haven't already, complete the CLA.

**Learn more about contributing:** https://reactjs.org/docs/how-to-contribute.html

```
yarn test
...
Test Suites: 138 passed, 138 total
Tests:       26 skipped, 2837 passed, 2863 total
Snapshots:   29 passed, 29 total
Time:        57.346s
Ran all test suites.
✨  Done in 59.82s.
```
```
yarn linc
Using globally installed version of Yarn
yarn run v1.2.0
$ node ./scripts/tasks/linc.js
Linting changed files...
> git merge-base HEAD master
> git diff --name-only --diff-filter=ACMRTUB b17e4c204e05de5ee360910626b0ccc938f37c06
> git ls-files --others --exclude-standard

Lint passed for changed files.
✨  Done in 1.80s.
```
```
yarn flow
Using globally installed version of Yarn
yarn run v1.2.0
$ node ./scripts/tasks/flow.js
Found 0 errors
Flow passed
✨  Done in 7.27s.
```

Additional tests:
* `yarn build` then copied `build/react-native/ReactNativeRenderer-dev.js` to ReactNative local copy
* verified that RN test app loaded and didn't redbox

### CODE REVIEW

**Comment by fkgozali** [comment]
cc @bvaughn

**Comment by sebmarkbage** [comment]
Approved and passes all tests. Added you to the team so feel free to "Squash and merge" when you're comfortable with it.

**Comment by bvaughn** [comment]
Welcome to the team, Kevin 😄

**Comment by bvaughn** [comment]
PS. "_all tests_" 😆

**Comment by fkgozali** [comment]
w00t

**Pull request merged**
