### PR TITLE
[WIP] Add SSR description in Doc

### PR DESCRIPTION
**Pull request by ryota-murakami**
screen shot 2018-08-13 at 15 25 32

# Why
SSR document does not exist in the official document right now.

This means that you can't find a way 「How to SSR with React」from the official document searchbox,
and you have to rely on an external blog such as Medium.
External blog is pretty good, but I think more ideal if there is the 「How to SSR with React」.
- Doesn't contain other popular library settings.
- You don't have to confirm is the article based on latest version React.

# What am I going to do?

- [ ] Write「How to SSR with React」Doc among with [SSR Fixtures](https://github.com/facebook/react/tree/master/fixtures/ssr)

### CODE REVIEW

**Comment by ryota-murakami** [comment]
@vikaskyadav I'm afraid, I don't commit yet, work in progress now😅

**Comment by vikaskyadav** [comment]
Then it is fine 😅

**Comment by nhunzaker** [comment]
Hey @ryota-murakami, I'm closing this out because there aren't any changes and this feels like it should be an issue over at the website repo.

Could you file this as an issue on https://github.com/reactjs/reactjs.org/issues ?

**Comment by nhunzaker** [comment]
Cool. I'll look out for it!

**Pull request closed without merging**
