### PR TITLE
update to use spyOn for console.warn #2749

### PR DESCRIPTION
**Pull request by kevinold**
@zpao I made consistent using spyOn for all of the instances I found mocking console.warn vs using spyOn (per your request https://github.com/facebook/react/issues/2749#issuecomment-71144536).

I did not find instances of any other console methods (error, log, dir) using a different syntax than spyOn.

### CODE REVIEW

**Comment by jeffbski** [comment]
+1

**Comment by kevinold** [comment]
@zpao @spicyj  Updated this one too with latest master this evening.

**Comment by sebmarkbage** [comment]
Nice! We'll need to figure out how to statically type spyOn but at least now it's consistent.

**Comment by zpao** [comment]
Awesome, let's do it. Thanks!

**Comment by sebmarkbage** [comment]
I think we may have added some more. :)

**Pull request merged**
