### PR TITLE
isRequiredIf proptype feature

### PR DESCRIPTION
**Pull request by evcohen**
Hey everyone, thanks for all of your work here on React. First PR!

I ran into a use case the other day where I wanted to conditionally enforce isRequired based on another prop's existence. It was fairly simple using a custom validator but this required re-implementing all of the type checking that comes for free with PropTypes anyway. With this change, it will introduce chaining any propType with `isRequiredIf(condition)` where `condition` can be a boolean or a function that returns a truthy value. 

The function has the same arguments as a custom propType validator: 
`isRequiredIf((props, propName, componentName) => props.hasOwnProperty('otherProp'))`

Thanks!

### CODE REVIEW

**Comment by jimfb** [comment]
Thanks for the PR!

As per https://github.com/facebook/react/issues/5080#issuecomment-146373158: 
 > propTypes are mostly in a sort of maintenance mode and we're not really planning to add more to them right now.

Proptypes are being replaced by static analyzers like Flow.  For this reason, I'm thinking we probably won't merge this.  However, I would encourage you to publish your proptype online so others can use it.

If you're looking for ways to get involved in React development, I'd recommend checking out the [good first bug](https://github.com/facebook/react/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+bug%22) list, which has a bunch of things that need fixing :).

**Comment by evcohen** [comment]
@jimfb Thanks for the thoughtful reply. This feature doesn't really work well as its own proptype since it should be chained onto React's built-in proptypes, but I will try and come up with a solution using a custom proptype. Thanks!

**Comment by evcohen** [comment]
https://github.com/evcohen/react-proptype-conditional-require

Thanks @jimfb

**Comment by joshuapinter** [comment]
@evcohen You did a great job with this! It's too bad that `prop-types` is in maintenance mode now and won't merge this in. 

The company I work for went ahead and created a fork that adds `isRequiredIf` functionality. It takes a function and gets passed the props, like: 

```js
id: PropTypes.number.isRequiredIf( props => !props.uid )
```

It doesn't take a boolean like yours does because we didn't require that. 

Anyway, just wanted to say thanks for your efforts and if anybody is still stuck using `prop-types` and wants to use a natural syntax for conditional requirements, feel free to use it. It can be found here: 

https://github.com/cntral/prop-types/tree/isRequiredIf

And you can easily use it in your `package.json` like so: 

```json
"prop-types": "github:cntral/prop-types#isRequiredIf"
```

🍻

**Pull request closed without merging**
