### PR TITLE
Add support for SVG clip-path attribute

### PR DESCRIPTION
**Pull request by kraf**
Added support for SVG clip-path attribute, ad #1657

See https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clip-path for details

### CODE REVIEW

**Comment by ghost23** [comment]
Wouldn't it make sense to also support the clipPath svg element then?!

**Comment by btholt** [comment]
This is a simple change that would be very beneficial to us at reddit right now. Any chance this can get merged? :)

**Comment by sebmarkbage** [comment]
@ghost23 You can already do `React.createElement('clipPath')` or `<clipPath />`, right?

**Comment by sebmarkbage** [comment]
We'll bring this in but it didn't make the cut for 0.13. Note that any new attribute is a potentially breaking change.

```javascript
var Component = React.createClass({
  return <div {...this.props}><span>Clip: {this.props.clipPath}</span></div>;
});
```

This is currently ignored but will now start transferring to the DOM. It is probably safe to assume that the DOM ignores it but in the case of nested SVG children it might not.

We're working on getting rid of the whitelist completely. Step one is #3104

**Comment by ghost23** [comment]
@sebmarkbage Hi. Well, React.createElement('clipPath') works, but it is not supported in jsx. The docs also do not mention clipPath as a supported svg element.

**Comment by sebmarkbage** [comment]
I believe it should be support in JSX in 0.13 RC2.

**Pull request closed without merging**
