### PR TITLE
[Flight] Ship DEV-only enableServerComponentLogs flag in Stable/Canary

### PR DESCRIPTION
**Pull request by sebmarkbage**
To recap. This only affects DEV and RSC. It patches console on the server in DEV (similar to how React DevTools already does and what we did for the double logging). Then replays those logs with a `[Server]` badge on the client so you don't need a server terminal open.

This has been on for over 6 months now in our experimental channel and we've had a lot of coverage in Next.js due to various experimental flags like taint and ppr.

It's non-invasive in that even if something throws we just serialize that as an unknown value.

The main feedback we've gotten was:

- The serialization depth wasn't deep enough which I addressed in #30294 and haven't really had any issues since. This could still be an issue or the inverse that you serialize too many logs that are also too deep. This is not so much an issue with intentional logging and things like accidental errors don't typically have unbounded arguments (e.g. React errors are always string arguments). The ideal would be some way to retain objects and then load them on-demand but that needs more plumbing. Which can be later.
- The other was that double logging on the server is annoying if the same terminal does both the RSC render and SSR render which was addressed in #30207. It is now off by default in node/edge-builds of the client, on by default in browser builds. With the `replayConsole` option to either opt-in or out.

We've reached a good spot now I think.

These are better with `enableOwnerStacks` but that's a separate track and not needed.

The only thing to document here, other than maybe that we're doing it, is the `replayConsole` option but that's part of the RSC renderers that themselves are not documented so nowhere to document it.

### CODE REVIEW

**Review by eps1lon — COMMENTED** [review]
Should we enable it based on `__VARIANT__` in www-dynamic so that we have some coverage for the old behavior until we clean it up?

I thought it was still double logging on the server terminal in Next.js so I'd like to double check.

**Comment by sebmarkbage** [comment]
> Should we enable it based on __VARIANT__ in www-dynamic so that we have some coverage for the old behavior until we clean it up?

I was just going to clean it up pretty soon after anyway since it's on everywhere.

**Comment by eps1lon** [comment]
Makes sense. It's been on in vercel.com for a while now.

**Review by eps1lon — APPROVED** [review]

**Comment by sebmarkbage** [comment]
Can bring up for further discussion if needed but this has a simple opt-out so it's not really that invasive.

**Pull request merged**
