### PR TITLE
Fix error loading source maps for devtools extension

### PR DESCRIPTION
**Pull request by sytranvn**
## Summary

**Issue** #20075. 
- Fix Devtools failed to load source map warning by reverting the changes from #19773 for `packages/react-devtools-extensions`.

## Test Plan
Current warning
image

Fixed on Chrome
image
image

Firefox
image

### CODE REVIEW

**Review by bvaughn — CHANGES_REQUESTED** [review]
Please also revert the changes to the 3 `manifest.json` files from that PR?

**Review by bvaughn — APPROVED** [review]

**Comment by bvaughn** [comment]
This looks good, but I can't merge it until you accept the Contributor License Agreement.

**Comment by sytranvn** [comment]
@bvaughn I accepted but I think it can take awhile to recheck. Can you trigger it manually :joy_cat:

**Comment by sytranvn** [comment]
Thanks for your guidance :+1:

**Comment by GuillaumeCisco** [comment]
Should we now wait for a new version of react-devtools-extension?

**Comment by bvaughn** [comment]
Yes, @guillaumeaubert. Same as with other bug fixes. :)

**Comment by mopsek** [comment]
Nice!

**Comment by lantanios** [comment]
Update:

Was getting 3 warnings, now just one left:
Updated react to 17.0.1 and reinstalled extension.

image

**Comment by goacgras** [comment]
> Update:
> 
> Was getting 3 warnings, now just one left:
> Updated react to 17.0.1 and reinstalled extension.
> 
> image

same here

**Comment by bvaughn** [comment]
That's interesting. This PR has not been released yet, so any change of behavior is on the browser side.

**Comment by bvaughn** [comment]
This change has been published to NPM and Chrome/Edge/Firefox as v4.10

**Pull request merged**
