### PR TITLE
Fix warning deduplication in attribute table

### PR DESCRIPTION
**Pull request by gaearon**
This avoids the need to manually patch React locally because of deduplication hiding warnings.
It takes us further from https://github.com/facebook/react/pull/10587 but I think that:

* We don't want to run headless Chrome as part of every test run anyway
* We can still add a "Save" button and a script that runs `yarn start` and presses it if we want to

But at least the data generated by this is more accurate than the current version.

### CODE REVIEW

**Comment by bvaughn** [comment]
After pulling this branch, the attr test harness totally crushes my Chrome. So bad that I can't even use Chrome's Task Manager to kill tabs.

**Comment by bvaughn** [comment]
It actually hung so badly I restarted my computer initially. Then as soon as I tried re-opening Chrome- (because of the service workers)- it auto-started and did the same thing. Took me a few minutes of trying to close the tab before it finally closed, then everything was back to normal

**Comment by gaearon** [comment]
Weird, it works consistently for me. Note it’s supposed to take about a minute — you can see the progress in Chrome title bar.

**Comment by bvaughn** [comment]
Yeah, I know. The tab titles were about the only thing that updated during the time, although much slower than what your screenshot is showing.

**Comment by gaearon** [comment]
What laptop are you using?

**Comment by bvaughn** [comment]
Work laptop (MacBook Pro, 2.8 GHz i7, 16GB ram).

**Comment by gaearon** [comment]
Are you on power?

**Pull request merged**
