### PR TITLE
Discard incorrect KeyboardEvent.key values for onKeyDown and onKeyUp in IE

### PR DESCRIPTION
**Pull request by syranide**
TL;DR-comment has in-depth explanation. Summary; all IE report `AltGr+1` as `'1'`, `~a` as `'a'` (`~` is a deadkey), etc in `keydown` and `keyup`, rather than the actual produced character. This normalizes that behavior to report `Unidentified` instead which is far preferable.

While it's quite technical, I think the logic is fairly self-explanatory and should be inherently safe (especially as none of the other browser I have access to even support `char`).

Test plan: manually in the browser
If approved: will need to do an exhaustive test of all keys do make doubly-sure

### CODE REVIEW

**Comment by zpao** [comment]
cc @salier. This is way outside my comfort zone. We already accepted it but it never got merged and so I think we should do another pass review before it goes in.

**Comment by syranide** [comment]
@zpao Yeah I'm supposed to do another review/test and keyboard event testing is kind of annoying, so I just haven't got around to it yet. :)

**Comment by salier** [comment]
This seems fine to me. It's a little unclear from the comments what exactly `char` is expected to be if supported but not populated -- "empty string" would be clearer than "no character". Otherwise, the `if (char)` line is confusing. (Unless I'm missing something here.)

Curious about the same thing as @sebmarkbage, is this also being done elsewhere?

**Comment by syranide** [comment]
@salier 

> It's a little unclear from the comments what exactly `char` is expected to be if supported but not populated

`key` refers to a virtual/keyboard key, `char` refers to a printable character. When `char` is empty it's because no printable character was associated with (or "recognized" for) the key press. `alt+key` does sadly not generate a `char` in IE, but this PR uses that to report `Unidentified` instead because it's far better than reporting the wrong key/char.

Should I clarify in the comments?

> Curious about the same thing as @sebmarkbage, is this also being done elsewhere?

No idea, I arrived at this solution from my own experimentation, but I doubt it. I could look around if necessary but AFAIK most don't really try that hard to normalize behavior it seems. They polyfill and fix obviously broken behavior, but they rarely normalize very extensively.

**Comment by salier** [comment]
> When char is empty it's because no printable character was associated with (or "recognized" for) the key press.

Yeah, my only issue was with the wording in the comment block -- "no character" could be construed as other values, while "empty string" is precisely one thing. :)

> I could look around if necessary but AFAIK most don't really try that hard to normalize behavior it seems.

Eh, I think we're probably okay here.

**Comment by gaearon** [comment]
This doesn’t merge cleanly today, and it doesn’t look like anyone on the team is ready to “own” this change, test it extensively, and later support it. Since other libraries don’t seem to perform this normalization and there doesn’t appear enough interest, I am closing it.

If somebody else in the community is affected by this bug please let us know. So far it doesn’t seem to be enough interest to warrant handling this case specially, and one can always do this manually by inspecting `nativeEvent`. It’s not ideal but it’s a reasonable workaround if it affects your app until there is more desire to get this fixed in the community.

Thanks for the PR though!

**Pull request closed without merging**
