### PR TITLE
Fix Flow issue and revert to showing "Unknown" in warnings for anonymous components

### PR DESCRIPTION
**Pull request by edvinerikson**
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`).
6. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
7. If you added or removed any tests, run `./scripts/fiber/record-tests` before submitting the pull request, and commit the resulting changes.
8. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

### CODE REVIEW

**Comment by edvinerikson** [comment]
I can't really understand why it fails

**Comment by gaearon** [comment]
The CI shows that a previously passing test now fails in Fiber mode:

```diff
--- a/scripts/fiber/tests-passing-except-dev.txt
+++ b/scripts/fiber/tests-passing-except-dev.txt
@@ -116,3 +116,4 @@ src/renderers/shared/shared/__tests__/ReactMultiChild-test.js
 
 src/renderers/shared/shared/__tests__/ReactStatelessComponent-test.js
 * should warn for childContextTypes on a functional component
+* deduplicates ref warnings based on element or owner
diff --git a/scripts/fiber/tests-passing.txt b/scripts/fiber/tests-passing.txt
index 050dd41..189f341 100644
--- a/scripts/fiber/tests-passing.txt
+++ b/scripts/fiber/tests-passing.txt
@@ -1560,7 +1560,6 @@ src/renderers/shared/shared/__tests__/ReactStatelessComponent-test.js
 * should throw on string refs in pure functions
 * should warn when given a string ref
 * should warn when given a function ref
-* deduplicates ref warnings based on element or owner
 * should provide a null ref
```

Read how to run tests in Fiber mode: https://github.com/facebook/react/issues/7925#issuecomment-259258900.

**Comment by gaearon** [comment]
It's likely failing because two different classes are `Unknown` in that test, and it gets deduplicated.

**Comment by gaearon** [comment]
Okay, so it turned we have a bunch of call sites that explicitly check for `!= null` result and have special logic when the name is not available (e.g. don’t print an extra useless message like `Check the render method of Unknown component`).

So `null` was useful after all.

**Comment by edvinerikson** [comment]
Yeah I noticed that as well. I will revert to null

**Comment by gaearon** [comment]
Sorry for the churn 😅

**Comment by edvinerikson** [comment]
No worries :D

**Comment by gaearon** [comment]
I don't think this will pass Flow, would it? It’s effectively `?string` now.

**Comment by edvinerikson** [comment]
oops.. missed that one..

**Comment by edvinerikson** [comment]
success 🎉

**Pull request merged**
