### PR TITLE
Don't add dangling commas to functions for packaging fixtures

### PR DESCRIPTION
**Pull request by bvaughn**

### CODE REVIEW

**Comment by gaearon** [comment]
I hope CI passes 😄

**Comment by bvaughn** [comment]
☹️  Bad Brian.

**Comment by bvaughn** [comment]
Hm. Running `yarn prettier` in master shows no changes, just as was the case in this branch, but CI thinks it does.

**Comment by bvaughn** [comment]
Weird. Stepping back to the commit before this and running `node ./scripts/prettier/index.js` also fails for me with the same error.

**Pull request merged**
