### PR TITLE
Remove one extraneous backtick from line 116 of 'codebase-overview.md' (#8274).

### PR DESCRIPTION
**Pull request by richiethomas**
*Before* submitting a pull request, please make sure the following is done...

1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`) - we've done our best to make sure these rules match our internal linting guidelines.
6. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

### CODE REVIEW

**Comment by gaearon** [comment]
This looks right, why did you close it?

**Comment by richiethomas** [comment]
The issue # in the commit message was incorrect.  I had written "8274" instead of "8724".

**Comment by aweary** [comment]
@richiethomas for future reference you can edit titles, no need to create a new PR for typos

**Comment by acdlite** [comment]
In the future, you can amend your commit (`git commit --amend`) to change the commit message then force push (`git push -f`) to your branch to update it. The PR will update to reflect.

**Comment by richiethomas** [comment]
Good to know.  I did do a commit amend followed by a force push to my fork, but I was unaware that would be reflected in the PR.  Will keep in mind for future reference, thanks.

**Pull request closed without merging**
