### PR TITLE
Fix #5726

### LINKED ISSUE #5726: Support SVG stroke-linejoin attribute
Support SVG `stroke-linejoin` attribute

### PR DESCRIPTION
**Pull request by meghprkh**
Add support for SVG stroke-linejoin attribute

See #5726

### CODE REVIEW

**Comment by zpao** [comment]
Note: we will probably not take this. We're working on an effort to allow all SVG attributes to pass through in #5714.

**Comment by meghprkh** [comment]
@zpao That's great. In fact I believe that you shall let all attributes pass through and just convert them from CamelCase to hifenated forms if react doesn't recognize the attribute. I believe that this should be closed then

**Comment by zpao** [comment]
👍 I'm going to leave it open for the time being and we'll close all of the SVG issues/PRs in bulk (to make sure we haven't missed anything).

**Comment by gaearon** [comment]
>In fact I believe that you shall let all attributes pass through and just convert them from CamelCase to hifenated forms if react doesn't recognize the attribute

The current thinking in #5714 is not to be smart about it and to pass them through exactly as the user specifies. This way we don't need to care whether we are aware of all possible camel cased attributes that really *are* camel cased in the spec (there are quite a few!)

**Comment by gaearon** [comment]
Verified that `stroke-linejoin` works in master when specified as is.

**Pull request closed without merging**
