### PR TITLE
Attach display name to method

### PR DESCRIPTION
**Pull request by bendyorke**
This fixes issue #3173, and is a refactoring of pr #6404.  I know `createClass` is going out of fashion, but thought it might as well get in now! #reactEurope-hackathon

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by bendyorke** [comment]
I've signed the CLA now, let me know if there are any other issues/comments!

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by gaearon** [comment]
This doesn’t merge cleanly. Can you rebase please? Thanks!

**Comment by alexzherdev** [comment]
I can pick this up if @bendyorke doesn't come around.

**Comment by aweary** [comment]
Thanks for the PR @bendyorke, but per https://github.com/facebook/react/issues/3173#issuecomment-256477141 we are not going to be making changes to `createClass` anymore.

**Pull request closed without merging**
