### PR TITLE
Open-source React Compiler

### PR DESCRIPTION
**Pull request by josephsavona**
React Compiler is open source!

### CODE REVIEW

**Review by sophiebits — APPROVED** [review]
thanks for including the history ❤️

**Review by rickhanlonii — APPROVED** [review]
LFG

**Comment by josephsavona** [comment]
DONT MERGE

we need to enable merge commits to retain history

**Review by gaearon — COMMENTED** [review]
unreal! congratulations :)

**Comment by matclayton** [comment]
Congrats!

**Comment by cetfu** [comment]
Congrats! 🥳🎉🎉🎉

**Comment by VCasecnikovs** [comment]
Congrats!!!

**Comment by adeleke5140** [comment]
lfggg

**Comment by ephraimduncan** [comment]
The moment react changed forever🎊

**Comment by DarrenBaldwin07** [comment]
Hell yeah!

**Comment by Fizzify** [comment]
Finally!

**Comment by ClockRide** [comment]
Congrats!! Thank you for your hard work ❤️

**Comment by Sh0ckWaveZero** [comment]
Wow! Congrats

**Comment by migueldaipre** [comment]
Congrats 🎉

**Comment by abhijeetpandit7** [comment]
This is unreal!

**Comment by yasseralsaidi** [comment]
go react!

**Comment by Huxpro** [comment]
I just feel the vibe that I need to be here!! 🚀

**Comment by lucascaton** [comment]
Yay!

**Comment by janefawkes** [comment]
that is beyond rad! congrats

**Comment by AhmedBaset** [comment]
Congratulations 🎊

**Comment by revskill10** [comment]
+1

**Comment by ren-chon** [comment]
congrats!!

**Comment by rjsdnql123** [comment]
Wow..

**Comment by bayromest** [comment]
yes

**Comment by HugaidaS** [comment]
Congratulations, looking forward to future improvements!)

**Comment by gersomonline** [comment]
You guys are making history 👏

**Comment by shubhxg** [comment]
🔥👏🗿

**Comment by icep0ps** [comment]
Lets go!! 🚀

**Comment by Zaid-maker** [comment]
Fix the workflow please

**Comment by savanesoff** [comment]
Way to go Idaho! :clap: :heart:

**Comment by BibhushanKarki** [comment]
Congrats 🎉

**Comment by ImPavloh** [comment]
LGTM

**Comment by marcelxv** [comment]
🥇

**Comment by ryuhangyeong** [comment]
Congrats!

**Comment by Hamidov6611** [comment]
Well done 😎

**Comment by yug-delemont** [comment]
Congrats 🧑‍💻

**Pull request merged**
