### PR TITLE
Replace hyperlink tag with button tag in tic-tac-toe tutorial and update related references in the tutorial document

### PR DESCRIPTION
**Pull request by pyitphyoaung**
…ate related references in the tutorial document

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run prettier`).
6. Make sure your code lints (`npm run lint`).
7. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
8. If you haven't already, complete the CLA.

### CODE REVIEW

**Comment by gaearon** [comment]
@bvaughn We'll need to update all codepens now, right?

**Comment by gaearon** [comment]
These look confusing as buttons:

screen shot 2017-10-03 at 5 01 22 pm

We should also update their labels. For example

* Go to game start
* Go to move #1

etc

**Comment by gaearon** [comment]
I'll do that.

**Comment by gaearon** [comment]
Done. :-)

**Comment by bvaughn** [comment]
Yeah 😁  [I tagged you on the parent PR about this](https://github.com/facebook/react/pull/11006#issuecomment-333591417)

**Comment by bvaughn** [comment]
You rock! 🎸

**Comment by pyitphyoaung** [comment]
Yay!  Cheers, guys! 😄

**Pull request merged**
