### PR TITLE
Provide esm entry point for react-is

### PR DESCRIPTION
**Pull request by TrySound**
Refs
  https://github.com/facebook/react/issues/13272#issuecomment-409939608
  https://github.com/reactjs/rfcs/pull/38

In this PR I modified build script to generate two more bundles
`react-is.development.mjs` and `react-is.production.min.mjs` and
entry point `index.mjs` which reexports all named values depending on
production/development environments like this

```
import * as dev from './esm/development.mjs'
import * as prod from './esm/production.min.mjs'

export var name =
  process.env.NODE_ENV !== 'production' ? dev.name : prod.name;
```

I replaced closure wrapper with vendor plugin which is able to process
es modules by replacing them before and returning them after closure
minification.

To prove treeshakability of dual entry point we can generate rollup
bundle with `import {} from 'package'`. If nothing will left then
user bundler is able to eliminate unused code from dual entry point.

### CODE REVIEW

**Comment by react-linter** [comment]
React: size: -0.5%, gzip: -0.1%

ReactDOM: size: 0.0%, gzip: 0.0%


  <details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 15a8f031838a553e41c0b66eb1bcf1da8448104d...0fdb3f4c03e31ade13b00e75c06cfbe559752c71</p>


  
## react
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react.development.js | +3.0% | -1.3% | 58.04 KB | 59.77 KB | 16.21 KB | 16 KB | UMD_DEV
**react.production.min.js** | **-0.5%** | **-0.1%** | **7.01 KB** | **6.98 KB** | **2.96 KB** | **2.96 KB** | **UMD_PROD**
react.development.js | -2.0% | -3.0% | 52.23 KB | 51.17 KB | 14.39 KB | 13.95 KB | NODE_DEV
**react.production.min.js** | **-0.6%** | **-0.5%** | **6.02 KB** | **5.98 KB** | **2.57 KB** | **2.55 KB** | **NODE_PROD**
React-dev.js | -1.1% | -1.4% | 50.06 KB | 49.5 KB | 13.8 KB | 13.61 KB | FB_WWW_DEV
**React-prod.js** | **-1.0%** | **-0.7%** | **13.69 KB** | **13.55 KB** | **3.8 KB** | **3.77 KB** | **FB_WWW_PROD**

## react-dom
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-dom.development.js | -0.7% | -4.4% | 643 KB | 638.77 KB | 151 KB | 144.31 KB | UMD_DEV
**react-dom.production.min.js** | **0.0%** | **0.0%** | **96.27 KB** | **96.27 KB** | **31.21 KB** | **31.23 KB** | **UMD_PROD**
react-dom.development.js | -5.4% | -5.4% | 639.14 KB | 604.77 KB | 149.83 KB | 141.67 KB | NODE_DEV
**react-dom.production.min.js** | **0.0%** | **0.0%** | **96.26 KB** | **96.27 KB** | **30.74 KB** | **30.75 KB** | **NODE_PROD**
react-dom-test-utils.development.js | +2.6% | -2.2% | 43.74 KB | 44.9 KB | 11.9 KB | 11.64 KB | UMD_DEV
**react-dom-test-utils.production.min.js** | **:small_red_triangle:+0.1%** | **:small_red_triangle:+0.3%** | **10.06 KB** | **10.07 KB** | **3.72 KB** | **3.73 KB** | **UMD_PROD**
react-dom-test-utils.development.js | -1.9% | -3.1% | 43.46 KB | 42.64 KB | 11.84 KB | 11.47 KB | NODE_DEV
**react-dom-test-utils.production.min.js** | **:small_red_triangle:+0.2%** | **:small_red_triangle:+0.3%** | **9.85 KB** | **9.87 KB** | **3.66 KB** | **3.67 KB** | **NODE_PROD**
react-dom-unstable-native-dependencies.development.js | -0.4% | -5.2% | 58.81 KB | 58.57 KB | 15.4 KB | 14.59 KB | UMD_DEV
**react-dom-unstable-native-dependencies.production.min.js** | **0.0%** | **:small_red_triangle:+0.1%** | **11.04 KB** | **11.04 KB** | **3.8 KB** | **3.8 KB** | **UMD_PROD**
react-dom-unstable-native-dependencies.development.js | -4.9% | -6.2% | 58.48 KB | 55.59 KB | 15.27 KB | 14.33 KB | NODE_DEV
**react-dom-unstable-native-dependencies.production.min.js** | **0.0%** | **-0.0%** | **10.86 KB** | **10.86 KB** | **3.73 KB** | **3.73 KB** | **NODE_PROD**
react-dom-server.browser.development.js | +0.8% | -3.1% | 102.25 KB | 103.07 KB | 27.24 KB | 26.39 KB | UMD_DEV
react-dom-server.browser.development.js | -4.2% | -4.5% | 98.38 KB | 94.22 KB | 26.3 KB | 25.12 KB | NODE_DEV
**react-dom-server.browser.production.min.js** | **0.0%** | **-0.0%** | **15.21 KB** | **15.21 KB** | **5.78 KB** | **5.78 KB** | **NODE_PROD**
react-dom-server.node.development.js | -4.1% | -4.4% | 100.3 KB | 96.14 KB | 26.83 KB | 25.65 KB | NODE_DEV
**react-dom-server.node.production.min.js** | **0.0%** | **-0.0%** | **16.02 KB** | **16.02 KB** | **6.08 KB** | **6.08 KB** | **NODE_PROD**
ReactDOM-dev.js | -2.4% | -2.3% | 646.35 KB | 630.51 KB | 148.13 KB | 144.75 KB | FB_WWW_DEV
**ReactDOM-prod.js** | **-0.6%** | **-0.5%** | **278.1 KB** | **276.44 KB** | **52.2 KB** | **51.94 KB** | **FB_WWW_PROD**
ReactTestUtils-dev.js | -2.1% | -3.2% | 40.66 KB | 39.8 KB | 10.92 KB | 10.57 KB | FB_WWW_DEV
ReactDOMUnstableNativeDependencies-dev.js | -5.2% | -6.7% | 56.24 KB | 53.31 KB | 14.23 KB | 13.28 KB | FB_WWW_DEV
**ReactDOMUnstableNativeDependencies-prod.js** | **-0.3%** | **-0.3%** | **26.16 KB** | **26.08 KB** | **5.28 KB** | **5.27 KB** | **FB_WWW_PROD**
ReactDOMServer-dev.js | -1.7% | -2.4% | 99.49 KB | 97.75 KB | 26 KB | 25.39 KB | FB_WWW_DEV
**ReactDOMServer-prod.js** | **-0.3%** | **-0.0%** | **33.08 KB** | **32.99 KB** | **7.98 KB** | **7.97 KB** | **FB_WWW_PROD**
react-dom.profiling.min.js | 0.0% | 0.0% | 97.39 KB | 97.41 KB | 31.14 KB | 31.15 KB | NODE_PROFILING
ReactDOM-profiling.js | -0.6% | -0.5% | 281.39 KB | 279.71 KB | 52.92 KB | 52.67 KB | FB_WWW_PROFILING

## react-art
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-art.development.js | -3.0% | -6.8% | 435.36 KB | 422.36 KB | 98.65 KB | 91.94 KB | UMD_DEV
**react-art.production.min.js** | **-0.0%** | **-0.1%** | **85.17 KB** | **85.16 KB** | **26.42 KB** | **26.41 KB** | **UMD_PROD**
react-art.development.js | -9.1% | -9.3% | 367.88 KB | 334.56 KB | 81.58 KB | 73.96 KB | NODE_DEV
**react-art.production.min.js** | **-0.0%** | **-0.1%** | **50.16 KB** | **50.15 KB** | **15.79 KB** | **15.79 KB** | **NODE_PROD**
ReactART-dev.js | -4.0% | -3.7% | 358.35 KB | 344.08 KB | 76.45 KB | 73.6 KB | FB_WWW_DEV
**ReactART-prod.js** | **-0.2%** | **-0.2%** | **152.95 KB** | **152.72 KB** | **26.36 KB** | **26.32 KB** | **FB_WWW_PROD**

## react-test-renderer
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-test-renderer.development.js | -8.2% | -12.0% | 363.77 KB | 333.8 KB | 79.99 KB | 70.42 KB | UMD_DEV
**react-test-renderer.production.min.js** | **-0.0%** | **0.0%** | **49.03 KB** | **49.02 KB** | **15.16 KB** | **15.17 KB** | **UMD_PROD**
react-test-renderer.development.js | -12.6% | -13.1% | 359.9 KB | 314.65 KB | 79.01 KB | 68.7 KB | NODE_DEV
**react-test-renderer.production.min.js** | **-0.0%** | **-0.1%** | **48.74 KB** | **48.73 KB** | **15.01 KB** | **14.99 KB** | **NODE_PROD**
react-test-renderer-shallow.development.js | +3.6% | +0.5% | 23.23 KB | 24.06 KB | 6.29 KB | 6.32 KB | UMD_DEV
react-test-renderer-shallow.development.js | -0.3% | -0.5% | 18.42 KB | 18.37 KB | 5.11 KB | 5.08 KB | NODE_DEV
ReactTestRenderer-dev.js | -8.2% | -8.1% | 365.01 KB | 335.06 KB | 77.94 KB | 71.62 KB | FB_WWW_DEV
ReactShallowRenderer-dev.js | -0.4% | -0.6% | 16.91 KB | 16.85 KB | 4.42 KB | 4.4 KB | FB_WWW_DEV

## react-reconciler
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-reconciler.development.js | -7.1% | -8.2% | 348.89 KB | 324.12 KB | 75.62 KB | 69.38 KB | NODE_DEV
**react-reconciler.production.min.js** | **-0.0%** | **-0.1%** | **47.71 KB** | **47.7 KB** | **14.47 KB** | **14.45 KB** | **NODE_PROD**
react-reconciler-persistent.development.js | -7.0% | -7.7% | 347.51 KB | 323.33 KB | 75.06 KB | 69.27 KB | NODE_DEV
**react-reconciler-persistent.production.min.js** | **-0.0%** | **-0.1%** | **47.72 KB** | **47.71 KB** | **14.47 KB** | **14.46 KB** | **NODE_PROD**
react-reconciler-reflection.development.js | -2.6% | -4.1% | 14.24 KB | 13.86 KB | 4.47 KB | 4.29 KB | NODE_DEV

## react-native-renderer
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
ReactNativeRenderer-dev.js | -3.2% | -3.0% | 483.18 KB | 467.58 KB | 106.8 KB | 103.61 KB | RN_FB_DEV
**ReactNativeRenderer-prod.js** | **-0.3%** | **-0.3%** | **214.2 KB** | **213.57 KB** | **37.54 KB** | **37.41 KB** | **RN_FB_PROD**
ReactNativeRenderer-dev.js | -6.9% | -6.9% | 482.92 KB | 449.58 KB | 106.74 KB | 99.38 KB | RN_OSS_DEV
**ReactNativeRenderer-prod.js** | **-0.3%** | **-0.3%** | **204.24 KB** | **203.63 KB** | **35.92 KB** | **35.81 KB** | **RN_OSS_PROD**
ReactFabric-dev.js | -6.8% | -6.8% | 473.39 KB | 441.18 KB | 104.36 KB | 97.24 KB | RN_FB_DEV
**ReactFabric-prod.js** | **-0.3%** | **-0.3%** | **195.36 KB** | **194.86 KB** | **34.36 KB** | **34.25 KB** | **RN_FB_PROD**
ReactFabric-dev.js | -6.8% | -6.8% | 473.43 KB | 441.15 KB | 104.38 KB | 97.24 KB | RN_OSS_DEV
**ReactFabric-prod.js** | **-0.3%** | **-0.3%** | **195.39 KB** | **194.9 KB** | **34.37 KB** | **34.26 KB** | **RN_OSS_PROD**
ReactNativeRenderer-profiling.js | -0.3% | -0.3% | 207.75 KB | 207.19 KB | 36.62 KB | 36.51 KB | RN_OSS_PROFILING
ReactFabric-profiling.js | -0.3% | -0.3% | 198.41 KB | 197.89 KB | 35 KB | 34.9 KB | RN_OSS_PROFILING
ReactNativeRenderer-profiling.js | -0.3% | -0.3% | 217.67 KB | 217.09 KB | 38.24 KB | 38.13 KB | RN_FB_PROFILING
ReactFabric-profiling.js | -0.3% | -0.3% | 198.37 KB | 197.85 KB | 34.98 KB | 34.88 KB | RN_FB_PROFILING

## react-scheduler
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-scheduler.development.js | -1.6% | -7.2% | 15.39 KB | 15.15 KB | 4.64 KB | 4.31 KB | UMD_DEV
react-scheduler.development.js | -6.0% | -7.8% | 15.2 KB | 14.29 KB | 4.6 KB | 4.24 KB | NODE_DEV
ReactScheduler-dev.js | -5.9% | -7.7% | 15.42 KB | 14.51 KB | 4.64 KB | 4.28 KB | FB_WWW_DEV
**ReactScheduler-prod.js** | **-0.2%** | **-0.2%** | **7.58 KB** | **7.56 KB** | **1.89 KB** | **1.89 KB** | **FB_WWW_PROD**

## react-is
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-is.development.js | +4.4% | +0.5% | 4.68 KB | 4.89 KB | 1.29 KB | 1.3 KB | UMD_DEV
react-is.development.mjs | n/a | n/a | 0 B | 3.94 KB | 0 B | 1.1 KB | ESM_DEV
**react-is.production.min.mjs** | **n/a** | **n/a** | **0 B** | **1.94 KB** | **0 B** | **735 B** | **ESM_PROD**

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by gaearon** [comment]
Does this `mjs` work on Node?

**Comment by TrySound** [comment]
Yes, I just tried

**Comment by gaearon** [comment]
Can we test it on CI somehow?

**Comment by TrySound** [comment]
I can try to setup [esm](https://github.com/standard-things/esm), but i'm not sure it works with jest already.

**Comment by gaearon** [comment]
Hmm, no I mean real Node (experimental flag). We don’t want to be in a situation where it works in esm but fails in real Node.

It doesn’t need to be in Jest. I was thinking a standalone script that acts as a smoke test.

**Comment by TrySound** [comment]
That's easier. Can we change node version in nvm to 10?

**Comment by gaearon** [comment]
Sure.

**Comment by TrySound** [comment]
Do you want me to add treeshakability stat?

**Comment by TrySound** [comment]
image

**Comment by gaearon** [comment]
Fix lint please?

**Comment by TrySound** [comment]
Done

**Comment by TrySound** [comment]
Rebased

**Comment by gaearon** [comment]
Do you mind rebasing again? Sorry.

This is a significant change and I'll need to look at it in more detail.

**Comment by TrySound** [comment]
I thought more about treeshakability measurement. The idea of distributing esm here is reexporting both production and development bundles. Our goal is to keep user production bundles as small as possible. Development bundles are usually doesn't matter a lot. Currently info about treeshakability doesn't provide useful enough information. Ideally if the size is less than production then development was fully treeshaked. But production version could be also partially treeshaked and we won't notice if something if left from development bundle.

So my solution is keeping track treeshakability of each esm bundles separately. `index.mjs` with reexports should just work if its dependencies are treeshakable.

**Comment by Andarist** [comment]
@TrySound If I've checked this correctly the production ESM bundle has quite some bloat - looks like some closure compiler stuff or similar.

**Comment by TrySound** [comment]
@Andarist Yes, that's why I changed treeshakability detection to only development bundle. This will be a bloat only for dev environment. Production will use only what is expected.

**Comment by TrySound** [comment]
@Andarist Dev bundle will be treeshaked out in production builds
https://github.com/facebook/react/pull/13321/files#diff-7a4b1c45d0fef2bb9fa773a2942c4080R788

This pattern is treeshakable too. And since it's generated it will always work. The only requirement is treeshakability of its dependencies. In this case at least dev should be treeshakable to prevent production builds bloat.

```js
import * as prod from './prod.js';
import * as dev from './dev.js';
export const A = process.env.NODE_ENV !== 'production' ? dev.A : prod.A;
```

**Comment by Andarist** [comment]
I understand how dev bundle can be tree-shaken, I'm talking specifically about prod bundle itself. It has been bloated and thus this might prevent tree-shaking of those bloated parts of the **production bundle**

**Comment by TrySound** [comment]
I don't think anybody is going to achieve treeshakability in react packages. They are quite atomic.

**Comment by Andarist** [comment]
> I don't think anybody is going to achieve treeshakability in react packages. They are quite atomic.

That's generally true, but I think it's also less true for `react-is`. Either way I'm not even talking about general tree-shakeability here, but rather that there is a **bloat** in the esm production build of `react-is`, this code is not react-is', but rather something added by closure-compiler or similar. Just look at the beginning of this:
<details>
<summary>react-is.production.min.mjs</summary>
var b=b||{};b.scope={};b.ASSUME_ES5=!1;b.ASSUME_NO_NATIVE_MAP=!1;b.ASSUME_NO_NATIVE_SET=!1;b.defineProperty=b.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,r){a!=Array.prototype&&a!=Object.prototype&&(a[c]=r.value)};b.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};b.global=b.getGlobal(this);b.SYMBOL_PREFIX="jscomp_symbol_";
b.initSymbol=function(){b.initSymbol=function(){};b.global.Symbol||(b.global.Symbol=b.Symbol)};b.Symbol=function(){var a=0;return function(c){return b.SYMBOL_PREFIX+(c||"")+a++}}();b.initSymbolIterator=function(){b.initSymbol();var a=b.global.Symbol.iterator;a||(a=b.global.Symbol.iterator=b.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&b.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return b.arrayIterator(this)}});b.initSymbolIterator=function(){}};
b.arrayIterator=function(a){var c=0;return b.iteratorPrototype(function(){return c< a.length?{done:!1,value:a[c++]}:{done:!0}})};b.iteratorPrototype=function(a){b.initSymbolIterator();a={next:a};a[b.global.Symbol.iterator]=function(){return this};return a};b.initSymbol();b.initSymbol();var d="function"===typeof Symbol&&Symbol.for;b.initSymbol();var e=d?Symbol.for("react.element"):60103;b.initSymbol();var f=d?Symbol.for("react.portal"):60106;b.initSymbol();var g=d?Symbol.for("react.fragment"):60107;
b.initSymbol();var h=d?Symbol.for("react.strict_mode"):60108;b.initSymbol();var k=d?Symbol.for("react.profiler"):60114;b.initSymbol();var l=d?Symbol.for("react.provider"):60109;b.initSymbol();var m=d?Symbol.for("react.context"):60110;b.initSymbol();var n=d?Symbol.for("react.async_mode"):60111;b.initSymbol();var p=d?Symbol.for("react.forward_ref"):60112;b.initSymbol();var q=d?Symbol.for("react.placeholder"):60113;
function t(a){if("object"===typeof a&&null!==a){var c=a.$$typeof;switch(c){case e:switch(a=a.type,a){case n:case g:case k:case h:return a;default:switch(a=a&&a.$$typeof,a){case m:case p:case l:return a;default:return c}}case f:return c}}}var typeOf=t;var AsyncMode=n;var ContextConsumer=m;var ContextProvider=l;var Element=e;var ForwardRef=p;var Fragment=g;var Profiler=k;var Portal=f;var StrictMode=h;
var isValidElementType=function(a){return"string"===typeof a||"function"===typeof a||a===g||a===n||a===k||a===h||a===q||"object"===typeof a&&null!==a&&("function"===typeof a.then||a.$$typeof===l||a.$$typeof===m||a.$$typeof===p)};var isAsyncMode=function(a){return t(a)===n};var isContextConsumer=function(a){return t(a)===m};var isContextProvider=function(a){return t(a)===l};var isElement=function(a){return"object"===typeof a&&null!==a&&a.$$typeof===e};
var isForwardRef=function(a){return t(a)===p};var isFragment=function(a){return t(a)===g};var isProfiler=function(a){return t(a)===k};var isPortal=function(a){return t(a)===f};var isStrictMode=function(a){return t(a)===h};export{typeOf,AsyncMode,ContextConsumer,ContextProvider,Element,ForwardRef,Fragment,Profiler,Portal,StrictMode,isValidElementType,isAsyncMode,isContextConsumer,isContextProvider,isElement,isForwardRef,isFragment,isProfiler,isPortal,isStrictMode};
</details>

**Comment by TrySound** [comment]
Well, esm doesn't solve this like it wasn't solved before with cjs. I think this is the question for another thread.

**Comment by Andarist** [comment]
Equivalent cjs production build has no such bloat, it seems to me this is issue with current setup - not sure if we are on the same page here, maybe we both have some information in our heads that make it harder to come to a common ground for both of us. I'll ping u on twitter, we'll be able to discuss it much quicker than in here. 

Side note - cjs production build weighs 677 bytes (gzipped), so it's much more near to my estimate of what esm production build should weight too.

**Comment by Andarist** [comment]
@TrySound @gaearon could we move this along? is there any blocker for this one? Is there any interest in this from the React team?

I can help to rebase this and in general finish it if @TrySound doesn't have time right now.

**Comment by TrySound** [comment]
@Andarist This is the blocker.
https://github.com/facebook/react/pull/15037

**Comment by frehner** [comment]
The blocker was just merged! :)

**Comment by Andarist** [comment]
Im super glad to hear that! @TrySound will you want to continue work on this one?

**Pull request closed without merging**
