### PR TITLE
Remove extra brace

### PR DESCRIPTION
**Pull request by mariosouto**

### CODE REVIEW

**Comment by mariosouto** [comment]
Done!

**Comment by bvaughn** [comment]
Cheers~

**Comment by mariosouto** [comment]
Thanks! 💯

**Comment by gaearon** [comment]
FWIW I don’t think we need the CLA for docs.

**Comment by zpao** [comment]
> FWIW I don’t think we need the CLA for docs.

True for super trivial things (like this) but I would still collect CLAs for docs in general.

**Pull request merged**
