### PR TITLE
modify Chinese docs , update to 0.14 from English version

### PR DESCRIPTION
**Pull request by WanderWang**
modify Chinese docs , update to 0.14 from English version .

Major changes : 

1. synchronous example code from english version ( especially ReactDOM in v0.14 )
2. replace ```react-tools``` and ``` JSXTransformer ``` to ``` Babel ```
3. some stiff Chinese grammar

### CODE REVIEW

**Comment by jimfb** [comment]
Looks good, can you squash the multiple commits into a single commit?

**Comment by WanderWang** [comment]
ok , should I close this PR and create a new PR with single commit again ？

**Comment by zpao** [comment]
No, you can use `git rebase` to combine commits (known as "squashing"). https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit gives a pretty succinct explanation in the context of pull requests. http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit also explains well.

**Comment by WanderWang** [comment]
High guys ,  I have some problem in squash the multi commits . For safety , I reset my code and create a new PR in https://github.com/facebook/react/pull/5203 , Sorry !

**Pull request closed without merging**
