### PR TITLE
First-Class Custom PropType Checker

### PR DESCRIPTION
**Pull request by ajgreenb**
I'm not sure if this is a desired feature, but I thought it would be nice to have an easy way to make custom `propType` validators required or optional. This patch essentially adds a new property to `ReactPropTypes` called `custom`. You pass it a custom validator function, and it just wraps that validator in `createChainableTypeChecker`.

```javascript
propTypes: {
  warning: React.PropTypes.custom(
    function (props, propName) {
      if (!props[propName].startsWith('WARNING: ')) {
        return new Error('`warning` prop must start with \'WARNING: \'');
      }
    }
  ).isRequired,
},
```

On the one hand, it requires you to add a little more code since you're no longer just passing a raw function, but I think it adds the nice benefit of making it simple to enforce required custom-validated `props`. Should passing an unwrapped function still be supported?

As I write this, it occurs to me (after writing the implementation and tests, sigh) that if you want to make a required custom validator, you can add an `if (!props[propName])` conditional to the body, heh. But this solution makes it a little more idiomatic...?

What do you all think?

### CODE REVIEW

**Comment by satya164** [comment]
How is it different than just checking if the value is `undefined`?

**Comment by ajgreenb** [comment]
@satya164 it's equivalent, but this solution is slightly more idiomatic. Plus, it assigns that responsibility to the React library, rather than the developer using it.

**Comment by jimfb** [comment]
Proptypes are mostly legacy and in maintenance mode, having been replaced by tools like Flow, so we've generally shied away from adding new features/functions/api.  There is no reason that this functionality needs to be tied into React, so my intuition is that the best strategy here is to just create a third-party library that helps users build custom proptypes, and post that on github.

**Comment by ajgreenb** [comment]
Oh, interesting. Okay then, closing this pull request. I'll look into using one of the more advanced tools. Thanks!

**Pull request closed without merging**
