### PR TITLE
Move ShallowRenderer tests

### PR DESCRIPTION
**Pull request by koba04**
ShallowRenderer is an independent renderer for testing, so this PR is to move tests for ShallowRenderer into a directory same as TestRenderer.

### CODE REVIEW

**Comment by gaearon** [comment]
Do you mind bringing this up to date please? Looks reasonable to me.

**Comment by koba04** [comment]
@gaearon rebased!

**Comment by gaearon** [comment]
Thanks!

**Comment by koba04** [comment]
Thanks!

**Pull request merged**
