### PR TITLE
Rename internal methods

### PR DESCRIPTION
**Pull request by behnammodi**
- Shipped `Children` object to ReactChildren
 - Replaced multiple exports to default export
 - Changed methods name to exported name

### CODE REVIEW

**Comment by rickhanlonii** [comment]
Hey @behnammodi, thanks for the PR!

We don't normally take stylistic PRs, style and readability are extremely subjective and these changes often introduce subtle mistakes. Going to close this but thanks again for your work!

**Comment by behnammodi** [comment]
Hey @rickhanlonii, you're welcome.
How to find a document about inside react, about how to work. I very interested to learn it

**Comment by rickhanlonii** [comment]
@behnammodi not sure we have anything more that the docs https://reactjs.org.

**Comment by behnammodi** [comment]
@rickhanlonii Thanks man, you're right. how do I internship for react core team? :)

**Pull request closed without merging**
