### PR TITLE
Improve error message thrown in Fiber with multiple copies of React

### LINKED ISSUE #9962: String Refs Without An Owner Should Fail Gracefully
Occurs in Fiber with multiple instances of the React package (which can't share current owner).

### PR DESCRIPTION
**Pull request by flarnie**
**what is the change?:**
 - Added warning in the place where this error is thrown in Fiber, to
   get parity with older versions of React.
 - Updated docs to mention new error message as well as old one.

I started to write a new docs page for the new error, and realized the
content was the same as the old one. So then I just updated the existing
error page.

**why make this change?:**
We want to avoid confusion when this error is thrown from React v16.

**test plan:**
- `yarn test src/renderers/__tests__/multiple-copies-of-react-test.js`
- `REACT_JEST_USE_FIBER=1 yarn run test src/renderers/__tests__/multiple-copies-of-react-test.js`
- manually inspected docs page
- manually tested in a CRA to trigger the error message

screen shot 2017-07-12 at 12 15 22 pm

screen shot 2017-07-12 at 11 52 07 am

**issue:**
Fixes #9962
Related to #8854

### CODE REVIEW

**Comment by spicyj** [comment]
Would this invariant make more sense as an `else` to this `if`?

https://github.com/facebook/react/blob/2e2f503cb84842d588295d8283366793bff1c8eb/src/renderers/shared/fiber/ReactChildFiber.js#L124

That way only that one piece of code needs to care about string refs.

**Comment by flarnie** [comment]
I think that makes sense @spicyj - if we put the 'invariant' there then we could even use basically the same error message and doc page, right?

**Comment by spicyj** [comment]
Yeah.

I would tweak it a bit: "Expected ref to be a function" is a little confusing if you pass a string ref because it requires the reader to understand that React converts the string to a function behind the scenes, which is an implementation detail. Something like "Element ref was specified as a string (myRef) but no owner was set." could be better. In the case that it's neither string nor function, you could say "Expected ref to be a function or a string".

**Comment by gaearon** [comment]
Maybe also let's not include `commitAttachRef(...)` there? It's not very useful to us since there's only one such invariant, and it's confusing to the user since it shows an internal method name as if they were expected to know what it means,

**Comment by flarnie** [comment]
Ah - I meant we could reuse the warning wording and docs from the old warning that gets thrown in 15.* - https://facebook.github.io/react/warnings/refs-must-have-owner.html

But I think you are right, we should give a specific error for this case, and probably a new docs page similar to https://facebook.github.io/react/warnings/refs-must-have-owner.html

I spent a while trying to write a test for this, and wasn't able to reproduce the error in the test environment. I was trying to use '[jestResetModules](https://facebook.github.io/jest/docs/jest-object.html#jestresetmodules)' to load and use a second copy of React, and it seemed to work, but the error wasn't triggered.

This is what I tried: https://gist.github.com/flarnie/46f744f6981f1f35861ef4cdeba67af1

Since we didn't have a test for the old warning (Refs must have owner) we could merge this without a test.

Writing a fixture that reproduces the error seems easier, but I don't want to commit to the overhead of checking it manually.

**Comment by flarnie** [comment]
I can't find any way to trigger the case where 'In the case that it's neither string nor function, you could say "Expected ref to be a function or a string".' so I'm not putting too much thought into that message, but I guess it makes sense to add that invariant since we *do* expect it to be a string or a function.

**Comment by spicyj** [comment]
What happens if you do ref={17} or ref={{abc: true}}?

**Comment by flarnie** [comment]
It doesn't complain for `ref={17}`, `ref={{abc: true}}`. The only thing I found to pass to `ref` that throws is `ref={Function}` and I think that is bad syntax, not really worried about someone doing that.

**Comment by flarnie** [comment]
And now it has a test! Thank youuuuuu @gaearon 🏎️

**Comment by flarnie** [comment]
I thought it would be more clear that way - looking now for patterns that are used currently.

**Comment by flarnie** [comment]
I'll update it to all be in one `it(...` assertion.

**Comment by spicyj** [comment]
I guess I am confused why there needs to be a branch at all. Is the behavior not the same?

**Comment by flarnie** [comment]
For the record, we talked more about why there needs to be a different branch for 'fiber' and 'stack' versions of this behavior; the new warning is in fiber only, and the old warning shows up if you are using stack.

The old warning will go away when we delete stack, but for now the test is covering both cases.

**Pull request merged**
