### PR TITLE
fix: use define property to overwrite console, close #19099

### LINKED ISSUE #19099: Bug: TypeError: "log" is read-only.
React version: 0.0.0-experimental-33c3af284

image

https://github.com/facebook/react/blob/master/packages/shared/ConsolePatchingDev.js#L45

>       // $FlowFixMe Flow thinks console is immutable.

Yes it _is_ immutable in some enviroment. Please add a try catch on it.

### PR DESCRIPTION
**Pull request by Jack-Works**
## Summary

This PR fixes #19099. React crashes in the content script (Web extension) in Firefox.

## Test Plan

- [x] validate if React no longer crashes in content script in Firefox.

### CODE REVIEW

**Comment by threepointone** [comment]
@Jack-Works could you please add a description and explain how you tested this?

cc @bvaughn, this seems reasonable

**Comment by Jack-Works** [comment]
I run React in the content script (Web Extension) in the Firefox

**Comment by threepointone** [comment]
Sorry if I wasn't clear, please add a summary of what this PR does and what it fixes, and how you tested it, in the first post of this this PR (up there, where it says "Summary" and "Test Plan"). Thanks!

**Comment by Jack-Works** [comment]
Ok, I'll do it later!

**Pull request merged**
