### PR TITLE
Revert "Don't wrap drag events in IE/Edge in dev builds"

### PR DESCRIPTION
**Pull request by spicyj**

### CODE REVIEW

**Comment by gaearon** [comment]
If we used CommonJS, we could write a lint rule that prevents imports of renderer-specific parts in shared folders.

**Comment by zpao** [comment]
We could still write the rule but it would be gnarly. We could also actually get to the point where we ship distinct packages so then this wouldn't have worked at all…

**Comment by jimfb** [comment]
This revert is effectively a breaking change, right?  Or did the fix never ship to npm and so this would be a semver-minor also?

On a meta note, I feel like we should have fixed forward (refactored/moved code) rather than just immediately reverting without review.

**Comment by spicyj** [comment]
It is not obvious to me how to fix forward; if you know how to do so cleanly I would appreciate a pull request. No, it only shipped in an alpha to npm.

**Comment by jimfb** [comment]
Ok, so presumably that makes it semver-minor also?

**Comment by spicyj** [comment]
It should go in the 15.1.0 release.

**Pull request merged**
