### PR TITLE
style(docsearch): add cursor + logo

### LINKED ISSUE #10965: [website] docsearch improvements
**What is the current behavior?**

the docsearch on the new page changed its design, but two features are different than in the previous version: 

- the "cursor" no longer has a separate colour (visible when you use the arrow keys to select a result)
- there no longer is an Algolia logo / mention

**What is the expected behavior?**

- A slightly different background colour for the cursor
- A mention of "search by Algolia" or our logo, as which is required because it's a free plan. 

Happy to open a PR for both of those issues, with whatever colour / solution we choose

cc @bvaughn and @gaearon

### PR DESCRIPTION
**Pull request by Haroenv**
fixes #10965

Not completely convinced about the cursor colour, but I couldn't really find a better one, cc @joecritch

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run prettier`).
6. Make sure your code lints (`npm run lint`).
7. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
8. If you haven't already, complete the CLA.

### CODE REVIEW

**Comment by joecritch** [comment]
Colour lgtm  🙌

**Comment by Haroenv** [comment]
I just tweaked the colour a little, made it slightly lighter so that it doesn't clash with the title on the left, and added an indicator to the right in the accent colour

screen shot 2017-10-02 at 18 16 59

**Comment by bvaughn** [comment]
PS If you rebase, the CI error is fixed now in master

**Comment by Haroenv** [comment]
Perfect, didn’t think of the no results view, will fix it tomorrow

**Comment by Haroenv** [comment]
screen shot 2017-10-03 at 19 03 56
screen shot 2017-10-03 at 19 03 40

Looks like this now @bvaughn

**Comment by bvaughn** [comment]
Screenshot looks good. Netlify preview failed to build though so I restarted it. Want to verify visually before merging. 😄

**Comment by Haroenv** [comment]
Perfect, thanks for merging

**Pull request merged**
