### PR TITLE
Export unstable_useMemoCache in experimental server runtime

### PR DESCRIPTION
**Pull request by gsathya**
Flight already has an implementation of useMemoCache:
https://github.com/facebook/react/blob/main/packages/react-server/src/ReactFlightHooks.js#L73-L79

This PR exports the existing hook.

### CODE REVIEW

**Review by poteto — APPROVED** [review]

**Comment by sebmarkbage** [comment]
It doesn't actually do anything so compiling a server layer would actually be a regression and arguably a bug. It should ideally error early if you do that.

**Review by sebmarkbage — CHANGES_REQUESTED** [review]
Seems like this should be an early error so it's good that it's not exported.

**Comment by sebmarkbage** [comment]
The same thing applies to Fizz in a way too btw since we're trying to replace the multi-pass renders there.

**Comment by sebmarkbage** [comment]
Previous discussion in https://github.com/facebook/react/pull/27829

**Comment by poteto** [comment]
> It doesn't actually do anything so compiling a server layer with Forget would actually be a regression and arguably a bug. It should ideally error early if you do that.

@sebmarkbage is there a reliable way to know if the compiler is trying to compile a server component (and therefore bail out of it?)

**Comment by sebmarkbage** [comment]
It varies by environment but since Server Components needs to compile in a separate layer of the bundler with a different set of compilers/plugins, you would typically simply exclude it from the compilation there.

**Comment by gsathya** [comment]
> It doesn't actually do anything so compiling a server layer with Forget would actually be a regression and arguably a bug. It should ideally error early if you do that.

That makes sense but we've got potentially optimisations planned that could help server components. I guess we could turn it on then, but maybe the safe default now is to run the compiler always but not do any memoization for server components?

**Pull request closed without merging**
