### PR TITLE
Fix SSR missing data-reactroot attribute inside invisible React elements

### PR DESCRIPTION
**Pull request by overlookmotel**
PR for #15012.

```js
const React = require('react'),
  {renderToString} = require('react-dom/server');

const Context = React.createContext();

const html = renderToString(
  <Context.Provider>
    <div>Hello!</div>
  </Context.Provider>
);
```

Before this PR, outputs:

```
'<div>Hello!</div>'
```

with this PR:

```
'<div data-reactroot="">Hello!</div>'
```

Implementation is through addition of a `.domRootFrame` property on `ReactDOMServerRenderer` instance.

* `domRootFrame` is `null` if no DOM element in stack above currently rendering element.
* When a entering a root DOM element, `domRootFrame` is set to the stack frame for that DOM element.
* When exiting root DOM element, `domRootFrame` is set back to `null` (the root element is identified by checking if the frame being popped from the stack is equal to `domRootFrame`)

I am not clear what desired behavior is when there are multiple DOM roots e.g.:

```
<React.Fragment>
  <div>One</div>
  <div>Two</div>
</React.Fragment>
```

I guess both `<div>`s should get `data-reactroot=""` markup, but not sure what the result on client side would be!

Any changes you want made, please shout.

### CODE REVIEW

**Comment by overlookmotel** [comment]
I altered the implementation to use an integer property `.domRootIndex` on `ReactDOMServerRenderer` instance.

Behavior remains the same.

If `domRootIndex === 0`, no DOM nodes exist above in the stack, so next DOM element encountered is the root and should have `data-reactroot` attribute. If `domRootIndex !== 0`, we are already inside a DOM node, so any other DOM elements are not the root.

* `domRootIndex` is `0` initially.
* When entering first DOM element, `domRootIndex` is set to length of stack after DOM element's frame is pushed onto stack.
* When exiting DOM root element, `domRootIndex` is set back to `0` (it's determined whether the frame being popped represents the DOM root element by testing if length of stack is equal to `domRootIndex`).

**Comment by ianks** [comment]
I'm not familiar with the React codebase so I can't comment on implementation, but overall the specs cover the cases where we are experiencing problems. I would also say that solving this issue is hugely important because in many cases, a visible react root will not exist since HOC will open need to have hydration code before rendering a component. Would love to see this get merged :smile:

**Comment by ianks** [comment]
Any progress on this?

**Comment by overlookmotel** [comment]
Anyone got a moment to look at this? @gaearon confirmed this was a bug, and this PR fixes it, so would be great if it'd be possible to look at merging it.

Happy to make any changes you need made to get it fit for merging.

**Comment by kiddkai** [comment]
Adding this attribute will make `render` function work exactly the same as `hydrate` function. 

By the implementation in the client side:

https://github.com/facebook/react/blob/1d48b4a68485ce870711e6baa98e5c9f5f213fdf/packages/react-dom/src/fire/ReactFire.js#L505

Even though `render` is currently not recommended, it removes everything from the container and render everything again on the client-side, which make sense for some use cases that SSR has some mismatch content with client render.

**Comment by kiddkai** [comment]
Adding this attribute will make `render` function work exactly the same as `hydrate` function. 

By the implementation in the client side:

https://github.com/facebook/react/blob/1d48b4a68485ce870711e6baa98e5c9f5f213fdf/packages/react-dom/src/fire/ReactFire.js#L505

Even though `render` is currently not recommended, it removes everything from the container and render everything again on the client-side, which make sense for some use cases that SSR has some mismatch content with client render.

**Comment by overlookmotel** [comment]
Hi @kiddkai. Just to clarify: are you saying this would be a bad thing?

**Comment by kiddkai** [comment]
Hi @overlookmotel, IMO it is a bad thing.

For some huge applications that haven't migrate to hydrate compatible code, it could be devastating. For some framework like `next.js`, they manually put `data-reactroot` into the top level element. Which will force `render` turn into `hydrate` mode. If you want the hydrate behaviour. It's better either use `render` with manual `data-reactroot` or just `hydrate`.

**Comment by overlookmotel** [comment]
@kiddkai If you don't want `data-reactroot` in your server-rendered HTML, can't you just use `.renderToStaticMarkup()` rather than `.renderToString()`?

My point with #15012 is that the current behavior is inconsistent.

The following produce `<div data-reactroot="">Hello!</div>`:

* `renderToString(<div>Hello!</div>)`
* `renderToString(<React.Fragment><div>Hello!</div></React.Fragment>)`

and the following produce just `<div>Hello!</div>`:

* `renderToString(<React.Fragment><React.Fragment><div>Hello!</div></React.Fragment></React.Fragment>)`
* `renderToString(<Context.Provider><div>Hello!</div></Context.Provider>)`

This does not look like an intentional decision to me, but a bug.

Actually, we should probably discuss this on #15012 rather than here, as that issue describes the bug (or what I say is a bug). This PR is just a fix for the issue.

**Comment by overlookmotel** [comment]
Please don't close this, Mr Robot.

@gaearon did confirm this as a bug in #15012, so I'm hoping it may be merged at some point.

**Comment by gaearon** [comment]
Thanks for PR.

>I am not clear what desired behavior is when there are multiple DOM roots 

I think that's the crux of this issue. Emitting two nodes tagged as roots isn't what we want, I think.

The reason this whole attribute even matters is for compatibility with hydrating via `ReactDOM.render` call. However we've already deprecated that behavior in favor of `ReactDOM.hydrate`. So I'm not sure this is worth fixing. What do you think?

**Comment by overlookmotel** [comment]
Please keep this fresh, Mr Bot.

**Comment by ianks** [comment]
whats the hold up on merging this?

**Comment by overlookmotel** [comment]
Closing as @gaearon has indicated on #15012 that they do not want to fix.

**Comment by gaearon** [comment]
Sorry for the churn. I appreciate you doing the work. We’ve gotten swamped with other stuff and now that I revisit it’s clear we want to go a different way anyway.

**Pull request closed without merging**
