### PR TITLE
Jasmine spies call args property consistency

### PR DESCRIPTION
**Pull request by matiassingers**
### stats:
- `mostRecentCall.args[0]`: 4 matches across 3 files
- `calls[0].args[0]`: 45 matches across 14 files
- `argsForCall[0][0]`: 75 matches across 25 files

~~Converted all to `calls[n].args[n]` for consistency with `calls.length`.~~

---
Related to #5129 and #3105

### CODE REVIEW

**Comment by spicyj** [comment]
I'd rather go with argsForCall which was already the predominant style. It's easiest to type.

**Comment by spicyj** [comment]
We can do argsForCall.length too if you like.

**Comment by matiassingers** [comment]
@spicyj good call, updated the commit with the changes.

**Comment by matiassingers** [comment]
@spicyj good call, updated the commit with the changes.

**Comment by spicyj** [comment]
@matiassingers Thank you! Would you be interested in adding a lint rule for this? We have a couple custom rules already.

**Pull request merged**
