### PR TITLE
Lock babel @ 5.6.x.

### PR DESCRIPTION
**Pull request by zpao**
5.7 and 5.8 are having issues with linting and I don't want to deal with that.

### CODE REVIEW

**Comment by bgw** [comment]
[Supposedly the infix operator issue is fixed in >5.8.0](https://github.com/babel/babel-eslint/issues/149).

**Comment by troutowicz** [comment]
I was experiencing issues with disabling linting for blocks of code using `/*eslint-disable */`, ended up being babel-core that needed locking @ 5.6.x, the latest version of the other babel packages worked fine.

**Comment by zpao** [comment]
A bunch of other things are broken though (looks like a lot of comment-related issues, but haven't looked into it). 
screen shot 2015-07-21 at 1 21 48 pm

**Comment by bgw** [comment]
Okay, I guess we can merge this then.

**Comment by spicyj** [comment]
(cc @sebmck)

**Comment by sebmck** [comment]
Looking into it.

**Comment by sebmck** [comment]
Found it. Comment attachment was recently integrated into Babel's parser for performance, Babel uses the comment node type  `CommentBlock`, while ESLint uses `Block` which causes it to ignore the comments due to the type difference. I've added a fix to `babel-eslint` and released it as v3.1.24.

**Comment by bgw** [comment]
Wow. That was fast. Thanks @sebmck.

**Comment by zpao** [comment]
Since others are referring here, there's still a problem with comments so we'll stay at 5.6 for a bit longer. https://github.com/babel/babel-eslint/issues/153

**Comment by sebmck** [comment]
Fixed the remaining comment issues and added regression tests to ensure it wont happen again in the future.

**Pull request merged**
