### PR TITLE
ReactTransitionGroup: Refactor Code

### PR DESCRIPTION
**Pull request by mertkahyaoglu**

### CODE REVIEW

**Comment by maxdeviant** [comment]
I think you could take the refactor a step further and reduce the conditional nesting, like so:

```js
function getEnvironmentChildMapping(instance, props) {
  if (__DEV__) {
    return ReactTransitionChildMapping.getChildMapping(
      props.children,
      ReactInstanceMap.get(instance)._debugID
    );
  }
  
  return ReactTransitionChildMapping.getChildMapping(
    props.children
  );
}
```

**Comment by mertkahyaoglu** [comment]
@maxdeviant Done 👍

**Comment by mertkahyaoglu** [comment]
Actually, do we need to check for `dev` here ? I think we already check for it [here](https://github.com/facebook/react/blob/master/src/addons/transitions/ReactTransitionChildMapping.js#L30).

Therefore, can we reduce the code even more like this?

``` javascript 
function getEnvironmentChildMapping(instance, props) {
  return ReactTransitionChildMapping.getChildMapping(
    props.children,
    ReactInstanceMap.get(instance)._debugID
  );
}
```

Or we might not even need a function.

**Comment by gaearon** [comment]
Thanks for the PR?

Is there any particular purpose for this refactoring? Generally we try to minimize style tweaks that don’t also fix bugs. It’s easy to accidentally introduce an issue while tweaking style, and then everybody is going to lose time fixing it, testing and shipping the fix.

I’m not saying we won’t take this, but it looks like very low priority to me so I wanted to set the expectations. We are not actively working on `ReactTransitionGroup` and plan to hand it over to the community, so changes to it are even more expensive because we don’t want to spend time maintaining it.

**Comment by mertkahyaoglu** [comment]
@gaearon Not really. It just reduces LOC. Repeating some code just didn't look good to me. Other than that very low priority as you said 👍

**Comment by maxdeviant** [comment]
@mertkahyaoglu I think it is safer to keep the `__DEV__` check, just in case the function is ever called elsewhere that doesn't have the check before it. I don't think it hurts much, since it gets stripped out in production build anyways.

@gaearon I can see it going either way. On the one hand, "if it ain't broke, don't fix it". But on the other, moving duplicate code into a single function could prevent having to fix a future issue in multiple places, should this code ever change. Not sure there is a good answer to which one is preferable, but you probably know better than me in this context :smile:

**Pull request closed without merging**
