### PR TITLE
[#9627] Fix componentWillUnmount test case in isMounted tests

### PR DESCRIPTION
**Pull request by mridgway**
This fixes the test case mentioned in #9627 and adds checks for a component's mixins to ensure that they are also getting the correct values.

### CODE REVIEW

**Comment by acdlite** [comment]
Thanks for the PR! The package lives in the 15-stable branch for now: https://github.com/facebook/react/tree/15-stable/addons/create-react-class. We might split into its own repo at some point (but maybe not because we don't want to support it indefinitely).

Do you mind opening the PR against that branch?

**Comment by gaearon** [comment]
Going to revisit this after 15.6 is out—until then we can't really merge because test will fail CI.

**Comment by mridgway** [comment]
Updated create-react-class devDependency so that they could be merged in tandem without build failure.

**Comment by gaearon** [comment]
Thanks!

**Pull request merged**
