### PR TITLE
Reword invariant message about empty tags (fixes #7065)

### LINKED ISSUE #7065: Invariant violation error message improvement
**Do you want to request a *feature* or report a *bug*?**
Error message bug.

**What is the current behavior?**
Uncaught Invariant Violation: img is a void element tag and must not have `children` or use `props.dangerouslySetInnerHTML`. Check the render method of <Component Name>

provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**
   ```
    render: function () {
        return ( 
            <div  >
                <img src={ this.props.track_artwork } >   </img>
            </div>
         );
       }
  ```
**What is the expected behavior?**
```
Uncaught Invariant Violation: img is a void element tag and must not have `children` nor use `dangerouslySetInnerHTML`. Check the render method of <Component Name>
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
```
"version": "16.0.0-alpha"
```
found in Chrome, but should be universal.

### PR DESCRIPTION
**Pull request by starkch**
*Before* submitting a pull request, please make sure the following is done...

1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`grunt test`).
5. Make sure your code lints (`grunt lint`) - we've done our best to make sure these rules match our internal linting guidelines.
6. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by starkch** [comment]
Hi, I updated the tests so they all pass with the message change that was made.
Thanks.

**Comment by gaearon** [comment]
Let’s change to `must neither ... nor ...` for clarity.

**Pull request merged**
