### PR TITLE
make dev and production environment consistent

### PR DESCRIPTION
**Pull request by chicoxyzzy**
see #2864

### CODE REVIEW

**Comment by sebmarkbage** [comment]
This probably needs another pass since it is somewhat stale, but it should be using the warning module instead of calling console.error directly.

**Comment by chicoxyzzy** [comment]
updated

**Comment by chicoxyzzy** [comment]
@sebmarkbage

**Comment by sebmarkbage** [comment]
lgtm. We'll pull in after we switch branches. It is too late for 0.13 so we'll pull it into the 0.14 branch.

**Pull request merged**
