### PR TITLE
Enable yarn offline mirror

### PR DESCRIPTION
**Pull request by kassens**
Not sure if this has been discussed before or if the increase repo size is worth it, but wanted to put this up for discussion.

This configures yarn offline mirror to include the dependencies in the `.yarn-offline-mirror` directory which should make CI more resilient to network availability errors like [this failed run](https://app.circleci.com/pipelines/github/facebook/react/31586/workflows/fe11aa7d-4030-4f95-a885-c24d4fe23396/jobs/532587).

This means the files have to be downloaded on clone, but on the plus side yarn install should work even when offline.

### CODE REVIEW

**Comment by kachkaev** [comment]
Have you thought of switching to Yarn 3 folks? It stores `tgz`s in `.yarn/cache`, which can be added to git for [zero-install](https://yarnpkg.com/features/zero-installs) mode.

**Comment by eps1lon** [comment]
>  this would make it easier to sneak unknown code in that gets executed by maintainers before it's caught.

I don't know about Yarn v1 but in v3 you have an option to verify the cache in CI which would catch people sneaking in code that doesn't also exist on the registry. V1 might have something similar. So it may be possible to verify the cache, if changed, and otherwise you always use the offline cache and skip network.

**Comment by kassens** [comment]
@eps1lon: Flow needs the `node_modules` directory anyway, so even switching to yarn v3, we'd still need to manifest the node_modules directory. I'll leave that switch to a different PR/discussion.

**Comment by acdlite** [comment]
Personally I've fine with the increased repo size but I don't feel as confident weighing the other implications so I'll leave this to others to decide. If you want to merge that's fine with me.

**Comment by acdlite** [comment]
My guess is that switching to Yarn 3 would break a bunch of stuff though so I would hold off on that for now

**Comment by rickhanlonii** [comment]
@kassens looking at the failed run - it looks like a DOM fixtures test. I don't think that fixture dependencies are cached, so an alternative fix here is to ensure that we're caching all the dependencies we use (like in the fixtures / release scripts).

**Comment by eps1lon** [comment]
This wasn't much about Yarn VX but rather about the security concern. When somebody changes the lockfile (or the offline cache), the cache should be verified. When the lockfile isn't changed you can rely on the offline cache (assuming that it was previously verified).

So maybe do a `yarn install` that ignores the offline cache (or rather refreshes it) and then fail CI if any change would've been comitted (e.g. `git diff --exit-code`). And only do that step when the corresponding lockfile changed (or do it once at the start of the pipeline to be safe).

The frustrating part in that case would be that you fail the whole pipeline on network errors (but maybe give network a bit more time on the verify first step?).

> @eps1lon: Flow needs the node_modules directory anyway, so even switching to yarn v3, we'd still need to manifest the node_modules directory.

In Yarn v3 you'd use the checked in cache (what is now offline cache) to manifest node_modules and therefore ignore network. I actually don't think there's any meaningful difference between Yarn v3 install cache with node-modules linker and Yarn v1 + offline cache. But maybe someone should just test how that'll work 🤔

**Comment by kassens** [comment]
Closing this for now, as I think we should first try to fix the cache key somehow. Not sure how to debug that though.

**Pull request closed without merging**
