### PR TITLE
Rename Javascript to JavaScript

### PR DESCRIPTION
**Pull request by lipis**
Not intrusive :)

### CODE REVIEW

**Comment by aweary** [comment]
Good with me!

**Comment by mjaltamirano** [comment]
I still see "Javascript" just below the "Rendering Multiple Components" section of the [Lists and Keys section](https://facebook.github.io/react/docs/lists-and-keys.html).

**Comment by lipis** [comment]
Fixed in the source though.. https://github.com/facebook/react/blob/master/docs/docs/lists-and-keys.md

**Comment by mjaltamirano** [comment]
Yeah, the source is definitely clean. I just thought I'd flag it in here since I noticed those changes weren't present in the Github pages documentation! Was going to make a PR of my own :)

**Comment by gaearon** [comment]
Sorry, we haven’t run the doc sync script yet so the site uses old version.
We'll run it soon. 😉

**Pull request merged**
