### PR TITLE
ReactDebugToolEventForwarderDevTool

### PR DESCRIPTION
**Pull request by troydemonbreun**
Per discussion with @jimfb on [6398](https://github.com/facebook/react/pull/6398#issuecomment-215277455)

### CODE REVIEW

**Comment by troydemonbreun** [comment]
@jimfb I did not forward the `*Flush` and `*Timer` events in `ReactDebugTool`, should I do those as well?

**Comment by jimfb** [comment]
I'm also curious to hear what @sebmarkbage thinks.

I really don't have a strong opinion here.  Just seems like the React events are among the most critical events, so it would make sense that each renderer would supply them to the devtools as part of the same stream/registration process.

This also avoids an edge case where someone writes a renderer that happens to use an event name which React subsequently chooses to use.  Any devtool listening to both React and MyReactRenderer would break.  However, if the renderer is responsible for forwarding the event, it means that renderer can rename/modify/appendInfo as appropriate for the given event.

**Comment by troydemonbreun** [comment]
@jimfb Any interest from the team on this?

**Comment by gaearon** [comment]
@troydemonbreun 

Sorry we didn’t come back to this. I believe @spicyj needed something similar in #6765 but went with a simpler option of [adding any DOM devtools to ReactDebugTool automatically](https://github.com/facebook/react/blob/c0ecde687ae3e599dced83a111e57ed49897b0b9/src/renderers/dom/shared/ReactDOMDebugTool.js#L44).

So this implementation appears no longer necessary, but an equivalent got merged. Thank you for the effort though!

**Pull request closed without merging**
