### PR TITLE
Add function to patch rAF and Observers API

### PR DESCRIPTION
**Pull request by tyao1**
## Summary

Browsers don't set `window.event` for some events, but ReactDOM needs the value to get the correct priority for current event.  Monkey patching the browser API would be a way to unblock this. It's unclear how we will enable the monkey patching. This PR just prepares a function to patch first. 

## How did you test this change?

`yarn test monkeyPatchEvents-test`
Tested manually on a playground

### CODE REVIEW

**Comment by acdlite** [comment]
Let's keep the PR open though because I think we might still decide to patch rAF. I believe that's still an unresolved question.

dispatchEvent is the higher priority, though.

**Comment by tyao1** [comment]
No worries! I will apply similar code to dispatchEvent
> we changed to a different strategy where default is always rAF-aligned, so these APIs don't need special treatment.

ah makes sense. 

> I think we might still decide to patch rAF.

why would we still need to patch rAF? is it because users can have rAF and call react methods in it?

**Comment by acdlite** [comment]
> why would we still need to patch rAF? is it because users can have rAF and call react methods in it?

setState inside of a rAF callback should ideally be flushed synchronously in a microtask, but because rAF callbacks don't set window.event we treat it as a default event, so with the current strategy it would get flushed in the _next_ rAF callback, which is too late.

**Comment by tyao1** [comment]
closing for now since we decided to not patch rAF

**Pull request closed without merging**
