### PR TITLE
Unify the way we fork modules

### PR DESCRIPTION
**Pull request by gaearon**
This unifies the ad hoc way we fork modules so it's easy to see which modules are forked under which conditions, and how to add new forks. This will help us get rid of the existing external dynamic injection that we still rely on in www (after this is merged).

### CODE REVIEW

**Comment by gaearon** [comment]
Verified the first commit doesn't change a single byte in the bundles.

**Comment by bvaughn** [comment]
❤️ This looks great, Dan

**Comment by gaearon** [comment]
The second commit adds my custom plugin for replacing forks since `rollup-plugin-alias` doesn't quite work for us (not sure if bug or intentional). https://github.com/rollup/rollup-plugin-alias/issues/34

I figured more control is nicer anyway since it's a pretty important part.

**Comment by gaearon** [comment]
Verified the final changes don't change the build either.

**Pull request merged**
