### PR TITLE
Fix broken build script --unsafe-partial mode

### PR DESCRIPTION
**Pull request by bvaughn**
Fixes the `--unsafe-partial` flag in the build script.

This series of commands _fails_ on main but _works_ in this branch:
```sh
# Download a known stable build of React:
scripts/release/download-experimental-build.js --commit=main

# Build only some packages with local changes:
yarn build -- --unsafe-partial --type=node_dev react-dom/index,react/index

# Throws an error about unexpected end of JSON string in main branch.
# Also leaves the build folder in an unusable state.
```

This PR fixes the issue by replacing the `ncp` package with `recursive-copy`.

### CODE REVIEW

**Review by jstejada — APPROVED** [review]
okay! why does the change in the library fixes the issue? also looks like ci is failing

**Comment by bvaughn** [comment]
Looks like CI is pretty unhappy with this. Not sure if that's more false positives (which we get pretty often these days) or if that indicates a problem.

**Comment by bvaughn** [comment]
> why does the change in the library fixes the issue?

An explanation is in the commit message for 88f72b4940999e1d5949603a447a0012eccc1665:

> The 'ncp' package hasn't been undated for ~7 years and seems buggy based on my own testing of the Rollup build scripts. (There is a race condition that I can repro 3 out of 4 times where copying a JSON file resolves the ncp() callback while the file's contents are still empty. This breaks scripts like ours which have subsequence calls to read/parse the copied JSON.
> 
> Based on my testing, the 'recursive-copy' package does not have this problem.

**Comment by jstejada** [comment]
oh, thanks! sorry i missed that explanation in the commit message, will make sure to look there as well in the future

**Comment by bvaughn** [comment]
LOL no it's my fault. I should have put it in the description. My bad. I remembered writing it but forgot it wasn't in the PR.

**Comment by bvaughn** [comment]
I might have to give up on this for now b'c I have other stuff to do. I'll file a bug for follow up instead!

**Pull request closed without merging**
