### PR TITLE
Upgrade to ESLint 4.1 and add no-focused-tests rule

### PR DESCRIPTION
**Pull request by bvaughn**
[It's too easy for focused tests to slip into the repo.](https://github.com/facebook/react/pull/11901#discussion_r159417632).

This PR addresses this by doing the following:
* Runs a lint rule on tests only that errors if it sees `fdescribe` or `fit` calls.
* Changes `file:` to `link:` for our custom, internal rules (just to simplify updating these in the future).
* Updates `eslint` from 3.10 -> 4.1 and `babel-eslint` from 7.1 -> 8.0 so that we can run this new rule only against tests.

### CODE REVIEW

**Comment by gaearon** [comment]
>due to our use of file:

Let's change it to `link:`?

**Comment by bvaughn** [comment]
> OK but maybe scope it to `-test.js` and `-test.internal.js`?

I'm unclear of how to do this?

Based on [the docs](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) I would expect something like this to work:

```js
module.exports = {
  rules: {
    // ...other rules...
    'react-internal/no-focused-tests': 0,
  },

  overrides: [
    {
      files: '**/__tests__/*.js',
      rules: {
        'react-internal/no-focused-tests': ERROR,
      }
    }
  ]
};
```

But I've tried a few variants and none of them work. Seems like `overrides` is just being ignored. I must be missing something.

**Comment by bvaughn** [comment]
> Let's change it to `link:`?

It seems the contents of `eslint-plugin-react-internals` get copied to `node_modules` when you `yarn install`, but then changes are not synced (regardless of whether we use `file:` or `link:`) unless you re-run `yarn install`.

I'm not very familiar with this type of intra-project linking.

I'm not convinced this needs to be fixed _right now_ though, as running `yarn install` "fixes" the issue and seems like the obvious thing to try if a lint rule can't be found. (Plus this folder doesn't change often.)

**Comment by gaearon** [comment]
>but then changes are not synced (regardless of whether we use file: or link:) unless you re-run yarn install.

`link:` just creates a symlink so I don't see how changes could be *not* reflected unless yarn bugged out. Note that you'd need to change lockfile too for that to work. The easiest way is to first `yarn remove <name>` and then `yarn add --dev -W link:<path>`.

**Comment by thymikee** [comment]
@bvaughn Psst, there's [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest) out there in the wild, may be handy here (no-focused-tests rule is already there).

**Comment by bvaughn** [comment]
Love the suggestion of using a shared rule, @thymikee! When I tried that rule on our codebase, it errored with a "_Cannot read property 'type' of undefined_" error. I will try to find time to look into that a little more.

**Comment by thymikee** [comment]
Appreciate if you could trace it and file an appropriate issue :) cc @SimenB

**Comment by bvaughn** [comment]
> Appreciate if you could trace it and file an appropriate issue

Sure, sure. Like I said, there seemed to be several issues. If you beat me to it though, you can reproduce by checking out this repo, applying the below patch, and running, `yarn lint`:

```diff
diff --git a/.eslintrc.js b/.eslintrc.js
index 57f7888f9..7066c3f9c 100644
--- a/.eslintrc.js
+++ b/.eslintrc.js
@@ -10,6 +10,7 @@ module.exports = {
   'root': true,
 
   plugins: [
+    'jest',
     'react',
     'react-internal',
   ],
@@ -40,6 +41,9 @@ module.exports = {
     'space-before-blocks': ERROR,
     'space-before-function-paren': OFF,
 
+    // https://github.com/jest-community/eslint-plugin-jest
+    'jest/no-focused-tests': ERROR,
+
     // React & JSX
     // Our transforms set this automatically
     'react/jsx-boolean-value': [ERROR, 'always'],
@@ -57,7 +61,6 @@ module.exports = {
 
     // CUSTOM RULES
     // the second argument of warning/invariant should be a literal string
-    'react-internal/no-focused-tests': ERROR,
     'react-internal/no-primitive-constructors': ERROR,
     'react-internal/warning-and-invariant-args': ERROR,
   },
diff --git a/package.json b/package.json
index dfcb33edf..b9eda8901 100644
--- a/package.json
+++ b/package.json
@@ -50,10 +50,11 @@
     "del": "^2.0.2",
     "derequire": "^2.0.3",
     "escape-string-regexp": "^1.0.5",
-    "eslint": "^3.10.2",
+    "eslint": "^4.15.0",
     "eslint-config-fbjs": "^1.1.1",
     "eslint-plugin-babel": "^3.3.0",
     "eslint-plugin-flowtype": "^2.25.0",
+    "eslint-plugin-jest": "^21.5.0",
     "eslint-plugin-react": "^6.7.1",
     "eslint-plugin-react-internal": "link:./scripts/eslint-rules/",
     "expect": "^21.3.0-beta.4",
diff --git a/yarn.lock b/yarn.lock
index a5ca34b57..16f6c5086 100644
```

(I omitted the `yarn.lock` portion of the diff since it can be regen'ed easily)

**Comment by thymikee** [comment]
Got a quick look and the errors in this diff come from ESLint 4 (not sure why though). All seem to work well under v3.

**Comment by SimenB** [comment]
The rule throwing is `no-unused-vars`, a core eslint rule. Just upgrading to eslint 4 throws the error, whether or not the jest plugin is in there.

I have zero clue how that happened, my shot in the datk is a bug in babel-eslint.

**Comment by SimenB** [comment]
It has something to do with config resolution in eslint 4. Doing `rm packages/*/package.json` makes lint pass with eslint 4. My guess is eslint treats package.json as root, but I don't know why... We don't have this issue in the Jest repo.

**Comment by thymikee** [comment]
@SimenB upgrading both `eslint` and `babel-eslint` works, totally forgot about it.

**Comment by SimenB** [comment]
The fix is to upgrade to babel-eslint@8, you're hit by https://twitter.com/geteslint/status/944829414159810560.

It will give annoying peer dep warning from fbjs config (maybe you can poke someone for https://github.com/facebook/fbjs/pull/275)

**Comment by bvaughn** [comment]
> OK but maybe scope it to -test.js and -test.internal.js?

Unfortunately, this was not possible with ESLint 3.x (what we used). The `overrides` option was added in ESLint 4.1. 😄 

I've gone ahead and updated it, and in the process switched us over to use the shared rule mentioned above. 

Based on my own local testing, the new rule only runs on tests. `yarn lint` passes.

**Comment by bvaughn** [comment]
Thanks @thymikee and @SimenB (and Dan of course)

**Comment by SimenB** [comment]
If you can think of any rules for jest you'd like to have, please say so!

**Pull request merged**
