### PR TITLE
Add workspaces hash to yarn cache key

### PR DESCRIPTION
**Pull request by rickhanlonii**
This should hopefully fix the tests on the main branch.

### CODE REVIEW

**Review by bvaughn — COMMENTED** [review]
Would we also hit this caching problem on the same branch if we added new deps?

**Comment by rickhanlonii** [comment]
If we add new deps, the yarn.lock checksum should change and break the cache

**Comment by rickhanlonii** [comment]
I believe that the issue here is that we changed the workspace, which requires a yarn install, but we didn't change the yarn.lock so when the PR was merged we used the cache node_modules and didn't run yarn.

If that's the case, then this PR won't solve the issue. Looking into a real fix now.

**Review by bvaughn — APPROVED** [review]
Did not read.

**Pull request merged**
