### PR TITLE
Bump Jest to 16

### PR DESCRIPTION
**Pull request by gaearon**
This just updates Jest.

### CODE REVIEW

**Comment by yaycmyk** [comment]
You could add a `cacheDirectory` entry as well to keep rebuilds speedy on CI. Otherwise, coverage runs can take quite a while. 

```
"jest": {
  "cacheDirectory": "node_modules/.jest_cache"
}
```

Or something like that, and make sure node_modules are cached by Travis if they aren't already.

**Comment by Aweary** [comment]
@gaearon any blockers for this?

**Comment by yaycmyk** [comment]
I personally would not merge until the Babel transform and object printing
issues are resolved.

**Comment by yaycmyk** [comment]
https://github.com/facebook/jest/issues/1922 and https://github.com/facebook/jest/issues/1772 specifically.

**Comment by yaycmyk** [comment]
Alrighty, now that the depth limiting change is in, I'd switch to `jest@17.0.1` and this should be good to go.

**Comment by yaycmyk** [comment]
I'd be happy to do both things if you want @gaearon?

I can do it tonight and send a PR.

**Comment by gaearon** [comment]
Please do!

**Pull request closed without merging**
