### PR TITLE
Update 03-interactivity-and-dynamic-uis.md

### PR DESCRIPTION
**Pull request by segmentationfaulter**
fixed a typo

### CODE REVIEW

**Comment by zpao** [comment]
Thanks for catching this. Would you be interested in also fixing this in the translated versions of this page?

**Comment by segmentationfaulter** [comment]
@zpao I never knew there are translated versions of React Docs.

**Comment by alexzherdev** [comment]
@zpao Sorry if off topic - I have seen the translations in the repo, but haven't figured out how to access them through the docs site itself. Are they actually available on facebook.github.io/react ?

**Comment by zpao** [comment]
@alexzherdev - translations are published but not setup well (eg most links are broken, nav links always go back to English). https://facebook.github.io/react/docs/why-react-ru-RU.html is a Russian translation for example. #4633 has some (dated) progress on making the translated content more accessible.

@segmentationfaulter - still interested in fixing up the translated files or shall we just handle that part?

**Comment by segmentationfaulter** [comment]
@zpao I would suggest handle this part for now.

**Comment by zpao** [comment]
Thanks, will followup :) Sorry for the delay getting this merged!

**Pull request merged**
