### PR TITLE
[Website] Add Facebook Open Source footer.

### PR DESCRIPTION
**Pull request by hramos**
Replace the old footer with the one we have adopted in the GraphQL and React Native websites, for consistency.

I'd like to get two review passes on this: 
* one technical pass in terms of integration into the existing codebase, and 
* one content pass to cover what links should be included and under which sections.

We'll likely need to come back to this and update the links as we expand the docs.

Preview (page content ommitted for clarity):
screencapture-127-0-0-1-4000-react-index-html-1475615476564

### CODE REVIEW

**Comment by lacker** [comment]
Is this compatible with https://github.com/facebook/react/pull/7870 ?

**Comment by lacker** [comment]
For content, I think this is OK for now, but I also think we should revisit the links once we actually have all the new docs written. The technical integration seems good to me too, as long as we make sure something sane happens on mobile.

**Comment by hramos** [comment]
This PR is not currently compatible but it shouldn't be too much trouble to update my CSS to use #7870's mobile-friendly changes.

**Comment by vjeux** [comment]
Great initiative for the footer :)

**Comment by hramos** [comment]
#7870 has been merged, and mobile changes have been taken into account in this PR.

**Pull request merged**
