### PR TITLE
[DevTools] Named hooks

### PR DESCRIPTION
**Pull request by bl00mber**
## #16474
This is the implementation of main proposed solution based on babel DEV-only AST transform, supporting built-in hooks.
If name is the default hook name (i.e. state for setState, reducer for useReducer), the hook is not injected by transform plugin and ignored by devtools.
Three methods of hook name extraction are used: first array item, identifier name, first argument name.

Supports:
* useState - first array item
* useReducer - first array item
* useRef - identifier name
* useCallback - identifier name
* useMemo - identifier name
* useContext - first argument name

## Before
named-hooks-before

## After
named-hooks-after

### CODE REVIEW

**Comment by gaearon** [comment]
Sorry we haven't gotten around to reviewing yet. This will be important to get back to but we haven't prioritized it yet.

**Comment by eps1lon** [comment]
Bump

**Comment by bl00mber** [comment]
@bvaughn

**Comment by bvaughn** [comment]
I think this is probably more of the direction we'll be heading with this feature, once we have the bandwidth to land the change and test it and roll it out:
https://github.com/MLH-Fellowship/react/pull/115

**Comment by bl00mber** [comment]
@bvaughn thanks for the review.

**Comment by bvaughn** [comment]
Thank you for this PR!

We ended up going with another solution for this: #21641

**Pull request closed without merging**
