### PR TITLE
Set deletedTreeCleanUpLevel to 3

### PR DESCRIPTION
**Pull request by gaearon**
As far as I understand the result of testing this was positive. Anything holding us off from hardcoding it?

Related to https://github.com/facebook/react/issues/16087.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Can we regress on this in case we need to for implementation details?

**Comment by gaearon** [comment]
Yea I think it's "best effort", not a guarantee.

**Review by acdlite — APPROVED** [review]

**Comment by robbecker-wf** [comment]
Would this be released in React 18 or backported to React 17?

**Comment by gaearon** [comment]
No plans to backport to 17. Can't promise we'll keep it in 18 (or that it won't regress at some point) but unless something else changes, this change would be in 18.

**Comment by trentgrover-wf** [comment]
For posterity - We (Workiva) have verified that our memory leak problems are resolved by this fix in master. Is there any rough expectation for when this will receive an official release?

**Comment by gaearon** [comment]
Please see my reply in https://github.com/facebook/react/issues/16087#issuecomment-871055642

**Pull request merged**
