### PR TITLE
Accept a Node engine of version 6.X.X

### LINKED ISSUE #6644: React does not support Node v6.0.0
The `package.json` does not accept a node engine of version 6.x

I don't think that there is some regressions caused by Node v6, so it should be okay?

### PR DESCRIPTION
**Pull request by RaitoBezarius**
This should fix #6644 -- I ran the test suite with Node v6.0.0 and NPM v3.8.6, all the tests were passing.
Thanks in advance!

### CODE REVIEW

**Comment by zpao** [comment]
Yea, this should be fine. Thanks :)

**Comment by keyanzhang** [comment]
When I run `npm run build` with node v6.0.0, the first 2 tasks (`delete-build-modules` and `build-modules`) warn about an outdated `graceful-fs` dep. The warnings don't show up when building on node v5.11.0. 

I'm not sure which package has this dependency tho. Should this be updated @zpao?

```
> grunt build

Running "delete-build-modules" task
(node:32080) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[14:43:14] Using gulpfile ~/fb/react/gulpfile.js
[14:43:14] Starting 'react:clean'...
[14:43:14] Finished 'react:clean' after 34 ms

Running "build-modules" task
(node:32081) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[14:43:14] Using gulpfile ~/fb/react/gulpfile.js
[14:43:14] Starting 'react:modules'...
```

**Comment by zpao** [comment]
Not much we can do if it's a dep we don't own. If you want to hunt it down and file an issue against whatever package is to blame, I encourage that :)

**Comment by keyanzhang** [comment]
@zpao It's related to tooling issues like #6433. For instance, `grunt` 0.4.x requires `glob` that requires `"graceful-fs": "~1.2.0"`.

However, I just diffed the build outputs on v6 and v5 and there's no difference. I guess we can ignore the warnings for now. 😀

**Comment by keyanzhang** [comment]
Oh that being said, should node v5 and v6 be added to the travis build matrix? @zpao

**Comment by zpao** [comment]
Nah, we generally recommend using (and most/all of the team uses) LTS versions for sanity so I think we'll just do that on Travis to cut down on the build matrix. Build output *should* be the same regardless.

**Pull request merged**
