### PR TITLE
Fix for #7170

### PR DESCRIPTION
**Pull request by troydemonbreun**
Fix for #7170

### CODE REVIEW

**Comment by troydemonbreun** [comment]
@keyanzhang Will [this](https://github.com/facebook/react/pull/7486/commits/79aa8eabba1413a5cfd0f6fd43cff4ce934800a3#diff-532ee6d7e82d5255713e145e0105802fR840) change invalidate your test "resets value of date/time input to fix bugs in iOS Safari" (and therefore break #7397)?

Thanks for your help.

**Comment by troydemonbreun** [comment]
@keyanzhang nevermind, apparently I had some fluke locally - sorry to bother you

**Comment by Aweary** [comment]
@troydemonbreun were you able to test and verify that this actually resolved #7170?

**Comment by troydemonbreun** [comment]
@aweary yes

**Comment by Aweary** [comment]
I cloned this locally and verified it worked as well, thanks @troydemonbreun!

**Pull request merged**
