### PR TITLE
Disable ViewportMetrics unless MouseEvent lacks support for pageX/pageY

### LINKED ISSUE #1300: React tracks scroll position internally and forces synchronous layout
React adds a scroll listener that tracks and caches the scroll position (I assume for some undocumented internal purpose). Additionally, the scroll listener forces a synchronous layout (see screenshot). This seems wasteful, especially considering that the values tracked are never exposed in the API.

What is the scroll listener used for? Can it be removed?

screen shot 2014-03-24 at 3 11 09 pm

### PR DESCRIPTION
**Pull request by gaearon**
This rebases #2271 by @syranide which fixes #1300.

The only change in the rebase is that the file moved.
I haven’t changed the logic.

@spicyj cleaned up the callsites internally so this should be good.

### CODE REVIEW

**Comment by syranide** [comment]
:+1:

**Comment by gaearon** [comment]
Oops, I merged before it linted.
Fixed the lint in 4c804361e089844c65dad251a0a1c7860771b563.

**Comment by spicyj** [comment]
@zpao Can we pick this into the next patch? @axemclion asked me about it today.

**Comment by zpao** [comment]
@spicyj This shipped in 15.0.0 (in the RCs even)… what issue are you guys seeing?

**Comment by spicyj** [comment]
Oh, my mistake. I thought I verified it hadn't been picked but I just checked again and it does look okay. @axemclion Can you let us know if you're still seeing a scroll listener added?

**Comment by Aweary** [comment]
@spicyj I just tested this in Chrome. `monitorScrollValue` is never called and there's no scroll listener attached that I can see.

**Comment by axemclion** [comment]
@spicyj I am using React 15.3.1 and for some reason, I still see the scroll event handler being added. The stack trace shows that it is from [here](https://github.com/facebook/react/blob/eaefd9052ae41d3318a2add286828a75da362193/src/renderers/dom/client/ReactMount.js#L376). Looks like this was because I was using JSDOM in my renderer and the change from this condition was not being me.

So yes, this is fixed and we no longer have a scroll handler.

**Pull request merged**
