### PR TITLE
Fix error handling when name is a Symbol

### PR DESCRIPTION
**Pull request by jon-ressio**
## Summary

Error discovered in a next.js application.  Normal warning about complex types being passed to client components from a server component, but in this case the code that tries to render a warning/error message actually causes a different error/exception that masks the original error.
I initially filed the issue against next.js ( https://github.com/vercel/next.js/issues/61966 ) with a repro example ( https://github.com/jon-ressio/vercel-prop-warn-error ).

I now think this is just from 1 case of String() not being called on name, so trying to concatenate a string and a symbol.  I fixed the two places I saw the same pattern.

## How did you test this change?

I have not tested it yet.  I can figure out how to yarn link and build next against my build of react that includes the fix, but it would take me a bit.  This feels like a pretty safe change, but if you'd like me to validate I can definitely do that, just let me know.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Thanks for reporting. I don't think this exactly the right fix. Because a client reference can never be extracted from a symbol export since it can't be referenced. Basically the proxy can't support symbols and should probably error in that case.

In particular the symbol trying to be extracted here is the `Symbol.toStringTag` symbol which maybe we should special case as being allowed in the proxy.

We can also special case detecting that this is a ClientReference when printing the error.

**Comment by sebmarkbage** [comment]
Alternative fix in #28355.

**Comment by jon-ressio** [comment]
Excellent, really appreciate the crazy-fast turnaround to get it fixed the right way.  See your tests, look good and should cover my case.

Thanks!

**Comment by sebmarkbage** [comment]
You got lucky I was working on improving error messages anyway. 😅

**Pull request closed without merging**
