### PR TITLE
fix: devtools cannot be closed correctly

### PR DESCRIPTION
**Pull request by Jack-Works**
## Summary

Fix devtools cannot be shutdown by bridge.shutdown().

### CODE REVIEW

**Comment by Jack-Works** [comment]
```
$ node ./scripts/jest/jest-cli.js --build -r=stable --env=development --ci
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'chalk'
Require stack:
- /home/circleci/project/scripts/jest/jest-cli.js
```

🤔?

**Comment by Jack-Works** [comment]
hello, @hoxyq can you take a look at this?

**Comment by hoxyq** [comment]
> hello, @hoxyq can you take a look at this?

Looks good to me, I will debug it on Monday to check if there are some downsides, because we've been using `bridge.send` for a long time now, to notify all bridge's subscribers. We might use both here, though, need to double-check.

**Comment by Jack-Works** [comment]
> > hello, @hoxyq can you take a look at this?
> 
> Looks good to me, I will debug it on Monday to check if there are some downsides, because we've been using `bridge.send` for a long time now, to notify all bridge's subscribers. We might use both here, though, need to double-check.

It has been a long time for me so I forgot why I found this code is incorrect. It maybe caused by the confusion between `send` and `emit`.

**Comment by hoxyq** [comment]
> > > hello, @hoxyq can you take a look at this?
> > 
> > 
> > Looks good to me, I will debug it on Monday to check if there are some downsides, because we've been using `bridge.send` for a long time now, to notify all bridge's subscribers. We might use both here, though, need to double-check.
> 
> It has been a long time for me so I forgot why I found this code is incorrect. It maybe caused by the confusion between `send` and `emit`.

This is really good catch, thanks for spotting this.

I can see that we are subscribing to `shutdown` event through `bridge` in different spots via `bridge.addListener('shutdown', ...)`.

But with our current implementation, it looks like this event is never fired: I've ran the test that you have updated, it fails.

I believe here we should call both `emit` and `send`, because calling `send` is required to notify other entities, for example:
https://github.com/facebook/react/blob/ce6842d8f528977119b80d969306c8475099f66e/packages/react-devtools-extensions/src/backendManager.js#L106-L134

**Comment by Jack-Works** [comment]
@hoxyq fixed!

**Review by hoxyq — APPROVED** [review]

**Pull request merged**
