### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by cloudy1**
*Before* submitting a pull request, please make sure the following is done...

1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`) - we've done our best to make sure these rules match our internal linting guidelines.
6. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

fix "unknown: Unexpected token" in "codepen.io".

### CODE REVIEW

**Comment by gaearon** [comment]
Thanks for the PR but I don't think that's the intention.
The intention was that you change *one line* from

```js
      <button className="square">
        {/* TODO */}
      </button>
```

to

```js
      <button className="square" onClick={() => alert('click')}>
        {/* TODO */}
      </button>
```

I'll leave to @lacker to decide how to fix this best.

**Comment by joh1234** [comment]
Update README
https://goo.gl/JBljdR

or 
http://bit.ly/2dK6Ojk

**Comment by Aweary** [comment]
@gaearon @lacker I think this can be resolved by changing:

> Try changing the tag returned in the `render()` function of the `Square` class to:

to something like:

> Try changing the opening tag of the element returned in the `render()` function of the `Square` class to:

**Comment by lacker** [comment]
I think @Aweary's suggestion is good here - I just tweaked the PR to follow the suggestion since it's such a small change that was easier than pinging this thread.

**Pull request merged**
