### PR TITLE
Clear timeout when component is unmounted, fixes #3623

### LINKED ISSUE #3623: ReactCSSTransitionGroup warns when removed while transition in progress
The [`noEventTimeout` timer](https://github.com/facebook/react/blob/2aeb8a2a6beb00617a4217f7f8284924fa2ad819/src/addons/transitions/ReactCSSTransitionGroupChild.js#L80) is not cleared when a child is unmounted while a transition is in progress. This causes a false positive warning.

### PR DESCRIPTION
**Pull request by sejoker**
Clear noEventListener timer when component is unmounted, fixes #3623

### CODE REVIEW

**Comment by spicyj** [comment]
I don't think this is quite right – since you're storing the timeout ID as a global now, you're mixing timers from different components together. You'll probably want to store it as `this.noEventTimout` or similar.

How did you test this?

**Comment by sejoker** [comment]
@spicyj thanks for feedback. I didn't find existing tests for the class. Will think how to cover the case with a test, although it maybe a bit complicated to do.

**Comment by spicyj** [comment]
It doesn't necessarily need to be a programmatic test, though that would be great. Would be good to know that it worked in manual testing at least.

**Comment by zpao** [comment]
@sejoker Are you interested in finishing this?

**Comment by sejoker** [comment]
@zpao I do but as I mentioned on the original issue https://github.com/facebook/react/issues/3623 I need help to reproduce the bug otherwise I cannot proceed any further.

**Comment by sejoker** [comment]
I cannot reproduce the case with false positive warning mentioned in the original issue so I am closing PR

**Pull request closed without merging**
