### PR TITLE
Warn for duplicate DevTools installations 

### PR DESCRIPTION
**Pull request by scyron6**
## Summary
This completes the tasks in issue #24157. It checks for duplicate installations using the extension ids (basically the same code from the previous pull request). If duplicate installations are detected, display a warning message to the user and write to local storage.

To check for duplicate installations, we take advantage of the constant extension ids for React DevTools. First, we get the current id of whatever extension we are in. If that extension is the chrome webstore extension, we check if the internal or local extension is installed. If it is the internal extension, we check the local extension is installed. If it is the local or an unknown extension, we can't reliably detect if other extensions are installed. To note, if it is the local extension and __DEV__ is true, we do not need to check for other extensions because they will automatically disable. 

Within the switch statement for 'local', I left in the separate if statement from the previous PR code. I can get rid of it, but I thought it would be good to keep in case we want to add separate handlers. I also removed the warning message if it is an unknown extension saying 'We cannot accurately detect separate extensions. You may have duplicate extensions installed which could cause errors'. Now we only display an error if a duplicate extension is actually detected.

## How did you test this change?

Testing this change was tricky because I obviously can't make changes to the published versions of devtools. Instead, I copied the unpacked build within the chrome extension folder and loaded it as a separate extension into chrome. I got rid of all content scripts and adjusted the background script to only respond to a message. I had to do this because chrome kept crashing when I had both installed.

First, I installed that extension into chrome. 
Screen Shot 2022-04-12 at 8 23 48 AM

Then I adjusted the extension ids in constants.js to reflect the test scenario. As you can see in the screenshot below, I set the CURRENT_EXTENSION_ID to the internal devtools and set the LOCAL_EXTENSION_ID to the sample extension I just installed. This way the function checkForDuplicateInstallations will believe it is currently in an internal installation, check if a local installation (my sample installation) exists, and since it is installed, print a warning message.

Screen Shot 2022-04-12 at 8 23 58 AM
Screen Shot 2022-04-12 at 8 24 16 AM

I then removed the installation and ran chrome again. The error message did not appear. 
Screen Shot 2022-04-12 at 8 24 47 AM

I also ran tests to check the following scenarios, but I did not take screenshots for all of them and was not sure how to automate the tests.

* Current extension id is the chrome webstore id and set local extension id to sample installation.
* Current extension id is the chrome webstore id and set internal extension id to sample installation
* Restart chrome after showing an warning message to see if it shows again
* Delete sample installation, rerun chrome and install installation again, rerun chrome and see the warning message.

### CODE REVIEW

**Comment by scyron6** [comment]
Hey I'm happy to continue working on it. It is a bit of a busy week at work for me, but I'll work on it this weekend.

**Comment by mondaychen** [comment]
@scyron6 sounds great. Thank you!

**Comment by mondaychen** [comment]
@scyron6 any updates?

**Comment by scyron6** [comment]
I am sorry I've gotten busy with work and some freelancing gigs. I am not going to be able to finish this out any time soon. Again, my apologies.

**Comment by mondaychen** [comment]
@scyron6 no worries. I'll take over

**Pull request closed without merging**
