### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Raksha25**
## Summary

I read the README very carefully and made the most precise changes while taking care of the tiniest details as per the best of my knowledge.

### CODE REVIEW

**Comment by acdlite** [comment]
Since these are all subjective nits that don't seem to alter or clarify the original meaning, I'm going to close. But thanks for your suggestions.

**Comment by adityamedhe** [comment]
What a shame 🤦

**Comment by Raksha25** [comment]
Hi @adityamedhe , this was not a spam PR. Look at the changes carefully, it was an attempt to remove minor errors. I understand their reason for not merging it. So it's better to analyse the thing carefully rather than sitting at your home in front of a screen and passing unnecessary remarks.

**Comment by Raksha25** [comment]
> What a shame 🤦

Hi @adityamedhe , this was not a spam PR. Look at the changes carefully, it was an attempt to remove minor errors. I understand their reason for not merging it. So it's better to analyse the thing carefully rather than sitting at your home in front of a screen and passing unnecessary remarks.

**Comment by adityamedhe** [comment]
@Raksha25 with all due respect Raksha, if you think my comment is unnecessary, so is this whole pull request. But just like the whole open source paradigm allows anyone to contribute and open PRs to mammoth projects like React, so does it allow me to have a say and express it openly. Also, I assume you too, created this PR while sitting at home in front of a screen, so I don't see how it makes you any different. Anyway, I hope you read this comment with the intention of understanding and not just responding.

You assume a lot about me. I did go through the pull request. It is after careful inspection of the changes submitted and the reactions, have I arrived upon the decision to comment. Say what you will, but the declining of pull request, the 14 downvotes on your opening comment, and the addition of `invalid` label all suggest that the maintainers _do_ consider this to be a spam PR. But let us not take their word for it and analyze the "errors" you've corrected -- 

"Error" Corrected|Why it is unnecessary/irrelevant/not an error
----|-----
|Added article "the" before "state out of the DOM" and "existing code" at two places|Refer [this page](http://www.butte.edu/departments/cas/tipsheets/grammar/articles.html) on rules for adding articles `a an the` in English language. More specifically, refer to the table at the top of the article. Clearly, "existing code" and "state" are **non count nouns** without a specific identity. (You are not referring to a particular piece of code or module, or state. For these, an article is not required to be added. So, while adding the article may or may not be that significant, we definitely can't say that it is a "minor error" at all.|
|Changed ["required to use" to "mandatory for using"](https://github.com/facebook/react/pull/19938/files#diff-04c6e90faac2675aa89e2176d2eec7d8R55)|I don't see how this is a "minor error". It is at best, a different wording of an already perfectly worded sentence. Or am I missing something?|
|[Added pronoun "you" to the sentence](https://github.com/facebook/react/pull/19938/files#diff-04c6e90faac2675aa89e2176d2eec7d8R71)|There is already a "you" pronoun at the beginning at the sentence ("To help you get your feet wet..."). So, an adding another pronoun is not required as we've already established the subject i.e. "you". Again, I do not see how this is a minor error.|

FAQs:
---
**Why did I take all this pain to type out such a huge comment? Do I not have any other meaningful work?**
I did it to only demonstrate that I'm not just another online heckler who "sits in front of a screen and passes unnecessary remarks".  My comment is backed by reasoning and, had it been not, I'd not have commented at all. Because believe me, unnecessarily harassing people and criticizing them is the worst possible use of my time.

**How does it matter to me? Why am I getting so much affected by this whole thing?**
- Due to pull requests like these, the credibility of Indian people in the OSS is rapidly declining. It causes the maintainers to tweet their frustration openly:
    - [Tweet by @gaearon (Dan Abramov, on the React team)](https://twitter.com/dan_abramov/status/1311692006775758853)
    - [Another Tweet in which India is mentioned](https://twitter.com/MarisaCodes/status/1311746146843471878)
- As you can see, so many people from our country are already promoting spam on PRs of huge and famous projects and doing all sorts of things that are drawing flak from the community. This affects other people who have nothing to do with all of this, to be automatically seen with raised eyebrows and a lot of assumptions being made about us. **I have been personally affected and stereotyped like this and that is one of the main reasons behind all this.**
- I hope you understand what a great thing OSS is and the fact that things like React, NodeJS, and a thousand other projects that are so critical in today's world and put food on the table of so many people, are actually made by people like you and me. This also brings a great responsibility. We should do all we can to keep the noise as less as possible and ensure that the maintainers are able to use their time best for the advancement of the project, and not things like these. In the end, it indirectly benefits us as the project moves ahead.

**Comment by gabrielferreiraa** [comment]
https://twitter.com/shitoberfest

**Comment by ujjwal-kr** [comment]
really a shame 💩

**Comment by Raksha25** [comment]
@adityamedhe  It makes sense. This time, I don't feel your comment was unnecessary as you were very much clear with your intentions. I understand your point and agree with it. No rage but I wanted to mention, if this is what you wanted to convey, it could have been done in a different/better/more explanatory way than the first comment.  Thankyou :)

**Comment by adityamedhe** [comment]
@Raksha25 thanks for your valuable suggestions on my self improvement, I'll definitely consider them and better myself per your recommendations. All the best for your open source contributions

**Comment by adityamedhe** [comment]
@Raksha25 thanks for your valuable suggestions on my self improvement, I'll definitely consider them and better myself per your recommendations. Also I'm grateful you didn't find my _this_ comment unnecessary. All the best for your open source contributions

**Pull request closed without merging**
