### PR TITLE
Extract errors from Error() and new Error() instead of invariant()

### PR DESCRIPTION
**Pull request by sebmarkbage**
The lint rule was updated but not the extract-errors script.

To test this, I first removed everything from codes.json, then ran extract-errors and then ran lint. Lint then found a couple of things missing. Namely in the partial renderer and react-suspense-test-utils. Perhaps because these are not included in the build.

However, then I restored codes.json and ran extract-errors again. This time it found a bunch that are not covered by the lint rule. What do we want to do about these?

Some these weren't using `invariant` before and so wasn't covered. However, they should've been covered by the lint rule, no?

### CODE REVIEW

**Comment by acdlite** [comment]
So I actually intentionally excluded these, mainly because we weren't previously using `invariant` to minify them and I wanted to keep the scope of the codemod down until we had a chance to discuss what our philosophy is for when to minify versus not.

https://github.com/facebook/react/blob/6485ef747249295c7bfb8e599b9dde76df143cec/.eslintrc.js#L140-L160

For example, I noticed that in some packages that only include one or two errors, the `formatErrorMessage` runtime is more bytes than if you didn't minify at all.

Also an open question whether it's worth minifying packages that aren't downloaded over the network.

But regardless of what we choose I think `extract-errors` shouldn't extract from packages that we don't also lint against, so maybe they should use the same array of file patterns.

**Comment by acdlite** [comment]
The other thing I did was add an explicit option to our bundle config to enable/disable minification per package. This was something else I wanted to discuss, because I had noticed the React Native errors weren't being minified, but I wasn't sure of the historical reasons for or against.

https://github.com/facebook/react/blob/6485ef747249295c7bfb8e599b9dde76df143cec/scripts/rollup/bundles.js#L844

In the meantime, I liked the explicitness of being able to control exactly which prod bundles get minified. Though if we decide we're going to minify all of them then I can remove it.

**Comment by sebmarkbage** [comment]
It's maybe a bit weird to have a few things be minified and not others in the same bundle.

Maybe it can be a config on the bundle whether it should run the extraction on it. That way you decide when configuring the bundle whether you expect it to be large and whether it'll be on the server or CLI.

The same source file could run on either server or client.

**Comment by acdlite** [comment]
Jinx!

**Review by acdlite — APPROVED** [review]
Stamping the changes to the extract-error script though maybe we should figure out which files to extract/not-extract before merging and line it up with the lint rule

**Comment by sebmarkbage** [comment]
Ignoring paths is not enough atm because of:

```
// eslint-disable-next-line react-internal/prod-error-codes
```

**Comment by sebmarkbage** [comment]
I pushed commits showing what happens if we ignore bundles minifyWithProdErrorCodes === false.

**Comment by acdlite** [comment]
I wrote an alternate implementation that scrapes the messages from the build artifacts. https://github.com/facebook/react/pull/22516/commits/8adbdb9cc2a9a7fa845ac776760750784bfa26b6

The Babel plugin (the one that replaces the error codes with `formatProdErrorMessage`) will output a FIXME comment with the expected message format. Then the `extract-errors` script will scrape those from the build directory and update `codes.json`.

I like this because you can run `extract-errors` on partial build output, without running the whole thing. And because runs on the actual build output instead of the source files.

**Pull request closed without merging**
