### PR TITLE
Update typescript

### PR DESCRIPTION
**Pull request by dmitriiabramov**
based on https://github.com/facebook/react/pull/6686

all i did is matched the `jest.d.ts` by regex and not string comparison (https://github.com/facebook/react/commit/cdc6e2acc7c985b6317f104aa8bdef68f4d6c35f)
the path that comes in is an absolute resolved path, so it never met the condition

i tested it with errors in type definitions and it failed (keep in mind that ts compiler has some sort of caching and to make it recompile you need to change the test file by adding whitespace or whatever)
screen shot 2016-05-18 at 9 53 29 pm
screen shot 2016-05-18 at 9 53 46 pm

will that resolve the issue?

ts compiler throws `undefined(linenumber)` errors, but i've no idea how to deal with that
cc @zpao @chicoxyzzy

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
it looks like it works after changing test file as you noticed

@zpao is that expected that `ReactClassEquivalence` test also fails?

@DanielRosenwasser can we prevent caching somehow? I didn't find any compiler option for that.

**Comment by chicoxyzzy** [comment]
Should I close #6686? I can't squash my previous commits now. @dmitriiabramov probably it would be better if you will send PR with your commit to my branch https://github.com/chicoxyzzy/react/tree/update_typescript so we can keep one PR open. But personally I don't mind if we will work on this feature here :)

**Comment by zpao** [comment]
I think caching is probably fine. Jest does it by default too.

@chicoxyzzy if you're ok having your commits squashed, @dmitriiabramov could do it in his branch and it will retain you as an author.

@dmitriiabramov - I think you're just introducing syntax errors right? What about type errors?

**Comment by chicoxyzzy** [comment]
@zpao @dmitiiabramov ok let's do it

I've seen type errors here. Part of my log
```
 FAIL  src/isomorphic/modern/class/__tests__/ReactTypeScriptClass-test.ts
● Runtime Error
Error: undefined(304): Argument of type 'string' is not assignable to parameter of type 'boolean'.
```

**Comment by dmitriiabramov** [comment]
yeah. i can confirm that it fails with type errors

**Comment by dmitriiabramov** [comment]
rebased and squashed

**Comment by facebook-github-bot-9** [comment]
@dmitriiabramov updated the pull request.

**Comment by zpao** [comment]
doit

**Comment by chicoxyzzy** [comment]
@zpao I want to update tests next and improve type definitions (or take them from `typings`?). Do you have any RFC for TypeScript-related things

**Comment by zpao** [comment]
No RFC. I would say just take definitions from typings.

Improving the TS tests is totally fine, just make sure we have the same set of tests with the same results in the ES6Class and CoffeeScript test files. We have a tests that ensures you have the same expectations so it *should* fail if you don't.

**Comment by chicoxyzzy** [comment]
Sure. Is it better to make new PR for that?

**Comment by zpao** [comment]
Yes please, that's a distinct effort. I'll merge this in now.

**Pull request merged**
