### PR TITLE
can refs attach happens before component lifecycle?

### PR DESCRIPTION
**Pull request by yiminghe**
Here is my use case:

Align component can make its root DOM node align with another node, so Align component need to access other DOM node (for example parent DOM node) on componentDidMount/DidUpdate.

Demo:  http://react-component.github.io/align/examples/simple.html

Currently I have to hack inside componentDidMount/DidUpdate using setTimeout: https://github.com/react-component/align/blob/4093774c326787830a1b57bd276300b040fc7fe4/src/Align.jsx#L33

Or is there a better way?

### CODE REVIEW

**Comment by jimfb** [comment]
I think the intent is that getting a ref means the referenced component has mounted into the dom and is available.  This allows the owner component to do things like measure the size of the referenced component.

If your Align component needs to access the parent dom node, can't you use `.parentNode` in your `componentDidMount`?

**Comment by yiminghe** [comment]
It's not just about parentNode, maybe sibling or any other nodes render by Align's owner component.

In the proposed change, ref is immediately accessible after render a component into dom. And in the release of 0.14, ref is actually a native dom node, I think it's appropriate.

**Comment by jimfb** [comment]
But what if the child component renders to an empty div (and holds a ref to the div) and then in `componentDidMount` fills the div with some contents (maybe a jquery widget or whatever).  The child component's DOM node may not be fully rendered until after `componentDidMount`.  This is a fairly common use case.  If you have the ref fire before componentDidMount, it means you get a ref to something prior to that component fully initializing.

**Comment by jimfb** [comment]
cc @sebmarkbage and @spicyj since I know they spent like half a day on the whiteboard trying to figure out the order of events for refs.  Maybe they'll have some input/thoughts/conclusions.

**Comment by spicyj** [comment]
The current ordering is deliberate. This way, when a ref to a component is resolved, you know that it is fully initialized (i.e., its componentDidMount has executed). Is it possible in your case for the child component to ask the parent to send it a signal once the parent is mounted? (Though executing callbacks on a parent component during the mount phase is tricky to reason about and is not recommended due to this timing issue.)

Long-term we'd like to support layout using a solution such as this:

https://github.com/reactjs/react-future/blob/master/04%20-%20Layout/02%20-%20Layout%20Components.js

Unclear yet whether we'll adopt that solution though.

**Pull request closed without merging**
