### PR TITLE
fixed unfound node error when Suspense is filtered

### PR DESCRIPTION
**Pull request by IDrissAitHafid**
fixes [#18924](https://github.com/facebook/react/issues/18924#issue-618218428)
fixes another occurrence of [#18256](https://github.com/facebook/react/issues/18256#issue-578077772) and [#19633](https://github.com/facebook/react/issues/19633#issue-680756123).

Reordering children of Suspense in a timed-out state can't be done, as in this state, it has two Fragment children one for the fallback and the other for the primary child, and for the tree to be built correctly, the primary child should be removed or skipped.

## How to reproduce it
Here's [the codesandbox](https://codesandbox.io/s/could-not-find-suspense-node-error-u0crl) code.

Untitled_ Oct 14, 2020 1_08 PM

cc @bvaughn

### CODE REVIEW

**Comment by gaearon** [comment]
Ahhh. Can we add tests to the Suspense DevTools test suites?

**Comment by IDrissAitHafid** [comment]
I really want to write the tests cuz I find reproducing this error on a test a bit challenging!
So yes I am working on it!

**Comment by bvaughn** [comment]
I was going to ask "can you write a test for this" :)

**Comment by IDrissAitHafid** [comment]
Ok, thanks!

**Review by bvaughn — APPROVED** [review]
Nice fix!

**Comment by IDrissAitHafid** [comment]
@bvaughn I have added the test, it was actually easier than I thought because you had already written everything (as always) 😅.

**Comment by IDrissAitHafid** [comment]
Thank you @bvaughn 😃 
As I was working on this PR, I think we should add a test for this case as well to help with these Suspense errors, but I couldn't think of a scenario that triggers it:
https://github.com/facebook/react/blob/2eb3181eb4247077eafc4df98d06d7a999ecf5d8/packages/react-devtools-shared/src/backend/renderer.js#L1561-L1562

And I have a question about this error message: 
https://github.com/facebook/react/blob/2eb3181eb4247077eafc4df98d06d7a999ecf5d8/packages/react-devtools-shared/src/devtools/store.js#L931
Correct me if I'm wrong 😅, but it confuses me as it seems that the opposite is the right one, I mean something like this:

> Children cannot be reordered during an addition or a removal operation.

 Or


> Children cannot be reordered after an addition or a removal operation.

**Comment by bvaughn** [comment]
> I couldn't think of a scenario that triggers it

Maybe a component that suspends twice? So suspend 1 -> resolve 1 and retry -> suspend 2?

> And I have a question about this error message

Not sure I understand.

DevTools backend sends updates to the frontend using specific message formats that have constraints. The ["re-order children" message](https://github.com/facebook/react/blob/master/packages/react-devtools/OVERVIEW.md#re-ordering-children) can only ever re-order children. It can never remove or add children.

Similarly, removing or adding a child can't reorder.

**Comment by IDrissAitHafid** [comment]
Yes, but it should be suspended twice in row something like: suspend 1 => suspend 2.
> Maybe a component that suspends twice? So suspend 1 -> resolve 1 and retry -> suspend 2?

 
I am fully aware of those constraints, what I wanted to say is that that error is thrown whenever you try to reorder children of a node just after an addition or a deletion of a child of the same parent.

Say we have a tree like this: 

- Parent => child 1 + child 2 + child 3

After removing child 3, the tree will be: 

- Parent => child 1 + child 2 

Now in some cases, if the frontend tries to reorder the children the error is thrown.    

 Here I have triggerd it, to show this console:    
image

**Comment by bvaughn** [comment]
Sorry, I'm not really following along with what you're asking WRT the suspend 1 => 2 thing.

Regarding the second point, I can't actually see which node (ID) things are being reordered for. Is this for Node 4? Can you repro this in a test?

**Comment by IDrissAitHafid** [comment]
What I understand from this line:
https://github.com/facebook/react/blob/2eb3181eb4247077eafc4df98d06d7a999ecf5d8/packages/react-devtools-shared/src/backend/renderer.js#L1561-L1562
is that there's no resolve in between, that's why I am confused.

For the error don't worry it's resolved on this PR (I have just undone it for the screenshot).
I am actually talking about the error message itself 😅.

> Is this for Node 4?

based on that operations array, after this `Store Add node 18 (div) as child of 4`, there's two **update tree base duration** operations followed by a **re-order** operation of 18 and 19 of the parent 4.

> Can you repro this in a test?

Ok, I'll see if I can.

**Comment by gaearon** [comment]
>is that there's no resolve in between, that's why I am confused.

This is just the case where the *fallback tree itself* is updated. E.g. `<Suspense fallback={state ? <A /> : <B />}>...</Suspense>`

**Comment by IDrissAitHafid** [comment]
thanks @gaearon, that made it clear. I'll add a test for it then 😁

**Pull request merged**
