### PR TITLE
[future uncertain] Add support for pointer events

### PR DESCRIPTION
**Pull request by syranide**
**The future of pointer events seem uncertain, this PR should not be accepted until it is decided.**

http://www.w3.org/TR/pointerevents/, only IE supports it at the moment it seems, you should be able to polyfill with http://handjs.codeplex.com/

1. I have reused EnterLeaveEventPlugin to power both Mouse and Pointer, feedback on my rewrite appreciated. One possibility is to construct a lookup map instead for isMouseEvent/isPointerEvent/isOverEvent/isOutEvent/etc, but I'm thinking it might just make the code more complex.
2. I took the liberty of stripping the alignment spacing in SimpleEventPlugin because I would still have had to realign everything, and this way makes future updates less likely to conflict. It's also consistent with ReactEventEmitter.
3. Should `mouseListenerNames` in `ReactDOMButton` include pointer events? Touch events too? Are there actually any events that you want it to attach when it's disabled?

```
   raw     gz Compared to master @ b75d11c6039e4d2ab796bce2a1934e9e69b2b7e7
 +4806   +613 build/react-with-addons.js
 +2175   +431 build/react-with-addons.min.js
 +4813   +591 build/react.js
 +2177   +446 build/react.min.js
```

### CODE REVIEW

**Comment by chenglou** [comment]
Btw Chrome is not adopting it: https://code.google.com/p/chromium/issues/detail?id=162757#c64

**Comment by iamdustan** [comment]
Unless they see a lot of dev support for it in userland (one comment is no. 128 on that lengthy thread).
More commentary (from a while ago): https://docs.google.com/document/d/17BUdF-uSg_0CUwhyenaB5FZeob0HK9DcD85lC1sH6cA/edit

And it is an official standard! http://www.w3.org/blog/news/archives/4430?pk_campaign=feed&pk_kwd=pointer-events-is-a-w3c-recommendation

**Comment by zoomclub** [comment]
flux-reactions is moving in a positive direction with view vs event separation of concerns. PointerEvents would make it ideal. It would be great for react to just manage input providers and event types themselves.

https://github.com/arqex/flux-reactions/issues/1

**Comment by syranide** [comment]
@iamdustan Interesting.

**Comment by iamdustan** [comment]
@syranide in what way? :)

**Comment by syranide** [comment]
Chrome is onboard now https://code.google.com/p/chromium/issues/detail?id=162757#c146

**Comment by zoomclub** [comment]
This is great news!

**Comment by syranide** [comment]
@sebmarkbage Now that PointerEvents seem to be gaining traction, should we go ahead and add support to React core?

**Comment by sebmarkbage** [comment]
I think we need to make a major design choice soon about what we want our event system to be. The browser's naive model is clearly not enough for a lot of use cases (sliding gestures, touch responder negotation, custom bubbling rules such as through abstraction layers instead of DOM layers, etc.). Building our own event system is fundamentally incompatible with other frameworks since the delegation/ownership model doesn't interact well between subtrees. Even if we did it, other frameworks might not and we remain incompatible anyway. Maybe we need two different optional event systems. Yet, we want the out-of-the-box experience to also be nice. We're also backporting some of the event systems from React Native back to the DOM.

Essentially it boils down to the fact that the componentization of events is still an unsolved problem since there is still global negotiation needed.

Maybe we should support it for the DOM regardless, but I think there is a much bigger discussion to be had about our event strategy.

**Comment by syranide** [comment]
> Maybe we should support it for the DOM regardless, but I think there is a much bigger discussion to be had about our event strategy.

@sebmarkbage Definitely, but it seems to me that you'll always have to expose the (almost) raw underlying event APIs, either directly or indirectly. There are millions of targets and none are 100% capable or even agree on the keyboard and mouse interface, so a forced standardized interface seems wholly unrealistic.

If users could componentize custom event APIs on-top of that it would be fantastic, but I imagine it's two-fold. Custom event subsystems on a per-subtree/root basis (requires some level of coordination) and event callbacks on a per-node/component basis (totally independent) that depend on either native or custom event subsystems.

So one way or another it seems to me that React won't be harmed by exposing PointerEvents the same way all other HTML events are currently exposed, it's just more of the same.

**Comment by zoomclub** [comment]
It would be great to learn more about what is in store for events in React. In the meantime or as an alternative Rx looks like a perfectly logical way of handling events in React apps. The Rx.DOM implementation is robust and is armed with Pointer and Touch events ready to go. See here:

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/events.md

**Comment by gaearon** [comment]
I’m closing this PR because there doesn’t seem to be enough momentum behind it. I think we should get better at closing PRs that are low on `momentum / support_cost` number, so that is what I’m trying to do here.

Like anything, it’s a matter of prioritization. I think that a good time to revisit this would be when Chrome supports Pointer events (at the moment it doesn’t). Let’s track any future work on this in #499. I do hope we’ll get this in eventually.

Thank you for your work on this!

**Pull request closed without merging**
