### PR TITLE
Replace vendor/constants recast transform with babel

### PR DESCRIPTION
**Pull request by spicyj**
Built files look the same up to parenthesization and quoting. This only saves 1.5 seconds out of ~20 on a clean build but it's a little simpler.

### CODE REVIEW

**Comment by spicyj** [comment]
(This conflicts with #3788…)

cc @sebmck – if you could take a look and let me know if this looks sane, I'd appreciate it.

**Comment by spicyj** [comment]
(it gets the @sebmck seal of approval!)

image

**Comment by zpao** [comment]
:thumbsup: I was actually going to look into this so thanks! :) I'll redo #3788 with babel (you did the hard part so it should be pretty easy)

**Comment by sebmck** [comment]
Also if you want to avoid those gross long node builders then you can [return a source string](http://babeljs.io/docs/usage/plugins/manipulation/#replacing-a-node-with-a-source-string).

**Comment by spicyj** [comment]
> NOTE: It's not recommended to use this API unless you're dealing with dynamic source strings

;)

**Comment by sebmck** [comment]
Sometimes you just gotta break the rules, like inlining styles in your JavaScript.

**Pull request merged**
