### PR TITLE
Allow components to render undefined

### PR DESCRIPTION
**Pull request by rickhanlonii**
Can be checked by a lint rule instead.

### CODE REVIEW

**Review by sebmarkbage — APPROVED** [review]

**Comment by ryota-murakami** [comment]
This thread helpful to know what's the reason for this change 👨‍💻
https://twitter.com/wongmjane/status/1415414995131670532

**Comment by sebmarkbage** [comment]
The original intention of this error was to catch missing return statements or empty early returns. It's an easy mistake when using early returns or multiple returns. This is better caught with a lint rule that can track that syntactically. Especially since this pattern is totally legit:

```
function Foo({children}) {
  return children;
}
```

And passing through an optional prop is legit:

```
function Bar({children}: {children?: Node}) {
  return <Foo>{children}</Foo>;
}
```

**Comment by nickmccurdy** [comment]
Does this need to be implemented in eslint-plugin-react or is another linter plugin already planned?

**Comment by iheyunfei** [comment]
I'm just saying
```tsx
const Foo: FC = ({ flag }) => {
  if (flag) {
    <div>
      hello, react
    </div>
  }
  return (
    <div>
      hello, world
    </div>
  );
}
```

**Comment by iheyunfei** [comment]
It may be subjective, but I'm more like explicit than implicit on these case.

> ```
> function Foo({children}) {
>   return children ?? null;
> }
> ```
> 
> 
>     
>   
> 
> And passing through an optional prop is legit:
> 
> 
> ```
> function Bar({children}: {children?: Node}) {
>   return <Foo>{children ?? null}</Foo>;
> }
> ```

**Comment by eps1lon** [comment]
> I'm just saying. And try to think about a big component.
> 
> ```tsx
> const Foo: FC<{ flag: boolean }> = ({ flag }) => {
>   if (flag) {
>     <div>
>       hello, react
>     </div>
>   }
>   return (
>     <div>
>       hello, world
>     </div>
>   );
> }
> ```

Is this not already covered by [`no-unused-expressions`](https://eslint.org/docs/rules/no-unused-expressions)? In other words: That example will not change behavior under this PR.

I think we can catch missing returns at some point at the type level (at least for TypeScript) since we can differentiate between `void` (missing return) and `undefined`:
```tsx
import * as React from 'react';
type ReactNode = undefined | null | string | number | React.ReactElement;

// @ts-expect-error A function whose type is neither void nor any must return a value.
function BadComponent(): ReactNode {}

function OkComponent(): ReactNode {
  return undefined
}
```

[Playground Link](https://www.typescriptlang.org/play?ssl=9&ssc=2&pln=3&pc=1#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQMAnmFplTAHIQAmrAvHACuAO14FgwrNzgAfOMMEAbRbLioYUCQHNVCkACMsUVdjwwAdKfwBRRVhBZhMenQD0ruAAEYqALRYADxZ8fyhiYwBBOAIRfGAIYTgAdwALCFRWJhY4YHRJYBgUozgANwhgaWFoFGFGOBBBdThKGEEoRORS5EVBLHM6GOE4hLgAIWRuAGESSEknAAoASgAuNjMuXjgAbwBfOgHYmHjEgHkAa2nwBMcYJdWrTh5WLbo4ZqxW9qFRLHFJbjoOyAA)

The problem is that we're blocked by https://github.com/microsoft/TypeScript/issues/21699 anyway. The TypeScript type-checker will continue to yell at you if you return `undefined` (just like it yells at you when you return a `string`).

**Comment by sebmarkbage** [comment]
Note that trying to fix this problem at the type level is exactly the issue we’re trying to avoid. Because it leads to a bigger headache and forked definitions along the way.

**Comment by eps1lon** [comment]
> Note that trying to fix this problem at the type level is exactly the issue we’re trying to avoid. Because it leads to a bigger headache and forked definitions along the way.

Could you elaborate what you mean by that? Are there some false positives that would be thrown at the type level but not with a lint rule?

**Comment by sebmarkbage** [comment]
Well specifically excluding `undefined`. Maybe we get it for free in TypeScript since we can't include `void` anyway in the definition. However, it still requires that the return type isn't explicitly set to void although maybe if you do that you're intentionally doing it so maybe that's ok.

**Comment by nickmccurdy** [comment]
Crossposting from https://github.com/yannickcr/eslint-plugin-react/issues/3020#issuecomment-882145680 to get more feedback:

Should linters warn when there's an explicit undefined return (`return undefined`)?

**Comment by ryota-murakami** [comment]
> Well specifically excluding undefined.

@sebmarkbage I don't get it.
@eps1lon showed the [playground](https://www.typescriptlang.org/play?ssl=9&ssc=2&pln=1&pc=1#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQMAnmFplTAHIQAmrAvHACuAO14FgwrNzgAfOMMEAbRbLioYUCQHNVCkACMsUVdjwwAdKfwBRRVhBZhMenQD0ruAAEYqALRYADxZ8fyhiYwBBOAIRfGAIYTgAdwALCFRWJhY4YHRJYBgUozgANwhgaWFoFGFGOBBBdThKGEEoRORS5EVBLHM6GOE4hLgAIWRuAGESSEknAAoASgAuNjMuXjgAbwBfOgHYmHjEgHkAa2nwBMcYJdWrTh5WLbo4ZqxW9qFRLHFJbjoOyAA) said  **TypeScript raise error as long as you never return undefined explicitly** so we don't try `exclude<ReactNode, undefined>` to fix that(this PR change allow unintended missing return as a valid ReactNode within type  level and lint rule) problem.


```typescript
import * as React from 'react';
type ReactNode = undefined | null | string | number | React.ReactElement;

// @ts-expect-error still throw error against missing return because ReactNode doesn't accept return type "void"
function BadComponent(): Exclude<ReactNode, undefined> {}

function OkComponent(): ReactNode {
  return undefined
}
```

[playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwCwAUDAJ5haZUwByEAJuwF44AVwB2-AsFFZecAD5xRwgDbL5cVDChSA5uqUgARlijrseGADpz+AKLKsILKJj0GjAPQe4AARioAWiwADzZ8IKhiU01gVTgYAAtiAHc4EyiUHWQpTTgQYFRUXThKGGEoUThjXGRhVHYbbj52XggsVFEyeDxcLDB4UvLKljY4ACIANwhgXjHGAjF8YAhKgCFkXgBhEkhpFwAKAEoALjhbYNxlYX4AHkaefgAaEXEsSWleAD44AG8AX0Y80WMGWlQA8gBrbbgFbOGBHU73Zq-RhwEpYMoVF4SKQyRh-IA)

**Comment by rickhanlonii** [comment]
Posted some more context to the React 18 Working Group: https://github.com/reactwg/react-18/discussions/75

**Comment by ryota-murakami** [comment]
@rickhanlonii Nice! Thank you. 😊

**Pull request merged**
