### PR TITLE
Run Flow for each renderer separately

### PR DESCRIPTION
**Pull request by gaearon**
This adds per-renderer Flow commands:

* `yarn flow dom`
* `yarn flow fabric`
* `yarn flow native`
* `yarn flow test`

If you forget to specify the one you need during local development, `yarn flow` will prompt you to do so. It should be possible to even run them in parallel although I’d expect it to be super slow so in practice you’ll probably use one at a time.

The typechecks are currently exactly the same between renderers. This is a preparation for https://github.com/facebook/react/pull/12792 which will shim the host config types for each renderer separately.

The `yarn flow-ci` command that runs on the CI is changed to run Flow with each renderer, one by one.

Internally, this works by having separate Flow configs in different directories (thus making Flow treat them as isolated from each other). We generate Flow configs from a single master template if you run `yarn`, `yarn flow`, or `yarn flow-ci`.

### CODE REVIEW

**Comment by gaearon** [comment]
This is ready for review.

**Comment by acdlite** [comment]
Is it still possible to spawn a Flow server?

**Comment by gaearon** [comment]
Yes, that's what `yarn flow` does now, both on master (since https://github.com/facebook/react/pull/12841) and here.

The full check has moved into `yarn flow-ci`.

**Comment by NE-SmallTown** [comment]
@gaearon Should we update the `PULL_REQUEST_TEMPLATE.md`?

**Comment by gaearon** [comment]
Sure.

**Comment by NE-SmallTown** [comment]
Are you working on this?

**Pull request merged**
