### PR TITLE
Update Lifting State Up not to mix up DOM value with component state

### PR DESCRIPTION
**Pull request by valscion**
A few weeks ago when teaching my friend, she got stuck on `this.state.value` vs. `event.target.value`. As the documentation talked a lot about "values", and the term "value" could mean three different things (values in general, the `value` prop / DOM value of the `<input>` component and the `value` in state/props), it was not weird that she got a bit confused.

I asked about this already from @gaearon in Twitter here: https://twitter.com/valscion/status/833776451442843649

### CODE REVIEW

**Comment by gaearon** [comment]
Can we also rename onChange then?

**Comment by valscion** [comment]
Yeah, we could. Maybe we could rename it to `onTemperatureChange`? Would that be OK?

**Comment by valscion** [comment]
There, that should do it ☺️. Let me know if you want further adjustments — I'm able to look at this again tomorrow

**Comment by valscion** [comment]
Anything I could do to get this shipped? Do I need to update the code pens to contain the new code, too?

**Comment by valscion** [comment]
Let me know if it was OK to change the codepen examples to also contain the updated code. Feel free to fork the pens for your account if you don't want them to show up under my name ☺️ 

* First pen: http://codepen.io/valscion/pen/VpZJRZ?editors=0010
* Second pen: http://codepen.io/valscion/pen/GWKbao?editors=0010
* Last pen: http://codepen.io/valscion/pen/jBNjja?editors=0010

**Comment by gaearon** [comment]
Can you also make a new GIF at the end? 😅

**Comment by valscion** [comment]
Oh yeah, sure, I can do that :smile:. Funny how I didn't see how many things would need to be changed but I'm totally fine by this :smile:

**Comment by valscion** [comment]
That should do it ☺️. Is there a way I could add the `review-needed` label back myself?

**Comment by gaearon** [comment]
We are no longer using our custom labels. 😉

**Comment by gaearon** [comment]
OK, that’s pretty great. Thanks for doing this.

**Comment by valscion** [comment]
:tada: Thanks for merging!

**Comment by valscion** [comment]
Hiya,

how and when do you update the documentations normally? It's been a week since this PR was merged. Do you only update the website with new major versions or some other milestone?

**Comment by gaearon** [comment]
Not really, just when somebody runs a script that updates the docs.

**Comment by gaearon** [comment]
Ran the script. Docs should update soon.

**Comment by gaearon** [comment]
Updated.

**Comment by valscion** [comment]
Thank you, I noticed yesterday already ☺️

**Pull request merged**
