### PR TITLE
Organize and add confs

### PR DESCRIPTION
**Pull request by GantMan**
Organization change: Upcoming proximity followed by past chronological.
This PR adds 3 unlisted confs and organizes it as previously described in PR #8007, which has since been moved because the file moved.

### CODE REVIEW

**Comment by mkonicek** [comment]
Nice to see so many conferences popping up!

**Comment by mkonicek** [comment]
In future PRs, can you please add a prefix to the commit message, like "[docs]" so it's clear what this commit does without looking at the source? It helps when writing release notes for example. From the title I wasn't sure what this PR organizes and what confs are - turns out it's conferences :)

**Comment by mkonicek** [comment]
@facebook-github-bot shipit

**Comment by mkonicek** [comment]
You should also add a test plan - screenshot showing it renders correctly on the website:

    cd react-native/website
    npm install
    npm start

**Comment by mkonicek** [comment]
I was going to merge this but then realized this was the React repo, not React Native :D

**Comment by lacker** [comment]
Seems useful to have a list of upcoming conferences. If it gets bothersome to maintain, though, we might have to remove it.

**Pull request merged**
