### PR TITLE
[Docs: Installation] Fix tabs responsive layout - Resubmit

### PR DESCRIPTION
**Pull request by AlmeroSteyn**
@gaearon Here is a clean PR

From old PR:
I fixed the tabs responsive styling. 

At the same time I made the tabs look more like tabs for the full layout with it breaking to a stacked layout at the 960px breakpoint used to stack the main navbar of the site.

What do you think?

### CODE REVIEW

**Comment by gaearon** [comment]
Can you post screenshots of what changed?

**Comment by AlmeroSteyn** [comment]
Sure.

Old version full width:
image

New version full width (font size did not change only zoomed out more with the capture):
image

Old version mobile:
image

New version mobile:
image

**Comment by Radi123** [comment]
@AlmeroSteyn - cool. I like this. I think this must be merged soon :smiley: :

**Comment by gaearon** [comment]
Thanks. I slightly tweaked it to my taste (limited the bottom line to the tab bar width).

**Comment by AlmeroSteyn** [comment]
Thanks!! And sorry for the mobile botch first time around. Browser minimum width was just not small enough to make the layout break :-s

**Pull request merged**
