### PR TITLE
Fix issue with SyntheticEvents and Proxies

### LINKED ISSUE #6187: Synthetic events proxy doesn't work for normal synthetic events
This blames to #5939, cc @kentcdodds 

Not sure yet if this is affecting all load events or just ones that are attached directly to nodes (for eg image). But the problem is that when we intercept `set` operations for `SyntheticEvent`s (but not "subclasses" like `SyntheticMouseEvent`), we don't have `target.constructor` @ https://github.com/facebook/react/blob/36798f7395d9b2e1cfaed988133d11fa88afa8f1/src/renderers/dom/client/syntheticEvents/SyntheticEvent.js#L199

Simplest repro: http://jsfiddle.net/ge8b0np9/ (will still fail w/o the load listener)

### PR DESCRIPTION
**Pull request by zpao**
Fixes #6187 (hacky but it seems to work)

### CODE REVIEW

**Comment by zpao** [comment]
Not quite, I missed another piece of this...

**Comment by sebmarkbage** [comment]
I suppose the subclasses should use Object.assign to inherit the static properties like they would on a native class.

**Comment by zpao** [comment]
The subclasses don't seem to be the problem though, it's the base class.

**Comment by sebmarkbage** [comment]
I think this might be setting up the wrong prototype:

https://github.com/facebook/react/blob/36798f7395d9b2e1cfaed988133d11fa88afa8f1/src/renderers/dom/client/syntheticEvents/SyntheticEvent.js#L193

Is that right? I think the second argument there should be extending the prototype of SyntheticEvent which has the right `.constructor` on it.

**Comment by sebmarkbage** [comment]
Or maybe not. That whole thing is so confusing. Create an issue to rewrite it and drop all the pooling shit?

**Comment by zpao** [comment]
Object.create to the rescue. I think it should be safe to use blindly there since we're already guarded to engines that support Proxies.

**Comment by koba04** [comment]
Sorry, It's my fault.
Thank you for fixing it!

This warning is also possible to detect adding properties in destructor instead of using Proxies.
The reason using Proxies is for making stack trace clearly.

https://github.com/facebook/react/pull/5947#issuecomment-178309118

> Or maybe not. That whole thing is so confusing. Create an issue to rewrite it and drop all the pooling shit?

I agree.
I'd like to consider and try refactoring SyntheticEvent.

**Pull request merged**
