### PR TITLE
Track error and warning messages by checking them into the repo

### PR DESCRIPTION
**Pull request by acdlite**
Updates the error code script to print out a list of warnings.

Additionally, CI will now fail if either the error code map or warnings list is not up to date. Similar to how `scripts/fiber/record-tests works`. Shouldn't be onerous because most commits do not change error or warning messages. If it fails, it prints a message with instructions on how to fix.

This will make it easier to track changes to errors or warnings.

### CODE REVIEW

**Comment by aweary** [comment]
Should the pull request template be updated too with instructions on updating the error/warning maps?

**Comment by sebmarkbage** [comment]
Do we really need this to block CI on a per-PR basis? We only need this when we publish new versions. Not running it doesn't really risk any regressions.

The idea with `scripts/fiber/record-tests` was that we needed to avoid regressions while we did the rewrite but we're close to be able to remove it. Arguably we could just tag the remaining explicitly and disable that script.

**Comment by acdlite** [comment]
We don't change error or warning messages that often, so most of the time you don't need to worry about it.

And when we do change or add them it's important that part gets reviewed. Without explicitly tracking them it's easy to accidentally change without the reviewer noticing.

But if we decide don't want to block CI I can remove that bit. The main reason I added this was to make it easier to update the whitelist in www, which can be done by running the script twice in two separate commits (or writing a new script to do that).

**Comment by acdlite** [comment]
I could also make it a Jest snapshot instead. Serves the same function but is maybe less confusing for contributors.

**Comment by sebmarkbage** [comment]
Let's remove the CI block for now. For context. The reason we added the whitelist in www to begin with is to make it __easy__ to rename and add warnings in this repo with minimal ceremony and review.

Otherwise if we wanted more ceremony around it we could just make it a blacklist instead.

**Comment by acdlite** [comment]
Ok will do

And personally I think a blacklist makes more sense but I'm probably not considering all the trade-offs that went into the original decision.

**Comment by sebmarkbage** [comment]
Basically, the motivation is that the status of FB's code base at any point shouldn't be a blocker to external contributions. I.e. external people will commit access should be able to land it without consideration if that will break FB and we shouldn't have elevated status.

In practice this hasn't been easy without a lot of context of what's being worked on anyway.

The secondary consequence is that we want to minimize any hinderance for us to pull the sync in as frequently as possible.

It seems to me that in the future, we'll need to run a build script to sync (for Rollup/flat bundles etc). So couldn't we just run this internally when we sync?

Everything about warnings is derived so there's no need to persist it in the repo.

The reason the error messages are persisted is because they have persisted IDs associated with them over time.

**Comment by acdlite** [comment]
I get that they're derived but I view it essentially like a Jest snapshot test (which I would have used to implement it had I thought about it before) and thought it'd be nice to require explicit approval when changing warnings or errors.

Anyway since the original motivation was calculate the diff in warnings between two commits I'll rewrite the script for specifically that use case.

**Comment by sebmarkbage** [comment]
Wouldn't you ideally want the diff between the previously landed version in www and the next version in www? So ideally the persistence would be in www, no? We already have the git commit hash there which would be enough to derive but we could also check in the warning messages if oyu want.

**Comment by acdlite** [comment]
Well yeah my thinking was that by checking the warnings into React, the GH sync script could be easily updated to diff the old and new files whenever we sync. Along with the snapshot rationale (making it harder to accidentally change messages) it seemed like a two-birds-one-stone thing.

But since we've decided the snapshot thing isn't valuable I'll just update the GH sync script to spit out a warnings diff whenever we run it.

**Comment by acdlite** [comment]
Closing in favor of #9097 and #9098

**Pull request closed without merging**
