### PR TITLE
[New Docs] Remove extra vertical spacing between items in the sidebar

### PR DESCRIPTION
**Pull request by ivanzotov**
Closes todo item in #7864

### CODE REVIEW

**Comment by ivanzotov** [comment]
In the current website the height of an item in the sidebar is 22px, so setting line-height to 1.6 looks same.

**Comment by gaearon** [comment]
Can you please post a screenshot?
Also, do you have any idea why this happened in New Docs?

**Comment by ivanzotov** [comment]
It changed after implementation of mobile layout – https://github.com/ivanzotov/react/commit/1fd7d9ab7a71c8e8c0a2590f05b71899f57e6b07#diff-edce6ff5a2d55fb4deadf85480f34736

screen shot 2016-10-14 at 3 06 13 pm

**Comment by ivanzotov** [comment]
It seems ok for mobile 
screen shot 2016-10-14 at 3 11 20 pm
as well

**Comment by gaearon** [comment]
Looks good to me. Can tweak later. Thanks!

**Pull request merged**
