### PR TITLE
Have jest check for window errors in a similar to console.error logs. Fix for #8260

### LINKED ISSUE #8260: Make sure that jest tests fail if an error is thrown within a jsdom event handler
In a few situations in our unit tests, we use .dispatchEvent on a jsdom DOM node in order to use the jsdom event system:

https://github.com/facebook/react/blob/e612826650ff68e73bff4d71db01fea8147ee1fd/src/renderers/dom/shared/wrappers/__tests__/ReactDOMInput-test.js#L127

But it appears that if the event handler throws (ex: change the onChange handler in that test to throw), then the error is silently ignored and does not cause the test to fail.

jsdom does make some attempt to report an error:

https://github.com/tmpvar/jsdom/blob/9.8.3/lib/jsdom/living/events/EventTarget-impl.js#L235

We should hook into this in our jest config (scripts/jest/test-framework-setup.js) and see if we can fail any test that triggers this exception behavior. From the implementation of reportException it looks like we might be able to do an onerror handler; if that doesn't work then hooking into their "virtual console" may be possible.

### PR DESCRIPTION
**Pull request by franciscofsales**
Fixes #8260

### CODE REVIEW

**Comment by joh1234** [comment]
Update README
https://goo.gl/JBljdR

or 
http://bit.ly/2dK6Ojk

**Comment by aweary** [comment]
@cpojer does this look right to you?

**Comment by cpojer** [comment]
sure

**Comment by aweary** [comment]
@franciscofsales can you resolve the conflicts when you get a chance?

**Comment by franciscofsales** [comment]
@aweary I synced and added the spyOn for window errors on a few tests. Hope all it's good now. Let me know if I can help any further.

**Comment by ttsui** [comment]
Any progress on getting this merged? 

Was caught out by this problem yesterday and wasted a good half day over it.

**Comment by gaearon** [comment]
@ttsui I don't understand. This PR is for the React repo infrastructure. It won't affect you as a Jest or React user.

**Comment by gaearon** [comment]
I'm going to close since we didn't do a good job reviewing and it got stale. The issue still exists but it seems like it's worth solving together with https://github.com/facebook/react/issues/11098#issuecomment-355032539. Thanks for the PR!

**Pull request closed without merging**
