### PR TITLE
Fix grammar in "Why Relay"

### PR DESCRIPTION
**Pull request by marcuswhybrow**
Should read: "eliminates bugs such **as** under- or over-fetching data"

### CODE REVIEW

**Comment by nonmadden** [comment]
:+1:

**Comment by jimfb** [comment]
Thanks!

**Comment by zpao** [comment]
In the future, please make docs changes to the `master` branch. The `gh-pages` branch is a compile target and this will get wiped out by future builds.

**Comment by marcuswhybrow** [comment]
Roger that. I did wonder where Jekyll was hiding.

**Pull request merged**
