### PR TITLE
Build distinct dev / prod & min builds

### PR DESCRIPTION
**Pull request by zpao**
_Hopefully_ this helps reduce some confusion about what each build actually is and maybe we'll see fewer people doing benchmarks with the dev version.

There's some more to do to make sure this is actually right and works, but this is the general idea. We'd build `react.dev.js` and `react.prod.js` and the minified version of each. We should do all the other ones as well (addons less important long term, but react-dom definitely needs this treatment because #7164).

We start recommending these file names as soon as they are part of a release. We keep building the plain `react.js` & `react.min.js` for compatibility. For v16 we stop building them entirely.

TODO:
- [ ] Remove the minified dev-mode warning. It won't make any sense. We might still want it for npm though
- [ ] Make sure prod build isn't already minified. It mostly is because of the `uglifify` step. We might not need those anymore anyway if we do this after rolloup (that step is only there to remove some `require`s but rollup handles that I think).
- [ ] docs updates
- [ ] Do 2 builds instead of 5 (should be able to just run uglify over the non-min code, can even have a `.map` then, and then copy the right files instead of doing a duplicate build).

### CODE REVIEW

**Comment by yaycmyk** [comment]
Not sure I agree with changing the names of both. Why not let react.min.js imply production (like all other JS libraries)  and offer a react.dev.min.js as an alternative?

**Comment by zpao** [comment]
If we had done this from the beginning, I'd agree. But the builds have existed like this for a long time and I'm afraid there would be more confusion from reusing the current files names (especially with things like npmcdn, bower). Plus, I kind of like that the use of .prod implies there is a .dev, whereas the alternative would not pique anybody's curiosity and they may think prod builds are the only thing.

We could maybe do that but it would have to happen at v16 and not before. I don't know when that will be. Maybe we could wait but it would mean living with the current confusion for longer.

**Comment by yaycmyk** [comment]
@zpao is the confusion so pervasive that it necessitates a major ergonomic change? Personally have never heard of this being an issue, but you folks definitely sample the feedback at a bigger scale.

**Comment by gaearon** [comment]
I see a new benchmark using DEV version every other week. The confusion unfortunately is pervasive.

**Comment by sebmarkbage** [comment]
Would it be enough to just rename `react.min.js` to `react.optimized.js` instead of splitting them out?

What if we use a build tool that inlines and minifies as a single batch then we can't keep separating them? There should be no reason to use one but not the other.

**Comment by gaearon** [comment]
>Would it be enough to just rename react.min.js to react.optimized.js instead of splitting them out?

I think the confusion is the other way around. People see a URL like https://cdnjs.cloudflare.com/ajax/libs/react/15.2.1/react.js and it doesn’t seem immediately wrong. So it’s the one that should be `react.unoptimized.js`.

**Comment by keyanzhang** [comment]
There are a few things that Rollup itself can't prune. For example `ReactComponentTreeDevTool` still [shows up](https://gist.github.com/keyanzhang/1dff99f6f54bcf9d4e3cc92ab407c41e#file-react-rollup-prod-unminified-js-L2451-L2456) in the unminified prod build and it will be removed by the `uglifify` step. Not 100% sure why but it might because of self-references.

**Comment by trueadm** [comment]
Closing this PR due to the work that's happened around Rollup and flat bundles on https://github.com/facebook/react/pull/9327

**Comment by gaearon** [comment]
For now we settled with @trueadm on using `react.development.js` and `react.production.min.js` but happy to change if the team doesn’t agree.

**Pull request closed without merging**
