### PR TITLE
Warn when textarea switches between controlled and uncontrolled

### LINKED ISSUE #16342: textarea does not show warning when switching from uncontrolled to controlled like inputs do
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

While things like `<input>` correctly get a warning when switching from uncrontrolled to controlled, I'm noticing `<textarea>` does not

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

Here's a codesandbox. Type in the input field, we see error (correct), change to textarea and start over, type in field and we don't see the error (incorrect I think) https://codesandbox.io/s/recursing-dawn-jls8i

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

16.8

### PR DESCRIPTION
**Pull request by bl00mber**
resolve #16342

### CODE REVIEW

**Comment by gaearon** [comment]
What is the concrete problem this is solving? I get that it's inconsistent but I'm trying to remember why we have a warning in the first place.

**Comment by bl00mber** [comment]
To prevent more type errors on the user side? Because controlled can only use strings as value, while uncontrolled can use undefined.

**Comment by Kirill486** [comment]
Arn't they ( ```<input>``` and ```<textarea>``` ) **inherit the same thing**?
Is there a chance that we can achieve the same by moving logic to the ancestor?

**Comment by bl00mber** [comment]
@Kirill486 that's the good point. @gaearon what do you thing about that? Should warning logic be placed to the parent to also handle `<select />` case?

**Comment by Kirill486** [comment]
@bl00mber , we may able manage to answer this question ourselves. The answer seem obvious for me)

**Comment by bl00mber** [comment]
@Kirill486 it doesn't seem _obvious_ to me, because I do not know if this PR is needed in the first place. There are PRs which are not reviewed for years or not reviewed at all so I want to make sure that this PR may have some chance to be reviewed in the future and that's the main purpose of my question.

**Pull request closed without merging**
