### PR TITLE
Use `onInput` instead of `onChange`

### PR DESCRIPTION
**Pull request by mathiasbynens**
See https://mathiasbynens.be/demo/input.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
I haven’t updated the CodePens that are linked, but would be happy to do so.

**Comment by vramana** [comment]
@mathiasbynens Not related to the PR but why is onInput faster? Any resources?

**Comment by sebmarkbage** [comment]
React's `onChange` doesn't work like the normal DOM `onchange`. It works more like `oninput` but also covers more cases.

Personally I think we should've gone with a different name to avoid confusion. The argument used in the early days of React went something like this:

1) Tracking all possible changes is very important in React because of the controlled component model. If you don't track every change, then React resets the value.

2) Newcomers to the platform intuitively think that `onChange` triggers for every change (for text fields, check boxes, select boxes etc.) and go for that first.

3) Therefore, we should "fix" this event rather than force people to use another one.

In hindsight I probably would've added a new event name and then triggered a warning/error if someone tried to use the "broken" `onChange` event. Feel free to open up an RFC issue for further discussion if you think that is worth it.

**Comment by mathiasbynens** [comment]
@vramana See https://mathiasbynens.be/demo/input.

@sebmarkbage Thanks for clarifying!

**Pull request closed without merging**
