### PR TITLE
fix crash when iterator returns a Proxy 

### PR DESCRIPTION
**Pull request by ivanhofer**
Fix for the issue described here: https://github.com/facebook/react/issues/21654#issuecomment-923648286

### CODE REVIEW

**Comment by SnO2WMaN** [comment]
@ivanhofer

 You may forgot to run prettier, please `yarn run prettier` .

**Comment by ivanhofer** [comment]
Thanks @SnO2WMaN!

@react-maintainer: you should probably rename the CI process to make it clear it runs prettier + eslint.
(and no, I don't want to create a circleci account just to see what went wrong)

**Review by bvaughn — CHANGES_REQUESTED** [review]
The repro here still breaks:
https://github.com/facebook/react/issues/21654#issuecomment-923648286

Now it just breaks with a different error. Before it thre:
> Uncaught TypeError: r.split is not a function

Now it throws:
> Uncaught DOMException: Failed to execute 'postMessage' on 'Window': function () { [native code] } could not be cloned.

**Comment by ivanhofer** [comment]
@bvaughn I don't get that error. For me it's working.
Running React Developer Tools 4.18.0 on Edge 93.0.961.52 on Windows 10

**Comment by bvaughn** [comment]
> Edge 93.0.961.52 on Windows 10

That's interesting. I'm running Chrome 94.0.4606.61 on Mac OS 11.6.

**Comment by bvaughn** [comment]
Just tested on Edge 91.0.864.59 and 94.0.992.31 and it throws there too.

**Comment by bvaughn** [comment]
Left a comment on #21654.

Basically, I'm happy to help dig into why this is failing, but I'd like a smaller repro that doesn't include several other libraries that I'm unfamiliar with.

**Pull request closed without merging**
