### PR TITLE
Merge pull request #1 from facebook/master

### PR DESCRIPTION
**Pull request by remekoh**
*Before* submitting a pull request, please make sure the following is done...

1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`) - we've done our best to make sure these rules match our internal linting guidelines.
6. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

Update from Original - 08/15/2016

### CODE REVIEW

**Comment by gaearon** [comment]
Not clear what this PR is supposed to do: it's empty and has no description.

**Comment by remekoh** [comment]
I am keeping my forked repo up to date with facebook:master

**Comment by gaearon** [comment]
You don't need to send PRs to the original repo for this :wink:

**Comment by kevinzwhuang** [comment]
@remekoh Here's a good article on updating your forked repo - https://robots.thoughtbot.com/keeping-a-github-fork-updated

Running this should do the trick:
```
git checkout master
git remote add upstream https://github.com/facebook/react.git
git fetch upstream
git rebase upstream/master
```

**Comment by gaearon** [comment]
@kevinzwhuang Thank you so much for linking to the article! I was on mobile but should've waited with commenting and done that.

**Comment by kevinzwhuang** [comment]
No problem, glad to help! :smile:

**Comment by remekoh** [comment]
Thanks, guys! 

I appreciate the help!

Newbie here... :)

**Pull request closed without merging**
