### PR TITLE
Stylistic changes. The previous example was more contrived than a don…

### PR DESCRIPTION
**Pull request by williamle8300**
…key's ass

### CODE REVIEW

**Comment by zpao** [comment]
> A common type of React component is one that extends a basic HTML element in a simple way.

Your example doesn't demonstrate that - it's just passes everything along with no extension. I'm inclined to just keep what we have, even if it is more contrived than a donkey's ass.

**Comment by williamle8300** [comment]
@zpao Can give me some direction on this?

I see a spread operator, a weird unicode checkmark in curly brackets...? What's with all the visual noise? 

Even though I don't have an exact idea of what this section is for, I know the whole code snippet could be re-edited to bring out the point more.

**Comment by williamle8300** [comment]
Y'know... I'm sorry @zpao. My tone is way out of line. I apologize. I wish I hadn't been to quick to vent, and esp in a public forum like this. I guess _I'm_ the ass... meh. Please forgive me. I hope things that plebs like myself say don't deter you (too) much in the good fight to build react.

I'm trying to learn React. IMO the docs could be 10x better. Waaay better code snippets and organized like in curricular format. I don't understand why the official react docs are organized the way it is, and I think react could be losing a large number of devs because of it.

Anyway. Please forgive me. Hook a brother up with some direction.

**Comment by zpao** [comment]
No hard feelings 😀

You're right, the docs are not great and the examples don't always help. We know but we haven't had a chance to properly deal with it. For the most part our docs are pretty much how they were written 2.5 years ago and at that point the way we told our story was different. New docs and changes have come in piecemeal and often written by different people, not with a cohesive voice.

We've slowly been thinking about how we can rewrite the docs but it's not a small time investment and we've had some other things to do so it hasn't been high priority.

* * *

Now back to that particular example…

The point of it is that you're wrapping a DOM component with some more data. In this case what's happening is that instead of just passing the children straight through, you make the children a checkbox and then the provided children. That's the only modification happening here. Yes, it's contrived. It could be made less so with less unicode.

```js
<CheckLink href="github.com" id="baz">foo<CheckLink>
```

Gets rendered into the DOM as

```html
<a href="github.com" id="baz">√ foo</a>
```

Again, just prepending a "check mark" (which yes, isn't actually a check mark) to the content of an anchor.

Anything else is not super easy. Eg, if you wanted to add a className, you actually should make sure it gets combined with the existing one if it was provided and then the point of the example gets lost in the supporting code.

```js
render() {
  var {className, ...otherProps} = this.props
  className = [className, 'my-default-class'].join(' ');
  return <a className={className} {...props} />
}
```

Ok, but why did we join like that and not just `+ ' my-default-class'`? Also what's that other `...` syntax? It looks the same but it's different…

And then we're explaining all the things that are not the most important thing here, which is that you can pass along props with a small modification *in the simple case*.

Sorry to write so much, docs are a frustrating topic because we know they're bad but making them better is a big effort. Finding the right level of detail to explain things to a broad audience is tricky (we get a lot of requests across our projects for pure ES5 examples because they aren't writing *any* ES6, so assuming people are familiar with new syntax is not a given).

* * *

So could we take your example and do something to it to make it fit into the goal? yup. Would it be less contrived? maybe. You probably want a default class on it like I wrote up above. Or inline styles which is a similar exercise. To get the point of the text across you need to add *something*. Maybe an `alt` attribute would be fine? It would wipe out a provided `alt` attribute but people are bad at accessibility so meh. Hopefully the goal of this is clearer and that gives you the perspective to make this a better example 😀

**Comment by zpao** [comment]
Just going to leave as is for now unless you want to come back to it. We'll plan to make examples better in a docs overhaul in the future though.

**Pull request closed without merging**
