### PR TITLE
Allow anonymous functions for properties of components

### PR DESCRIPTION
**Pull request by cbclemmer**
I have completed my CLA for my github username and this is my first pull request for react.

## Summary
This pull request attempts to resolve issue #24791. The issue states that anonymous functions set to a property of a component name will throw an error with eslint. There are no errors when running the application in node, only when running eslint with the eslint plugin `eslint-plugin-react-hooks`. 
The error is supposed to check whether the 
To fix this I added a branch for the `isCoponentName` function in `src/RulesOfHooks.js` file to accommodate properties of components. It seemed like the function was only checking whether the node was an identifier and testing the name based off of this. This worked if you assigned an anonymous function to a variable first and then assigned it to a property of a class (outlined in the reply to the issue), but I think it should really be checking the name of the property of the component to see whether that is abiding by the rules that it needs to.

## How did you test this change?
Test added for package: eslint-plugin-react-hooks
This was the most reduced version of the error that occurred in the issue that I could replicate with a failing test that matched what was described in the issue.
```
App.View = () => {
    useHook();
}
```

### CODE REVIEW

**Review by eps1lon — COMMENTED** [review]
Do we have a test that `App.view = () => useHook()` is still considered invalid?

**Comment by Colton-Clemmer** [comment]
@eps1lon Why would it be invalid? Is it because of the return value?

**Comment by Colton-Clemmer** [comment]
@eps1lon I couldn't find one so I added the test to the "invalid" list

**Comment by cbclemmer** [comment]
@eps1lon This pr got stale. I've updated it from main today. Is it still relevant enough to merge it?

**Pull request closed without merging**
