### PR TITLE
Add numeric CSS property - stroke width

### PR DESCRIPTION
**Pull request by nmn**
Stroke Width is an SVG related property that is numeric and should not be appended with `px`.

### CODE REVIEW

**Comment by golenazfazli** [comment]
Note:report issuses

**Comment by nmn** [comment]
@golenazfazli Sorry, but I didn't notice this as an issue. I'm currently reading the React source and I just found this in code. So I obviously fixed it directly.

**Comment by zpao** [comment]
Ignore @golenazfazli, that appears to be a terrible bot.

**Comment by nmn** [comment]
@zpao I feel dumb!

**Comment by spicyj** [comment]
Thanks, this looks good. Will merge this after we branch for 0.13 final.

**Comment by nmn** [comment]
@spicyj thanks.

**Pull request merged**
