### PR TITLE
semicolon cleanup

### PR DESCRIPTION
**Pull request by Simek**
One unnecessary semicolon removed and few missing added.

### CODE REVIEW

**Comment by jimfb** [comment]
Looks legit, thanks!  How did you find all these?  Is there a lint rule we can enable?

**Comment by zpao** [comment]
Not for TypeScript (at least not the tooling we have, but probably with some basic TS tooling). And I think we're still excluding a few of the files in test/ from linting. We need to move a few things from there to a better place and then we can lint that properly too.

**Comment by Simek** [comment]
Maybe adding this (https://www.npmjs.com/package/grunt-tslint) grunt plugin as a task will help to find wrong semicolons and more. But in my case IntelliJ just mark marked them as warnings.

**Comment by bgw** [comment]
IMO, I think it's a bit excessive to start including linters for TypeScript, CoffeeScript, etc. It's a tiny proportion of our code.

**Comment by zpao** [comment]
@bgw agreed :)

**Pull request merged**
