### PR TITLE
Additional troubleshooting documentation

### PR DESCRIPTION
**Pull request by jrobison153**
I'm a new contributor to the react project, as such I ran into some headaches trying to install on my Win7x64 system. It took me a few hours of fiddling around based on information pulled from numerous sources to get it working. I've condensed what worked for me into a section of a more general Troubleshooting guild and linked it from the main README.md in the hopes that it will provide some relief to the next contributor. Ideally the community can expand on this guide.

### CODE REVIEW

**Comment by zpao** [comment]
Thanks for starting this. Let's actually make this a page in the wiki so that it's more easily editable without PRs. We can still have the link in the README.

**Comment by jrobison153** [comment]
Sounds good Zpao, I'll make the changes there.

Cheers, 

Justin J.

**Comment by jrobison153** [comment]
sorry, did not mean to close the pull request. I've added a new wiki page and updated the README.

**Comment by jrobison153** [comment]
zpao, I'm going to close this pull request and open a new one. I realized I created this from the wrong branch of my fork anyway. Stay tuned.

**Comment by jrobison153** [comment]
[New pull request](https://github.com/facebook/react/pull/3943)

**Pull request closed without merging**
