### PR TITLE
Convert select/option to not use wrappers

### PR DESCRIPTION
**Pull request by spicyj**

### CODE REVIEW

**Comment by spicyj** [comment]
@sebmarkbage Last ones!

**Comment by mridgway** [comment]
@spicyj What about https://github.com/facebook/react/blob/806ff23f03fa54f40e4ea34ab4e9e9f9170a213b/src/renderers/dom/shared/ReactDefaultInjection.js#L44?

**Comment by spicyj** [comment]
@mridgway Yup, going away soon. Will require a bunch more changes though.

**Comment by spicyj** [comment]
(@mridgway Done in #4139.)

**Pull request merged**
