### PR TITLE
Move setState callback to right after didUpdate

### PR DESCRIPTION
**Pull request by spicyj**
It's much easier to do it this way in Fiber and there shouldn't be much observable difference.

### CODE REVIEW

**Comment by acdlite** [comment]
Not sure how related this is, but there's also a bug in stack where `setState` callbacks enqueued inside `componentWillMount` aren't flushed properly: https://github.com/facebook/react/blob/master/src/renderers/shared/stack/reconciler/__tests__/ReactCompositeComponentState-test.js#L174-L207

Should that be dealt with separately?

**Comment by spicyj** [comment]
I'll fix that now but in a separate PR.

**Comment by acdlite** [comment]
LGTM but someone who knows stack should give final approval

**Comment by jimbolla** [comment]
Is there any chance this change makes it into a React 15.x release? This actually fixes an issue in the next version of react-redux? Would be great to have this sooner than React 16.

**Comment by gaearon** [comment]
Since it's a potentially  breaking change, it can only land in a major version.

**Pull request merged**
