### PR TITLE
Mobile friendly docs [WIP]

### PR DESCRIPTION
**Pull request by yangshun**
With reference to https://github.com/facebook/react/issues/5404, I have made the docs more friendly for mobile devices:

1. Nav bar is fixed and can be scrolled horizontally. Inspired from the mobile nav of [Framer's docs](framerjs.com/docs/)
2. Nav docs is hidden on mobile screens by default. Revealed by pressing a button.
3. Footer text is center-aligned.

You can try the mobile friendly version of the docs site: http://yangshun.im/react/docs/getting-started.html.

Note that this is still work in progress, wanted to get the opinions and suggestions of the team before I polish things up and test each page on various mobile devices. Suggestions and feedback are welcome!

screen shot 2015-11-20 at 9 25 46 am

### CODE REVIEW

**Comment by yaycmyk** [comment]
screen shot 2015-11-20 at 1 25 54 pm

No bueno. Need to add this to the media query:

```css
.nav-main::-webkit-scrollbar {
    display: none;
}
```

**Comment by yangshun** [comment]
Any updates on this? @jimfb @zpao . Although this is yet to be completed but I'd love to give feedback as I go along, or perhaps close this if it isn't necessary.

**Comment by jimfb** [comment]
@zpao usually handles the website stuff, passing to him.  cc @spicyj

**Comment by spicyj** [comment]
I don't like the scrolling header. The jest docs fit on one line I guess:

image

If we can't fit on one line I would prefer just breaking into two or three lines. I don't see the nav in your screenshot – how is it triggered?

**Comment by gaearon** [comment]
Ping @yangshun, would you like to update this in response to the comments above? Thanks!

**Comment by vjeux** [comment]
Closing this as there hasn't been any updates in 3 months. Feel free to comment on this one or recreate a pull request if this is something you'd like to continue.

**Pull request closed without merging**
