### PR TITLE
Don't flush interactive updates to uncontrolled components early

### PR DESCRIPTION
**Pull request by gaearon**
This is related to what @NE-SmallTown noticed in https://github.com/facebook/react/pull/13488#issuecomment-416805935.

In the first commit, I amend my test to check for more things. Specifically, it seems weird that `setState` inside an `onChange` handler in async mode was flushed synchronously upon exiting an event — even though there was just one event. So I assert that it shouldn’t do that.

The cause turns out related to this:

https://github.com/facebook/react/blob/1c0ba70b4b753178d1bb9d9d8e32b90c50ec7e2c/packages/events/ReactGenericBatching.js#L44-L51

We need to flush restore for controlled inputs at the end of the interactive event. But we currently do this regardless of whether an input is controlled or not:

https://github.com/facebook/react/blob/1c0ba70b4b753178d1bb9d9d8e32b90c50ec7e2c/packages/react-dom/src/events/ChangeEventPlugin.js#L59-L60

In the second commit, I change it so that we don't flush interactive updates early for cases where the inputs aren't controlled (or affect other controlled inputs).

I'm not very familiar with this code and not entirely sure this is right. For example, an input might flip from uncontrolled to controlled, and we kinda support that (with a warning)? Then I think this detection would fail.

Also not sure it's worth the added complexity in practice. If you think it's valuable I can add more test coverage.

### CODE REVIEW

**Comment by react-linter** [comment]
ReactDOM: size: :small_red_triangle:+0.1%, gzip: :small_red_triangle:+0.2%


  <details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 1c0ba70b4b753178d1bb9d9d8e32b90c50ec7e2c...96cbe4d06abb5c4765dac40e62f0daac2f7b0c15</p>


  
## react-dom
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-dom.development.js | +0.1% | +0.1% | 660.24 KB | 660.85 KB | 154.94 KB | 155.1 KB | UMD_DEV
**react-dom.production.min.js** | **:small_red_triangle:+0.1%** | **:small_red_triangle:+0.2%** | **95.36 KB** | **95.46 KB** | **31.18 KB** | **31.25 KB** | **UMD_PROD**
react-dom.development.js | +0.1% | +0.1% | 656.33 KB | 656.94 KB | 153.81 KB | 153.97 KB | NODE_DEV
**react-dom.production.min.js** | **:small_red_triangle:+0.1%** | **:small_red_triangle:+0.1%** | **95.3 KB** | **95.4 KB** | **30.91 KB** | **30.94 KB** | **NODE_PROD**
ReactDOM-dev.js | +0.1% | +0.1% | 663.69 KB | 664.32 KB | 151.92 KB | 152.08 KB | FB_WWW_DEV
**ReactDOM-prod.js** | **:small_red_triangle:+0.1%** | **:small_red_triangle:+0.1%** | **287.74 KB** | **287.99 KB** | **53.32 KB** | **53.35 KB** | **FB_WWW_PROD**
react-dom.profiling.min.js | +0.1% | +0.1% | 98.18 KB | 98.28 KB | 31.51 KB | 31.54 KB | NODE_PROFILING
ReactDOM-profiling.js | +0.1% | +0.1% | 293.15 KB | 293.39 KB | 54.64 KB | 54.68 KB | FB_WWW_PROFILING

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by sebmarkbage** [comment]
Doesn’t seem worth it to me.

Uncontrolled Components are non-idiomatic and not something we optimize for. Certainly don’t want to add more code for.

Interactive updates do not provide a lot of guarantees of batching regardless. If you want that you use scheduleWork.

We know we want to make a breaking change around this anyway in https://github.com/facebook/react/issues/9657 so we can fix it then rather than risk it now.

**Comment by sebmarkbage** [comment]
We still have to explain how to use scheduleWork in controlled components to avoid this. So it’s just simpler that it’s the same story for both.

**Comment by gaearon** [comment]
Fair.

**Pull request closed without merging**
