### PR TITLE
Fix [website] side nav sometimes shows incorrect 'current' highlight (#10888)

### PR DESCRIPTION
**Pull request by NicBonetto**
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run prettier`).
6. Make sure your code lints (`npm run lint`).
7. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
8. If you haven't already, complete the CLA.

### CODE REVIEW

**Comment by NicBonetto** [comment]
This pull request will change SyntheticEvent's path name from events to synthetic-events. I also changed the file name formerly www/.cache/docs-events-html.json to www/.cache/docs-synthetic-events-html.json and the values of 'path' and 'slug' to the new path name to my fork; however, I do not think I can push those changes. And if I can I do not know how to since the www/.cache directory does not show up on Github (only in my editor).

**Comment by gaearon** [comment]
This would change the URL pages refer to, no? I'd like us to just fix the highlighting bug rather than work around it by changing the page URL.

**Comment by NicBonetto** [comment]
Ok got it, I will look more into it.

**Comment by NicBonetto** [comment]
I am sorry, but I need some help. What exactly are the arguments (location and item) that are passed into the isItemActive function? The file path is in the gatsby branch following www/src/utils/isItemActive.js.

**Comment by NicBonetto** [comment]
I am sorry, but I need some help. Where exactly can I find the data that are passed as arguments to the isItemActive and findSectionForPath functions? The files that contain these functions can be found in the gatsby branch following www/src/utils/isItemActive.js and www/src/utils/findSectionForPath.js. It will help me streamline the debugging process if I can navigate through the directories quickly. Thank you!

**Comment by NicBonetto** [comment]
This commit changes the forEach loop in the findSectionForPath function, and breaks out of the loop when a match is found. This will show the correct highlight on the sidebar. However, if you click on References in the sidebar while Handling Events is open, SyntheticEvents will still be highlighted. If I am on the right direction, I will fix this bug in my next commit.

**Comment by bvaughn** [comment]
In this branch, both "Handling Events" and "Synthetic Event" get highlighted. (Go [here](https://deploy-preview-10951--reactjs.netlify.com/docs/handling-events.html) and click to expand the "Reference" section to verify.)

I think the approach taken in #10977 is probably better. Rather than checking if the path _includes_ the slug it verifies that the two are equal. (It also does this for the active item highlight.)

Since you were working on this first, I'm happy to land this one instead of that one but I believe we should mimic the approach taken there.

**Comment by NicBonetto** [comment]
Agreed, that solution works better. I will submit my code shortly.

**Comment by bvaughn** [comment]
One more request before we can merge- would you rebase your PR so that it can be merged into the `master` branch? The `gatsby` branch has been merged and is no longer the right target for this PR.

**Pull request closed without merging**
