### PR TITLE
fixed:webComponent can receive child elements

### PR DESCRIPTION
**Pull request by a707843858**
This the webComponent can  receive child elements ,and  webComponent can  rending inside.

### CODE REVIEW

**Comment by gaearon** [comment]
@josepharhar What's the canonical way to handle this? The approach in this PR seems unlikely — but I want to understand whether we do need something special. I kind of expected that the way it already works (`appendChild` etc like normal DOM) would be enough.

**Comment by josepharhar** [comment]
I've skimmed the patch and I don't fully understand what's going on...
Based on the test, it seems like this patch makes react call `setAttribute('children', ???)` with something on custom elements, right? What's the value and why is it needed for custom elements?

**Comment by gaearon** [comment]
I think the intention (I agree the patch doesn’t seem right) was to make it possible to add children to custom elements. But that’s already possible, right? That’s what I’m confirming.

**Comment by josepharhar** [comment]
I made a test page to try adding children from within the custom element itself and from react at the same time to see what would happen: https://codesandbox.io/s/trusting-yonath-3eo24?file=/src/index.js:365-369
It seems like the custom element can add children to itself and you can add children from React at the same time without problems.

**Pull request closed without merging**
