### PR TITLE
Remove react-tools

### PR DESCRIPTION
**Pull request by zpao**
ReactTools is deprecated so lets remove it.

### CODE REVIEW

**Comment by zpao** [comment]
Updated with the complete removal of react-tools. I left a couple of the other changes in-tact and then re-added jstransform and commoner to our devdeps (I hadn't done a fresh npm install to test last time…). We'll get rid of jstransform once we do #4130.

**Comment by zpao** [comment]
cc @amasad. If react-native isn't ready to consume react from npm, we could build a new package that is just `src/` (maybe call it react-provides-module or something similarly obtuse). I know there are some other pieces that we'll need for react-native before it's ready - @sebmarkbage is working on that.

**Comment by amasad** [comment]
We can't because of the overrides?

**Comment by zpao** [comment]
Yea, pretty much. But decoupling the overrides is not completely straightforward.

**Pull request merged**
