### PR TITLE
Fix to work fiber debugger with npm start

### PR DESCRIPTION
**Pull request by koba04**
I tried to work ReactFiber Debugger by the following way. But it doesn't work.

> Running
> 
> First, npm run build in React root repo folder.
> 
> Then npm install and npm start in this folder.
> 
> Open http://localhost:3000 in Chrome.

* https://github.com/facebook/react/tree/master/examples/fiber/debugger

This PR is to fix that.
To do that, is it ok to add `fiber.js` into `react-dom`?

In addition to that, I've fixed warnings about `keys`.

Thanks.

### CODE REVIEW

**Comment by gaearon** [comment]
Oh, I think it didn't work because I deleted React from package.json but not from Yarn lockfile. Could you try just removing React from lockfile? That should work too.

**Comment by koba04** [comment]
@gaearon Thanks! You are right. I missed `.env` and CRA is using `dotenv`. This issue is only `react-dom` is in `yarn.lock`.

**Comment by gaearon** [comment]
This looks good, thanks! To be clear, your approach would also work, I'm just not sure if `file:` is supported in all versions of Node or not.

**Comment by koba04** [comment]
Thanks!

> file: is supported in all versions of Node or not.

I'm using `file:` with npm v2 and v3, which is fine. But I'm not sure it works in all environments including Windows :)

**Comment by 15828881249** [comment]
嘻嘻

**Pull request merged**
