### PR TITLE
[Docs] Add accessibility to tabs in installation documentation

### PR DESCRIPTION
**Pull request by AlmeroSteyn**
For your consideration:

After seeing the mention of the awesome addition of tabs in the docs, I added some accessibility features so that all users will be able to use these tabs easily.

### CODE REVIEW

**Comment by AlmeroSteyn** [comment]
@gaearon Thank you for taking the time to review and you are quite correct.

Firstly I added the style to get the mouse pointer going. Was so busy testing it with keyboard only...

As for the tab control itself, neither a button nor a link is quite right in this case. The [ARIA specification for the tab control](https://www.w3.org/TR/2013/WD-wai-aria-practices-20130307/#tabpanel) specifies the expected interactions for this kind of control. They are actually operated with the arrow keys instead of space or enter. Only the selected tab should be in the focus flow of the page, with the tabindex rolling over as the user interacts with it.

Initially I was not sure just how far to go with the change as I respect the effort of those who have worked on this bit before me, but it's clear it creates more confusion than it solves. And using buttons here would create a kind of `toggle button` hybrid thing. Or you'd have to strip the role from the `li` and mess with the `button` itself or assistive tech will get confused.

So now I added the logic to make it navigable with arrow keys as expected, giving the following result in a screen reader. In this case I used NVDA in Firefox:
image

I have also added a text underline on focus (following the style of the tab like links on the home page) as the standard browser focus outline was getting lost around the tabs, which makes it nasty for sighted users who have to use a keyboard.

Please let me know what you think. If you like what you see and if this is a way you would like to go with accessibility in the React docs (both actual docs about a11y and making the docs themselves more accessible) I would be happy to help where I can.

**Comment by gaearon** [comment]
I think the text underline feels odd. It's okay on links because they get it both on focus and on hover, but it's odd to have an underline instead of an outline. I also *do* get the browser outline, but maybe it depends on the browser (mine is Chrome on OS X).

**Comment by AlmeroSteyn** [comment]
@gaearon Love love that you say that!

Okay, here is my button with focus set in Firefox on Windows:
image
and in Chrome on Windows:
image

In Chrome I can see the outline happening but the contrast is terrible. In Firefox I can see no change happening (aside from the underline I made).

In order to be visible to users with low vision or color blindness, there would need to be at least a significant colour contrast difference between the button itself and the focus outline or some sort of shape change. I opted for the underline (although I would be the first to argue to style only links as links)  but also considered making the button colour very dark on focus. 

The second option is usually extremely accessible but I know a lot of folks find it ugly. Is there a very dark blue in the docs style guide you'd be happy for me to use in this case? This could also become the hover colour for the tabs then.

**Comment by AlmeroSteyn** [comment]
I have removed the underline already and added a darker blue focus style to the selected tab for illustration.

**Comment by gaearon** [comment]
I changed the color to be less dark so that it doesn’t look as weird (compromise).
LGTM!

**Comment by gaearon** [comment]
Also thanks for caring. If you find more issues like this let us know.

**Comment by AlmeroSteyn** [comment]
It's a pleasure!!

However I see that on mobile it freaks out a bit as the tabs aren't wrapping well. Will fix it when I get home later today.

**Comment by gaearon** [comment]
Cool, thanks!

**Pull request merged**
