### PR TITLE
Fix event target for input change events.  Fixes #4288


### LINKED ISSUE #4288: [regression] e.target for onChange is ndefined in 0.14.0-beta1
I tried updating from `0.14.0-alpha3` to `0.14.0-beta1`.

Something has changed in between these releases that is making it so that `e.target` in onChange's synthetic event is undefined.

### PR DESCRIPTION
**Pull request by jimfb**
Fix event target for input change events.  Fixes #4288

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Will `beta2` be released after merging this?

**Comment by jimfb** [comment]
@chicoxyzzy Not sure, I'd really like to get the reconciler fix too before beta 2, but we'll see.

@zpao CR?  This should be ready to go.

**Comment by jimfb** [comment]
Ping @zpao

**Comment by zpao** [comment]
Threading that argument through is pretty annoying :(. Any other cases you missed?

**Comment by zpao** [comment]
Note for blame hunters (eg me): this is a regression due to #4150.

**Comment by jimfb** [comment]
Hopefully not missing any others.  I did a skim of the uses of nativeEvent, all of them looked reasonable (already have nativeEventTarget or don't need it in that situation).

**Comment by vslinko** [comment]
@zpao do you have plans for `beta2`?

**Comment by zpao** [comment]
Ship it at some point

**Comment by richardaday** [comment]
+1 on beta2

This bug seems common enough to block most apps immediately after installing to 0.14.0-beta1

**Comment by jimfb** [comment]
@vslinko @richardaday It's not an officially supported/stable solution, but https://www.npmjs.com/package/react-dom-future stays up-to-date and has these fixes merged.  Obviously don't use this in production, but it'll let you play with the latest and greatest features and then you can let us know when we broke things in trunk :).

**Comment by chicoxyzzy** [comment]
@jimfb thank you!

**Comment by vslinko** [comment]
@jimfb :metal:

**Comment by spicyj** [comment]
@jimfb We already have http://react.zpao.com/builds/master/latest/ which has the latest browser builds as well as the npm packages (.tgz). So you can run

```
npm install http://react.zpao.com/builds/master/latest/react-dom.tgz
```

or list that URL as the version spec in package.json. These are updated automatically by Travis.

**Comment by jimfb** [comment]
Ok, great, that works too!

**Comment by syranide** [comment]
Was this in beta2/3? I'm still seeing the same issue.

**Comment by spicyj** [comment]
Should have been…

**Comment by syranide** [comment]
Compiling with React(+DOM) 0.14.0-beta3 and `event.target === undefined` on IE9 in `onChange`.

**Comment by zpao** [comment]
Well, the change definitely made it out. But perhaps it wasn't a complete fix.

**Pull request merged**
