### PR TITLE
6049 add support for onCancel event

### PR DESCRIPTION
**Pull request by ludvigsen**
Adds support for the onCancel event described here: https://github.com/facebook/react/issues/6049

### CODE REVIEW

**Comment by cbrwizard** [comment]
This might not be needed at all, but I think that this change will benefit from tests. Like in [this file](https://github.com/facebook/react/blob/master/src/renderers/dom/client/eventPlugins/__tests__/ChangeEventPlugin-test.js).

**Comment by ludvigsen** [comment]
@cbrwizard I don't think jsdom supports the Dialog element, so testing this could prove an issue, at least through jsdom/jest.

**Comment by NoelBroda** [comment]
@ludvigsen ping

**Comment by devjunkORG** [comment]
@ludvigsen I took your code, rebased and fixed conflicts. I don't know if it helps but I'd at least like to give this issue a bit of visibility. 

https://github.com/devjunkORG/react/commit/1bca7a6752758e3531e43601b21d4e5ae3fbacc2

**Comment by ludvigsen** [comment]
@devjunkORG Thanks, I appreciate it. Did you check to see if stuff still works as well?

**Comment by ludvigsen** [comment]
@aweary Great! I'll try to resolve the conflicts.

**Comment by ludvigsen** [comment]
@aweary Resolved the conflicts also added onClose event for completeness

**Comment by aweary** [comment]
Thanks @ludvigsen! I verified locally that the events are being dispatched for `onClose` and `onCancel` with a `<dialog />` element. This LGTM, thanks again!

**Pull request merged**
