### PR TITLE
Add deprecation note for deprecated component APIs

### PR DESCRIPTION
**Pull request by zpao**
These are the APIs listed here: https://github.com/facebook/react/blob/master/src/modern/class/ReactComponent.js#L100-L105

### CODE REVIEW

**Comment by spicyj** [comment]
replaceProps too?

**Comment by zpao** [comment]
Hmm, we're missing that from the code… @sebmarkbage?

**Comment by sebmarkbage** [comment]
Nobody uses replaceProps. We should just deprecate it from composites right now.

**Comment by zpao** [comment]
First rule of shipping code: don't make changes an hour before shipping.

**Comment by sebmarkbage** [comment]
First rule of shipping code: Shit happens.

**Comment by zpao** [comment]
It's cool, I missed it in review :). I know you were thinking of actually deprecating. I just put the message in the plain JS case #3361.

**Pull request merged**
