### PR TITLE
Refactoring PooledClass

### PR DESCRIPTION
**Pull request by mixed**
I found duplicated code in `PooledClass`. I think that `Static Pooler` can merge several pooler method.

### CODE REVIEW

**Comment by Aweary** [comment]
@mixed thanks for the PR! Using `arguments` to implement a generic pooler was noted as possibility in the top level comment in `PooledClass`. I believe it may have some some negative performance implications, which is why it was avoided in the first place.

cc @spicyj @sebmarkbage

**Comment by gaearon** [comment]
I think that division was intentional. I’m not sure it makes any perf difference these days, but I think we won’t take changes to that code these days because it’s just not worth the work to test all the browsers for regressions. The work on “Fiber” (new reconciler) may not use `PooledClass` at all, so I wouldn’t personally touch it and risk breaking or slowing down something.

**Comment by gaearon** [comment]
Thanks for the PR though!

**Comment by mixed** [comment]
@Aweary @gaearon
Thank you for your explanation. :)

**Pull request closed without merging**
