### PR TITLE
chore: upgrade to Jest 26

### PR DESCRIPTION
**Pull request by SimenB**
## Summary

As mentioned in #18815, it's incoming. I mostly wanna test the new (opt-in) fake timers, but I thought to open a PR with just the bump as well. Includes #18815, so you can choose to just merge this one if you want.

Draft for now as 26 is still alpha.

## Test Plan

Green CI

### CODE REVIEW

**Comment by gaearon** [comment]
@SimenB We're running into a need for the latest jsdom, which would require us to get on Jest 26. Any chance you want to revive this PR? I'd be happy to assist with missing bits.

**Comment by rickhanlonii** [comment]
Could we patch Jest 25 with a new jsdom patch version or does it include more changes then just this?

**Comment by gaearon** [comment]
We're gonna go with a custom jsdom fork for the time being but this is a liability.

**Comment by eps1lon** [comment]
Can you override the default environment `jest` is using in this repo and use [`jest-environment-jsdom-sixteen`](https://www.npmjs.com/package/jest-environment-jsdom-sixteen) instead? That way you can split up the work required for jest 26 into two parts: fixing broken test due to jsdom 16 and fixing broken tests due to jest 26.

**Comment by SimenB** [comment]
`jest-environment-jsdom-sixteen` is for jest 25, so you can use that 👍

**Comment by rickhanlonii** [comment]
PR to use jest-environment-jsdom-sixteen [here](https://github.com/facebook/react/pull/19288), we can land that after JSDOM publishes the fix.

**Comment by SimenB** [comment]
#19920

**Pull request closed without merging**
