### PR TITLE
Update 03-interactivity-and-dynamic-uis.md

### PR DESCRIPTION
**Pull request by jmarceli**
Fix typo. Props CAN'T change over time (as I suppose).

### CODE REVIEW

**Comment by ericelliott** [comment]
Props **can** change over time. Typically, those changes are the reason the component re-renders.

**Comment by cody** [comment]
Seems the wording causes confusion. Just three weeks ago there was #3944.

**Comment by jmarceli** [comment]
Thanks for clarification in #3944, I was confused by this sentence: `Try to use props as the source of truth where possible. One valid use to store props in state is to be able to know its previous values, because props can change over time.` I think it might be confusing for other beginners as well.

**Comment by zpao** [comment]
@ericelliott & @cody are right that it is correct as written but if it's confusingly worded, let's change it. Maybe this is clearer:

> … because props may change as a component is re-rendered.

**Comment by ericelliott** [comment]
:clap:

**Comment by zpao** [comment]
No response from author so closing out and will just change myself.

**Pull request closed without merging**
