### PR TITLE
Add unstable_concurrentUpdatesByDefault

### PR DESCRIPTION
**Pull request by rickhanlonii**
## Overview

Adds a flag to opt-into time-slicing by default per root.

### CODE REVIEW

**Comment by dai-shi** [comment]
(Let me leave a minor note here as I have been curious about the wording. Do they all mean the same thing? `concurrent updates` `concurrent rendering` `time slicing` `concurrent mode`. Hope the future documentation clarifies it.)

**Comment by sebmarkbage** [comment]
What is this for? Can we feature flag it if it's internal only?

**Comment by rickhanlonii** [comment]
@sebmarkbage internally some roots will be sync by default and others will opt-in to time-slicing.

**Comment by rickhanlonii** [comment]
@dai-shi good question:

- **concurrent updates**: Updates that are rendered concurrently. For example, updates wrapped in `startTransition`.
- **concurrent rendering**: Renders that happen concurrently. These will render with time-slicing, potentially at the same time as other renders.
- **time slicing**: Rendering that yields to other work, like the browser or other rendering tasks. See [here for more info](https://reactjs.org/blog/2018/03/01/sneak-peek-beyond-react-16.html).
- **concurrent mode**: This isn't well defined any more because there's not a single mode that turns on concurrent rendering everywhere, but different features that opt-into concurrent rendering in certain situations.

**Review by acdlite — APPROVED** [review]
Nit: Could wrap the root option in the flag to save a ridiculously small number of bytes and perhaps alleviate Seb's concern that it will leak to open source

**Pull request merged**
