### PR TITLE
Unitless css props

### PR DESCRIPTION
**Pull request by andrewdavey**
For #836

### CODE REVIEW

**Comment by Kureev** [comment]
For me lineHeight still doesn't work without 'px'. I'm using 0.13.0-beta.1, what's wrong?

**Comment by syranide** [comment]
`lineHeight` supports unit-less values so you need to provide `px` yourself.

**Comment by appsforartists** [comment]
At first blush, I like @vjeux's proposal from the previous issue (`lineHeight` is assumed to be in pixels unless passed as a string).  It feels more consistent with the other values (like `fontSize`).

```
"lineHeight":  48  // 48px
"lineHeight": "48" // 48 lines
```

**Comment by Kureev** [comment]
@appsforartists +1

**Comment by syranide** [comment]
@appsforartists `<Comp fontSize="13" />` vs `<Comp fontSize={13} />` though. Personally I think the auto suffixing is nice, but it's kind of arbitrary and makes things less obvious with unit-less styles (but which support `px`). It seems to me that just dropping it from core is the right way to go.

**Comment by appsforartists** [comment]
What's `Comp`?  I thought we were discussing CSS.

**Comment by zpao** [comment]
I think he meant if `Comp` has a render that does `style={{fontSize: this.props.fontSize}}`. Then it matters how you write `<Comp fontSize=... />`, or `Comp` has to handle different types and do what it intends.

**Comment by appsforartists** [comment]
Fair point.

So long as React Native is moving forward with the presumption that CSS values should be Numbers (with pixels as the assumed unit), we have an edge case (handling potentially unitless values).  The question is, which side of the edge should be sharp?

[TextStylePropTypes](https://github.com/facebook/react-native/blob/c88a1cd9b82a9421b83af2a53cf9e1d7bc848e45/Libraries/Components/Text/TextStylePropTypes.js) declares `lineHeight` to be a number, and a quick test in the Movies demo shows that it's being interpreted as a pixel value.

Is there a list of properties that aren't being treated as pixels because they might be unitless?  The only one I've encountered so far is `lineHeight`.  

If that's the only one, I think the sane thing to do is to force people to pass Strings if they want the unitless value and Numbers if they want pixels.  Still not ideal, but at least it's consistent (Numbers are _always_ pixels), and the fail case is obvious (if your double-spaced paragraph is only 2 pixels tall, you'll know right away that the number is being treated as pixels).

**Comment by zpao** [comment]
> Is there a list of properties that aren't being treated as pixels because they might be unitless? The only one I've encountered so far is `lineHeight`.

I can't speak for react-native but there is a non-trivial list when you have to support all of CSS: https://github.com/facebook/react/blob/master/src/browser/ui/dom/CSSProperty.js#L14-L37

**Comment by appsforartists** [comment]
@zpao Skimming that list, it seems like the intersection of things that could be pixels and things that could be unitless has exactly one member: `lineHeight`.

**Comment by zpao** [comment]
Oh I guess I misunderstood. Yea, I think you're right.

**Comment by appsforartists** [comment]
So if the only property affected is `lineHeight`, how do you feel about @vjeux's idea to cast Numbers (but not Strings) to pixels?  This would make it consistent with the other numerical font properties (e.g. `fontSize`).

**Comment by korbin** [comment]
:+1: on the lineHeight-is-in-pixels assumption.

**Comment by pke** [comment]
The `lineHeight` discrepancy hit me yesterday. I was under the assumption that all css properties that are not strings are treated as pixels. Why `lineHeight` should be the exception is not clear to me and I agree with @appsforartists that numbers should always be pixels. If one really want to set `lineHeight` to unit-less (lines) then one can use a String.

**Comment by spicyj** [comment]
All CSS properties that take only lengths are automatically pixels. lineHeight can take a length or a ratio so it is treated differently. I agree this can be confusing but don't know of a better alternative.

**Comment by appsforartists** [comment]
@spicyj I think I pretty clearly proposed a better alternative in this thread. 😀

**Comment by spicyj** [comment]
@appsforartists I guess you did propose an alternative. :) Isn't the current failure case equally prominent?

**Comment by appsforartists** [comment]
My hunch is that more people are passing Numbers and expecting pixels than there would be passing Numbers and expecting em multiples.  Like I said last year, there's a nasty edge case here, but at least we can pick which edge is sharp.

**Comment by vjeux** [comment]
Adding px to all the numbers has the nice side effect of eliminating the whitelist but it introduces other unexpected behavior like {flex: 1} which is not going to be valid anymore but heavily used in React Native.

**Pull request merged**
