### PR TITLE
feat: support Micro-Frontend mode and Module Federation modules

### PR DESCRIPTION
**Pull request by nyqykk**
## Summary

Background:
Micro Frontend framework like garfish、qiankun and Module Federation are also need fast refresh.

Loading Progress:
Micro Frontend: 
Main App Fast Refresh -> Main App ReactDOM -> Sub App Fast Refresh -> Sub App ReactDOM.
This order has no trouble when perform refresh, but if Sub App external React and ReactDOM and using Main App's, it will Invalid to perform refresh, because Sub App ReactDOM will not init after Sub App Fast Refresh Runtime.

Module Federation:
Host App(like Main App) Fast Refresh -> Host App ReactDOM -> Sub App Fast Refresh -> Reuse Main App's ReactDOM(inited yet)
Since MF has shared to reuse loaded packages, ReactDOM is possible to reuse the inited package, so refresh is also invalid.

So we need to keep the **injected** into memory. This can make sure the Sub App can put the **injected** into its React Refresh Runtime

### CODE REVIEW

**Comment by Prasadlohakare25** [comment]
please assign me this problem

**Comment by eps1lon** [comment]
Thank you for reporting this bug and working on a fix. Could you include a minimal repro that showcases the bug and confirms your change fixes it?

**Comment by nyqykk** [comment]
https://github.com/nyqykk/react-refresh-example

I am sorry for module federation example. I just use a Micro-Frontend Framework to add an example instead. Because the problem will just exist in the newest MF version(we are making an huge upgrade with the author of MF, after we finish it and publish, this problem will show. If you think it is so early to fix it, after we publish the new version, i will come back here again)

In this example, the Sub App will external React and ReactDOM to use the Host App's React and ReactDOM.

The Reason why refresh can not work:
Host App(like Main App) Fast Refresh -> Host App ReactDOM -> Sub App Fast Refresh -> Reuse Main App's ReactDOM(inited yet)
Sub App's Fast Refresh do not init by ReactDOM

**Comment by nyqykk** [comment]
> Thank you for reporting this bug and working on a fix. Could you include a minimal repro that showcases the bug and confirms your change fixes it?

https://github.com/nyqykk/react-refresh-example

I am sorry for module federation example. I just use a Micro-Frontend Framework to add an example instead. Because the problem will just exist in the newest MF version(we are making an huge upgrade with the author of MF, after we finish it and publish, this problem will show. If you think it is so early to fix it, after we publish the new version, i will come back here again)

In this example, the Sub App will external React and ReactDOM to use the Host App's React and ReactDOM.

The Reason why refresh can not work:
Host App(like Main App) Fast Refresh -> Host App ReactDOM -> Sub App Fast Refresh -> Reuse Main App's ReactDOM(inited yet)
Sub App's Fast Refresh do not init by ReactDOM

**Comment by nyqykk** [comment]
> Thank you for reporting this bug and working on a fix. Could you include a minimal repro that showcases the bug and confirms your change fixes it?

And React Devtools also keep the renderer in it's inject hook.
https://github.com/facebook/react/blob/67cc9ba8789335b9da0838a446137c1be62adbcd/packages/react-devtools-shared/src/hook.js#L325

**Pull request closed without merging**
