### PR TITLE
Use .slice() for all substring-ing

### PR DESCRIPTION
**Pull request by sophiebits**
- substr is Annex B
- substring silently flips its arguments if they're in the "wrong order", which is confusing
- slice is better than sliced bread (no pun intended) and also it works the same way on Arrays so there's less to remember

---

> I'd be down to just lint and enforce a single form just for the potential compression savings by using a repeated string.

_Originally posted by @sebmarkbage in https://github.com/facebook/react/pull/26663#discussion_r1170455401_

### CODE REVIEW

**Comment by sophiebits** [comment]
I at least skimmed all the changes. They're _probably_ right.

**Comment by sebmarkbage** [comment]
Yaas. Look at that gzip win!

**Review by sebmarkbage — APPROVED** [review]

**Comment by sophiebits** [comment]
10 bytes saved! 🔥

**Comment by sophiebits** [comment]
Actually, saving 4 bytes on gzip -9 is pretty good considering it's just one callsite in that bundle.

**Pull request merged**
