### PR TITLE
[docs] Italian localization of documentation

### PR DESCRIPTION
**Pull request by claudiopro**
This is a voluntary effort to translate the React docs to Italian. I see there are a Chinese, Japanese, and Korean translation so I assume it is legit to contribute an additional translation :smile: 

Please note this is a work in progress, I'll remove the `[In Progress]` marker when done. I'll ask questions mentioning committers if needed.

### CODE REVIEW

**Comment by jimfb** [comment]
Yep, completely legit!  Sounds great!  Let us know when you're ready to merge.  We'll ask that you squash your commits into a single commit before we merge.

**Comment by claudiopro** [comment]
@jimfb okiedokie, that's fair. Thanks!

**Comment by claudiopro** [comment]
@jimfb hi, how can I try out the translation? Does the regular build produce static HTML pages?

**Comment by dmatteo** [comment]
@claudiopro I can help, if you need. Just ping me

**Comment by jimfb** [comment]
@claudiopro Start a local jekyll server as per the readme, then the translated docs follow a pattern like http://facebook.github.io/react/docs/getting-started-ja-JP.html

**Comment by claudiopro** [comment]
Oh, I found the instructions in `docs/README.md`:

```sh
$ cd react/docs
$ bundle install # Might need sudo.
$ npm install
```

@dmatteo thanks, I'll ping you if I'm stuck!

**Comment by jimfb** [comment]
Yeah, you'll also need

```sh
$ cd react/docs
$ bundle exec rake
$ bundle exec jekyll serve -w
$ open http://localhost:4000/react/
```
etc

**Comment by claudiopro** [comment]
@jimfb awesome, thanks!

**Comment by claudiopro** [comment]
@jimfb @dmatteo how would you request translated docs? Are they served based on request locale, or should they be requested directly? e.g. `http://localhost:4000/react/docs/getting-started-ja-JP.html`

**Comment by jimfb** [comment]
Right now I think they're requested directly.  I think @zpao was looking into serving based on locale, but I don't think that's ready, though he might tell me I'm wrong :).

**Comment by claudiopro** [comment]
LOL ok, I'll finalize my squashed commit so :o)

**Comment by iamchenxin** [comment]
@claudiopro  To show your locale version nav for test, you should modify the jekyll's yml (docs/_data/nav_docs.html) to your locale version . Maybe there is a automatic generate command , but i dont kown.

**Comment by claudiopro** [comment]
@zpao @jimfb all set, translation completed and commits squashed into one. Please review.

**Comment by zpao** [comment]
This is awesome. Could you rebase on top of master here so that there's only the docs commit? Looks like there are a couple stray commits showing up right now.

**Comment by claudiopro** [comment]
@zpao sorry about that, I had rebased to squash but didn't reset the HEAD. Now it's reset to 208f20b.

**Comment by zpao** [comment]
Thanks! We'll probably be making some changes in the next few days as we fix up some documentation for 0.14. We may ping you to see if you're interested in updating this translation as well :)

**Comment by claudiopro** [comment]
@zpao sure, send my way!

**Pull request merged**
