### PR TITLE
Started setting both props.class and props.className for DOM elements

### PR DESCRIPTION
**Pull request by jimfb**
Mostly for shits and giggles, but I was curious to see how often this would fire on my devserver (ie. curious if it actually creates a migration burden, because code wins arguments).

Fixes https://github.com/facebook/react/issues/5926, FWIW.  This would need lots more discussion before we could actually consider merging such a thing.

### CODE REVIEW

**Comment by yaycmyk** [comment]
Is there a plan to support `for` vs `htmlFor` as well?

**Comment by jimfb** [comment]
If we were to change `className`->`class`, we would also change `htmlFor`->`for`.  But any such change is clearly in the 'exploration' stage rather than the 'implementation' stage.

**Comment by mikeybox** [comment]
@jimfb has this been reviewed and is it likely to be included in a v15 minor release?
thanks.

**Comment by jimfb** [comment]
@mikeybox No, there is a long road and many discussions between here and there.

**Comment by mikeybox** [comment]
@jimfb thanks for the update

**Comment by gaearon** [comment]
I’ll close because this doesn’t merge cleanly and we don’t seem to want to do this in the short term. We might want to reopen some day but I’d expect we’d have a more solid plan around this by that time.

**Pull request closed without merging**
