### PR TITLE
Refactored Installation page to no longer use tabs

### LINKED ISSUE #11043: Active Tab is not included in current route or permalinks on new docs site
**Do you want to request a *feature* or report a *bug*?**
bug on new docs site

**What is the current behavior?**
on the new docs site active tab is not included in current route or permalinks so when attempting to send someone here https://reactjs.org/docs/installation.html#using-a-cdn they are instead dropped here https://reactjs.org/docs/installation.html because the correct tab is not active

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
- go here https://reactjs.org/docs/installation.html
- click "add react to existing app" tab
- grab any permalink from within this section, (ex. https://reactjs.org/docs/installation.html#enabling-es6-and-jsx)
- open that permalink from within an incognito window

**What is the expected behavior?**
should be taken to the correct linked section within the docs

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
this is not an issue with react itself, just the new docs site

### PR DESCRIPTION
**Pull request by bvaughn**
Resolves #11043

The installation page previously used a one-off tab mechanism to visual limit the content shown on the screen. Unfortunately this mechanism did not work correctly in production on the new website, causing some links to show the incorrect content.

Ultimately this PR resolves the issue by removing all of the embedded HTML+CSS in the `installation.md` file in favor of standard markdown syntax. I believe this is the best short-term solution and that we can revisit the UI/UX of this page in the future to improve it (cc @joecritch).

screen shot 2017-10-02 at 3 17 48 pm

The anchor tags should now work correctly, eg https://deploy-preview-11050--reactjs.netlify.com//docs/installation.html#using-a-cdn

For posterity, I also considered the following alternative approaches.

---

### Pros:
* Keeps the document uncluttered by limiting the presented info (in a manner similar to the tabs)
### Cons:
* Not obvious what the next/prev links should be on the Installation page or any of the sub-pages
* Could not redirect from any existing external links to eg `/docs/installation.html#using-a-cdn` 

screen shot 2017-10-02 at 3 08 12 pm

---

## Keeping content in a single page but with side-nav headers
screen shot 2017-10-02 at 3 15 14 pm

### Pros:
* Nice high-level overview of the sections, similar to tab mechanism
### Cons:
* Complicated the sidenav logic for Docs by mixing in behavior currently only used in the Tutorial section (eg anchor-syncing as you click or scroll around)
* Hopefully we'll get this sort of behavior for free by way of a higher-level proposal like #10980

### CODE REVIEW

**Comment by gaearon** [comment]
Can we maybe add a note to Babel section that once again mentions you don't need to configure anything if you use CRA? For some reason people just skip ahead there and get lost :-(

**Comment by bvaughn** [comment]
Sounds like you have a somewhat specific idea of what you want to be added where, and I don't. Mind posting a follow-up a PR that does this? I'd be happy to review it.

**Comment by gaearon** [comment]
I don't really have a solution to that problem. (Well, tabs were a solution but they introduced other problems.)

I just know that people don't read titles on one page, skip ahead, and then don't realise they've missed the section they needed.

I've seen countless reports from people who tried CRA and then for some reason continued reading down and attempted to install webpack and Babel on top of it. They didn't believe CRA just works out of the box. They saw "Enabling JSX and ES6" and thought they need to do it even if it's in a completely separate section.

**Comment by bvaughn** [comment]
I'd be happy to spend some time going over the docs with a fresh set of eyes, maybe trying to tackle some problems like this, if Sophie thinks it's worth the time spent. Will add it to the discussion notes for today's sync.

**Comment by sophiebits** [comment]
Maybe it makes sense to just split these into three separate pages?

**Comment by bvaughn** [comment]
@sophiebits Like I described in the PR description, "Breaking the sub-sections into their own pages" ? Or something else...

**Comment by sophiebits** [comment]
Yes, that. 😳

**Comment by bvaughn** [comment]
Yeah, i'm not opposed to doing that. I mostly held off because I didn't know how many existing links it might break. (We can clearly search within the site and fix any internal ones, but I've been finding out there are a lot of external links to the site.)

**Comment by sophiebits** [comment]
JS redirect?

**Comment by bvaughn** [comment]
Yeah I guess we _could_ do that but it seems...shitty. We would have to replace the `installation.md` markdown+template with a new `installation.html.js` page so we could do the redirect _and_ we'd need to remember to keep that redirect in-sync any time we made structural changes to either of the newly-added markdown files (which seems a tad bit fragile).

**Comment by sophiebits** [comment]
> we'd need to remember to keep that redirect in-sync any time we made structural changes to either of the newly-added markdown files

Would this be different from any other time we move files around? Seems like if A redirects to B then we move B to a new page C, we need to add redirects from B to C regardless, and the chain A -> B -> C would work. Sorry if I'm misunderstanding something.

**Comment by bvaughn** [comment]
> Would this be different from any other time we move files around?

Yes, in that it would be unexpected. As someone modifying markdown content in a `*.md` file, I wouldn't expect to know that I should also go hunt down some JavaScript redirect in a different part of the website repo to keep its `#anchortaglikethis` in sync with my `# Markdown Title Like This`.

**Pull request merged**
