### PR TITLE
Add documentation for shallow testing

### PR DESCRIPTION
**Pull request by graue**
See #2393 for the original issue, and #2497 for the implementation.

### CODE REVIEW

**Comment by jsfb** [comment]
Are we using this internally yet?  We might want to hold off on merging this documentation until we've started using this and validated that the API makes sense and is production-ready.

**Comment by graue** [comment]
I had similar concerns, especially since it doesn't support refs (or context?). @sebmarkbage points out it's a better testing story than anything we have currently, though.

**Comment by zpao** [comment]
I think we should probably start talking about it and getting people to use it. We're a slower moving ship so it's harder to steer but getting feedback from people who can move a bit faster would be worthwhile and will perhaps get us to the best shape possible.

We should probably enumerate any limitations though (and perhaps label it as "beta" or something just so people have an idea of what they're getting into)

**Comment by jareware** [comment]
This looks very useful! I'm curious as to why you'd want to limit this to [one level](https://github.com/graue/react/blob/76f5453cc7551d0daa9a5a2f63b6ec06778a9383/docs/docs/10.4-test-utils.md#shallow-rendering) of components, though..? Seems to me you'd be dealing with the same limitations (e.g. ref's missing) regardless of depth, and being able to test the whole composition of the UI could be valuable.

**Comment by graue** [comment]
@jareware: the motivation is to be able to test just one thing at a time (i.e., unit testing). Say Foo's render method returns `<div class="foo"><Bar /></div>`. It's useful to test in isolation without worrying about how Bar behaves. You couldn't do this before. If, however, you want to do more of an integration test, you've always been able to render all the way down and assert properties of the DOM.

**Comment by jareware** [comment]
@graue, the value in testing one-level-deep is not lost on me, and I think I see the possible misunderstanding now. So am I correct in assuming whereas previously we've been able to either render a complete component hierarchy using DOM emulation (e.g. `jsdom`) OR rendering directly as a string, this PR would introduce a third method, where there's no need for DOM emulation (but limited to the depth of a single component)?

**Comment by sebmarkbage** [comment]
@jareware Correct.

**Comment by jareware** [comment]
Ok, now that that's cleared up, is there any reason why this *couldn't* be done for an entire component hierarchy instead of a single, "shallow" component? Anything like `this.getDOMNode()` would obviously be out of the question, but besides that.

**Comment by zpao** [comment]
@graue let me know if you have any updates you want to make before this gets merged. Otherwise I'm happy with it.

**Comment by graue** [comment]
:shipit:

**Comment by zpao** [comment]
Thanks :)

**Comment by graue** [comment]
Aww, this doesn't seem to have made it into the [changelog](https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html)...

**Comment by spicyj** [comment]
Oops, our mistake…

**Pull request merged**
