### PR TITLE
[Fiber] Separate priority field for pending updates

### PR DESCRIPTION
**Pull request by acdlite**
Currently there is a single priority field `pendingWorkPriority` that represents the priority of the entire subtree. The scheduler does a breadth-first search to find the next unit of work with a matching priority level. If a subtree's priority does not match, that entire subtree is skipped. That means when an update is scheduled deep in the tree (`setState`), its priority must be bubbled to the top of the tree. The problem is that this causes the all the parent priorities to be overridden — there's no way to schedule a high priority update inside a low priority tree without increasing the priority of the entire tree.

To address this, this PR introduces a separate priority field called `pendingUpdatePriority` (not 100% sold on the name). The new field represents the priority of the pending props and state, which may be lower than the priority of the entire tree. Now, when the scheduler is searching for work to perform, it only matches if the `pendingUpdatePriority` matches. It continues to use the `pendingWorkPriority` as a fast hint to skip subtrees if they do not match. (To elaborate further: because the work priority is the highest priority of any node in the entire tree, if it does not match, there's no point in searching any deeper.)

Based on https://github.com/facebook/react/pull/7344. Compare view: https://github.com/acdlite/react/compare/fibersetstate...fiberupdatepriority

@sebmarkbage

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Rebase: https://github.com/sebmarkbage/react/tree/fiberupdatepriority

**Comment by sebmarkbage** [comment]
You can also end up with `pendingProps` in progressed work in the work-in-progress tree I guess. Not sure how that affects the `setState` case.

**Comment by adig1245** [comment]
Bola de idiotas dejense de manadas y de envolver a la gente solo que avanzar mas uso de la red y ustedes tengan mas ganancias por uso global de red web

**Comment by gaearon** [comment]
I'll close since this is outdated. I also think it was covered by #8010?

**Comment by acdlite** [comment]
Yeah way outdated

**Comment by sebmarkbage** [comment]
It isn't not covered yet though. In fact the solution to this problem is blocking me from landing the demo properly. You can't really do as interesting scheduling examples without the separate priority field.

So we should fix something like it but by putting the field on the update queue.

**Comment by acdlite** [comment]
@sebmarkbage Is this tracked on the umbrella issue? I can pick this back up again, unless you'd rather do it

**Comment by sebmarkbage** [comment]
@acdlite It is not tracked but we probably should. It'd be great if you can pick it back up so we can get the demo with hover effects running smoothly!

**Pull request closed without merging**
