### PR TITLE
Add unit test: should generate simple markup for attribute with `>` symbol

### PR DESCRIPTION
**Pull request by jimfb**
Add unit test: should generate simple markup for attribute with `>` symbol

### CODE REVIEW

**Comment by zpao** [comment]
Not sure we need this test, it should already be covered by the other attribute tests (eg https://github.com/facebook/react/blob/master/src/renderers/dom/shared/__tests__/ReactDOMComponent-test.js#L703-L719)

**Comment by jimfb** [comment]
Eeh, this test verifies public API (the other test does not).  If a refactor/rewrite results in us doing markup generation differently, someone might generate markup without invoking `renderToStaticMarkup`, meaning the old unit test could pass but integration could be wrong.  Additional test shouldn't hurt anything, and it does add a little value, so might as well.

**Comment by zpao** [comment]
Alright

**Comment by spicyj** [comment]
I'm confused what other kind of markup we might generate here?

**Comment by spicyj** [comment]
I see, this is a followup to https://github.com/facebook/react/issues/4323.

**Pull request merged**
