### PR TITLE
Preserve DOM node when updating empty component

### LINKED ISSUE #2770: When returning null, <noscript /> tag is always rerendered
tl;dr: If you have a component that returns `null` and it rerenders, the noscript tag is unmounted and a new one is created because shouldUpdateReactComponent gets `<ReactEmptyComponentType />` and `null` and returns false.

---

This came out of some internal components that were breaking after the most recent update.

I haven't gone to see if this is more widely broken - it might have been before any of the recent updates, just that the empty component is triggering it reliably. I've been some reports of `` having similar weird problems that we couldn't track down. It's use of `LocalEventTrapMixin` is very similar to what's happening in `ReactEmptyComponentType`.

The trigger here is that we're triggering an update during the mount phase. When we do this `<Child key="0">` works correctly because it's before `<Child key="1">` which is triggering `Parent` to rerender. `<Child key="2">` is the broken one because its `componentDidMount` hasn't been called yet. So we actually call its `componentWillUnmount` first. Then we still call its `componentDidMount`.

There's also the whole question of *why* we're trying to unmount anything at all here. It seems like we shouldn't be doing that.

cc @sebmarkbage @spicyj

Drop this into examples/basic-jsx-harmony and debug with pausing on caught exceptions. I added some breakpoints in ReactEmptyComponent to make it super obvious.

```js
'use strict';

var Child = React.createClass({
  componentDidMount() {
    this.props.onMount && this.props.onMount();
  },
  render() {
    if (!this.props.visible) {
      return null;
    }

    return <div>hello world</div>;
  }
})


var Parent = React.createClass({
  update() {
    this.forceUpdate();
  },
  render() {
    return (
      <div>
        <Child key="0" visible={false} />
        <Child key="1" visible={true} onMount={this.update} />
        <Child key="2" visible={false} />
      </div>
    );
  }
})

React.render(
  <Parent/>,
  document.getElementById('container')
);
```

### PR DESCRIPTION
**Pull request by spicyj**
Fixes #2770.

Included: Refactor empty component handling; now doesn't use ReactCompositeComponent and `._currentElement` is actually null/false.

### CODE REVIEW

**Comment by spicyj** [comment]
Opinions on the circular dependency here for `instantiateReactComponent`→ `ReactEmptyComponent` → `instantiateReactComponent`? This has `instantiateReactComponent` pass a reference to itself when instantiating `ReactEmptyComponent`. (We have this problem in two other places already: in `ReactDOMComponent` we get around the dependency issue by injecting the cycle via `ReactNativeComponent`; in `ReactCompositeComponent` we export an incomplete class and `instantiateReactComponent` completes it with a reference to itself.)

**Comment by sebmarkbage** [comment]
Do we need to update anything in devtools?

**Comment by sebmarkbage** [comment]
WRT the cycles, I think we'll end up merging all cyclic code into ReactReconciler eventually but this is fine for now.

**Comment by spicyj** [comment]
Well this is what happened before in the devtools, apparently:

image

But yes. https://github.com/facebook/react-devtools/pull/199 does that.

**Comment by sebmarkbage** [comment]
Ok. Lgtm. Let's try it.

Side note: I always thought we allowed `true` to be empty as well. Isn't that what happens for `traverseAllChildren`?

**Comment by spicyj** [comment]
Yes, that is what happens for real children. We also allow undefined in that case, and empty string makes an empty text node which really could be nothing as well. I was thinking on my way home that maybe we should rescind our support for false and support only null… but maybe supporting everything is simpler, easier, and more consistent.

**Pull request merged**
