### PR TITLE
fix: checkbox with `preventDefault` on click should not trigger SyntheticEvent

### LINKED ISSUE #9023: event.preventDefault in click handler does not prevent onChange from being called
**Do you want to request a *feature* or report a *bug*?**

Bug!

**What is the current behavior?**

When rendering an `input` element of type `checkbox` with an `onClick` and `onChange` handler, `onChange` is still called even though `event.preventDefault()` is called in the `onClick` handler.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

http://jsfiddle.net/rf3w7apc/

**What is the expected behavior?**

Calling `event.preventDefault` in the `onClick` handler should prevent the default action  from occurring (or undo its effect), which is to update the value of the `input` element. This should stop any `change` event listener from being invoked. See https://jsfiddle.net/L1eskzsq/ for expected behavior

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Tested using a build from master, Chrome  56.0.2924.87 (64-bit)

### PR DESCRIPTION
**Pull request by zombieJ**
## Summary

React use SyntheticEvent to trigger change event on checkbox & radio by click event. But when called `preventDefault` on click event, it does not trigger native change event but will trigger on React. It's caused by the `checked` state will tmp set to opposite but reset when finished by browser:

https://html.spec.whatwg.org/multipage/input.html#the-input-element

Add check to ignore change event when prevent is marked

resolve #9023

## How did you test this change?

Update `ChangeEventPlugin-test.js` for preventDefault case. (Since this is prevent wrong event trigger, seems can do nothing for video record)

related issue:
* #9023
* https://github.com/mui-org/material-ui/issues/23709
* https://github.com/ant-design/ant-design/issues/32790

### CODE REVIEW

**Comment by zombieJ** [comment]
hi @rickhanlonii,
I'm not sure if I missing something. Could you help to confirm this PR?

Thanks~

**Comment by zombieJ** [comment]
Half month passed but nobody takes a look... : (

**Comment by eps1lon** [comment]
This doesn't seem to work in a Chrome Version 96.0.4664.45 (Official Build) (64-bit) when we call `event.preventDefault` in a React `onClick` handler: https://codesandbox.io/s/react-18-checkbox-click-preventdefault-change-quirk-4mwl8

**Comment by eps1lon** [comment]
Here is a test that still fails in this PR which is based on https://codesandbox.io/s/react-18-checkbox-click-preventdefault-change-quirk-4mwl8?file=/src/index.js. Notice that `handleNativeChange` is not called as expected but `handleReactChange` is. If we don't call `event.preventDefault` then both handlers are called as expected.

```jsx
it('should not fire change for checkbox input when preventDefault is called in onClick', () => {
  const handleReactChange = jest.fn();
  const handleNativeChange = jest.fn();

  const node = ReactDOM.render(
    <input
      type="checkbox"
      defaultChecked
      onClick={event => {
        event.preventDefault();
      }}
      onChange={handleReactChange}
    />,
    container,
  );
  node.addEventListener('change', handleNativeChange);

  node.click();

  expect(handleNativeChange).toHaveBeenCalledTimes(0);
  expect(handleReactChange).toHaveBeenCalledTimes(0);
});
```

**Comment by zombieJ** [comment]
@eps1lon,
Thx for your feedback. Let me check out~

**Comment by zombieJ** [comment]
Hmmm...
`dispatchQueue` seems push the `change` event before real `onClick` call. It makes additional `change` event trigger.

**Comment by zombieJ** [comment]
@eps1lon,
Fixed. Please check: https://codesandbox.io/s/react-18-checkbox-click-preventdefault-change-quirk-forked-ptol7?file=/src/index.js

**Comment by eps1lon** [comment]
> @eps1lon, Fixed. Please check: [codesandbox.io/s/react-18-checkbox-click-preventdefault-change-quirk-forked-ptol7?file=/src/index.js](https://codesandbox.io/s/react-18-checkbox-click-preventdefault-change-quirk-forked-ptol7?file=/src/index.js)

Fixed in Chrome 96 👍🏻 For safe measure, could you check various other browsers as well (e.g. Safari and IE 11 are notorous for inconsistent behavior).

**Comment by zombieJ** [comment]
Update:
Tested in Chrome, Firefox, Safari worked as expect.

Since CodeSandbox do not support IE11, I need additional work for test it.

**Comment by zombieJ** [comment]
@eps1lon, 
I've tested follow browser with latest version. All work as expect:
* Chrome
* Safari
* IE11
* Firefox

**Comment by zombieJ** [comment]
@eps1lon, wait your feed back : )

**Comment by zombieJ** [comment]
@eps1lon , anything more I can do? : )

**Comment by zombieJ** [comment]
@sebmarkbage could you pls help to take a look?

**Comment by zombieJ** [comment]
Anyone can help on this?

**Comment by zombieJ** [comment]
@eps1lon, could you help to take a look?~ Thanks

**Comment by zombieJ** [comment]
@bvaughn, could you help to merge this? thx

**Comment by n0099** [comment]
LGTM

**Comment by zombieJ** [comment]
Hi @bvaughn, is any chance that this PR will be merged or something else that I can help?~

**Comment by zombieJ** [comment]
Hi @bvaughn, is there any chance to merge this PR?

**Comment by zombieJ** [comment]
@sebmarkbage, could you help to take a look?

**Comment by zombieJ** [comment]
@Huxpro Could you help to find someone can handle this? thx

**Comment by n0099** [comment]
@gnoff plz take a look on this

**Comment by zombieJ** [comment]
hi @kassens,
Could you help to check this? This PR has been wait for over one year : )

**Comment by zombieJ** [comment]
@eps1lon, safe to merge? : )

**Comment by zombieJ** [comment]
Why PR is such hard. I don't want to disturb but none care about this  : (

@eps1lon  @gnoff @kassens  @alunyov  @sebmarkbage  @gaearon  @poteto

**Comment by zombieJ** [comment]
@eps1lon @gnoff @kassens @alunyov @sebmarkbage @gaearon @poteto

**Pull request closed without merging**
