### PR TITLE
Double-render function components with Hooks in DEV in StrictMode

### PR DESCRIPTION
**Pull request by gaearon**
Alternative to https://github.com/facebook/react/pull/14639. (See last commit.)

Less risky. Would make DEV faster for the stateless case. It's mostly Hooks abuse that we're worried about anyway. Added a test for `useMemo(fn, [])` specifically.

### CODE REVIEW

**Comment by gaearon** [comment]
I'll merge to unblock the sybnc.

**Comment by bvaughn** [comment]
Nice compromise, Dan

**Comment by gaearon** [comment]
I already reverted

**Comment by gaearon** [comment]
(Resubmitted in https://github.com/facebook/react/pull/14654)

**Comment by bvaughn** [comment]
Hm?

This was just a follow up comment from #14639.

I just meant the concept of doing the double-rendering only for function components that used hooks.  Seems like a nice compromise from double rendering everything.

**Comment by gaearon** [comment]
Just wanted to clarify we haven't actually landed this

**Pull request merged**
