### PR TITLE
Fixed debug performance labels for new component types

### PR DESCRIPTION
**Pull request by bvaughn**
We shouldn't show "Unknown" in the performance tab:
screen shot 2018-04-12 at 9 05 29 am

The perf labels will now exclude `StrictMode` and `unstable_AsyncMode` components. `forwardRef` components will display as "_ForwardRef_".

### CODE REVIEW

**Comment by gaearon** [comment]
Maybe let's just exclude them? Not that they're very valuable. I think they're just going to clutter the output in most cases.

Like we exclude context [here](https://github.com/facebook/react/blob/c27a99812e75e73d9fad88c97ac8b8db452012c1/packages/react-reconciler/src/ReactDebugFiberPerf.js#L176-L178).

**Comment by billschaller** [comment]
@gaearon this means that we can't collect perf data for functional components implemented with forwardRef - if the ref is forwarded to an intrinsic like <image />, it becomes effectively invisible to the perf infra.

**Comment by gaearon** [comment]
Hmm. I guess maybe let's keep `forwardRef` but ignore modes.

**Comment by bvaughn** [comment]
Will do! Thanks for the confirmation, Bill! 👍

**Comment by billschaller** [comment]
Also @bvaughn if a forwardRef has a displayName set, can that displayName be logged to usertiming instead of `ForwardRef`?

**Comment by bvaughn** [comment]
Sure. I'll mimic what DevTools does.

**Comment by bvaughn** [comment]
Updated, with tests.

**Pull request merged**
