### PR TITLE
[docs/conferences] Move ReactEurope 2017 from Upcoming to Past

### PR DESCRIPTION
**Pull request by ehellman**
ReactEurope 2017 has now ended, moved to Past Conferences. Thanks to everybody who attended!

No playlists are available from the talks yet.

### CODE REVIEW

**Comment by trueadm** [comment]
LGTM, thanks!

**Comment by ehellman** [comment]
Resolved the conflicts! :)

**Comment by trueadm** [comment]
Thanks @edmellum

**Comment by gaearon** [comment]
@trueadm Please add "Documentation: needs merge to stable" label when merging doc PRs. Otherwise it won't appear on the website until React 16.

**Pull request merged**
