### PR TITLE
Update value tracking on cousin radios

### LINKED ISSUE #10739: Recent radio input onChange changes break expected behavior
### Background ###
I see from [this issue thread](#1471) that recent changes were pushed in `15.6.x` that have – to my mind – broken some of the expected behavior when it comes to firing `onChange` events in a group of radio button inputs.
  
I am aware of the conversation in #1471, but the problem it's describing is not exactly the same as this so far as I can tell. 
  
Note that the problem I'm about to describe *does not occur* in React <=`15.4.x`.
  
### Expectations ###
We would expect an individual radio button's `onChange` to fire in these two conditions (among others):
1.  A radio input is clicked and it's state changes
2.  A label for any radio input is clicked, causing (1).
  
Indeed, native elements work precisely this way:

```html
<html>
    <head></head>
    <body>
        <input type="radio" id="radio1" name="radiogroup"/>
        <label for="radio1">One</label>
        <input type="radio" id="radio2" name="radiogroup"/>
        <label for="radio2">Two</label>
    </body>
    <script>
        var r1 = document.getElementById('radio1');
        var r2 = document.getElementById('radio2');
        var handler = function(event){
            console.log(event);
        };
        r1.addEventListener('change', handler);
        r2.addEventListener('change', handler);
    </script>
</html>
```
  
If you click the above radio buttons and observe the console output, you'll see that the event is firing as expected: only when a desired input's state is being changed to something new.
  
[Here is a Codepen example](https://codepen.io/darth-cheney/pen/PJZjEq/)
  
### React Expectations ###
The following React component will work as expected in `15.4.x` but not `15.6.x`:
   
```jsx
const RadioTest = (props) => {
    let handler = (event) => {
        console.log(event);
    }
    return(){
        <div>
            <input
                type="radio"
                name="radiogroup1"
                id="radio1"
                onChange={handler}/>
            <label htmlFor="radio1">One</label>
            <input
                type="radio"
                name="radiogroup1"
                id="radio2"
                onChange={handler}/>
            <label htmlFor="radio2">Two</label>
        </div>
    }
};
```
In `15.4.x` React, this the inputs in this component will work as you'd expect and as the native DOM elements work. [This Codepen shows it working properly with 15.4.1](https://codepen.io/darth-cheney/pen/yzeXKo/)
  
In `15.6.x`, the `onChange` event **seems to only fire once**. [Here is another Codepen showing it doesn't work](https://codepen.io/darth-cheney/pen/MEKoxV/) when 15.6.1 is imported.
  
It is, of course, entirely possible that I am doing something incorrectly (and have been doing so for a couple of years now), but the breaking change to my components only came with recent updates.

### PR DESCRIPTION
**Pull request by jquense**
fixes #10739 

I’m not sure how this managed to not get fixed in the last PR. I updated the fixture to ensure that its fully testing whether the regression is fixed. Unfortunately
it means that 15.6.2 didn’t get this fix, do we call it at this point or what is the policy on releasing fixes on previous majors?

### CODE REVIEW

**Comment by gaearon** [comment]
Flow fails:

```

$ node ./scripts/tasks/flow
Error: src/renderers/dom/shared/inputValueTracking.js:19
 19: type ElementWithValueTracker = HTMLInputElement & WrapperState;
                                                       ^^^^^^^^^^^^ property `_valueTracker`. Property not found in
333:       inputValueTracking.updateValueIfChanged(otherNode);
                                                   ^^^^^^^^^ HTMLInputElement. See: src/renderers/dom/fiber/wrappers/ReactDOMFiberInput.js:333
```

>Unfortunately it means that 15.6.2 didn’t get this fix, do we call it at this point or what is the policy on releasing fixes on previous majors?

Was it always broken or did it regress in 15.6.0? If it fixes a regression I guess we'll have to cut 15.6.3. But we need to make sure the fix is solid.

**Comment by jquense** [comment]
This is was a regression in `15.6.0` yeah. grr flow, sorry about that, i have to much trust that my vscode will surface an issue :P

I've love to ensure that this solid, any other thoughts on acceptance criteria for that? We'll do the full fixture test run on it of course (not that that helped last time), more context here: https://github.com/facebook/react/pull/10186#discussion_r142151892

**Comment by gaearon** [comment]
Do we have a post mortem on why fixtures didn't catch this?

**Comment by aweary** [comment]
> do we call it at this point or what is the policy on releasing fixes on previous majors

I think this would warrant another 15 patch release.

**Comment by jquense** [comment]
> Do we have a post mortem on why fixtures didn't catch this?

Not entirely, I don't see much suggesting that something changed since the PR that broke it again, but idk. My hunch is that it's because the fixture was incomplete. It only asked to tests for 2 change events, the last fix essentially added one more change event where their wasn't one, but   stopped there. so:

- originally: you got one change event e.g initial selected **A** -> **B** worked, but not **B** -> **A**
- first fix: **A** -> **B** -> **A** worked (2 events) but not **A** -> **B** -> **A** -> **B**
- this one: all events fire

**Comment by jquense** [comment]
gonna fix this up. anyone want to do a bit more testing in addition to what I've done or we feel good about this?

**Comment by jquense** [comment]
ping before 16.1.0 happens

**Comment by jquense** [comment]
(I still need to rebase sorry)

**Comment by nhunzaker** [comment]
@jquense I'll do some QA on this, but I can't get to it until later today. 

Still I'd like to get this merged in soon.

**Comment by nhunzaker** [comment]
Works in:

Firefox 47, 57
Safari 7.1, 8, 9, 10.1, 11
Chrome 42, 43, 44, 62
IE 9, 10, 11
Edge 16
iOS 8.4, 10.2, 11

On an unrelated note, the click event test fixtures fails in:

Safari 7.1, 8, 9
iOS Safari 8.4
Chrome 42

I'll file a separate issue for that, even if it's to conclude that we don't care.

**Comment by nhunzaker** [comment]
Oh, and I ran prettier for you, so this should pass CI soon :)

**Comment by gaearon** [comment]
I think it is extremely unlikely we'll do another 15.x at this point.

**Comment by gaearon** [comment]
Looking at the fix though it does seem pretty small. If we broke it and you're willing to cut 15.6.4 and more in case it adds further breakage then maybe. :-)

**Comment by nhunzaker** [comment]
Awesome. I'll write up a check list. I'd also like to run it locally on a few of our apps at work and verify everything is 👌 in real apps, then circle back to the test fixtures with any mishaps.

**Comment by nhunzaker** [comment]
The first thing to do is send this out to `15-dev`. @jquense is that something you are comfortable taking on?

**Pull request merged**
