### PR TITLE
Redirect old Jekyll website to new Gatsby website

### PR DESCRIPTION
**Pull request by bvaughn**
Proposed alternative to #10856: Add `index.html` and `404.html` pages with JavaScript redirect to reactjs.org.

I've pushed this change to the [`gh-pages` branch in my fork of react](https://github.com/bvaughn/react/tree/gh-pages) and it seems to work okay, eg:

* https://bvaughn.github.io/react/
* https://bvaughn.github.io/react/docs/installation
* https://bvaughn.github.io/react/community/videos.html

PS Aww yeeeaaahhhhh −96,611

### CODE REVIEW

**Comment by bvaughn** [comment]
😅 😅 😅  Thanks~

**Comment by bvaughn** [comment]
Going to hold off on merging this for the moment. Not sure how it might impact crawlers.

**Comment by gaearon** [comment]
The method I mentioned in the other PR worked really well with the crawlers. But the downside is I manually went through all files with this copy paste. Maybe we could just automate it?

**Comment by bvaughn** [comment]
Yeah, after considering crawlers, I'm also leaning towards manually generating the entire site (yuck) with `<meta>` tags. Over time (once we update the GitHub site settings and once people start noticing the redirects) those old links will hopefully become less common.

**Comment by bvaughn** [comment]
I updated the Gatsby site `gatsby-node.js` script to log each page and redirect path it generates. (This should be the entire list of unique URLs for the new/old site.) Then I ran the following script:

```js
const {existsSync, mkdirSync, writeFileSync} = require('fs');
const {join} = require('path');

const urls = `...`; // From gatsby-node.js

const createPage = path => `
<html>
  <head>
    <meta http-equiv="refresh" content="0; url=https://reactjs.org/${path}">
    <link rel="canonical" href="https://reactjs.org/${path}">
  </head>
  <body>
    Redirecting to <a href="https://reactjs.org/${path}">https://reactjs.org/${path}</a>...
  </body>
</html>
`;

urls.trim().split('\n').forEach(path => {
  let bound = 0;
  while (true) {
    const index = path.indexOf('/', bound);

    if (index >= 0) {
      let subpath = path.substr(0, index);
      subpath = join(__dirname, subpath);

      if (!existsSync(subpath)) {
        mkdirSync(subpath);
      }

      bound = index + 1;
    } else {
      break;
    }
  }

  writeFileSync(
    join(__dirname, path),
    createPage(path)
  );
});
```

I'll push this momentarily.

**Pull request closed without merging**
