### PR TITLE
Add component stack to ReactControlledValuePropTypes

### PR DESCRIPTION
**Pull request by spicyj**

### CODE REVIEW

**Comment by gaearon** [comment]
If we're getting rid of "Check the render method", should we encourage people to use the `jsx-source` plugin more broadly? Unfortunately we don't include it in development because we don't have a sure way to tell if the user is in development or not.

**Comment by spicyj** [comment]
The stack without jsx-source is still more informative than "Check the render method".

**Comment by aweary** [comment]
What if it displayed some information on including `jsx-source`  if `__source` isn't available?

> Include the `babel-plugin-transform-react-jsx-source` plugin in your Babel development config to get a full trace of this warning.

Or something less verbose with a link.

**Comment by spicyj** [comment]
I'm torn. You wouldn't have line info if you don't use JSX and on frames containing third-party components.

**Comment by gaearon** [comment]
>The stack without jsx-source is still more informative than "Check the render method".

Ah, I haven't thought about it. 👍

**Pull request merged**
