### PR TITLE
Remove AnalyticsEventPlugin

### PR DESCRIPTION
**Pull request by spicyj**
We only ever had a couple internal users of this, and now we have none. Removing it from the repo for cleanliness.

### CODE REVIEW

**Comment by blainekasten** [comment]
:+1:

**Comment by zpao** [comment]
:thumbsup:

**Comment by tholapz** [comment]
What do you suggest to use in place of this feature?

**Comment by spicyj** [comment]
I don't know; this was never supported. I haven't used https://github.com/yahoo/react-i13n but it might be useful for you.

**Comment by gaearon** [comment]
If you happen to use Redux, people find https://github.com/markdalgleish/redux-analytics helpful.

**Pull request merged**
