### PR TITLE
Rewrote ReactIncrementalPerf-test using only public API.(#11299)

### PR DESCRIPTION
**Pull request by abiduzz420**
## Prerequisites
- [x] All tests ran successfully
- [x] Code formatted with prettier
- [x] Code linting done
- [ ] Flow run pending (Issue related to Windows, #11703)
- [x] Completed the CLA

## Changes added
- `ReactPortal.js` shifted to `shared` directory
- Implemented `createPortal()` method in `ReactNoop.js`
- This `createPortal()` is used to write test for support portals in `ReactIncrementalPerf-test.internal.js`

_Please let me know if I need to make any further modifications or changes._

### CODE REVIEW

**Comment by abiduzz420** [comment]
This PR solves the issue from #11299 in `ReactIncrementalPerf-test.js`

**Comment by gaearon** [comment]
Thanks!

**Comment by abiduzz420** [comment]
Thanks @gaearon Dan for helping me out :)

**Comment by SomeshThakur** [comment]
Awesome Work Uzair ! :)

**Comment by kwnccc** [comment]
Great job @abiduzz420

**Pull request merged**
