### PR TITLE
adler32: Properly break loop into 4096-char blocks

### PR DESCRIPTION
**Pull request by spicyj**
I believe this was lost in translation in #4400. Can't say I fully understand why this is significant at all though...

### CODE REVIEW

**Comment by spicyj** [comment]
@syranide @jimfb

**Comment by jimfb** [comment]
Subtle.  Do we care?  If so, do we want a testcase?

Our implementation is already doing things like dropping the expensive UTF16 arithmetic, right?

Also, are we maintaining the checksumming?  Or are we moving to walking elements at restore time?

**Comment by syranide** [comment]
It's the same thing except the for-condition is cached and not reevaluated every iteration.

**Comment by jimfb** [comment]
@syranide Doesn't look the same.  The new version proposed in this diff does not update the value of `i + 4096` on each loop iteration.

**Comment by spicyj** [comment]
I don't see how it can be the same because i changes each iteration.

**Comment by spicyj** [comment]
I don't know how to test this.

Checksumming and dropping IDs are completely independent. I haven't heard any interest in dropping checksumming or what an alternative would be.

**Comment by syranide** [comment]
Oh wait yeah, the current implementation is broken for large values (overflow), but otherwise identical. It was meant to be done this way to avoid mod:ing every iteration.

**Comment by jimfb** [comment]
@spicyj No, not dropping IDs, this is referring to the `createElement vs innerHTML` change.  The alternative would be walking the materialized DOM and diffing, rather than re-generating the markup and checking the checksum.  Regenerating the markup requires an equivalent to renderToString to be shipped with ReactDOM in order to revive the markup, right?

**Comment by syranide** [comment]
I haven't done the math/testing, but I suspect no one is actually affected by this bug and the result should be the same before and after no longer buggy.

**Comment by jimfb** [comment]
I think what @syranide is saying is that this new version is more correct, in which case, I'm fine with shipping it (:+1:).  I still wonder if we want a unit test.

**Comment by syranide** [comment]
Yeah that's correct, let me just give it a spin a few times and make sure.

**Comment by syranide** [comment]
Yeah, you need something in the vicinity of a 2^24 long string for it to *overflow*. So realistically it doesn't need to be fixed. However, with this PR it's faster because of the cached condition and some JS VMs will use integer math for 32bit ints rather than floating point arithmetic which makes it even faster.

**Comment by spicyj** [comment]
Am I missing something? With 16-bit chars it could overflow after 91 chars:

```
a = 1;
b = 0;
for (i = 0; b < Math.pow(2,32);i++) {
b += (a += 65535) + (a += 65535) + (a += 65535) + (a += 65535);
}
i
```

image

**Comment by syranide** [comment]
Safe integers are 53bit or so. Also yes, worst-case utf16 shorten it significantly, but still unlikely that anyone has overflowed I'd say.

**Comment by spicyj** [comment]
@jimfb Do you want to propose a test I can add? Otherwise I don't have anything more to do here.

**Comment by jimfb** [comment]
I'll defer to @syranide for a CR on this one.  He understands this code best.  That said, the code looks fine with me ( :+1: ).

If you do decide to add a test: maybe generate a large string that would overflow the old code, and assert that the checksum is correct.  Not a huge deal I suppose.

**Comment by syranide** [comment]
The only thing that makes sense to me is to pregenerate a bunch of checksums (or use a ref impl) and test against that. Certainly a good thing, but it doesn't seem high priority to me in context, different versions of react are not compatible and it's a dev thing (kind of), so even an incorrect impl is probably good enough. So yeah, sure why not, but doesn't seem like a deal breaker to me.

**Pull request merged**
