### PR TITLE
Remove Reconciler fork (1/2)

### PR DESCRIPTION
**Pull request by kassens**
We've heard from multiple contributors that the Reconciler forking mechanism was confusing and/or annoying to deal with. Since it's currently unused and there's no immediate plans to start using it again, this removes the forking.

Fully removing the fork is split into 2 steps to preserve file history:

**This PR**
- remove `enableNewReconciler` feature flag.
- remove `unstable_isNewReconciler` export
- remove eslint rules for cross fork imports
- remove `*.new.js` files and update imports
- merge non-suffixed files into `*.old` files where both exist (sometimes types were defined there)

**#25775**
- rename `*.old` files

### CODE REVIEW

**Comment by sebmarkbage** [comment]
It would actually be better to do it in the reverse way and keep `.old.js` and then rename those to `.new.js`. Because I believe the old history before the fork is preserved in `.old.js`. So blame would lead you to those older commits instead of when all the `.new.js` files were added. https://github.com/facebook/react/commit/17f582e0453b808860be59ed3437c6a426ae52de#diff-8efe87e6ea593ec7054c62c8e87f845666ce3ca6b72ab492a1dbcd9f7e28357f

**Comment by kassens** [comment]
Updated to remove the `*.new` files instead.

**Comment by kassens** [comment]
Sorry for the noise, this should now be ready for review.

**Comment by acdlite** [comment]
@sebmarkbage https://github.com/facebook/react/pull/25774#issuecomment-1334551895

Oh nice! For some reason I thought I had messed that up. Glad it's still there.

**Review by acdlite — APPROVED** [review]

**Pull request merged**
