### PR TITLE
Add documentations for Shallow rendering of TestUtils

### PR DESCRIPTION
**Pull request by koba04**
This PR is for adding some documentations for shallow rendering.

* Add `render` returns shallowly rendered output
* Add a documentation about unmount method
* Add a documentation about getMountedInstance method

### CODE REVIEW

**Comment by vjeux** [comment]
Thanks for this pull request and sorry we didn't get to use it but it looks like it is now on the website: https://facebook.github.io/react/docs/test-utils.html#shallow-rendering

Closing it. Feel free to reopen a new pull request if you think that the current version is missing things from this pull request!

**Comment by gaearon** [comment]
I think the point wasn’t to document shallow rendering itself, it was about `getMountedInstance()` and `unmount()` which are currently undocumented. I don’t know whether they are public API or not though 😄 .

**Comment by koba04** [comment]
> I think the point wasn’t to document shallow rendering itself, it was about getMountedInstance() and unmount() which are currently undocumented. I don’t know whether they are public API or not though 😄 .

I'm not sure too...

> Add render returns shallowly rendered output

How about this one?
I think in many cases don't need calling `getRenderOutput` because `render` returns the rendered output.
Is there any intent ?

**Comment by gaearon** [comment]
I'll close this PR since we reshuffled docs. If you'd like, you can submit another PR documenting `unmount()` and `getMountedInstance()` but please maintain the style of existing docs.

**Pull request closed without merging**
