### PR TITLE
FIXED SSL link to JSFiddle breaking dependencies

### PR DESCRIPTION
**Pull request by nemoDreamer**
Browser won't allow loading the dependencies in `<script src="http://fb.me/react-js-fiddle-integration.js"></script>`.

### CODE REVIEW

**Comment by spicyj** [comment]
cc @reedloden – there are probably more of these that don't work in their current state…

**Comment by reedloden** [comment]
Ugh, I didn't notice jsfiddle.net was including a `<script>` like this. I can poke jsfiddle.net to update their react support to use https://fb.me/react-js-fiddle-integration.js instead, but somebody on FB's side needs to update that link to go to an [SSL'ized version](https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-prn1/851561_341095626017279_6573_n.js). If you use HTTPS Everywhere (which I do), there's a [rewrite rule](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Facebook.xml) that makes this not get noticed.

cc @zpao to see if he could poke somebody on FB's side.

**Comment by spicyj** [comment]
(It's not jsfiddle's doing – the link is included in each fiddle by the fiddle's author.)

**Comment by zpao** [comment]
For any jsfiddles owned by us, we can fix those. For ones like this which are unowned we can't. But we can recreate them under our reactjs user.

**Comment by nemoDreamer** [comment]
So let's close this PR, since you guys want to stay full SSL, right?
Or are you keeping this open to track resolution of the JSFiddle non-SSL dependencies?

**Comment by zpao** [comment]
Yea, let's close this. I filed #3735 so we don't forget. Thanks for the find btw.

**Pull request closed without merging**
