### PR TITLE
use Object.is for checking mutated children

### LINKED ISSUE #7424: False-positive mutation warning
Given the following test case

```jsx
function TestCmp() {
  return <span>{NaN}</span>;
}

ReactDOM.render(<TestCmp />, document.getElementById('app'));
```
Produces the following warning:

```
Warning: Component's children should not be mutated.
    in span (created by TestCmp)
    in TestCmp (created by Unknown)
```

This is probably caused by [this mutation check](https://github.com/facebook/react/blob/328fc75bc910032ff37dc9d93429fb14b476bd0d/src/renderers/shared/hooks/ReactChildrenMutationWarningHook.js#L34), which was introduced in 15.3.0, but it doesn't work for NaN, because NaN != NaN

### PR DESCRIPTION
**Pull request by just-boris**
fixes #7424

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by chicoxyzzy** [comment]
If we're going to use `object-is` package we also should use it [here](https://github.com/facebook/react/pull/6132) IMO. cc @zpao

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by just-boris** [comment]
~~вы тут ночуете что ли?~~

Of course, I'd like to found all other usages and replace with this lib as well, like it happens with `object-assign` now.

**Comment by caub** [comment]
except NaN, is there another case?

**Comment by just-boris** [comment]
This also doesn't differ `+0` and `-0`, but I don't think that this can be useful for mutation check.

**Comment by zpao** [comment]
Using this external module is going to be more trouble than it's worth right now. We'd have to do something like #6376.

Could you instead inline a copy of the fn like we did in #6132. It's a couple extra bytes but not a huge deal.

**Comment by caub** [comment]
Can't this be a polyfill since `Object.is` is now in browsers?

**Comment by zpao** [comment]
We can discuss that separately. Right now we haven't required the polyfill exist in the other places it's used so we won't start now.

**Comment by just-boris** [comment]
I think this is not actual, because #7455 removes this code at all.

Also, now `Object.is` is used only in ReactPropTypes.js module, so there is no need to create this as shared modlue.

**Pull request closed without merging**
