### PR TITLE
Move renderer host configs into separate modules

### PR DESCRIPTION
**Pull request by gaearon**
I tried resolving host configs statically but it's hard right now because the host config is all over the place in the renderer code.

If we want to resolve the host configs statically, we're going to need to put them into separate modules (so that we can use ES imports for better mangling, and to override resolving on the file level).

I'm working just on that step here. It doesn't change anything from the reconciler's point of view. In some cases (such as with test renderer) I'll have to create a third file that keeps mutable private state that's accessible both by the renderer public API and the host config.

I did this for all host configs except `react-noop-renderer`. This is because we use `react-noop-renderer`, among other things, for testing the npm `react-reconciler` package, and the way it's written now with inline reconciler calls reflects how external renderers will continue consuming it. When we add inlining, we'll want to keep that system working.

The diff appears as if there were a lot of changes, but really it's just moving things around and tweaking what imports what. I didn't change the logic.

### CODE REVIEW

**Comment by sophiebits** [comment]
It seems like there are three ways we could do this.

# 1. Split Host Config and Renderer (i.e., this diff)

ReactDOMHostConfig.js:

```
export default {...};
```

ReactDOM.js:

```
import {createContainer, ...} from 'ReactFiberReconciler';
...
export default ReactDOM;
```

# 2. Host Config and Renderer as separate exports

I understand that ES6 modules allow circular imports. So I think that means we can do something like:

ReactDOM.js:

```
import {createContainer, ...} from 'ReactFiberReconciler';
...
export const hostConfig = {...};
export default ReactDOM;
```

and ReactFiberReconciler can import the host config from here. This way we don't need to split them up, which might be more convenient.

# 3. Like now, with a little dynamic injection

That is, continue having ReactFiberReconciler export a function. I guess that would need to look something like:

```
function ReactFiberReconciler(hostConfig) {
  invariant(ReactGlobalHostConfig.current === null);
  ReactGlobalHostConfig.current = hostConfig;
  return require('ReactFiberReconcilerGuts');
```

And then ReactDOM.js unchanged. Which I'm sure Seb will hate, but it would be nice to do this because then we can match the external API for our internal renderers.

# ?

I don't feel qualified to know which is best here.

**Comment by gaearon** [comment]
The approach I wanted to do is similar to what you suggested in (1) except we'd have an `export` for every method in the config rather than a default export for the whole config.

This is why I want to go all-in on ES6 modules and avoid a reified object `config` representation. Having `config` as an object prevents GCC from mangling its property names, and also prevents it from inlining its implementations when they're small enough (such as the case with `insertBefore()` etc).

In terms of expressing it in code, custom renderers would keep doing

```js
import reconciler from 'react-reconciler';
var Thing = reconciler(config);
```

but our renderers would do this:

```js
import * as ReactDOM from 'react-reconciler/inline'; // inline = magic!
```

**Comment by gaearon** [comment]
@bvaughn @acdlite If either of you find the time to review today, I'd be very grateful—this is going to be a pain to keep in sync and I'd like to land before anything else changes in these files :-)

**Comment by gaearon** [comment]
I did some build diffing and I think this is correct. DOM bundle looks closest, other bundles have the order of modules switched up a little bit but the end result should be the same.

**Pull request merged**
