### PR TITLE
Add lang attribute to html tag in tutorial

### PR DESCRIPTION
**Pull request by adelevie**
This should probably be done across the board. Nevertheless, the presence of this attribute helps ensure WCAG compliance.

### CODE REVIEW

**Comment by jimfb** [comment]
I'm not sure how I feel about this one.  The purpose of this code is to be a simple example, and the additional markup just adds more noise for the reader.  The goal of this document is to teach React while keeping the complexity to a minimum, and I don't feel like this change furthers that goal.

We've left off a bunch of WCAG stuff in the examples, and making everything fully WCAG compliant would result in a bunch of additional code that is orthogonal to React.  React does support the WCAG attributes, and anyone who is making their site WCAG compliant will surely be able to figure out how to add these attributes.  This is further complicated by the fact that these documents are being translated into different languages, and it means that the translation may no longer be purely of text nodes (code changes now involve changing browser code).

Anyway, we've also left off things like character encoding tags (though those are arguably even less optional).

**Comment by jimfb** [comment]
We also don't specify the lang attribute on http://facebook.github.io/react/  We should probably fix that, @adelevie, if you're interested in this stuff and looking for something to do :).

**Comment by adelevie** [comment]
Done https://github.com/facebook/react/pull/4295 :)

FWIW, the code generated from the React tutorials should be near close to WCAG-compliant (if not already). That said, that's a fair judgment call on your part, and I appreciate the well-thought-out response.

I've been using the [HTML Code Sniffer](http://squizlabs.github.io/HTML_CodeSniffer/) to quickly find low hanging accessibility bugs.

**Comment by zpao** [comment]
Yea, I'm with @jimfb on this. It's not necessarily bad but the focus, especially on the getting started page, is not on the HTML details (and might actually be the wrong thing to copy paste for somebody in a different locale, whereas the doctype is actually important in some browsers).

I do think accessibility is important though so let's add it to the actual tutorial code (https://github.com/reactjs/react-tutorial/blob/master/public/index.html and https://github.com/facebook/react/blob/master/docs/docs/tutorial.md)

**Pull request closed without merging**
