### PR TITLE
Update to Jest 12.1.1 and Jasmine 2

### PR DESCRIPTION
**Pull request by gaearon**
I took #6769 as a base and updated it to match changes in master so that it merges cleanly.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
@gaearon updated the pull request.

**Comment by zpao** [comment]
Cool, thanks for taking this on and tracking down. If it rebases cleanly onto master, let's do that and then squash those last 2 commits into the "update jasmine2 with changes from master" commit, then do a real merge (not squash and merge).

**Comment by facebook-github-bot-5** [comment]
@gaearon updated the pull request.

**Comment by facebook-github-bot-3** [comment]
@gaearon updated the pull request.

**Comment by gaearon** [comment]
screen shot 2016-05-25 at 22 41 18

**Pull request merged**
