### PR TITLE
Use ReactNativeFeatureFlags in ReactNative

### PR DESCRIPTION
**Pull request by janicduplessis**
Import the proper implementation based on feature flags. Also adds `@flow` in `ReactNativeFeatureFlags`.

Tested that it works by changing `useFiber` in `ReactNativeFeatureFlags` and made sure it uses the right renderer.

cc @bvaughn

### CODE REVIEW

**Comment by sebmarkbage** [comment]
This will bloat the package size for any RN build so we need to ensure that we do this properly by verifying that the performance impact will be minimal.

**Comment by janicduplessis** [comment]
Ideally dead code elimination would work here so we don't ever bundle both renderers. Not sure if it is the case atm.

**Comment by janicduplessis** [comment]
Actually it won't since you could change the flags at runtime. Was there any discussion about bundling with those feature flags? It will be even more important for React web.

**Comment by gaearon** [comment]
Why does it matter the for the web?

Internally at FB we just ship both until we are ready to cut over to Fiber. In open source version we will cleanly cut over in the next release.

**Comment by bvaughn** [comment]
Thanks for submitting this @janicduplessis 😄  This was on my list but I was holding off because of what @sebmarkbage mentioned about package size impact.

Using Ads Manager as a test, I created a minified iOS production bundle for both stack and fiber builds _and_ for the feature-flag build (which includes both).

| RN Version  | Bundle size |
| --- | --- |
| Stack only | 5,307,659 bytes |
| Fiber only | 5,345,738 bytes |
| Runtime switch | 5,359,313 bytes |

The feature flag switch would add 51,654 bytes to the Ads Manager app (slightly less than 1% of the total size). That's probably okay in terms of file size. I don't know how it would impact overall performance though.

I'll run an internal test with this change to verify the runtime impact is minimal. 😄  Stay tuned!

**Comment by janicduplessis** [comment]
@gaeron I figured it would affect bundle size quite a bit, which is more an issue on web where you have to download it at runtime. Makes sense, shipping react 16 with fiber only solves this :)

**Comment by sebmarkbage** [comment]
I think what we'll do is have the open source version of RN only ship with one renderer right now. We'll ship both in Facebook apps for a while as we A/B test them. Then we'll switch over RN to be Fiber-only.

**Comment by janicduplessis** [comment]
Sounds like a good plan, closing this.

**Pull request closed without merging**
