### PR TITLE
warn when it looks like you haven't updated react-dom

### PR DESCRIPTION
**Pull request by threepointone**
sketching a possible "fix" for #14039 for discussion. 

- icky error message, I know. 
- can't think of a good test for this, open to suggestions. should I mock the dispatcher to trigger this specific error? sounds self serving. 
- should probably add a TODO to remove this in v17

### CODE REVIEW

**Comment by threepointone** [comment]
I should add a flag that fires this warning only once.

**Comment by gaearon** [comment]
How did you test this? It's likely specific message in https://github.com/facebook/react/issues/14039 is no longer what happens. We need to actually look at what happens when e.g. using `react@16.8.0-alpha.0` and `react-dom@16.7.0` / `react-dom@16.6.0` (it's even possible the messages are different).

**Comment by threepointone** [comment]
I haven't tested this, setting it up right now. will report back.

**Comment by gaearon** [comment]
We kind of wanted `react-dom` to keep working with `react` of the same major without breaking. I don't think a strict match is necessarily desired unless you're trying to use new features — in which case you should have *at least* that version of both.

**Comment by aweary** [comment]
>  I don't think a strict match is necessarily desired unless you're trying to use new features

Why not? Using mismatched versions isn't something people do intentionally (afaik) and if a user is already updating one, the burden of updating the other should be low.

**Comment by gaearon** [comment]
If it works fine, what's the point of being too sensitive about it? In general it doesn't cause issues anymore.

**Comment by threepointone** [comment]
alright, I've verified, here'se how react/react-dom at various versions interact with a simple hook - 

react@16.7.0-alpha.0
* 0.0 - ?? fails before react even starts up,  
* 3.0, 4.0, invariant - `Hooks can only be called inside the body of a function component.`
* 5.0, 6.0 - `dispatcher.useState is not a function`
* 8.0 - ` Cannot set property 'current' of undefined`

react@16.8.0-alpha.0
* all older versions fail with “Hooks can only be called inside the body of a function component."
* 0.0 - 2.0 - throws
* 3.0 - 7.0-alpha - invariant 

honestly, this is kind of an edgecase squared, mismatched versions of react/react-dom *and* using hooks recently. maybe we shouldn't do anything.

**Comment by aweary** [comment]
> If it works fine, what's the point of being too sensitive about it? In general it doesn't cause issues anymore.

It does cause issues though, and even if it causes _less_ issues now there is still a chance that it will break things in the future. I don’t think there’s any reason to think that this would be less likely in the future? We don’t have any fixtures looking for undefined behavior with mismatched versions before release AFAIK

A single warning doesn’t seem too sensitive either. There’s no case where we recommend using mismatched versions, so it would always signal a real issue to the user.

**Comment by gaearon** [comment]
@threepointone It "throws" on usage only, right? If we don't use Hooks then it's ok?

**Comment by gaearon** [comment]
>0.0 - 2.0 - throws

throws what?

>3.0 - 7.0-alpha - invariant

which invariant?

**Comment by threepointone** [comment]
@gaearon - "Hooks can only be called inside the body of a function component.". they all throw. 0.0 - 2.0 throw it as a regular error (like, codesandbox reported it as a normal error), the rest as an invariant (with the 'invariant' warning).

**Comment by gaearon** [comment]
OK. I think the most actionable thing here is to make a doc page (similar to "current owner" error) that explains possible causes (calling outside render, calling inside useMemo, duplicate React, wrong version of React), and add a link to the existing invariant. What do you think?

**Comment by threepointone** [comment]
Yeah, I think that would gather these loose ends in one place. I'll do it.

**Comment by threepointone** [comment]
closing

**Pull request closed without merging**
