### PR TITLE
Update 07-forms.md

### PR DESCRIPTION
**Pull request by timarney**

### CODE REVIEW

**Comment by zpao** [comment]
`value` is assigned to a variable on the previous line. This came up in #3028 so let's just get rid of the assignment line. Can you update with that?

**Comment by cody** [comment]
@zpao Without the variable the line gets too long, doesn't it?

**Comment by timarney** [comment]
I missed that line just like #3028.  Based on other tutorials etc... I prefer this.state.   Showing function  vs making code compact.

If there was another input below, that was a shorter line would the code change for that input (in the same example)?

**Comment by zpao** [comment]
@cody yea :( Perhaps we could just make this mulitline?

It's not how we would typically format this but it easy to read at a glance:

```js
    return <input
             type="text"
             value={this.state.value}
             onChange={this.handleChange}
           />;
```

(damn you ASI for not just letting us go to the next line)

**Comment by timarney** [comment]
Hey Guys

Probably not the correct place to post this but ...

Outside of the above.  I'm confused regarding "Uncontrolled Components" on this page in the docs.

"Any user input will be immediately reflected by the rendered element. If you wanted to listen to updates to the value, you could use the onChange event just like you can with controlled components."

===============================
I put together a little test here (using jest):

https://github.com/timarney/react-formtest

If I use the "controlled way" outlined in the docs -> value={this.state.value} onChange={this.handleChange} the test passes.

If I don't use value={this.state.value} the test fails.  

For the onChange guessing I could remove the line this.setState({value: event.target.value}); but how the default handlers work.

Am I misunderstanding something or?

**Pull request closed without merging**
