### PR TITLE
Fix active item for permalinks

### LINKED ISSUE #11043: Active Tab is not included in current route or permalinks on new docs site
**Do you want to request a *feature* or report a *bug*?**
bug on new docs site

**What is the current behavior?**
on the new docs site active tab is not included in current route or permalinks so when attempting to send someone here https://reactjs.org/docs/installation.html#using-a-cdn they are instead dropped here https://reactjs.org/docs/installation.html because the correct tab is not active

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**
- go here https://reactjs.org/docs/installation.html
- click "add react to existing app" tab
- grab any permalink from within this section, (ex. https://reactjs.org/docs/installation.html#enabling-es6-and-jsx)
- open that permalink from within an incognito window

**What is the expected behavior?**
should be taken to the correct linked section within the docs

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
this is not an issue with react itself, just the new docs site

### PR DESCRIPTION
**Pull request by ilasorsa**
This should fix #11043

### CODE REVIEW

**Comment by bvaughn** [comment]
Thanks for this PR 😄 

Did you perhaps mean to refer to issue #10888 (rather than #11043)?

I believe #10888 was already resolved via PR #10998 but please let me know if that is incorrect. Going to close this for now since I think it's already been resolved.

**Comment by ilasorsa** [comment]
With this PR I intended to fix the active class for URI with permalink into it. If you go [here](http://reactjs.netlify.com/docs/hello-world.html#a-note-on-javascript), it misses the active class for the current item. It seems to me #11043 was about this behaviour but I might be wrong.

**Comment by bvaughn** [comment]
Thanks for clarifying. #11043 was actually about the Installation page specifically, and properly jumping to anchor tags within its tabbed UI (which has been removed).

**Comment by bvaughn** [comment]
Please rebase this PR so that it can be merged into `master` rather than the `gatsby` branch (which is closed). You'll need to handle conflicts in files like [`findSectionForPath`](https://github.com/facebook/react/blob/master/www/src/utils/findSectionForPath.js) which already have a subset of these changes applied.

Then I'll give it another pass. 😄

**Comment by ilasorsa** [comment]
I'm sorry but I fear this is bugged in "tutorial" section.

**Comment by bvaughn** [comment]
Okay. Please feel free to re-open when/if you resolve that issue.

**Pull request closed without merging**
