### PR TITLE
Fix test renderer unmount

### PR DESCRIPTION
**Pull request by gre**
Fixes https://github.com/facebook/react/issues/8459

### CODE REVIEW

**Comment by Aweary** [comment]
@gre can you run the [`scripts/fiber/record-test`](https://github.com/facebook/react/blob/master/scripts/fiber/record-tests) script and add the results to this please? I think we can merge afterwards

**Comment by gre** [comment]
done

**Comment by Aweary** [comment]
Thanks again @gre!

**Comment by gaearon** [comment]
@aweary 

Please always set the "next" (non-specific) milestone when merging. Otherwise the release tool won't see the pull request and we'll keep skipping it until the next major.

**Pull request merged**
