### PR TITLE
ESLint upgrade & fixes

### PR DESCRIPTION
**Pull request by zpao**
Upgraded to using JS instead of YAML and upgraded eslint & bits. I had some other formatting I had done which conflicted but I kept some of it.

### CODE REVIEW

**Comment by jimfb** [comment]
Looks fine to me, just needs to be squashed, @spicyj ?

**Comment by zpao** [comment]
I'll squash the last two. I want to keep the file move / conversion distinct so we can track the actual rule changes.

**Comment by jimfb** [comment]
I'll tentatively accept, pending a thumbs up from @spicyj

**Comment by zpao** [comment]
Meh, it's fine :)

**Pull request merged**
