### PR TITLE
Change warnings to use expectDev

### PR DESCRIPTION
**Pull request by spicyj**
There are still prod deviations but this is many of them.

### CODE REVIEW

**Comment by gaearon** [comment]
Looks like https://github.com/facebook/react/blob/master/scripts/jest/setupSpecEquivalenceReporter.js needs changing too?

**Comment by gaearon** [comment]
Or rather https://github.com/facebook/react/blob/master/src/isomorphic/modern/class/__tests__/ReactClassEquivalence-test.js.

**Comment by spicyj** [comment]
Just gonna leave out the ReactES6Class-test changes for now.

**Comment by gaearon** [comment]
Looks great!
I cherry-picked to master and updated the test list files.

**Pull request closed without merging**
