### PR TITLE
move augmentClass definition above SyntheticEvent Proxy replacement

### PR DESCRIPTION
**Pull request by walrusfruitcake**
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`).
6. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run prettier`).
7. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
8. If you added or removed any tests, run `./scripts/fiber/record-tests` before submitting the pull request, and commit the resulting changes.
9. If you haven't already, complete the CLA.

### CODE REVIEW

**Comment by aweary** [comment]
The browser mentioned in #10010 is QTWebkit, which appears to be an unofficial fork of Webkit. While this change is trivial, I'm hesitant to include changes meant to address dev-only issues in unsupported browsers. 

The usage of `Proxy` here appears to be correct, which indicates that the `Proxy` implementation `GTWebkit` is using is possibly incorrect (especially since this `Proxy` call has been working in Webkit browsers for a long time).

**Comment by gaearon** [comment]
We could get it in but there's no guarantee we won't break again.

**Comment by aweary** [comment]
@gaearon do you want to make the call here? It's a (seemingly) innocent change, but I'm hesitant to accept since it sets a precedence for including changes for unsupported environments. But it's up to you.

**Comment by gaearon** [comment]
If it doesn't break anything I'm cool with taking it.

**Comment by aweary** [comment]
Cool, I'll verify everything looks OK locally and merge if so

**Comment by gaearon** [comment]
Seems fine to me, I'll get it in.

**Pull request merged**
