### PR TITLE
Loosen assertion so it matches any production error

### PR DESCRIPTION
**Pull request by acdlite**
This test was failing because the error code didn't match. The specific error code isn't important.

### CODE REVIEW

**Comment by gaearon** [comment]
I would assume it means it is crashing for a different reason.

**Comment by acdlite** [comment]
It was because the message was slightly different, which I fixed in https://github.com/facebook/react/commit/2afcf6e09f6a710a0898b6bf097626079aa8719a

I figured loosening the invariant made sense, anyway.

Although after rebasing, now I'm having a different problem where the error code transform isn't picking up that invariant, but works for other invariants in the same file. Weird.

**Comment by acdlite** [comment]
Ah, the message is the same as Stack but the template string passed to `invariant` is different. I'll change.

Also, we haven't run `gulp react:extract-errors` in a while. Should we automate that?

**Comment by acdlite** [comment]
I guess it happens before release so it's not a big deal.

**Comment by gaearon** [comment]
Yea, it's in the release guide so shouldn't be necessary.

**Comment by acdlite** [comment]
@spicyj Going to assume this is good to merge now that we know why the codes were different (they're the same now), since you approved it earlier.

**Comment by spicyj** [comment]
I don't think we should loosen this unnecessarily – even if format changes are okay, problems building the URL or similar could surface and be caught by the old test. Can we revert this? (If I rescind my acceptance then please don't consider a PR accepted.)

**Comment by acdlite** [comment]
Ok I'll revert it and open a separate PR without the change to the test.

**Comment by acdlite** [comment]
And sorry, I didn't intentionally ignore your review... I thought it was ambiguous whether you had "rescinded" it or not, since there were two reviews, hence my comment :D

**Comment by spicyj** [comment]
Latest review wins. :)

**Pull request merged**
