### PR TITLE
refactoring: warning revamp part 2

### PR DESCRIPTION
**Pull request by Jessidhia**
Part 2 of https://github.com/facebook/react/issues/16753

Updating the babel plugin to handle the new syntax was a bit tricky.

`invariant` was also originally not part of the scope, but because the plugin that validated arguments to `warning` also expected `invariant` to have the same interface, I had to choose between forking the plugin or also transforming `invariant`.

Some of the expressions may look funny; they were generated by this codemod:

<details>

```js
'use strict';

module.exports = function transformer(file, api) {
  const j = api.jscodeshift;

  return j(file.source)
    .find(j.CallExpression)
    .filter(path => {
      const callee = path.value.callee;
      if (callee.type !== 'Identifier') {
        return false;
      }
      const name = callee.name;
      const scope = path.scope.lookup(name);

      return (
        // "isGlobal" just means file scope, even in Modules
        (scope === null || scope.isGlobal) &&
        (name === 'warning' ||
          name === 'warningWithoutStack' ||
          name === 'lowPriorityWarning' ||
          name === 'lowPriorityWarningWithoutStack' ||
          name === 'invariant')
      );
    })
    .forEach(path => {
      const firstArgument = path.value.arguments[0];
      if (firstArgument.type === 'StringLiteral') {
        // already transformed?
        return;
      }
      if (firstArgument.type === 'Literal') {
        if (firstArgument.value) {
          if (path.parentPath.value.type === 'ExpressionStatement') {
            path.prune();
          } else {
            path.replace(j.identifier('undefined'));
          }
          return;
        }
        path.value.arguments.shift();
        return;
      }

      path.value.arguments.shift();
      if (path.parentPath.value.type === 'ExpressionStatement') {
        return path.parentPath.replace(
          j.ifStatement(
            j.unaryExpression('!', firstArgument),
            j.blockStatement([path.parentPath.node])
          )
        );
      } else {
        return path.replace(
          j.sequenceExpression([
            j.logicalExpression('||', firstArgument, path.node),
            j.identifier('undefined'),
          ])
        );
      }
    })
    .toSource();
};
```
</details>

### CODE REVIEW

**Comment by gaearon** [comment]
Seems like something's up in prod environment — prod tests are failing?

**Comment by acdlite** [comment]
> invariant was also originally not part of the scope, but because the plugin that validated arguments to warning also expected invariant to have the same interface, I had to choose between forking the plugin or also transforming invariant.

Can you please fork `invariant` instead? We have separate plans to replace those with `throw Error` expressions in the source and I'd rather not update those callsites twice.

**Comment by acdlite** [comment]
I personally hate the `wrap-warning-with-env-check` plugin. Can we make an eslint rule instead of relying on a babel plugin to do it for us? The end game is to get to writing `console.error` directly.

**Comment by gaearon** [comment]
Thanks for starting this! @walaura picked up your script and we got to completion in https://github.com/facebook/react/pull/17568. ❤️

**Pull request closed without merging**
