### PR TITLE
Fix reversed server/client in message

### PR DESCRIPTION
**Pull request by gilbox**

### CODE REVIEW

**Comment by gilbox** [comment]
I would fix the UT but at first glance it looks OK. I still think this is a bug though.

**Comment by zpao** [comment]
This is actually correct as is. `markup` is generated on the client. `rootMarkup` is what was already in the node. The failing test shows this correctly (yay tests!).

**Comment by gilbox** [comment]
Actually, what the tests prove is that the test coverage is incomplete. I agree that the test seems correct. However, in my real-world scenario the markup was swapped. I don't care enough about this bug to pursue it right now, though, so closing this is alright.

**Comment by zpao** [comment]
I would definitely be interested in a test case that shows the discrepancy. Let us know if you can repro & find the time to share.

**Pull request closed without merging**
