### PR TITLE
Fix two typos in CHANGELOG.md

### PR DESCRIPTION
**Pull request by owenarthur**
## Summary

This fixes two small typos in the v19.0.0 CHANGELOG.md entry.

## How did you test this change?

N/A

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
Thank you. I also incorporated these changes into https://github.com/facebook/react/releases/tag/v19.0.0

**Comment by eps1lon** [comment]
Can you sign [the CLA check](https://github.com/facebook/react/pull/31678/checks?check_run_id=33998870808) so that we can merge this?

**Comment by kachkaev** [comment]
It’d be also great to fix heading levels if it’s not too late: https://github.com/facebook/react/pull/31675#discussion_r1871923519

**Comment by eps1lon** [comment]
@kachkaev Can you file a PR for that?

**Comment by kachkaev** [comment]
Sure: https://github.com/facebook/react/pull/31683

**Comment by kachkaev** [comment]
> @kachkaev Can you file a PR for that?

https://github.com/facebook/react/pull/31683

**Pull request merged**
