### PR TITLE
Rename "shared subset" to "server"

### PR DESCRIPTION
**Pull request by acdlite**
The internal file ReactSharedSubset is what the `react` module resolves to when imported from a Server Component environment. We gave it this name because, originally, the idea was that Server Components can access a subset of the APIs available on the client.

However, since then, we've also added APIs that can _only_ by accessed on the server and not the client. In other words, it's no longer a subset, it's a slightly different overlapping set.

So this commit renames ReactSharedSubet to ReactServer and updates all the references. This does not affect the public API, only our internal implementation.

### CODE REVIEW

**Review by gnoff — COMMENTED** [review]
@acdlite When Seb and I discussed this in the past we thought the suffix should be `react-server` rather than `server` because it aligns with the condition. If we use just server it is a bit ambiguous since it isn't meant to be used for SSR. I'm still partial to `react.react-server.js` but lmk if you feel strongly to keep `react.server.js`

**Comment by acdlite** [comment]
@gnoff That's fine with me though I'm not sure `react.react-server` is much less confusing than `react.server` in that regard. 

How about `react.rsc`? Or is the idea to align it with the `react-server` exports condition?

**Comment by acdlite** [comment]
I'll switch to `react-server` for now though we should probably clean up the naming. `server-only` is another place where the same concept exists but has a different name.

**Review by gnoff — APPROVED** [review]
yeah the idea was to align it with the condition so it was unambiguous that this file would be used if you used the react-server condition

**Pull request merged**
