### PR TITLE
fix some eslint warnings and update the dep

### PR DESCRIPTION
**Pull request by brianleroux**

### CODE REVIEW

**Comment by brianleroux** [comment]
just "signed" the cla :shipit:

**Comment by zpao** [comment]
Unfortunately right now we can't actually use the latest eslint *quite* yet :( It's actually in much better shape than it was, but we locked to the version we did because it (mostly) happened to support the same set of ES6/JSX features we use (still used esprima-fb at the time). Namely, all of our code parses, which was important. ESlint 0.11 final and 0.12 didn't support many things we needed. 0.13 is actually looking great, though it's still missing rest args (AFAICT looking at docs).

And you can actually see with Travis that not everything is parsing. Even with a couple more options enabled (https://gist.github.com/zpao/8cae06d2428b64f205c8), `ReactClass` still isn't parsing (this is the rest args case).

I think for now we should leave what we have so we can have Travis fail lint accurately. I'm depending on this to help make sure our internal linting mostly matches up and I don't waste too much time with followup commits here (our linting is mostly stricter on GitHub, though there are some rules turned off because of the same parsing reasons).

BUT I do want this as soon as possible (though I'll say we should just put the features in the config in `src/.eslintrc`) and I'll take the incremental lint fixes in the mean time :) (though I kind of want to lose the goo.gl link - the 80 chars rule is silly). Want to drop the eslint upgrade?

**Comment by zpao** [comment]
Going to close this out in favor of #3097. Thanks though @brianleroux!

**Comment by brianleroux** [comment]
:thumbs_up:

**Comment by brianleroux** [comment]
damn. that would've worked for slack!

**Comment by zpao** [comment]
:thumbsup: (no underscore)
tmyk

**Comment by brianleroux** [comment]
katy

(I'll stop now.)

**Pull request closed without merging**
