### PR TITLE
Allow wrap attribute in textarea

### PR DESCRIPTION
**Pull request by jas14**
See #4226

### CODE REVIEW

**Comment by jimfb** [comment]
lgtm, cc @spicyj

**Comment by zpao** [comment]
This should be added to htmlpropertyconfig, not here. @jimfb can you follow up with the details and confirm the testing is done right (look at other PRs for my comments about testing property vs attribute)

**Comment by spicyj** [comment]
Thanks @zpao, I hadn't gotten a chance to look.

**Comment by jas14** [comment]
It seems like this new attribute should be covered by existing generic tests i.e. `renderers/dom/shared/__tests__/ReactDOMComponent-test`.

But since this attribute only has two legal values (`hard` and `soft`) and is specific to `textarea`s, would it make sense to add this as a sort of pass-through property that has to meet the aforementioned invariants before it is set as a DOM attribute?

**Comment by spicyj** [comment]
No, it's fine to just add it to the list of supported properties and not add a unit test, but you should test manually:

Are you able to make a local build and test that this property works correctly? It's important that both the initial render and updating the property work as those exercise different codepaths.

**Comment by jas14** [comment]
Yep, just built successfully and used it to both initially render and update the attribute. I can post the snippet if you want.

**Comment by jimfb** [comment]
It looks like this field can be either a property or an attribute (eg. https://msdn.microsoft.com/en-us/library/ms535152(v=vs.85).aspx), so should we be using `MUST_USE_ATTRIBUTE` or `null` here or does it not matter @spicyj ?

**Comment by spicyj** [comment]
If both work for updates, `null` is best.

**Comment by jimfb** [comment]
@jas14 Let's use `null` unless there is a browser that requires it to be an attribute.  Also, we need to rebase due to merge conflict.  Otherwise, looks good to go.

**Comment by zpao** [comment]
Cool. Can you squash these to a single commit? Then we can merge.

**Comment by zpao** [comment]
Thanks!

**Pull request merged**
