### PR TITLE
[performance] Inline ReactMultiChild.mountChildren

### PR DESCRIPTION
**Pull request by mridgway**
I found that `ReactMultiChild.mountChildren` and the functions it calls were iterating over the children many times. This inlines those calls as it is a critical rendering path. Through testing a chat example I have found about a 10-15% performance gain in `renderToString` using benchmark.js.

Test: https://github.com/mridgway/react-perf/tree/inlineMountChildren
Test results: https://travis-ci.org/mridgway/react-perf/builds/59480548

### CODE REVIEW

**Comment by spicyj** [comment]
For reference, this separation was introduced intentionally in this PR:

https://github.com/facebook/react/pull/2567

cc @sebmarkbage

**Comment by mridgway** [comment]
I seem to have broken the test right before pushing. Will investigate.

**Comment by sebmarkbage** [comment]
Yea, this was intentionally separated, knowing that it is a slight performance loss for now. It is a part of an on-going refactor to separate instantiation and resolution from the render strategy. That way we can reuse core React logic while having the option to optimize for different render outputs (DOM, ART, React Native, etc). It is also easier to reason about fragments (components that render multiple elements) if we can diff the resolved set.

The idea is to move the instantiation out of the DOM component.

It is likely we can remerge this kind of optimization later as more of this refactor starts coming together but I think I'd rather keep it separate for now so that we can incrementally continue the refactor instead of having to make a complete reimplementation from scratch.

This brings up an interesting point though. For renderToString, we don't really need to keep any of the internal state tree which is only used for optimizing updates. Maybe we need a whole optimized pipeline that doesn't generate the internal memoization nor the state tree?

**Comment by mridgway** [comment]
:+1: totally agree @sebmarkbage. I think that would also help with some of the GC issues we're seeing with higher throughput in node. If you can point me in the right direction for where to start with this, I'd be more than glad to work on it.

**Comment by mridgway** [comment]
Looks like there's still a significant gain if we inline only `ReactChildReconciler.instantiateChildren`:

Changes: https://github.com/facebook/react/compare/master...mridgway:inlineInstantiateChildren
Test: https://github.com/mridgway/react-perf/tree/inlineInstantiateChildren
Result: https://travis-ci.org/mridgway/react-perf/builds/59784288

**Comment by spicyj** [comment]
Nice find. Maybe we can take advantage of ReactChildren.map here? We may want a version which skips the ReactFragment.create call for these internals but otherwise I think it should give the right effect.

**Comment by mridgway** [comment]
I pulled the traversal function out into a named functioned rather than inline in the branch above. I will run a comparison of using `ReactChildren.map` vs `traverseAllChildren` directly.

**Comment by mridgway** [comment]
As you said I'm running into a lot of error logs due to `ReactFragment.create` being called with nulls and other invalid arguments. I think sticking with `traverseAllChildren` in this case will be better.

**Comment by spicyj** [comment]
Sorry, I may have been a little unclear. Can you do something like this

```
diff --git a/src/utils/ReactChildren.js b/src/utils/ReactChildren.js
index e470609..84ca357 100644
--- a/src/utils/ReactChildren.js
+++ b/src/utils/ReactChildren.js
@@ -122,7 +122,7 @@ function mapChildren(children, func, context) {
   var traverseContext = MapBookKeeping.getPooled(mapResult, func, context);
   traverseAllChildren(children, mapSingleChildIntoContext, traverseContext);
   MapBookKeeping.release(traverseContext);
-  return ReactFragment.create(mapResult);
+  return mapResult;
 }
 
 function forEachSingleChildDummy(traverseContext, child, name, i) {
@@ -142,7 +142,10 @@ function countChildren(children, context) {
 
 var ReactChildren = {
   forEach: forEachChildren,
-  map: mapChildren,
+  map: function(children, func, context) {
+    return ReactFragment.create(mapChildren(children, func, context));
+  },
+  mapObject: mapChildren,
   count: countChildren
 };
 
```

and then use ReactChildren.mapObject?

**Comment by mridgway** [comment]
Ok, so I create a branch that uses ReactChildren.mapObject: https://github.com/facebook/react/compare/master...mridgway:inlineInstantiateChildrenWithMap

There are two tests that fail using this method:

 * core/__tests__/ReactMultiChildReconcile-test ReactMultiChildReconcile should insert non-empty children in middle where nulls were.
 * core/__tests__/ReactMultiChildText-test ReactMultiChildText should correctly handle all possible children for render and update.

I believe this is because map doesn't handle skipping nulls.

I also ran a benchmark for using `traverseAllChilden` as my per previous comment vs. using `ReactChildren.mapObject` as @spicyj suggested. Running locally, I'm seeing a significant overhead in using the pooling added by `ReactChildren.mapObject`. On some runs it shows to be less performant than not inlining. You can see the travis-ci run of the benchmark here: https://travis-ci.org/mridgway/react-perf/builds/60283471

**Comment by mridgway** [comment]
@sebmarkbage Can you elaborate one what you mean by "internal state tree"? I'm trying to understand what could be removed from the rendering path to optimize server rendering. I have a feeling some of the `mountComponent` logic needs to be split up into rendering logic and other logic (event registration, state management, etc.), but I'm not familiar enough with the "other" logic that's happening to know what to look at.

**Comment by spicyj** [comment]
@mridgway Interesting. If inlining a closure (like https://gist.github.com/spicyj/594910785229dba07d5c) is faster we should probably switch to that – we've tried to avoid closures in favor of manually passing context objects in hopes of lowering GC pressure and improving perf but all of this feels like dogscience.

image

**Comment by spicyj** [comment]
Sorry for all the back and forth.

**Comment by mridgway** [comment]
No worries. I too often feel like I have no idea what I'm doing.

I think using `traverseAllChildren` directly as in https://github.com/facebook/react/compare/master...mridgway:inlineInstantiateChildren addresses your concern about GC although it does duplicate some of the code in `ReactChildren.map`. We do need [this check](https://github.com/facebook/react/compare/master...mridgway:inlineInstantiateChildren#diff-89f33512519fa4d853463913eac8ef04R24) though in order for the tests to pass. Any ideas on introducing that check in to `ReactChildren.map`?

**Comment by spicyj** [comment]
I tried to replicate these results locally and in different browsers. Here's what I did:

```sh
$ git checkout origin/inlineMountChildren
$ npm install -g browserify
$ npm install babelify envify
$ NODE_ENV=production browserify -t babelify bench-chat.js >bundle.js
```

And I created bench.html:

```html
<meta charset="utf-8">
<body style="font: 10px Menlo; white-space: pre;">
<div id="container"></div>
<script>
console.log = function(x) {
  container.textContent += x.replace(/\033\[[0-9;]*m/g, '') + '\n';
};
</script>
<script src="bundle.js"></script>
```

Opening bench.html in Safari (JavaScriptCore) gave me:

```
RenderChat for inputs Optimized x 2,094 ops/sec ±0.85% (66 runs sampled)
RenderChat for inputs Stock x 2,081 ops/sec ±0.78% (66 runs sampled)
The Fastest test suite is RenderChat for inputs Optimized,RenderChat for inputs Stock

+------------+---------------+---------------+
|            â”‚ Optimized     â”‚ Stock         |
+------------+---------------+---------------+
| RenderChat â”‚ 2,094 ops/sec â”‚ 2,081 ops/sec |
+------------+---------------+---------------+
```

where they're the same speed (not sure what's up with the encoding there), and in Chrome I got:

```
RenderChat for inputs Optimized x 1,534 ops/sec ±2.38% (61 runs sampled)
RenderChat for inputs Stock x 1,775 ops/sec ±1.56% (65 runs sampled)
The Fastest test suite is RenderChat for inputs Stock

+------------+---------------+---------------+
|            │ Optimized     │ Stock         |
+------------+---------------+---------------+
| RenderChat │ 1,534 ops/sec │ 1,775 ops/sec |
+------------+---------------+---------------+
```

where the old version is 15% faster. Running `node bench-chat.js` gave me

```
RenderChat for inputs Optimized x 368 ops/sec ±3.18% (73 runs sampled)
RenderChat for inputs Stock x 348 ops/sec ±2.99% (72 runs sampled)
The Fastest test suite is RenderChat for inputs Optimized

+------------+-------------+-------------+
|            │ Optimized   │ Stock       |
+------------+-------------+-------------+
| RenderChat │ 368 ops/sec │ 348 ops/sec |
+------------+-------------+-------------+
```

where your version is maybe 5% faster, but not the 10–15% you were seeing originally. Any ideas if I'm doing something wrong or if this is just wildly different between engines? I'd have expected Chrome and Node to be more similar, at the very least.

**Comment by mridgway** [comment]
Are the symlinks working correctly for you? browserify does not work for me locally to create the bundle.js as you did. I'm not sure why your results are so different from my local tests and travis-ci.

**Comment by mridgway** [comment]
It's also worth noting, that even with two versions of stock flux, the benchmark for the item that is tested first is usually ~5% lower than the second which is why I moved "optimized" as the first test case. Consistency seems to be a consistent problem =/

**Comment by mridgway** [comment]
Here's travis with 10 runs of bench-chat: https://travis-ci.org/mridgway/react-perf/builds/60620846

**Comment by mridgway** [comment]
So it looks like I didn't have the node_modules for each of the apps pushed, so the components may have been using the wrong React. I have pushed the node_modules folder for each app and used symlinks to the react versions such that they are completely isolated. I'm hoping this will make the tests more consistent for you.

https://github.com/mridgway/react-perf/tree/inlineMountChildren

**Comment by mridgway** [comment]
Closing this since it undoes a purposeful refactor. I will open a new PR to discuss inlining just `ReactChildReconciler.instantiateChildren`.

**Pull request closed without merging**
