### PR TITLE
Fix isMounted return true while rendering to string

### PR DESCRIPTION
**Pull request by laskos**
Fix for #5383.

### CODE REVIEW

**Comment by jimfb** [comment]
Explicitly tracking isMounted status seems reasonable to me, but @sebmarkbage or @spicyj should take a look and sanity check.

**Comment by spicyj** [comment]
No, this would be bad for perf. I'm not even really convinced that either return value makes sense in this case. But if we care about fixing this it might be best to go through enough of the unmount process that `_renderedComponent` gets set back to false.

**Comment by jimfb** [comment]
Wouldn't going through the unmount process be even worse for perf?

I think the component is clearly not mounted.  The mount image has been generated but until that mount image gets parsed into the DOM document, but IMO it isn't mounted.  What is your reasoning for neither return value making sense?

**Comment by sebmarkbage** [comment]
Should we just deprecate isMounted already? We generally don't like to be forced to get keep state around for the off chance that someone might want to read it.

**Comment by spicyj** [comment]
Not worse than always adding to the transaction mount-ready queue like this does.

**Comment by laskos** [comment]
Despite I am the author of this PR I am agree with @spicyj  - adding enqueue callback each time we mount component may has huge affect on perf.

There is little sense in calling `unmountComponent` after render to string but it has side effects such as calling `component.componentWillUnmount()` and may has more, that I don't know about. I didn't find any reason (expect this case) to call `componentWillUnmount` conditionally.

**Comment by laskos** [comment]
Can you look on new fix @spicyj ? I know it is little hacky but IMO not more than before, thats why I am agree with @sebmarkbage - this callback should be deprecated. Using lifecycle callbacks is better pattern and will help to preserve bugs like this one. I can make PR for this, if you want.

**Comment by spicyj** [comment]
This is also not good because it relies on the DOM implementation whereas ReactUpdateQueue is used on all platforms (like React Native).

What change are you proposing, sorry? The recommendation was to not use isMounted, which is a change you would make in your own code.

**Comment by laskos** [comment]
> This is also not good because it relies on the DOM implementation whereas ReactUpdateQueue is used on all platforms (like React Native).

It relies on DOM implementation just like isMounted do. What is difference with React Native? Don't you render it into WebKit window anyway? So wrapper still has ownerDocument. Except I am wrong.

> What change are you proposing, sorry? The recommendation was to not use isMounted, which is a change you would make in your own code.

I was meaning about add warring in isMounted, that it is not the best way.

**Comment by jimfb** [comment]
@sebmarkbage I'd be fine with deprecating it (I'm always a fan of removing features).  But it is used an awful lot internally (hundreds of components), which is going to be a beast to codemod away.  Also, we need to make sure there are no legitimate uses of `isMounted()`, though I suppose the workaround is to manually track mounted state.  Probably a good topic for Friday's agenda.

**Comment by spicyj** [comment]
React Native does not use a DOM at all.

**Comment by laskos** [comment]
So indeed - call `unmountComponent` could be only option here. But how to prevent it from calling `componentDidUnmount` without hacks like isStringRendering method arguments etc.?

**Comment by sebmarkbage** [comment]
I think that ultimately the correct solution here is that there shouldn't be an "internal instance" for server rendered components. To do that, we would have to create a separate mount path for them, which we intend to do at some point and in that case.

Actually, they wouldn't even call into ReactUpdateQueue because they would only get ReactNoopUpdateQueue injected.

**Comment by laskos** [comment]
Think about it for while. From isomorphic point of view you mount component to render it. It is not mounted to the DOM but in isomorphic part of code there is no such things. So actually isMounted tells the true - we mount component for while, and we should unmount it after get markup. This is not valid bug for me. And we should (I know you will not agree with me here) call componentDidMount and componentDidUnmount. Client side code should be run only after get `ReactDOM.findDOMNode()`, not after call `componentDidMount` since we support server rendering. I know it is breaking change but it is right way.

**Comment by jimfb** [comment]
@laskos `componentDidMount` means that users are allowed to do things like imperatively add children to their placeholders and perform other dom operations.  It can't be called until after `findDOMNode()` becomes accessible/valid.  Also, unless I'm miss-understanding what you're saying... `ReactDOM.findDOMNode()` doesn't get called by React (it gets called **from** user code, so you can't wait for it to get called before allowing user code to run).

If we're ready to do it, I think the correct solution is to deprecate `isMounted()`, but I suspect that won't get decided until this week's team meeting.

**Comment by laskos** [comment]
@jimfb I mean that user should care about it:

```javascript
class Component extends ReactComponent {
  componentDidMount() {
    var node = ReactDOM.findDOMNode();
    if (node) {
      /// OK we are in browser so we can do crazy stuff with our node
    } else {
      /// Hmmm component is mounted but I can't get my node what does in mean?
      /// Do I run thin on server? Yes it must be it
    }
  }

  componentDidMountIntoDOM() {
      // If such callback would exist then it is clear we are in browser here
  }
}
```

**Comment by jimfb** [comment]
What, in that case, is the purpose if `componentDidMount`?  What would you want to put in there?

**Comment by laskos** [comment]
@jimfb Hm to be honest i wasn't think about it yet. Nothing, I guess. From this point of view (user) calling those callback is useless indeed. But from isomorphic point of view we do mount component. I just cannot find another reason (than get workaround to fix this) to not call componentDidUnmount while unmounting component.

**Comment by laskos** [comment]
Sorry, I was thinking about componentWillUnmount, not componentDidUnmount

**Comment by jimfb** [comment]
It makes no sense to have `componentDidMount` as a lifecycle event before the DOM node is available, unless there is something you would want to do there (I can't think of anything).  This means `componentDidMount` needs to be called after "mounting" into the DOM.  That's effectively what mounting means anyway (the "mount image" has been materialized).

@laskos I think it is incorrect to think that mounting has occurred from an isomorphic perspective.  We have created a "mount image" (a description of what needs to be done to mount) but haven't actually materialized it.  That string could just be thrown away (in which case, it is never mounted anywhere) or the markup/string could be duplicated and sent to a thousand rows of a table (in which case, the image gets mounted into a thousand different places).  From an isomorphic perspective, the "mount image" is rarely materialized into a serialized form (so it skips that phase), but mounting still hasn't happened until the view nodes have been materialized.

@laskos You can't call `componentDidUnmount` (or `componentWillUnmount`) because you didn't call `componentDidMount`, and unmount is often used to cleanup things that were allocated in `componentDidMount`.  Also, componentDidUnmount (or `componentWillUnmount`) means the component lifecycle is done and the component can throw stuff away (when in fact, the lifecycle hasn't even started).

Anyway, the entire discussion is academic if we end up getting rid of `isMounted`, so let's loop back Friday evening.

**Comment by gaearon** [comment]
I’m closing this because we can’t introduce DOM dependencies in `ReactUpdateQueue` as described in https://github.com/facebook/react/pull/5420#issuecomment-155594445, and we plan to get away from `isMounted()` anyway as described in #5465.

Thank you for taking time to contribute and sparking this discussion! This one did not get through but we hope to see more pull requests from you in the future.

**Pull request closed without merging**
