### PR TITLE
Remove unused bundles

### PR DESCRIPTION
**Pull request by rickhanlonii**
## Summary

This PR splits the www bundles into modern and classic and then removes the unused combinations.

See commits for the three included changes.

## Test Plan

- Run the sync before/after to confirm all the correct files are output.

### CODE REVIEW

**Comment by rickhanlonii** [comment]
Oops, I meant to publish this as a draft until I'm done testing the changes.

**Comment by acdlite** [comment]
Another way to do this is to add a `releaseChannels` option to the bundle config:

```js
  /******* React DOM *******/
  {
    bundleTypes: [
      UMD_DEV,
      UMD_PROD,
      UMD_PROFILING,
      NODE_DEV,
      NODE_PROD,
      NODE_PROFILING,
      FB_WWW_DEV,
      FB_WWW_PROD,
      FB_WWW_PROFILING,
    ],
    releaseChannels: [OSS_EXPERIMENTAL, OSS_STABLE, FB_MODERN, FB_STABLE],
    moduleType: RENDERER,
    entry: 'react-dom',
    global: 'ReactDOM',
    externals: ['react'],
  },
```

The distinction is, `bundleType` is about output format. UMD, CJS, Haste, ESM, and so on.

Whereas `releaseChannels` is purely about which features are enabled.

I think that's a better conceptual match for our build dimensions.

**Comment by rickhanlonii** [comment]
I went that route initially but the combinations didn't make sense. E.g. what's an example of a `NODE_DEV`, `FB_MODERN` combination? Would you keep FB_WWW as a bundle type? How would you exclude `ReactDOMServer-dev.modern.js` while keeping `ReactDOMServer-prod.modern.js` and `ReactDOMServer-dev.classic.js`? It may match more conceptually but without rewriting the entire config, I think it makes it harder to reason about what will be output based on a given config.

**Comment by rickhanlonii** [comment]
Interestingly, I'm now making the same argument @sebmarkbage was making against the test-cli options. I think the difference there is in the test CLI we can still list common combinations and if you use invalid combinations, we can show warnings. But in this config, you want to minimize the mental grepping you need to do to know what's being bundled.

**Comment by acdlite** [comment]
> How would you exclude ReactDOMServer-dev.modern.js while keeping ReactDOMServer-prod.modern.js and ReactDOMServer-dev.classic.js

Is that actually a valid use case?

A more realistic case that I think illustrates your point is that there's no such thing as a bundle that's both `OSS_EXPERIMENTAL` and `FB_WWW_PROD`. But I think that's fine; we'd just won't output combinations that don't make sense, like you already do here: https://github.com/facebook/react/pull/20369/files#diff-f05e9513ea1c7e83c66f63dc3a7a2e1d464c58c7beebe1c375a2845caa6b0bc4R776-R780

> It may match more conceptually but without rewriting the entire config, I think it makes it harder to reason about what will be output based on a given config.

I agree that it's a bit harder to predict the final bundles — nothing's easier than listing out every single one in a flat list — but it makes the implementation harder to maintain,  and encourages weird ad hoc workarounds like this `isFBBundle` check:

https://github.com/facebook/react/blob/504222dcd21c7ac43eb78df11226bab47ec03bb0/scripts/rollup/build.js#L545-L558

That could check the release channel instead.

**Comment by rickhanlonii** [comment]
There's a new problem where many of the files that we are skipping now have build tests that run on them, so it looks like we need to build them anyway? @acdlite should we bail out of this strategy and just add a filter to the sync?

**Comment by rickhanlonii** [comment]
> Is that actually a valid use case?

Yes, that's currently a file that needs to be removed while keeping the others.

**Comment by acdlite** [comment]
> Yes, that's currently a file that needs to be removed while keeping the others.

CircleCI has a "matrix builds" feature that lets you exclude certain combinations. https://circleci.com/docs/2.0/configuration-reference/#excluding-sets-of-parameters-from-a-matrix.  I suppose we could do something similar.

I do like the explicitness of listing out every combination for every bundle. (I can't even remember what the `moduleType` option means :D)

But I guess I was hoping that this would be as small a change as possible, given that our build script is so complex already.

> should we bail out of this strategy and just add a filter to the sync?

Yeah probably. Getting too bikesheddy. One day we'll redo this whole pipeline from scratch and we can make it better then.

**Comment by rickhanlonii** [comment]
Yeah, agreed. Re: complexity - one reason I liked this approach more is that the _implementation_ was cleaner even though there's more bundle config. There's effectively [three lines that change](https://github.com/facebook/react/pull/20369/files#diff-f05e9513ea1c7e83c66f63dc3a7a2e1d464c58c7beebe1c375a2845caa6b0bc4R776) in the actual build script (I hear you though).

**Comment by rickhanlonii** [comment]
I should be able to land most of the first commit without any issue, let me update.

**Comment by sebmarkbage** [comment]
fwiw. I really like this change because it lists out every combination. It's so easy to understand.

The combinatorial thing makes you think about combinations that don't make sense.

**Comment by sebmarkbage** [comment]
The RELEASE_CHANNEL flag makes most sense for open source. EXPERIMENTAL != MODERN and that keeps tripping me up. Especially for esoteric things like the Webpack plugin. I'm also not sure it actually works for those. Like what happens if we publish the Webpack package today in experimental? What tag will it get?

**Comment by acdlite** [comment]
Yeah I like the API of listing out every combination; I just don’t like how scattershot the implementation is later when we infer things about the underlying dimensions. It’d be cool we if we that in one place, immediately when we consume the bundle. Best of both worlds.

**Comment by acdlite** [comment]
The experimental !== modern thing is a separate issue that this doesn’t address. Our `@gate experimental` check is subtly wrong for the same reason.

**Comment by rickhanlonii** [comment]
I think it does apply here because they way you build modern is with `RELEASE_CHANNEL=experimental yarn build` (which happens to be the default).

**Comment by acdlite** [comment]
@rickhanlonii I always just download from CI so I don't really care about the CLI

**Comment by rickhanlonii** [comment]
Yeah, I was talking about the implementation treating EXPERIMENTAL == MODERN. E.g. in the sync script we first run with the "stable" channel to build `classic`, then we run "experimental" to build `modern` or that the build.js script there are only two release channels: stable and experimental. Or that the build doesn't output classic or modern files, those file names are created in the sync script. Things like that.

Maybe that's different than what @sebmarkbage was getting tripped up by.

**Comment by rickhanlonii** [comment]
Closing because we filter these out in the sync instead.

**Pull request closed without merging**
