### PR TITLE
change tutorial script (success & error is deprecated )

### PR DESCRIPTION
**Pull request by hideokamoto**
tutorial script included following jQuery script
- success()
- error()

There are deprecated in jQuery 1.8, so I replaced them.
- success() -> done()
- error() -> fail()

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by hideokamoto** [comment]
OK.
Now I have registered my account at https://code.facebook.com/cla.

Thanks!

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by zpao** [comment]
`success` and `error` properties are not deprecated, only the methods (`$.ajax().success()`). `done` and `fail` as methods replace those but the use of them as properties actually doesn't work, so the code you have here isn't correct. I appreciate you taking the time though and especially for updating all the code in the translations as well!

**Pull request closed without merging**
