### PR TITLE
[Fizz] Expose maxBoundarySize as an option

### PR DESCRIPTION
**Pull request by sebmarkbage**
Bike shed now or forever hold your peace.

### CODE REVIEW

**Comment by gaearon** [comment]
This applies to content only, right? E.g. if fallback is longer we still have to emit it. So the size is not really of the boundary itself but its primary content. Is that right?

**Comment by gaearon** [comment]
How about `maxContentLength`?

**Comment by sebmarkbage** [comment]
The implementation is not really correct now because it's shallow. So if you include many small boundaries, it will never break it up. My original heuristic measured the parent instead but had to abandon that for some reason. I think the real heuristic needs to be an accumulation that includes previous siblings. So that it writes until the next boundary would exceed the threshold. Similarly a SuspenseList should stop at some point even if it only has small boundaries for each item.

So it's really about the parent boundary's max size at that point. It won't be exactly capped below that number but roughly.

I suspect this option might change implementation details given the various ways it's possible to do this so I wouldn't over focus on the exact details. The number indicates roughly how much HTML you can transfer, layout and render in a meaningful window (likely 500ms since that's what the train model uses).

**Review by gaearon — APPROVED** [review]
I feel like it's hard to name until we know more precisely how we end up using it.

**Comment by sebmarkbage** [comment]
I added a qualified guess for the initial default value to try. We'll need to get more data on this from non-FB sources.

>> This is a default heuristic for how to split up the HTML content into progressive
>> loading. Our goal is to be able to display additional new content about every 500ms.
>> Faster than that is unnecessary and should be throttled on the client. It also
>> adds unnecessary overhead to do more splits. We don't know if it's a higher or lower
>> end device but higher end suffer less from the overhead than lower end does from
>> not getting small enough pieces. We error on the side of low end.
>> We base this on low end 3G speeds which is about 500kbits per second. We assume
>> that there can be a reasonable drop off from max bandwidth which leaves you with
>> as little as 80%. We can receive half of that each 500ms - at best. In practice,
>> a little bandwidth is lost to processing and contention - e.g. CSS and images that
>> are downloaded along with the main content. So we estimate about half of that to be
>> the lower end throughput. In other words, we expect that you can at least show
>> about 12.5kb of content per 500ms. Not counting starting latency for the first
>> paint.

**Comment by sebmarkbage** [comment]
RFC: `progressiveChunkSize`

**Comment by gaearon** [comment]
Like

**Pull request merged**
