### PR TITLE
Temporarily comment out bundle-collapser for JSXTransformer

### PR DESCRIPTION
**Pull request by chenglou**
This will at least make the examples run while we fix the issue.

### CODE REVIEW

**Comment by chenglou** [comment]
https://github.com/facebook/react/commit/9bc19619366cb6e876bf14dc6bee038ddb6f6b86#commitcomment-9349605

@zpao (not sure how to ping ShihChi)

**Comment by chenglou** [comment]
Also, all the examples requiring `*.min` throw a big red error in the console for the lack of source maps. Kinda ugly.

**Comment by zpao** [comment]
OK figured out *why* this is happening. There's a caught error when using amdefine, which is used by source-map-generator (and others) to make a browser compatible package. Anyway, inside amdefine, it looks at the type of the argument. If it's a string, it treats it like a regular synchronous require. If it's not a string it assumes the argument is an array of strings, so it uses `dep.map`, which throws because `dep` is the number 10. Specifically, see https://github.com/jrburke/amdefine/blob/master/amdefine.js#L110-L126

So yea, we can't use bundle-collapser here. Hopefully it doesn't randomly break in the future.

Alternatively we could update bundle-collapser to use `'10'` instead of `10` for the module identifiers which would sneakily get around the bug. Or also update the source-map-* tools to not use amdefine (might be good *anyway*).

Can you update the comment there to mention the restriction being amdefine, which is a dependency of a dependency. Then let's merge it in.

Nice catch all around, by the way. We probably would have found it but it would have been the day before a release.

**Comment by chenglou** [comment]
:+1:

**Comment by zpao** [comment]
Thanks!

**Pull request merged**
