### PR TITLE
Add case typo catching for prop types

### PR DESCRIPTION
**Pull request by pranaygp**
We currently don't warn for properties that don't exist in the propTypes set. I.e. we don't catch typos.

This is an attempt at fixing that (This issue is at #6153)

### CODE REVIEW

**Comment by Aweary** [comment]
Thanks for the PR @pranaygp. We do have two other PRs open for this right now https://github.com/facebook/react/pull/6938 and https://github.com/facebook/react/pull/6255 that I'd like to give a chance, though there hasn't been a lot of movement on those recently.

@gaearon looks like you've reviewed the other PRs before, could you take a look at them again when you get a chance to see if we still want to make this change, which PR we should accept, and what changes needed to be made?

**Comment by pranaygp** [comment]
@Aweary that makes sense. I wasn't aware of those PRs since they didn't reference the issue in question ( #6153)

If there is something fundamental that needs to be implemented before this (or the other PRs) get merged, I'm happy to get on it.

Till then, I'll hunt for other issues I can work on.

**Comment by aweary** [comment]
@pranaygp just a quick status update for you. I closed https://github.com/facebook/react/pull/6255 since the author's account no longer exists. https://github.com/facebook/react/pull/6938 was still opened a few months before this PR so I'd like to see if I can get that one merged. If not, we can work with you here to get this one merged 👍

**Comment by pranaygp** [comment]
@aweary Awesome. Happy to continue working on merging this if you so need me to :)

**Comment by aweary** [comment]
PropTypes have been removed from React core and now exist as a separate package `prop-types`. Any future feature requests, bug reports, or changes should be directed to the new repo at https://github.com/reactjs/prop-types.


Sorry about that @pranaygp!

**Pull request closed without merging**
