### PR TITLE
Support document rendering

### PR DESCRIPTION
**Pull request by gnoff**
## Hydrating into Document
This PR addressed the most fundamental issue identified in #22833. In that issue a hydration mismatch when hydrating into the Document caused a broken application because the client rendered fallback could not append any content to the Document.

This is caused by the fact that a Document can only have 1 element at a time, namely the documentElement which is usually `<html>` and by not removing it beforehand the append of a new `<html>` element fails.

Initially I looked into recycling the documentElement so it is never removed or appended but just moved around to whatever fiber needs it, staying in the Document tree as its root. This worked fine but added some code on hot paths and a bit of size.

I then looked at what would happen if we simply removed the documentElement (i.e. treat it like any other Element) and in Chrome, Safari, and Firefox (modern versions) there seems to be no issue with this. This PR is much smaller and simply updates `clearContainer` to properly clear the Document as a container so that a later appendChild of an `<html>` element will not violation Document invariants

### Hydration into Document compatibility with 3rd party scripts and Extensions

The original issue shows an extension breaking a React application. This PR does not introduce compatibility with extensions or 3rd party scripts that modify the DOM before React hydrates, it simply inverts what gets broken. This change would result in (worst case) React breaking the extension rather than the extension breaking React.

## createRoot for Document
as a consequence of the fix for hydration in Document using Document as a root should work now. This PR also adds back types for using createRoot on Document. It should be noted that doing so will effectively wipe out the entire document so third party styles and other DOM elements created by server response, 3rd party scripts, or extensions will be dropped. This is probably not that useful a feature but since it is supported by implementation with no special casing I added back in

### CODE REVIEW

**Review by sebmarkbage — APPROVED** [review]

**Comment by eps1lon** [comment]
> This PR addressed the most fundamental issue identified in https://github.com/facebook/react/issues/22833.

Does this PR actually fix https://github.com/facebook/react/issues/22833?

**Comment by gnoff** [comment]
> > This PR addressed the most fundamental issue identified in #22833.
> 
> Does this PR actually fix #22833?

Yes, https://codesandbox.io/s/react-18-hydration-mismatch-in-document-fixed-24523-9n6zos?file=/package.json

There are hydration errors but the issue of unmounting the entire app is fixed. The hydration errors are expected if I understand the test case correctly

**Comment by CanRau** [comment]
Any eta on when this will be shipped?

**Comment by ZipBrandon** [comment]
Looking to check on an updated timeline estimate for this and 18.2? This PR resolves issues that I experience with SSR, but other libraries which mark React as a peer dependency are upset when I am having to `npm i --force` the `next` for react and react-dom.  The sub-packages end up installing their own React dependencies which leads to the Rules of Hooks being broken (like https://github.com/plouc/nivo/blob/master/packages/bar/package.json) which I have to subsequently remove from its `node_modules`.

**Comment by gaearon** [comment]
You can use Yarn `resolutions` or npm `overrides` to force "deep" packages to use the same version, as far as I know.

**Pull request merged**
