### PR TITLE
[Fizz] implement renderToReadableStream for Node

### PR DESCRIPTION
**Pull request by gnoff**
This is the first PR in a series that will add the webstream APIs such as `rendertToReadableStream` and `createFromReadableStream` to the Node builds. To avoid adding any runtime overhead this is implemented using a separate build and combined together much like how the legacy APIs are implemented. This first PR implements `renderToReadableStream` for Fizz. Later PRs will implement `renderToReadableStream` for Flight Server and `createFromReadableStream` for Flight Client.

### CODE REVIEW

**Comment by dai-shi** [comment]
Hi, just curious which you recommend web stream or node stream in node, in general or for specific cases.

**Comment by gnoff** [comment]
Node streams should be better performing so generally we won’t recommend these. There can be reasons though to maybe use this if you are writing code that you want to be runnable in node and in other runtimes. For maximum perf though best bet is to implement the node specific apis if they are available

**Comment by marbemac** [comment]
@gnoff curious, why'd you end up closing this? IMHO, with everybody seemingly converging on the web stream standard (including node since v16 or so), including `renderToReadableStream ` in the node build makes a ton of sense.

> There can be reasons though to maybe use this if you are writing code that you want to be runnable in node and in other runtimes

100% - and for local dev vs prod. Often local dev is done w node runtime, while final product is deployed to some edge provider.

**Comment by krutoo** [comment]
> Node streams should be better performing

@gnoff How we can check this when npm packages of react dont provide functions for both of stream types?

**Comment by krutoo** [comment]
@gnoff Can we add typings for `react-dom/server.edge` as it is done here?

https://github.com/redwoodjs/redwood/pull/10284

**Comment by asleepace** [comment]
@gnoff is there a better way to import this in Bun?

Screenshot 2024-04-27 at 6 39 39 PM

**Pull request closed without merging**
