### PR TITLE
Non-element option children test

### PR DESCRIPTION
**Pull request by jfo84**
Hey @gaearon, I produced a failing test case for your comment. The test fails on dev and passes on prod. I wasn't sure about the logic for avoiding the warning and would love some pointers. Thanks

### CODE REVIEW

**Comment by gaearon** [comment]
Why does it throw? I wouldn’t expect it to throw because it renders an element — not just any object. I would expect it to throw for something like `{}` inside children.

**Comment by gaearon** [comment]
Regarding the original TODO, given a non-element object (unlike your test) I’d expect them all to throw. The issue is more that PROD hydration doesn’t. DEV hydration is consistent with both DEV and PROD client and server render because they also throw.

**Comment by gaearon** [comment]
In your test it fails due to a missing warning assertions. Not for the reason you’re thinking.

**Comment by jfo84** [comment]
Got it. I'll take a look this week.

**Pull request closed without merging**
