### PR TITLE
Don't warn when style value is '0'

### PR DESCRIPTION
**Pull request by zpao**
This reverts #6458 and then implements the goal of that PR without affecting the output.

While I agree that #6458 is "safe", it's a subtle behavior change in the generated output and I think we shouldn't take it in the branch. In `master` we should make the change to stop appending `px` to all strings (not just `'0'`).

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
@zpao updated the pull request.

**Comment by gaearon** [comment]
LGMT

**Comment by gaearon** [comment]
(I believe you’ll need #6458 when cherry-picking this though?
)

**Comment by zpao** [comment]
> (I believe you’ll need #6458 when cherry-picking this though?)

I'll special case this and cherry-pick just the 2nd commit here instead of landing and reverting.

**Pull request merged**
