### PR TITLE
Added component stack to contentEditable warning

### LINKED ISSUE #8497: Add component stack to the contentEditable warning
*feature*

>Warning: A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional.

It would help heaps if I would know _which_ component is causing this.

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
In ref to #8497 I've added the componentStack to the contentEditable warning message. Update test suite and all tests pass. Closes #8497

### CODE REVIEW

**Comment by gaearon** [comment]
Please run `npm run prettier` and commit. Thanks!

**Comment by Ethan-Arrowood** [comment]
screen shot 2017-10-06 at 3 12 55 pm
There seems to be no changed files.

**Comment by gaearon** [comment]
Odd. Can you maybe run `yarn` first? Maybe exact version difference.

**Comment by Ethan-Arrowood** [comment]
screen shot 2017-10-06 at 6 39 01 pm

Really odd

**Comment by Ethan-Arrowood** [comment]
Okay I did a clean install of `node_modules` and it seemed to fix it. Pushed prettified files.

**Comment by gaearon** [comment]
Can you press on the red cross icon and check why it failed?

**Comment by Ethan-Arrowood** [comment]
screen shot 2017-10-07 at 5 53 57 pm
Looks like prettier is still causing the issue.

**Comment by gaearon** [comment]
Looks like unrelated commits got here. Maybe easier to start another branch and cherry pick your commits?

**Comment by Ethan-Arrowood** [comment]
Yeah this was my mistake. I tried to rebase my master branch forgetting that this PR came off of that (which was another mistake in itself).

**Comment by Ethan-Arrowood** [comment]
@gaearon I'm still trying to master Github so before I completely ruin things I want to run my thought process by you.

1. Reset local master branch to remote master branch
2. Create new branch
3. Cherry pick commits to new branch
4. Close this PR
5. Open a new PR from the new branch
6. Commit and push additional changes to new branch

**Comment by gaearon** [comment]
That sounds like the way to go.

**Comment by Ethan-Arrowood** [comment]
@gaearon I've created a new PR https://github.com/facebook/react/pull/11208

**Pull request closed without merging**
