### PR TITLE
chore: Add document is null check in invariant

### PR DESCRIPTION
**Pull request by zombieJ**
## Summary

In jest, when a test is ended, it will make document as `null` instead of `undefined`. So the invariant of `typeof document !== 'undefined'` will miss the case of `null`.

## Test Plan

Update `ReactDOM-test.js` for `null` case.

### CODE REVIEW

**Comment by zombieJ** [comment]
hi @acdlite, could you pls take a look? thanks~

**Comment by zombieJ** [comment]
cc @bvaughn

**Review by rheh — APPROVED** [review]

**Comment by zombieJ** [comment]
cc @gaearon

**Comment by zombieJ** [comment]
cc @rickhanlonii

**Comment by zombieJ** [comment]
cc @sebmarkbage

**Comment by zombieJ** [comment]
@acdlite @bvaughn  @gaearon   @rickhanlonii    @sebmarkbage

**Comment by bvaughn** [comment]
@zombieJ Don't spam mentions. There are a lot of PRs waiting for review. The team will review them when we get the opportunity.

**Comment by zombieJ** [comment]
> @zombieJ Don't spam mentions. There are a lot of PRs waiting for review. The team will review them when we get the opportunity.

Thanks for reply.

**Comment by zombieJ** [comment]
Hi @bvaughn,
This PR has passed month no processed. Seems recently days many PR have been merged. What should I do next?

**Comment by rickhanlonii** [comment]
Hey @zombieJ, thanks for the suggestion and I'm super sorry for the delay.

The real issue here is that this code is firing after jest has torn down the environment at all. To fix the core issue, we've created https://github.com/facebook/react/pull/20915, but that's a breaking change so we've  been waiting until we're ready for the next release to land it.

**Pull request closed without merging**
