### PR TITLE
ReactMultiChildText-test.js fix __html typo

### PR DESCRIPTION
**Pull request by murashki**

### CODE REVIEW

**Comment by zpao** [comment]
Good catch. Luckily it doesn't matter for the error we're expecting :)

**Comment by murashki** [comment]
) I don't think so. Code under the `expect` was guaranteed throwing cause of typo, thus test was always passed. So this test could hide an error we need to know about.

Thanks for React! It's amazing :+1:

**Comment by zpao** [comment]
In this case it's ok and we throw the same error either way. [The code that throws](https://github.com/facebook/react/blob/master/src/browser/ui/ReactDOMComponent.js#L108-L112) only looks to see if `dangerouslySetInnerHTML` is non-null and children were also specified.

Definitely true that this typo could have masked an error if we change some code though. That's generally why I think it's a good a idea to specify the error message we expect to be thrown :)

**Comment by murashki** [comment]
Thanks.
Please, could you explain the reason of the double underline in `__htlm`? Why not `htlm`? It's look... little strangely.

**Comment by zpao** [comment]
We've explained it a few times. It's to make sure it's nice and awkward and
intentional so when you use it, it's annoying you clear that you're
breaking out of the nice box React provides. There are a couple open
discussions about changing it.

**Comment by murashki** [comment]
Thanks!

**Pull request merged**
