### PR TITLE
Add yarn build --unsafe-partial

### PR DESCRIPTION
**Pull request by gaearon**
We normally delete the `build` folder when rebuilding for consistency. This can be annoying if I make a tiny scoped edit to a particular package. This is an escape hatch so I can iterate faster when I know what I'm doing.

### CODE REVIEW

**Comment by gaearon** [comment]
You think so? I actually like the entry point granularity.

**Comment by bvaughn** [comment]
The case I'd like to avoid is one of us testing an outdated/unrealistic local `node_module` (with stuff left over in the package from a previous build).

So e.g.
```
yarn build -- react,react-dom --type=NODE      
```

I think it would be safer to start with
```
 rm -rf build/node_modules/react
 rm -rf build/node_modules/react-dom
```

**Comment by gaearon** [comment]
Maybe I'll rename to `partial-dangerous`? I really don't intend this to be used widely. Only for cases where you're debugging why some prod test is failing or similar.

**Comment by gaearon** [comment]
Changed to `unsafe-partial`.

**Pull request merged**
