### PR TITLE
Fix some typos in README.md

### PR DESCRIPTION
**Pull request by Himanshunitrr**

### CODE REVIEW

**Comment by Himanshunitrr** [comment]
What should I do for Facebook CLA Check?

**Comment by Himanshunitrr** [comment]
I signed for https://code.facebook.com/cla

**Comment by bvaughn** [comment]
The removal of this comment seems like a pretty subjective change.

**Comment by Himanshunitrr** [comment]
Should I close this PR ?

**Comment by bvaughn** [comment]
Sorry, I was out for the day (weekend)

Thanls for being so understanding 🙇

**Pull request closed without merging**
