### PR TITLE
Warn about Infinity in style value

### PR DESCRIPTION
**Pull request by vitalets**
Currently React warns about `NaN` values in style. 
This PR adds warnings about `Infinity`:
```jsx
<h1 style={{ fontSize: 1 / 0 }}></h1>
```
Warning:
```
Warning: `Infinity` is an invalid value for the `fontSize` css style property.

### CODE REVIEW

**Comment by aweary** [comment]
cc @spicyj are we OK with adding this new warning?

**Comment by gaearon** [comment]
I’ve made this mistake a few times. IMO let’s merge it. Worst case scenario somebody will explain the reasoning, we’ll revert and learn 😄

**Comment by syranide** [comment]
Just FYI. The reason we warn for `NaN` is because it breaks comparison checks, not because of the value itself. Not saying it's a bad idea though.

**Comment by gaearon** [comment]
Sorry for the churn—can you please rebase this?

@aweary If you approve something, feel free to merge. We can always revert later. Otherwise things get stale.

**Comment by aweary** [comment]
Sorry about that, I went ahead and rebased it myself. Thanks again @vitalets!

**Comment by vitalets** [comment]
Thank you @aweary !

**Pull request merged**
