### PR TITLE
Rename ReactTypeOfWork to ReactWorkTags, ReactTypeOfSideEffect to ReactSideEffectTags

### PR DESCRIPTION
**Pull request by sophiebits**
And `type TypeOfWork` to `type WorkTag` and `type TypeOfSideEffect` to `type SideEffectTag`.

### CODE REVIEW

**Comment by sophiebits** [comment]
This is more consistent in naming, right?

**Comment by gaearon** [comment]
`ReactTypeOfSideEffect` too?

**Comment by ryota-murakami** [comment]
`ReactWorkType` `ReactSideEffectType` are feels strange?

**Comment by sebmarkbage** [comment]
You have some test failures but seems fine. I’m also for renaming anything that may cause deep linking issues.

**Comment by gaearon** [comment]
Deep linking? We have flat bundles.

**Pull request merged**
