### PR TITLE
Add key validation to React.Children.toArray

### PR DESCRIPTION
**Pull request by clemmy**
Addresses https://github.com/facebook/react/issues/11549

This warns only on React.Children.toArray. I don't think the other children helper methods (`forEach`, `map`, and `count`) are dangerous.

### CODE REVIEW

**Comment by gaearon** [comment]
What's the rollout plan? Just enabling this is going to be painful for everyone who's intentionally using to suppress the key warning.

**Comment by aweary** [comment]
>I don't think the other children helper methods (forEach, map, and count) are dangerous.

It looks like [`map` can also be used to skip key validation](https://jsfiddle.net/Aweary/8korna1m/) since it also uses `mapIntoWithKeyPrefixInternal`

**Comment by clemmy** [comment]
@aweary Hmm, I imagined there would be a use case where `.map` is used to add keys to a child, but on second thought, that seems super awkward as you'd have to do something like:
```js
React.Children.map(children, (child) => { <Child {...child.props} key={} /> })
```

**Comment by clemmy** [comment]
@gaearon Add keys or use JSX fragments! Outside of that, they might just have to deal with the fact  that since they're doing something weird, we're going to warn them.

**Comment by gaearon** [comment]
Have you tried this on www and assessed how many new warnings this will cause?

**Comment by gaearon** [comment]
I'll close because it's a bit stale and also needs somebody to assess the number of new warnings at FB, but @clemmy's internship has ended. Maybe we'll revisit this some time in the future. I'll keep the issue open.

**Pull request closed without merging**
