### PR TITLE
Test with AppVeyor with Node 11 and 12

### PR DESCRIPTION
**Pull request by Saibamen**
Test with Node 11 and 12

### CODE REVIEW

**Comment by hang-yoko-tran** [comment]
s

**Comment by Saibamen** [comment]
> 
> 
> s

s?

**Comment by threepointone** [comment]
Hi! What is the purpose and motivation for this change? What does it do, or why is it useful?

**Comment by Saibamen** [comment]
We need to test it with recent NodeJS LTS version: https://nodejs.org/en/download/

**Comment by Saibamen** [comment]
> It usually works

Usually ;)
So we should test with latest LTS version of NodeJS in CI

**Comment by acdlite** [comment]
Can we replace AppVeyor with a CircleCI workflow instead? My understanding is that we only use AppVeyor because CircleCI used to not support Windows. But now it does: https://circleci.com/blog/windows-general-availability-announcement/

**Comment by Saibamen** [comment]
ping

**Pull request closed without merging**
