### PR TITLE
document checkbox using click handlers for change events

### PR DESCRIPTION
**Pull request by WickyNilliams**
I had an issue related to this earlier today. Feels like a short paragraph warning of potential pitfalls would be of benefit to others who might hit this issue. Discussed with @zpao on IRC, agreed to make PR.

For more info:
* https://github.com/facebook/react/issues/3005#issuecomment-72513965
* https://github.com/facebook/react/blob/c7e4f55eb061b578497ed316d3e9e0dfa7026f46/src/browser/eventPlugins/ChangeEventPlugin.js#L287

### CODE REVIEW

**Comment by CodyReichert** [comment]
This would be really nice note to have in the documentation, I was wondering my checkbox wasn't updating and scouring the forms page to see what I was doing wrong. It should be self explanatory, but I'm sure others have had the same problem.

**Comment by spicyj** [comment]
Hmm. I must be tired because I'm not fully understanding the issue, but maybe we should just fix this?

**Comment by CodyReichert** [comment]
In a nutshell, using `preventDefault` in a checkbox onChange handler keeps the checkboxes from visually updating because react actually uses the event (for radios also i believe). But as @zpao said in another thread, if you don't have a good reason for using `preventDefault` just don't. In my case I was just lazily copying code and didn't really think twice, but probably would have spotted that note in the docs.

I haven't dug into the react source enough to know if there's actually something to 'fix'. It sounds like the reason for that behavior is browser compatibility.

**Comment by spicyj** [comment]
Thanks @WickyNilliams and @benglass!

**Comment by WickyNilliams** [comment]
Forgot I'd ever made this PR :) thanks for merging

**Pull request merged**
