### PR TITLE
Improve formatting of errors when building

### LINKED ISSUE #11454: Improve formatting of errors when building React
Currently when the build fails (e.g. due to a missing named export), the message is pretty ugly:

screen shot 2017-11-04 at 13 12 31

It would be nice to display the relevant line inline with syntax highlighting, sort of like Babel does it. Maybe Babel's `babel-code-frame` could be helpful (not sure).

To reproduce, fail the build by removing some `export` somewhere and run `yarn build`. (Tip: `yarn build core --type=NODE_DEV` is the fastest way to build just `packages/react/*` and that might be enough to reproduce and iterate on the error message.)

The relevant logic for displaying build errors is probably somewhere in `scripts/rollup/build.js`.

**If you'd like to work on this please comment here, so we don't have many people working on the same thing.**

### PR DESCRIPTION
**Pull request by misoguy**
Fix #11454 
I don't know the history behind using `error.codeFrame` in `catch()`
but it seems that rollup is providing with the formatted lines inside `error.frame` instead of `error.codeFrame`
What I could find so far about rollup's `error.frame` is [here](https://github.com/rollup/rollup/blob/b949eb08169115ff66648838cbc4833379bf9440/src/Module.js#L296)
and the related `getCodeFrame` [here](https://github.com/rollup/rollup/blob/219f1f13da6fef63aec621f2d4eca56cffc3fee0/src/utils/getCodeFrame.js#L12)

### CODE REVIEW

**Comment by gaearon** [comment]
Can you add a screenshot?

**Comment by misoguy** [comment]
Sure this is the snapshot
image

**Comment by gaearon** [comment]
It would be nice to get some syntax highlighting for this. Babel does it.

**Comment by misoguy** [comment]
Could you add a screenshot of babel's syntax highlighting? To make sure we are on the same page :)

**Comment by misoguy** [comment]
I'm guessing it's something like this?
image

**Comment by gaearon** [comment]
Yes! And it would be nice to remove `undefined` from the header (when it's `undefined`).

**Comment by gaearon** [comment]
Do you plan to finish this with the syntax highlighting?

**Comment by misoguy** [comment]
I would like to finish this with the syntax highlighting but there seems to be an [issue](https://github.com/rollup/rollup/issues/1697) with rollup's `error` object.
It seems that the [`error.frame`](https://github.com/facebook/react/pull/11456/commits/396b7a11ee5b92578889b82056e216dca593c920#diff-c5453c501251b48888b4a9b15ff55ae1R606) used in this PR which has the error code frame without syntax highlighting also shows wrong line numbers.
The screenshot [above](https://github.com/facebook/react/pull/11456#issuecomment-341940239) shows that the error line is 13 while on the real file the error is on line 12.
I'm looking into rollup's issue regarding this problem but not sure when I can get a fix for it.

Would it be ok to leave this PR open in the mean time?
or should it be merged or closed for a new PR?

**Comment by gaearon** [comment]
Sure let's keep it open.

**Comment by misoguy** [comment]
I have a PR open for the issue I mentioned about rollup's `error` object. https://github.com/rollup/rollup/pull/1728
Hopefully it will be merged and released so that I can get back on track with the syntax highlighting 😄

**Comment by misoguy** [comment]
@gaearon `rollup` has been released with my PR merged.
Therefore I have upgraded `rollup` dependency and added `babel-code-frame` to finish up with syntax highlighting properly as below 😄 
image

**Comment by gaearon** [comment]
Can you please send a separate PR for updating Rollup first? Since it may not be obvious from from commit log and it's a substantial change.

Please also run `yarn build` to record build sizes before and after the change. (As separate commits.) This would tell us if Rollup update accidentally regresses on bundle sizes.

**Comment by misoguy** [comment]
@gaearon I have sent a separate PR for updating rollup via #11591. I'll rebase this PR to the updated commit once it is merged.

**Comment by misoguy** [comment]
Finished up this PR by removing rollup upgrade and merging master branch

**Comment by gaearon** [comment]
CI fails?

**Comment by misoguy** [comment]
Didn't run yarn prettier 😞  Fixed it now.

**Comment by gaearon** [comment]
Thanks! This is great.

**Comment by gaearon** [comment]
It seems like there's an issue in case the error is a syntax error from Babel. Then `error.loc.file` is missing, and `loc` reports the wrong line number anyway.

**Comment by gaearon** [comment]
I fixed with 018276976.

**Pull request merged**
