### PR TITLE
Cleaned up a few names in the reconciler.

### PR DESCRIPTION
**Pull request by jimfb**
Cleaned up a few names in the reconciler.

### CODE REVIEW

**Comment by spicyj** [comment]
Can we be consistent between ChildElements and ChildrenElements if you're changing them instead of introducing both? I prefer the former since it's shorter. Note that we do use the term "node" to mean element or collection of elements though.

**Comment by jimfb** [comment]
@spicyj Updated for consistency.

I opted to use ChildrenElements because ChildElements implies to me that the collection of elements refer to a single child (perhaps because of recursive flattening, or because we implementing https://github.com/facebook/react/issues/2127).  I prefer to keep both of them in the plural form.  Updated for consistency, so this should be good to go.  Please approve, or let me know if you feel strongly about Child over Children and I'll change it.

**Comment by spicyj** [comment]
(y)

**Comment by spicyj** [comment]
assuming Travis passes

**Comment by jimfb** [comment]
Thanks!  Travis passes, merging.

**Pull request merged**
