### PR TITLE
Deduplicate "unknown prop" warning to ease pain of version updates

### PR DESCRIPTION
**Pull request by flarnie**
**Note:** There are other PRs open to fix some failing tests and I expect to rebase on top of those and fix any remaining failures before landing. Hope folks can review this anyway in light of this.

Some widely used libraries which depend on React have used syntax that
ends up passing non-standard props to default React components like
'dom' and 'div'. For example:
```
  // where this.props contains attributes like 'foo'
  return <div {...this.props} />;
```

Since we started throwing warnings for this syntax in Reactv15.2 some
libraries have not upgraded past v15.2.

Now, because of deprecations in 15.5, some libraries will only work with
Reactv15.5, and this causes a conflict when other libraries are pinned
at v15.1. The overall effect is that either there are version conflicts
or the "unknown prop" warning is thrown all over the place, and users of
these libraries can't fix the warnings.

See https://github.com/facebook/react/issues/9466 for more context.

We are deduping this warning in hopes that it allows more library
authors to update to the latest version of React. React v16.0 may take a
different approach to this issue. For some related discussion, see
https://github.com/facebook/react/issues/9477

**Test Plan:**
 - Added a unit test
 - Manually tested with a fixture that was not committed; https://gist.github.com/flarnie/db011bf54206f30b9983cd4dc674c82e

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`).
6. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run prettier`).
7. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
8. If you added or removed any tests, run `./scripts/fiber/record-tests` before submitting the pull request, and commit the resulting changes.
9. If you haven't already, complete the CLA.

### CODE REVIEW

**Comment by spicyj** [comment]
Does this mean that if a third-party component warns first, then you'll never see any warnings for first-party code?

**Comment by gaearon** [comment]
Yea. IMO at this point it’s a reasonable tradeoff (most third party libs have updated long ago).

**Comment by flarnie** [comment]
Yea - there are definitely trade-offs with this approach. It sounds like there was some discussion on Twitter, and then on the issue as well. I think this is okayish for v15.6, but we may want to discuss more how to deal with this in v16.0.

**Comment by gaearon** [comment]
IMO we should completely switch to the new behavior in 16.0 (https://github.com/facebook/react/issues/9477). Then we won't need to come back to this warning at all.

**Comment by flarnie** [comment]
Holding off merging this until the React core team discusses this approach more. @spicyj @gaearon

**Comment by gaearon** [comment]
Closing per discussion with @flarnie and https://github.com/facebook/react/issues/9466#issuecomment-299856525.

**Pull request closed without merging**
