### PR TITLE
[Documentation] Impreove the react-component section of doc

### PR DESCRIPTION
**Pull request by NE-SmallTown**
[#9304](https://github.com/facebook/react/issues/9304)

### CODE REVIEW

**Comment by gaearon** [comment]
@aweary Can you look at this?

**Comment by aweary** [comment]
I can see advantages on both sides. Currently, it assumes that readers are making that connection between "in" and "synchronous". It might be clear to us, but newer developers might not understand the nuance. On the other hand, the added complexity here does feel like a bit much. We should try to simplify the language as much as possible.

Maybe just something like:

```
`componentWillMount()` is invoked immediately before mounting occurs. It is called before `render()`, therefore setting state synchronously in this method will not trigger a re-rendering. Avoid introducing any side-effects or subscriptions in this method.
```

**Comment by NE-SmallTown** [comment]
@gaearon Thanks for your feedback.

> Generally if say "in this method" we always mean "synchronous".

IMO,"in" is a description of **physical location** rather than execution order,such as `function foo(){var a; function b(){}; setTimeout(function c(){})}`,I will say `a`, `b` and `c` all "in" the `foo` method.So,that's why I say "synchronous" here because "asynchronous"'s opposite is "synchronous",not "in".

**Comment by NE-SmallTown** [comment]
@aweary > the added complexity here does feel like a bit much

Ye,I agree.So,maybe add the pr/issue link about this in the more details or Implementation Notes section would be better?

**Comment by aweary** [comment]
I think it's probably better if we avoid linking to PRs/issues from the docs when possible. I think we'd be fine if we just updated 'setting state' to 'setting state synchronously' as that should avoid any confusion about what "in" means.

**Comment by NE-SmallTown** [comment]
@aweary Yup,I update it

**Comment by gaearon** [comment]
Looks good, thanks!

**Pull request merged**
