### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by chicoxyzzy**
- update eslint, babel-eslint, eslint-plugin-react
- update fbjs-scripts
- update del

### CODE REVIEW

**Comment by jimfb** [comment]
At the very least, we'll need to squash these three commits into a single commit before merging.

Staying up-to-date seems generally good.  Just curious if there was anything that forced/motivated this change, or was it just cleanup?

@zpao and @spicyj because npm.

**Comment by chicoxyzzy** [comment]
There are no any important reasons for updating this. I just noticed del 2.0.2 is used by other packages such as eslint for example so I thought its time to update del version used in gulpfile. So I've updated eslint packages as well as I did last week. fbjs-scripts use `.eslinrc` so I updated it as well.

I have split these changes into three commits to make it possible to cherry-pick or revert some of them if necessary but I surely can squash them into one.

**Comment by jimfb** [comment]
Normally we squash, but there are sometimes exceptions.  I'll let @spicyj or @zpao decide about squashing and/or merging this one.

**Comment by zpao** [comment]
FYI: No changes to eslintrc have been made in fbjs-scripts and the changes that have been made there don't affect us. The only actual change is to del, which now uses promises. Your change in the gulpfile should be right but I ran into issues in the past when using it with dependent tasks (but just testing again locally can't repro my original issues so meh).

We're not going to cherry-pick any of these to stable so let's squash.

**Pull request merged**
