### PR TITLE
Switch to parent-based context.  Fixes #2112.

### LINKED ISSUE #2112: Switch the Context to use the Parent tree instead of the Owner tree
I'm pretty convinced at this point that Contexts are more useful in the Parent tree than the Owner tree. It also opens up new use cases for parent->child communication that wasn't possible before.

### PR DESCRIPTION
**Pull request by jsfb**
Switch to parent-based context.  Fixes #2112.

### CODE REVIEW

**Comment by spicyj** [comment]
Can we add a new test that would have failed with owner-based context?

**Comment by jsfb** [comment]
Yep, good idea, done.

**Comment by mridgway** [comment]
Seems like `ReactElement._context` and `ReactContext` should be removed since they are no longer used with parent contexts.

**Comment by jsfb** [comment]
@mridgway That's a super easy change, but I'd like to separate functional changes from cleanup changes (which don't affect functionality) to make code reviews easier.  That way, someone has a chance of actually understanding what's going on in any given commit.  If @spicyj would like it to be part of the same commit, I'll go ahead and amend.

**Comment by spicyj** [comment]
Having all the cleanup in one commit is preferable to me.

**Comment by jsfb** [comment]
Ok, easy money, done.

**Comment by mridgway** [comment]
If you do the cleanup in a separate commit and revert this change then the reverted changes won't function correctly unless you revert the cleanup as well. Seems like it creates unnecessary dependencies between commits.

**Comment by jsfb** [comment]
Cherry-picking reverts can be exceedingly difficult anyway, because people inevitably touch the same code (especially when you have huge commits, you're likely to overlap/conflict somewhere, and merging commits exacerbates the problem).  So it's a loose-loose situation.

Regardless, it's a style difference, I don't have a strong preference either way, already fixed it as per @spicyj.

**Comment by sebmarkbage** [comment]
I kind of prefer functional changes in a separate commit too, although since PRs allow multiple commits they could be merged.

Accepted, but DON'T land until we've solved the layers issue since that will get this reverted.

**Comment by gaearon** [comment]
What's the issue with layers? Can I read about it somewhere?

**Comment by sebmarkbage** [comment]
Nope, it is an internal FB issue.

**Comment by sebmarkbage** [comment]
Basically, there is no way to pass a context to a new subtree - which was also true before but some people hacked around it so we have to undo those hacks.

**Comment by gaearon** [comment]
Ah, the mystical `ReactLayer` from @chenglou's gists.

**Comment by jsfb** [comment]
Layer issue is solved, pending a final review and sync with www.

**Comment by sebmarkbage** [comment]
Well ideally we should land that (and prepare the callers) first since we won't be able to sync React internally now.

**Comment by skiano** [comment]
@jimfb 

I am excited about this feature, so I built react at 7d4491753158afc839f2934367ad2f7878ff7283.

On that commit, I can use parent based contexts (as I see in the unit test that was added)

However, I when I try v0.13.3 I can't seem to get it working.

Was this reverted or changed between then and now?

**Comment by spicyj** [comment]
0.13.3 only includes 0.13 plus individually cherry-picked commits; 0.14 will include everything that's currently in master.

**Comment by skiano** [comment]
Thanks for the info,

Sorry if this info is elsewhere, but does anyone have an idea about how soon 0.14 might go out?

**Comment by spicyj** [comment]
After the things in #3220 get done.

**Comment by mjackson** [comment]
Just wanted to say THANK YOU to @jimfb and everyone else who worked on this change. This feels like the right way to go.

**Pull request merged**
