### PR TITLE
 [docs] Sync up tutorial.zh-CN with en(a440f40) 

### PR DESCRIPTION
**Pull request by iamchenxin**
Sync up tutorial.zh-CN with en(a440f40) 
and amend 08.1-more-about-refs.zh-CN.md

### CODE REVIEW

**Comment by jimfb** [comment]
@iamchenxin Looks good, can you squash these into a single commit?

**Comment by iamchenxin** [comment]
@jimfb ok,I will update more docs in two days. then i squash them into one.

**Comment by iamchenxin** [comment]
@jimfb Squash docs into one .

**Comment by jimfb** [comment]
Great, thanks!

**Pull request merged**
