### PR TITLE
setting a flag, so that the first movement will have the correct value

### PR DESCRIPTION
**Pull request by jasonwilliams**
This should hopefully fix the initial movementX and movementY values introduced in https://github.com/facebook/react/pull/9018

### CODE REVIEW

**Comment by gaearon** [comment]
Out of curiosity, can you make some browser testing and see what browser gives us for the first event, when this property is supported natively?

**Comment by nhunzaker** [comment]
As far as I can tell, the initial movement is always 0, using this method:

1. Open the `mouse-event` fixture
2. Refresh the page, and immediately alt+tab to another app
3. Hover over the fixture
4. Tab back to the browser
5. Move your mouse

**Comment by nhunzaker** [comment]
This does, however, appear to work correctly in Safari 11.1 (Safari is the other browser that does not support movementX/Y)

**Comment by gaearon** [comment]
LGTM

**Comment by jasonwilliams** [comment]
I've tested Chrome, Firefox and Edge, by using the mouse-event fixture, setting a breakpoint over https://github.com/facebook/react/blob/master/packages/react-dom/src/events/SyntheticMouseEvent.js#L45 and then hovering over the page after page load.

Chrome 67.0.3396.87 i did quite a few times, and the first hover event always had movementX at 0
chromepageloadmovementx

Edge 42.17134.1.0 had very similar results after quite a few tries
edgepageloadmovementx

Firefox Developer Edition 61.0b14 seemed to be the outlier here, as i was getting random values each time, sometimes 13, or 18 or 12. This could be saying more about dev tools though, rather than the initial value of movementX
firefoxpageloadmovementx

**Comment by gaearon** [comment]
Nice! This is sufficient—I think `0` is the most reasonable initial value.

**Comment by aweary** [comment]
`0` is the spec-defined initial value 👍

https://w3c.github.io/pointerlock/#extensions-to-the-mouseevent-interface

> The un-initialized value of movementX/Y must be 0.

I also noticed that the spec states: 

> movementX/Y must be zero for all mouse events except mousemove.

It's potentially minor but we're not restricting our polyfill  `mousemove` events, so it's slightly out of spec.

**Comment by gaearon** [comment]
>It's potentially minor but we're not restricting our polyfill mousemove events, so it's slightly out of spec.

Oh, I missed that. We should definitely limit it to `mousemove` events. I don't think it's minor—if you rely on `movementX`/`movementY` then you'll potentially drop movements.

**Comment by aweary** [comment]
@jasonwilliams do you want to fix this in another follow up?

**Pull request merged**
