### PR TITLE
Fix __proto__ bug in ReactDOMSelect

### PR DESCRIPTION
**Pull request by spicyj**
https://twitter.com/rauschma/status/857307345231249409

### CODE REVIEW

**Comment by sebmarkbage** [comment]
I think @trueadm was saying that `Object.create(null)` would force it into dictionary mode which is what we want here.

**Comment by spicyj** [comment]
¯\_(ツ)_/¯ is that better? can switch.

(I just learned why assigning to __proto__ on normal objects has magic behavior but is okay on Object.create(null) objects: the magic is encoded as a setter for `Object.prototype.__proto__`. crazytown)

**Comment by sebmarkbage** [comment]
if the string is interned maybe it's better than the concat? `¯\_(ツ)_/¯`

**Comment by rauschma** [comment]
Note: `__proto__` via setter/getter was introduced in ES6. Prior to that, you should escape that key (and the escaped key, etc.).

**Comment by spicyj** [comment]
Whatever, just gonna go with this.

**Pull request merged**
