### PR TITLE
[Fiber] WIP context

### PR DESCRIPTION
**Pull request by edvinerikson**
I am currently trying to get familiar with the Fiber codebase and IMO the best way to get up to speed is to work with the code.
So I started working on adding context support and got some tests passing for it however I am not sure if this is a good approach and I would appreciate some feedback on the work. All flows are not implemented yet.

I am not sure if I should utilize the Fiber more, right now I have `childContext` there which seems to break the pattern with `memoized` and `pending`. e.g maybe `childContext` could be renamed to `memoizedChildContext` but I am not sure what pending would be. Feedback would be helpful.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
I'd like to explore a zero cost solution of context. The current way we do context is too expensive when you're not using it. We have a different strategy in mind that I think @gaearon might be looking at atm.

**Comment by edvinerikson** [comment]
Alright, sounds reasonable. Looking forward to see a different approach. Since you are working on this internally is there something else that I might be able to work on?

**Comment by sebmarkbage** [comment]
@edvinerikson If you look at Phase 5 of https://github.com/facebook/react/issues/7925 there are a few issues there that are unclaimed that would be very helpful. You can also look for unit tests that aren't covered by the other ones issue.

**Comment by edvinerikson** [comment]
Thanks! I'll take a look, some of them are just magic for me 😆

**Pull request closed without merging**
