### PR TITLE
allow use empty value in input button

### PR DESCRIPTION
**Pull request by gebilaoxiong**
Close: https://github.com/facebook/react/issues/12872

### CODE REVIEW

**Comment by react-linter** [comment]
ReactDOM: size: :small_red_triangle:+0.2%, gzip: :small_red_triangle:+0.1%


  <details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: c601f7a64640290af85c9f0e33c78480656b46bc...999736eef46cc9d18d7d1643b89b9bb591360ff1</p>


  
## react-dom
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-dom.development.js | +0.1% | +0.1% | 621.4 KB | 621.84 KB | 144.74 KB | 144.82 KB | UMD_DEV
**react-dom.production.min.js** | **:small_red_triangle:+0.2%** | **:small_red_triangle:+0.1%** | **93.69 KB** | **93.88 KB** | **30.33 KB** | **30.37 KB** | **UMD_PROD**
react-dom.development.js | +0.1% | 0.0% | 605.76 KB | 606.2 KB | 140.74 KB | 140.81 KB | NODE_DEV
**react-dom.production.min.js** | **:small_red_triangle:+0.2%** | **:small_red_triangle:+0.1%** | **92.19 KB** | **92.38 KB** | **29.31 KB** | **29.35 KB** | **NODE_PROD**
ReactDOM-dev.js | +0.1% | 0.0% | 628.05 KB | 628.5 KB | 143.5 KB | 143.57 KB | FB_WWW_DEV
**ReactDOM-prod.js** | **:small_red_triangle:+0.2%** | **:small_red_triangle:+0.2%** | **273.68 KB** | **274.11 KB** | **51.53 KB** | **51.61 KB** | **FB_WWW_PROD**

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by aweary** [comment]
Thanks, but there's already an open pull request for this https://github.com/facebook/react/pull/12780

**Comment by gebilaoxiong** [comment]
@aweary Yes, but can I fix it?

**Comment by ellsclytn** [comment]
I'll get back to #12780 within the next couple of days 🙂. It's been open for a while because I didn't open an Issue open with it at first, so it went unnoticed for a bit.

**Pull request closed without merging**
