### PR TITLE
Fix ReactTestUtils.isCompositeComponent

### PR DESCRIPTION
**Pull request by koba04**
Currentry, ReactTestUtils.isCompositeComponent returns true even if passed a DOMComponent.

```js
ReactTestUtils.isCompositeComponent(ReactTestUtils.renderIntoDocument(<div/>)); // true
```

This is for fixing that.
I think every Component except DOMComponent is CompositeComponent. Is it correct?

### CODE REVIEW

**Comment by sebmarkbage** [comment]
No, there are also React ART Components, React Native Components etc.

This is also not verifying that it is indeed a component at all, any random object or string or null would pass.

The problem right now is that React DOM components are wrapped in composites. We're planning on changing that and just returning the straight up DOM node.

**Comment by koba04** [comment]
@sebmarkbage 

Thank you for your feedback!

I've fixed problems in your feedback.

>
The problem right now is that React DOM components are wrapped in composites. We're planning on changing that and just returning the straight up DOM node.

Even if React DOM Components are not wrapped in composites, `!inst.tagName` is required for React ART Components (React Native Components too?).

**Comment by koba04** [comment]
This PR is not fixed all issues completely and is just a workaround.
But I think this should be applied because current implementation is quite not working...

**Comment by koba04** [comment]
@sebmarkbage 
In v0.14.0-beta3, This issue is fixed. Thanks!
But an error occurred when it's passed `null`.
I fixed it.

**Comment by spicyj** [comment]
I actually ended up fixing this in #5016 so we don't need to take this. Thanks for looking into it.

**Pull request closed without merging**
