### PR TITLE
Implemented a React.PropTypes.componentOf 

### PR DESCRIPTION
**Pull request by cassiozen**
Prop must be a React component of a certain type.

### CODE REVIEW

**Comment by spicyj** [comment]
This would be called elementOfType if we do want it, though I'm not sure we do since if a component is expecting a `<Button />` element you should (ideally) be able to pass `<PurpleButton />` and have that work too.

**Comment by gaearon** [comment]
>if a component is expecting a `<Button />` element you should (ideally) be able to pass `<PurpleButton />` and have that work too.

I agree. Merging this would suggest React encourages inheritance, which it is the opposite of truth.

**Comment by sebmarkbage** [comment]
It's important to support composition but also important to support good helpers when a component doesn't make sense in certain contexts. This gets pretty complicated to get right though so I'd rather leave it to user space now.

**Comment by tomchentw** [comment]
For anyone who came here, I've extracted this PR into an independent package on npm: [react-prop-types-element-of-type](https://github.com/tomchentw/react-prop-types-element-of-type). I've included warning messages for component inheritance as well to reduce chances of misusage. Issues & PRs are welcomed.

**Pull request closed without merging**
