### PR TITLE
Ensure 'onResponderGrant' is called after 'onResponderTerminate'

### LINKED ISSUE #6217: onResponderGrant called before onResponderTerminate
When a responder captures the active responder, it seems that `onResponderTerminate` is not called until after `onResponderGrant`. This seems like the wrong thing to do. Are there reasons for this behavior?

### PR DESCRIPTION
**Pull request by aleclarson**
Fixes #6217

### CODE REVIEW

**Comment by spicyj** [comment]
Did you run the tests?

**Comment by gaearon** [comment]
This has been around almost for a year and is not merged so I’m closing. If this fixes an issue and there is a person who can review it and confirm it’s correct please feel free to reopen!

**Comment by gaearon** [comment]
Ugh, sorry, I read that as 2015 but it’s actually from 2016 :scream: 
Reopening but it would be great to know who can review this!

**Comment by spicyj** [comment]
Has Travis not run the tests on this PR from over a month ago?!

**Comment by gaearon** [comment]
What is the status of this?
It doesn’t merge cleanly.

There are no tests so I don’t know how to tell what is being fixed, and whether the fix is correct.
Should we merge this or close this?

**Comment by spicyj** [comment]
The test changes made in this PR should be reverted:

https://github.com/facebook/react/pull/5308#issuecomment-166764304

then the tests should pass in order for us to merge this. Also might break some RN apps, not sure how to really predict where that might happen.

**Comment by aleclarson** [comment]
Should I rebase onto master or do you guys got it from here?

**Comment by spicyj** [comment]
This would need revision from you in order to go in, per my last comment.

**Comment by aleclarson** [comment]
Alright, the commits merge cleanly with master.
And I reverted test changes from bb11639.

One reason to keep the current behavior:
- The next responder (that will receive the `grantEvent`) uses a shared object to retrieve the previous responder (that will receive the `terminateEvent`). If the `grantEvent` comes after the `terminateEvent`, the previous responder might have updated the shared object in its `onResponderTerminate` callback. Now the next responder can't retrieve the previous responder (because the previous responder already cleaned up).

But maybe there's a way to do that (even after this PR)?

**Comment by joh1234** [comment]
Update README
https://goo.gl/JBljdR

**Comment by nhunzaker** [comment]
@aleclarson Sorry to stall so long on this. Is there a simple way for me to test this fix?

@spicyj Assuming we could address the conflicts and produce a simple test plan, would you be willing to take a second look at this? This is a bit out of my depth.

**Comment by spicyj** [comment]
I think this should be okay. Good to merge if it gets rebased and tests still pass. (Sorry for missing this last update originally.)

**Comment by nhunzaker** [comment]
Cool. @aleclarson what do you think? I'm happy to rebase this (I think I can)

**Comment by nhunzaker** [comment]
@aleclarson Any update? Do you mind if I take over rebasing this and getting it in?

**Comment by aleclarson** [comment]
@nhunzaker Sure, go ahead. I'm not familiar with the test strategy for `ResponderEventPlugin`.

**Comment by gaearon** [comment]
Anyone wants to revive this? :-)

**Comment by gaearon** [comment]
This doesn't have an owner and is stale again. I'll just close but mention the PR number in https://github.com/facebook/react/issues/6217 so somebody can pick it up if it's still relevant.

**Pull request closed without merging**
