### PR TITLE
Update Reusable Components and Forms Docs to ES6

### PR DESCRIPTION
**Pull request by raphaelkross**
Update Reusable Components and Forms Docs to ES6.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by raphaelkross** [comment]
Just agreed with terms!

**Comment by facebook-github-bot-0** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by facebook-github-bot-2** [comment]
@raphaelkross updated the pull request.

**Comment by facebook-github-bot-9** [comment]
@raphaelkross updated the pull request.

**Comment by gaearon** [comment]
Thank you so much! I expanded on some of the topics but kept the change attributed to you.
I cherry-picked it manually as 9174c29acc60a7f2c1de1b729d7b2ff5492391f8 but you'll appear as a contributor.
Cheers!

**Pull request closed without merging**
