### PR TITLE
CSSTransitionGroup don't fall back to deprecated behaviour if transition*Timeout is 0

### PR DESCRIPTION
**Pull request by piscolomo**
After look around #5873 i think we should consider `transition*Timeout` if it's a number. Right now, if user passes any transitionTimeout as `0` it falls back to the deprecated behaviour

### CODE REVIEW

**Comment by TheBlasfem** [comment]
Other option may be still using deprecated behaviour in falsy values, if is decided that, i can send a fix displaying a warning when `0` is assigned in a timeout

**Comment by rhys-vdw** [comment]
@TheBlasfem your PR is not quite correct because you need both checks to be the same. Warning displays on `value == null`, behaviour is determined by `typeof(value) === 'number'`. I'd recommend just using the `null` check.

`setTimeout` will accept a string as the delay, so this check might also screws up if you do this:

```js
// Provide delay as string.
<CSSTransitionGroup transitionEnterDelay="500">
```

**Comment by TheBlasfem** [comment]
thanks for the comment @rhys-vdw I've updated the PR

**Comment by gaearon** [comment]
What is the use case where you’d want to specify a timeout with `0` value?

**Comment by rhys-vdw** [comment]
@gaearon It's a while ago now... But I think I just put 0 it in to disable transitions while I was experimenting and got different behaviour without a warning. Or perhaps I put one of the transitions to '0' to document that I was aware of the prop but wanted to disable it. To be honest I can't really remember what this is about. Either way the issue is not a use case as such, just a minor inconsistency as mentioned in #5873.

**Comment by gaearon** [comment]
We don’t have an owner for ReactTransitionGroup internally because we don’t use it, and it seems like we don’t have the capacity to review PRs for it at the moment. Your best strategy might be to fork its code (or find an existing fork) and propose these changes there. If any of the forks turns out to be successful we might deprecate our own version and start pointing to the fork in the docs. Sorry it turned out to be this way, but it’s best to do something than to leave this hang forever so I’m closing.

**Pull request closed without merging**
