### PR TITLE
[WIP] Use ES modules internally

### PR DESCRIPTION
**Pull request by gaearon**
Based on top of https://github.com/facebook/react/pulls.

This is probably broken in some ways (and definitely breaks Jest) but some test displays Hello World. Builds are a few KBs down.

Probably don't want to land this until we have a way to run tests against bundles. Still was fun try. I intend to keep this (relatively) up to date hoping I can land it within a few weeks once the infra is there.

### CODE REVIEW

**Comment by acdlite** [comment]
Cool! How did you convert

```js
if (__DEV__) {
  var warning = require('warning');
}
```

?

**Comment by nhunzaker** [comment]
27,000 deletions. Why such a stark drop?

**Comment by spicyj** [comment]
It's stacked (ha) on #10517.

**Comment by nhunzaker** [comment]
Oh. Haha. @spicyj so clever!

**Comment by gaearon** [comment]
@acdlite For now I just turned everything into `import`s so there might be DEV-only things there. I have a list of them. We can do something like https://github.com/facebook/react/issues/10176#issuecomment-315398546 as this gets closer to reality. I think the bigger blocker is lack of test infra.

**Comment by gaearon** [comment]
Did this in another PR.

**Pull request closed without merging**
