### PR TITLE
fix: typo in list-and-keys.md

### PR DESCRIPTION
**Pull request by Charlotteis**
This changes a 'Wrong!' in the list-and-keys documentation to 'Right!' and it makes more sense.

Hope this helps 🌞

### CODE REVIEW

**Comment by Charlotteis** [comment]
I signed the CLA for the first time, moments before I submitted this PR... will try again.

**Comment by gaearon** [comment]
Hmm, I think this "Wrong" was right 😛 

The idea is that the first example shows both lines being wrong.
Then the next example shows both lines being right.

I can see how this could be confusing, but not sure how to express it in a different way.

**Comment by Charlotteis** [comment]
Hmmmmmmmmmmmm. I defer to you then. I wouldn't say the message was lost, but I was like 'this doesn't read quite right'

**Comment by gaearon** [comment]
Do you have ideas on how to improve it? I don't feel very good about this part but I'm not sure how to fix it.

**Comment by Charlotteis** [comment]
My idea on improving was adding 'Correct!' maybe take out the 'Wrong' all together?

Like

> wrong, don't put it here
> it should go here

?

**Comment by gaearon** [comment]
And make it a single example?

Right now we have:

## Wrong example

```js
// Wrong: don't put it here
...

// Wrong: you forgot it here
// ...
```

## Correct example

```js
// Correct: you didn't put it here
...

// Correct: you put it here
// ...
```

As an alternative, we could do a single example:

## Correct Example

```js
// Don't put it here!
...

// Put it here!
...
```

Does this make sense?

**Comment by Charlotteis** [comment]
A single example sounds really good!

**Comment by gaearon** [comment]
@Charlotteis Would you like to make another PR for this?

**Comment by Charlotteis** [comment]
I can certainly try, hopefully some point today.

**Comment by gaearon** [comment]
Thanks!

**Pull request closed without merging**
