### PR TITLE
Fix/12200 regresssion select multiple

### PR DESCRIPTION
**Pull request by GarethSmall**
## Problem

When creating a select element and setting multiple the first element would be selected. This was due to the multiple prop being set after the children we're appended.

An non-react example  case created by @aweary can been seen here - https://jsfiddle.net/dm6vkq9q/

## Solution

Have a special case where if the element type were of select set the properties before the children are appended.

## Issue
https://github.com/facebook/react/issues/12200

### CODE REVIEW

**Comment by gaearon** [comment]
Why is a separate hook necessary?

**Comment by GarethSmall** [comment]
The idea was to set select attributes before the children were appended. Currently it goes append children > set attributes. Which for this is an issue. Maybe an extra hook was overkill in this instance. Do you have an alternative solution?

**Comment by aweary** [comment]
I think one of the other two solutions I listed in https://github.com/facebook/react/issues/12200#issuecomment-364566803 would be preferable, but I'd like @gaearon's input.

**Comment by gaearon** [comment]
I think it's more likely we can change the order of the existing hooks than that we'd introduce a new hook.

**Comment by GarethSmall** [comment]
Do you mean by switching appendAllChildren and finalizeInitialChildren?

**Comment by gaearon** [comment]
Sorry, I don't remember how this works, and don't anticipate having time to look into this in the near future

**Comment by GarethSmall** [comment]
Alright, thank you for the input. Im going to head back to the drawing board on this.

**Comment by gaearon** [comment]
I'm not saying this option isn't available as a last resort or if you make a compelling case for why it might be necessary universally. Just that an API addition (even an internal one) needs more justification than a bugfix.

**Comment by GarethSmall** [comment]
Initially i tested out switching the hooks unfortunately this introduced more bugs than the one fix. I thought this might be a bit excessive for one case. Ill try out a few more possible solutions for this issue and see what I come up with.

**Comment by gaearon** [comment]
For posterity, the fix was https://github.com/facebook/react/pull/13270

**Pull request closed without merging**
