### PR TITLE
fixed minor typo

### PR DESCRIPTION
**Pull request by ghost**
Hi, My name is Pralay.

I just fixed a typo, please review and accept the changes if it makes sense.

Thank you!

Regards,
Pralay

### CODE REVIEW

**Comment by jimfb** [comment]
Can you please sign the CLA so we can merge?

https://code.facebook.com/cla

**Comment by jimfb** [comment]
Ping @ghost

**Comment by facebook-github-bot-7** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by jimfb** [comment]
Great, thanks @ghost!

**Comment by zpao** [comment]
I'm kind of surprised github let you merge this since it's now an empty commit… sounds like a bug :)

**Pull request merged**
