### PR TITLE
Stopgap fix for element disabling

### PR DESCRIPTION
**Pull request by spicyj**
Fix for #8308. This is a bad hack -- EventPluginHub.getListener isn't even DOM-specific -- but this works for now and lets us release 15.4.1.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
This replaces https://github.com/facebook/react/pull/8365/commits/c6323cb9857b4d8ac5742ec09d3ad8cedfc30a9f then.

**Comment by nhunzaker** [comment]
Should I migrate this over to https://github.com/facebook/react/pull/8329 or do you all want to start fresh for a 16.0 fix? I just wanted it fixed really, happy to hand it off to more capable hands.

**Comment by spicyj** [comment]
We should probably go with something closer to #8329 long-term although the logic doesn't quite belong in ReactTreeTraversal. Need to figure out where it does belong.

**Comment by nhunzaker** [comment]
>  the logic doesn't quite belong in ReactTreeTraversal. Need to figure out where it does belong.

Happy to move discussion over to #8329 but I had two thoughts:

1. Some sort of injection for traversal that can tag meta data. We just need to keep track of if we're inside of a disabled interactive element or not
2. Strip out the prop in `ReactDOMComponent` so that it bubbles over the element, but doesn't result in a binding. We'd still have to pass some way of indicating that an interactive element was inside of a `fieldset`, but it might be a more natural place to put DOM behavior.

**Comment by gaearon** [comment]
Was the release tool not used for 15.4.1? This is still tagged as `15-next` but it has been released I think.

**Pull request merged**
