### PR TITLE
Fix production propTypes test so it works with error code system

### PR DESCRIPTION
**Pull request by acdlite**
Test expects the unminified error message. Without this fix the test will break after the next release.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Why do we need to avoid extracting this?

**Comment by sebmarkbage** [comment]
Seems like before we're done extracting this, we ideally *do* want this in the error code map. Otherwise React Native (that runs on alphas) will get an error with no way to look it up right?

**Comment by acdlite** [comment]
Ok then the test needs to be fixed

**Comment by keyanzhang** [comment]
You won't need to manually remove it after having it in the map. Keeping old error messages there is fine and it supports outdated versions.

**Comment by acdlite** [comment]
@keyanzhang Not sure what you're referring to

**Comment by keyanzhang** [comment]
Oh, @acdlite I was talking about the plan to remove outdated error messages... Did I misunderstand it? 😢

**Comment by acdlite** [comment]
Oh sorry, some context: we have a test that makes an assertion on a production error message. It passes currently because it's newer than the last stable release. But once we run the error code script, it will fail because the message will be minified.

My original plan was to special case this error so it doesn't get minified, since we'll eventually move PropTypes into a separate package anyway. But instead I just changed the test.

**Comment by keyanzhang** [comment]
Got it, yeah that makes perfect sense. Thanks for explaining! :)

**Pull request merged**
