### PR TITLE
Skip portals when rendering on server-side.

### PR DESCRIPTION
**Pull request by diasbruno**
Hi,

Here is an option that just skips portals while rendering on the server-side environment.

I'll try to find some ideas to help dealing with modals on tests.

Please let me know if there are any improvements in this PR. 
If the solution is not ideal, it can be closed.

Thank you.

### CODE REVIEW

**Comment by cpojer** [comment]
Would you mind rebasing this PR on top of master? Then we can figure out how to merge this :)

**Comment by diasbruno** [comment]
@cpojer Done.

**Comment by diasbruno** [comment]
This is an old patch. Not sure if it is relevant now or there are things to change. I believe most implementations that uses `createPortal` have some kind of check if DOM is available.

IMHO, since portals can't be rendered on server-side, I don't know if throwing an exception is desired and will make all libraries to check for DOM environment. Making portal a no-op seems ok. Perhaps, display a warn when trying to render?

cc @cpojer @gaearon

**Comment by oliviertassinari** [comment]
To provide more context, one of the reasons why Material-UI has [a Portal](https://next.material-ui.com/utils/portal/) component is to avoid the server-side error.

**Pull request closed without merging**
