### PR TITLE
[fresh] Reset useMemoCache in response to a FastRefresh run

### PR DESCRIPTION
**Pull request by poteto**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #30677
* #30663
* #30662

This PR introduces a new (dev only) debug property on fibers to indicate
that it is being rerendered as a result of a FastRefresh run. This
allows React to clear the cache even where the size (incidentally)
remains constant between renders: for example, if edited code _happens_
to keep the cache size the same but the code is meaningfully different
such that it is no longer correct to reuse the cache.

### CODE REVIEW

**Comment by gaearon** [comment]
Is it possible to use the module-level `ignorePreviousDependencies` for this, which should be getting set in the right places?

**Comment by gaearon** [comment]
Also noticing the test passes even if I comment out `currentlyRenderingFiber._debugNeedsMemoCacheReset === true`

**Comment by gaearon** [comment]
I think https://github.com/facebook/react/pull/30700 makes sense to me, any reason why we don't do that instead?

**Comment by poteto** [comment]
Closing in favor of #30700

**Pull request closed without merging**
