### PR TITLE
[DevTools] Add React Conf notification

### PR DESCRIPTION
**Pull request by mattcarrollcode**
This PR creates notifies DevTools users of React Conf through:

1. Updating the text on the popup

Screenshot 2024-01-31 at 3 45 45 PM

2.  a text "badge" notification on the extension icon 

Screenshot 2024-01-31 at 3 44 41 PM

The badge disappears after the user clicks on the icon or after React Conf ends.

Note: this only works on Chrome and hasn't been tested or written to work on Firefox or Edge yet.

### CODE REVIEW

**Comment by markerikson** [comment]
Honest question: can I ask what the intent and goal is behind this change?  (beyond the obvious "tell people about ReactConf").

this feels like a change that A) few users will notice because (my assumption) users rarely click on the React DevTools button in the toolbar, B) is very likely to attract _negative_ attention "OH NO REACT TEAM IS TRYING TO ADVERTISE IN MY BROWSER!" (see also prior complaints from Firefox users about its association with Pocket and inability to opt out of behavior built into the browser, as well as existing React issues from users complaining about the "use the React DevTools" log messages).

If the goal is just "spread the word about ReactConf as widely as possible", it feels like a blog post submitted to Reddit, HN, and some community discords, would have a broader reach.

**Comment by mattcarrollcode** [comment]
@markerikson thanks for the feedback! We haven't decided to do this, and still may choose not to.

My main motivation behind this would be to get a more diverse audience at React Conf. I think you're right that Reddit, HN, etc. have a broad reach but they all target people that are active on social platforms. My hope is that something like this would nudge folks from underrepresented groups to attend React Conf.

I hear (and share) your hesitation to have something that may look like an ad in a developer tool but I think the tradeoff to cultivate a more diverse community may be worth it. I've also done some work to minimize the annoyance: the badge only shows up once, and once you click on the devtools icon the badge goes away and doesn't come back again.

**Comment by billyjanitsch** [comment]
I agree with @markerikson. I appreciate the intention, but my guess is that the reaction from the community will be at least slightly negative. Minimizing the annoyance is appreciated but I think the concern will be more about the precedent. In general, co-opting developer tools for advertising purposes hasn't been received well in the JS ecosystem. (e.g., the wave of npm postinstall messages a few years back.) This feels like an unforced error during a time when React is already struggling with community sentiment.

Have you considered adding a banner to the React docs instead? This could reach a large and similarly diverse audience without encroaching on developer tools.

**Comment by mattcarrollcode** [comment]
Thanks for the feedback y'all! I'm going to explore other directions and I'm closing this pull request.

**Pull request closed without merging**
