### PR TITLE
Fail gracefully when comment container is detached

### LINKED ISSUE #11067: "Cannot read namespaceURI of null" error when rendering into a comment
See internal task 22198152.

### PR DESCRIPTION
**Pull request by sophiebits**
Fixes #11067. Not much we can do here but it kinda sucks for us to fail hard. IMO this is the most reasonable thing we can do.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Can we warn but still throw to preserve the simple logic for prod?

**Comment by sebmarkbage** [comment]
Or at least throw a custom error message in prod so that this still throws and we have the option to simplify it, if we're worried about logging?

E.g. `invariant(node.parentNode, "Nice minifiable error message")`.

**Comment by sophiebits** [comment]
I think problems like https://fburl.com/a5tpcgfj (internal link) where it creates terrible user experiences from throwing is likely to happen to people again and again. This particular error was caused by a misguided (IMO) attempt to clean up pagelet containers when transitioning to new pages https://fburl.com/us6qo7yl but I think lots of people who use this feature will run into this by accident.

**Comment by sebmarkbage** [comment]
Do we think that the Chrome GC bug is a legit issue?

Why is this scenario worse than any other place we throw? What is the bad user experience?

What's the scenario we think is likely to happen to cause this issue?

The internal auto-cleanup thing doesn't seem legit and many different things can go wrong in React (and any other code that does manual unmount clean or worse, listens to dom mutation events). If someone external presented that we'd probably just say "fix your code".

**Comment by sophiebits** [comment]
OK, I put up D6000272 for the internal clearing thing. We can try it and see if we run into it again from other people doing clowny stuff and how common it seems.

**Comment by gaearon** [comment]
I think we decided "meh" on this.

**Pull request closed without merging**
