### PR TITLE
Support Pointer Events

### LINKED ISSUE #499: Support Pointer events specification
What is your approach to IE10 touch events?

Hammer.js checks `window.navigator.pointerEnabled || window.navigator.msPointerEnabled` and then switches `touchstart`, `touchmove`, `touchend touchcancel` to `pointerdown MSPointerDown`, `pointermove MSPointerMove`, `pointerup pointercancel MSPointerUp MSPointerCancel`.

### PR DESCRIPTION
**Pull request by philipp-spiess**
Closes #499

This PR adds support for Pointer Events as discussed in #499. It is heavily based on previous work in #1389 and will add most pointer events to the `SimpleEventPlugin` and enter/leave events to `EnterLeaveEventPlugin`.

I added a new DOM fixture to test all pointer events and make sure my implementation does indeed work. I tested on Chrome 65 and Firefox 59 without seeing any issues. If you think the fixtures is not necessary for future changes, I'm happy to remove them as well.

The only open question is if we want to add a polyfill. For the sake of simplicity, I opted against a polyfill for this PR. However, this work is compatible with [PEP][] (I've verified this behavior in Safari 11 by loading PEP in `fixtures/dom/public/index.html`).

[PEP]: https://github.com/jquery/PEP

### CODE REVIEW

**Comment by jquense** [comment]
Nice! I think a polyfill is probably not needed here. In general we are trying to less of that to simplify and shrink react-dom

**Comment by philipp-spiess** [comment]
@jquense I absolutely agree. It’s not worth the maintenance costs if there are well-established alternatives like PEP that work flawlessly.

**Comment by react-linter** [comment]
ReactDOM: size: :small_red_triangle:+1.1%, gzip: :small_red_triangle:+0.9%


  <details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 5dfbfe9da740398c0a2cf4d897a0085000d06b7b...9548c1cf1f021a0fe5ebfcf5b2d25ca2e27370f2</p>


  
## react-dom
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-dom.development.js | +0.3% | +0.3% | 609.28 KB | 611.31 KB | 140.41 KB | 140.82 KB | UMD_DEV
**react-dom.production.min.js** | **:small_red_triangle:+1.1%** | **:small_red_triangle:+0.9%** | **100.18 KB** | **101.3 KB** | **31.97 KB** | **32.26 KB** | **UMD_PROD**
react-dom.development.js | +0.3% | +0.3% | 593.65 KB | 595.68 KB | 136.25 KB | 136.71 KB | NODE_DEV
**react-dom.production.min.js** | **:small_red_triangle:+1.1%** | **:small_red_triangle:+1.0%** | **98.64 KB** | **99.77 KB** | **31.11 KB** | **31.41 KB** | **NODE_PROD**
ReactDOM-dev.js | +0.4% | +0.4% | 618.04 KB | 620.34 KB | 139.01 KB | 139.52 KB | FB_DEV
**ReactDOM-prod.js** | **:small_red_triangle:+0.9%** | **:small_red_triangle:+0.8%** | **284.83 KB** | **287.28 KB** | **52.32 KB** | **52.74 KB** | **FB_PROD**
react-dom-test-utils.development.js | +0.9% | +0.8% | 40.75 KB | 41.1 KB | 11.69 KB | 11.78 KB | UMD_DEV
**react-dom-test-utils.production.min.js** | **:small_red_triangle:+2.9%** | **:small_red_triangle:+2.1%** | **10.64 KB** | **10.95 KB** | **3.96 KB** | **4.04 KB** | **UMD_PROD**
react-dom-test-utils.development.js | +1.0% | +0.9% | 35.61 KB | 35.96 KB | 10.27 KB | 10.36 KB | NODE_DEV
**react-dom-test-utils.production.min.js** | **:small_red_triangle:+3.1%** | **:small_red_triangle:+2.4%** | **9.91 KB** | **10.22 KB** | **3.73 KB** | **3.82 KB** | **NODE_PROD**
ReactTestUtils-dev.js | +0.9% | +0.9% | 36.89 KB | 37.24 KB | 10.46 KB | 10.55 KB | FB_DEV
react-dom-unstable-native-dependencies.development.js | +0.2% | +0.1% | 61.18 KB | 61.33 KB | 16.02 KB | 16.04 KB | UMD_DEV
**react-dom-unstable-native-dependencies.production.min.js** | **:small_red_triangle:+0.8%** | **:small_red_triangle:+0.5%** | **11.32 KB** | **11.41 KB** | **3.92 KB** | **3.94 KB** | **UMD_PROD**
react-dom-unstable-native-dependencies.development.js | +0.3% | +0.1% | 56.85 KB | 56.99 KB | 14.77 KB | 14.79 KB | NODE_DEV
**react-dom-unstable-native-dependencies.production.min.js** | **:small_red_triangle:+0.8%** | **:small_red_triangle:+0.5%** | **10.6 KB** | **10.68 KB** | **3.66 KB** | **3.68 KB** | **NODE_PROD**
ReactDOMUnstableNativeDependencies-dev.js | +0.3% | +0.1% | 57.09 KB | 57.28 KB | 14.56 KB | 14.58 KB | FB_DEV
**ReactDOMUnstableNativeDependencies-prod.js** | **:small_red_triangle:+0.7%** | **:small_red_triangle:+0.3%** | **26.26 KB** | **26.45 KB** | **5.36 KB** | **5.38 KB** | **FB_PROD**

## create-component-with-subscriptions
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
create-component-with-subscriptions.development.js | n/a | n/a | 0 B | 9.7 KB | 0 B | 3 KB | NODE_DEV
**create-component-with-subscriptions.production.min.js** | **n/a** | **n/a** | **0 B** | **3.69 KB** | **0 B** | **1.6 KB** | **NODE_PROD**

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by philipp-spiess** [comment]
@gaearon Thanks for looking into that! Any ideas where/how we can loose some weight?

**Comment by jquense** [comment]
No more adding any events? Or polyfill? I think react DOM has a responsibility to support the new things in the platform as much as it has one to web perf. Not mention adding new events without bundle increases will likely require a rewrite of the event system. The latter is going to take a long time and involve a lot of input across renderers and FB in general, I hate for RD to fall behind in platform support in the meantime.

**Comment by gaearon** [comment]
>No more adding any events? Or polyfill?

I’m not saying to never add them. But this is adding *a lot*.

>Not mention adding new events without bundle increases will likely require a rewrite of the event system.

I think that might be an overstatement. To drop the 1K pre-gzip, we need to find a way to drop the 1K pre-gzip. Not necessarily rewrite the event system. It could be composed of small improvements anywhere.

We get a lot of PRs with features. I appreciate this but I think it's time more people start hunting for opportunities to cut the size if we want to ship those features.

>Any ideas where/how we can loose some weight?

I tend to start by running `yarn build core,dom --type=UMD_PROD --pretty`. Read the bundles in `build/dist`. Look for opportunities to cut the code. Repeat.

Here are some examples of me doing it: https://github.com/facebook/react/pull/11912 https://github.com/facebook/react/pull/11800 https://github.com/facebook/react/pull/10803 https://github.com/facebook/react/pull/10802 https://github.com/facebook/react/pull/10671 https://github.com/facebook/react/pull/10227. There was no specific pattern other than I looked through all the bundle code, found dubious logic, and deleted or refactored it.

**Comment by gaearon** [comment]
To clarify the previous comment. I don’t mean we need to find a way to add events without increasing the whitelist right now (although that would be nice). I mean that if we want to add something, we need to start being more proactive at removing something. Even if those things are not directly related. This applies both to the core team and to the outside contributions.

**Comment by jquense** [comment]
> I think that might be an overstatement. 

Sorry, it's an overstatement if the idea is we should find anything to remove. I do think this PR illustrates that long term, the current system is not great, if we don't want to increase the bundle size as the platform grows. I'd love to start making incremental improvements to the events, (as well as @nhunzaker tho we've both been short on time :/ ). I would say tho, that our explorations there, indicate tho that incremental improvements are hard there, as the whole system sort of neatly rests on itself. Maybe on that front we could do another small call and debrief a bit out it and chart a way forward.

> This applies both to the core team and to the outside contributions.

Ya that's great, We should and definitely start building an environment of trimming down the code. I'm just a bit worried about the added outside cost. This adds an even steeper hill to outside contributors, in already hard-to-contribute-to code base. Finding things that are safe to delete requires a lot of experience in the codebase, and as a point of contribution, it's a lot harder to get reviews for those sort of changes. I totally understand the sentiment i just want to make sure we aren't pushing folks away from submitting good additions, because they can't cut an equal amount out somewhere.

**Comment by gaearon** [comment]
> I do think this PR illustrates that long term, the current system is not great,

Agreed! Rewriting it is a very ambitious goal that also has downstream effects (e.g. `react-native-web` currently strongly relies on it). So I don't think it's feasible to look at this holistically yet.

>as a point of contribution, it's a lot harder to get reviews for those sort of changes

I’m always happy to review bundle size improvements outside of the normal queue. I agree it's not easy but it's necessary.

**Comment by aweary** [comment]
I think identifying if we can move forward with https://github.com/facebook/react/pull/11894/ would be a good opportunity to reduce bundle size.

**Comment by gaearon** [comment]
I won't have time to do it but happy to review.

**Comment by necolas** [comment]
Is the idea that any bundle size increase at all is a blocker? Or only above a certain absolute size, or is there a % threshold?

**Comment by gaearon** [comment]
I'm uncomfortable adding non-core features that increase size at the same time as we're working on core features that will *also* increase the size.

It's not that there's any particular change or a size limit, but the fact that we get *very* few pull requests that remove code. So every non-core feature contributes to a death by a thousands cuts. There was a lot of hard work to get the bundle size down with 16 (partially to “free the space” for new features) and the bar for taking unplanned changes that increase the size is becoming higher now.

**Comment by gaearon** [comment]
@philipp-spiess Can you please rebase so we can land this? Thanks!

**Comment by gaearon** [comment]
This looks good to me.

**Comment by gaearon** [comment]
(To add context to my earlier comments, @philipp-spiess made a pretty big refactoring to save some bytes in https://github.com/facebook/react/pull/12629. So that's why I'm comfortable taking this now. :-)

**Comment by jquense** [comment]
woohoo! Thanks ya'll

**Comment by superkarolis** [comment]
Nice addition to React DOM! However, I couldn't get the example (https://codesandbox.io/s/q83r7nrwv6) from the announcement to work on mobile. Tried it on both, iPhone Safari and Chrome. Any ideas why? I added PEP polyfill just to try but it didn't help either. I could investigate to see what could be the problem if no one knows for sure.

**Comment by philipp-spiess** [comment]
@superkarolis Unfortunately Safari does not support pointer events yet and every browser that ships in the App Store is forced to use the Safari renderer as well (So Chrome on iOS is just a wrapper around Safari IIRC).

There are problems with PEP as well like the issue I filed [here](https://github.com/jquery/PEP/issues/365) but adding PEP to the example works fine for me, can you test this as well? https://codesandbox.io/s/o5k8ynrj89

I also had to add the `touch-action` CSS property as a HTML property like the documentation of PEP mentions. Maybe that is what you missed out? :)

**Comment by Kovensky** [comment]
One problem I have with codesandbox is that it will, occasionally, load very old versions of the bundles, instead of the latest one. It also doesn't seem to record which version was used in the sandbox. Like it insisting on loading React 16.0.0 instead of 16.3.0 back when I was trying to write the code snippet for #12551.

**Comment by superkarolis** [comment]
@philipp-spiess My bad, forgot about `touch-action`, thanks man!

**Pull request merged**
