### PR TITLE
fix: Error: Cannot read property 'duration' of undefined

### PR DESCRIPTION
**Pull request by Amine-H**
## Summary

Fix for #18786 and #18798

Just a few things I should mention first, I am really new to the code base, ~not sure what was the intention to use the indexes from `commits` instead of `commitData`.
In other words if `commitData` has more commit than `commits` (interaction commits) then this PR would be showing more commits than whan It should.~

#### UPDATE:
I have updated my changes to "ignore" commits that have no corresponding `commitData`

## Test Plan

- Profile https://react-example1.s3.amazonaws.com/index.html
- Scroll down to the end of the list

Thanks @shiftyp for the clear reproduction steps

### CODE REVIEW

**Comment by Amine-H** [comment]
After further investigating the issue, I found out that the changes I pushed aren't a valid.

the issue is caused when you stop profiling while the page still doing some work. causing missing commit in `commitData` or `interactionCommits` as an unexisting `commit`

**Comment by bvaughn** [comment]
Thanks for submitting this PR!

I'm a little concerned that while it fixes a symptom (out of range index) it doesn't fix the underlying cause (why is the data missing?)

Adding some logging to DevTools and trying the repro, I can see that e.g. the backend records 181 commits but then the later profiling data only contains 180 commits. So one of them is being filtered out for some reason or is not being sent across the bridge. Either way this is likely to cause bigger problems than just this specific fix, so I'm going to look into it further.

**Comment by bvaughn** [comment]
Going to close this PR in favor of #18862!

**Comment by Amine-H** [comment]
Alright ! that should do it! thanks :+1:

**Comment by bvaughn** [comment]
No problem! Thank you!

**Pull request closed without merging**
