### PR TITLE
fixed memoized state  --> packages\react-dom\src\server\ReactPartialRendererHooks.js

### PR DESCRIPTION
**Pull request by Biki-das**
this was an old issue #16416 , this could be a possible fix , please have a look @bvaughn @rickhanlonii

### CODE REVIEW

**Comment by Biki-das** [comment]
@rickhanlonii , hello hope you take a look at this

**Comment by Biki-das** [comment]
@bvaughn , need a review!!

**Comment by bvaughn** [comment]
@Biki-das We see when PRs are opened. This isn't the only thing we're working on. Please don't ping so aggressively.

**Comment by Biki-das** [comment]
> @Biki-das We see when PRs are opened. This isn't the only thing we're working on. Please don't ping so aggressively.

Oh sorry for that will keep that in mind!

**Comment by gaearon** [comment]
Thanks for the PR, but this is not the right fix. You are working around the symptom, but not the root cause. Please see https://github.com/facebook/react/issues/16416#issuecomment-886213854 for root cause analysis.

**Comment by Biki-das** [comment]
> Thanks for the PR, but this is not the right fix. You are working around the symptom, but not the root cause. Please see https://github.com/facebook/react/issues/16416#issuecomment-886213854 for root cause analysis.

Thanks for the feedback will look into it and try to find solution.

**Pull request closed without merging**
