### PR TITLE
Require instantiable components to extend React.Component

### LINKED ISSUE #4599: Warn If a Component Doesn't Extend React.Component
To support arrow functions and plain functions as "components" we need to know if we can call new on them. Examples that won't work:

```js
function PlainFunctionComponent(props) {
  return null;
}

var ArrowFunctionComponent = (props) => <div />;

class ClassComponent {
  render() {
    return <div><PlainFunctionComponent /><ArrowFunctionComponent /></div>;
  }
}
```

We need to detect if a component is a "function" or a "class" before calling `new` on it.

We can call `new` on everything if they're plain functions as long as they return a `ReactElement`. However, that won't work for null/false/string return values and we want to support those too. We also can't call `new` on arrow functions. Likewise, we can't NOT call `new` on classes.

Unfortunately ECMAScript doesn't have a way to detect if something is `new`able or not.

The current plan is to add our own static flag to React.Component so that we can detect if something is a class.

Any class pattern that doesn't require `new` should still be possible:

```js
function ModuleComponent(props) {
  return {
    render() {
      return <div />;
    }
  };
}
```

I'm not sure how we can distinguish this pattern from one that requires `new` for warnings though. :(

### PR DESCRIPTION
**Pull request by spicyj**
Fixes #4599.

### CODE REVIEW

**Comment by spicyj** [comment]
This almost works, except MockedComponent here doesn't end up with the flag:

https://github.com/facebook/react/blob/2f96d70087494dd1b8e725abc4a0609d3985dbe6/src/renderers/shared/reconciler/__tests__/ReactMockedComponent-test.js#L53

@sebmarkbage ideas?

**Comment by sebmarkbage** [comment]
If you use an object, jest will mock it. You would potentially set it to an object during __DEV__ or testing maybe?

**Comment by spicyj** [comment]
Fixed by changing isReactClass to not have an underscore…

https://github.com/facebook/jest/blob/9d726ed478ecff19acc5bf04a2600e559818cfb6/src/lib/moduleMocker.js#L311

**Comment by sebmarkbage** [comment]
Another thing we could do is:

```js
element.type.prototype instanceof React.Component
```

That locks it into a by-reference equality (and therefore a single `react` package). Not sure if that is good or bad. Certainly more idiomatic.

**Comment by syranide** [comment]
> That locks it into a by-reference equality (and therefore a single react package). Not sure if that is good or bad. Certainly more idiomatic.

Multiple React packages means it's likely they'll be different versions, so that's probably preferable? Mixing React packages seems like a bad idea (or a mistake) and being slapped with an error seems beneficial I would think.

**Comment by laserjim** [comment]
I like `instanceof`; feels cleaner than checking for magic properties.

**Comment by jimfb** [comment]
I like `instanceof`; feels cleaner than checking for magic properties.

**Comment by spicyj** [comment]
I thought the whole point (one of the whole points) of 0.14 (0.15 maybe) was that you can use more than one React.

**Comment by syranide** [comment]
@spicyj But not mixing between them I would assume?

**Comment by jimfb** [comment]
@spicyj You can use more than one react-renderer without using more than one react-core.  `React.Component` lives in the shared core, and I think it's very reasonable to assume a single shared react-core.

**Pull request merged**
