### PR TITLE
Delete react-dom-factories package

### PR DESCRIPTION
**Pull request by gaearon**
This package is already published at `1.0.0`.
Unlike the version in `src`, the published version is already standalone and inlined. 

It seems to me that we won’t be changing this package further. And even if we will, we’ll do it from `15-stable`. So I’m deleting this.

### CODE REVIEW

**Comment by gaearon** [comment]
Seems safe enough, I’ll just merge.

**Comment by mjomble** [comment]
Seems like this broke the link in the deprecation warning - https://fb.me/react-dom-factories

**Comment by gaearon** [comment]
Hmm. That's good because it was pointing to the wrong place. Let me update the link. Thanks for noticing!

**Comment by gaearon** [comment]
Fixed now.

**Comment by nhunzaker** [comment]
For great justice.

**Pull request merged**
