### PR TITLE
Updated ReactIncrementalSideEffects-test.internal.js to ES6

### PR DESCRIPTION
**Pull request by barrymichaeldoyle**
I've completed all the checks and read through all the code of conduct and contribution documents.

This is my first time I'm submitting a pull request to a Facebook open source project. **I have completed the CLA**.

I've updated one of the older test files to use new ES6 syntax. If this is acceptable. I'll continue to update other older tests in the same way.

Would love some feedback 👍

### CODE REVIEW

**Comment by barrymichaeldoyle** [comment]
Not sure why exactly the CircleCI tests failed. Don't have much experience with CircleCI, does anyone know what's up with that?

**Comment by raunofreiberg** [comment]
Pretty sure some of those standards were on purpose and following Airbnb's JS style guide. 

I.e [Prefer regular functions over arrow functions for components](https://github.com/airbnb/javascript/tree/master/react#class-vs-reactcreateclass-vs-stateless)

**Comment by jquense** [comment]
React isn't following the airbnb style guide, but i don't know if some of these were on purpose for another reason. I suspect most of the code tho was just that way from a while ago and can be updated to a more modern style

**Comment by aweary** [comment]
I'm not sure it matters much, I usually ere on the side of avoiding changes unless they're necessary. There's nothing wrong with the way the tests currently are, and changing them for purely stylistic reasons just opens things up to breakage.

**Comment by barrymichaeldoyle** [comment]
Ok fair enough, you're correct in saying the changes aren't necessary. I just figured that yes, the code was writen a while ago, so ES6 wasn't really the standard that it's becoming now. So I figured it was worth updating to match the latest standards.

It also helped me get a little more familiar with the React code base since I'd love to contribute to it where needed.

Thanks for the feedback.

**Comment by barrymichaeldoyle** [comment]
So is the consensus that I shouldn't bother with updating files and I should just close this PR?

**Comment by barrymichaeldoyle** [comment]
Cool. closing PR since I haven't had much feedback here. Sorry for the time waste.

**Pull request closed without merging**
