### PR TITLE
Switch to using comma-dangle: always-multiline

### PR DESCRIPTION
**Pull request by hawsome**

### CODE REVIEW

**Comment by zpao** [comment]
We could probably stop ignoring `docs/_js/*.js` from eslint. I bet there are a bunch of other things in there that we could fix. Would you be interested in doing that?

I'd prefer to have that done in bulk and not just eyeball some lint violations.

**Comment by hawsome** [comment]
Hi @zpao, I would love to as I'd really enjoy learning React. I may have trouble with fully committing though as I'm pretty busy with school right now.

**Comment by zpao** [comment]
Fair enough, we'll take this as is and make the effort for the rest later.  I appreciate the help!

If you could just sign the CLA (link in comment above from our bot), that would be great. Thanks!

**Comment by hawsome** [comment]
Done and done 👍

**Comment by zpao** [comment]
Thanks! (manually confirmed, beating the bot)

**Pull request merged**
