### PR TITLE
[ReactDOMFactories] Reduce byte size

### PR DESCRIPTION
**Pull request by fabiomcosta**
Since the object keys and valus are always the same I decided to transform that to an array.
That should save some bytes from the JS package.
Traversing an array should also be faster than `mapObject`, which should make this module initialize faster.

### CODE REVIEW

**Comment by spicyj** [comment]
This was meant to be safe against Closure advanced mode. Is this actually smaller after gzip?

**Comment by fabiomcosta** [comment]
I don't see how that would not be safe againts GCC advanced mode, but I'll make sure everything works and that the gzip size is better.

**Comment by zpao** [comment]
Because app code that does `React.DOM.output` will get crushed to something like `React.DOM.q`, but since we use quotes in an array `React.DOM.output` will actually exist.

**Comment by syranide** [comment]
@zpao We don't run GCC on React so `React.DOM.input` would still exist and work, but the element it creates would be `<q>` or whatever.

**Comment by zpao** [comment]
Yes, *we* don't but the goal with the GCC support was so that somebody could if they wanted (eg clojurescript).

**Comment by zpao** [comment]
```
Running "compare_size:files" (compare_size) task
   raw     gz Sizes
  1198    641 build/react-dom-server.js
   734    445 build/react-dom-server.min.js
  1179    632 build/react-dom.js
   715    436 build/react-dom.min.js
699327 157734 build/react-with-addons.js
150302  43356 build/react-with-addons.min.js
632976 142973 build/react.js
137902  39947 build/react.min.js

   raw     gz Compared to master @ 23167f287eda5ee23725a099e67d6086baa8e300
     =      = build/react-dom-server.js
     =      = build/react-dom-server.min.js
     =      = build/react-dom.js
     =      = build/react-dom.min.js
 -2603   -764 build/react-with-addons.js
  -912   -410 build/react-with-addons.min.js
 -2603   -757 build/react.js
  -911   -385 build/react.min.js
```

`mapObject.js` (1466 bytes) no longer gets packaged as a result so that's a bit over half the raw savings (which we likely wouldn't see internally). As far as perf goes we're talking about the difference of iterating 130 entries. Since we're all speculating, I estimate the difference is going to be on the order of ns (ie negligible). We could inline `mapObject` and get > half those bytes back and probably also a speculative perf win (could avoid the `.call`), while still maintaining GCC compatibility.

**Comment by fabiomcosta** [comment]
@zpao, thx for the data! I've been a bit lazy with this PR.
So what is the conclusion here? It seems to me that it's all positive and we could merge it.

**Comment by jimfb** [comment]
@fabiomcosta Did you verify it works with GCC?  Intuitively it seems like it should, but we should verify.

**Comment by syranide** [comment]
AFAIK anyone relying on `React.DOM.input` and GCC will break, with this you have to do `React.DOM['input']`. Right? That seems like a bad idea.

**Comment by jimfb** [comment]
@syranide Yeah, I agree, we don't want to break that.

**Comment by fabiomcosta** [comment]
@syranide from my understanding this is unrelated to this change. This change won't change the component names from `React.DOM` and won't make devs use `React.DOM['input']`.
@jimfb, I'm sending links showing the code compiled with GCC advanced mode. Thx for pushing this, I agree this is important.
[You'll have to select "Advanced" and then press "Compile"]
GCCed with changes: https://goo.gl/rFLcBt
GCCed without changes: https://goo.gl/iVMxMS

**Comment by syranide** [comment]
@fabiomcosta `input` specifically is special-cased in GCC and is never mangled, try some of the other tags: https://goo.gl/qf1FWL

**Comment by jimfb** [comment]
@fabiomcosta I just looked at the example you posted, I think @syranide is correct, this doesn't minify safely for properties like `svg` and `progress` :(.

**Comment by fabiomcosta** [comment]
@syranide @jimfb, cool, I see, I can see now that it does the same for `form` and some other strings.
But the current code doesn't "solve" that either, I would think that it would make GCC recognize that but the same minification happens to the `ReactDOMFactories` keys with the current code.
I guess neither the current code nor the new one are safe to be used with GCC advanced mode, as seen by the following link:
https://goo.gl/28mB2z

If the current code wants to be safe with GCC it would have to use the key from the "big object" as the key that is added to `React.DOM`, but it ignores that and only uses the value.

**Comment by spicyj** [comment]
mapObject preserves keys.

**Comment by fabiomcosta** [comment]
@spicyj, I don't know what I was thinking, you're right. Sorry for the confusion.

**Pull request closed without merging**
