### PR TITLE
Wrap lifecycle events with ReactPerf.measure if __DEV__

### PR DESCRIPTION
**Pull request by gfogle**
In order to do more advanced metrics with ReactPerf, ReactDefaultPerf, etc. we really need to have those being run through the measure cycle as well as renders.

This will allow for more advanced metrics like `# of times should component update called per component`, etc.

Ultimately, would like to see React pump out warnings for things like `component has no state or props and no shouldComponentUpdate` or `shouldComponentUpdate always returns true/false`.

Seems like this would be much more impactful if baked into core rather than having to write additional 3rd-party tools to hijack ReactComponents to measure them.

### CODE REVIEW

**Comment by gfogle** [comment]
this is in relation to #4522

**Comment by jimfb** [comment]
You posted a link this pull request; I assume you intended to link to: https://github.com/facebook/react/issues/4521

The unit tests aren't passing, as per Travis.

Conceptually this feature seems reasonable to me but we should confirm with @spicyj and @sebmarkbage

**Comment by gfogle** [comment]
@jimfb - looking into the tests now. I'm hijacking the lifecycles so where they're re-attached might be the issue.

**Comment by gfogle** [comment]
@jimfb - sorry for the delay in getting to look at this. Travis is kosher now.

**Comment by sebmarkbage** [comment]
This is only wrapping it in ReactClass which doesn't work with ES6 classes etc. It should be done in CompositeComponent if anything. However, I'm not sure if these necessarily are makes sense as part of ReactPerf or some more complete profiling solution.

**Comment by gfogle** [comment]
Yea I originally was going to break it up into smaller PRs. I'll just submit all of it at once.

George

**Comment by gfogle** [comment]
@sebmarkbage - Agree that ReactClass isn't really the best way to tackle this given that it breaks the test suite. I'm looking through implementing these features onto ReactCompositeComponent instead. Trouble I'm seeing is that only the methods defined on RCC are running through ReactDefaultPerf i.e. mountComponent, updateComponent, etc. So trying to hijack the `inst` var in mountComponent works and can be re-routed through ReactPerf... but none of the lifecycles are actually going to be seen by ReactDefaultPerf to increment counts, etc.

will look into this more. if it makes things easier i can pull this over to the issue i created and just close this PR.

**Pull request closed without merging**
