### PR TITLE
[Gatsby docs update] WIP add Acknowledgements page

### PR DESCRIPTION
**Pull request by flarnie**
**NOTE:** This isn't done yet, but pushing the progress I have.

**what is the change?:**
Add custom template for 'acknowledgements' page

**why make this change?:**
We want this page to show up on the new docs site.

**test plan:**
Manual testing, BUT it doesn't work yet because the markdown file has
some logic that isn't supported by the plugins we are using.

See screenshot: 

screen shot 2017-09-26 at 4 44 05 pm

**issue:**
checklist item on Gatsby checklist
https://github.com/bvaughn/react/wiki/Gatsby-check-list

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run prettier`).
6. Make sure your code lints (`npm run lint`).
7. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
8. If you haven't already, complete the CLA.

### CODE REVIEW

**Comment by bvaughn** [comment]
> Manual testing, BUT it doesn't work yet because the markdown file has some logic that isn't supported by the plugins we are using.

Logic in a markdown file 🤢

This sounds like something we shouldn't carry over from the old site.

**Comment by bvaughn** [comment]
I'm going to branch your branch and hopefully finish this 😄

**Comment by bvaughn** [comment]
For your consideration: #10873

**Comment by flarnie** [comment]
Thanks for wrapping this up @bvaughn - closing since https://github.com/facebook/react/pull/10873 was merged. :)

**Pull request closed without merging**
