### PR TITLE
[ReactFiberScheduler.js] Remove redundant if else branch

### PR DESCRIPTION
**Pull request by NE-SmallTown**
The codes of [this if statement](https://github.com/facebook/react/blob/4bcee56210bd3ab3f6440ff7313a255148e22107/packages/react-reconciler/src/ReactFiberScheduler.js#L1661-L1667) is same with the [else if statement](https://github.com/facebook/react/blob/4bcee56210bd3ab3f6440ff7313a255148e22107/packages/react-reconciler/src/ReactFiberScheduler.js#L1668-L1674), so we merge them as one branch

### CODE REVIEW

**Comment by NE-SmallTown** [comment]
Any update on this or I miss something?

**Comment by Hanmy3** [comment]
Leanh@gmail.com

**Comment by Hanmy3** [comment]
Leanhn6@gmail.com

**Comment by NE-SmallTown** [comment]
@gaearon Any update on this or I miss something?

**Comment by NE-SmallTown** [comment]
@gaearon Any update on this or I miss something?

**Comment by NE-SmallTown** [comment]
@gaearon Any update on this or I miss something?

**Comment by rodrigooler** [comment]
@NE-SmallTown very strange this if else if ! 🤔

**Comment by sminutoli** [comment]
Besides the strange `if`, it looks like there's a heavy repeated logic... What do you think about a refactor? 

https://codesandbox.io/s/933n1x2qqw

(I've made the regression tests before doing any refactor)

**Comment by NE-SmallTown** [comment]
@gaearon Any update on this or I miss something?

**Comment by sminutoli** [comment]
@NE-SmallTown you're welcome, I'm an infiltrator here, it drew my attention and I've made the exercise just for fun (the original code needs a lot of mental process to be understood).

**Comment by sminutoli** [comment]
@NE-SmallTown btw inlining the functions seems to be a great middle-path solution... 

https://codesandbox.io/s/vnj701o6o0

**Comment by NE-SmallTown** [comment]
@gaearon Any update on this or I miss something?

**Comment by NE-SmallTown** [comment]
@gaearon Any update on this or I miss something?

**Comment by NE-SmallTown** [comment]
@gaearon Hi, Dan, would you mind look at this or I miss something?

**Comment by NE-SmallTown** [comment]
@gaearon Hi, Dan, would you mind look at this or I miss something?

**Comment by NE-SmallTown** [comment]
@gaearon Hi, Dan, would you mind look at this or I miss something?

**Comment by NE-SmallTown** [comment]
Hello, is there anyone could look at this or I miss something?

**Comment by NE-SmallTown** [comment]
Hello, is there anyone could look at this or I miss something?

**Comment by NE-SmallTown** [comment]
Hello, is there anyone could look at this or I miss something?

**Comment by NE-SmallTown** [comment]
Hello, is there anyone could look at this or I miss something?

**Comment by NE-SmallTown** [comment]
Hello, is there anyone could look at this or I miss something?

**Comment by NE-SmallTown** [comment]
Hello, is there anyone could look at this or I miss something?

**Comment by NE-SmallTown** [comment]
Hello, is there anyone could look at this or I miss something?

**Comment by NE-SmallTown** [comment]
Hello, is there anyone could look at this or I miss something?

**Comment by NE-SmallTown** [comment]
Hello, is there anyone could look at this or I miss something?

**Pull request closed without merging**
