### PR TITLE
Gatsby site supports IE11

### PR DESCRIPTION
**Pull request by bvaughn**
* Added polyfills.
* ~~Removed TypeKit (which I'd been planning on doing anyway, but it was preventing me from testing prod build in IE11).~~

### CODE REVIEW

**Comment by joecritch** [comment]
@bvaughn Does this mean we lose the webfont altogether?

**Comment by bvaughn** [comment]
> @bvaughn Does this mean we lose the webfont altogether?

Yeah, and I'm not willing to fight for/against it, so I guess we can undo that change.

**Comment by bvaughn** [comment]
No. I don't care. I've reverted that change.

**Comment by nhunzaker** [comment]
@bvaughn Ah okay. Gross. Maybe I should look at this on my current app!

**Pull request merged**
