### PR TITLE
Include latest version of jQuery in tutorial

### PR DESCRIPTION
**Pull request by AnSavvides**
The commit message should be descriptive enough :)

I have already submitted a CLA in the past.

### CODE REVIEW

**Comment by zpao** [comment]
We should perhaps even update this further and match what we do in the html we ship in the tutorial repo: https://github.com/reactjs/react-tutorial/blob/master/public/index.html

Let me know if you want to do that or we can always to that later. It hasn't been an issue either way.

**Comment by AnSavvides** [comment]
That's a good point!

Looking at the tutorial repo I can see it uses jQuery 2.x, which doesn't support IE8, whereas React does if you [use some polyfills](https://facebook.github.io/react/docs/working-with-the-browser.html#polyfills-needed-to-support-older-browsers) right? Would it make sense to use jQuery 1.x both here and in the tutorial for those that might be seeking to develop against IE8?

Let me know what you think and I'll update this branch accordingly and open a PR in the [react-tutorial](https://github.com/reactjs/react-tutorial) repo if need be :)

**Comment by zpao** [comment]
I don't think it's super important to make the tutorial compatible with IE8. IE8 is usually an afterthought and if you do need to support it, you probably have some experience and know what you would need to do differently (including using an appropriate version of jQuery and not just copy and pasting code from tutorials).

**Comment by iamdustan** [comment]
any thoughts of removing jquery for fetch (potentially with a reference to `https://github.com/github/fetch`) since it’s only present for `$.ajax`?

**Comment by AnSavvides** [comment]
Ooh that's a good idea actually @iamdustan :) What do you think @zpao?

**Comment by zpao** [comment]
I like the idea but I'm a bit torn that it might be *too* new. While `$.ajax` has it's downsides, it's relatively familiar. Even if you've never used it, it's pretty simple to understand. `fetch` on the other hand uses Promises which have another step to actually understand.

We don't do it in the tutorial but elsewhere we talk about aborting xhr during `componentWillUnmount`. This is trivial with native xhr & `$.ajax` but is actually currently impossible with `window.fetch`.

So for now, let's just stick with what we have. We may want to revamp the tutorial entirely in the future and we can consider it then.

**Comment by iamdustan** [comment]
fwiw, `$.ajax` also returns promise-like objects. My main reasoning is to avoid referencing `jQuery` and `React` at all, to hopefully prevent just one person from putting it in their unwittingly and then depending upon it instead of the model React provides.

Great point concerning aborting. Seems like a big oversight to the `fetch` design.

**Comment by zpao** [comment]
True, I forgot about jQuery's deferreds. And that's a good point. I'm not opposed longer term, but let's keep this change simple. I love the enthusiasm though - let's chat more about what else we can do to make some broader changes to the tutorial.

**Comment by AnSavvides** [comment]
Yeah not being able to `abort` is a bit of a deal breaker - that's a very good point. It looks like there is an issue for adding support for [`abort`](https://github.com/slightlyoff/ServiceWorker/issues/625) - maybe sometime in the future `window.fetch` will be a viable solution.

Cool, so I've updated to `jQuery` 2.x so this should be ready to go :) Thanks for the nice conversation @zpao and @iamdustan :+1:

**Comment by zpao** [comment]
:thumbsup: thanks!

**Pull request merged**
