### PR TITLE
Upgrade to Jekyll 3

### PR DESCRIPTION
**Pull request by Daniel15**
Full list of changes is at https://jekyllrb.com/docs/upgrading/2-to-3/. The tl;dr of it is:
 - Relative permalinks are no longer supported, so all the files in the `docs` and `tips` subdirectories need their permalink to be prefixed with `docs/` and `tips/` respectively
 - `post` and `page` types were renamed to `posts` and `pages` respectively
 - `jekyll-paginate`, `pygments` and `redcarpet` are all now optional, so I needed to explicitly add it to the Gemfile. By default, Jekyll now uses `rouge` rather than `pygments` for syntax highlighting, but rouge does not support highlighting individual lines (`hl_lines`) so we need to continue using Pygments.
 - Layout metadata (eg. `sectionid`) is now on a `layout` variable rather than `page`

Tested the following pages and confirmed that they all work:
 - "Docs" link (getting started page): http://127.0.0.1:4000/react/docs/getting-started.html
 - Downloads: http://127.0.0.1:4000/react/downloads.html
 - Tutorial: http://127.0.0.1:4000/react/docs/tutorial.html
 - A few pages under the "docs" subdirectory, to confirm they're working properly:
    - http://127.0.0.1:4000/react/docs/addons.html
    - http://127.0.0.1:4000/react/docs/why-react.html
    - http://127.0.0.1:4000/react/docs/create-fragment.html
 - A few tips:
    - http://127.0.0.1:4000/react/tips/false-in-jsx.html
    - http://127.0.0.1:4000/react/tips/style-props-value-px.html
 - Non-English versions of the page:
    - http://127.0.0.1:4000/react/docs/getting-started-it-IT.html
    - http://127.0.0.1:4000/react/docs/getting-started-ja-JP.html

Please let me know if you'd like me to add anything else to the test plan. I can push the site onto my test server if you like. :)

### CODE REVIEW

**Comment by zpao** [comment]
I had thought about doing this before but I've actually been planning on moving away from Jekyll for a while. I don't know what the timeline for that really is so I guess it's fine to update this in the mean time. Were there any tangible wins like faster site generation?

**Comment by Daniel15** [comment]
> Were there any tangible wins

It works on Windows when using Ruby 2.2, so I could actually build the site on my main computer without having to mess with multiple Ruby versions :stuck_out_tongue: The old version of Jekyll has some really old dependency that doesn't run on Ruby 2.2 on Windows.

I didn't notice anything else apart from that, other than the fact that we're no longer depending on an old dependency.

>  I've actually been planning on moving away from Jekyll for a while

Do you think that'd happen some time soon though? I remember seeing someone prototyping that a long time ago (probably in 2014). Jekyll seems decent for what it is.

**Comment by zpao** [comment]
My thinking for ditching Jekyll was that we can start writing React for our site. Additionally, the docs for some of our other sites use react-page which is really unsupported (except when we decide to touch it) and it would be good to get us on the same page (or closer to it anyway). I'd like to get everything on a bit more modern platform that we can iterate on better and not copy & paste 20 files between projects. I've done some experimentation but got caught up with higher pri work, was hoping to loop back around to it this half but we'll see. So realistically it's not happening short term, which is why I'm fine taking this now :)

**Comment by Daniel15** [comment]
As long as there's advantages of switching and we're not just reinventing the wheel. It sounds like we'd be able to iterate faster with a non-Jekyll solution. The nice thing about Jekyll is that it mostly works out-of-the-box. If we do switch the site to something else (React-powered like you said), ideally it should be something similar - Give it some markdown files, some templates (or React components), and a small config, and get a static site as output :smile: 

I've never used `react-page`, did it do something like that? Why'd we deprecate it?

> not copy & paste 20 files between projects

What do you need to copy and paste? You should be able to put all shared stuff in a separate Git repo and add it as a submodule to all the sites in order to share the contents. If Jekyll needs them in particular directories, you could just symlink them.

**Comment by gaearon** [comment]
>If we do switch the site to something else (React-powered like you said), ideally it should be something similar - Give it some markdown files, some templates (or React components), and a small config, and get a static site as output 

A few existing options:

* https://github.com/gatsbyjs/gatsby
* https://github.com/MoOx/phenomic

**Comment by zpao** [comment]
Believe me, I've thought about all of the things Daniel.

**Comment by zpao** [comment]
Finishing this up in #7308.

**Comment by Daniel15** [comment]
Thanks @zpao!

**Pull request closed without merging**
