### PR TITLE
Closure Compiler wrong assignment order in `instantiateReactComponent`

### LINKED ISSUE #8894: Closure Compiler: wrong assignment order in `instantiateReactComponent`
When consuming React from source with the Google Closure Compiler, [this bit](https://github.com/facebook/react/blob/eca5b1d48e71218800156ce474ec79b990b09fbd/src/renderers/shared/stack/reconciler/instantiateReactComponent.js#L26-L32) of code isn't being run in the correct order.

It seems like the Google Closure Compiler transformation is changing the function to a `var` assignment. It messes up the behavior because the original `instantiateReactComponent` function is hoisted. My thought is it's related to the fact that the `instantiateReactComponent` function is exported from that module. 

Anyway, this produces an error because the assignment to `ReactCompositeComponentWrapper.prototype` is now in the wrong order (assignment -> function definition, when we want definition -> assignment).

This may also be related or the root cause of #8887.

The most straightforward solution is to bring the `Object.assign` call after the function is declared, which I've verified works correctly. I'm happy to submit a PR with the described approach.

### PR DESCRIPTION
**Pull request by anmonteiro**
This fixes #8894

### CODE REVIEW

**Comment by anmonteiro** [comment]
Can we get this reviewed? This simple change alone can go a long way empowering Google Closure Compiler users to get dead-code elimination on React by consuming it from a `node_modules` installation.

**Comment by gaearon** [comment]
This looks fine by itself. However, just to set expectations, I’m not quite sure when we’ll cut another patch release, and React 16 will contain a completely rewritten core, so this change won’t affect it.

**Comment by anmonteiro** [comment]
Thanks!

I understand. So to avoid encountering similar problems with Fiber, are there instructions to build master locally and take it for a spin?

**Comment by gaearon** [comment]
@anmonteiro 

Yea. You should be able to build from master and then import `react-dom/fiber` instead of `react-dom`.

**Comment by anmonteiro** [comment]
Great. Will do and report any issues I encounter along the way.

**Comment by anmonteiro** [comment]
@gaearon Don't know where else to provide feedback, but everything seems to work successfully when consuming ReactDOMFiber with the Google Closure Compiler 👍

**Pull request merged**
