### PR TITLE
Remove coverage badge from README

### PR DESCRIPTION
**Pull request by bvaughn**
This badge doesn't seem that useful. I'm also not really sure how it's being computed, given that [the Coveralls report](https://coveralls.io/github/facebook/react?branch=master) seems mostly comprised of `.py` files:
Screen Shot 2019-03-26 at 12 34 40 PM

FYI @paul (just on the off chance that you care)

### CODE REVIEW

**Comment by paul** [comment]
I do not care.

**Comment by bvaughn** [comment]
Haha, sorry Paul! Auto complete got the best of me. I meant to cc @zpao.

**Comment by zpao** [comment]
I think you must be looking at a different coveralls report 😬. I see the react repo tree… it's not my call anyway though so y'all do you!

**Comment by bvaughn** [comment]
Interesting. The report has since changed. Andrew and I both looked at it previous, and the build date was very stale. (Now it shows March 2019, but before it showed a date several years ago.)

Oh well. 👍

**Comment by meals37** [comment]
God bless

**Pull request merged**
