### PR TITLE
remove recommendation to download react-devtools (depracated)

### PR DESCRIPTION
**Pull request by battaile**
(ok I really just want to be a contributor)

### CODE REVIEW

**Comment by spicyj** [comment]
Why would we remove this? The dev tools aren't deprecated.

**Comment by jimfb** [comment]
Devtools are struggling but not deprecated.  Also, a replacement is on the way, so we'll probably just update the fburl or update the plugin on the chrome store, so no change to the React code should be necessary for this.

@battaile If you're looking to get involved: https://github.com/facebook/react/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+bug%22

**Comment by battaile** [comment]
Oh sorry I got it confused with react-tools I think, and thanks @jimfb I'll definitely check it out!

**Comment by iamdustan** [comment]
Oh a replacement? How does one learn more?

**Comment by spicyj** [comment]
@iamdustan Just a brief mention in our meeting notes for now: https://discuss.reactjs.org/t/meeting-notes-2015-06-19/697?u=spicyj. Probably @jaredly will put up a pull request to the devtools repo in the next few weeks and then you can try it out.

**Comment by iamdustan** [comment]
haha. I’m convinced.

screen shot 2015-06-24 at 7 05 00 am

**Pull request closed without merging**
