### PR TITLE
contentType in the handleCommentSubmit (react-tutorial)

### PR DESCRIPTION
**Pull request by vamsi**
`contentType: 'application/json',`

The change is required, made to wait for 30minutes figuring out what to do. Finally adding that solved my problem

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by zpao** [comment]
Sorry you had that experience. I thought setting `dataType`, as well as setting the `Content-Type` headers for the responses from all the servers would have made this work. Since we haven't heard about this being an issue in the past, could you share your setup so that we can try to reproduce it and see if there are similar conditions which reproduce it (or other issues).

**Comment by vamsi** [comment]
I tried this on with Rails framework with a backbone component mixin in the React. 
[From the docs](http://api.jquery.com/jQuery.ajax/)
dataType - The type of data that you're expecting back from the server
contentType - When sending data to the server, use this content type.

**Comment by zpao** [comment]
The servers we provide in our tutorial work fine with, and several are even expecting, the default `contentType` of `application/x-www-form-urlencoded` so I think we're going to leave this as is. Unfortunately we can't support people running the tutorial with a setup different than we expect as there is just too much we would have to test and support. Again, sorry you had that experience - this is exactly why we provide servers you can run.

**Pull request closed without merging**
