### PR TITLE
Add Learning Resources section to the Community Resources on the website

### PR DESCRIPTION
**Pull request by tylermcginnis**
This PR is in regards to @gaearon's [tweet](https://twitter.com/dan_abramov/status/746419224541691904) and I'd like to open dialog before this is merged about the best way to approach utilizing community learning resources in the official docs. 

My concern with this "Learning Resources" approach is that it could easily become a link dump which would be both ineffective and overwhelming for beginners. The way to avoid a link dump would be to have some form of quality check. However, that may lead to too much effort needed by the core team to keep up with PRs.

### CODE REVIEW

**Comment by zpao** [comment]
Yea, we should be careful about the way we approach this as anything we link to will appear "blessed". We initially kept the Complementary Tools page on the site until that grew too large and it's now on the wiki: https://github.com/facebook/react/wiki/Complementary-Tools. That definitely would likely turn into a dumping ground and would be really hostile for new people as you say.

In an ideal world our docs would be perfect for beginners and we wouldn't need to rely on managing a list of other docs. Short term that is not going to happen so I'm happy to link to a few places running some courses. Obviously you have some skin in that game @tylermcginnis with the one you've included, but let's offer a few other options too :)

It might also be good if we could find some individuals who could do some cursory vetting of materials so that burden isn't all on the core team. @Aweary - you were part of the workshop at React Europe right? Do you have some insight into what other resources people are using / would you be interested in helping? Language is important too, we might want to find out what resources are available for non-English speakers.

**Comment by Aweary** [comment]
> It might also be good if we could find some individuals who could do some cursory vetting of materials so that burden isn't all on the core team. @Aweary - you were part of the workshop at React Europe right? Do you have some insight into what other resources people are using / would you be interested in helping? Language is important too, we might want to find out what resources are available for non-English speakers.

I attended the hackathon and the conference but unfortunately missed out on the workshop, but regardless I would be more than happy to help aggregate and review resources. As long as all the recommended resources are consistent and not too repetitive (you don't want to link to a dozen different articles on "getting started with React") I think this would be generally useful.

> In an ideal world our docs would be perfect for beginners and we wouldn't need to rely on managing a list of other docs.

This might also be a good opportunity to identify what exactly the official docs/tutorial lacks and see if we can expand on those topics in the official docs (which I'd be happy to help with as well).

**Comment by tylermcginnis** [comment]
@zpao I agree with everything you said. I run [React Newsletter](http://twitter.com/reactnewsletter) so I've read quite a bit of React resources over the last few years. I'll compile a list of those resources which I've seen be the most helpful for @Aweary or anyone else to look over.

**Comment by markerikson** [comment]
One issue is that there's many different forms of useful resources out there.  Basic terminology tutorials, build-a-project tutorials, video series, full-blown courses, explanations of library internals, articles on specific use cases like forms or AJAX, component libraries, articles on performance, component lists, component search tools, ... there's a _lot_ of stuff out there.  And there's even a lot of _good_ stuff.  I've been maintaining a list of resources on React and Redux that I have looked at and consider to be fairly high quality, and that list is now up to at least 430 links - and it's not just a link dump either, I've categorized them and added blurbs.  Obviously that's way more than you'd want in an "official" list.

Not quite sure exactly what criteria you'd want to apply to an "official" list.  Obviously totally up to the React team to apply any criteria you want, I just foresee someone whining because their article wasn't included.  That said, Redux's [Ecosystem page](http://redux.js.org/docs/introduction/Ecosystem.html) is probably a pretty good model to follow.

To toss out a few potential meta-resources:

- My own [React/Redux Links list](https://github.com/markerikson/react-redux-links), which is pretty comprehensive at this point.
- [Awesome-React](https://github.com/enaqx/awesome-react), which is more of a link dump, but decently organized
- https://js.coach/, a _very_ useful search tool for React-related packages

Overall, I'd suggest defining several different categories of links, probably keep each category limited to 3-4 links, and clarify that these are just a few "staff picks".  I'd also specifically point to these other lists as broader resources.

**Comment by Aweary** [comment]
> One issue is that there's many different forms of useful resources out there. Basic terminology tutorials, build-a-project tutorials, video series, full-blown courses, explanations of library internals, articles on specific use cases like forms or AJAX, component libraries, articles on performance, component lists, component search tools, ... there's a lot of stuff out there.

In an ideal world we'd pick the "best-in-class" resource for each topic, but I guess that's easier said than done.

> Overall, I'd suggest defining several different categories of links, probably keep each category limited to 3-4 links, and clarify that these are just a few "staff picks". I'd also specifically point to these other lists as broader resources.

This is the approach I'd recommend as well. Maybe we can try to get some community feedback about what they feel the official docs are missing and address those areas. Ideally, the articles would cover core concepts like data fetching, composition, performance, etc.

One concern I have is whether this list would contain articles covering React integration with popular libraries (like Redux). One the one hand it would definitely be useful for the majority of people, but on the other hand, you'd either have to include guides for a huge number of libraries or consider those few libraries "officially endorsed" which is a slippery slope.

**Comment by markerikson** [comment]
Any further thoughts on putting together a resources list?

**Comment by gaearon** [comment]
cc @lacker who plans to work on revamping React docs

**Comment by lacker** [comment]
I think the "category" approach makes sense. We did this when we revamped the React Native docs recently - https://facebook.github.io/react-native/docs/more-resources.html - and it ended up being pretty useful.

We have not had much whining about it, but it's clear that it is not a community space where everyone can list every product on there, it's just a short list controlled by the core team. I think the same approach would be useful for React. So, rather than accept this PR and then encourage more people to add things one by one, it's probably better for a single person to do some surveys, get feedback  and research and organize a set of ~15 top links. Maybe @ericnakagawa or maybe we should batch this up with some other website work and do this at the time of the "big React doc revamp" whenever we do that.

**Comment by gaearon** [comment]
Closing this for now as we revamped the docs completely, but I linked to this PR from #8060, and we should do something.

**Comment by gaearon** [comment]
I think the right thing to do here is to keep such content where it has always been: on the project wiki. We just need someone to clean it up and add really good content there (right now it's a mix of good and bad). Then we can link to it from the docs. Since it's a wiki, it won't carry endorsement stronger than we feel comfortable giving, so I think it's the best way forward.

If you're interested in helping with it, please see https://github.com/facebook/react/issues/9583.

**Pull request closed without merging**
