### PR TITLE
(Issue#10957) Replace hyperlink tag with button tag in tic-tac-toe tutorial

### PR DESCRIPTION
**Pull request by pyitphyoaung**
…torial

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run prettier`).
6. Make sure your code lints (`npm run lint`).
7. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
8. If you haven't already, complete the CLA.

### CODE REVIEW

**Comment by bvaughn** [comment]
I think this is a good change.

It looks like you missed one reference though:
> For each step in the history, we create a list item &lt;li&gt; with a link &lt;a&gt; inside it that goes nowhere (href="#") but has a click handler which we'll implement shortly.

We'll also want @gaearon to mirror these changes in his Codepens too.

**Comment by pyitphyoaung** [comment]
Cheers for pointing out missing area, @bvaughn!  Let me prepare new pull request that covers reference areas I missed out with this pull request.

**Comment by bvaughn** [comment]
No need for a new pull request. You can just push an additional commit to your existing branch and this pull request will be updated.

**Comment by pyitphyoaung** [comment]
Sorry, I already deleted fork and got new fork with complete changes for this issue - 10957.

**Pull request closed without merging**
