### PR TITLE
Grammar, jsx syntax highlighting

### PR DESCRIPTION
**Pull request by mbrookes**

### CODE REVIEW

**Comment by iamdustan** [comment]
## Before
JS Highlighting

## After
JSX Highlighting

**Comment by iamdustan** [comment]
^ as far as GH is concerned. Not sure if the doc site generator also has JSX syntax highlighting :)

**Comment by mbrookes** [comment]
Good question - since it's hosted on github I had naively assumed it would be supported, but given it's jekyll, it might not. I'll build the docs site locally and check.

**Comment by mbrookes** [comment]
You're right, it doesn't. Shame! I'll close and submit the grammar fix separately.

**Pull request closed without merging**
