### PR TITLE
Fix componentWillUnmount() not counted by ReactPerf

### PR DESCRIPTION
**Pull request by gaearon**
This fixes `componentWillUnmount()` not being measured because `ReactDebugTool` doesn’t realize there is a flush going on. Also adding tests to check that all lifecycle methods are instrumented.

### CODE REVIEW

**Comment by gaearon** [comment]
@spicyj

**Comment by facebook-github-bot-9** [comment]
@gaearon updated the pull request.

**Comment by spicyj** [comment]
👍 

I assume we already have tests to make sure renders due to setState are instrumented? Because that's a different code path than the top-level renders. Thanks for including a top-level update though.

**Comment by gaearon** [comment]
We currently don’t, sorry 😄  . I’ll add a `setState` path here as well before merging.

**Comment by facebook-github-bot-0** [comment]
@gaearon updated the pull request.

**Pull request merged**
