### PR TITLE
Regression test: Missing unmount after re-order

### PR DESCRIPTION
**Pull request by acdlite**
Adds a regression test for a bug I found in the effects refactor.

The bug was that reordering a child that contains passive effects would cause the child to "forget" that it contains passive effects. This is because when a Placement effect is scheduled by the reconciler, it would override all of the fiber's flags, including its "static" ones:

```js
child.flags = Placement;
```

The problem is that we use a static flag to use a "static" flag to track that a fiber contains passive effects.

So what happens is that when the tree is deleted, the unmount effect is never fired.

In the new implementation, the fix is to add the Placement flag without overriding the rest of the bitmask:

```js
child.flags |= Placement;
```

(The old implementation doesn't need to be changed because it does not use static flags for this purpose.)

### CODE REVIEW

**Review by bvaughn — APPROVED** [review]
Nice test!

**Review by bvaughn — APPROVED** [review]
Nice test!

**Review by bvaughn — APPROVED** [review]
Nice test!

**Review by bvaughn — APPROVED** [review]
Nice test!

**Comment by sophiebits** [comment]
Nice test!

**Comment by bvaughn** [comment]
That was a GitHub bug 😅 I was only excited enough about the test to comment twice.

**Comment by myspivey** [comment]
Nice test!

**Pull request merged**
