### PR TITLE
Update error codes and rollup.json

### PR DESCRIPTION
**Pull request by tomocchino**
Is there any reason not to update these, so we can stop getting all the warnings when we build locally?

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Are the rollup consistent across platforms? We've seen them diverge slightly in the past. So someone else might still get slightly different numbers.

**Comment by tomocchino** [comment]
Every time I build (and I've run yarn build somewhere north of 100 times tonight) I get different results there. We'll have to wait for @trueadm to provide some guidance on that, I think.

**Comment by sebmarkbage** [comment]
Checking in new error codes mean that we're going to spend those numeric ids. We typically don't want to do that until release in case we end up removing or renaming one of the errors.

**Comment by tomocchino** [comment]
Ah, okay. Thanks for the context. I wonder if a better fix would be for me to make builds less noisy locally. 😄

**Comment by gaearon** [comment]
IMO we should just silence the warning. We have a section about updating error codes in the release checklist—that should be enough.

**Comment by trueadm** [comment]
@tomocchino the results should be the same for a build, depending on if the error codes are all up to date and your yarn is the latest (slight tweaks in Rollup keep changing the output it seems).

**Pull request closed without merging**
