### PR TITLE
[Fizz] experimental_useEvent

### PR DESCRIPTION
**Pull request by gaearon**
#25229 for Fizz.

The shim throws if you try to call it during SSR. It is shared between all event functions so that we can remove them from SSR with a compiler.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Removing them from SSR with a compiler isn’t going to be very impactful with the new approach anyway but sure.

**Comment by gaearon** [comment]
Is it worth returning a new function then for simplicity?

**Comment by sebmarkbage** [comment]
Probably still worth doing this. You shouldn't rely on identity of these anyway.

Looks like you have a test failure tho.

**Comment by gaearon** [comment]
> You shouldn't rely on identity of these anyway.

I could see that, but doesn’t this contradict what we’re saying about the identity being semantic?

**Comment by gaearon** [comment]
fixed the test

**Comment by sebmarkbage** [comment]
> I could see that, but doesn’t this contradict what we’re saying about the identity being semantic?

In this case, it's opted of being semantic. Since it shouldn't go into the dependency list of whatever is consuming it (which is something that being local ensures, btw) its identity doesn't matter. So technically it's not even guaranteed to be stable.

**Review by sebmarkbage — APPROVED** [review]

**Comment by gaearon** [comment]
>So technically it's not even guaranteed to be stable.

Why not enforce *that*, then?

**Comment by sebmarkbage** [comment]
We could return a new instance for every call in DEV on the client. That way it's enforced in one direction on the server and another direction on the client.

**Comment by gaearon** [comment]
Does this mean the linter should actively prevent you from adding it?

**Pull request merged**
