### PR TITLE
Pass `pendingProps` as argument in `createWorkInProgress`

### PR DESCRIPTION
**Pull request by zombieJ**
Update `createWorkInProgress` in `ReactFiber.js` to accept `pendingProps` as argument.

### CODE REVIEW

**Comment by gaearon** [comment]
[Here](https://github.com/zombieJ/react/blob/bd09b73e356e6148dd4ebd3b598904ccae774d2b/src/renderers/shared/fiber/ReactChildFiber.js#L291) is the callsite that hasn't been updated. It's confusing when functions take different number of arguments in different cases.

What do you think should happen? Should we pass `null` explicitly?

And why did Flow not catch the missing argument?

**Comment by zombieJ** [comment]
Hi @gaearon,
Yes. I think it may better if pass `null` as arguments.
Since react src code is made up of many modules. Function with same args is much eazy for understanding.

And for Flow, I'm not sure why it not catch.

Let me update the pr 😄

**Comment by gaearon** [comment]
I asked @acdlite to look at this when he finds time since it’s his TODO originally.

**Comment by gaearon** [comment]
(In any case let's defer this until after 16)

**Comment by acdlite** [comment]
Also let's wait until expiration times lands because it will be a pain to resolve the conflicts. https://github.com/facebook/react/pull/10426

**Comment by zombieJ** [comment]
Got it. I will update after 16 & #10426

**Comment by zombieJ** [comment]
@acdlite @gaearon ,
To avoid merge conflict, I open a new PR for this: https://github.com/facebook/react/pull/11296

Close old one

**Pull request closed without merging**
