### PR TITLE
Unify context implementations

### PR DESCRIPTION
**Pull request by acdlite**
## Based on #13139

Implements the legacy, string-based context API on top of the new context API. This doesn't save much in code size because most of the legacy stuff deals with merging and masking. Arguably, it's a conceptual complexity win.

I'm ambivalent about whether we land this.

### CODE REVIEW

**Comment by react-linter** [comment]
React: size: :small_red_triangle:+2.4%, gzip: :small_red_triangle:+1.7%

ReactDOM: size: :small_red_triangle:+0.8%, gzip: :small_red_triangle:+0.8%


  <details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 6731bfbed7964fdcb9b0080bce3edefc2a65d196...073d7d0478e76d5738969d27242886ce3213c358</p>


  
## react
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react.development.js | +0.8% | +0.8% | 56.81 KB | 57.26 KB | 15.82 KB | 15.95 KB | UMD_DEV
**react.production.min.js** | **:small_red_triangle:+2.4%** | **:small_red_triangle:+1.7%** | **6.86 KB** | **7.03 KB** | **2.91 KB** | **2.96 KB** | **UMD_PROD**
react.development.js | +0.9% | +0.9% | 51 KB | 51.46 KB | 13.99 KB | 14.12 KB | NODE_DEV
**react.production.min.js** | **:small_red_triangle:+2.8%** | **:small_red_triangle:+2.3%** | **5.86 KB** | **6.03 KB** | **2.52 KB** | **2.57 KB** | **NODE_PROD**
React-dev.js | +0.9% | +0.9% | 48.58 KB | 49.04 KB | 13.26 KB | 13.38 KB | FB_WWW_DEV
**React-prod.js** | **:small_red_triangle:+2.4%** | **:small_red_triangle:+1.9%** | **13.38 KB** | **13.71 KB** | **3.73 KB** | **3.8 KB** | **FB_WWW_PROD**

## react-dom
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-dom.development.js | +0.2% | -0.1% | 627.88 KB | 628.92 KB | 146.85 KB | 146.77 KB | UMD_DEV
**react-dom.production.min.js** | **:small_red_triangle:+0.8%** | **:small_red_triangle:+0.8%** | **95.52 KB** | **96.23 KB** | **30.85 KB** | **31.08 KB** | **UMD_PROD**
react-dom.development.js | +0.2% | -0.0% | 624 KB | 625.05 KB | 145.67 KB | 145.61 KB | NODE_DEV
**react-dom.production.min.js** | **:small_red_triangle:+0.7%** | **:small_red_triangle:+0.5%** | **95.51 KB** | **96.21 KB** | **30.39 KB** | **30.55 KB** | **NODE_PROD**
ReactDOM-dev.js | +0.2% | -0.0% | 630 KB | 631.49 KB | 143.94 KB | 143.9 KB | FB_WWW_DEV
**ReactDOM-prod.js** | **:small_red_triangle:+1.6%** | **:small_red_triangle:+0.9%** | **268.64 KB** | **273 KB** | **50.62 KB** | **51.06 KB** | **FB_WWW_PROD**
react-dom.profiling.min.js | +0.7% | +0.5% | 96.48 KB | 97.18 KB | 30.73 KB | 30.88 KB | NODE_PROFILING
ReactDOM-profiling.js | +1.6% | +0.9% | 271.26 KB | 275.62 KB | 51.2 KB | 51.66 KB | FB_WWW_PROFILING

## react-art
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-art.development.js | +0.3% | -0.1% | 411.86 KB | 412.9 KB | 92.41 KB | 92.32 KB | UMD_DEV
**react-art.production.min.js** | **:small_red_triangle:+0.9%** | **:small_red_triangle:+0.9%** | **82.66 KB** | **83.37 KB** | **25.45 KB** | **25.68 KB** | **UMD_PROD**
react-art.development.js | +0.3% | -0.1% | 343.84 KB | 344.88 KB | 75.27 KB | 75.21 KB | NODE_DEV
**react-art.production.min.js** | **:small_red_triangle:+1.5%** | **:small_red_triangle:+1.3%** | **47.64 KB** | **48.34 KB** | **14.83 KB** | **15.02 KB** | **NODE_PROD**
ReactART-dev.js | +0.4% | -0.0% | 332.64 KB | 334.14 KB | 70.01 KB | 70 KB | FB_WWW_DEV
**ReactART-prod.js** | **:small_red_triangle:+2.8%** | **:small_red_triangle:+1.8%** | **139.51 KB** | **143.47 KB** | **23.92 KB** | **24.36 KB** | **FB_WWW_PROD**

## react-test-renderer
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-test-renderer.development.js | +0.3% | -0.1% | 348.35 KB | 349.39 KB | 75.83 KB | 75.76 KB | UMD_DEV
**react-test-renderer.production.min.js** | **:small_red_triangle:+1.4%** | **:small_red_triangle:+1.3%** | **48.53 KB** | **49.23 KB** | **14.89 KB** | **15.09 KB** | **UMD_PROD**
react-test-renderer.development.js | +0.3% | -0.1% | 344.47 KB | 345.51 KB | 74.85 KB | 74.78 KB | NODE_DEV
**react-test-renderer.production.min.js** | **:small_red_triangle:+1.5%** | **:small_red_triangle:+1.6%** | **48.24 KB** | **48.94 KB** | **14.71 KB** | **14.94 KB** | **NODE_PROD**
ReactTestRenderer-dev.js | +0.4% | -0.0% | 347.69 KB | 349.19 KB | 73.58 KB | 73.58 KB | FB_WWW_DEV

## react-reconciler
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-reconciler.development.js | +0.3% | -0.1% | 333.16 KB | 334.2 KB | 71.39 KB | 71.31 KB | NODE_DEV
**react-reconciler.production.min.js** | **:small_red_triangle:+1.5%** | **:small_red_triangle:+1.6%** | **47.16 KB** | **47.85 KB** | **14.13 KB** | **14.35 KB** | **NODE_PROD**
react-reconciler-persistent.development.js | +0.3% | -0.1% | 331.78 KB | 332.82 KB | 70.83 KB | 70.74 KB | NODE_DEV
**react-reconciler-persistent.production.min.js** | **:small_red_triangle:+1.5%** | **:small_red_triangle:+1.6%** | **47.17 KB** | **47.86 KB** | **14.14 KB** | **14.36 KB** | **NODE_PROD**

## react-native-renderer
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
ReactNativeRenderer-dev.js | +0.3% | 0.0% | 466.84 KB | 468.37 KB | 102.79 KB | 102.82 KB | RN_FB_DEV
**ReactNativeRenderer-prod.js** | **:small_red_triangle:+1.8%** | **:small_red_triangle:+1.1%** | **203.5 KB** | **207.24 KB** | **35.74 KB** | **36.15 KB** | **RN_FB_PROD**
ReactNativeRenderer-dev.js | +0.3% | 0.0% | 466.57 KB | 468.1 KB | 102.73 KB | 102.76 KB | RN_OSS_DEV
**ReactNativeRenderer-prod.js** | **:small_red_triangle:+1.8%** | **:small_red_triangle:+1.2%** | **199.61 KB** | **203.25 KB** | **34.98 KB** | **35.39 KB** | **RN_OSS_PROD**
ReactFabric-dev.js | +0.3% | 0.0% | 457.12 KB | 458.65 KB | 100.38 KB | 100.42 KB | RN_FB_DEV
**ReactFabric-prod.js** | **:small_red_triangle:+1.9%** | **:small_red_triangle:+1.2%** | **191.87 KB** | **195.51 KB** | **33.57 KB** | **33.98 KB** | **RN_FB_PROD**
ReactFabric-dev.js | +0.3% | 0.0% | 457.15 KB | 458.68 KB | 100.4 KB | 100.43 KB | RN_OSS_DEV
**ReactFabric-prod.js** | **:small_red_triangle:+1.9%** | **:small_red_triangle:+1.2%** | **191.9 KB** | **195.54 KB** | **33.58 KB** | **34 KB** | **RN_OSS_PROD**
ReactNativeRenderer-profiling.js | +1.8% | +1.1% | 202.29 KB | 205.92 KB | 35.58 KB | 35.99 KB | RN_OSS_PROFILING
ReactFabric-profiling.js | +1.9% | +1.3% | 194.26 KB | 197.89 KB | 34.1 KB | 34.53 KB | RN_OSS_PROFILING
ReactNativeRenderer-profiling.js | +1.8% | +1.1% | 206.13 KB | 209.88 KB | 36.34 KB | 36.74 KB | RN_FB_PROFILING
ReactFabric-profiling.js | +1.9% | +1.2% | 194.22 KB | 197.85 KB | 34.08 KB | 34.51 KB | RN_FB_PROFILING

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by sophiebits** [comment]
Would this break unstable_renderSubtreeIntoContainer (#12493)?

**Comment by philipp-spiess** [comment]
@sophiebits 🤔I was commenting on the wrong issue in the morning. I had the very same question here: https://github.com/facebook/react/pull/13139#issuecomment-402033542 (just want to link it for completeness)

**Comment by acdlite** [comment]
To clarify, it’s not a breaking change. In my comment above I meant that we don’t plan to make `unstable_renderIntoSubtree` work with the `createContext` API. It still works with the legacy API in this PR, using the same flawed approach as in the current implementation.

**Comment by acdlite** [comment]
But I’d also prefer to just deprecate legacy context :D

**Comment by acdlite** [comment]
Not worth it

**Pull request closed without merging**
