### PR TITLE
Always set window.event in test environment

### PR DESCRIPTION
**Pull request by gaearon**
To avoid future surprises and confusion. Let's just do it everywhere.

I'm not sure this is exactly accurate and matches how the browser does it. Probably not. But close enough?

### CODE REVIEW

**Comment by acdlite** [comment]
Hmm. Will most users run their tests in an environment with `window.event`? What does JSDOM do? How will React Testing Library work?

Maybe we should warn if it's undefined? Though then we need some guidance for fixing it.

**Comment by gaearon** [comment]
Hmm yeah good point. The answer is I have no idea. I'll ask Twitter.

**Comment by gaearon** [comment]
>Maybe we should warn if it's undefined? 

How would you know you're in an event though?

>What does JSDOM do?

Seems like it doesn't do anything, as it's sort of a legacy property. At least our version doesn't.

>How will React Testing Library work?

I think RTL could do something like this as part of its setup. Or in its `fireEvent` wrapper.

**Review by crypt096 — APPROVED** [review]

**Comment by crypt096** [comment]
Please resolve conflicts.

**Pull request closed without merging**
