### PR TITLE
Highlight 'NOT' word in example page.

### PR DESCRIPTION
**Pull request by terry3**
Highlight the "not" word in the example page, in case the guy like me who do not recogniced the react was not work at all.

### CODE REVIEW

**Comment by jimfb** [comment]
Capitalized, bolded, and wrapped in asterisks... seems a bit aggressive.  I think I'd prefer one of the three.

I'm a little curious how you ran into this?  Did you checkout the source code from master, or how did the examples fail for you?

**Comment by jimfb** [comment]
Ping @terry3

 > I'm a little curious how you ran into this? Did you checkout the source code from master, or how did the examples fail for you?

**Comment by terry3** [comment]
Hi @jimfb 
So sorry for late to give you feedback.
And yes I checkout the source code from master.
The example failed just  because I just forget to build react.
Thank you!

**Comment by jimfb** [comment]
Sounds like other people don't have a strong opinion here.  Do you want to update the PR (`git commit --amend`, `git push -f`) to do one of the three (Capitalized / bolded / wrapped in asterisks) and then I think we can merge this.

**Comment by zpao** [comment]
Let's just use `<strong>`. We don't need `*` nor caps.

**Comment by terry3** [comment]
Hi @jimfb @zpao, please help to review this again, thanks!

**Comment by jimfb** [comment]
Looks good, thanks!

**Comment by zpao** [comment]
FYI: This isn't documentation in the same sense (doesn't end up on website) and we're not likely to do another 0.14.x release unless something major comes up, so not merging to stable.

**Pull request merged**
