### PR TITLE
Move no-jsx note in ReactElement tests

### LINKED ISSUE #6157: ReactElement tests "explicitly not using JSX"
The [`ReactElement` tests](https://github.com/facebook/react/blob/56c423afd66f7f1363dee87d25795418d5e74a30/src/isomorphic/classic/element/__tests__/ReactElement-test.js#L14-L15) have this at the beginning:

```js
// NOTE: We're explicitly not using JSX in this file. This is intended to test
// classic JS without JSX.
```

But there're a number of instances of JSX in the file. For example, [test # 1](https://github.com/facebook/react/blob/56c423afd66f7f1363dee87d25795418d5e74a30/src/isomorphic/classic/element/__tests__/ReactElement-test.js#L47-L49).

1. Should the note be removed or clarified?

1. Should JSX be purged from the file?

1. When adding tests to this file should they be free of JSX? In certain contexts but not others?

### PR DESCRIPTION
**Pull request by mxstbr**
Closes #6157, ping @jimfb

### CODE REVIEW

**Comment by jimfb** [comment]
There are a bunch of these that got missed.  Like `describe('when using parent that uses .createFactory()'`

**Comment by mxstbr** [comment]
I only did those where it makes sense, when explicitly mentioning `createFactory`, `createElement` etc. in the test description it feels like a repetition to have the note there as well.

**Comment by jimfb** [comment]
:+1:

**Comment by jimfb** [comment]
Thanks @mxstbr!

**Comment by mxstbr** [comment]
Sure thing @jimfb, glad to be of help!

**Pull request merged**
