### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Gpx**

### CODE REVIEW

**Comment by Aweary** [comment]
@Gpx thanks!

**Comment by abigsmall** [comment]
@aweary hi, apologies if commenting on an already merged PR is not the right venue for this, but I was curious as to how come the [live docs](https://facebook.github.io/react/contributing/implementation-notes.html) still has the typo pre-PR, given that the PR was merged in October? is there a set release schedule for the docs?

**Comment by aweary** [comment]
@abigsmall thanks for pinging me, we use the `Documentation: needs merge to stable` label to queue up PRs that have changes that need to be published. I added the wrong label after merging, so it wasn't caught.

It should be out the next time we we update the docs page!

**Comment by abigsmall** [comment]
ahh, that’s how it works! no problem, thanks for the info!

**Pull request merged**
