### PR TITLE
Clarify that indexes should not be used as keys

### PR DESCRIPTION
**Pull request by Bear-Foot**
Answers to https://github.com/facebook/react/issues/6339.

I would really appreciate any insights about how to make this more concise. Maybe code isn't the best way to make people understand ?

### CODE REVIEW

**Comment by gaearon** [comment]
Side note: there *are* valid reasons to use indexes as keys but those are rare cases. For example, if you implement a virtualized list with limited number of real items, you actually *want* them to be reused.

**Comment by Bear-Foot** [comment]
Sorry but I didn't fully understand. Should I add what you wrote to my PR ?

Also I did an [http://codepen.io/bear-foot/pen/VazeLq](example on Codepen), is it ok to add codepens in docs ?

**Comment by jedwards1211** [comment]
The reason the wrong text shows in the wrong input in that example is not just that they're keyed with indices, but that the inputs are uncontrolled components.  I'm more inclined to think that *uncontrolled components may be an anti-pattern*.  I think this should be considered carefully before advising against index keys.

**Comment by Bear-Foot** [comment]
@jedwards1211 I see what you mean. I think in your case your cannot avoid using [keyed fragments](https://facebook.github.io/react/docs/create-fragment.html).

**Comment by jedwards1211** [comment]
@Bear-Foot that would work in this case, but really I wouldn't go to such lengths.  Rather, I just avoid using uncontrolled components.  They're another manifestation of internal state that makes the app less predictable because uncontrolled components don't always render exactly what you pass in.

**Comment by gaearon** [comment]
Closing as outdated, but thanks for your work! We now have more info about using keys in docs.

**Pull request closed without merging**
