### PR TITLE
Add destructors to pooled classes in ReactChildren

### PR DESCRIPTION
**Pull request by spicyj**
And make destructors mandatory so we're less likely to forget again.

### CODE REVIEW

**Comment by spicyj** [comment]
Note to self: a couple internal users of this will need to be fixed.

**Comment by zpao** [comment]
Note to @spicyj: we should add a test that makes sure we expect an error when a destructor doesn't exist

**Comment by spicyj** [comment]
I mean, I don't care *that* much!

**Comment by spicyj** [comment]
spicyj requested review of #4720: Add destructors to pooled classes in ReactChildren.
spicyj added a comment to #4720: Add destructors to pooled classes in ReactChildren.

I am finding hard to imagine a scenario in which adding a test for this would really help. We already have a test making sure the destructor is called if present; no one will accidentally reintroduce an `if (instance.destructor)` and if they're adding it back on purpose they'd just as soon delete the test checking that it's required.

**Comment by zpao** [comment]
The scenario is that one of us comes along, gets an error in their class which doesn't have a destructor, and decides that PooledClass must need a null check, then gets it reviewed by somebody who didn't see this discussion. They ran the tests and nothing failed so assumed it's an ok change to make since it didn't break expectations. At least if they delete a test they have to acknowledge that they are changing expected behavior.

**Comment by spicyj** [comment]
But who would add a null check? All pooled classes store some sort of data and thus need a destructor so it wouldn't make sense to make it optional again.

But okay, I'll add a test.

**Comment by spicyj** [comment]
^^

**Comment by zpao** [comment]
👍

**Pull request merged**
