### PR TITLE
Added fb.me url to error message.


### PR DESCRIPTION
**Pull request by jsfb**
Added fb.me url to error message.

### CODE REVIEW

**Comment by zpao** [comment]
Let's make these `fb.me/react-something-all-lowercase-because-urls-really-shouldnt-be-case-sensitive`. And actually in the past we've always done `fb.me/react-warning-whatever`. I noticed we didn't do that for fb.me/react-context-by-parent, but I think we might want to switch that one too for consistency.

**Comment by jsfb** [comment]
The urls are not guessable anyway, and are only discoverable through react, so consistency-for-the-sake-of-consistency (ie., the "react-" prefix) seems pointless.  Having all lower case urls, meh, ok.  Regardless, fixed.  Ready to merge?

**Comment by spicyj** [comment]
FWIW I agree that the lowercase and consistent `fb.me/react-warning-` prefix is nice for aesthetics.

**Comment by zpao** [comment]
Let's use `react-warning-*` and then fix the other case as well (either here or in another PR)

**Comment by jsfb** [comment]
@zpao Ok, using react-invariant as per conversation.

Ready to merge?

**Comment by zpao** [comment]
:+1:

**Pull request merged**
