### PR TITLE
Implement support for all SVG elements

### PR DESCRIPTION
**Pull request by andrew-d**
This takes the list of SVG elements from the W3 specification
(http://www.w3.org/TR/SVG/eltindex.html) and adds support for all of
them.

In addition, added support for additional SVG attributes.

Note: some of this work is based on @zpao's [existing branch](https://github.com/zpao/react/compare/fuck-svg).  Also, the commit applies cleanly on top of the 0.12-stable branch, [if anyone is interested](https://github.com/andrew-d/react/tree/andrew-full-svg-support-0.12).

### CODE REVIEW

**Comment by andrew-d** [comment]
For reference, here's the `build/` directory after running `grunt clean build` (to see the built size):

```
drwxr-xr-x   12 andrew  andrew     408 Jan 21 14:01 .
drwxr-xr-x   39 andrew  andrew    1326 Jan 21 13:59 ..
-rw-r--r--    1 andrew  andrew  475037 Jan 21 14:00 JSXTransformer.js
drwxr-xr-x  172 andrew  andrew    5848 Jan 21 14:00 modules
drwxr-xr-x    8 andrew  andrew     272 Jan 21 14:01 npm-react
drwxr-xr-x    8 andrew  andrew     272 Jan 21 14:01 npm-react-tools
-rw-r--r--    1 andrew  andrew  270284 Jan 21 14:01 react-tools.tgz
-rw-r--r--    1 andrew  andrew  654376 Jan 21 14:00 react-with-addons.js
-rw-r--r--    1 andrew  andrew  136610 Jan 21 14:01 react-with-addons.min.js
-rw-r--r--    1 andrew  andrew  595499 Jan 21 14:00 react.js
-rw-r--r--    1 andrew  andrew  126579 Jan 21 14:00 react.min.js
-rw-r--r--    1 andrew  andrew  601885 Jan 21 14:01 react.tgz
```

**Comment by andrew-d** [comment]
Worth noting that, unless I comment out the attributes listed below in `SVGDOMPropertyConfig.js`, [this error](https://github.com/facebook/react/blob/54c82da15f6b4717425edbf68e23ae82583a50af/src/browser/ui/dom/DOMProperty.js#L74) is triggered.  It appears that this is since they conflict with the HTML attributes in `HTMLDOMPropertyConfig.js`.  I'm not as familiar with the internals of React as I could be, so is simply removing the below attributes the appropriate way of handling this?

- `class`
- `height`
- `lang`
- `method`
- `title`
- `type`
- `width`

**Comment by eliseumds** [comment]
+1

**Comment by shaunbent** [comment]
+1

**Comment by gaearon** [comment]
I wonder which parts of this are relevant after we started passing all SVG attributes through in #5714.

**Comment by jimfb** [comment]
This diff is over a year old, has merge conflicts, last comment was over a month ago, https://github.com/facebook/react/pull/5714 merged over a month ago.  If there is anything actionable, we can open a new issue/PR.

**Pull request closed without merging**
