### PR TITLE
set __DEV__ feature flag for development asserts

### PR DESCRIPTION
**Pull request by chicoxyzzy**
|file|raw size before|file|raw size after|
--------------|-------------|---------------|------
react.min.js | 117468 | react.min.js|113800|
react-with-addons.min.js | 127498|react-with-addons.min.js|123438|

```
   raw     gz Compared to master @ 8d5838af728a425ca17595c074b6d3ef16015eda
     =      = build/JSXTransformer.js
     =      = build/react-test.js
 +7068   +506 build/react-with-addons.js
 -4060  -1173 build/react-with-addons.min.js
 +6667   +430 build/react.js
 -3668  -1054 build/react.min.js
```

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
|file|size before|file|size after|
--------------|-------------|---------------|------
react.min.js | 117468 | react.min.js|113800|
react-with-addons.min.js | 127498|react-with-addons.min.js|123438|


```
   raw     gz Compared to master @ 8d5838af728a425ca17595c074b6d3ef16015eda
     =      = build/JSXTransformer.js
     =      = build/react-test.js
 +7068   +506 build/react-with-addons.js
 -4060  -1173 build/react-with-addons.min.js
 +6667   +430 build/react.js
 -3668  -1054 build/react.min.js
```

**Comment by zpao** [comment]
Our philosophy is that runtime behavior should not be meaningfully impacted by environment. By stripping out errors from production you have different runtime behavior. Problems that stop execution in dev will run with unpredictable behavior in prod. Thanks for the effort but we aren't going to do this.

**Comment by chicoxyzzy** [comment]
if so why there are already places in master branch where errors are stripped away? also there are some warnings I cutted off which not breaking behavior. BTW these behaviors should be covered by tests then

**Comment by chicoxyzzy** [comment]
https://github.com/facebook/react/blob/master/src/browser/ui/ReactMount.js#L579 is this correct?

**Comment by zpao** [comment]
There should be no places where we throw errors (`invariant`) in dev that we don't throw in prod. If there are, then I think we made a mistake. Like that one in ReactMount, we should either make that a warning or make sure we do that check outside the dev block.

`warning`s we're a bit less consistent with. Some of the ones you changed in here are already behind __DEV__ checks because the function is only called in dev.

**Comment by chicoxyzzy** [comment]
@zpao ok I'll try to

IMHO these lines makes dev and production code inconsistent:
https://github.com/facebook/react/blob/master/src/browser/ui/ReactMount.js#L579
https://github.com/facebook/react/blob/master/src/event/EventPluginUtils.js#L30
https://github.com/facebook/react/blob/master/src/event/EventPluginUtils.js#L59
https://github.com/facebook/react/blob/master/src/event/EventPluginUtils.js#L87
https://github.com/facebook/react/blob/master/src/event/EventPluginUtils.js#L134
https://github.com/facebook/react/blob/master/src/event/EventPluginUtils.js#L175
https://github.com/facebook/react/blob/master/src/event/EventPluginHub.js#L112
https://github.com/facebook/react/blob/master/src/event/EventPluginHub.js#L118
https://github.com/facebook/react/blob/master/src/event/EventPropagators.js#L40

should vendor files be fixed too?
https://github.com/facebook/react/blob/master/src/vendor/core/emptyObject.js#L16
https://github.com/facebook/react/blob/master/src/vendor_deprecated/core/copyProperties.js#L24

I think this is inconsistent as well:
https://github.com/facebook/react/blob/master/src/vendor/core/invariant.js#L26

IMHO [this](https://github.com/facebook/react/blob/master/src/browser/eventPlugins/AnalyticsEventPluginFactory.js#L175) and [this](https://github.com/facebook/react/blob/master/src/browser/eventPlugins/AnalyticsEventPluginFactory.js#L199) are only places where `__DEV__` flag should cut `invariant`. Should it?

Also as I see `warning` has `__DEV__` flag itself
https://github.com/facebook/react/blob/master/src/vendor/core/warning.js#L25
should it be cutted on top level as well?

**Comment by zpao** [comment]
I haven't looked closely but a couple quick things...

1. invariant using __DEV__ is fine, we do that so we can show a useful message when the error is thrown. In prod we strip out the message arg and depend on the generic message lower.
2. warning is fine too for mostly the same reasons. We require a message in dev but make the whole thing a noop in prod. There is no program logic difference
3. Object.freeze in emptyObject is a special case to catch potential developer error so nobody depends on emptyObject being mutable. This (and other vendor files) are actually shared across FB projects so those are a bit harder to enforce our philosophy
4. We're going to remove copyProperties so don't worry about that one.
5. I think you're right that the places in your top file group should get fixxed. Thanks for finding them. I haven't had a chance to look thoroughly or figure out which is the right route (warning vs invariant).

**Comment by chicoxyzzy** [comment]
@zpao ok thank you I'll try my best to fix inconsistent places. Just for clarification, I was not very clear saying 
>Also as I see warning has __DEV__ flag itself
https://github.com/facebook/react/blob/master/src/vendor/core/warning.js#L25
should it be cutted on top level as well?

There are two approaches in current master:
- using `if (__DEV__)` statement before `warning`
- and not using it (in this case warning becomes noop)
Does it matter to add `__DEV__` flag before `warning` or not?

**Comment by chicoxyzzy** [comment]
@zpao so I choose to use `console.log` because I believe it semantically closer to `throw` then `warning`'s `console.warn` #2868

**Comment by telkomsel666** [comment]
#1~
17 Jan 2015 09:14, "Sergey R" <notifications@github.com> menulis:

**Pull request closed without merging**
