### PR TITLE
Simplify CSS shorthand property warning

### PR DESCRIPTION
**Pull request by sophiebits**
I figured out a simpler way to do #14181. It does allocate some but I think that's OK. Time complexity might even be better since we avoid the nested loops the old one had.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Are we ok releasing the first one in a patch release?

I think we should probably add this warning behind a feature flag since it is likely to be very noisy.

**Comment by sophiebits** [comment]
I don't think this will be very noisy. I think it basically always indicates a real bug.

**Comment by sebmarkbage** [comment]
In that case we should first turn it on internally and verify that assumption.

**Comment by sophiebits** [comment]
Happy to. If we want to cut a patch first we can disable it temporarily I guess.

**Comment by gaearon** [comment]
@astr0sl0th This PR has been merged a year ago. Please don’t leave reviews on old PRs, you’re spamming everyone’s notifications.

**Pull request merged**
