### PR TITLE
DevTools should inject XHTML pages too (not just HTML)

### LINKED ISSUE #22834: [DevTools Bug]: CDN-based site not working
### Website or app

https://lcdev.shaped.ca

### Repro steps

Dev tools not working in FF or Chrome, says "This page doesn't appear to be using react".

React is included via CDN as shown on react website https://reactjs.org/docs/cdn-links.html:
``
	<script crossorigin="anonymous" src="https://unpkg.com/react@17/umd/react.development.js"></script>
``

Web Console on said page says:
``
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
``

### How often does this bug happen?

Every time

### DevTools package (automated)

_No response_

### DevTools version (automated)

_No response_

### Error message (automated)

_No response_

### Error call stack (automated)

_No response_

### Error component stack (automated)

_No response_

### GitHub query string (automated)

_No response_

### PR DESCRIPTION
**Pull request by bvaughn**
Resolves #22834

- [x] Verified that https://lcdev.shaped.ca works after this change.
- [x] Verified the original fix for #17739 does not regress by visiting https://www.w3schools.com/xml/note.xml.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
What's the regression test? That link doesn't include React on the page so how do you test it.

Interesting regardless, because I was thinking we'd stop supporting XHTML documents. Not sure everything in Fizz works. 😬

**Review by lunaruan — APPROVED** [review]
Stamping because this looks fine but maybe wait on Seb's discussion about whether or not to allow XHTML documents to land?

**Comment by bvaughn** [comment]
> What's the regression test?

The regression test was viewing https://www.w3schools.com/xml/note.xml to make sure syntax highlighting wasn't broken.

> That link doesn't include React on the page so how do you test it.

React is loaded on the page, though nothing is rendered.

I cheated a bit and confirmed that `__REACT_DEVTOOLS_GLOBAL_HOOK__` was defined on the page _after_ my change. (Before it was undefined b'c of the content-type check.)

(I can't actually login and test the site.)

**Comment by bvaughn** [comment]
I think that until we make the decision to _not_ support XHTML, it makes sense for DevTools to support it. (Even if Fizz decides not to support it, I'm still not sure it would make sense for DevTools to intentionally _not_ support it.)

Any concerns to merging this PR for now, @sebmarkbage? Happy to follow up with a larger discussion.

**Comment by sebmarkbage** [comment]
No concerns. Even if we don't support it, it makes sense for DevTools to keep supporting old versions.

I still don't quite get what broke on a page that doesn't have React on it?

It doesn't break syntax highlighting for me. Is there something in DevTools that can throw an error or something on that page? Can that happen in other scenarios if there are missing types?

**Comment by bvaughn** [comment]
> I still don't quite get what broke on a page that doesn't have React on it?

Even after login, DevTools would not "work" on this page because DevTools would never define its global hook for the content-type (XHTML).

> It doesn't break syntax highlighting for me. Is there something in DevTools that can throw an error or something on that page? Can that happen in other scenarios if there are missing types?

This was an old quirk (fixed two years ago) where DevTools broke syntax highlighting for certain content types (like XML) when it injected itself, so we started only injecting for HTML.

**Comment by sebmarkbage** [comment]
> This was an old quirk (fixed two years ago) where DevTools broke syntax highlighting for certain content types (like XML) when it injected itself, so we started only injecting for HTML.

Ah, I get it. It was an old regression test. Not a newly added one. Makes sense.

**Pull request merged**
