### PR TITLE
React -> ReactDOM for render() and findDOMNode()


### PR DESCRIPTION
**Pull request by jimfb**
React -> ReactDOM for render() and findDOMNode()

### CODE REVIEW

**Comment by spicyj** [comment]
Do the in-website examples (docs/_js) still run okay?

**Comment by jimfb** [comment]
Are those the examples on the homepage (http://localhost:4000/react/)?  If so, yes, they ran happily.

**Comment by spicyj** [comment]
Yes. You need to run `rake` in docs/ to rebuild the compiled JS files.

**Comment by jimfb** [comment]
Done.

**Pull request merged**
