### PR TITLE
Fixed issue for better bundles,chunks and workers name in devtools-extensions.

### LINKED ISSUE #22115: DevTools: Better Bundle Names for Dynamically Imported Modules
In the DevTools extension, webpack currently uses an automatically assigned ID as the chunk name for dynamically imported modules (ie. `parseHookNames` and associated code will get bundled into `6.js`).

We've tried adding `chunkFilename: '[name].js'` to `output` in `webpack.config.js` and  magic comments (ie.`/* webpackChunkName: "parseHookNames" */`) to the dynamic import to fix, but neither works.

### PR DESCRIPTION
**Pull request by akgupta0777**
## Summary

This Pull request fixes #22115 

## How did you test this change?
 ran `yarn test:chrome `

## Demonstration of the proposed changes
Using magic comments on dynamic imports fixes the chunk names properly. 
For workers I added a name property to the workerize-loader in webpack.config.js

## Result
Now the files after building devtools-extensions are as follows.
image

### CODE REVIEW

**Comment by akgupta0777** [comment]
@bvaughn I ran all the tests locally they passed all but here are failing. Can you help me.

**Comment by bvaughn** [comment]
@akgupta0777 Unfortunately the way our Npm cache is implemented is pretty flaky in CI right now. Those failures aren't test related, and I've restarted them.

**Comment by akgupta0777** [comment]
Thanks @bvaughn , Please review

**Review by bvaughn — APPROVED** [review]
This does fix the file names. I can confirm by:
```sh
# packages/react-devtools-extensions

$ rm -rf chrome/build

$ yarn build:chrome

$ ls -l chrome/build/unpacked/build

-rw-r--r--  1 bvaughn  staff     8112 Sep 15 13:42 background.js
-rw-r--r--  1 bvaughn  staff     5345 Sep 15 13:42 contentScript.js
-rw-r--r--  1 bvaughn  staff   305003 Sep 15 13:42 importFile.worker.worker.js
-rw-r--r--  1 bvaughn  staff   343161 Sep 15 13:42 injectGlobalHook.js
-rw-r--r--  1 bvaughn  staff  2172594 Sep 15 13:42 main.js
-rw-r--r--  1 bvaughn  staff     4293 Sep 15 13:42 panel.js
-rw-r--r--  1 bvaughn  staff  2712294 Sep 15 13:42 parseHookNames.chunk.js
-rw-r--r--  1 bvaughn  staff  2560010 Sep 15 13:42 parseSourceAndMetadata.worker.worker.js
-rw-r--r--  1 bvaughn  staff   440919 Sep 15 13:42 react_devtools_backend.js
-rw-r--r--  1 bvaughn  staff   320673 Sep 15 13:42 renderer.js
-rw-r--r--  1 bvaughn  staff    55301 Sep 15 13:42 vendors~parseHookNames.chunk.js
```

**Comment by bvaughn** [comment]
Thank you!

**Pull request merged**
