### PR TITLE
switch links to open GH pages, not 404

### PR DESCRIPTION
**Pull request by davidkorff**
switched the current urls:
https://github.com/facebook/react/blob/master/docs/docs/hello-world.html
https://github.com/facebook/react/blob/master/docs/tutorial/tutorial.html
To the GitHub pages route. Currently they render a 404 page. 
https://facebook.github.io/react/docs/hello-world.html
https://facebook.github.io/react/tutorial/tutorial.html

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`).
6. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
7. If you added or removed any tests, run `./scripts/fiber/record-tests` before submitting the pull request, and commit the resulting changes.
8. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

### CODE REVIEW

**Comment by aweary** [comment]
Thanks again @davidkorff, but these URLs should remain relative so the docs are portable (in case the domain ever changes). We don't recommend reading the docs from the Github repo, as they're meant to be viewed after they've been compiled.

A good rule of thumb is that if it works on https://facebook.github.io/react/ then it's likely OK.

**Comment by davidkorff** [comment]
Oh, wow. That’s embarrassing. Thanks so much for explaining it.

**Comment by bvaughn** [comment]
Nothing to be embarrassed about, @davidkorff! 😄

**Comment by aweary** [comment]
Yeah, no need to be embarrassed, we really appreciate the effort regardless 👍

**Pull request closed without merging**
