### PR TITLE
Fixed invalid prop type warning to be more specific.

### PR DESCRIPTION
**Pull request by NicBonetto**
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. Run `yarn` in the repository root.
3. If you've fixed a bug or added code that should be tested, add tests!
4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.
5. Format your code with [prettier](https://github.com/prettier/prettier) (`yarn prettier`).
6. Make sure your code lints (`yarn lint`). Tip: `yarn linc` to only check changed files.
7. Run the [Flow](https://flowtype.org/) typechecks (`yarn flow`).
8. If you haven't already, complete the CLA.

**Learn more about contributing:** https://reactjs.org/docs/how-to-contribute.html

### CODE REVIEW

**Comment by NicBonetto** [comment]
#11289

**Comment by gaearon** [comment]
The person might still be trying to pass it as a string though. We should probably suggest both cases.

>If you intentionally tried to pass a boolean, pass it as a string instead: %s="%s". If you mean to conditionally pass an attribute, use a ternary expression: %s={condition ? value : null}.

**Comment by NicBonetto** [comment]
Would you like me to change the test cases as well? An example would be change ReactDOMComponent-test.js line 2058 from:
`Warning: Received `true` for non-boolean attribute `whatever``
to:
`Warning: If you intentionally tried to pass a boolean, pass it as a string instead: true=\"whatever\". If you mean to conditionally pass an attribute, use a ternary expression: 
        in div (at ReactDOMComponent-test.js:2053)={condition ? value : null}.`

**Comment by gaearon** [comment]
Yes, we would need to fix the test cases. But the message you provided is wrong. When I said `%s` I meant that you'd need to substitute the attribute name and value there so that it looks like (for example if attribute is `my-attribute` is `null`):

>If you intentionally tried to pass a boolean, pass it as a string instead: my-attribute="true". If you mean to conditionally pass an attribute, use a ternary expression: my-attribute={condition ? value : null}.

If you read the message you posted, it appears completely broken. So I didn't mean that message. 😉  Please approach this from a user perspective: would a message with stack in the middle like `(at ReactDOMComponent-test.js:2053)={condition ? value : null}` make sense to you? Probably not. Then this is not what should be done.

**Comment by NicBonetto** [comment]
Closing this issue, will reopen another with the correct code in a few minutes.

**Pull request closed without merging**
