### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Kewri**
Syntax error and unexpected tokens has been handled.

### CODE REVIEW

**Review by hieueuro — COMMENTED** [review]
https://github.com/hieueuro

**Review by crypt096 — APPROVED** [review]

**Comment by hieueuro** [comment]
Ok

**Comment by bvaughn** [comment]
This looks like maybe there's been some confusion. Not sure what the purpose of this PR is. Just testing how it works?

Going to close it.

**Comment by hieueuro** [comment]
Ok good

**Pull request closed without merging**
