### PR TITLE
chore: update to latest release of babel

### PR DESCRIPTION
**Pull request by SimenB**
## Summary

Fixes a couple of the test failures from #17896 and reduces the diff.

Updated babel by deleting everything `@babel/*` in the lockfile and running `yarn`

(Ironically my PR to Babel which broke the test: https://github.com/babel/babel/pull/10361)

## Test Plan

Green CI

### CODE REVIEW

**Comment by necolas** [comment]
Thanks. We should probably bump the base versions of the dependencies in the `package.json` too https://github.com/facebook/react/blob/master/package.json#L7

**Comment by SimenB** [comment]
@necolas any particular reason to? They're all in `devDependencies` so not user facing at all, meaning the version in the lockfile should be all that matters.

**Comment by trueadm** [comment]
@SimenB We should update the package.json `devDependencies` anyway, but also it makes sense for users who might not be using Yarn?

**Comment by SimenB** [comment]
@necolas @trueadm updated

**Comment by trueadm** [comment]
Looks good, thank you!

**Pull request merged**
