### PR TITLE
add compressionImageComponent

### PR DESCRIPTION
**Pull request by hamdymohamedak**

### CODE REVIEW

**Comment by josephsavona** [comment]
What is the intent of this change? The directory you’re adding to isn’t actively used for anything, and it isn’t clear what this fixture is meant to test. We’re happy re-open if you provide more context.

**Comment by hamdymohamedak** [comment]
Compression Image Component can compress any img at your App to webp and you can control the compress value with quality prop

**Comment by hamdymohamedak** [comment]
Maybe i set a code at wrong path 
Tell me please where can i set a built in Component

**Comment by josephsavona** [comment]
Thanks, but we only accept substantial contributions that have a concrete purpose for adding to the repository.

**Pull request closed without merging**
