### PR TITLE
Add tabs to installation page (#9275, #9277)

### LINKED ISSUE #9275: Confusingly structured Installation section
Hey guys, I want to bring out some issue in docs, Install section. https://facebook.github.io/react/docs/installation.html. This happened to me and one of my colleagues and I guess others may get confused too.

For example I want to use create-react-app approach for installing react.
This means I need to follow ONLY this section right: https://facebook.github.io/react/docs/installation.html#creating-a-single-page-application

But after my colleague followed that, he then thought had do follow things like this too:
https://facebook.github.io/react/docs/installation.html#enabling-es6-and-jsx

In other words the installation docs, doesn't say that if you follow the first link I gave for example above, following second link is not necessary as create-react-app includes Babel for example.
Isn't it?

I think the doc has to mention that it is an OR approach, either use this section, or this, etc.

### PR DESCRIPTION
**Pull request by markspolakovs**
This adds tabs for create-react-app and existing apps to the installation section of the docs. The tab implementation is a simplified version of React Native's installation page (https://github.com/facebook/react-native/blob/master/docs/GettingStarted.md).

Fixes #9275.

### CODE REVIEW

**Comment by gaearon** [comment]
Thanks for jumping on this! What do you think about adding a second level of tabs for "new application" with different bundlers? Then we could provide minimal instructions for each. I guess it's a bit out of scope but still wondering if you'd like to work on this.

**Comment by markspolakovs** [comment]
@gaearon I could have a crack at it, although it might require a bit of monkeying with the void-to-container `<block />` script. Could you take a look at this PR now, so that I don't make the same mistakes twice? Thanks 😄

**Comment by gaearon** [comment]
Thanks! I looked at it, and I noticed you didn’t have the right colors for the links, and a few other issues. I am very short on time right now so I decided to just tweak it to use the exact copy of script RN page uses.

**Comment by markspolakovs** [comment]
Alright, cool. When you have some time, could you let me know what you'd have had changed? I'll try to implement the second level of tabs when I get a chance.

**Pull request merged**
