### PR TITLE
Fix children to be a prop in the blog post example

### PR DESCRIPTION
**Pull request by gaearon**
Whoops. Other examples seem fine.

cc @zpao

### CODE REVIEW

**Comment by cody** [comment]
This looks wrong to me too:

On line 12: In this traditional UI model, it is up to you **to** take care

On line 165 do the braces make sense? *is-a* ()

**Comment by gaearon** [comment]
Thanks @cody, fixed those too.

**Comment by gaearon** [comment]
ping @spicyj, can I merge this?

**Comment by spicyj** [comment]
Sure. Then `git cherry-pick -x` on the 0.14-stable branch (or tag it with "needs merge to stable" and someone will do it… eventually).

**Comment by gaearon** [comment]
Just did this. Should I also this for my other PR (#5702)?

**Comment by spicyj** [comment]
Just for the website. Shouldn't matter for the other one because everyone should be looking at master on github.

**Comment by gaearon** [comment]
Got it.

**Pull request merged**
