### PR TITLE
[WIP] Add Appveyor Badge

### PR DESCRIPTION
**Pull request by raphamorim**
Reference: #11605 

Hi @gaearon, we still need to configure AppVeyor for facebook/react 🤓
I think in something like: https://ci.appveyor.com/project/facebook/react

### CODE REVIEW

**Comment by gaearon** [comment]
Kicked off the build, let's see if it works

**Comment by raphamorim** [comment]
Ok **crossed fingers**

**Comment by gaearon** [comment]
This fails:

screen shot 2017-11-29 at 01 54 23

Wanna look into making a fix? My guess is you can't just run `yarn`, have to add `.cmd` on Windows.

**Comment by raphamorim** [comment]
Ok, I'll work on it.

**Comment by gaearon** [comment]
I fixed AppVeyor. I don't think we'll want a badge though. It's already getting very crowded.
We can still see AV status in the commit list so that should help catch regressions.
Thanks though!

**Comment by raphamorim** [comment]
Make sense @gaearon,
Sorry for delay and thanks 👍

**Comment by gaearon** [comment]
If you're interested, https://github.com/facebook/react/issues/11703

**Comment by raphamorim** [comment]
Nice, can you assign it for me?

**Pull request closed without merging**
