### PR TITLE
Add support for SVG marker element

### PR DESCRIPTION
**Pull request by jonase**
Support for the SVG marker element as mentioned in https://github.com/facebook/react/issues/1657#issuecomment-47669892. I followed @brandonbloom's patch where he added support for the [ellipse element](https://github.com/facebook/react/pull/1675)

### CODE REVIEW

**Comment by RobertWarrenGilmore** [comment]
:+1: This would be very helpful.

**Comment by jboolean** [comment]
+1

**Comment by frzng** [comment]
It seems this issue became obsolete before merging. I have created a new PR #5398.

**Comment by gaearon** [comment]
Thank you for the PR, and sorry about the long wait. Now that #5714 is merged, all attributes on SVG elements will be passed through as is, with no need for the whitelist. I'm closing this but please let me know if you have any troubles in master.

**Pull request closed without merging**
