### PR TITLE
Add onTransitionStart, onTransitionEnd, and onTransitionCancel support

### PR DESCRIPTION
**Pull request by milesj**
I got bored and thought I would try adding support for these events. This is my attempt so far.

The current code works, as I can log the start/end/cancel events correctly. What I don't know how to do properly is to monitor changes on the style object. If you know a better way, I'm all ears!

### CODE REVIEW

**Comment by jimfb** [comment]
@spicyj @syranide

**Comment by milesj** [comment]
Things I've tried so far:

- Wrap the `style._onChange` function so that I can monitor when the style attribute changes. This doesn't actually work 100% of the time, and it's also non-standard since it's based on cssom/cssstyle. This also doesn't support styles that have changed via class names being toggled.

- Tried wrapping `ReactDOMComponent._updateDOMProperties` so that I have instant access to style/class changes, but this doesn't work since the object is marked with `Object.preventExtensions`. Bummer, this would be the best solution.

- Tried hooking into the `ReactReconcileTransaction` transaction within `ReactDOMComponent`, but have yet to find a way to easily access it. I'm guessing there's no public API.

- Possibly hook into `ReactUpdates` somehow? Still not familiar with how exactly it works.

The more I look into this and work on it, the more I realize why this hasn't been supported yet. My best bet right now is to modify `ReactDOMComponent` so that I can monitor for changes. Any input would be appreciated!

**Comment by jimfb** [comment]
Ping @spicyj @syranide

**Comment by milesj** [comment]
I think I found a nice way to hook into this. Will push a commit shortly.

**Comment by milesj** [comment]
Ok, pushed. I added a `TransitionUtils` object that hooks into a `ReactDOMComponent`s transaction cycle, allowing me to listen to mounts and updates.

The biggest issue now is that `ReactDOMComponent._nativeNode` is not an actual DOM element, and thus it's `style` object is incorrect. I can't use `getComputedStyle()` correctly. Is there no way to access the actual DOM element?

**Comment by milesj** [comment]
So I tested this in a browser instead of JSDOM, and it does work how I expected it to. 

However, there is no way to run sanity checks on the previous and current styles as `getComputedStyle()` returns the computed styles at call time, before the transition starts, not what it *will* be once the transition finishes. So at this point, both values are always equal.

Such a bummer. Guess I will just go the easy route and bind the native DOM event.

**Comment by milesj** [comment]
Ended up going with this approach: https://github.com/facebook/react/pull/5835

**Pull request closed without merging**
