### PR TITLE
Inline dev-only requires

### PR DESCRIPTION
**Pull request by gaearon**
This is inspired by @keyanzhang’s work in #7178 but without Rollup.
He noticed `ReactComponentTreeDevtool` and some other devtools get included into prod build.
This fixes it:

```
   raw     gz Compared to master @ 7d0801e1a085ef7c52b0cc0212404335fa75c717    
     =      = build/react-dom-server.js                                        
     =      = build/react-dom-server.min.js                                    
     =      = build/react-dom.js                                               
     =      = build/react-dom.min.js                                           
  +133    +22 build/react-with-addons.js                                       
 -3715  -1088 build/react-with-addons.min.js                                   
  +133    +18 build/react.js                                                   
 -3694  -1133 build/react.min.js  
```

Unfortunately it’s way too easy to regress on this. Maybe we should have a way of marking certain files as dev-only and then failing the build if they end up in production bundle?

### CODE REVIEW

**Comment by vjeux** [comment]
> Maybe we should have a way of marking certain files as dev-only and then failing the build if they end up in production bundle?

Should be easy to make it happen

```js
// file.js
require('assertOnlyIncludedInDev');

// assertOnlyIncludedInDev.js
if (!__DEV__) {
  throw 'This file should only be included in __DEV__';
}
```

**Comment by zpao** [comment]
@vjeux that doesn't fail the build process, just causes the final bundle to break in the browser. It will break FB though (except when inline-requires is on then it should be ok).

**Comment by vjeux** [comment]
@zpao hopefully there's at least going to be one test failing if the entire React bundle instant fatal :)

**Comment by gaearon** [comment]
If we add a check for the production bundle, there is still a potential pitfall: any lazy requires (which could be in prod as well) would not be caught.

**Comment by zpao** [comment]
> hopefully there's at least going to be one test failing if the entire React bundle instant fatal :)

There isn't. We don't have anything run tests on the bundles. Best chance would be running the examples but they all use the dev build.

**Comment by keyanzhang** [comment]
Haha, you beat me to it. Ideally we won't have lazy requires any more.

**Pull request merged**
