### PR TITLE
cloneElement: Added checker for undefined props

### PR DESCRIPTION
**Pull request by buoyantair**
Extending PR #13387  with revised changes.

### CODE REVIEW

**Comment by buoyantair** [comment]
@matthargett yes I need to write tests yet..

**Comment by buoyantair** [comment]
@matthargett Hi, I added the test. Do review :)

**Comment by buoyantair** [comment]
Bump!

**Comment by gaearon** [comment]
Thanks for the PR. Sorry for radio silence. While this is unfortunate, fixing this would be a breaking change and I don't think it's worth the churn at this point.

**Pull request closed without merging**
