### PR TITLE
Reject non-objects in spec/key path

### PR DESCRIPTION
**Pull request by stefk**
The `update` function currently accepts various malformed inputs in its `spec` parameter, leading to bad error reporting or buggy behaviour:

```js
update({a:[1, 2]}, null); 
// TypeError: Cannot convert undefined or null to object

update({a:[]}, []); 
// no error

update({a:[]}, [[]]); 
// {0: undefined, a: []}

update({a:[1, 2]}, {a: {$slice: [[0,1]]}}) 
// TypeError: Cannot read property '0' of undefined

```

This PR strengthens the first `invariant` in order to reject any spec/key path that is not a plain object.

### CODE REVIEW

**Comment by jimfb** [comment]
@yungsters Is this something you would want to take?

**Comment by gaearon** [comment]
I think we should take this. The current behavior with a bad spec is unspecified and inconsistently broken in weird ways.

However this will be a breaking change so if we don’t do this before 15, we might as well deprecate `react-addons-update` and never do it.

**Comment by gaearon** [comment]
However I think the warning message is misleading. It claims that “You provided a key path to update() that did not contain one of $push, $unshift, $splice, $set, $merge, $apply.”. However this is not the case for these invalid inputs:

```js
[{ $set: 3 }]

{
  a: { $set: 5 },
  b: null
}
```

While these are also invalid, they are invalid for different reasons (specs can’t be arrays). And I’m not sure we event want to error on a null spec, as just skipping it seems more useful for cases when the update object is created conditionally.

I’m marking this as needing changes. This might not land at all due it being a low priority and potentially breaking. However if you’d like to work on this, please make sure the error message reflects what the user needs to fix.

Thank you for contributing!

**Comment by stefk** [comment]
@gaearon, I think the original intent of the error message is to warn the user that he/she might have forget or mispell a command in the spec, like in:

 ```js
{ a: { b: 'c' }}
```
 or:

 ```js
{ a: { set: 'b' }}
```

Unfortunately, I can't see a way to keep that intent while providing another error for non-objects specs. The best I can think of would be to keep one invariant and slightly reword its message:

> You provided an invalid spec to update(). Ensure that the spec and every key path in it are plain objects containing one of the following commands: $push, $unshift, $splice, $set, $merge, $apply.

Let me know if you think it's worthwhile, I'll update the PR accordingly.

**Comment by gaearon** [comment]
Can we throw a different error when we encounter an array? e.g. `You provided an invalid spec to update(). The spec may not contain an array except as the value of $set, $push, $unshift, or $splice.` What do you think?

**Comment by stefk** [comment]
@gaearon, that's a good idea, I've added a dedicated invariant for arrays. I've also re-checked the original behaviour with null values, and it turns out that it always led to type errors ("Cannot convert undefined or null to object"), so there's no real breaking change here.

**Comment by zpao** [comment]
Personally I don't want to make any more changes to `update` ever while it's under the React umbrella. It should be an entirely standalone project if it's going to exist. There were a bunch of PRs and issues in this repo that would all be great to have but with nobody working on it, were just dropped out. I would still love to see somebody from the community pick this up, run with it and maintain it because we haven't. I'll even give you a free name for it too!

**Comment by gaearon** [comment]
@kolodny Do you plan to maintain https://github.com/kolodny/immutability-helper? We could make it an official new home of the `update()`. From what I understand it is already API compatible.

**Comment by kolodny** [comment]
@gaearon yup see https://github.com/kolodny/immutability-helper/issues/1#issuecomment-204221134

**Comment by gaearon** [comment]
@stefk 

Thanks for the PR. We decided we won’t be taking more changes to `update()`. You can submit this PR to https://github.com/kolodny/immutability-helper which is a drop-in replacement for it.

**Pull request closed without merging**
