### PR TITLE
[Doc] change a word in Doc

### PR DESCRIPTION
**Pull request by cht8687**
I feel use 'seeking' is better in this context. Maybe the original author of this paragraph had a typo?

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by zpao** [comment]
This is correct as is - it's describing the current state of your app, which is that it has performance problems you are seeing. "Experiencing" would be a better word if you wanted to change it to that.

**Comment by zpao** [comment]
Thanks!

**Comment by cht8687** [comment]
thank you Paul.

**Pull request merged**
