### PR TITLE
ESLint: Warn about using hooks inside try-catch

### PR DESCRIPTION
**Pull request by michaelneu**
## Summary

Currently, the ESLint plugin doesn't always flag using hooks inside try-catch blocks. Consider the following example where `useHookB` inside `useMultipleHooks` won't be called if `useMaybeThrowingHook` throws:

```js
function useMaybeThrowingHook() {
  // conditionally throws at some point in time
}

function useMultipleHooks() {
  useHookA();
  useMaybeThrowingHook();
  useHookB();
}

function Component1() {
  try {
    useMultipleHooks(); // (a) no warning
    useHookC();         // (b) warning
  } catch {
    // ignore catch
  }

  return <div />;
}
```

The Rules of Hooks plugin uses ESLint's code paths to determine whether a hook is called conditionally. ESLint assumes the code path going into the `try` block and the first expression in it to be the same path, so the plugin can't know that calling `(a)` might mean calling a hook inside of it conditionally. However, `(b)` generates a warning, since ESLint assumes a separate path after `(a)` potentially throws.

This PR adds a condition for when a hook is called inside a `try` block - additionally to counting its entry/exit paths - to catch these errors more broadly.

## Test Plan

I added some tests for this, the above example now causes linter warnings. Therefore my test plan is:

```bash
$ yarn test --prod ESLintRulesOfHooks
```

### CODE REVIEW

**Review by crypt096 — APPROVED** [review]

**Review by 3imed-jaberi — COMMENTED** [review]
+-0

**Review by rickhanlonii — COMMENTED** [review]
This looks good to me, but I'd like to confirm the change with @gaearon before merging.

Also, could we add a few more tests, including some using built-ins? I can see using a built-in such as useState to be allowed since it doesn't throw (though it would be weird to use it this way so maybe consistency to say "no hooks in a try" is better here).

**Comment by rickhanlonii** [comment]
Thinking about this more, shouldn't this be allowed:

```
function Component1() {
  try {
    useHook();
  } catch {
    // ignore catch
  }

  return <div />;
}
```

**Comment by michaelneu** [comment]
I'd agree regarding consistent usage for built-ins, but I think it might be confusing if some hooks are "valid" in a try-catch and others aren't (should a hook that just wraps a built-in be allowed? what if we call a built-in after a custom hook?). I don't have a strong preference either though.

Regarding the example: I don't think this should be allowed. If `useHook` throws internally because, e.g., we're accessing something on a `null`'d `useContext` field, we'd exit `useHook` early/conditionally before calling any remaining hooks in it.

**Comment by rickhanlonii** [comment]
@michaelneu isn't that true whether or not the try/catch is used?

**Comment by michaelneu** [comment]
It is, but the problem is that try/catch silences the error. Consider this example:

```js
function useHook() {
  const x = useX();

  invariant(x != null, 'x should not be null');

  // if we're in a try/catch, this would be equivalent, but it's against the Rules of Hooks:
  // 
  //   if (x == null) {
  //     return;
  //   }

  return useComplexSum(x, x);
}
```

Without a try/catch, `invariant` would make the component fail to render, notifying React that there was an error (and bubbling it up to the error boundary). But with the try/catch, the `invariant` will cause `useHook` to exit before `useComplexSum` executes - leaving the `useState` and `useEffect` unexecuted while "successfully" rendering the component with fewer hooks (which yields a React warning).

**Comment by michaelneu** [comment]
@rickhanlonii / @gaearon apologies for pinging, can you maybe give this another look? I rebased just now and the first hook in a `try` block doesn't show a warning without this change applied.

**Pull request closed without merging**
