### PR TITLE
Add ReactNext 2016 conference

### PR DESCRIPTION
**Pull request by ilyagelman**
Add ReactNext conference to list of conferences

### CODE REVIEW

**Comment by mxstbr** [comment]
The website link isn't correct, it's only accessible over HTTP, not HTTPS. I.e. `https://react-next.com/` fails, while `http://react-next.com/` works.

**Comment by ilyagelman** [comment]
Sorry, missed it. Updated.

**Comment by facebook-github-bot-3** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-4** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by zpao** [comment]
Thanks!

**Pull request merged**
