### PR TITLE
ESlint plugin is broken on 7.32.0 - Missing hasSuggestions

### PR DESCRIPTION
**Pull request by dannyvassallo**
## Summary

I kept hitting this error after upgrading to ESlint 7.32.0 whenever reaching a hook that had a suggestion.

```
Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Rules with suggestions must set the `meta.hasSuggestions` property to `true`.
```

## Test Plan

I've updated the meta entry and used it in my own project. Lint completes successfully.
I've also updated the Eslint version in this project.

### CODE REVIEW

**Comment by dannyvassallo** [comment]
@bvaughn sorry to ping you directly but is there something I need to do to improve this PR or get a review? It's becoming an issue for my team and I'd hate to have to rollback our ESlint update. Thank you so much for your time!

**Comment by bvaughn** [comment]
@gaearon would be the best person to review this so I'm going to tag him. If he doesn't have time, I can take a stab at it. I just don't have much context.

**Comment by dannyvassallo** [comment]
> @gaearon would be the best person to review this so I'm going to tag him. If he doesn't have time, I can take a stab at it. I just don't have much context.

Thank you both!

**Comment by dannyvassallo** [comment]
@gaearon It turns out we were using a branch on ESLint that introduced this bug. I can remove the version updates to ESLint here and leave just the `hasSuggestions` property if you'd like to merge it in anticipation of the breaking change to come in version 8.0.0.

Additionally I can add this rule: https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/require-meta-has-suggestions.md

Please let me know how I can be of assistance. Thank you!

**Pull request closed without merging**
