### PR TITLE
Fix docs on ReactElement

### PR DESCRIPTION
**Pull request by jddxf**
We should test $$typeof field against REACT_ELEMENT_TYPE to check if something is a React Element.

### CODE REVIEW

**Comment by gaearon** [comment]
Thanks for the PR but I believe the original is clearer. REACT_ELEMENT_TYPE [is](https://github.com/jddxf/react/blob/bedbc5f066b7a45520ab78ecb806ab557485535a/src/shared/utils/ReactElementSymbol.js#L18) Symbol.for('react.element'). Cheers!

**Comment by jddxf** [comment]
REACT_ELEMENT_TYPE is a plain number if there is no native Symbol nor polyfill.

**Comment by gaearon** [comment]
Right, but this is a fallback case and doesn't seem as important to document here to me.
Maybe could add "or a magic number as a fallback".

**Comment by jddxf** [comment]
Got it. Then I'll just ignore it. Thanks.

**Pull request closed without merging**
