### PR TITLE
Korean translation for docs

### LINKED ISSUE #2945: Add Korean translated docs
After seeing some good Chinese contributors contributing, I'm starting React docs translation project in React Korea group. As soon as we finish (or, have enough amount of docs translated) the translation, we would like to send a pull request. What do you guys think about it?

If you are interested, see [here](https://github.com/reactkr/discuss/issues/4) (even though its mostly in Korean):

### PR DESCRIPTION
**Pull request by sairion**
Fixes #2945 

By this PR, 26 out of 39 docs entry will be provided as Korean as well. (tracker: https://github.com/reactkr/discuss/issues/4)

P.S.
We kept most of Chinese translator's convention, but would like to introduce another PR for docs internalization. I think cherry-picking from #2876 seems to be a good start point!

### CODE REVIEW

**Comment by disjukr** [comment]
+1

**Comment by AiOO** [comment]
:+1:

**Comment by yeun** [comment]
:+1:

**Comment by JessicaJisun** [comment]
:+1::+1:

**Comment by Kroisse** [comment]
:+1::+1::+1:

**Comment by sairion** [comment]
Korean translation of React docs is finished and updated with the most recent one (at this moment of writing).

@zpao Any updates?

**Comment by marocchino** [comment]
@zpao Korean translate team members all agree with cla. You can see full the members list here. ( reactkr/react#55 ) If you still have a reason that  you can not merge this pr. please tell us. We will fix it.

**Comment by zpao** [comment]
Alright, let's do it. Sorry for the delay, it's been a bit crazy around here recently with react native :)

**Comment by zpao** [comment]
Ok, now moving forwards (and this is something we need to figure out a bit more across translations but I'm here), I really like the update in batches approach. Some things we'll definitely encourage that we fix across locales (eg, my change in #3487 would have been done to the ko-KR page as well), but others just won't be possible. I think it would be awesome to keep an eye on changes to docs (perhaps on a weekly basis just looking at https://github.com/facebook/react/commits/master/docs) and submitting changes in batches.

Looking further ahead, I've had https://github.com/screeninteraction/jekyll-multiple-languages-plugin open in a tab for a long time now, it might be time to finally look at integrating that. We have 3 translations at the moment - zh-CN, ja-JP, ko-KR - and while they aren't all complete, it would be great to integrate them into the site more holistically. Ultimately I'd like to move away from Jekyll to something node-based (and preferably using React, as we're doing in most of our other docs sites). We might have to write out own i18n stuff to make that work though.

If anybody is interested in taking on the larger project here and I'll try to give some guidance and thoughts.

**Comment by marocchino** [comment]
We already doing weekly update in [here](https://github.com/reactkr/react/pulls?utf8=%E2%9C%93&q=is%3Apr++update). It need to rebase with master but, hopefully We can send PR tomorrow. so.. dont worry about update translation. :smile:

**Comment by zpao** [comment]
@marocchino awesome! We'll be better with actually merging the PRs moving forward :)

**Comment by growingdever** [comment]
:+1:

**Pull request merged**
