### PR TITLE
Removes legacy TODOs in createfactory methods

### PR DESCRIPTION
**Pull request by onstash**
This pull-request addresses issue #11936 based on inputs from @aweary.

### CODE REVIEW

**Comment by onstash** [comment]
Thanks for reviewing, @mihalskiy. 😄

**Comment by gaearon** [comment]
We should still leave the "legacy hook" note IMO. TODO can change to "remove it".

**Comment by onstash** [comment]
Hi @gaearon. Confirming if I understood your comment correctly. Instead of removing the TODOs, we could replace the text "Legacy hook: warn if accessed" to "Legacy hook: remove it"?

**Comment by gaearon** [comment]
Yep

**Comment by onstash** [comment]
Thank you for helping me @gaearon! 😃

**Pull request merged**
