### PR TITLE
[RFC] Proposal for ReactTestRenderer selector API

### PR DESCRIPTION
**Pull request by rafeca**
I've been following the discussion in #7148 and decided to submit a proposal for a selector API. The methods that I've added to the TestComponent are:

```
TestComponent::getChildren()
TestComponent::getType() 
TestComponent::getProps()
TestComponent::find()
TestComponent::findAll()
TestComponent::findByProps()
```

With this functionality, tests that interact or assert props on subcomponents can be easily written.

This is an example of test that uses these new methods:

``` js
class Component extends React.Component {
  constructor() {
    super();
    this.state = { clicked: 0 };
  }

  render() {
    return (
      <div>
        <span>{this.state.clicked}</span>
        <myelement onClick={this._onClick}/>
      </div>
    );
  }
  _onClick = () => {
    this.setState({clicked: 1});
  }
}

var renderer = ReactTestRenderer.create(<Component />);

// Check that the default printed value is 0
expect(renderer.find('span').getChildren()[0].toJSON()).toEqual(0);

// Trigger a click on "myelement"
renderer.find('myelement').getProps().onClick();

// Check that the printed value has been updated
expect(renderer.find('span').getChildren()[0].toJSON()).toEqual(1);
```

### CODE REVIEW

**Comment by spicyj** [comment]
The get* methods will have to work a little differently so I did a first draft of that in #7516. After we agree on that then we can look at traversal helpers.

**Comment by faceyspacey** [comment]
@rafeca i really like `findByProps`. At first I was expecting an ezyme/jquery/cheerio API where you can search by css selectors, but I think this makes a lot more sense for React. 

With things like CSS modules, fancy combinator css selectors (and perhaps css style selectors in javascript in general) has become an anti-pattern, i.e. along with the idea of the separation of concerns regarding js in your "html." I personally never use css selectors in javascript anymore and am quite happy about it. From this viewpoint, it's basically a leaky abstraction. 

Now that said, without `findAllByProps` this selector API is severely crippled. You need to be able to do `findAllByProps({className: 'foo'})` and get an array of elements, just as you do `.find('.foo')` in enzyme of jquery.

**Comment by jquense** [comment]
btw if anyone _wants_ a css selector syntax I already wrote an abstraction for that: https://github.com/jquense/bill

**Comment by gaearon** [comment]
We have this now:
https://reactjs.org/docs/test-renderer.html#testrenderer

Thanks!

**Pull request closed without merging**
