### PR TITLE
Fixes for 15.5 addons

### PR DESCRIPTION
**Pull request by gaearon**
See https://github.com/facebook/react/issues/9384 for details.

### CODE REVIEW

**Comment by bvaughn** [comment]
`create-react-class` needs updated deps:
```diff
diff --git a/addons/create-react-class/package.json b/addons/create-react-class/package.json
index 323740f..e57d1ba 100644
--- a/addons/create-react-class/package.json
+++ b/addons/create-react-class/package.json
@@ -29,8 +29,8 @@
   },
   "devDependencies": {
     "jest": "^19.0.2",
-    "react": "^15.4.2",
-    "react-addons-test-utils": "^15.4.2",
-    "react-dom": "^15.4.2"
+    "react": "15.5.0",
+    "react-addons-test-utils": "15.5.0",
+    "react-dom": "15.5.0"
   }
 }
diff --git a/addons/create-react-class/yarn.lock b/addons/create-react-class/yarn.lock
index fd16b74..c6856fc 100644
--- a/addons/create-react-class/yarn.lock
+++ b/addons/create-react-class/yarn.lock
@@ -581,7 +581,7 @@ fb-watchman@^2.0.0:
   dependencies:
     bser "^2.0.0"
 
-fbjs@^0.8.1, fbjs@^0.8.4, fbjs@^0.8.9:
+fbjs@^0.8.4, fbjs@^0.8.9:
   version "0.8.12"
   resolved "https://registry.yarnpkg.com/fbjs/-/fbjs-0.8.12.tgz#10b5d92f76d45575fd63a217d4ea02bea2f8ed04"
   dependencies:
@@ -1565,6 +1565,18 @@ promise@^7.1.1:
   dependencies:
     asap "~2.0.3"
 
+prop-types@15.5.0-alpha.0:
+  version "15.5.0-alpha.0"
+  resolved "https://registry.yarnpkg.com/prop-types/-/prop-types-15.5.0-alpha.0.tgz#a342108678256db125eee3d1ae2f889af3531bd7"
+  dependencies:
+    fbjs "^0.8.9"
+
+prop-types@~15.5.0:
+  version "15.5.4"
+  resolved "https://registry.yarnpkg.com/prop-types/-/prop-types-15.5.4.tgz#2ed3692716a5060f8cc020946d8238e7419d92c0"
+  dependencies:
+    fbjs "^0.8.9"
+
 prr@~0.0.0:
   version "0.0.0"
   resolved "https://registry.yarnpkg.com/prr/-/prr-0.0.0.tgz#1a84b85908325501411853d0081ee3fa86e2926a"
@@ -1584,28 +1596,30 @@ randomatic@^1.1.3:
     is-number "^2.0.2"
     kind-of "^3.0.2"
 
-react-addons-test-utils@^15.4.2:
-  version "15.4.2"
-  resolved "https://registry.yarnpkg.com/react-addons-test-utils/-/react-addons-test-utils-15.4.2.tgz#93bcaa718fcae7360d42e8fb1c09756cc36302a2"
+react-addons-test-utils@15.5.0:
+  version "15.5.0"
+  resolved "https://registry.yarnpkg.com/react-addons-test-utils/-/react-addons-test-utils-15.5.0.tgz#d09f7475ba7728bcdb288303a687b64c75b31a5c"
   dependencies:
     fbjs "^0.8.4"
     object-assign "^4.1.0"
 
-react-dom@^15.4.2:
-  version "15.4.2"
-  resolved "https://registry.yarnpkg.com/react-dom/-/react-dom-15.4.2.tgz#015363f05b0a1fd52ae9efdd3a0060d90695208f"
+react-dom@15.5.0:
+  version "15.5.0"
+  resolved "https://registry.yarnpkg.com/react-dom/-/react-dom-15.5.0.tgz#86a8d6dcde388473815039de3840706e1f28f697"
   dependencies:
-    fbjs "^0.8.1"
+    fbjs "^0.8.9"
     loose-envify "^1.1.0"
     object-assign "^4.1.0"
+    prop-types "~15.5.0"
 
-react@^15.4.2:
-  version "15.4.2"
-  resolved "https://registry.yarnpkg.com/react/-/react-15.4.2.tgz#41f7991b26185392ba9bae96c8889e7e018397ef"
+react@15.5.0:
+  version "15.5.0"
+  resolved "https://registry.yarnpkg.com/react/-/react-15.5.0.tgz#1f8e4b492dcfbf77479eb4fdfc48da425002e505"
   dependencies:
-    fbjs "^0.8.4"
+    fbjs "^0.8.9"
     loose-envify "^1.1.0"
     object-assign "^4.1.0"
+    prop-types "15.5.0-alpha.0"
 
 read-pkg-up@^1.0.1:
   version "1.0.1"
```

**Comment by gaearon** [comment]
This doesn't affect correctness right? Just testing.

**Comment by bvaughn** [comment]
Yeah, that's fair. Guess I thought it was worth adding so we didn't scratch our heads later if we ever have to come back to this.

**Comment by bvaughn** [comment]
Initial round of unit tests and manual testing looks good.

**Comment by kookiekat** [comment]
Hope this will be released soon: react-router is now broken (with npm2) in the latest v3.0.4 since it now references create-react-class

**Comment by gaearon** [comment]
I think you might be misunderstanding this PR. This PR just fixes a few issues with addons that are unrelated to `createClass`.

React Router is **not** broken, it just shows a deprecation warning. This warning is harmless. It won’t turn into a real error until a few months later (with React 16), and by that time React Router maintainers will release a version that doesn’t use `createClass` (or uses a separate package).

Hope this clarifies it a bit!

**Comment by gaearon** [comment]
Oh wait nevermind, I just understood the issue. You’re completely right!
We’ll release a fix today.

**Comment by gaearon** [comment]
@kookiekat The fix for `create-react-class` is up (15.5.2).

**Pull request merged**
