### PR TITLE
Hide children of Offscreen after destroy effects

### PR DESCRIPTION
**Pull request by rickhanlonii**
Will quickly test internally then land the flag everywhere.

### CODE REVIEW

**Comment by acdlite** [comment]
Does this really need to be gated?

**Comment by rickhanlonii** [comment]
I think either @gaearon or @sebmarkbage recommended gating it in case there is an issue.

**Comment by gaearon** [comment]
I think I was referring to a different change (the one Andrew did). I don’t know whether this one would benefit from gating

**Comment by acdlite** [comment]
Needs a test

**Review by sebmarkbage — APPROVED** [review]
We should make up a test but it's a little tricky to come up with a realistic one since the observable difference is mainly whether it has a layout or not and even that is not true if we use content-visibility to keep the layout.

Since display: none has no effect in JS DOM, it seems like the only way to write the test is assert on implementation details (i.e. is display: none set).

**Pull request merged**
