### PR TITLE
test: Add current behavior for label clicking in a browser

### PR DESCRIPTION
**Pull request by eps1lon**
## Summary

Failing test for https://github.com/facebook/react/issues/18591

## Test Plan

https://codesandbox.io/s/user-label-click-with-associated-checkbox-1zs7z?file=/public/index.html showscases the event order in a real browser (tested with Chrome 84)

### CODE REVIEW

**Comment by eps1lon** [comment]
What's happening in 

```js
input.focus();
input.click();
```

- `.focus()` schedules discrete updates 
- when `click` is invoked we flush these updates setting `checked` to `false`
- by the time we [`updateChecked()`](https://github.com/facebook/react/blob/03de849af03996b7477420c97de7741ce1214149/packages/react-dom/src/client/ReactDOMInput.js#L170) (from the `.focus()` the user agent has already set `checked` to `true` which is now overridden
- When we flush the discrete updates from the click `checked` is false and no update is scheduled. The change event is missed.

**Comment by gaearon** [comment]
Want to try rebasing? I think this is fixed because discrete events are now flushed early. The fix is under the `enableDiscreteEventMicroTasks` flag.

**Comment by eps1lon** [comment]
> Want to try rebasing? I think this is fixed because discrete events are now flushed early. The fix is under the `enableDiscreteEventMicroTasks` flag.

Seems like it's fixed after some manual testing. Though I don't see how we can test this automatically.

I have to flush between focus and click in JSDOM and a browser or else no change event is dispatched. So in the end the flag doesn't actually fix the behavior when dispatching programmatically (we just switched from `act()` to `await null`). It's up to you whether you want to support this considering this behavior works in a browser (but is not replayable automatically).

**Comment by eps1lon** [comment]
Fixed already and testing this with jest is not possible.

**Pull request closed without merging**
