### PR TITLE
Switch to JSX API for context

### PR DESCRIPTION
**Pull request by acdlite**
80% sure this will be the final API. Merging this now so we can get this into the next www sync in preparation for 16.3.

### CODE REVIEW

**Comment by billyjanitsch** [comment]
Hi @acdlite! I know you're eager to ship the new context API, but I have some questions about the process behind developing it, if you have time to answer. (I know there's a blog post coming, but I assume it won't address this side of things.)

I really appreciate that y'all have opened up some of the React API to public discussion via RFCs. The context RFC had a lot of great discussion. As I understand, it and #11818 were merged to test out the semantics, with a period of API bikeshedding to follow before the release.

However it seems like that bikeshedding happened quickly, behind the scenes. I wasn't able to find any public venue to discuss the API over the past few weeks; I figured there'd be an issue or something before it was finalized. I was also surprised to see a final decision of a JSX-based `children` prop, since it seemed like the public consensus [largely](https://github.com/reactjs/rfcs/pull/2#discussion_r155415053) [favored](https://github.com/reactjs/rfcs/pull/2#discussion_r155369863) [`render`](https://github.com/facebook/react/pull/11818#issuecomment-360374208) in the initial RFC & PR. (I totally understand the desire to pick one and run with it, though. I don't have a strong preference either way.)

I'm curious about your thoughts here. Was it an intentional choice to make the API decisions internally?  Would you agree with my conception of the public opinion / was it an intentional choice to steer the ecosystem in a different direction? Do you see RFCs in general as a place to discuss semantics, syntax, or both?

**Comment by gaearon** [comment]
>However it seems like that bikeshedding happened quickly, behind the scenes. 

That's always going to be the case with final decisions. We get a lot of input from RFCs, and we appreciate it. That input plays a large role in our considerations. But ultimately we have to make a choice. You can't reach a consensus with a thousand people, so it is reached by a small group of people on the team (who take weeks of both internal and external feedback into account).

>I wasn't able to find any public venue to discuss the API over the past few weeks; I figured there'd be an issue or something before it was finalized

There was just one thing to decide: children vs render vs "plain functions". That is largely a superficial difference (but one that people tend to feel strongly about, just like whether to use semicolons). Creating another issue wouldn't give us any feedback that we haven't already received a dozen times. If you read the RFC comments (each of the people involved with this decision read the whole thread), you will see the discussion going in circles because people who post opinions often don't read past discussions. We felt that no new arguments are being made, and it was a good time for us to talk through this in private and form a consensus.

>it seemed like the public consensus largely favored render in the initial RFC & PR

There was no public "consensus", only dividing opinions with one option being more popular than the other. Part of what informs the public consensus is the existing decisions made in the core APIs. If core APIs always treat children as a node people will perceive the other options as "risky".

We have discussed all arguments for and against these choices that we're aware of (including those that came to light through the RFC discussion), and decided to settle on the `children` prop. We feel it fits more naturally with what we're trying to express there and is better suited to nesting. But yes, ultimately we had to pick one, and that's what we went with.

**Comment by billyjanitsch** [comment]
Thank you for your thoughts, @gaearon. I appreciate you engaging with these sorts of questions.

> There was no public "consensus" [...] We feel it fits more naturally with what we're trying to express there

"consensus" was the wrong word, and I didn't mean to say that you should choose an option just because it's more popular. I was just curious to what extent the decision was made because of a perception of popularity, a desire to steer the community, a matter of taste, etc. (which you helped explain.)

If it doesn't already, maybe the blog post could also include this sort of explanation. I think it would be useful for the community to help digest the changes.

> Creating another issue wouldn't give us any feedback that we haven't already received a dozen times [...] discussion going in circles

I see where you're coming from. I've read both threads in full too; public discussion gets noisy and repetitive. Thank you for enduring and sifting through for useful feedback.

In comments like https://github.com/facebook/react/pull/11818#issuecomment-360367019, I thought the team was saying "let's focus on the mechanics now, there will be time to discuss the API later." I didn't want to add to the noise. Maybe I misinterpreted.

Perhaps future RFCs could specify where the team sits and what you are looking for feedback on (e.g. "the semantics are finalized; we need to decide on an API; we see options A, B, and C with these pros/cons and lean slightly towards B; we are not considering D because X") Many people don't read the thread before commenting but most read the first post. This context might help keep discussion focused and useful.

(I think the [unusual](https://twitter.com/dan_abramov/status/960579972007161856) amount of FUD around this release is due to unconstrained interpretation -- more context prevents people from jumping to excessive conclusions about the intentions/effects of changes.)

**Comment by gaearon** [comment]
>In comments like #11818 (comment), I thought the team was saying "let's focus on the mechanics now, there will be time to discuss the API later." I didn't want to add to the noise. Maybe I misinterpreted.

Fair enough. In this case maybe it would be more correctly to say "By now we've already heard all the arguments for and against children-as-a-function because the topic has been beaten to death both in the RFC discussion and for months on Twitter. We'd like other, more important aspects of the API to receive at least some of the attention that's being paid to the most superficial part of it."

Although, to be extra particular, that comment was by an FB employee, and I think Andrew was referring to the final private decision-making process as "final bikeshedding". Andrew and Cheng met later, and Andrew explained that `provide()` / `consume()` still produces React elements (and thus ReactReason would have to wrap that API anyway). That removed Cheng's concern.

**Pull request merged**
