### PR TITLE
合并原作者的更新

### PR DESCRIPTION
**Pull request by miaozhirui**
如题

### CODE REVIEW

**Comment by zpao** [comment]
Can you post title and description of this in English please? You'll also want to rebase because there is a ton of noise here. Also also, don't try to merge into gh-pages. You should target master.

**Comment by hbrls** [comment]
@zpao I think he was trying to merge from facebook to his own fork, but hit the wrong button.

**Comment by koistya** [comment]
Maybe, that's somehow related Maybe, that's somehow related to the DDoS attack which is taking place on GitHub right now.to the DDoS attack which is taking place on GitHub right now.

**Comment by zpao** [comment]
Alright, reopen if this was intended and we can discuss further.

**Pull request closed without merging**
