### PR TITLE
fix 'any' type in legacyRenderSubtreeIntoContainer in ReactDOM.js; DRY up some repeated lines

### PR DESCRIPTION
**Pull request by nateq314**
Code contained the comment:
```
// TODO: Without `any` type, Flow says "Property cannot be accessed on any
+  let root: Root;
-  // member of intersection type." Whyyyyyy.
```
This is happening because `_reactRootContainer` is a maybe-typed property but `root` is not. Flow doesn't allow this kind of thing unless enclosed in a typecheck (https://flow.org/en/docs/types/maybe/#toc-refining-maybe-types). Remove the assignment altogether and make it just a declaration, then the error goes away. Slightly refactor the if-else and the way `root` is assigned in the `else` clause and you're all good.

Also refactored some repeated lines into nested functions as below.

### CODE REVIEW

**Comment by nhunzaker** [comment]
This looks good to me, but someone more familiar with this code should pass off here. Beyond that:

- [x] Flow passes
- [x] Tests pass
- [x] Unit test coverage exhausts all branches of this update

I think this is good to go, but I'll ping some folks to talk a look. Great work!

**Comment by nhunzaker** [comment]
Hey @acdlite, looks like this is [your TODO](https://github.com/facebook/react/blame/master/packages/react-dom/src/client/ReactDOM.js#L1057-L1058), do you mind taking a quick look at this?

**Comment by nhunzaker** [comment]
Beyond that, I've left a note to check back in about a week just to make sure things move along.

**Comment by react-linter** [comment]
ReactDOM: size: -0.1%, gzip: 0.0%


  <details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 52fbe7612e0527b8c86decac519c344626f6bd72...a89897b2dcb0f2cd7294a75094748a17ce1bdb95</p>


  
## react-dom
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-dom.development.js | -0.1% | -0.0% | 626.32 KB | 625.95 KB | 145.82 KB | 145.75 KB | UMD_DEV
**react-dom.production.min.js** | **-0.1%** | **0.0%** | **94.16 KB** | **94.07 KB** | **30.5 KB** | **30.5 KB** | **UMD_PROD**
react-dom.development.js | -0.1% | -0.0% | 610.68 KB | 610.31 KB | 141.81 KB | 141.75 KB | NODE_DEV
**react-dom.production.min.js** | **-0.1%** | **0.0%** | **92.66 KB** | **92.57 KB** | **29.48 KB** | **29.49 KB** | **NODE_PROD**
ReactDOM-dev.js | -0.1% | -0.0% | 620.2 KB | 619.79 KB | 141.21 KB | 141.15 KB | FB_WWW_DEV
**ReactDOM-prod.js** | **-0.1%** | **0.0%** | **269.19 KB** | **268.93 KB** | **50.57 KB** | **50.57 KB** | **FB_WWW_PROD**

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by gaearon** [comment]
I think we'd like to avoid creating an extra closure in this method.

**Comment by nhunzaker** [comment]
Looks like the fork of this disappeared. @nateq314 is this something you are interested in working on still?

**Comment by nhunzaker** [comment]
I'm going to close this out since the fork has been deleted, but @nateq314 feel free to send out a new PR if you'd like to take a look at this again!

**Pull request closed without merging**
