### PR TITLE
Build perf and test-utils addon npm packages

### LINKED ISSUE #4279: How to use Perf and TestUtils
In v0.14.0-beta1, Perf and TestUtils don't publish as npm package.

https://github.com/facebook/react/blob/master/grunt/tasks/npm-react-addons.js#L8-L42

How can i use these libraries?
Should I use `react/lib/xxx` directly?

```
var Perf = require("react/lib/ReactDefaultPerf");
var TestUtils = require("react/lib/ReactTestUtils");
```

 I can't find a document mentioned this.

### PR DESCRIPTION
**Pull request by zpao**
Fixes #4279

### CODE REVIEW

**Comment by yaycmyk** [comment]
:clap: Very excited to see test-utils split off ^_^

**Comment by spicyj** [comment]
Should either of these be called `dom`?

**Comment by zpao** [comment]
Good question. We didn't do that for the transition group addons but maybe we should…

**Comment by zpao** [comment]
Meh, let's leave it as is for now for parity. We can rename things later.

**Pull request merged**
