### PR TITLE
Remove classSet/cx

### LINKED ISSUE #3489: Remove classSet/cx entirely
Now that we deprecated it, we should remove it *before* we ship 0.14.

Would you like the honors @chenglou?

### PR DESCRIPTION
**Pull request by chenglou**
Fixes #3489
@zpao

### CODE REVIEW

**Comment by spicyj** [comment]
Remove the docs too?

**Comment by zpao** [comment]
Yea, that's a good idea. Perhaps we leave the permalink so the fb.me link works with the deprecation note. But otherwise remove it from addons landing page and prev/next.

**Comment by chenglou** [comment]
K, added a new commit.

**Comment by zpao** [comment]
:boom: We may want to tweak the actual className docs a bit more but that can come later.

**Pull request merged**
