### PR TITLE
support slot attribute on DOM elements for V1 shadowDom named slots p…

### LINKED ISSUE #7784: support slot attribute (ShadowDOM v1) on DOM elements
**Do you want to request a _feature_ or report a _bug_?**
feature ( I guess? )

**What is the current behavior?**
React doesn't support `slot` attribute which comes with shadowDom v1, so it will throw error and because of that, web component isn't working

code:

``` js
class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h2>Welcome to React</h2>
        </div>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <div>
          <fancy-tabs background hello="World!">
            <button slot="title">Tab 1</button>
            <button slot="title" selected>Tab 2</button>
            <button slot="title">Tab 3</button>
            <section>content panel 1</section>
            <section>content panel 2</section>
            <section>content panel 3</section>
          </fancy-tabs>
        </div>
      </div>
    );
  }
}
```

rendered html with error

screen shot 2016-09-21 at 2 05 47 pm

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

Support new DOM attribute standard

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.3.2 / Chrome 53 / OSX El Capitan

### PR DESCRIPTION
**Pull request by Hotell**
Closes #7784

### CODE REVIEW

**Comment by elmariofredo** [comment]
@Hotell @Aweary any progress with the merge? Thanks!

**Comment by Hotell** [comment]
Errors resolved long time ag.o Any progress on this, or you just don't care about the platform ? So sad...

**Comment by Aweary** [comment]
Sorry for the delay. The core team has been very busy working on Fiber and I've been a little busy this week 😄 Thanks for the PR @Hotell

**Comment by LadyYoung957** [comment]
Come get this food

On Nov 4, 2016 2:07 PM, "Martin Hochel" <notifications@github.com> wrote:
>
> Errors resolved long time ag.o Any progress on this, or you just don't
care about the platform ? So sad...

**Comment by Georgegriff** [comment]
is/when will this be released?

**Pull request merged**
