### PR TITLE
[DevTools] Add open in editor

### PR DESCRIPTION
**Pull request by ezzak**
## Summary

Add ability to view the current component in your code editor.

## Test Plan

Open with vscode (default behavior):

https://user-images.githubusercontent.com/20268283/139626389-81eda89a-2f69-4e6b-8a2b-2df6f6e093e7.mov

Open in sublime (customized behavior):

https://user-images.githubusercontent.com/20268283/139626402-853a15e9-eb70-4727-925d-e4cd5f23edcf.mov

Icon updated after these videos were captured

Screen Shot 2021-10-31 at 10 22 10 PM

### CODE REVIEW

**Comment by ezzak** [comment]
Updated to make the url configurable:

- Assumption: URL should have the two tokens "{path}" and "{line}" which we fill in, we kinda need these to be tokens as different apps do things differently.

VSCode Urls: https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls
Sublime Urls: https://github.com/asuth/subl-handler

**Review by bvaughn — COMMENTED** [review]
Tested it with an OSS build and CRA:

https://user-images.githubusercontent.com/29597/139738296-b65eba2c-33fe-45b3-b102-68f1435d4988.mp4

**Comment by bvaughn** [comment]
Also confirmed that it works in the extension:

open-in-editor-2

**Comment by jstejada** [comment]
so good! excited for this to land!

**Review by bvaughn — COMMENTED** [review]
This is, overall, great!

One requested change:

For the internal build, let's actually pre-fill in the editor URL value (rather than just a placeholder).

For the OSS version, we can leave the placeholder as the default (bc not everyone uses VSCode).

**Comment by ezzak** [comment]
Addressed comments:

Updated behavior:

Without env variable:

process.env.EDITOR_URL defaulted to null. Setting is disabled by default. If user goes to settings they can see the vscode default url as a placeholder and use it if they wish to. If user types anything in this the setting gets enabled.

With env variable:

process.env.EDITOR_URL is a string. Setting is enabled by default and uses this url. If user goes to settings they can see it pre-filed in. If they delete it they can disable the setting or they can override it to a desired value.

**Review by bvaughn — APPROVED** [review]
Thanks for seeing this through! I'm going to push a few small tweaks, then we can land.

**Pull request merged**
