### PR TITLE
Clarify that ReactPerf.getLastMeasurements() is now opaque

### PR DESCRIPTION
**Pull request by gaearon**
This documents changes from #6286 and should be up on the website when 15 is released.

### CODE REVIEW

**Comment by jimfb** [comment]
:+1:

**Comment by gaearon** [comment]
Should I merge it now, or wait for 15 to be released? How do we divide “needs merge to stable asap” from “needs merge to stable on next release”?

**Comment by jimfb** [comment]
Merge now but do not mark as needing to be cherry-picked to stable.

**Comment by gaearon** [comment]
How do we remember to cherry-pick it later? Is this part of the stable release process?

**Comment by jimfb** [comment]
We never cherry-pick it.  When the v15 branch is cut, it will be cut from master, so it will include this commit.  The cherry-picking is only for backporting the documentation to v14.

**Comment by gaearon** [comment]
Ah, that makes total sense. Thanks!

**Pull request merged**
