### PR TITLE
Remove viewport metrics, other pageX/pageY behaviors

### PR DESCRIPTION
**Pull request by nhunzaker**
`pageX` and `pageY` are supported in every browser, which makes it possible to remove a lot of code. I don't expect this one to get merged so easily; I'm happy to provide any additional testing.

### Test methodology

I created a case here using React's pageX/pageY feature test:
http://codepen.io/nhunzaker/pen/GWwmyK

### Test Results

YES
----
IE9
FF 3
Chrome 15
Opera 10.6
Yandex 14.12
Safari 4 - Windows
Safari 4 - Mac
Windows Phone 8.1
iOS 4.3.2
Android 4 (Native Browser)
Android 4.4 (Chrome)

NO
-----
IE8

### CODE REVIEW

**Comment by gaearon** [comment]
Seems like it's indeed IE8 only.
Reference:

* https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/pageX ("Internet Explorer: 9, (Others): Yes")
* http://www.quirksmode.org/mobile/tableViewport_desktop.html (IE8: no)
* http://www.jacklmoore.com/notes/mouse-position/ ("The only major browser that does not support these properties is IE8.")

**Comment by nhunzaker** [comment]
@gaearon Prettiered and squashed.

**Comment by nhunzaker** [comment]
Should pass, waiting on a lint fix: https://github.com/facebook/react/pull/9300

**Comment by gaearon** [comment]
It will also fail because you need to run `./scripts/fiber/record-tests` and commit the result.

**Comment by nhunzaker** [comment]
Done. I am sorry for the trouble.

**Comment by gaearon** [comment]
No worries, thank you for this!

**Pull request merged**
