### PR TITLE
Polyfill event.dataTransfer.type for drag & drop events

### LINKED ISSUE #3656: In Chrome, synthetic drag and drop events should use DOMStringList for event.dataTransfer.types
`event.dataTransfer.types.contains(...)` is broken in Chrome.

### PR DESCRIPTION
**Pull request by jansedivy**
This pull request demonstrates our idea (me and @hejld) how to fix #3656 and #2676. We started with just polyfilling the types property for now.

There are few aspects that are not finished yet - object pooling, checking if it is possible to use defineProperty, and tests - but it should be enough to gather initial feedback.

Thanks a lot!

cc @syranide

### CODE REVIEW

**Comment by hejld** [comment]
@spicyj @zpao any thoughts on this? Should we proceed with implementation? Thanks!

**Comment by syranide** [comment]
`Object.defineProperty` isn't available on IE8.

Also, `this.dataTransfer` should be set using the same principle as in (or is there a reason not to?):
https://github.com/jansedivy/react/blob/drag-fix/src/renderers/dom/client/syntheticEvents/SyntheticMouseEvent.js#L34

It also seems problematic as this doesn't polyfill functionality universally and, as far as I can tell, will simply error if you try to use this API on a lesser browser. So it seems to me that this deviates from existing event polyfills provided by React and it's not immediately clear to me whether going this route is a good idea or not (long-term/maintainability/etc).

**Comment by hejld** [comment]
Thanks! This helps a lot. Will get back to you once the feedback is incorporated.

**Comment by gaearon** [comment]
Thank you for taking time to contribute. I’m closing as this PR has not received updates in response to the feedback in https://github.com/facebook/react/pull/5529#issuecomment-169029359. Please feel free to open another one if you plan to get back to this!

**Pull request closed without merging**
