### PR TITLE
Run prettier and linting before git commit

### PR DESCRIPTION
**Pull request by trivikr**
This is done with the help of husky and lint-staged

As per the [existing contribution instructions](https://reactjs.org/docs/how-to-contribute.html#sending-a-pull-request), the contributor has to run prettier and linting manually before submitting the pull request.
This PR ensures that those instructions are run automatically when contributor runs `git commit` thus removing the requirement of running those instructions manually

### CODE REVIEW

**Comment by trivikr** [comment]
Hi, any update on this PR?

**Comment by gaearon** [comment]
Isn't `lint-staged` broken for use cases like `git add -p`?

**Comment by trivikr** [comment]
Yup! It looks like lint-staged still has issues with partial-staging (discussed extensively in okonet/lint-staged/issues/62)
I verified the issue in minimal repo [trivikr/lint-staged-test](https://github.com/trivikr/lint-staged-test)

**Comment by trivikr** [comment]
Looks like the issue with partial staging on lint-staged can be fixed by using precommit instead (example PR CraveFood/farmblocks/pull/44)
I'll play with precommit some time, and post a new PR. This PR can be closed.

**Comment by aberezkin** [comment]
@trivikr It looks like using pre-commit will introduce required global dependency which we can't control from package.json. It'll require contributors to install it manually. Isn't it a problem?

**Comment by trivikr** [comment]
@aberezkin Yup!
I'd also gone through other [pre-commit hooks](https://prettier.io/docs/en/precommit.html) available for Prettier - only [Option 4: precise-commits](https://prettier.io/docs/en/precommit.html#option-4-precise-commits-https-githubcom-jameshenry-precise-commits) allows partial file formatting. However, it can't be configured.

**Comment by trivikr** [comment]
One solution could be to run `git commit --no-verify` to avoid git hooks being run while doing partial staging ([documentation](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#_committing_workflow_hooks))

Assuming partial staging is mostly done by experienced developers and they know what they're doing, can we go ahead with using husky+lint-staged as done in this PR?

**Comment by aberezkin** [comment]
Even without taking into account that not only experienced developers can use partial commits (GUIs simplify partial adding for git newcomers) there are more that can occur.

First of all, I don't think that prettier has anything to do with experience since it is an **opinionated** formatter. Its main goal is to prevent long team discussions about code formatting rules, not verify developers' experience. Experienced developers can have their own way of coding things which is not compatible with prettier.

**Comment by aberezkin** [comment]
Yes, I clearly understand this. I just pointing out why assuming that partial staging is used only by experienced developers is a bad idea.

**Comment by aberezkin** [comment]
Looks like okonet/lint-staged#75 will be released soon and this PR will be kind of legit.

**Comment by trivikr** [comment]
That's good to know @aberezkin :smile:

**Comment by vikr01** [comment]
okonet/lint-staged#75 has been merged

**Comment by aberezkin** [comment]
Hasn't been released, though

**Comment by vikr01** [comment]
@aberezkin What makes you think that? [It's right there in the README](https://github.com/okonet/lint-staged#reformatting-the-code). It even links to [a blog post](https://hackernoon.com/announcing-lint-staged-with-support-for-partially-staged-files-abc24a40d3ff) that states:

>Introducing lint-staged v8
Today, after more than two years and 138 commits I’m very excited to finally release version 8 of lint-staged that supports partially staged files!

The [latest version on `npm` is 8.0.4](https://www.npmjs.com/package/lint-staged), so it does seem to have been released.

**Comment by aberezkin** [comment]
@vikr01, Yes seems like it's released since v8. My bad, sorry.

**Comment by y7usuf** [comment]
You should close the PR. It is merged already.

**Comment by trivikr** [comment]
I don't see husky/lint-staged in master's package.json https://github.com/facebook/react/blob/master/package.json

Where is it merged to @y7usuf?

**Pull request closed without merging**
