### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by TanaseHagi**
Added version and babel preset

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by jimfb** [comment]
@zpao @spicyj

**Comment by zpao** [comment]
We already have a `.babelrc` in there and the version is not needed since we don't publish this. Could you strip this down to just updating the React dependencies?

**Comment by TanaseHagi** [comment]
Yes you're right. My bad. I'm trying to learn React and I downloaded the starter kit from [https://facebook.github.io/react/docs/getting-started.html](https://facebook.github.io/react/docs/getting-started.html) which does not have the `.babelrc` file and I couldn't compile. That's why I made the changes, but did not notice the github repo had the file.

**Comment by facebook-github-bot-5** [comment]
@TanaseHagi updated the pull request.

**Comment by zpao** [comment]
Bah, I thought I fixed the babelrc packaging issue with #6617. Sorry about that. I'll try that again…

**Comment by zpao** [comment]
Thanks! And thanks for catching the issue with the babelrc. I have a proper fix for that now so we'll avoid the issue in the future.

**Comment by TanaseHagi** [comment]
You're welcome.

**Pull request merged**
