### PR TITLE
Fixed lint error in ReactErrorUtils-test

### PR DESCRIPTION
**Pull request by bvaughn**
This has been nagging me for a few days 😅 

screen shot 2017-08-29 at 9 09 08 am

### CODE REVIEW

**Comment by bvaughn** [comment]
:grin: It's sad that I let it bug me for days before fixing it.

**Comment by sophiebits** [comment]
I think the original intent was that all our lints would be errors (CI-blocking) or off. I guess that regressed along the way, but maybe we can turn everything back to error if we're at no warnings?

**Comment by bvaughn** [comment]
I dig that suggestion.

**Comment by bvaughn** [comment]
Our [`.eslint` config](https://github.com/facebook/react/blob/master/.eslintrc.js) says it's stricter than default, explicitly turning some warnings into errors. I assume we just aren't covering all possible warnings. (I'm not sure if there's a way to do this, judging from the docs.)

**Comment by bvaughn** [comment]
Ooh looks like maybe `--max-warnings` will do the trick. I'll try it.

**Comment by bvaughn** [comment]
Warnings fail in #10572

**Pull request merged**
