### PR TITLE
Fix Japanese/Italian/Korean tutorials

### PR DESCRIPTION
**Pull request by serima**
Go through the drill, got a following error.

image

But English version is right.

image

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by serima** [comment]
signed.

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by keyanzhang** [comment]
Thanks! While we are here, would you mind also fixing [`tutorial.it-IT.md`](https://github.com/facebook/react/blob/master/docs/docs/tutorial.it-IT.md) and [`tutorial.ko-KR.md`](https://github.com/facebook/react/blob/master/docs/docs/tutorial.ko-KR.md)?

**Comment by serima** [comment]
@keyanzhang thank you for your review.
I fixed both of them.

**Comment by keyanzhang** [comment]
Thanks!

**Pull request merged**
