### PR TITLE
deps: bump ESLint version to v7

### PR DESCRIPTION
**Pull request by koba04**
## Summary

This PR is to update ESLint version in `devDependencies` to v7.
The motivation is to verify whether `eslint-plugin-react-hooks` works fine with ESLint v7.
#18878 is a PR to bump the peerDependencies version, but it doesn't guarantee the behavior with ESLint v7.

I've also fixed some failed tests with ESLint v7.
The fails are caused by https://github.com/eslint/eslint/pull/12955, which makes `output` require when the rule has fixed the code.

## Test Plan

`yarn test` && `yarn lint`

### CODE REVIEW

**Comment by koba04** [comment]
All checks have passed🚀

**Comment by gaearon** [comment]
thank you

**Comment by trueadm** [comment]
This is now causing master to fail because during our validation script we get the error:

`No files matching the pattern "./build/node_modules/*/umd/*.js" were found.`

Oddly, there are definitely files in there, as it states this just above.

```
Checking if files exist in ./build/node_modules/*/umd/*.js...
Found 32 bundles.
```

**Comment by gaearon** [comment]
I reverted in https://github.com/facebook/react/pull/18899 because this failed master builds. It seems like we only ran this task on master? @koba04 mind looking into this?

**Comment by koba04** [comment]
@gaearon oh, I’ll work on it now!

**Comment by koba04** [comment]
@gaearon @trueadm I've fixed it at #18900.

**Pull request merged**
