### PR TITLE
Use const instead of var (ES6 best practices)

### PR DESCRIPTION
**Pull request by rajatsehgal**

### CODE REVIEW

**Comment by bhamodi** [comment]
LGTM.

**Comment by yaycmyk** [comment]
Side note - you can drop the parens around `props` as well. A single arity arrow function doesn't need parens.

**Comment by zpao** [comment]
Yea, that's fine. Can you update the translated versions of that file too?

> you can drop the parens around `props` as well

I'd prefer we don't do that in our docs, especially for this type of code. I hate it less for the single line use in `.map` and co but in general I wish the single argument case was not an exception.

**Comment by rajatsehgal** [comment]
Updated the translated versions to reflect the same change of var to const. Didn't see the example in the Japanese version though.

**Comment by bhamodi** [comment]
@rajatsehgal - could you please squash all these commits into one master commit? Thanks!

**Comment by rajatsehgal** [comment]
Squashed.

**Comment by bhamodi** [comment]
@zpao - LGTM.

**Comment by zpao** [comment]
Thanks!

**Pull request merged**
