### PR TITLE
Allow third party react-native components to render strings

### PR DESCRIPTION
**Pull request by iyegoroff**
After introducing new invariant checks in react-native 0.56.0 release, third party native components that can render strings became broken - e.g. https://github.com/iyegoroff/react-native-text-gradient/issues/11

This PR allows third party components to render strings if they have static property `canRenderString` set to `true`.

Usage:

```js
const ICanRenderString = createReactClass({
  statics: {
    canRenderString: true
  },
  ...
};

class ICanRenderStringToo extends React.Component {
  static canRenderString = true;
}
```

### CODE REVIEW

**Comment by mgcrea** [comment]
Just to add a bit of weight to the PR. We can't use [styled-components](https://www.styled-components.com/) with react-native anymore. Looks like this `Invariant Violation: Text strings must be rendered within a <Text> component.` has broken a lot of react-native third-party libraries.

**Comment by react-linter** [comment]
<details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 34348a45b4b1de40d285ba7168e4d6770e620911...76f43e6b34be332e2d16b75be2517572fc4b00cd</p>


  
## schedule
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
schedule.development.js | n/a | n/a | 0 B | 19.17 KB | 0 B | 5.74 KB | UMD_DEV
**schedule.production.min.js** | **n/a** | **n/a** | **0 B** | **3.16 KB** | **0 B** | **1.53 KB** | **UMD_PROD**

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by xdreamcode** [comment]
Please merge this PR! It is causing a lot of problems with some third party libraries.

**Comment by Balasnest** [comment]
Please merge this PR. Waiting for this merge from a long time.

**Comment by rkdavidson** [comment]
What's holding this PR up from merging? Looks good to go

**Comment by georgian3688** [comment]
I am facing issue in react native 0.57. Please merge this PR.

**Comment by rkdavidson** [comment]
Hi @hramos, hoping to get some traction on this PR and @rowinbot mentioned you above ☝️.

**Comment by hramos** [comment]
@rkdavidson this being the React repo, I defer to the @facebook/react-core team.

**Comment by rkdavidson** [comment]
Ah @hramos thanks, forgot about the general team @ handle.
Thanks for the quick response 🙇‍♂️

**Comment by alittletf** [comment]
wow...wanted to use react-native-text-gradient but it is dependent on this being merged in. Kind of bummer we are coming up on a year and no merge yet

**Comment by rkdavidson** [comment]
Any update on what's holding this PR up?

**Comment by gaearon** [comment]
The approach taken by this PR is not something we'd go with. It adds checks in a very hot path and introduces a new public API which isn't something we do lightly. I also don't think this API makes sense for this use case. It should "just work", not require you to annotate something with a special tag.

If this is still a problem please file a new issue where we can discuss this.

**Comment by gaearon** [comment]
Also all the "please merge" comments here weren't helpful. What would have been helpful is filing a new issue with a concrete problem. Because these comments were all on a PR that isn't shippable, we missed this whole discussion.

**Pull request closed without merging**
