### PR TITLE
Synced ReactNativeFiber bugfix for leaf-node children

### PR DESCRIPTION
**Pull request by bvaughn**
Upstream sync of a bugfix committed to fbsource.

### CODE REVIEW

**Comment by gaearon** [comment]
Could you explain why it works? I don't understand.

**Comment by bvaughn** [comment]
CI failure certainly seems unrelated to my change.

screen shot 2017-04-04 at 3 54 31 pm

**Comment by bvaughn** [comment]
> Could you explain why it works? I don't understand.

In ReactNative leaf nodes (eg strings/numbers within a `Text` component) are tracked in JavaScript as numbers that map to a corresponding native view. For other types of views we create wrapper objects that contain the native tag/number as well as an a view configuration and an array of current children. (We need to track children so that we can add/move/remove them via `UIManager` and so that we can recursively uncache fibers when unmounting.)

Previously I was not properly handling 2 cases where a `child` parameter was a leaf-node type (just a number) and so the result was that I was passing `UIManager` a value of `null` when it expected a number.

**Comment by gaearon** [comment]
OK I get it now. I was confused thinking `typeof` check related to the *element* (which could also be a number itself, but this doesn't leak to renderer API in Fiber, unlike in Stack) rather than native tag. Thanks for explaining.

**Comment by bvaughn** [comment]
Steam rolling ahead with this since it's already been merged in fbsource and I don't want to forget and have it wiped out by the next sync 😄

**Comment by gaearon** [comment]
👍

**Comment by gaearon** [comment]
y u no prettier 
screen shot 2017-04-05 at 7 50 10 pm

**Comment by gaearon** [comment]
(I'll fix it)

**Comment by gaearon** [comment]
Not because I'm trying to shame you but because I'm also pushing a change 😄

**Comment by bvaughn** [comment]
Guh! Because we have too many different workflows and I've been working mostly with native/fbsource lately which doesn't use Prettier _and I'm forgetful and ashamed of myself_ ☹️ 

Thanks Dan! 😄

**Pull request merged**
