### PR TITLE
SimpleMemoComponent should warn if a ref is given

### LINKED ISSUE #13964: React.memo – attempting to assign a ref to a component wrapped in memo does not produce a friendly error message
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Attempting to assign a ref to a component wrapped in React.memo does not produce a friendly error message. Attempting the same thing with a functional component *not* wrapped in memo gives a descriptive error ("Warning: Function components cannot be given refs. Attempts to access this ref will fail.").

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
I trust this is not needed for this case

**What is the expected behavior?**
The same error message as with a non-memo functional component should be displayed.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
16.6.0

### PR DESCRIPTION
**Pull request by sophiebits**
Fixes #13964.

### CODE REVIEW

**Comment by sophiebits** [comment]
@bvaughn I don't understand what you mean. The test does test SimpleMemoComponent.

**Comment by bvaughn** [comment]
Sorry. I wrote the exact opposite of what I meant to write. ☹️ We're explicitly testing the simple memo case but not the lazy+memo case.

**Comment by bvaughn** [comment]
Hmm, well ok then.

**Comment by sophiebits** [comment]
Pardon?

**Comment by bvaughn** [comment]
😊 uh... please ignore me. wrong response / wrong issue.

**Pull request merged**
