### PR TITLE
[Fiber] [WIP] Get ReactComponentTreeHook working

### PR DESCRIPTION
**Pull request by gaearon**
Not a high priority so just posting initial work in progress.
With the commented out bits, passes 19 tests, fails 42 tests.

This needs a lot more work, would be happy if someone in the community wanted to pick it up.

### CODE REVIEW

**Comment by laskos** [comment]
> would be happy if someone in the community wanted to pick it up.

FYI I went on this wip, but it was just a try. Here is my work:

https://github.com/laskos/react/tree/wip-debugid

Code quality isn't even comparable but still, I covered 52/60 tests. Maybe you will find something useful.

I would love to see more WIP like this. It is easy entry point for potential contributors, clearly defined target.

**Comment by gaearon** [comment]
Oh nice! Actually my code is very dirty right now, I wrote the simplest thing that works but it needs some refactoring (remove the most blatant repetition and long lines, extract some of these in functions). I'd be thrilled if you could pick that up and work further on it.

Nice job on your fixes. One thing I think my code does more correct is that it doesn't modify the hook code itself. This is fairly important: the idea is to make the events to be emitted at the right times rather than add Fiber-specific hacks in the hook. The hook should stay as simple as possible.

One thing I'm not happy about in the new implementation is that onBeforeX/onX pairs of events don't really work well for the new reconciler. This is because it can "begin" and even "complete" work many times but then throw it away if a higher priority update happens.

This especially doesn't make sense in Chrome DevTools where we plot the timeline when ReactPerf is active. It probably wouldn't make sense to plot a "stack-like" timeline from onBeforeX to onX events because onBeforeX can happen multiple times. We also don't know until the commit phase if the result is going to actually end up in the tree or not. So ideally we should not be updating the tree information until the commit.

On the other hand some warnings want to read the information from the tree at any time. So maybe the tree should learn to differentiate "work in progress" but still answer questions like "who is this component's parent" for things that aren't still committed. Another gotcha is that in Fiber, commits don't traverse the whole tree so you're only going to learn that some roots have mounted but ideally shouldn't have to traverse the children every time. The hook should learn to deal with this. 

Sorry this isn't inconclusive, but nobody really worked on this yet. If you'd like to help, I think the first good step is to consider use cases for the tree hook (Perf, in the future React DevTools, warning messages using it, and Chrome Timeline integration in Perf), and figure out how to change the event design so that those use cases are still fulfilled reasonably well in Fiber world where commits happen separately, work can be aborted, and it is not recursive.

**Comment by gaearon** [comment]
Won't be doing this.

**Comment by omerts** [comment]
> 
Won't be doing this.
> 
@gaearon, why? because of the above issues? or because there is something better now?

**Comment by Shahryar27** [comment]
i have received your email but i have not received book

**Pull request closed without merging**
