### PR TITLE
Fixed schedule/tracking require for www sync script

### PR DESCRIPTION
**Pull request by bvaughn**
Whoops 😄 Overlooked this little detail.

### CODE REVIEW

**Comment by gaearon** [comment]
Oh lol. I forgot we even had this. I don't think it's necessary anymore — I set up a forwarding module in my sync diff. And we could do the same for ReactIs.

**Comment by bvaughn** [comment]
Ooh! How do you setup a forward for `schedule/tracking`? I wasn't sure...

**Comment by gaearon** [comment]
>If we can remove ReactIs also– can we remove React too (and the entire plugin)?

Probably, yes.

>How do you setup a forward for schedule/tracking?

You need to add folder to a special directory and then re-run a special script.

**Comment by react-linter** [comment]
<details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 2d5c590cc2e0bffb1b3b9b2ace942faf39a5fb6d...bdf2a06ca52dd83e907f9ff27eeab29692651501</p>


  
## schedule
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
schedule.development.js | n/a | n/a | 0 B | 19.17 KB | 0 B | 5.74 KB | UMD_DEV
**schedule.production.min.js** | **n/a** | **n/a** | **0 B** | **3.16 KB** | **0 B** | **1.53 KB** | **UMD_PROD**

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by gaearon** [comment]
I'll need to confirm that this works and then we can merge

**Comment by bvaughn** [comment]
Yeah, totally. I'm in the process of testing it now.

**Pull request merged**
