### PR TITLE
Expose ReactCoroutine on __SECRET as unstable API

### PR DESCRIPTION
**Pull request by thejameskyle**
Opening PR for the sake of discussion after talking to @gaearon. 

I've wanted to experiment with ReactCoroutine for awhile. I can copy the code into another project to try it out and I will, but Dan brought up adding it to `__SECRET...` so here's a PR

### CODE REVIEW

**Comment by thejameskyle** [comment]
Note: I didn't test or think about the actual contents of this change that much, I can fix it up if the team wants to do this.

**Comment by gaearon** [comment]
I think we could move it to `react` package since that's the right place for "isomorphic" stuff. I think we planned to move it there after it's more fleshed out, but might as well do now. 

Then export it from `packages/react/src/React.js` in the secret field (there's already a few things there).

Existing imports of `ReactCoroutine` in the reconciler would then need to be changed to read it from that internal field of `require('react')`. There shouldn't be many.

Does this make sense?

**Comment by thejameskyle** [comment]
What should be done with the types [being imported from `ReactTypes`](https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactCoroutine.js#L13)?

Does it make sense to move the `ReactTypes` module into `react` as well?

**Comment by gaearon** [comment]
I think those should be moved to `shared/`. I think I did that in https://github.com/facebook/react/pull/11303 but it's not ready yet.

**Comment by gaearon** [comment]
Thanks for PR and the discussion. I went ahead and made a separate package for this. https://github.com/facebook/react/pull/11364

It will be out together with 16.1.

**Pull request closed without merging**
