### PR TITLE
Remove injectMixin

### PR DESCRIPTION
**Pull request by vjeux**
The only callsite left was removed here: https://github.com/facebook/react/commit/e8af100849932387643977587ccd7a4c1a981470#commitcomment-17570210 but the code to handle it remained.

Test Plan:
tbgs and ibgs, make sure there's no callsites.

Reviewers: @jimfb, @spicyj, @sebmarkbage

### CODE REVIEW

**Comment by spicyj** [comment]
lgtm

**Comment by vjeux** [comment]
What's the next step? Do I just click the merge button?

**Comment by spicyj** [comment]
Please also give it a semver label (semver-patch) and milestone (15.y.z since it doesn't need to be in any particular release), then squash and merge.

**Comment by sebmarkbage** [comment]
Nice. I think getNodeHandle in RN was the last one to need this.

**Pull request merged**
