### PR TITLE
Refs between fiber and stack

### PR DESCRIPTION
**Pull request by spicyj**
I feel gross. Better ideas welcome.

### CODE REVIEW

**Comment by spicyj** [comment]
(Non-additive test changes are just to improve test isolation.)

**Comment by sebmarkbage** [comment]
So before we go down this line, do we have an idea of how many more of these issues we could face? Is it only going to be refs? What about warnings/hooks etc?

If it's only refs then any hack seems isolated and fine but if it's going to be a few more maybe we need another approach.

**Comment by sebmarkbage** [comment]
(On top of the existing batchedUpdates and findDOMNode hacks)

**Comment by spicyj** [comment]
We could probably have problems if we read the owner and call .getName() on it. Not sure what else.

**Comment by spicyj** [comment]
Now that I fixed Flow it uses the ReactInstance type in the file so when we remove that we'll notice.

**Pull request merged**
