### PR TITLE
[Stack] Fix error boundary when mounting a component into a already mounted tree

### PR DESCRIPTION
**Pull request by edvinerikson**
Opening a failing test PR for error boundary in Stack. If there is an easy fix I will be happy to fix it otherwise I guess I can wait for Fiber which this seems to be working in
cc @gaearon 
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`).
6. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
7. If you added or removed any tests, run `./scripts/fiber/record-tests` before submitting the pull request, and commit the resulting changes.
8. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

### CODE REVIEW

**Comment by gaearon** [comment]
I think it might be a legit bug in Stack implementation. It’s known to be incomplete but if you see an easy fix, go for it.

**Comment by edvinerikson** [comment]
I think I fixed it!! amazing

**Comment by edvinerikson** [comment]
Not sure if the test name is good enough, couldn't come up with anything better. I tried to use the existing components as well but then the test started giving false positives (implementation was wrong but test passed anyway).

**Comment by gaearon** [comment]
Can you explain why existing components didn't work? This will be confusing to future readers.

**Comment by edvinerikson** [comment]
I'll put a inline comment 👍🏼

**Comment by edvinerikson** [comment]
when thinking about it, maybe the assignment should occur after `unmountComponent` as well? 🤔

**Comment by gaearon** [comment]
Sorry, I meant I don't understand why you define your own `ErrorBoundary` and `BrokenRender`. Somebody will think it's duplication and remove them.

**Comment by edvinerikson** [comment]
oh maybe you meant in the in the tests.. I am not 100% sure why they didn't work.. it was something with the wrapping `<div>` in `ErrorBoundary` that caused it. I tired to remove the `div` but then other tests started to fail.

**Comment by gaearon** [comment]
We need to have a good explanation so that we really understand the problem before fixing it. There may be more corner cases.

**Comment by edvinerikson** [comment]
I can't really pinpoint the cause.. but it seems that as soon as there is a Host component within the same owner, the composite component manages to resolve to that one as the host node.

`ReactDOM.render(<div><ErrorBoundary><BrokenRender /></ErrorBoundary></div>)` doesn't work but `<ErrorBoundary><div><BrokenRender /></div></ErrorBoundary>`  works.

`<ErrorBoundary><div><CompositeAsManyAsYouWant><BrokenRender /></CompositeAsManyAsYouWant></div></ErrorBoundary>` works as well. it just have to be a host component some where for it to work

I think it takes a slightly different code-path somewhere when there is a host component which is why it works.

**Comment by gaearon** [comment]
Just to set expectations, this probably won't be a high priority for us since Fiber supersedes it anyway. It’s a nice find, but I’d need to dig into why exactly this happens, and why exactly this fix works, to accept it.

**Comment by edvinerikson** [comment]
Yeah I can see that. I noticed more issues than this as well so I guess
it's better to wait for Fiber.

**Pull request closed without merging**
