### PR TITLE
Test :Add a small test for ReactTestUtils to find rendered component with type in document

### PR DESCRIPTION
**Pull request by Biki-das**
I tried to write  test for the   ReactTestUtils to find rendered component with type in document

Tests before this PR

Windows PowerShell 4_13_2022 11_35_24 PM

Tests after this PR 

Windows PowerShell 4_13_2022 11_35_30 PM

### CODE REVIEW

**Comment by Biki-das** [comment]
@lunaruan could you review?

**Comment by Biki-das** [comment]
@gaearon could you. Review?

**Review by rickhanlonii — APPROVED** [review]
Seems good to me, surprised that we don't have a test like this already.

**Comment by Biki-das** [comment]
> Seems good to me, surprised that we don't have a test like this already.

Also added some tests one month back to the react ART package too 😀
https://github.com/facebook/react/pull/23195

**Comment by Biki-das** [comment]
hey @rickhanlonii  is it good to go , or there are some nits?

**Comment by Biki-das** [comment]
@gaearon friendly ping :-)

**Comment by worldwidebaby** [comment]
See #21309

**Comment by Biki-das** [comment]
@lunaruan could you review?

**Comment by badajack** [comment]
hey @sebmarkbage could you review!

**Comment by Biki-das** [comment]
hey @eps1lon seems like this can go forward as it's  already been approved looking forward to your thoughts

**Pull request merged**
