### PR TITLE
[joke] its not fine

### PR DESCRIPTION
**Pull request by rickhanlonii**
cheeky idea for blocking this import

### CODE REVIEW

**Comment by markerikson** [comment]
What would be needed to enable cross-renderer contexts instead?

**Comment by superhooman** [comment]
What if it’s installed globally?

**Comment by rickhanlonii** [comment]
@markerikson this is a cheeky joke. Obviously we wouldn't land this. 

The issue to track that feature request is still https://github.com/facebook/react/issues/13332. It's unclear how to implement support for that feature, but we've been talking to @drcmda about options for third-party renderers. When we have more info, we'll update the issue.

**Comment by sebmarkbage** [comment]
Spent some time investigating. Regardless the versions would have to be in perfect lock-step but that turns out to be a requirement anyway so that's fine.

The proper solution that behaves like a Portal should forward the value during a concurrent render into the child. Meaning it should actually be part of the same render phase. That's not just an issue with Context but Props too. Ideally it shouldn't have to commit the outer root before forwarding the inner values.

Additionally, it's not just Context that is contextual. There's internal contexts and for example if you Suspend in the child renderer outside a Suspense boundary, it should affect the parent render. E.g. a startTransition in the parent should stall or .

That's the proper implementation. It's very difficult, and may require compromising on performance for everyone, but it's not impossible. Realistically, that amount of work, I don't see that getting prioritized any time soon. There's just way more pressing issues.

The smaller version of converting an outer render into a sync secondary render after commit, with no Suspense or Transition integration etc. is easier. That might be "good enough". However, there's the question of whether encouraging thinking of these is a single root given that new features won't work seamlessly anyway. So it might've been "good enough" before but not "good enough" in the future.

There's also a whole other approach of creating fake DOM nodes using the DOM renderer.

**Pull request closed without merging**
