### PR TITLE
Dangerfile exits early if build failed

### PR DESCRIPTION
**Pull request by bvaughn**

### CODE REVIEW

**Comment by sophiebits** [comment]
Does this mean if danger succeeds then you push an update and break the build, the old comment sticks around?

**Comment by bvaughn** [comment]
🤔 I'm not sure. I can test it out on this PR by pushing a bad commit.

Maybe I need to explicitly print an error message using `danger.markdown` ..

**Comment by bvaughn** [comment]
Given the current changes, if a build fails in the scenario you describe, @sophiebits, this comment will replace the previous one:
screen shot 2018-12-06 at 2 17 16 pm

If I just `process.exit(0)` without logging anything, I think the danger comment would just be removed (or not added to begin with). Which is preferable?

**Comment by sophiebits** [comment]
I think showing the message is preferable. It's harder to get confused that way.

**Comment by bvaughn** [comment]
Seems redundant, since there will also be an update from CI in that case:
screen shot 2018-12-06 at 2 22 12 pm

In either case, the stale/invalid results stats would be remove.

**Comment by bvaughn** [comment]
I think it's better for the danger comment to be removed if the build fails. I think the red CI ❌ is enough feedback for that case.

Unless anyone objects, I think the behavior this PR currently exhibits is okay.

**Comment by sophiebits** [comment]
ok, cool!

**Comment by bvaughn** [comment]
No problem 😄

**Pull request merged**
