### PR TITLE
Rename ReactDOMClient to ReactDOM

### PR DESCRIPTION
**Pull request by spicyj**
This closer matches the npm package name and (I assume) is what we want to call it internally.

### CODE REVIEW

**Comment by zpao** [comment]
Haaaaaave you met ReactDOM? https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactDOM.js

**Comment by spicyj** [comment]
lol.

**Comment by spicyj** [comment]
fixed.

**Comment by sebmarkbage** [comment]
ReactHTMLSVGFactories is probably more specific. Doesn't include MathML afaik. :)

**Comment by spicyj** [comment]
I mean, it's called `React.DOM`.

**Pull request merged**
