### PR TITLE
Let's call it Blub

### PR DESCRIPTION
**Pull request by vjeux**

### CODE REVIEW

**Comment by vjeux** [comment]
I don't want it Blub, I want it Blob

**Comment by spicyj** [comment]
Let's call it React…

**Comment by amasad** [comment]
:+1:

**Comment by zpao** [comment]
*for anybody who is super confused…*

This was a test of the bot to automatically label PRs as it goes through the review process.

**Comment by gaearon** [comment]
I thought somebody got stoned

**Comment by vjeux** [comment]
I forgot that so many people were listening to pull requests, sorry about that :x

**Comment by gaearon** [comment]
Anyway, @jlongster has already named in [Bloop](http://jlongster.com/Removing-User-Interface-Complexity,-or-Why-React-is-Awesome#The-Bloop-Library).

**Comment by vjeux** [comment]
This was my inspiration!

**Comment by spicyj** [comment]
testing

**Comment by spicyj** [comment]
testing 2

**Comment by spicyj** [comment]
testing 3 (sorry folks, testing emails)

**Comment by bloodyowl** [comment]
is there any chance to see this bot open-sourced? I use these labels in my workflow too, that'd be interesting.

**Comment by vjeux** [comment]
@bloodyowl https://gist.github.com/vjeux/68fc9285791eef56e2c3

**Comment by bloodyowl** [comment]
@vjeux nice, thanks!

**Pull request closed without merging**
