### PR TITLE
Mobile layout for docs

### PR DESCRIPTION
**Pull request by thymikee**
This PR refers to #7833. Provides a basic mobile layout for React docs page.

### CODE REVIEW

**Comment by lacker** [comment]
Nice! Does this change the look of the non-mobile site in any way? Also, can you add a screenshot of the new appearance to this PR?

**Comment by thymikee** [comment]
Sure, here are the screenshots for 375px, 768px, 1377px

localhost-4000-react-community-support html 2
localhost-4000-react-index html 2
localhost-4000-react-index html 1
localhost-4000-react-community-support html 1
localhost-4000-react-community-support html
localhost-4000-react-index html

**Comment by thymikee** [comment]
To answer your question, this should not alter the desktop view. 

However, while adding the mobile layout I've noticed quite a lot places for CSS refactor, but I didn't want to touch anything more than needed to achieve the goal for this PR.

**Comment by hramos** [comment]
This looks reasonable, thanks for the PR! One thing I am not too sure about is the display of TOC links at the top of the page, above the content. This can get out of hand on pages with many links in the sidebar. Could these links be rendered *after* the content instead?

For reference, this is how a regular Docs page and the Blog index look like on an iPhone 5 screen size with your changes. Reaching the content would require a few swipes.

screen shot 2016-10-04 at 3 13 18 pm
screen shot 2016-10-04 at 3 13 09 pm

**Comment by thymikee** [comment]
@hramos no problem, this is what I'm doing for Blog Post page type.

**Comment by thymikee** [comment]
Although I would rather leave Blog page nav as it is right now, because it already has a max of 10 items and for me it's convenient to have this kind of brief list.

Maybe we could limit this to 5 on mobile? (5 is the number of posts displayed on Blog page, so we're consistent here).

**Comment by hramos** [comment]
Yeah that seems useful. Lets leave the blog page as it is.

**Pull request merged**
