### PR TITLE
Don't use Component name in console.createTask

### PR DESCRIPTION
**Pull request by sebmarkbage**
Chrome requires us to have a Task name. Currently the component name appears twice. Once in the Task name and then once in the next callsite that appears within that Component.

This removes the component name from the Task name and just replaces it with `<>` to indicate that it's a React task spawned from a JSX callsite. Yet still keeps it light weight. Since this will repeated every other line in the stack. In a real app it can be very deep.

I keep the name for built-ins because they don't have another stack frame associated with them and they're always the last stack frame since they don't create other elements they're never the owner.

Before/After:

Screenshot 2024-05-30 at 12 06 41 PM
Screenshot 2024-05-30 at 12 18 43 PM

Before/After:

Screenshot 2024-05-30 at 12 06 57 PM
Screenshot 2024-05-30 at 12 18 23 PM

### CODE REVIEW

**Comment by eps1lon** [comment]
If you'd ignore-list the frame, would the task also disappear or would it remain?

**Comment by sebmarkbage** [comment]
If it's between ignore listed items it seems to hide it. In fact, there's some async stacks within those 53 hidden frames in the screen shot. I'm not sure exactly the rules for when it gets hidden though. Like if it needs to be sandwiched or something.

However, even in that case you could have ignored listed the component itself but the component calls another function that isn't (e.g. a render prop) and then the component name of the ignore listed component would disappear and you'd only see your render prop.

**Comment by eps1lon** [comment]
I'm leaning towards keeping the component name in the task. Mostly motivated by not liking `<>` because that just looks like a Fragment. And even that connection is a stretch for the uninitiated I suspect. But also because of the potential issue when the frame is ignore listed and then you don't know what `<>` refers to.

Honestly, I don't really mind seeing the component name twice in `<App>` and `App` but then you spent way more time than I looking at these task stacks. I wouldn't be surprised if I feel the same after looking at task stacks for a while.

**Comment by sebmarkbage** [comment]
The other motivation here is that we can't always get the name which yields `<...>`. It's actually very common because we lazily initialize (require) modules when client components are rendered with Flight or React.lazy.

But yea, I opened this as a separate PR because it's not a slam dunk.

**Comment by sebmarkbage** [comment]
I also hope Chrome removed the `(async)` and then it becomes much cleaner.

**Review by JhonySpark — COMMENTED** [review]
👌

**Comment by sebmarkbage** [comment]
I'll abandon for now since @eps1lon likes the before better.

**Comment by sebmarkbage** [comment]
Another possible alternative would be to actually add prop names and key to the task name. Basically a little mini DevTools view.

**Pull request closed without merging**
