### PR TITLE
Make tutorial CDN URLs use https

### PR DESCRIPTION
**Pull request by adelevie**
All of the CDN'd content is available over HTTPS, SSL ensures a more secure connection, and I can't think of any downside to doing this.

### CODE REVIEW

**Comment by konklone** [comment]
:+1: Yep, no downside, and it prepares the site for eventually being served at an HTTPS connection itself.

**Comment by jsfb** [comment]
Minor performance ramifications, but I agree, nominal.

**Comment by adelevie** [comment]
Thanks for the quick merge!

**Comment by spicyj** [comment]
Note that although fb.me is available over HTTPS, the URLs it redirects to are not.

**Comment by adelevie** [comment]
Ah, interesting. Is there any way around this?

**Comment by jsfb** [comment]
Baby steps.  The fb.me urls can be updated at some point in the future, once the fbcdn supports https or if we post the files on a different cdn.  One reason that CDNs often don't support https is that TLS breaks ISP caches because the ISP can't cache data from an end-to-end TLS connection (obviously).  Either way, it removes one step in the upgrade path if we decide to use a secure CDN, and it means that users will not need to update their URLs if/when we switch the CDN to TLS.

**Comment by konklone** [comment]
fb.me is Facebook's, and the URLs it redirects to are on FB's Akamai-fronted CDN. They have an invalid Akamai cert:

https://dragon.ak.fbcdn.net/hphotos-ak-xpf1/t39.3284-6/10574688_1565081647062540_1607884640_n.js

I think only Facebook can fix that. In the meantime, it's still good practice to provide HTTPS links in the tutorial, and Facebook can fix the fb.me redirects on their own servers without having to update the tutorial code (or the websites of people who have copy/pasted the tutorial code).

**Comment by zpao** [comment]
I think we'll probably just swap these out and stop pointing at fb.me. I did that in the tutorial repo a while ago (it just pulls from cdnjs). The only downside there (and the main reason I haven't stopped using fb.me entirely) is around releases. We want to have something available when we push the releases out but there's usually a small lag time before cdnjs/jsdelivr are updated.

**Pull request merged**
