### PR TITLE
Report version and bundle type to DevTools

### PR DESCRIPTION
**Pull request by gaearon**
This lets us do https://github.com/facebook/react-devtools/pull/667 in a more future proof way.

### CODE REVIEW

**Comment by bvaughn** [comment]
Do we need to update other renderers (eg native)?

**Comment by gaearon** [comment]
Yep, added.

**Comment by iamdustan** [comment]
I assume third party renderers should do this as well?

**Comment by gaearon** [comment]
Yeah. (Although we don't really have a story around how they are built yet.)

**Pull request merged**
