### PR TITLE
Standardised for loops

### PR DESCRIPTION
**Pull request by James-Dunn**
Some loops saved the .length to a variable in the for loop, some didn’t. This caches
the length in all for loops for a minor performance boost and
consistency.

### CODE REVIEW

**Comment by zpao** [comment]
Do you have some data to back up the perf boost claim?

I tend to not actually like this pattern. And it might not generally be needed (http://mrale.ph/blog/2014/12/24/array-length-caching.html is a good read). It might be worth changing the cases where we do cache.

**Comment by jsfb** [comment]
I tend to agree with @zpao regarding the readability of the two loop styles.  I like the readability of the version without the cached loop size.

That said, I just ran a microbenchmark (for what it's worth, see @zpao's article), and the new loop style proposed by @James-Dunn does outperform the uncached version by a few percentage points.  (Tested on chrome, results were 35 mm-ops/sec and 38 mm-ops/sec for uncached and cached respectively).  So that would be in favor of merging this change.

In my opinion, source code should be for human consumption and bytecode should be for machine consumption.  I would much rather work with human-readable code.  There are countless stories of people optimizing for runtimes, the runtimes improve, and the "optimized" code becomes worse than the "unoptimized" code when running in the improved runtime.  The moral of the story being: source code is for humans.  If caching the array length improves performance, I tend to think it should be part of a transform we run (or better, submitted as a pull request to V8), and not a style that engineers need to manually conform to.

**Comment by James-Dunn** [comment]
My initial test showed caching winning by a few percent, but looking at more tests seems to show the opposite. http://jsperf.com/for-loop-caching

I opened another pull request (https://github.com/facebook/react/pull/3552) removing caching from the for loops that had it. We can close this pull request if you agree.

**Comment by zpao** [comment]
#3552 landed so closing this out.

**Pull request closed without merging**
