### PR TITLE
Fixes #7824

### LINKED ISSUE #7824: React fails to update TextNode in IE8
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

React fails to update text nodes in IE8

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

This is as close as I could get to a reproduction: https://fiddle.jshell.net/zrozubsb/1/show/

I think JSFiddle itself doesn't work in IE8 though, so it's masking the real problem, which you can see here:

image

**What is the expected behavior?**

DOM updates/doesn't throw error

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

React 15.3.1. Internet Explorer 8. Not sure if it ever worked; I have a feeling it didn't.

-----

I will be submitting a PR for this shortly as I know you aren't actively supporting IE8 any more, but it's actually a pretty simple fix. I hope I outlined the issue well enough.

### PR DESCRIPTION
**Pull request by mnpenner**
Re-submitting [this PR](https://github.com/facebook/react/pull/7826) since I messed it up. Sorry for the mess.

### CODE REVIEW

**Comment by syranide** [comment]
👍 cc @jimfb (again :))

**Comment by jimfb** [comment]
For posterity, the repro is:

```
const React = require('react');
const ReactDOM = require('react-dom');

var Hello = React.createClass({

    getInitialState: function() {
        return {foo: "foo"};
    },

    clickA: function(ev) {
        this.setState({foo: "bar"});
    },


    render: function() {
        return <div>
            <button onClick={this.clickA}>{this.state.foo} <img src="https://s3.amazonaws.com/media-p.slid.es/uploads/alexanderfarennikov/images/1198519/reactjs.png" width="15" height="15" /></button>
        </div>;
    }
});

ReactDOM.render(
    <Hello name="World" />,
    document.getElementById('container')
);
```

**Comment by marvinhagemeister** [comment]
@mnpenner Thanks for your hard work in tracking this one down!

**Comment by blling** [comment]
@mnpenner do you use React15 in production?

**Comment by mnpenner** [comment]
@blling We're using React 15.6 in production, yes. Soon to upgrade to React 16.2 since we finally dropped IE8.

But in my experience, yes, even 15.6 worked fine with IE8.

**Comment by blling** [comment]
@mnpenner Thanks. Could you list your package.json configs ? :)

**Comment by mnpenner** [comment]
@blling Okay...but this is quite specific to our project, and overkill for just about anything else: https://gist.github.com/mnpenner/d09beb0c243311d2f5f512d0899114c0

**Comment by blling** [comment]
@mnpenner Could you send an email to me with the configs?
I could not open the link for some reason...

blling.fa@gmail.com

**Comment by blling** [comment]
cc @mnpenner , are you there？ I use `webpack1.15.0` and upgrade `React` to `15.0.0`, I get the follow error：
```javacript
if (IE8_DOM_DEFINE) try {
    return dP(O, P, Attributes);
  } catch (e) { /* empty */ }
if ('get' in Attributes || 'set' in Attributes) throw TypeError('Accessors not supported!') // throw this error
```
If i use `React 14.9.0` the error is go away, do you know how could i solve the issue?

**Comment by mnpenner** [comment]
Sorry @blling, I don't know the answer. Try some more polyfills, like `core-js/es6`, `core-js/es5` and `core-js/stage/4`.

**Pull request merged**
