### PR TITLE
added a jspm link

### PR DESCRIPTION
**Pull request by capaj**

### CODE REVIEW

**Comment by jimfb** [comment]
@spicyj I don't have any strong objections, but I wonder if mentioning jspm adds value for our users.  I hear about browserify and webpack all the time, but I don't really hear much about jspm.  There is no wikipedia page for jspm, and while that's not an required metric, it's a pretty low bar to meet and an indication that they don't have critical mass.  Lots of research (both at Facebook and elsewhere) has shown that people who are trying to connect with a new site/person/tool/whatever (like React) are attracted when they see familiarity and are turned away by things/terms that they don't recognize.  You're far more familiar with the js community at large, so I'll let it be your call, but my inclination is that mentioning the top two frameworks (browserify and webpack) is sufficient.

**Comment by spicyj** [comment]
Agree. @capaj Happy to revisit if JSPM becomes more popular.

**Comment by atrauzzi** [comment]
Worth revisiting yet? :)

**Comment by spicyj** [comment]
Sorry, I don't think so.

**Pull request closed without merging**
