### PR TITLE
Add autoFocus to list of whitelisted dom element props.

### PR DESCRIPTION
**Pull request by jimfb**
Add autoFocus to list of whitelisted dom element props.

### CODE REVIEW

**Comment by jimfb** [comment]
@zpao @spicyj

**Comment by spicyj** [comment]
k

**Comment by syranide** [comment]
But we still want to keep our `autoFocus` polyfill as well?

**Comment by jimfb** [comment]
@syranide sorry, can you elaborate?

**Comment by spicyj** [comment]
@syranide I'm guessing you misinterpreted this change as passing autoFocus through to the DOM, but it only silences a new warning about unknown properties because for our purposes, autoFocus is not an unknown property, even though it doesn't pass through the normal attribute list.

@jimfb Would be nice if you added a test here too.

**Comment by syranide** [comment]
@spicyj Doh, my bad.

**Pull request merged**
