### PR TITLE
Specify "files" field for npm packages

### PR DESCRIPTION
**Pull request by zpao**
I had some rogue `.rej` files get published last release. I cleaned those up but for the future, this is good regardless.

### CODE REVIEW

**Comment by vjeux** [comment]
<3

**Comment by sebmarkbage** [comment]
Eh... should I just revert this in #7164 then?

**Comment by zpao** [comment]
Why would you need to? You can add to the `files` field as needed but not revert.

**Comment by sebmarkbage** [comment]
Ah. I can add `lib/` to the other packages like you did for `react`.

**Pull request merged**
