### PR TITLE
Allow to configure hooks to check for async callbacks in eslint-plugin-exhaustive-deps

### PR DESCRIPTION
**Pull request by ahoisl**
## Summary

1. Add option `checkAsyncFor` to configure which effect hooks should be checked for async callbacks
2. Fix position/index of `dependencies` parameter in hooks. Dependencies are usually the last parameter in a hook function, e.g. [useImperativeHandle](https://reactjs.org/docs/hooks-reference.html#useimperativehandle)

## How did you test this change?

1. Added unit tests & tried out in my own project
2. Ran existing unit tests with no errors & tried out in my own project

### CODE REVIEW

**Comment by ahoisl** [comment]
There seem (at least) 3 other PRs trying to improve the dependencies parameter index problem, with #24344 seeming to be the most promising (latest & no conflicts).
The other two (#18861, #21719) also look good but seem to be stale (conflicts).

If any of those will be merged, I will gladly remove the "Correct index for hook dependencies" commit from this PR

**Comment by JamesHemery** [comment]
Any update ?

**Comment by ahoisl** [comment]
It's still an issue.

Another issue was created that reported a similar problem: #26099

**Comment by ahoisl** [comment]
This is still an issue, but commenting was disallowed, so did not have an option to "bump"

**Pull request closed without merging**
