### PR TITLE
chore: update hero example on website

### PR DESCRIPTION
**Pull request by evgenyrodionov**
Change class-component to functional because it's stateless

### CODE REVIEW

**Comment by evgenyrodionov** [comment]
Also updated link to REPL

**Comment by gaearon** [comment]
I think that code is no longer used (sorry, we're switching to a new website).

I'm not sure I want to do this. The other two examples use classes, and it's easier to first introduce someone to `render` and `this.props` once and then build on that knowledge, than to introduce two different syntaxes on the intro page.

But thanks for the PR!

**Comment by evgenyrodionov** [comment]
I wanted to introduce functional components because it's so much easier and obvious than classes. 

But I got your point, thanks for response!

**Comment by evgenyrodionov** [comment]
Yes it is.

**Pull request closed without merging**
