### PR TITLE
Move ReactIOS components to ReactNative

### PR DESCRIPTION
**Pull request by javache**
None of these components are iOS specific, so change the prefix to ReactNative and move them to the common folder.

### CODE REVIEW

**Comment by jimfb** [comment]
@sebmarkbage @zpao

**Comment by sebmarkbage** [comment]
You can also just move them up one level. I only kept this folder structure while I was constantly rebasing.

**Comment by sebmarkbage** [comment]
Accepted. Feel free to hit Squash and Merge when you're ready.

**Comment by facebook-github-bot-3** [comment]
@javache updated the pull request.

**Pull request merged**
