### PR TITLE
Use a closure to bind argument to callback in ReactErrorUtils

### PR DESCRIPTION
**Pull request by Aweary**
See discussion starting [here](https://github.com/facebook/react/issues/8354#issuecomment-261802649).

This prevents the fake event used here from being passed to the callback. This was causing issues where event handlers received an extra argument in dev only.

@gaearon I verified this fix resolves the issue by building and testing in the basic click counter example. I'm not sure where a unit test for this would go.

### CODE REVIEW

**Comment by gaearon** [comment]
Feel free to add a test for ReactErrorUtils if one doesn't exist already. You could also look at change history to see if there were any related tests introduced with this file in the first place.

Can you confirm single argument matches production behavior?

**Comment by Aweary** [comment]
@gaearon I added test for `ReactErrorUtils` 👍

**Comment by gaearon** [comment]
Lint is failing.

**Comment by gaearon** [comment]
Tagging as minor since somebody might have accidentally relied on that.

**Comment by gaearon** [comment]
Linter fails.

**Comment by Aweary** [comment]
@gaearon fixed 👍

**Comment by gaearon** [comment]
LGTM

**Comment by Heedster** [comment]
@aweary @gaearon I am getting this issue in 15.6.1. Is this issue back ?
I see that ReactErrorUtils is not using the bind syntax which was replaced in this pull request. 
https://github.com/facebook/react/blob/v15.6.1/src/renderers/shared/utils/ReactErrorUtils.js#L78

Is that causing the issue ?

**Comment by gaearon** [comment]
We didn’t cherry pick this change so it’s not in 15.x. We might release 15.6.2 with it, see #10040.

**Pull request merged**
