### PR TITLE
Use incrementing numerical IDs to identify DOM components

### PR DESCRIPTION
**Pull request by spicyj**
Builds on #5190. So... ignore the first 10 commits.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Good luck!

**Comment by afraser** [comment]
Is there any way that this could cause problems when using an older version of React on the same page?

**Comment by spicyj** [comment]
Good question. I think this should probably be fine alongside 0.14 but didn't test.

**Comment by afraser** [comment]
I'm wondering about 0.13.3 in particular. If I don't get an answer here I'll let you all know what I find when I dive in.

**Pull request merged**
