### PR TITLE
[DevTools] upgrade electron to latest version & security improvements

### LINKED ISSUE #25667: [DevTools Bug]: react-devtools depends on vulnerable version of electron
### Website or app

https://github.com/facebook/react/blob/main/packages/react-devtools/package.json

### Issue
electron package versions <18.3.7 suffer from a security vulnerability: "Exfiltration of hashed SMB credentials on Windows via file:// redirect".
See https://github.com/advisories/GHSA-p2jh-44qj-pf2v

### Solution
Upgrade electron dependency in react-devtools to >18.3.7

### How often does this bug happen?

Every time

### DevTools package (automated)

_No response_

### DevTools version (automated)

_No response_

### Error message (automated)

_No response_

### Error call stack (automated)

_No response_

### Error component stack (automated)

_No response_

### GitHub query string (automated)

_No response_

### PR DESCRIPTION
**Pull request by mondaychen**
## Summary

resolves #25667
This PR also resolves several security issues in the standalone app

## How did you test this change?

Tested locally `yarn start` in react-devtools package. Everything works normal

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204123419819195

### CODE REVIEW

**Review by tyao1 — APPROVED** [review]

**Comment by micsco** [comment]
@mondaychen thanks for doing this upgrade. I've noted though that the preload.js file is missing from the package (found on npm).

This seems to be because the file wasn't added to the package.json file under the `files` property. I'm not able to make a contribution right now to resolve this but wanted to bring it to your attention in case you can fix it before I can.

**Comment by mondaychen** [comment]
Ah thanks @micsco. I'll work on a fix

**Comment by mondaychen** [comment]
@micsco this should have been fixed in 4.27.4. Thank you again for reporting

**Comment by micsco** [comment]
@mondaychen amazing, thank you for looking at this so quickly. It's not yet on npm but I'll keep an eye out for it and confirm when so. 

Thanks again

**Pull request merged**
