### PR TITLE
Test that ReactErrorUtils module can be shimmed

### PR DESCRIPTION
**Pull request by acdlite**
We do this in www.

### CODE REVIEW

**Comment by acdlite** [comment]
This is a WIP btw. Once I figure out why it's not working in www I'll update the test.

**Comment by acdlite** [comment]
Added a commit to convert shorthand syntax for function Flow types to the expanded form, since something in the www test pipeline can't parse it. I'll follow up with Jest team about this.

PR is now ready for review.

**Comment by gaearon** [comment]
Is this something we want to expose in open source?

**Comment by spicyj** [comment]
We historically haven't; if there are things that this provides but window.onerror can't, we could revisit.

**Comment by acdlite** [comment]
I figured we could revisit this alongside Brian's error logging thing.

**Comment by bvaughn** [comment]
`invokeGuardedCallback` is also only used for `__DEV__` so it probably wouldn't suffice for the generic error-logging stuff I was thinking about. FWIW I was also kind of imagining something that could be used for warnings _as well as_ errors and this is error-specific.

**Comment by acdlite** [comment]
Sure I meant that eventually we'll need an API for hooking into the error/warning logging system, which would replace the need for www to shim this module, which is gross and won't work with flat bundles.

**Comment by bvaughn** [comment]
Gotcha. Agreed.

**Pull request merged**
