### PR TITLE
Remove unstable_ prefix from Suspense

### PR DESCRIPTION
**Pull request by sebmarkbage**
We are using it with lazy and the combination Suspense + lazy seems pretty stable. maxDuration is not but that's only enabled when you're in ConcurrentMode which is still unstable.

Don't forget to fix www.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Although I guess https://github.com/facebook/react/pull/13921 is a counter argument. :)

**Comment by gaearon** [comment]
Would be nice to follow up to understand how it landed while breaking that test.

**Comment by sophiebits** [comment]
Should maxDuration be prefixed?

**Comment by sebmarkbage** [comment]
I think it's fine to leave `maxDuration`. You have to type `unstable_` somewhere to use it. We're going to have to add types for this API and changing that after the fact, especially with the poor versioning story there, it'll be a pain.

**Pull request merged**
