### PR TITLE
Explain how to attach events more explicitly

### PR DESCRIPTION
**Pull request by ioctaptceb**
I spent several hours trying to understand how to attach a React animation event to a React DOM element. Since I am used to doing it the regular javascript way (via `node.addEventListener(...etc)`) I eventually managed the mental gymnastics of realizing "... wait... maybe its just like `onClick`"

Which it was! And it looks quite beautiful. But it did take me a couple of hours. 

I now realize how obvious this is, but it was a very frustrating couple of hours. Since I don't think I am the only person who is going to be confused by this, I have added a small blurb about how to attach these events to React DOM elements. Please let me know if I can write this better somehow, or if the examples are lacking.. Thanks!

### CODE REVIEW

**Comment by jimfb** [comment]
I have no philosophical objection to this, but honestly, it hasn't come up that often.  If you go through the quick start tutorial, you learn to use events there.  Also, handling events is a super common flow in any React code, so you could have looked at pretty much any example app (including the third example on the [reactjs.com](http://reactjs.com) homepage).

CLA required: https://code.facebook.com/cla

**Comment by ioctaptceb** [comment]
Well, saying that someone could find it from sample apps as an argument against it in the official documentation is not a good argument here in my opinion. it doesn't matter if it's in a tutorial or if it's in all tutorials. the API docs should have all the information that a person needs to interface with that api, otherwise they are incomplete. i feel quite strongly about good documentation, and good documentation sometimes requires pointing out the obvious. at the present moment, there is no resource that you can easily access that has comprehensive information about how to use events in the react docs.

**Comment by ioctaptceb** [comment]
Hi again, 

I am coming back to this because I think I need to emphasis the importance of this. Recently I was coaching a couple of developers on react, and when we came to the question of events and the use of events in react. I told them to go to the event documentation and see if any of the events fit their purposes. They replied that they had already looked at that page, and had no idea how to use these events. I am a more experienced developer, and I did the tutorials for react, however when I cam across this page, I was also confused, simply because im used to the vanilla JS way of attaching events. This is why I opened this PR, and I suspected that I was not the only person running into this.

I think one of the reasons you do not have many people complaining is because either its obvious to them (they already have experience), or they don't realize that the events doc page is in fact describing how to use what they want to use in react (because there is no information of how to implement it). In general, less experienced programmers that I have worked with have found the react docs rather mystifying, especially since there are few examples or explanations of how to read the docs, and the docs do not follow a standard format. I find the docs quite good, but I also understand why this is difficult for less experienced developers. It would be good to make the docs more friendly and accessible. Also, the docs should be complete, if you are telling people to just do the quick start tutorial to get information about some part of the api, that might mean that the docs are incomplete. By being accessible and sometimes explaining the obvious means that more people do things "the react way" and the community grows.

**Comment by gaearon** [comment]
Please sign the CLA, we can’t get this in without the CLA.
I think this is fine but let’s tweak this:

* Make this the first section in this file (since it’s aimed at beginners)
* Keep just one example, there is no need to have so many examples there
* Link to the section of the docs that explains how to attach events (e.g. the tutorial) and clarify that the rest of this page assumes you already know how to use them

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by milesj** [comment]
The docs on events are pretty straight forward. This seems unnecessary.

**Comment by zpao** [comment]
I this is fine to have but I completely agree with @gaearon - it should be an into at the top of this page, it should be short and sweet, and importantly correct ("event handlers can directly be attached to DOM elements" is misleading as most event handlers aren't attached directly but work through delegation).

**Comment by aweary** [comment]
This is handled well by our [new doc page on events](https://facebook.github.io/react/docs/handling-events.html), so I think this is safe to close 👍

**Pull request closed without merging**
