### PR TITLE
move docs and examples licenses

### PR DESCRIPTION
**Pull request by jonricaurte**
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run prettier`).
6. Make sure your code lints (`npm run lint`).
7. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
8. If you haven't already, complete the CLA.

### CODE REVIEW

**Comment by sophiebits** [comment]
It's better to keep them in the root of the repo for clarity so no one accidentally thinks the main license applies to docs content.

**Comment by jonricaurte** [comment]
I see. Was just trying to make it so the MIT License was displayed in the top navigation bar: https://github.com/facebook/react/issues/10889

**Comment by sophiebits** [comment]
Got it. I think it's clearer to keep it this way; if GitHub will only display it if there is one LICENSE then I guess we'll have to do without. Thanks!

**Comment by gaearon** [comment]
We could also move docs in a different repo (like many projects do).

**Comment by jonricaurte** [comment]
Just wanted to make it less of a headache for you all so it basically shows the GitHub stamp of approval kind of thing especially after seeing all the discussions regarding licenses the past few weeks.

**Comment by gaearon** [comment]
Yea, I agree it would be nice. I'm just not sure we can do it.
It would be nice if GH just let you pick the primary license..

**Comment by jonricaurte** [comment]
I agree.

**Pull request closed without merging**
