### PR TITLE
add useStateObject

### PR DESCRIPTION
**Pull request by ofirzBM**
useStateObject is using useState for create single object and exposing it's properties as accessors.
It removes the use of [val, setVal] array and use property accessor for both get and set.

Usage:
`const state = getStateObject({ test: 1 });

const update = (val) => {
	state.test = val;
}
return <div>{state.test}</div>`

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. Run `yarn` in the repository root.
3. If you've fixed a bug or added code that should be tested, add tests!
4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.
5. Run `yarn test-prod` to test in the production environment. It supports the same options as `yarn test`.
6. If you need a debugger, run `yarn debug-test --watch TestName`, open `chrome://inspect`, and press "Inspect".
7. Format your code with [prettier](https://github.com/prettier/prettier) (`yarn prettier`).
8. Make sure your code lints (`yarn lint`). Tip: `yarn linc` to only check changed files.
9. Run the [Flow](https://flowtype.org/) typechecks (`yarn flow`).
10. If you haven't already, complete the CLA.

**Learn more about contributing:** https://reactjs.org/docs/how-to-contribute.html

### CODE REVIEW

**Comment by ofirzBM** [comment]
> Is there a reason you believe this should be in core and not just a library?

Thank you for your feedback,
I don't think so, but I believe this approach is easier to use and read.

**Comment by threepointone** [comment]
It’s unlikely we’re going to add this to our list of primitives. I’m going to close this PR, I would recommend you make a reusable library of this instead.

**Comment by ofirzBM** [comment]
> It’s unlikely we’re going to add this to our list of primitives. I’m going to close this PR, I would recommend you make a reusable library of this instead.

Sad, but thanks again for your time.
Beside that, how do you find this approach? is it easy to understand? use?

**Comment by threepointone** [comment]
It’s not bad! Don’t be discouraged that this didn’t land in react, it’s not a commentary on your code or abilities at all. React tries very hard to be a minimal api with only the basic blocks so that developers and users can make their own abstractions like yours. It would make sense to be directly in react only if it couldn’t be solved with an abstraction, or is so commonly used that it only makes sense to include it by default. 

So yes, your abstraction looks useful. As some feedback - while react devs also usually try to stay away from mutative apis where they manually mutate objects like above, but libraries like mobx show that there’s still appeal for the approach. There’s definitely an audience for your api, you just need to find it :)

Good luck!

**Pull request closed without merging**
