### PR TITLE
[WIP] Allow dev to acknowledge ‘onChange’ warning by passing undefined/null

### PR DESCRIPTION
**Pull request by nicolevy**
### Problem 1 - pushed

When explicitly setting onChange prop to undefined or null, a warning is still presented
```
<input type="radio" checked={true} onChange={undefined} />
```
### Problem 2

Warning is not shown unless `checked` has a truthy value, ie this does not prompt a warning:
```
<input type="radio" checked={false} />
```

References issue #12477

### CODE REVIEW

**Comment by react-linter** [comment]
<details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 52afbe0ebb6fca0fe480e77c6fa8482870ddb2c9...922fead8e4e2ba7b10d9d578362e8ee5feba8afe</p>


  
## react-test-renderer
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-test-renderer.development.js | n/a | n/a | 0 B | 345.01 KB | 0 B | 72.25 KB | UMD_DEV
**react-test-renderer.production.min.js** | **n/a** | **n/a** | **0 B** | **54.61 KB** | **0 B** | **16.67 KB** | **UMD_PROD**
react-test-renderer-shallow.development.js | n/a | n/a | 0 B | 23.67 KB | 0 B | 6.34 KB | UMD_DEV
**react-test-renderer-shallow.production.min.js** | **n/a** | **n/a** | **0 B** | **7.17 KB** | **0 B** | **2.34 KB** | **UMD_PROD**

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by gaearon** [comment]
I'm not sure we decided on #12477 yet. Let me follow up there.

**Comment by nicolevy** [comment]
@gaearon no problem! The part that I fixed was a really quick one so I thought I’d push that. I can always close this and open up another one to work on the falsey checked value problem. That fix is going to mess with a lot of tests I think 🤔

**Comment by nicolevy** [comment]
re-scoping

**Pull request closed without merging**
