### PR TITLE
Update tutorial with reference to autobinding docs

### PR DESCRIPTION
**Pull request by bruceharris**

### CODE REVIEW

**Comment by jimfb** [comment]
If we're going to do this, we would need to mention that this is only true for the `createClass` API (not for ES6 classes).  But I'm not convincd this is worthwhile, as we're going to change the docs to ES6 classes soon, and this will just need to be removed again.

**Comment by bruceharris** [comment]
@jimfb Updated to indicate that this is specifically with `createClass(...)`. Since we are providing a link to the docs that describe autobinding (and how it doesn't work with ES6 classes), I'd suggest this is an improvement to the current state.

When I read the tutorial I was struggling to understand how this could work; first tried to see if JSX compilation was binding the functions, then had to google around for a while until I found a blog post that explained autobinding.

**Comment by facebook-github-bot-8** [comment]
@bruceharris updated the pull request.

**Comment by jimfb** [comment]
Yeah, ok, thanks!

**Pull request merged**
