### PR TITLE
Revert "Remove object-assign polyfill (#23351)"

### LINKED ISSUE #24103: Bug: Yarn build fail, rollup issues
React version: Current main branch

## Steps To Reproduce

1. Clone the repository from the main branch
2. Install node and yarn (node version: 16.14.0, yarn version: 1.22.17, JDK version: tried both 11 and 17)
3. Run yarn
4. Run yarn build

## The current behavior
Error message :

``` 
C:\Users\Irene Park\Desktop\react>yarn build
yarn run v1.22.17
$ node ./scripts/rollup/build.js
 BUILDING  react.development.js (umd_dev)
 OH NOES!  react.development.js (umd_dev)

RangeError: Maximum call stack size exceeded
    at ExportDefaultVariable.includeCallArguments (C:\Users\Irene Park\Desktop\react\node_modules\rollup\dist\shared\node-entry.js:2943:25)
    at Identifier$1.includeCallArguments (C:\Users\Irene Park\Desktop\react\node_modules\rollup\dist\shared\node-entry.js:4477:23)
    at LocalVariable.includeCallArguments (C:\Users\Irene Park\Desktop\react\node_modules\rollup\dist\shared\node-entry.js:2950:23)        
    at Identifier$1.includeCallArguments (C:\Users\Irene Park\Desktop\react\node_modules\rollup\dist\shared\node-entry.js:4477:23)
    at ExportDefaultVariable.includeCallArguments (C:\Users\Irene Park\Desktop\react\node_modules\rollup\dist\shared\node-entry.js:2950:23)
    at Identifier$1.includeCallArguments (C:\Users\Irene Park\Desktop\react\node_modules\rollup\dist\shared\node-entry.js:4477:23)
    at LocalVariable.includeCallArguments (C:\Users\Irene Park\Desktop\react\node_modules\rollup\dist\shared\node-entry.js:2950:23)        
    at Identifier$1.includeCallArguments (C:\Users\Irene Park\Desktop\react\node_modules\rollup\dist\shared\node-entry.js:4477:23)
    at ExportDefaultVariable.includeCallArguments (C:\Users\Irene Park\Desktop\react\node_modules\rollup\dist\shared\node-entry.js:2950:23)
    at Identifier$1.includeCallArguments (C:\Users\Irene Park\Desktop\react\node_modules\rollup\dist\shared\node-entry.js:4477:23) {       
  watchFiles: [
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\index.experimental.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\React.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\forks\\ReactSharedInternals.umd.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactCreateRef.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactChildren.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactMemo.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactElement.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactBaseClasses.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactContext.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactForwardRef.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactLazy.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactHooks.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactServerContext.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactElementValidator.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactMutableSource.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactStartTransition.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactAct.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactCurrentDispatcher.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactCurrentActQueue.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactDebugCurrentFrame.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactSharedInternals.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactCurrentOwner.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactCurrentBatchConfig.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactServerContextRegistry.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\react\\src\\ReactNoopUpdateQueue.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\shared\\ReactSymbols.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\shared\\ReactVersion.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\scheduler\\index.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\shared\\ReactFeatureFlags.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\shared\\consoleWithStackDev.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\shared\\isArray.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\shared\\getComponentNameFromType.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\shared\\CheckStringCoercion.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\shared\\hasOwnProperty.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\shared\\assign.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\shared\\isValidElementType.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\shared\\checkPropTypes.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\shared\\ReactComponentStackFrame.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\shared\\enqueueTask.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\scheduler\\src\\forks\\Scheduler.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\scheduler\\src\\SchedulerFeatureFlags.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\shared\\ConsolePatchingDev.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\scheduler\\src\\SchedulerMinHeap.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\scheduler\\src\\SchedulerProfiling.js',
    'C:\\Users\\Irene Park\\Desktop\\react\\packages\\scheduler\\src\\SchedulerPriorities.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## The expected behavior
No error messages from rollup. Success in yarn build.

### PR DESCRIPTION
**Pull request by jeongwoopark0514**
This reverts commit 1ad8d81292415e26ac070dec03ad84c11fbe207d.
Closes #24103.

## Summary

I just started to contribute to React repository. I followed the manual (https://reactjs.org/docs/how-to-contribute.html) and installed all the necessary tools before I start any major contributions. However, I noticed 'yarn build' does not work in the main branch and found out that from that commit yarn build started to fail. 

## How did you test this change?
I did 'yarn build' and 'yarn test'. This is not additional coding and the previous commits should have been already approved, so there should be no big issue.

### CODE REVIEW

**Comment by asemqaffaf** [comment]
LGTM

**Comment by gaearon** [comment]
The build clearly works on CI so this has something to do with your local environment. Maybe there’s some mistake that causes it to break on windows in particular? In any case, reverting that PR isn’t the way to go. Please find and address the root of the current problem.

**Comment by zjfresh** [comment]
I found it was the bug of Rollup(see [the fix](https://github.com/rollup/rollup/pull/3581) in [Rollup@2.10.6](https://github.com/rollup/rollup/releases/tag/v2.10.6) on 22 May 2020):
image
image

I try upgrade rollup to 2.10.6 and fix rollupConfig treeshake.pureExternalModules to treeshake.moduleSideEffects: pureExternalModules

Then the problem is Babel seems doesn't transform the Object.assign.(When all is fun in mac but on my windows 10, Nodejs 16 and 17)
image
image

**Comment by zjfresh** [comment]
See scripts\babel\transform-object-assign.js

"Don't replace Object.assign if we're transforming shared/assign"

React avoid transform object-assign by itself, but some where has change Object.assign to assign :(

**Comment by zjfresh** [comment]
#24318 Solution to this problem

**Pull request closed without merging**
