### PR TITLE
Make devtools warning disappear if installed

### PR DESCRIPTION
**Pull request by sophiebits**
Depends on facebook/react-devtools#23 to be useful.

### CODE REVIEW

**Comment by sahas-** [comment]
I installed the latest extension few days back, it was working good, however, dont see the plugin anymore in devtools. When Ioad my app, I see this on the console " Download the React DevTools for a better development experience"

**Comment by gaearon** [comment]
@sahas- You're sure you're using React 0.12?

**Comment by sahas-** [comment]
@gaearon - it says Version: 0.12.1. I did pull it down from Chrome store..

**Comment by gaearon** [comment]
@sahas- I meant React's version, not extension's

**Comment by sahas-** [comment]
yep, here is what I see
// Version exists only in the open-source version of React, not in Facebook's
// internal version.
React.version = '0.12.2';

**Comment by sahas-** [comment]
any suggestions?

**Comment by gaearon** [comment]
Maybe you are opening a page via `file://` protocol? In this case Chrome disables extensions unless you tick a special checkbox on Extensions page.

**Comment by sahas-** [comment]
Thanks. I'm running the app using mongoose web server locally. It did work a week ago but stopped for some reason.

**Comment by Tectract** [comment]
I find this message to be distracting to my dev process. How do I turn it off?

**Comment by OR13** [comment]
As an Angular dev consuming a 3rd party React plugin (Help Scout Beacons), I'd rather not see this message ever... I guess I will submit an issue to the plugin provider, as well. 

Reminds me of: https://code.google.com/p/google-cast-sdk/issues/detail?id=309

Its not good advertising...

**Comment by maxfriedmann** [comment]
We're using https://www.npmjs.com/package/zombie for some headless ui testing and this message pops up all the time. We're having react components there (which are tested by JEST in a different step) as well but in that scenario we explicitly don't want to use the React DevTools. 

I agree with @OR13, not a very good place for advertising...

```
> jasmine-node --test-dir tests/ui --coffee --matchall --autotest

Watching for changes in tests/ui
Download the React DevTools for a better development experience: https://fb.me/react-devtools
.Download the React DevTools for a better development experience: https://fb.me/react-devtools
.

Finished in 0.622 seconds
2 tests, 4 assertions, 0 failures, 0 skipped


tests/ui/homepage-spec.js was changed
Download the React DevTools for a better development experience: https://fb.me/react-devtools
.Download the React DevTools for a better development experience: https://fb.me/react-devtools
.

Finished in 0.618 seconds
2 tests, 4 assertions, 0 failures, 0 skipped


tests/ui/homepage-spec.js was changed
Download the React DevTools for a better development experience: https://fb.me/react-devtools
.Download the React DevTools for a better development experience: https://fb.me/react-devtools
.

Finished in 0.619 seconds
2 tests, 4 assertions, 0 failures, 0 skipped
```

**Comment by mikeesouth** [comment]
Seconded. How can we disable this warning? I'm using a library (auth0-lock) and that library is including React. I'm not using React myself and I have no interest in installing the React DevTools.

**Comment by newswim** [comment]
Thirded.

**Comment by kyletaylored** [comment]
+1

I'm not even a React developer, and this message is incredibly distracting when working on my own project, but it's caused by some browser extension using React. If someone is using React and you want them to use DevTools, make it blatantly obvious in the docs instead of spamming every developer's console who isn't even using it.

**Comment by wbowers-coursera** [comment]
+1 still seeing this.

**Pull request closed without merging**
