### PR TITLE
Failing test for Context.Consumer in suspended Suspense

### PR DESCRIPTION
**Pull request by overlookmotel**
Failing test for issue #19701.

Apologies if I'm not understanding the correct use of `expect(Scheduler).toHaveYielded()`.

### CODE REVIEW

**Comment by engprodigy** [comment]
@overlookmotel and @gaearon This is looking abandoned. Can I take a look at it?

**Comment by eps1lon** [comment]
Bump

**Comment by overlookmotel** [comment]
Still relevant I think!

**Comment by gaearon** [comment]
Thanks. Potential fix in https://github.com/facebook/react/pull/23095.

**Pull request closed without merging**
