### PR TITLE
adds ReactRally & Reactive 2016 + conf locations

### PR DESCRIPTION
**Pull request by yanandcoffee**

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-8** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by jimfb** [comment]
Looks good to me 👍 

I like that you added the locations, that was a nice touch.

cc @zpao

**Comment by zpao** [comment]
Thanks!

**Comment by yanandcoffee** [comment]
:) glad to be of help.

**Pull request merged**
