### PR TITLE
Update to Babel 6

### PR DESCRIPTION
**Pull request by kittens**
Update to use Babel 6. Also enables loose mode for some of the transforms.

I've also ported the `dev-expression` plugin to Babel 6, PR is here: facebook/fbjs#117 Will update this PR once it's been merged and released to npm.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
cc @zpao

**Comment by kittens** [comment]
I'll compare build sizes to make sure there's no regressions.

**Comment by yaycmyk** [comment]
Apparently it's not a great idea to use loose mode: http://www.2ality.com/2015/12/babel6-loose-mode.html

**Comment by kittens** [comment]
@yaycmyk It's fine, we aren't relying on any of the semantics we're losing.

**Comment by kittens** [comment]
```
   raw     gz Compared to master @ 7a3009c2b4560b3db40f7b5a21cd70defe2b8c48
     =      = build/react-dom-server.js
     =      = build/react-dom-server.min.js
     =      = build/react-dom.js
     =      = build/react-dom.min.js
   -28     -4 build/react-with-addons.js
     =      = build/react-with-addons.min.js
   -26     +1 build/react.js
     =      = build/react.min.js
```

**Comment by kittens** [comment]
Forgot to add the ES3 safety transforms that quote properties that are keywords. Adding those transforms now yields:

```
   raw     gz Compared to master @ 7a3009c2b4560b3db40f7b5a21cd70defe2b8c48
     =      = build/react-dom-server.js
     =      = build/react-dom-server.min.js
     =      = build/react-dom.js
     =      = build/react-dom.min.js
   -18     +7 build/react-with-addons.js
     =      = build/react-with-addons.min.js
   -16    +13 build/react.js
     =      = build/react.min.js
```

The rest of the byte savings are due to some Babel 6 code generator improvements that reduces the amount of redundant parentheses. A diff of `react.js` and `react-with-addon.js` is available here: https://gist.github.com/kittens/1f168ea83b6714ff27d8

**Comment by zpao** [comment]
`fbjs-scripts@0.6.0-alpha.2` is up

**Comment by SimenB** [comment]
The ES3-transforms are still buggy, aren't they?

babel/babel#3368

**Comment by kittens** [comment]
@SimenB Yeah it doesn't effect the React codebase and we're going to merge that soon anyway.

**Comment by kittens** [comment]
@zpao Having some weirdness with ESLint and `fbjs-scripts`. The [lint build](https://travis-ci.org/facebook/react/jobs/111887446) is failing because it couldn't find `.eslint` which was renamed to `.eslintrc.js`, however I've already updated it [here](https://github.com/kittens/react/commit/5412109b373c407b0238f654474dc795a5dc40c8#diff-1dc6ee56b778cd91e0327b52aaeaa1b9R5), any idea where else it could be referenced?

**Comment by zpao** [comment]
Latest lint build is failing for a different reason - lots of lint failures: https://travis-ci.org/facebook/react/jobs/112105791

Add 
```yaml
 ecmaFeatures:
   modules: false
```

into our .eslintrc and you'll be ok. There are a couple other new warnings due to changed upstream config too, but that'll fix the bulk of them (and you can ignore the rest if you want)

**Comment by kittens** [comment]
CI is green, I fixed the new errors but left the line warnings. Let me know if there's any more tests you want me to run to ensure this doesn't break anything (it shouldn't, the diff I posted before does not change anything).

**Comment by zpao** [comment]
Thanks 😺

**Pull request merged**
