### PR TITLE
Add perf-counters npm module to scripts

### PR DESCRIPTION
**Pull request by spicyj**
```
$ node
> var PerfCounters = require('perf-counters');
> PerfCounters.init();
> var start = PerfCounters.getCounters(); console.log('test'); var end = PerfCounters.getCounters();
test
> start
{ instructions: 1382, loads: 421, stores: 309 }
> end
{ instructions: 647633, loads: 195771, stores: 133246 }
>
```

### CODE REVIEW

**Comment by spicyj** [comment]
cc @jimfb @sebmarkbage 

This should install out of the box on CentOS 7 and also seemed to on Ubuntu 14.04 (with g++ installed). On CentOS 6, I had to do

```
$ yum install devtoolset-2 devtoolset-2-binutils
$ CXX=/opt/rh/devtoolset-2/root/usr/bin/g++ npm install perf-counters
```

In either case, it will not work with node 0.10. I tested only with iojs-v3.3.0 which is easy to install using nvm.

**Comment by jimfb** [comment]
Looks good.

**Comment by jimfb** [comment]
Posting mostly for the reference of my future self: Had to use v4.1.0 instead of iojs on my ubuntu machine.  Also, npm install perf-counters.

**Comment by spicyj** [comment]
(iojs works fine with this, but you need to `npm install` using the same version of node that electron uses, if you're using electron.)

**Pull request merged**
