### PR TITLE
Update webpack according to brand guidelines

### PR DESCRIPTION
**Pull request by montogeek**
Following official webpack guidelines: https://webpack.js.org/branding/#the-webpack-name
> webpack should always be written in lower-case letters, even at the beginning of a sentence.

### CODE REVIEW

**Comment by gaearon** [comment]
I was hoping they’d change it but seems like the poll was in favor of keeping the lowercase name. Okay.

**Comment by gaearon** [comment]
Can you please do a search over docs and change it everywhere?

**Comment by montogeek** [comment]
Sure

**Comment by montogeek** [comment]
@gaearon Even blogposts?

**Comment by montogeek** [comment]
Updated all ocurrences

**Pull request merged**
