### PR TITLE
Fix this in a functional component for ShallowRenderer

### LINKED ISSUE #13141: react-test-renderer shallow: SFCs should not get `this`
**Do you want to request a *feature* or report a *bug*?**
bug.

**What is the current behavior?**
This addresses a bug in `enzyme`, https://github.com/airbnb/enzyme/issues/1683.

On [this line](https://github.com/facebook/react/blob/master/packages/react-test-renderer/src/ReactShallowRenderer.js#L110) `element.type()` invokes the SFC with `element` as the `this` value. I believe that this is needed for create-react-class components, but that there needs to be a separate branch for SFCs.

**What is the expected behavior?**
`this` inside a strict-mode SFC will be `undefined`, not the element.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
In all of React 0.13, 0.14, 15, and 16, this bug exists.

While the bug ideally will be fixed, I understand that it's highly unlikely that it would be backported to the 14/15 lines - but I can wrap around it if there's a reliable way, in those versions, to distinguish SFCs from create-react-class components (is there?).

### PR DESCRIPTION
**Pull request by koba04**
Fixes #13141

### CODE REVIEW

**Comment by gaearon** [comment]
Thanks!

**Comment by ljharb** [comment]
So actually I think this will break createReactClass components, because they don't have `.isReactComponent` :-/

**Comment by gaearon** [comment]
They assign `ReactComponent.prototype` (where `ReactComponent` is `React.Component`) which includes it. Without this flag, we never `new` something.

**Comment by ljharb** [comment]
hmm - when i `createReactClass({ render() {} }).isReactComponent` i get `undefined`. What am i missing?

**Comment by gaearon** [comment]
It's on the prototype, not on the class.

```js
createReactClass({ render() {} }).prototype.isReactComponent
```

works.

**Comment by koba04** [comment]
Thanks!

**Pull request merged**
