### PR TITLE
update babel-core to 5.8.34 in tutorial docs

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by keyanzhang** [comment]
Thanks! CLA is required before we merge this: https://code.facebook.com/cla

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by jimfb** [comment]
Looks good, thanks @nikolas!

**Comment by Daniel15** [comment]
Ideally we should switch the docs over to [babel-standalone](https://github.com/Daniel15/babel-standalone/blob/master/README.md) as it uses Babel 6.

**Comment by zpao** [comment]
@Daniel15 Let's keep that discussion in #5497. Let me know when babel-standalone gets the auto-transform functionality and we'll switch.

**Pull request merged**
