### PR TITLE
Update uglify-js and lock to 2.4.x

### PR DESCRIPTION
**Pull request by bhamodi**

### CODE REVIEW

**Comment by zpao** [comment]
What does this give us?

**Comment by bhamodi** [comment]
@zpao - a new `--mangle-regex` option. See: https://github.com/mishoo/UglifyJS2/pull/733

**Comment by zpao** [comment]
Do you have intentions for us to use `--mangle-regex`?

FWIW, `^2.4.23` will install `2.4.24` and if we're not actually using the new feature I'm not convinced we need to update the version string.

**Comment by bhamodi** [comment]
Well, there is are also bug fixes coming out with the new release: https://github.com/mishoo/UglifyJS2/commit/905b6011784ca60d41919ac1a499962b7c1d4b02
and https://github.com/mishoo/UglifyJS2/commit/85a5fc0aeb1785982506c09a484e12608ba01624.

Actually you bring up a good point and I have a question about that. Do we want to be implicit and use `^`  to allow people to upgrade to the latest minor version? I know some repos that don't necessarily follow semantic versioning and introduce breaking changes in minor versions. How do you feel about being more explicit about versions and using `~` to only allow patch version upgrades?

And also, doesn't `npm install` on `^2.4.23` just install v2.4.23? I thought it would only upgrade to `2.4.24` if you run `npm update`.

**Comment by zpao** [comment]
> Actually you bring up a good point and I have a question about that. Do we want to be implicit and use ^ to allow people to upgrade to the latest minor version? I know some repos that don't necessarily follow semantic versioning and introduce breaking changes in minor versions. How do you feel about being more explicit about versions and using ~ to only allow patch version upgrades?

Meh. Historically if it becomes an issue, we address it then (eg #4474). For releases we always delete node_modules folder and reinstall fresh, shrinkwrapping in our stable branch to ensure our dependencies are locked. We don't have any issues with updated packages then.

> And also, doesn't npm install on ^2.4.23 just install v2.4.23? I thought it would only upgrade to 2.4.24 if you run npm update.

That depends on if you already have 2.4.23 installed or if nothing is there. 2.4.23 satisfies ^2.4.23. But installing without any version there will grab latest (or look at nested deps and try to do the smartest thing to install the fewest things, which is how npm3 works). Otherwise yes, `npm update` should update to latest. Also explicitly installing with the new version range works over the existing one (`npm i uglify-js@^2.4.23` will install 2.4.24 if 2.4.23 is already installed).

* * *

Soooo ultimately I think I'm just going to say no here.  If there were something specific in that version we had to have, then yes. But making this sort of change for every package update is noisy.

**Comment by zpao** [comment]
I really appreciate the initiative though! I think this is a great way to get involved and I hope to see you around some more :)

**Comment by bhamodi** [comment]
Hey @zpao, thanks for the feedback! I can understand why we wouldn't want to do this for every patch version update. That being said, I would still recommend looking into locking all dependencies to a minor version and using the `~` notation to allow for patch version upgrades. (I'd be interesting in sending a diff for that.)

And ya, I'm trying my best to get involved in the open source community. Hopefully when I better understand this library, I'll be able to contribute more meaningful changes. :)

**Pull request closed without merging**
