### PR TITLE
DevTools: Scroll to first error or warning by click on error or warning icon

### PR DESCRIPTION
**Pull request by behnammodi**
Now, we can click on error or warning icon to scroll to first error or warning

Screen Shot 2021-07-09 at 01 50 42

### CODE REVIEW

**Comment by bvaughn** [comment]
The up/down arrow buttons let you step through errors and warnings. This UI was patterned after UIs like Chrome's find-in-page or Sublime's file search.

I'm not sure I think that clicking on the icons themselves is that intuitive. Can you point me at some reference UIs that work this way maybe?

**Comment by behnammodi** [comment]
You can see this behavior as same in Apple XCode

**Comment by bvaughn** [comment]
> You can see this behavior as same in Apple XCode

Can you show me (in a screen recording)? I don't see it.

**Comment by behnammodi** [comment]
Of course, I will prepare

**Comment by behnammodi** [comment]
@bvaughn Sorry, I mistake

**Review by crypt096 — APPROVED** [review]

**Comment by bvaughn** [comment]
I think this behavior is _okay_ but since it doesn't match IDEs or find-in-page features I can think of, I'm inclined to just leave the feature working as-is. (I think the current behavior is pretty intuitive.) I appreciate the suggestion and the PR though! 🙇🏼  If you're interested in contributing to DevTools, we have a [list of issues](https://github.com/facebook/react/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Component%3A+Developer+Tools%22+label%3A%22good+first+issue%22) that I suggest looking at for starter ideas! 😄

**Comment by behnammodi** [comment]
@bvaughn  Thanks man, I'm going to resolve some of them

**Pull request closed without merging**
