### PR TITLE
Fixed Copyright year for three files and react.js licence to BSD-license

### PR DESCRIPTION
**Pull request by brianpchsu**
I did something stupid in rebase and need to redo pull request. Sorry about this. I changed react.js licence to BSD-license and update the year in that, ReactDOMIframe.js, and setTextContent.js to 2015. Thanks.

### CODE REVIEW

**Comment by brianpchsu** [comment]
It was originally in this thread. 
https://github.com/facebook/react/pull/3135

**Comment by zpao** [comment]
Thanks!

**Comment by syranide** [comment]
@brianpchsu Looks good, for future reference; if you mess up a branch, you can always reset it to master and start from fresh in the same branch.

**Comment by brianpchsu** [comment]
Thanks. I will keep that in mind!!

**Pull request merged**
