### PR TITLE
Add lang="en" attribute to html tag for gh-pages

### PR DESCRIPTION
**Pull request by adelevie**

### CODE REVIEW

**Comment by jimfb** [comment]
@adelevie I'm not entirely sure what a fix to the language thing is going to look like, but I know that index.html is generated from index.md, so modifying the generated output is not going to work.  Also, pull requests should be against `master`, not `gh-pages`;  changes from `master` will get copied over to `gh-pages` after they are in the master branch.

The source file of index.html is index.md, but the md file is translated into html and inserted into the generic page template, so you're probably going to need to find the template file and modify that.  Furthermore, we probably can't just set the `lang` in the template file if we use the same template file for all the translations (not sure if we do).  Regardless, the diff as-is won't work.  I'd recommend looking in /docs/README.md to get an introduction to how the documentation/website is generated.

**Comment by zpao** [comment]
Going to close out since this is against the wrong branch as mentioned (and you can't change the target branch once a PR is created). @jimfb is right - we do use the same templates for all the translations so we'd want a way to make sure that it's possible to override (eg, by specifying a `lang` field in the front matter). It's doable but will be more work than just what you have here.

**Comment by adelevie** [comment]
Hey, that was pretty boneheaded of me!

You all are great.

**Comment by justo-rivera** [comment]
What is the best practice to change the lang attribute of index.html? 
Besides replacing "en"

It's weird to assume a language for an application, and I found no documentation about the best practice on how to change it.

This is kind of a bug because chrome will tell the users of the application to "TRANSLATE FROM ENGLISH" and this is a UX/UI problem.

Thanks

**Pull request closed without merging**
