### PR TITLE
Add playground homescreen to DOM Fixtures

### PR DESCRIPTION
**Pull request by nhunzaker**
This pull request adds a new home screen for the DOM test fixtures that should make it easier to produce test cases without having to setup React locally. Additionally, it provides a "file github issue" button that will generate a new issue with auto-populated browser information:

example

Check it out here:
http://react-dom-fixtures.surge.sh

## Why this PR is so big

In order for this to work, I'm leaning on Formidable's [component-playground](https://github.com/FormidableLabs/component-playground). Naturally, they import React using commonjs. This is problematic for our existing way of handling versioned React code: `const React = window.React`. Webpack can smooth this over using the [`externals`](https://webpack.js.org/configuration/externals/) configuration, but that we can't (as far as I know) do that with `create-react-app`.

So I've ejected `create-react-app`, added this configuration, and updated all of the fixtures to use `import React` instead of `const React = window.React`. I've also tried my best to simplify/cut some fat, but this change set is bigger than I would have liked. 

## Other thoughts

Long term, I would love to deploy this and make it a part of the release process. It would be awesome if we could farm out manual DOM testing to the community (though this is more of a pipe dream at the moment).

### CODE REVIEW

**Comment by gaearon** [comment]
Ooh I really don't want to eject 😞 

Can we make a pre-build step where we point `react` and `react-dom` symlinks to files that just reexport `window.React` and `window.ReactDOM`?

**Comment by aweary** [comment]
I would if we could integrate this with JSFiddle somehow instead? That way we actually reproduce the issue in-browser without having to import the fixture locally, build, etc.

**Comment by gaearon** [comment]
I thought the idea was this would be up somewhere.

**Comment by nhunzaker** [comment]
Yep. I'd like to eventually host this and make it easy for people to file issues as they see them. I also think it would be pretty to copy a test fixture into the editor.

I've reverted the ejection. I'll play around with sym-linking react and react-dom later today.

**Comment by nhunzaker** [comment]
Sorry to answer your question @aweary: I definitely don't want to reproduce JSFiddle, but I've hit issues in the past testing JS fiddle on mobile phones and IE. It can also be a pain to quickly switch versions of React. If we could figure that part out, I'd be game.

**Comment by aweary** [comment]
I see, I missed the part about hosting this. I have a couple clarifying questions + reservations:

* Have we tested that _this_ works on mobile phones and IE?

* What would the process for testing be? With JSFiddle you get a unique link taking you to the hosted example, but in this case it seems like we'd have to manually copy + paste the content into the playground, which seems potentially difficult when testing on other devices (how to test on actual mobile devices?)

* Is the intention to replace the existing JSFiddle issue template and recommend this only, or supplement? JSFiddle lets you include HTML and CSS as well, which in some cases is required to reproduce an issue. 

* It's useful for us that it includes the `TestCase` components and stuff, but I feel it might raise the barrier to entry for providing a reproducible test case. Is there a way to abstract that out? Maybe have fields for issue title + steps to reproduce and just compose those parts of the test case behind the scene?

* I like the idea behind auto-populating browser + OS, but I'm worried it might give us misleading results. For example, if someone is reporting an issue with iOS Safari, they can't write up the test case on iOS Safari. They'll do it on a desktop, and since we're no longer explicitly asking them for this information it's more likely that they'll just exclude it.

**Comment by jquense** [comment]
The mobile case is interesting, because yeah it's unlikely a user will write the test case on the mobile browser, and without a url to the code they wrote it's not easy for them to test it once they do write it. The babel repl serializes the code to the url query and calls it a day. It works fairly well actually for a low-tech solution

**Comment by nhunzaker** [comment]
> Have we tested that this works on mobile phones and IE?

I should have clarified mobile operating systems. This is working well for me on tablets. We'd need to do some UI work to better suite mobile phones. It's actually really nice because I can use something like browserstack.com to paste in a test case from Chrome:

<a href="https://user-images.githubusercontent.com/590904/28278642-c3eadf3c-6aeb-11e7-93f5-218cf8b14cc8.png">
  screen shot 2017-07-17 at 12 28 19 pm
</a>

_Click for a larger view_

But as @jquense pointed out, a shareable URL would generally be better. We could collapse the code view on smaller screens.

I've tested this down to Android 4.3, iOS 5, and IE9 (though older versions need some CSS love, and the parsing the babel runtime can be slow on older, weaker Androids). There's an issue on React 16.0, but otherwise it's working.

> What would the process for testing be?

What if we stringified the test case into a URL? That would be very... long, but shareable.

> Is the intention to replace the existing JSFiddle issue template and recommend this only

Perhaps some time long in the future - but I'm hesitant. I think the JSFiddle still works well.

> It's useful for us that it includes the TestCase components and stuff, but I feel it might raise the barrier to entry...

Great idea. That would shorten a shareable URL too

> I like the idea behind auto-populating browser + OS, but I'm worried it might give us misleading results

Makes perfect sense. I can remove it.

**Comment by nhunzaker** [comment]
- Re-injected (?) react-scripts. Reversing the ejection
- Fixed some style issues in IE9 and older iOS/Android
- Simplified the default test case
- Stubbed React, ReactDOM, and ReactDOMServer (this was super interesting)

**Comment by nhunzaker** [comment]
Added URL serialization of the code snippet:

http://localhost:3000/?version=15.6.1#code=function%20handleClick%20%28%29%20%7B%0A%20%20alert%28%27clicked%27%29%3B%0A%7D%0A%0Alet%20padded%20%3D%20%7Bpadding%3A%2010%2C%20display%3A%20%27inline-block%27%7D%0A%0Afunction%20App%20%28%29%20%7B%0A%20%20return%20%28%0A%20%20%20%20%3Cdiv%3E%0A%20%20%20%20%20%20%3Cspan%20style%3D%7Bpadded%7D%20onClick%3D%7BhandleClick%7D%3EYea%3C%2Fspan%3E%0A%20%20%20%20%20%20%3Cbr%20%2F%3E%3Cbr%20%2F%3E%0A%20%20%20%20%20%20%3Cspan%20style%3D%7Bpadded%7D%20onClick%3D%7BhandleClick%7D%3EYea%2C%7B%27%20%27%7DNah%3C%2Fspan%3E%0A%20%20%20%20%20%20%3Cbr%20%2F%3E%3Cbr%20%2F%3E%0A%20%20%20%20%20%20%3Cspan%20onClick%3D%7BhandleClick%7D%3EYea%2C%7B%27%20%27%7DYea%3C%2Fspan%3E%0A%20%20%20%20%3C%2Fdiv%3E%0A%20%20%29%0A%7D%0A%0AReactDOM.render%28%3CApp%2F%3E%2C%20mountNode%29%3B

Fun thought. We could use a string compression algorithm to make it smaller, but the resulting URL looks pretty weird. 😵 

http://localhost:3000/?version=15.6.1#ㆇ뀦੠뱬͠䌃㤠ꐂ怃Ąë贰耏\‎찴뀉䈅蔠㨁葀ᛗာ듃倇怄⪇¬⩄醀܆Ʌ軁㌦ʺ䢡ㅸ겚캘ೊ찀䬀溨Ⰵ᝞歩迮븽怂쀣⎓耄萜ᰈث℀㮈⒜᠆⁕蘀ᢀ偫ꞛ깕脳耪鈄℩⾍账ሮ〈嘩⑖౤趹℈⺿ᘂℰ⺒⍇᥄⃟爄㌏멁䮉랎乪稚涃뎶䋂쪅ꢼࢫꂑ㴣⤁쀼耬댴锄Ჺ⊕鸁૖稴嘇❅ᒀΗϔ盂

**Comment by nhunzaker** [comment]
No follow up, and this is way out of date. I'll close this and circle back at a later time.

**Pull request closed without merging**
