### PR TITLE
Add dominant-baseline to SVG DOM properties

### PR DESCRIPTION
**Pull request by jdeherrera**

### CODE REVIEW

**Comment by jongold** [comment]
Is there any reason this hasn't been merged?

**Comment by neverfox** [comment]
+1

**Comment by okorz001** [comment]
Bump. Ran into this issue today.

**Comment by gaearon** [comment]
Thank you for the PR, and sorry about the long wait. Now that #5714 is merged, all attributes on SVG elements will be passed through as is, with no need for the whitelist. I'm closing this but please let me know if you have any troubles in master.

**Pull request closed without merging**
