### PR TITLE
argument pooler with rest params and spread

### PR DESCRIPTION
**Pull request by timurtu**

### CODE REVIEW

**Comment by gaearon** [comment]
Thanks for PR! I think the use of different hardcoded poolers is intentional for better performance. So we won't take this.

Now, I can't claim this actually results in better perf since it was optimized for browsers that were mainstream four years ago. Ideally I think we'd like to get rid of this code altogether and just inline the valuable parts in two places where they're used (element traversal and synthetic events). Would you like to look into that instead?

**Comment by timurtu** [comment]
That makes sense I could look into it yeah

**Comment by gaearon** [comment]
cc @lelandrichardson who might also be interested in doing this

**Comment by timurtu** [comment]
Okay let me know @lelandrichardson

**Pull request closed without merging**
