### PR TITLE
Fixed unclear wording in comment

### PR DESCRIPTION
**Pull request by xelad1**
Perhaps not understanding what "key a set a fragment..." is supposed to mean.  Hopefully I'm not misreading this as a typo.

### CODE REVIEW

**Comment by spicyj** [comment]
I think this is supposed to say "set or". Do you mind changing it and squashing your commits? Thanks!

**Comment by xelad1** [comment]
Err I did this in the git gui (bad form I know), not sure how to squash when I commit outside of the terminal.

**Comment by jimfb** [comment]
You should be able to squash by using command line git (even if the commit wasn't originally made using the command line).  The command you're looking for is probably something like `git rebase -i HEAD^^`.

**Comment by zpao** [comment]
squashed and merged: 761921499c2b8e23f3f98f1b9c2c64b07c4b8844

Thanks @xelad1!

**Pull request closed without merging**
