### PR TITLE
Remove some unnecessary repetition

### LINKED ISSUE #19650: Bug:
React version: 16.6.1

## Steps To Reproduce

1. open source code（src\react\packages\react-dom\src\client\ReactDOMComponent.js）

`
if (namespaceURI === HTML_NAMESPACE) {
    namespaceURI = getIntrinsicNamespace(type);
  }
  if (namespaceURI === HTML_NAMESPACE) {
    if (__DEV__) {
      isCustomComponentTag = isCustomComponent(type, props);
      // Should this check be gated by parent namespace? Not sure we want to
      // allow <SVG> or <mATH>.
      warning(
        isCustomComponentTag || type === type.toLowerCase(),
        '<%s /> is using incorrect casing. ' +
          'Use PascalCase for React components, ' +
          'or lowercase for HTML elements.',
        type,
      );
    }
`
## The current behavior
  Why repeat the same if statement

## The expected behavior
merge

### PR DESCRIPTION
**Pull request by bvaughn**
Resolves #19650

### CODE REVIEW

**Review by gaearon — CHANGES_REQUESTED** [review]
This code is not equivalent?

```js
if (x === 5) {
  x = diceRoll()
}
if (x === 5) {
  // ...
}
```

cannot be simplified into

```js
if (x === 5) {
  x = diceRoll()
  // ...
}
```

**Comment by bvaughn** [comment]
Oh geeze. Yeah the `namespaceURI` change is totally not valid. Yikes.

**Comment by bvaughn** [comment]
Thanks Dan. I just tossed this up in a hurry before the Org meeting thinking I'd come back and look at it afterward.

**Comment by gaearon** [comment]
Luckily our test suite caught it ❤️

**Comment by bvaughn** [comment]
I have a feeling that I am going to relive the shame of this PR internally for a long time 😆

**Comment by gaearon** [comment]
To be fair it's a pretty confusing pattern. I remember writing this and thinking what the hell is this doing.

**Pull request closed without merging**
