### PR TITLE
[DOCS] ReactTextComponent was renamed ReactDOMTextComponent a while ago

### PR DESCRIPTION
**Pull request by jayphelps**

### CODE REVIEW

**Comment by jimfb** [comment]
Eeh, ok.  We generally don't take small changes like this, but this does fix a typo, so I suppose we can take it.

**Comment by jayphelps** [comment]
@jimfb ah whoops, didn't realize. Is that to mitigate commit count inflating or something? I haven't seen this happen notably in any other major project, but I wouldn't doubt it does.

What's the sanctioned approach to fixing typos and other doc corrections?

**Comment by jimfb** [comment]
@jayphelps There is some discussion in https://github.com/facebook/react/pull/6463

Generally, we prefer that you squish it into a more meaningful commit that happens to touch the same file.  The TLDR is that these little micro-changes clutter the commit log for a given file and make it more difficult to track the more meaningful history/changes.

**Comment by zpao** [comment]
I think this one is probably fine but I would say we should do a sweep and ensure there are no other places that also need to be updated. This one is a bit different from #6463 since that was a code style change and this is more of a correctness thing.

**Comment by jayphelps** [comment]
@zpao cool, thanks for clarifying. As far as sweep, this was indeed the only place where `ReactTextComponent` hadn't been updated.

**Pull request merged**
