### PR TITLE
Changed example json value.

### PR DESCRIPTION
**Pull request by yuji0602**
Hi.

When I had to try the [tutorial](https://facebook.github.io/react/docs/tutorial.html#updating-state), I get an error at the Chrome console.

```
react.js:19287 Warning: flattenChildren(...): Encountered two children with the same key, `.$undefined`. Child keys must be unique; when two children share a key, only the first child will be used.
```

Fixed value of json.

### CODE REVIEW

**Comment by zpao** [comment]
The JSON there is a simplified representation of what's in the tutorial repo that we expect people to be following along with. However since we did have these ids in the data earlier in the tutorial, this is totally fine.

**Comment by jimfb** [comment]
@yuji0602 Please sign the CLA when you get the chance, so we can merge.  Thanks!

https://code.facebook.com/cla

**Comment by yuji0602** [comment]
@zpao Thank you for checking.
@jimfb I signed the CLA.

**Comment by zpao** [comment]
Just noticed this was against the `15-stable` branch, will cherry-pick over to `master` to make sure we don't lose this in the future.

**Pull request merged**
