### PR TITLE
Validate DOM nesting for hydration before the hydration warns / errors

### PR DESCRIPTION
**Pull request by sebmarkbage**
If there's invalid dom nesting, there will be mismatches following but the nesting is the most important cause of the problem.

Previously we would include the DOM nesting when rerendering thanks to the new model of throw and recovery. However, the log would come during the recovery phase which is after we've already logged that there was a hydration mismatch.

People would consistently miss this log. Which is fair because you should always look at the first log first as the most probable cause.

This ensures that we log in the hydration phase if there's a dom nesting issue. This assumes that the consequence of nesting will appear such that the won't have a mismatch before this. That's typically the case because the node will move up and to be a later sibling. So as long as that happens and we keep hydrating depth first, it should hold true. There might be an issue if there's a suspense boundary between the nodes we'll find discover the new child in the outer path since suspense boundaries as breadth first.

Before:

Screenshot 2024-02-23 at 7 34 01 PM

After:

Screenshot 2024-02-23 at 7 22 24 PM

Cameo: RSC stacks.

### CODE REVIEW

**Review by rickhanlonii — APPROVED** [review]

**Review by gnoff — APPROVED** [review]
I know it’s pedantic but these invalid nestings can only cause hydration issues if you SSR+hydrate. React can actually render these invalid nestings just fine for new trees because there is no parsing involved.

the original message is “react doesn’t support invalid HTML nesting” and the new message is focused more on hydration itself which might make it seem more like this is a hydration problem than just incorrect HTML.

Maybe we the hydration specific warning message during hudration and a non hydration specific message when not hydrating?

**Comment by sebmarkbage** [comment]
The issue is that you can get the message while client navigating or loading something, in development, which may then cause a hydration error in production or in another scenario. So it's easier to just keep it short.

**Comment by sophiebits** [comment]
Nice improvement.

**Comment by AhmedMuhammedElsaid** [comment]
Nice One, Thanks

**Review by AhmedMuhammedElsaid — COMMENTED** [review]
Really Nice One ,

**Pull request merged**
