### PR TITLE
Add more context to DOM nesting warning

### PR DESCRIPTION
**Pull request by spicyj**
Better version of #3578.

### CODE REVIEW

**Comment by spicyj** [comment]
Looking at ReactDOMComponent-test is probably a good place to start.

**Comment by spicyj** [comment]
@zpao You reviewed #3516 – want to take a look at this one? This follows @sebmarkbage's advice in https://github.com/facebook/react/pull/3578#issuecomment-91353722.

**Comment by spicyj** [comment]
@zpao

**Comment by sebmarkbage** [comment]
shipit

**Pull request merged**
