### PR TITLE
Fill in necessary webpack cli commands

### PR DESCRIPTION
**Pull request by timwis**
These are necessary for webpack to build react properly

### CODE REVIEW

**Comment by timwis** [comment]
Signed :+1:

**Comment by timwis** [comment]
@gaearon I've added the `preset` setting to the command

**Comment by gaearon** [comment]
Thanks! These files are being reshuffled in #6148 so I’ll leave it to @jimfb to pick up these changes manually.

**Comment by jimfb** [comment]
Ok, pulled this into #6148

**Pull request closed without merging**
