### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by li-jia-nan**
## Summary

fix typo

## How did you test this change?

Only fix typo, no need test case.

### CODE REVIEW

**Comment by li-jia-nan** [comment]
@kassens @gaearon @sebmarkbage @acdlite pls review, thx :)

**Review by AnLuoRidge — COMMENTED** [review]
You're creating a typo. "built" is correct here as the past participle of "build".

**Comment by li-jia-nan** [comment]
> You're creating a typo. "built" is correct here as the past participle of "build".

That's it, thank you for reminding me, my English is not very good.

**Comment by AnLuoRidge** [comment]
Could you close the PR then? To save time for the team.

**Pull request closed without merging**
