### PR TITLE
Added tests for getEventTarget

### PR DESCRIPTION
**Pull request by timjacobi**
`getEventTarget` seemed not to have been tested yet. This PR adds some tests for it.

### CODE REVIEW

**Comment by gaearon** [comment]
This is a unit test, which we're trying to avoid. It won't help us if we rewrite the implementation and stop using this helper. Instead we want to have integration tests using public API only.

**Comment by timjacobi** [comment]
Makes sense. Are we thinking about a strategy on how we integration test cross browser inconsistencies? For example having `event.srcElement` set instead of `event.target` is quite hard to fake in integration tests. I'm still thinking about whether it is even a good idea to have the test "know" about this inconsistency or if we should run the test in an actual browser.

**Comment by gaearon** [comment]
The tests I previously pointed to (https://github.com/facebook/react/pull/11365) already do this 🙂 please check them out.

**Comment by timjacobi** [comment]
Alright. I'm gonna close this. Will keep an eye on the migration to public API test. ;)

**Pull request closed without merging**
