### PR TITLE
#22988 - Fix Bug: @license header in React 18 bundles contains vundefined

### PR DESCRIPTION
**Pull request by vitaliemiron**
Fix the version issue - https://github.com/facebook/react/issues/22988

### CODE REVIEW

**Comment by salazarm** [comment]
try
`reactVersion = require('../../packages/shared/ReactVersion')`

**Comment by vitaliemiron** [comment]
> try `reactVersion = require('../../packages/shared/ReactVersion')`

doesn't work for me, do you have any idea why ?
Screenshot 2021-12-21 at 18 22 03

**Review by bvaughn — APPROVED** [review]
~~Thanks!~~

Actually, I need to think on this one further.

This change will fix the `undefined` issue but the version number shown in the header comment will lag behind the version we are building to publish.

**Review by bvaughn — CHANGES_REQUESTED** [review]
Removing approval for now to avoid confusion.

**Comment by vitaliemiron** [comment]
If I can help with something else LMK please

**Comment by bvaughn** [comment]
There's an interesting mix of concerns here between the Rollup scripts that are building the JS bundles we're about to publish and the bespoke [release scripts](https://github.com/facebook/react/tree/main/scripts/release) we use that inject the right version number _after_ building and _before_ publishing.

Honestly maybe the best fix here for now is just to remove the version from the header comment. 😄 

```diff
diff --git a/scripts/rollup/wrappers.js b/scripts/rollup/wrappers.js
index 46b162cee..3521f9b70 100644
--- a/scripts/rollup/wrappers.js
+++ b/scripts/rollup/wrappers.js
@@ -3,7 +3,6 @@
 const {resolve} = require('path');
 const {readFileSync} = require('fs');
 const {bundleTypes, moduleTypes} = require('./bundles');
-const reactVersion = require('../../packages/react-dom/package.json').version;
 
 const {
   NODE_ES2015,
@@ -54,7 +53,7 @@ const license = ` * Copyright (c) Facebook, Inc. and its affiliates.
 const wrappers = {
   /***************** NODE_ES2015 *****************/
   [NODE_ES2015](source, globalName, filename, moduleType) {
-    return `/** @license React v${reactVersion}
+    return `/** @license React
  * ${filename}
  *
 ${license}
@@ -67,7 +66,7 @@ ${source}`;
 
   /***************** NODE_ESM *****************/
   [NODE_ESM](source, globalName, filename, moduleType) {
-    return `/** @license React v${reactVersion}
+    return `/** @license React
  * ${filename}
  *
 ${license}
@@ -78,7 +77,7 @@ ${source}`;
 
   /***************** UMD_DEV *****************/
   [UMD_DEV](source, globalName, filename, moduleType) {
-    return `/** @license React v${reactVersion}
+    return `/** @license React
  * ${filename}
  *
 ${license}
@@ -88,7 +87,7 @@ ${source}`;
 
   /***************** UMD_PROD *****************/
   [UMD_PROD](source, globalName, filename, moduleType) {
-    return `/** @license React v${reactVersion}
+    return `/** @license React
  * ${filename}
  *
 ${license}
@@ -98,7 +97,7 @@ ${license}
 
   /***************** UMD_PROFILING *****************/
   [UMD_PROFILING](source, globalName, filename, moduleType) {
-    return `/** @license React v${reactVersion}
+    return `/** @license React
  * ${filename}
  *
 ${license}
@@ -108,7 +107,7 @@ ${license}
 
   /***************** NODE_DEV *****************/
   [NODE_DEV](source, globalName, filename, moduleType) {
-    return `/** @license React v${reactVersion}
+    return `/** @license React
  * ${filename}
  *
 ${license}
@@ -125,7 +124,7 @@ ${source}
 
   /***************** NODE_PROD *****************/
   [NODE_PROD](source, globalName, filename, moduleType) {
-    return `/** @license React v${reactVersion}
+    return `/** @license React
  * ${filename}
  *
 ${license}
@@ -135,7 +134,7 @@ ${source}`;
 
   /***************** NODE_PROFILING *****************/
   [NODE_PROFILING](source, globalName, filename, moduleType) {
-    return `/** @license React v${reactVersion}
+    return `/** @license React
  * ${filename}
  *
 ${license}
@@ -294,7 +293,7 @@ ${source}`;
 const reconcilerWrappers = {
   /***************** NODE_DEV (reconciler only) *****************/
   [NODE_DEV](source, globalName, filename, moduleType) {
-    return `/** @license React v${reactVersion}
+    return `/** @license React
  * ${filename}
  *
 ${license}
@@ -313,7 +312,7 @@ ${source}
 
   /***************** NODE_PROD (reconciler only) *****************/
   [NODE_PROD](source, globalName, filename, moduleType) {
-    return `/** @license React v${reactVersion}
+    return `/** @license React
  * ${filename}
  *
 ${license}
@@ -327,7 +326,7 @@ ${source}
 
   /***************** NODE_PROFILING (reconciler only) *****************/
   [NODE_PROFILING](source, globalName, filename, moduleType) {
-    return `/** @license React v${reactVersion}
+    return `/** @license React
  * ${filename}
  *
 ${license}
```

**Comment by vitaliemiron** [comment]
haha, ok, will you push in this branch the changes or I'll ?)

**Review by bvaughn — APPROVED** [review]
Thanks!

**Pull request merged**
