### PR TITLE
[v16] Remove React.__spread

### PR DESCRIPTION
**Pull request by koba04**
This PR is for removing `React.__spread`, which is listed in #8854.

### CODE REVIEW

**Comment by acdlite** [comment]
Would you mind rebasing this PR with latest from master? There was an upstream lint error than has since been fixed.

**Comment by koba04** [comment]
@acdlite Thanks! Rebased it!

**Comment by acdlite** [comment]
Thanks!

**Comment by koba04** [comment]
Thanks!

**Pull request merged**
