### PR TITLE
Guard against a null node

### LINKED ISSUE #2619: CSSTransitionGroup throws when a child returns null from render
I came across this, when using `react-router`. When loading a route initially where the route handler is actually inside a `ReactCSSTransitionGroup` and then removing it from the transition group leads to an `Uncaught TypeError: Cannot read property 'addEventListener' of null `. The weird thing is that it only happens on initial load of a nested route, not when the same view is being pulled up via the menu. I'm not sure if this is an issue related `react-router` or if it belongs to `react`. But the thing is that the `RouteHandler` component either returns a react element, or it returns `null`. It seems like an edge case maybe, because it only happens in this specific initial render setup.

It could be fixed, by adding a guard to the `transition()` method of  `ReactCSSTransitionGroupChild`:
```
if (!node) {
  finishCallback && finishCallback();
  return;
}
```

### PR DESCRIPTION
**Pull request by johanneslumpe**
This could fix #2619

### CODE REVIEW

**Comment by spicyj** [comment]
It's not super obvious what should happen with events if a component switches away from null during the would-be transition time or if it switches to null while transitioning, but I guess this is an improvement either way.

Can you squash your commits together?

**Comment by johanneslumpe** [comment]
@spicyj embarrassing, but I don't know how to squash. Maybe you can provide me with a small snippet so I know it once and for all? :)

**Comment by spicyj** [comment]
No worries. On your `patch-1` branch, you'll want to run an interactive rebase by doing

```
git rebase -i master
```

meaning you want to edit the changes you've made since the top of the `master` branch. You'll get a text editor, hopefully with two lines corresponding to your two commits. If you change the second "pick" to a "f" or "fixup" then save the file, git will amend the second commit to the first (and throw away its message). You'll then want to do a `git push -f` to overwrite the branch you currently have on GitHub with the new, altered commit.

**Comment by johanneslumpe** [comment]
@spicyj I think that worked :)

**Comment by spicyj** [comment]
Thanks @johanneslumpe!

**Pull request merged**
