### PR TITLE
Add a note about deprecating react-addons-perf

### PR DESCRIPTION
**Pull request by koba04**
`react-addons-perf` is no longer in React v16. This documentation is not linked from anywhere but we can get the page from Google search like the word "react performance".

Should I keep the documentation and add a deprecated warning?

### CODE REVIEW

**Comment by gaearon** [comment]
We should figure something out here.
cc @acdlite 

I think all addon pages should stay available for React 15 and earlier users, but the should have a prominent heading saying what the users or each addon should do in 16.

**Comment by koba04** [comment]
Something like this?

Note: `react-addons-perf` is no longer supported in v16. Please use Chrome Performance Tab instead: [Learn more about it](https://facebook.github.io/react/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab).

**Comment by koba04** [comment]
I've updated this to add a note about deprecating `react-addons-perf`

**Comment by koba04** [comment]
Thanks 🙏

**Pull request merged**
