### PR TITLE
Clarify use of arrow functions

### PR DESCRIPTION
**Pull request by spicyj**
Per https://github.com/facebook/react/commit/1db20999f0336cfacc6af5ee6f5a77803d74381b#commitcomment-12865588.

### CODE REVIEW

**Comment by zpao** [comment]
Do you think this might imply that you have to use an ES6 arrow function?

**Comment by syranide** [comment]
Although not-really-related, should we perhaps mention #4651 as well?

**Comment by spicyj** [comment]
@zpao Maybe it does, but honestly this syntax is incredibly cumbersome if you don't use an arrow function that I don't think anyone will want to.

@syranide Already did – see line 119.

**Comment by zpao** [comment]
Yea, if you use inline functions. The other way I could see people doing this with a prebound function, eg`<TextInput ref={this._setInput}>` (which is honestly what I would probably write, I tend to not like creating functions in `render()`). The important part of this is that it's bound. But yea, this is fine. I'll point anybody who is confused to you :P

**Pull request merged**
