### PR TITLE
Update rendering-elements.md

### PR DESCRIPTION
**Pull request by murtazahaveliwala**
Updating text to be in sync with sample html

### CODE REVIEW

**Comment by bvaughn** [comment]
Thanks 😄

**Comment by gaearon** [comment]
@bvaughn Please "Squash and Merge" documentation PRs. The tool doesn't understand merge commits :-(. cc @zpao

**Comment by bvaughn** [comment]
Guh! Sorry @gaearon. I thought that only applied to multi-commit PRs.

**Comment by gaearon** [comment]
You can also fix the tool to understand them. AFAIK it would just need to pass `-m 1`.

**Pull request merged**
