### PR TITLE
[Flight] Implement `react-server-dom-turbopack`

### PR DESCRIPTION
**Pull request by gnoff**
stacked on #27314 

Turbopack requires a different module loading strategy than Webpack and as such this PR implements a new package `react-server-dom-turbopack` which largely follows the `react-server-dom-webpack` but is implemented for this new bundler

### CODE REVIEW

**Review by sebmarkbage — APPROVED** [review]

**Comment by daukantas** [comment]
Your github input has been violating my email !

Attention:  Please  make adjusted  changes to prevent your input entering this email site.


Warning! Please review “Scams and Identity Theft Attempts Targeting International Affiliates”, which can be found at https://www.hupd.harvard.edu/scams-targeting-international-affiliates
Scams and Identity Theft Attempts Targeting International Affiliates<https://www.hupd.harvard.edu/scams-targeting-international-affiliates>
Introduction
www.hupd.harvard.edu<http://www.hupd.harvard.edu/>
.

________________________________

**Comment by lazarv** [comment]
@gnoff @sebmarkbage instead of creating specific versions of `react-server-dom-*` for Webpack, esm or turbopack, why don't you let the consumer of the package provide the module loading functionality? It could be easily passed as an option during rendering. Now the Webpack and turbopack versions are calling the global `__webpack_require__` or `__turbopack_require__` functions and you also duplicating code for each specific version.

**Comment by gnoff** [comment]
For performance. Each binding package can implement a strategy that is optimized for the bundler in a way that can’t be don’t with a general load function. For instance the wire format of chunks is not the same between webpack and turbopack but if we used a single package we would need to encode all the required data to satisfy any and all bundles from a single package. The implementations of turbopack and webpack look substantially similar because turbopack made some changes recently that happen to make it work more like webpack but a few months ago this package would have looked quite a bit different.

**Comment by lazarv** [comment]
Thanks for the reasoning @gnoff! If all of this functionality will be ever supported other than Next.js, then I suppose there will be a generic version of `react-server-dom` (maybe the esm version, when that will be ever properly published to npm) which could be used by anyone else. For my experimental Vite-based meta-framework at https://github.com/lazarv/react-server I just used the webpack version and I provided the `__webpack_require__` as a global variable. But this `__*_require__` function is already very versatile, only issue is that it's not available to pass it as an option to the renderer, only as an exactly named global variable. What I do is very hackish because of React right now is only supporting these exact bundlers.

**Comment by gnoff** [comment]
There is a PR open for a vite package that we are looking to help land soon. That should probably work better for you when it is available

**Pull request merged**
