### PR TITLE
Fix transitionName prop-type on CSS transition group child

### PR DESCRIPTION
**Pull request by djrodgerspryor**
I put the wrong prop-type in ReactCSSTransitionGroupChild (as pointed out by @Daniel15); this PR replaces it with the correct one.

### CODE REVIEW

**Comment by spicyj** [comment]
Thanks! Can you add a unit test that uses transitionName like this?

**Comment by Daniel15** [comment]
Thanks! Rather than having the propType copied and pasted in two different places, you might be able to reuse the propType in `ReactCSSTransitionGroup` by doing something like 

```js
propTypes: {
  transitionName: ReactCSSTransitionGroupChild.propTypes.name
```

**Comment by zpao** [comment]
Thanks for the quick PR. Let's do what @Daniel15 said (in addition to the test and fixing the other one) - will help make sure we don't diverge :)

**Comment by djrodgerspryor** [comment]
@spicyj and @zpao All done. Sorry about the long delay.

**Comment by spicyj** [comment]
Thank you!

**Pull request merged**
