### PR TITLE
Fix an edge case in `ReactFiberUpdateQueue`

### PR DESCRIPTION
**Pull request by jddxf**
Correct me if I misunderstood something.

### CODE REVIEW

**Comment by acdlite** [comment]
Good catch! Hmm, typically we'd want to make sure we have a unit test to prevent a regression, but with edge cases like this that are so implementation specific it may not be worth it. Do you mind giving it a shot?

**Comment by acdlite** [comment]
Actually don't sweat it. The path you'd have to take to trigger this edge case is pretty complex. I'll give it a shot before I land.

**Comment by jddxf** [comment]
That's fine.Thanks!

**Comment by gaearon** [comment]
That’s pretty cool, thank you for finding it. Did you just walk into it reading the source?

**Comment by jddxf** [comment]
@gaearon Yes.I am trying to understand the fiber :)

**Comment by gaearon** [comment]
So are we. 😄

**Comment by jddxf** [comment]
lol.

**Comment by gaearon** [comment]
@acdlite Is this still relevant?

**Comment by gaearon** [comment]
I'm going to close since this is outdated. If the bug still exists please re-submit with instructions to reproduce the problem. Thanks!

**Pull request closed without merging**
