### PR TITLE
polish some vendor sources

### PR DESCRIPTION
**Pull request by chicoxyzzy**
single quote 'use strict' + some jsdoc additions

### CODE REVIEW

**Comment by zpao** [comment]
Quick note, these are mostly just synced one way (out to GH) so this might be more annoying than it's worth (except for the 1 change to code). So if I stall here and we never merge it, that's why :/

**Comment by chicoxyzzy** [comment]
ok. there is also some jsDoc improvements in `src/vendor/key-mirror/keyOf.js` if you will edit these files out there.

**Comment by chicoxyzzy** [comment]
BTW why do we need tests in `vendor/*`? If they are something we can't affect (from react repo) we can think of them like of third-party libraries (sort of node_modules). If so, should we test these libraries from react repo? Or they should be tested out there?

**Comment by zpao** [comment]
I think we're going to end up leaving vendor alone for now. Thanks for the initiative though!

**Pull request closed without merging**
