### PR TITLE
Add test fixtures to cover disabled selected options

### PR DESCRIPTION
**Pull request by nhunzaker**
Related issues: #2803

We don't have amazing test fixture coverage for selects, so I've added two cases based on the discussion in #2803:

1. A selected, disabled, option should be picked, but not selectable
2. When there is no value match, the default selected option should be the first non-disabled option

Pretty standard stuff. A lot of this is just basic browser behavior, but I believe these test cases *already* caught a bug in the current edge build of React: 

**Selects no longer "skip" over disabled options when selecting the default option.** [(Example of standard DOM behavior)](https://codepen.io/nhunzaker/pen/GEwVYv)

Also, I've added a new field to link related issues in the test cases. Take a look at the result here:

http://react-select-default-option-fixtures.surge.sh/selects

### CODE REVIEW

**Comment by nhunzaker** [comment]
@aweary Would it be possible to check this out on your local React to make sure I'm not crazy? It looks like the behavior for selects has changed between 16.0.0-alpha3 and the local build.

## 16.0.0-alpha3

The default value is "0" for the last test case:

screen shot 2017-07-11 at 8 22 04 am

## Local Build

The default value is "Please select an option":

screen shot 2017-07-11 at 8 22 41 am

**Comment by aweary** [comment]
@nhunzaker I'm seeing the same thing here, with the latest master build. This does indeed look like a regression. I'll take a look at it.

**Comment by aweary** [comment]
This issue stems from https://github.com/facebook/react/pull/8349 which introduced an `updateOptions` call when a `select` element is mounted.  If`updateOptions` doesn't find a matching `option` it [defaults to setting the first `option` as selected](https://github.com/facebook/react/blob/ca46c5278fe24dd9f564918d30e454033278e054/src/renderers/dom/fiber/wrappers/ReactDOMFiberSelect.js#L110-L112).

In previous versions `updateOptions` was not called on the initial mount, so it defaulted to the standard behavior of the browser.

**Comment by gaearon** [comment]
cc @sebmarkbage regarding above explanation

**Comment by gaearon** [comment]
Seems like https://github.com/facebook/react/pull/10456 superseded this.

**Pull request closed without merging**
