### PR TITLE
[DevTools][State Tooltip] Added a stack of of component owners

### LINKED ISSUE #24170: [React DevTools] Component Stacks for Timeline Profiler
In the Timeline Profiler, we currently denote each state update with a dot. If you hover on the state update, you get some information about it, such as which component caused the update, the lane the update was rendered at, and the time that the update happened. This is useful for unique components. However, for components (ex. library components) that are used in multiple places, just having the component name is less helpful. 

It would be most useful to get a stack of component owners (like in the rendered by section in the Components tab). However, we only have owner metadata in DEV mode, and it usually only makes sense to profile in production. The next best thing we can do, then, is to get all the parent components and create a stack out of that (ie the return path of the fiber rather than the owner path). 

image

We want to add component stacks so that we also know which parent(s) caused the update. For this task, a potential solution is:
* [ ] When a state update happens, walk the fiber's return path and save all the component names and their source. (See `markStateUpdateScheduled` for code pointers on where to put this)
* [ ] After we're done profiling, process the stack so that we create a stack of return fibers
* [ ] Pass the stack to the DevTools front end and add the component stacks to the UI when a user hovers over a state update

### PR DESCRIPTION
**Pull request by blakef**
## Summary

https://user-images.githubusercontent.com/49578/174205388-89f4f8b5-f04b-44e9-abfa-7cc950554f10.mp4

Added a side panel that:
- list all parent components in the hierarchy of the Fiber initiating the state change
- clickable link to inspect components in the hierarchy
- list scrolls, ellipses for long component names

We can filter out built in components.  Maybe as a follow up someone could add a checkbox that toggles this?

resolves #24170

## How did you test this change?

Ran the change in the inline-devtools in the devtools-shell + as an extension in Chrome.

### CODE REVIEW

**Comment by lunaruan** [comment]
Hey! This is a great first draft of the PR. 😍 It's great to see that you have an end to end implementation of this working!

A few comments/questions:
1. I love the UI that you've created for the component stack! It conveys information in a clear and concise way. One thing I wonder if you've considered how the visualization of the component stack might be like in larger apps. For example, if you have a reusable button with many layers of parent components, it would be really hard, with only 5 elements in the component stack, to actually be able to identify where the button is used. What do you think about giving developers the ability to get all the elements in the stack instead of just the first 5? We don't have to visualize all of them (5 is probably a good number to start), but perhaps we can create some sort of UI to let the user get the rest of the components (perhaps a copy component stack button or a show more button?)
2. Using the displayName is great in `__DEV__` mode where the name (or user specified `displayName`) of the function is not minified. However, most people want to profile production apps (since dev apps tend to be a lot slower than production ones). In this case, often function names have been minified into a coupe of letters, which makes it really difficult for developers to debug. What do you think about adding the location of the function as well to make the function easier to find? There are a couple of strategies for this (checkout the function `describeNativeComponentFrame`). Feel free to ping me with questions!

**Comment by blakef** [comment]
I love these ideas. Let me come back to you with something.

**Comment by blakef** [comment]
@lunaruan updated the video to show how it looks.  There's plenty of room for small tweaks with the styling, and some of the UX (enabling / disabling built in components).

**Comment by gaearon** [comment]
Should the stack be in the reverse order? So that you see the component itself at the top.

**Comment by lunaruan** [comment]
Yayy! Glad you got the source working! 😊

One concern I have with this implementation is that you can only view the source when the fiber ID maps are accurate. These maps are only populated on render, which means that this implementation will only work if your'e profiling the active window and the fibers haven't been deleted from the map. Fibers are deleted from the map when they are removed from the fiber tree, and this is not an uncommon occurrence.

We also support uploading traces to React DevTools if you want Chrome performance data on top of your React Timeline data. We are working with Chrome on a better integrate method, but until then, you can only get screenshots, Chrome flamegraph chats, performance marks, etc. if you profile first in chrome and then upload to the React Profiler. This implementation will also not work in this case, because the IDs will be associated with the wrong fiber (or not present at all)

Going back up to my previous comment, I think jumping to source is a great idea if the source is available and it's possible to implement, but if it isn't, what do you think about storing the location instead of the parent ID and allowing for some sort of "go to editor" method instead?

**Comment by blakef** [comment]
@lunaruan  yea, sorry you did make this point earlier.  I've still got that code lying around in the reflog.

**Comment by blakef** [comment]
Closing this in favour of #24805

**Pull request closed without merging**
