### PR TITLE
add React Day Berlin

### PR DESCRIPTION
**Pull request by operatino**
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run prettier`).
6. Make sure your code lints (`npm run lint`).
7. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
8. If you haven't already, complete the CLA.

### CODE REVIEW

**Comment by operatino** [comment]
Anyone? No breaking change, I promise :)

**Comment by operatino** [comment]
Resolved conflicts

**Comment by operatino** [comment]
I see other PR's with conference additions are getting merged before this one (#10614), looks discriminating. Can anybody have a look at this as well?

**Comment by operatino** [comment]
cc @nhunzaker

**Comment by nhunzaker** [comment]
Looks good. Sorry for the delay. Working through the queue as fast as I can :)

**Comment by operatino** [comment]
Thanks a lot, @nhunzaker!

**Pull request merged**
