### PR TITLE
Refactor ShallowRenderer

### PR DESCRIPTION
**Pull request by koba04**
I've refactored ReactShallowRenderer for readability, which is not changing the behavior.
If this was merged, I'll add type annotations with Flow.

### CODE REVIEW

**Comment by gaearon** [comment]
This fails Flow: https://travis-ci.org/facebook/react/jobs/160155787

**Comment by koba04** [comment]
@gaearon 
Thank you for your review!
Failing Travis is because of #7736. This PR seems to be not relevant.

**Comment by gaearon** [comment]
OK, let’s wait for that to land and then try this again. Thanks!

**Comment by Aweary** [comment]
@gaearon @koba04 I've merged https://github.com/facebook/react/pull/7736, so those flow errors should be resolved now 👍

**Comment by koba04** [comment]
@gaearon @Aweary Thanks! rebased.

**Comment by koba04** [comment]
@Aweary Thank you!
@gaearon Flow has been fixed.

**Comment by gaearon** [comment]
Thanks!

**Comment by koba04** [comment]
Thanks!

**Pull request merged**
