### PR TITLE
Changed webpack's hyperlink

### PR DESCRIPTION
**Pull request by gitanupam**
..to point to 2.x documentation instead of 1.x (and to be consistent with other links on the page)

*Before* submitting a pull request, please make sure the following is done...

1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`) - we've done our best to make sure these rules match our internal linting guidelines.
6. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

### CODE REVIEW

**Comment by gaearon** [comment]
It's not stable yet, and Webpack repo points to 1.x docs. Why make the change?

**Comment by aweary** [comment]
@gaearon you linked to [webpack.js.org](http://webpack.js.org) twice in https://github.com/facebook/react/commit/db140c887f389995b8be2ddbfb33601b49708c12 when you added the links, I assumed that was intentional? I can change them all to the `1.x` docs if it wasn't.

**Comment by aweary** [comment]
ping @gaearon, did you want me to change all the links to point to `1.x` docs instead?

**Comment by gaearon** [comment]
Looks like I linked inconsistently, even db140c8 includes both style of links. I'd say let's change them all to point to 1.x, wanna do it?

**Comment by aweary** [comment]
You bet I do!

**Pull request merged**
