### PR TITLE
The Web Optimization Project has optimized your repository!

### PR DESCRIPTION
**Pull request by devedse**
# Web Optimization Project (Beta)

The [Web Optimization Project](https://www.github.com/devedse/weboptimizationproject) is a project that will automatically optimizes files in git repositories by compressing them losslessly. This project was created by [Devedse](https://github.com/devedse) in an effort to save the world! :smirk:

If you have any questions, feel free to create an issue or join the gitter chat:
[Join the chat at https://gitter.im/WebOptimizationProject/Lobby](https://gitter.im/WebOptimizationProject/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

## Optimization

The Web Optimization Project optimized this repository. All optimizations (compressions) are done losslessly and no quality / data is lost. This is also verified afterwards by the Wop so you can be sure that your images are exactly the same.

### Commit 1

Information | Value
-- | --
Version | 0.0.4.0
Support file extension | .PNG .JPG .JPEG .GIF .BMP

#### Statistics

Stats | Value
-- | --
Total size before optimization | 21MB
Total size after optimization | 19.2MB
Optimized size compared to old | 91.23%
Total bytes saved | 1.8MB
Time taken for optimization | 25.4 Hours

#### Files optimized in this repository

FileName | Original Size | Optimized Size | Bytes Saved | Duration | Successful
-- | -- | -- | -- | -- | --
external.png | 189B | 189B | 0B | 9 Seconds | True
external_2x.png | 134B | 134B | 0B | 7 Seconds | True
logo_og.png | 10.5KB | 10.5KB | 0B | 1.2 Minutes | True
logo_small.png | 4.3KB | 4.3KB | 0B | 8 Seconds | True
logo_small_2x.png | 12.5KB | 12.5KB | 0B | 11 Seconds | True
logo_small_gray.png | 1.8KB | 1.8KB | 0B | 7 Seconds | True
logo_small_gray_2x.png | 4.2KB | 4.2KB | 0B | 8 Seconds | True
noise.png | 22.1KB | 22.1KB | 0B | 9 Seconds | True
oss_logo.png | 3.9KB | 3.9KB | 0B | 11 Seconds | True
search.png | 244B | 244B | 0B | 7 Seconds | True
animal-sounds.jpg | 48.1KB | 48.1KB | 0B | 2 Seconds | True
chatapp.png | 21.6KB | 21.6KB | 0B | 43 Seconds | True
cra-better-output.png | 146.4KB | 146.4KB | 0B | 1.4 Minutes | True
cra-dynamic-import.gif | 1.7MB | 1.7MB | 0B | 35 Seconds | False
cra-jest-search.gif | 906.9KB | 906.9KB | 0B | 9 Seconds | False
cra-pwa.png | 45.4KB | 45.4KB | 0B | 2.4 Minutes | True
cra-runtime-error.gif | 1.7MB | 1.7MB | 0B | 31 Seconds | False
cra-update-exports.gif | 1.4MB | 1.4MB | 0B | 29 Seconds | False
devtools-full.gif | 1.3MB | 479KB | 899.9KB | 24 Seconds | True
devtools-search.gif | 929.2KB | 929.2KB | 0B | 50 Seconds | True
devtools-side-pane.gif | 42.6KB | 42.6KB | 0B | 2 Seconds | False
devtools-tree-view.png | 71.2KB | 71.2KB | 0B | 9.7 Hours | True
dog-tutorial.png | 40.5KB | 40.5KB | 0B | 2.4 Minutes | True
error-boundaries-sta...png | 35.8KB | 35.8KB | 0B | 13.6 Hours | True
error-boundaries-sta...png | 34.9KB | 34.9KB | 0B | 2 Minutes | True
first-look.png | 27.6KB | 27.6KB | 0B | 34 Seconds | True
flux-chart.png | 41.6KB | 41.6KB | 0B | 1.8 Minutes | True
flux-diagram.png | 130.1KB | 130.1KB | 0B | 6.8 Minutes | True
genesis_skeleton.png | 142.6KB | 142.6KB | 0B | 28 Seconds | True
gpu-cursor-move.gif | 789.6KB | 308.2KB | 481.4KB | 3 Seconds | True
guess_filter.jpg | 37.7KB | 37.7KB | 0B | 2 Seconds | True
hacker-news-react-na...png | 102.8KB | 102.8KB | 0B | 56 Seconds | True
jsx-compiler.png | 13.7KB | 13.7KB | 0B | 1.5 Minutes | True
kendoui.png | 22KB | 22KB | 0B | 36 Seconds | True
khan-academy-editor.png | 10.8KB | 10.8KB | 0B | 1 Second | False
landoflisp.png | 108.7KB | 108.7KB | 0B | 30 Seconds | True
lights-out.png | 3.3KB | 3.3KB | 0B | 29 Seconds | True
makona-editor.png | 23.5KB | 23.5KB | 0B | 47 Seconds | True
markdown_refactor.png | 5.3KB | 5.3KB | 0B | 39 Seconds | True
modus-create.gif | 992.3KB | 965.6KB | 26.7KB | 8 Seconds | True
monkeys.gif | 532KB | 177.6KB | 354.4KB | 4 Seconds | True
ngreact.png | 54.4KB | 54.4KB | 0B | 2 Minutes | True
om-backbone.png | 126.5KB | 126.5KB | 0B | 1.2 Minutes | True
parse-react.jpg | 47.9KB | 47.9KB | 0B | 1 Second | True
polarr.jpg | 66KB | 66KB | 0B | 1 Second | True
propeller-logo.png | 1.3KB | 1.3KB | 0B | 11 Seconds | True
property-finder.png | 60.9KB | 60.9KB | 0B | 51 Seconds | True
quiztime.png | 18.7KB | 18.7KB | 0B | 1.4 Minutes | True
react-50k-mock-full.jpg | 126.8KB | 126.8KB | 0B | 3 Seconds | True
react-50k-mock.jpg | 83KB | 83KB | 0B | 2 Seconds | True
react-50k-tshirt.jpg | 633.4KB | 633.4KB | 0B | 3 Seconds | True
react-browserify-gul...jpg | 23.1KB | 23.1KB | 0B | 1 Second | True
react-dev-tools.jpg | 69.7KB | 69.7KB | 0B | 1 Second | True
react-diff-tree.png | 26.8KB | 26.8KB | 0B | 52 Seconds | True
react-draggable.png | 10.2KB | 10.2KB | 0B | 1.1 Minutes | True
react-hackathon.jpg | 48.8KB | 48.8KB | 0B | 2 Seconds | True
react-page.png | 19.9KB | 19.9KB | 0B | 28 Seconds | True
react-perf-chrome-ti...png | 68.4KB | 68.4KB | 0B | 1.3 Minutes | True
react-php.png | 35.7KB | 35.7KB | 0B | 53 Seconds | True
react-svg-fbp.png | 57.2KB | 57.2KB | 0B | 1.2 Minutes | True
reactive-bookmarklet.png | 40.8KB | 40.8KB | 0B | 1.5 Minutes | True
reflux-flux.png | 2KB | 2KB | 0B | 21 Seconds | True
relay-visual-archite...png | 129KB | 129KB | 0B | 9 Minutes | True
resistance-calculato...png | 44.2KB | 44.1KB | 47B | 1.3 Minutes | True
skills-matter.png | 120.3KB | 120.3KB | 0B | 1.7 Minutes | True
snake.png | 6.8KB | 6.8KB | 0B | 1 Minute | False
steve_reverse.gif | 5.4MB | 5.4MB | 0B | 1.6 Minutes | True
sweet-jsx.png | 18.4KB | 18.4KB | 0B | 1.2 Minutes | True
tcomb-react-native.png | 24.3KB | 24.3KB | 0B | 1.8 Minutes | True
thinking-in-react-co...png | 18.6KB | 18.6KB | 0B | 37 Seconds | True
thinking-in-react-mo...png | 17KB | 17KB | 6B | 30 Seconds | True
todomvc.png | 21.8KB | 21.8KB | 0B | 1.8 Minutes | True
turboreact.png | 3.4KB | 3.4KB | 3B | 23 Seconds | True
tutsplus.png | 28.8KB | 28.8KB | 0B | 1.2 Minutes | True
unite.png | 13.3KB | 13.3KB | 0B | 27 Seconds | True
versioning-1.png | 22.2KB | 8KB | 14.3KB | 41 Seconds | True
versioning-2.png | 23.1KB | 9.1KB | 14KB | 1.2 Minutes | True
versioning-3.png | 44.1KB | 28.8KB | 15.3KB | 1.4 Minutes | True
versioning-4.png | 47.9KB | 31.8KB | 16.1KB | 2.4 Minutes | True
versioning-5.png | 31.5KB | 12.7KB | 18.8KB | 1.4 Minutes | True
versioning-6.png | 44.8KB | 27.7KB | 17.1KB | 1.9 Minutes | True
versioning-poll.png | 48.2KB | 48.2KB | 0B | 2.9 Minutes | True
weather.png | 6.8KB | 6.8KB | 0B | 17 Seconds | True
wolfenstein_react.png | 110.9KB | 110.8KB | 104B | 1.2 Minutes | True
xoxo2013.png | 168.3KB | 168.3KB | 0B | 1.4 Minutes | True
xreact.png | 3.2KB | 3.2KB | 0B | 26 Seconds | True
compiled-successfull...png | 50KB | 50KB | 0B | 2.7 Minutes | True
compiled-with-warnin...png | 135.1KB | 134.4KB | 761B | 3.6 Minutes | True
created-folder.png | 136KB | 136KB | 0B | 3.9 Minutes | True
failed-to-compile.png | 136.5KB | 135.7KB | 856B | 3.7 Minutes | True
npm-run-build.png | 122.1KB | 122.1KB | 0B | 3.5 Minutes | True
relay-architecture.png | 55.1KB | 55.1KB | 0B | 8.1 Minutes | True
relay-containers-dat...png | 27.3KB | 27.3KB | 0B | 4 Minutes | True
relay-containers.png | 13.9KB | 13.9KB | 0B | 2.5 Minutes | True
sample-newsfeed.png | 56.9KB | 56.9KB | 0B | 3.1 Minutes | True
cdn-cors-header.png | 42.5KB | 42.5KB | 0B | 2 Minutes | True
codewinds-004.png | 2.3KB | 2.3KB | 0B | 10 Seconds | True
devtools-dev.png | 51.6KB | 51.6KB | 0B | 53 Seconds | True
devtools-prod.png | 27.1KB | 27.1KB | 0B | 39 Seconds | True
granular-dom-updates.gif | 124.2KB | 122.9KB | 1.3KB | 21 Seconds | True
implementation-notes...png | 51KB | 51KB | 0B | 2 Minutes | True
javascript-jabber.png | 1.6KB | 1.6KB | 0B | 10 Seconds | True
keyboard-focus.png | 1.7KB | 1.7KB | 0B | 10 Seconds | True
perf-dom.png | 7.3KB | 7.3KB | 0B | 14 Seconds | True
perf-exclusive.png | 9.3KB | 9.3KB | 0B | 15 Seconds | True
perf-inclusive.png | 12.2KB | 12.2KB | 0B | 23 Seconds | True
perf-wasted.png | 16KB | 16KB | 0B | 22 Seconds | True
react-devtools-state.gif | 567.3KB | 567.3KB | 0B | 9 Seconds | False
should-component-upd...png | 23.9KB | 23.9KB | 0B | 1.2 Minutes | True
thinking-in-react-ta...png | 14.2KB | 10.7KB | 3.5KB | 22 Seconds | True
devtools.png | 23.4KB | 23.4KB | 0B | 1 Minute | True
tictac-empty.png | 10.9KB | 1.8KB | 9.1KB | 1.8 Minutes | True
tictac-numbers.png | 16.4KB | 4KB | 12.4KB | 28 Seconds | True
grayarrow.gif | 111B | 111B | 0B | 1 Second | True
logo.png | 218B | 218B | 0B | 7 Seconds | True

### Commit 2

Information | Value
-- | --
Version | 0.0.5.0
Support file extension | .PNG .JPG .JPEG .GIF .BMP

#### Statistics

Stats | Value
-- | --
Total size before optimization | 19.2MB
Total size after optimization | 19.1MB
Optimized size compared to old | 99.93%
Total bytes saved | 13.4KB
Time taken for optimization | 2.3 Hours

#### Files optimized in this repository

FileName | Original Size | Optimized Size | Bytes Saved | Duration | Successful
-- | -- | -- | -- | -- | --
external.png | 189B | 189B | 0B | 9 Seconds | True
external_2x.png | 134B | 134B | 0B | 7 Seconds | True
logo_og.png | 10.5KB | 10.5KB | 0B | 1.6 Minutes | False
logo_small.png | 4.3KB | 4.3KB | 0B | 15 Seconds | True
logo_small_2x.png | 12.5KB | 12.5KB | 0B | 21 Seconds | True
logo_small_gray.png | 1.8KB | 1.8KB | 0B | 9 Seconds | True
logo_small_gray_2x.png | 4.2KB | 4.2KB | 0B | 8 Seconds | True
noise.png | 22.1KB | 22.1KB | 0B | 16 Seconds | True
oss_logo.png | 3.9KB | 3.9KB | 0B | 48 Seconds | True
search.png | 244B | 244B | 0B | 12 Seconds | True
animal-sounds.jpg | 48.1KB | 48.1KB | 0B | 5 Seconds | True
chatapp.png | 21.6KB | 21.6KB | 0B | 1.3 Minutes | True
cra-better-output.png | 146.4KB | 146.4KB | 0B | 3.2 Minutes | True
cra-dynamic-import.gif | 1.7MB | 1.7MB | 0B | 1.9 Minutes | False
cra-jest-search.gif | 906.9KB | 906.9KB | 0B | 14 Seconds | False
cra-pwa.png | 45.4KB | 45.4KB | 0B | 3.2 Minutes | True
cra-runtime-error.gif | 1.7MB | 1.7MB | 0B | 51 Seconds | False
cra-update-exports.gif | 1.4MB | 1.4MB | 0B | 1.2 Minutes | False
devtools-full.gif | 479KB | 479KB | 0B | 36 Seconds | True
devtools-search.gif | 929.2KB | 929.2KB | 0B | 1.4 Minutes | True
devtools-side-pane.gif | 42.6KB | 29.3KB | 13.3KB | 6 Seconds | True
devtools-tree-view.png | 71.2KB | 71.2KB | 0B | 1.6 Minutes | True
dog-tutorial.png | 40.5KB | 40.5KB | 0B | 1.4 Minutes | True
error-boundaries-sta...png | 35.8KB | 35.8KB | 0B | 2.9 Minutes | True
error-boundaries-sta...png | 34.9KB | 34.9KB | 0B | 1.9 Minutes | True
first-look.png | 27.6KB | 27.6KB | 0B | 37 Seconds | True
flux-chart.png | 41.6KB | 41.6KB | 0B | 2.1 Minutes | True
flux-diagram.png | 130.1KB | 130.1KB | 0B | 7.4 Minutes | True
genesis_skeleton.png | 142.6KB | 142.6KB | 0B | 31 Seconds | True
gpu-cursor-move.gif | 308.2KB | 308.2KB | 0B | 4 Seconds | True
guess_filter.jpg | 37.7KB | 37.7KB | 0B | 3 Seconds | True
hacker-news-react-na...png | 102.8KB | 102.8KB | 0B | 1 Minute | True
jsx-compiler.png | 13.7KB | 13.7KB | 0B | 50 Seconds | True
kendoui.png | 22KB | 22KB | 0B | 1.5 Minutes | True
khan-academy-editor.png | 10.8KB | 10.8KB | 0B | 2 Seconds | False
landoflisp.png | 108.7KB | 108.7KB | 0B | 30 Seconds | True
lights-out.png | 3.3KB | 3.3KB | 0B | 32 Seconds | True
makona-editor.png | 23.5KB | 23.5KB | 0B | 50 Seconds | True
markdown_refactor.png | 5.3KB | 5.3KB | 0B | 44 Seconds | True
modus-create.gif | 965.6KB | 965.6KB | 21B | 22 Seconds | True
monkeys.gif | 177.6KB | 177.6KB | 8B | 8 Seconds | True
ngreact.png | 54.4KB | 54.4KB | 0B | 1.7 Minutes | True
om-backbone.png | 126.5KB | 126.5KB | 0B | 1 Minute | True
parse-react.jpg | 47.9KB | 47.9KB | 0B | 1 Second | True
polarr.jpg | 66KB | 66KB | 0B | 2 Seconds | True
propeller-logo.png | 1.3KB | 1.3KB | 0B | 11 Seconds | True
property-finder.png | 60.9KB | 60.9KB | 0B | 49 Seconds | True
quiztime.png | 18.7KB | 18.7KB | 0B | 1.9 Minutes | True
react-50k-mock-full.jpg | 126.8KB | 126.8KB | 0B | 3 Seconds | True
react-50k-mock.jpg | 83KB | 83KB | 0B | 2 Seconds | True
react-50k-tshirt.jpg | 633.4KB | 633.4KB | 0B | 4 Seconds | True
react-browserify-gul...jpg | 23.1KB | 23.1KB | 0B | 2 Seconds | True
react-dev-tools.jpg | 69.7KB | 69.7KB | 0B | 2 Seconds | True
react-diff-tree.png | 26.8KB | 26.8KB | 0B | 46 Seconds | True
react-draggable.png | 10.2KB | 10.2KB | 0B | 1.4 Minutes | True
react-hackathon.jpg | 48.8KB | 48.8KB | 0B | 2 Seconds | True
react-page.png | 19.9KB | 19.9KB | 0B | 30 Seconds | True
react-perf-chrome-ti...png | 68.4KB | 68.4KB | 0B | 2 Minutes | True
react-php.png | 35.7KB | 35.7KB | 0B | 50 Seconds | True
react-svg-fbp.png | 57.2KB | 57.2KB | 0B | 1.4 Minutes | True
reactive-bookmarklet.png | 40.8KB | 40.8KB | 0B | 39 Seconds | True
reflux-flux.png | 2KB | 2KB | 0B | 23 Seconds | True
relay-visual-archite...png | 129KB | 129KB | 0B | 9.6 Minutes | True
resistance-calculato...png | 44.1KB | 44.1KB | 0B | 1.3 Minutes | True
skills-matter.png | 120.3KB | 120.3KB | 0B | 1.5 Minutes | True
snake.png | 6.8KB | 6.8KB | 0B | 41 Seconds | False
steve_reverse.gif | 5.4MB | 5.4MB | 0B | 35 Seconds | True
sweet-jsx.png | 18.4KB | 18.4KB | 0B | 1.2 Minutes | True
tcomb-react-native.png | 24.3KB | 24.3KB | 0B | 2.1 Minutes | True
thinking-in-react-co...png | 18.6KB | 18.6KB | 0B | 37 Seconds | True
thinking-in-react-mo...png | 17KB | 17KB | 0B | 30 Seconds | True
todomvc.png | 21.8KB | 21.8KB | 0B | 2.2 Minutes | True
turboreact.png | 3.4KB | 3.4KB | 0B | 22 Seconds | False
tutsplus.png | 28.8KB | 28.8KB | 0B | 1.2 Minutes | True
unite.png | 13.3KB | 13.3KB | 0B | 31 Seconds | True
versioning-1.png | 8KB | 8KB | 0B | 33 Seconds | False
versioning-2.png | 9.1KB | 9.1KB | 0B | 41 Seconds | True
versioning-3.png | 28.8KB | 28.8KB | 0B | 1.3 Minutes | True
versioning-4.png | 31.8KB | 31.8KB | 0B | 1.7 Minutes | True
versioning-5.png | 12.7KB | 12.7KB | 0B | 57 Seconds | True
versioning-6.png | 27.7KB | 27.7KB | 0B | 1.4 Minutes | True
versioning-poll.png | 48.2KB | 48.2KB | 0B | 2.7 Minutes | True
weather.png | 6.8KB | 6.8KB | 0B | 17 Seconds | True
wolfenstein_react.png | 110.8KB | 110.8KB | 0B | 1.1 Minutes | True
xoxo2013.png | 168.3KB | 168.3KB | 0B | 1.3 Minutes | True
xreact.png | 3.2KB | 3.2KB | 0B | 15 Seconds | True
compiled-successfull...png | 50KB | 50KB | 0B | 3 Minutes | True
compiled-with-warnin...png | 134.4KB | 134.4KB | 0B | 3.7 Minutes | True
created-folder.png | 136KB | 136KB | 0B | 3.5 Minutes | True
failed-to-compile.png | 135.7KB | 135.7KB | 0B | 3.5 Minutes | True
npm-run-build.png | 122.1KB | 122.1KB | 0B | 3.4 Minutes | True
relay-architecture.png | 55.1KB | 55.1KB | 0B | 8.7 Minutes | True
relay-containers-dat...png | 27.3KB | 27.3KB | 0B | 4.1 Minutes | True
relay-containers.png | 13.9KB | 13.9KB | 0B | 2.7 Minutes | True
sample-newsfeed.png | 56.9KB | 56.9KB | 0B | 3.2 Minutes | True
cdn-cors-header.png | 42.5KB | 42.5KB | 0B | 1.5 Minutes | True
codewinds-004.png | 2.3KB | 2.3KB | 0B | 10 Seconds | True
devtools-dev.png | 51.6KB | 51.6KB | 0B | 46 Seconds | True
devtools-prod.png | 27.1KB | 27.1KB | 0B | 33 Seconds | True
granular-dom-updates.gif | 122.9KB | 122.9KB | 0B | 3 Seconds | True
implementation-notes...png | 51KB | 51KB | 0B | 2.8 Minutes | True
javascript-jabber.png | 1.6KB | 1.6KB | 0B | 10 Seconds | True
keyboard-focus.png | 1.7KB | 1.7KB | 0B | 11 Seconds | True
perf-dom.png | 7.3KB | 7.3KB | 0B | 15 Seconds | True
perf-exclusive.png | 9.3KB | 9.3KB | 0B | 16 Seconds | True
perf-inclusive.png | 12.2KB | 12.2KB | 0B | 23 Seconds | True
perf-wasted.png | 16KB | 16KB | 0B | 23 Seconds | True
react-devtools-state.gif | 567.3KB | 567.3KB | 0B | 13 Seconds | False
should-component-upd...png | 23.9KB | 23.9KB | 0B | 1.2 Minutes | True
thinking-in-react-ta...png | 10.7KB | 10.7KB | 0B | 21 Seconds | False
devtools.png | 23.4KB | 23.4KB | 0B | 59 Seconds | True
tictac-empty.png | 1.8KB | 1.8KB | 0B | 43 Seconds | False
tictac-numbers.png | 4KB | 4KB | 0B | 23 Seconds | False
grayarrow.gif | 111B | 111B | 0B | 1 Second | True
logo.png | 218B | 218B | 0B | 7 Seconds | True

### CODE REVIEW

**Comment by devedse** [comment]
Did some more improvements to the Web Optimization Project, hopefully the I can get the next version to not fail on any of the optimizations :smile:.

**Comment by devedse** [comment]
Wrong PNG files are not included in the Checkin. Only files that match 100% pixel by pixel are included.

**Comment by sophiebits** [comment]
If you open the Changed Files tab it clearly shows many added files named Wrong*.png.

**Comment by devedse** [comment]
You're right. I currently don't have access to my computer, but will investigate this later.

**Comment by gaearon** [comment]
Closing as stale (and we're moving those files anyway).

**Comment by devedse** [comment]
Just investigated the issue and this was a line of code that should've been only for debugging, it's fixed in my code now atleast :)

**Pull request closed without merging**
