### PR TITLE
updated Strict Badge link to point to new docs

### PR DESCRIPTION
**Pull request by runday198**
## Summary
Closes https://github.com/facebook/react/issues/26821

Updated Strict Badge link to point to the new docs

### CODE REVIEW

**Comment by hoxyq** [comment]
Appreciate your help with this, have to go with https://github.com/facebook/react/pull/26825.

**Comment by runday198** [comment]
It's all good, friend

**Comment by runday198** [comment]
Wonder if you could maybe give some advice on contributing more to OS, would much appreciate it

**Comment by hoxyq** [comment]
> Wonder if you could maybe give some advice on contributing more to OS, would much appreciate it

I think I am not the best person to give advices on how to start with open source. Looks like you already doing great, look for more easy first tasks to tackle and then try to find more complex problems, engage with other contributors in discussions. Good luck!

**Comment by runday198** [comment]
No worries, any advice is good. Thanks a lot

**Pull request closed without merging**
