### PR TITLE
Remove setProps and replaceProps.

### PR DESCRIPTION
**Pull request by jimfb**
Remove setProps and replaceProps.

### CODE REVIEW

**Comment by spicyj** [comment]
:+1: 

Can we get rid of TopLevelWrapper now? I don't remember.

**Comment by jimfb** [comment]
I don't remember either, but we would probably need it for setstate/replacestate, right?

relevant diff:
https://github.com/facebook/react/commit/643651b8e5f91de4e59580b46330a1aba4e66100

**Comment by spicyj** [comment]
That was so that we could enqueue updates to native components in the same way as composites – native components don't have setState so it might be irrelevant now.

**Comment by jimfb** [comment]
Ok, removing `TopLevelWrapper` should be a separate diff anyway, so I'll merge this now and that will unblock us for that diff.

**Comment by trigun539** [comment]
Since getDomNode was removed. Is it possible to focus a list item?
Before:
`
this.ref.element.getDOMNode().focus();
`
Now?
`
this.element.focus(); // In my case, the element is a li not an input.
`
Tried both ways, and not working. Tried to find documentation about putting an element in focus, but only thing I saw was doing something like: this.input.focus();

Any suggestions? Doc link I could follow. Thanks

**Comment by gaearon** [comment]
@trigun539 

Is this a question about React or about DOM in general? In React, you no longer need `getDOMNode()` because you get the DOM node itself.

As to how `focus()` works, it might be better to consult DOM tutorials. It’s not specific to React, unless you can show there is something that works in DOM but breaks in React, in which case you would need to file a bug with a reproducing case.

I hope this helps!

**Comment by spicyj** [comment]
@trigun539 You need to add a ref to the input element. See the docs for more details:

https://facebook.github.io/react/docs/refs-and-the-dom.html

**Comment by laumair** [comment]
@trigun539 @gaearon Have used something like this in one of my implementations with focusing an input element. Not sure if this is the best way but I am pretty sure this can help. 
```
const InputField = (props) => {
  const { input, shouldFocusField } = props;
  const focusField = c => {
    if (c != null) {
      c.focus();
    }
  };

  return <input {...input} {...shouldFocusField ? { ref: focusField } : {}} />;
};

```
Where you can control the `shouldFocusField` boolean in the component where you use the `InputField` component. This would definitely work for any other component as well as far as I think. Hope this helps!

**Comment by trigun539** [comment]
Thanks for the help.

**Comment by trigun539** [comment]
I guess the real issue was related to this and not react: http://stackoverflow.com/questions/30213603/javascript-not-able-to-set-focus-to-first-li-element-within-ul. Thanks again. @gaearon @spicyj @laumair 

Added the tab index and worked great!

**Pull request merged**
