### PR TITLE
yarn

### PR DESCRIPTION
**Pull request by madhusudhan123-star**
added new words like yarn for yarn user better learning

### CODE REVIEW

**Comment by harryzumwalt-wk** [comment]
Hi @madhusudhan123-star 👋 , even though this is a simple documentation change, it would be great if you could still use a more descriptive PR title. This helps others understand the purpose of your PR more easily. Possibly something like "Add Yarn package link to README".

Also it seems you have linked to the create-react-app package, which is different from react itself. This is the link for the yarn React package:
https://yarnpkg.com/package/react

**Comment by harrygz889** [comment]
Hi @madhusudhan123-star 👋 , even though this is a simple documentation change, it would be great if you could still use a more descriptive PR title. This helps others understand the purpose of your PR more easily. Possibly something like "Add Yarn package link to README".

Also it seems you have linked to the create-react-app package, which is different from react itself. This is the link for the yarn react package:
https://yarnpkg.com/package/react

**Comment by madhusudhan123-star** [comment]
Thank you for the information and for guiding me. I will try to change it. I am first time contributing in GitHub.

**Review by akirataguchi115 — COMMENTED** [review]
LGTM!

**Comment by madhusudhan123-star** [comment]
Thank you

**Pull request closed without merging**
