### PR TITLE
Continue render on null reference error in IE

### PR DESCRIPTION
**Pull request by wesrobinson12**
In IE11, my application is receiving the `Unable to get property '__reactInternalInstance$nn565zf8wm9c' of undefined or null reference` error.  The findParent function is passing a null container which is being used as an object with a key of reactInternalInstance in the ReactDOMComponentTree file

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run prettier`).
6. Make sure your code lints (`npm run lint`).
7. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
8. If you haven't already, complete the CLA.

### CODE REVIEW

**Comment by gaearon** [comment]
Can you reproduce this problem with React 16 RC?

**Comment by wesrobinson12** [comment]
@gaearon - I'm attempting to fix all deprecation warnings and get up and running with React 16, but am getting the error "Cannot find module 'react-dom/test-utils'".  I was attempting to replace react-addons-test-utils.  Any idea why I might be seeing this?

**Comment by gaearon** [comment]
It definitely exists: https://unpkg.com/react-dom@next/test-utils.js.
So if you see this, you probably didn't update `react-dom` to `16.0.0-rc.2`.

**Comment by wesrobinson12** [comment]
I see the issue now...we have a number of packages that import PropTypes from the 'react' library.  Do you know of a work-around here?

**Comment by gaearon** [comment]
You can temporarily patch it manually, e.g.

```js
import './patchReact'
```

as your first import statement, and there do

```js
require('react').PropTypes = require('prop-types')
```

**Comment by gaearon** [comment]
I'll close this as it's specific to 15. Please try again with React 16 and let me know if it still reproduces.

**Pull request closed without merging**
