### PR TITLE
[strawman] Add Prepack to bundles

### PR DESCRIPTION
**Pull request by gaearon**
This doesn't actually work. I haven't played with Prepack much before so I'm not sure what exactly we need to do. The good news is that we can actually know if we fix the issues thanks to the new bundle tests :-)

React DOM currently ends up empty for some reason. Maybe need to model a DOM environment for its initialization.

In the past when I've tried Prepack, it emitted terribly large code for DOM injections because they create dictionaries that are large when serialized. But I plan to later remove those injections anyway. SimpleEventPlugin also has this problem.

### CODE REVIEW

**Comment by blling** [comment]
Prepack is BSD-licensed. We also provide an additional patent grant....

**Comment by gaearon** [comment]
This doesn't have anything to do with whether we can use it for our build system or not. :-)

**Comment by blling** [comment]
:-)

**Comment by sebmarkbage** [comment]
I don't know if the lazy closure initialization is currently not optional. We definitely need that to be optional before adopting. Shouldn't be that difficult to fix.

**Comment by gaearon** [comment]
By lazy closure initialization you mean..? Something that would help us not create bloated objects?

**Comment by gaearon** [comment]
Tfw you re-read Sebastian a few months later and it makes sense.
He's saying we don't want to evaluate the IIFE.

**Comment by sebmarkbage** [comment]
That's not what I'm saying. :) Prepack lazily initialize objects the first time they're needed instead of all the time.

Prepack has a mode for "simple closures" now that should be enough.

**Comment by gaearon** [comment]
Why do we care if they're initialized lazily on first access or not?

**Comment by sebmarkbage** [comment]
Because the initialization code adds bloat.

**Comment by gaearon** [comment]
https://github.com/facebook/react/issues/12206

**Pull request closed without merging**
