### PR TITLE
Remove trapBubbledEventsLocal

### PR DESCRIPTION
**Pull request by jfo84**
This PR moves calls to `trapBubbledEventsLocal` outside of an equivalent switch statement of html tags.

This is a duplicate of #9973. I think y'all were busy cleaning up 15.6 when I first PR'ed this.

### CODE REVIEW

**Comment by gaearon** [comment]
Hmm. I don’t think that’s what the TODO was referring to.

If I understand it right, the TODO is asking to inline the calls themselves instead of `trapBubbledEventsLocal` calls. So the fix would be to

1. Completely delete `trapBubbledEventsLocal`
2. Duplicate its switch branches in two respective functions calling it instead of calls to `trapBubbledEventsLocal`

This lets us avoid doing `switch` twice.

**Comment by jfo84** [comment]
I took that approach in #9924 but didn't get any feedback. I just resurrected that branch and merged master and some tests are failing, but I'll take a look later. I can just revert the initial commit and squash commit onto this branch to keep the conversation in one place

**Comment by jfo84** [comment]
It looks like it was just a local issue. Ready for review @gaearon

**Comment by gaearon** [comment]
Yea, sorry about that. This is our biggest release yet and we haven’t been reviewing things well.

**Comment by gaearon** [comment]
Looked through the code in each case and did manual testing for some of these.
I think this is correct. Thanks!

**Comment by jfo84** [comment]
No worries, @gaearon. Y'all get a lot of PR's

**Pull request merged**
