### PR TITLE
Don't set value prop for uncontrolled component

### PR DESCRIPTION
**Pull request by wrzasa**
I'm a newbie, but as far as I understand you don't set `value` property for uncontrolled components. In code example for uncontrolled components the `value` prop is set.

### CODE REVIEW

**Comment by wrzasa** [comment]
No thanks. Way too much trouble to provide you with some minor bug report. Use it as you wish or forget it.

Don't you think it's a little weird to make someone who of good will gives you own time to improve what you do, to register somewhere, read and sign a lengthy license agreement (shouldn't I consult it with my lawyer first?)? I already gave you as much time as I wished and what you require is much more. It's not even close to community.

BTW: what will you do now? The issue is there, but the fix is mine? If I don't sign anything, you won't be able to correct the issue, because the fix is mine? The fix is so simple it probably can't be done differently. Will you waste your time look for another way to fix this? Isn't it odd?  Aren't you a little bit entangled by your own policy?

**Comment by Aweary** [comment]
Thanks for the PR @wrzasa, we appreciate it. The CLA is required for any contribution, feel free to take your time and read it over (it's actually relatively short). If you or your employer have concerns over the terms of the CLA feel free to consult with them or your legal council. We have over 800 contributors from various backgrounds, all of which have signed the CLA, so hopefully that's a vote of confidence if anything.

If you do decide to sign the CLA: as far as this change goes, could you just remove the line all together instead of commenting it out? That would make it consistent with the CodePen.

Thanks!

**Comment by gaearon** [comment]
@wrzasa 

Sorry about this!

CLA is mostly meant for code changes, not for docs. I think we should move docs into a separate repo and disable CLA there.

Either way, I don't think just commenting it out is going to make tutorial much clearer. If you look at other open PRs, you can see that @ericnakagawa is working to fix multiple issues in this doc in #8084, so we'll probably go ahead with that instead.

Cheers!

**Comment by wrzasa** [comment]
Feel free to use it as you wish (or not). Just wanted to make sure somebody will notice this. 

I will certainly consider CLA when I have some real contribution.

**Comment by gaearon** [comment]
Yea, thanks for bringing it to our attention. We'll fix today or tomorrow.

**Pull request closed without merging**
