### PR TITLE
Use only public API in CSSProperty-test

### PR DESCRIPTION
**Pull request by ksvitkovsky**
As a part of #9955

### CODE REVIEW

**Comment by gaearon** [comment]
Can we also have a second test that verifies they get correctly set when rendering on the client side with ReactDOM? In fact I think it might be best to remove this file and create a similar test inside ReactDOMServerIntegration-test that verifies these styles end up being set. Because it tests both client and server rendering at the same time.

**Comment by ksvitkovsky** [comment]
I have that weird issue(?) when rendering element with styles that has ms-prefixed rules. Rendered element' style property has ms-prefixed rules starting with lower-case 'm' in `clean client render`-scenario, while in others it is upper-case 'M'.

Is that the expected behavior? If so, is that ok to write expectations like this - `expect(e.style.MsFlexGrow || e.style.msFlexGrow).toBe('10');`

**Comment by gaearon** [comment]
Might be a jsdom bug. Yes, I think this is fine since it depends on jsdom implementation.

**Comment by gaearon** [comment]
Thanks!

**Pull request merged**
