### PR TITLE
Refactor `precacheChildNodes` slightly

### PR DESCRIPTION
**Pull request by eoin**
This ‘fixes’ a bizarre IE9 script engine issue, discussed in https://github.com/facebook/react/issues/7803#issuecomment-254831838.

### CODE REVIEW

**Comment by Aweary** [comment]
@ccoffey can you confirm this fix resolves your issue?

**Comment by eoin** [comment]
@Aweary yep! I work with @ccoffey 😄, and we've verified that this fixes the issue, both for our app, and with the [repro-case](github.com/ccoffey/react-ie9-crash) that @ccoffey created.

**Comment by ccoffey** [comment]
@Aweary confirmed, this does resolve the issue I created!

**Comment by Aweary** [comment]
@spicyj @sebmarkbage does this change seem OK to you?

**Comment by spicyj** [comment]
Sure, I guess. No guarantee it won't break again later.

**Comment by Aweary** [comment]
Yeah, I'm not big on including a fix without knowing exactly why its a fix. But I suppose its a harmless change.

@eoin can you resolve the merge conflicts?

**Comment by eoin** [comment]
@Aweary resolved.

**Comment by gaearon** [comment]
LGTM, thanks.

**Comment by steroberts89** [comment]
Does anyone have an date for the version which contains this release?

**Comment by gaearon** [comment]
Ideally we'd like the next patch release to also fix https://github.com/facebook/react/issues/8392. So if you could help find a solution to it, we could get it out quicker.

**Comment by gaearon** [comment]
This is now out in 15.4.2.
Please verify.

**Pull request merged**
