### PR TITLE
Add support for new TypeScript ModuleResolutionKind=node

### PR DESCRIPTION
**Pull request by remojansen**
This PR add support for the new Typescript ModuleResolutionKind=node as described in the proposal [here](https://github.com/Microsoft/TypeScript/issues/2338).

More information is also available at https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages

### CODE REVIEW

**Comment by jimfb** [comment]
This looks super cool!

Was it generated in some way, or did you build it by hand?

The reason I ask is that there are two things we need to figure out:
 * How do we maintain it (ideally we could just re-run a script, but maybe we need to do it by hand)
 * How do we verify it (for correctness... maybe we just accept PRs as they come - but this just compounds the whitelist hell we already face)

**Comment by zpao** [comment]
Looks like this is just copied in from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts, which is manually built & maintained.

Jim brings up a good point - it would be awesome to have a way to verify and / or autogenerate this. The latter is probably not going to happen so the former would be ideal. If we can't do that then I don't think we'll take this. We don't use TS and so we wouldn't know when we break things without something automated telling us.

A few further (more specific) points:
1. We don't use that package.json to ship to npm (look inside `packages/react` to find the right one).
2. We'd want this for react-dom and each of the addons. all or nothing.
2. We're well past v0.13.3 now and would need these updated for master

cc @sebmarkbage because TS and modules

**Comment by remojansen** [comment]
- The `.d.ts` file comes form [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) which is the main source of TypeScript definition files. The files are hand-made. 

- For sometime the React team will have to take the `.d.ts` from DefinitelyTyped or accept PRs but with the new module resolution logic, as more and more npm modules will include typings people will stop using DefinitelyTyped.

- The DefinitelyTyped project validates that the `.d.ts` files compile but they don't have a way to ensure that the `.d.ts` files declares the API of a library in the correct way. The only way to ensure that would be writing a TypeScript app importing react and its `.d.ts` file and run some e2e tests.

**Comment by remojansen** [comment]
About auto-generating `.d.ts` files... it would be possible but really complex (and a great contribution to the TypeScript community). You basically need to take the React.js library as an input and find out two things:

- Public APIs (signatures without types)
- Types

I only have two ideas about how to achieve this:

- Use a run-time code analyser to find out the signatures and types. A start point could be something based on http://flowtype.org/
- My second idea is to document all the React Methods and use the comments to generate the `.d.ts` files. This solution is less complex but more "hacky".

The generation of `.d.ts` is probably the only major problem of working with TypeScript.

**Comment by sebmarkbage** [comment]
It wouldn't be unreasonable to have this work live inside the React repo since it is being well maintained already. That request should come from the primary team maintaining it with appropriate testing infrastructure and licensing information associated with it. We won't take this without those things.

Even at Facebook, our React definitions are maintained by the Flow team itself. In its own repo. So it's kind of up to those teams if they want to source of truth to live here.

Might be nice to include them in npm releases.

**Pull request closed without merging**
