### PR TITLE
Move DOM related code to the injection

### PR DESCRIPTION
**Pull request by maciej-ka**
This PR is about a todo comment in `EventPluginHub`
```
// TODO: shouldPreventMouseEvent is DOM-specific and definitely should not		
// live here; needs to be moved to a better place soon
```

This is a proposal to add `PreventedEvents` injection that takes some DOM dependent code out of EventPluginHub.

### CODE REVIEW

**Comment by lokson** [comment]
This is my first code contribution. Would you know why ./scripts/circleci/test_entry_point.sh is failing in test check?

**Comment by aweary** [comment]
Please don't use the title for status updates, it produces a lot of noise in the PR.

**Comment by lokson** [comment]
@aweary ok, sorry for that. Would you know why one test `test_entry_point.sh` is failing on Circle? Jest is all green, I'm clueless.

**Comment by gaearon** [comment]
If I scroll to the bottom I see:

```
Received return code 0 from: node ./scripts/tasks/eslint
Received return code 1 from: node ./scripts/prettier/index
Received return code 0 from: node ./scripts/tasks/flow
Received return code 0 from: node ./scripts/tasks/jest
Received return code 0 from: ./scripts/circleci/build.sh
Received return code 0 from: ./scripts/circleci/test_print_warnings.sh
Received return code 0 from: ./scripts/circleci/track_stats.sh
```

You probably forgot to run `npm run prettier` and commit the result.

**Comment by lokson** [comment]
Thanks, all checks pass now.

**Comment by gaearon** [comment]
On the one hand it'd be nice to fix it. On the other hand I'm hesitant to add even more indirection to an already overabstracted part of the library...

**Comment by gaearon** [comment]
I'm going to close this. I don't think we want to add any more dynamic injection.

**Pull request closed without merging**
