### PR TITLE
去掉被我们

### PR DESCRIPTION
**Pull request by huanqing**
去掉被我们 ... 语言更简洁

### CODE REVIEW

**Comment by jimfb** [comment]
CLA is required before we can merge this.   https://code.facebook.com/cla

**Comment by jimfb** [comment]
Ping.

**Comment by keyanzhang** [comment]
在 merge 您的 PR 之前需要请您签署一下 https://code.facebook.com/cla。谢谢！

**Comment by gaearon** [comment]
Thanks for the PR! We just released [new docs mostly written from scratch](https://facebook.github.io/react/). However this means that all old localized content is gone, as new one needs to be written. We will track this effort in https://github.com/facebook/react/issues/8063. Sorry!

**Pull request closed without merging**
