### PR TITLE
Update babel-eslint and eslint packages

### PR DESCRIPTION
**Pull request by necolas**
## Summary

We need to update our eslint dependencies as they have fallen behind.

This patch updates the main `eslint` package and adds `eslint-config-prettier` to silence errors related to formatting, which `prettier` manages.

## Test Plan

`yarn lint`.

## Notes

This diff does not update eslint plugin packages, because adding the following results in `yarn lint` failing with the attached error message.

```diff
diff --git a/package.json b/package.json
index d64d53a6a..a3159d8b4 100644
--- a/package.json
+++ b/package.json
@@ -47,12 +47,13 @@
     "danger": "^9.1.8",
     "error-stack-parser": "^2.0.2",
     "eslint": "^6.8.0",
-    "eslint-config-fbjs": "^1.1.1",
+    "eslint-config-fbjs": "^3.1.1",
     "eslint-plugin-babel": "^5.3.0",
     "eslint-plugin-flowtype": "^2.25.0",
     "eslint-plugin-jest": "^22.15.0",
+    "eslint-plugin-jsx-a11y": "^6.2.3",
     "eslint-plugin-no-for-of-loops": "^1.0.0",
-    "eslint-plugin-react": "^6.7.1",
+    "eslint-plugin-react": "^7.17.0",
     "eslint-plugin-react-internal": "link:./scripts/eslint-rules",
     "fbjs-scripts": "^0.8.3",
     "filesize": "^3.5.6",
```

```console
export * from './src/ReactIs';
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/necolas/OpenSource/github/facebook/react/node_modules/prop-types/index.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
error Command failed with exit code 1.
```

### CODE REVIEW

**Comment by gaearon** [comment]
What's up with the commas? Did we change Prettier config, or how does this work?

**Comment by necolas** [comment]
Oh yeah I forgot none of these commands automatically run on commits in this repo.

> What's up with the commas? Did we change Prettier config, or how does this work?

Running `yarn lint` produced a lot of errors about missing trailing commas

**Comment by gaearon** [comment]
Here's what I don't understand. Presumably, `yarn prettier` would have removed those commas (because Prettier doesn't know about our ESLint config). But why didn't CLI fail? Our CI should fail when `yarn prettier` produces a change.

**Comment by necolas** [comment]
IIRC CI did fail over prettier producing changes

**Pull request merged**
