### PR TITLE
The Web Optimization Project has optimized your repository!

### PR DESCRIPTION
**Pull request by devedse**
# Web Optimization Project (Beta)

The [Web Optimization Project](https://www.github.com/devedse/weboptimizationproject) is a project that will automatically optimizes files in git repositories by compressing them losslessly. This project was created by [Devedse](https://github.com/devedse) in an effort to save the world! :smirk:

## Optimization

The Web Optimization Project optimized this repository. All optimizations (compressions) are done losslessly and no quality / data is lost. This is also verified afterwards by the Wop so you can be sure that your images are exactly the same.

### Commit 1

Information | Value
-- | --
Version | 0.0.2.0
Support file extension | .PNG .JPG .JPEG .GIF .BMP

#### Statistics

Stats | Value
-- | --
Total bytes saved in this commit | 1.9MB

#### Files optimized in this repository

FileName | Original Size | Optimized Size | Bytes Saved | Successful
-- | -- | -- | -- | --
external.png | 1.2KB | 189B | 1KB | True
external_2x.png | 1.1KB | 134B | 1017B | True
logo_og.png | 10.5KB | 10.5KB | 18B | True
logo_small.png | 10.5KB | 4.3KB | 6.2KB | True
logo_small_2x.png | 28.4KB | 12.5KB | 15.9KB | True
logo_small_gray.png | 5.4KB | 1.8KB | 3.7KB | True
logo_small_gray_2x.png | 9.3KB | 4.2KB | 5KB | True
noise.png | 22.8KB | 22.1KB | 771B | True
oss_logo.png | 4.3KB | 3.9KB | 406B | True
search.png | 1.3KB | 244B | 1.1KB | True
animal-sounds.jpg | 51.7KB | 48.1KB | 3.6KB | True
chatapp.png | 27.2KB | 21.6KB | 5.6KB | True
cra-better-output.png | 214.2KB | 146.4KB | 67.8KB | True
cra-dynamic-import.gif | 1.7MB | 1.7MB | 0B | True
cra-jest-search.gif | 906.9KB | 906.9KB | 0B | True
cra-pwa.png | 90.2KB | 45.4KB | 44.8KB | True
cra-runtime-error.gif | 1.7MB | 1.7MB | 0B | True
cra-update-exports.gif | 1.4MB | 1.4MB | 0B | True
devtools-full.gif | 1.3MB | 1.3MB | 0B | True
devtools-search.gif | 929.2KB | 929.2KB | 0B | True
devtools-side-pane.gif | 42.6KB | 42.6KB | 0B | True
devtools-tree-view.png | 134KB | 71.2KB | 62.9KB | True
dog-tutorial.png | 59.2KB | 40.5KB | 18.7KB | True
error-boundaries-stack-trace-line-numbers.png | 68.1KB | 35.8KB | 32.2KB | True
error-boundaries-stack-trace.png | 66.7KB | 34.9KB | 31.8KB | True
first-look.png | 36.3KB | 27.6KB | 8.8KB | True
flux-chart.png | 68KB | 41.6KB | 26.4KB | True
flux-diagram.png | 197.4KB | 130.1KB | 67.3KB | True
genesis_skeleton.png | 167.9KB | 142.6KB | 25.4KB | True
gpu-cursor-move.gif | 789.6KB | 789.6KB | 0B | True
guess_filter.jpg | 39.7KB | 37.7KB | 2KB | True
hacker-news-react-native.png | 127.2KB | 102.8KB | 24.4KB | True
jsx-compiler.png | 30KB | 13.7KB | 16.3KB | True
kendoui.png | 41.2KB | 22KB | 19.1KB | True
khan-academy-editor.png | 10.8KB | 10.8KB | 0B | False
landoflisp.png | 156.4KB | 108.7KB | 47.8KB | True
lights-out.png | 11.9KB | 3.3KB | 8.6KB | True
makona-editor.png | 34.6KB | 23.5KB | 11KB | True
markdown_refactor.png | 7.2KB | 5.3KB | 1.8KB | True
modus-create.gif | 992.3KB | 992.3KB | 0B | True
monkeys.gif | 532KB | 532KB | 0B | True
ngreact.png | 85.3KB | 54.4KB | 30.9KB | True
om-backbone.png | 176KB | 126.5KB | 49.5KB | True
parse-react.jpg | 55.6KB | 47.9KB | 7.7KB | True
polarr.jpg | 69.5KB | 66KB | 3.5KB | True
propeller-logo.png | 3.1KB | 1.3KB | 1.8KB | True
property-finder.png | 72.7KB | 60.9KB | 11.8KB | True
quiztime.png | 22KB | 18.7KB | 3.3KB | True
react-50k-mock-full.jpg | 133.8KB | 126.8KB | 7KB | True
react-50k-mock.jpg | 118.4KB | 83KB | 35.4KB | True
react-50k-tshirt.jpg | 675.6KB | 633.4KB | 42.3KB | True
react-browserify-gulp.jpg | 25KB | 23.1KB | 1.9KB | True
react-dev-tools.jpg | 80.9KB | 69.7KB | 11.2KB | True
react-diff-tree.png | 39.7KB | 26.8KB | 12.8KB | True
react-draggable.png | 26.5KB | 10.2KB | 16.3KB | True
react-hackathon.jpg | 51.3KB | 48.8KB | 2.6KB | True
react-page.png | 24.1KB | 19.9KB | 4.2KB | True
react-perf-chrome-timeline.png | 96.3KB | 68.4KB | 27.9KB | True
react-php.png | 41.6KB | 35.7KB | 5.9KB | True
react-svg-fbp.png | 72KB | 57.2KB | 14.8KB | True
reactive-bookmarklet.png | 58.7KB | 40.8KB | 17.8KB | True
reflux-flux.png | 2.8KB | 2KB | 877B | True
relay-visual-architecture-tour.png | 278.6KB | 129KB | 149.6KB | True
resistance-calculator.png | 58.3KB | 44.2KB | 14.1KB | True
skills-matter.png | 165.3KB | 120.3KB | 45KB | True
snake.png | 6.8KB | 6.8KB | 0B | False
steve_reverse.gif | 5.4MB | 5.4MB | 0B | True
sweet-jsx.png | 48KB | 18.4KB | 29.5KB | True
tcomb-react-native.png | 56.2KB | 24.3KB | 31.9KB | True
thinking-in-react-components.png | 27.7KB | 18.6KB | 9.1KB | True
thinking-in-react-mock.png | 24.4KB | 17KB | 7.3KB | True
todomvc.png | 51KB | 21.8KB | 29.2KB | True
turboreact.png | 5.8KB | 3.4KB | 2.4KB | True
tutsplus.png | 53KB | 28.8KB | 24.2KB | True
unite.png | 15.8KB | 13.3KB | 2.4KB | True
versioning-1.png | 22.2KB | 22.2KB | 0B | False
versioning-2.png | 23.1KB | 23.1KB | 0B | False
versioning-3.png | 44.1KB | 44.1KB | 0B | False
versioning-4.png | 47.9KB | 47.9KB | 0B | False
versioning-5.png | 31.5KB | 31.5KB | 0B | False
versioning-6.png | 44.8KB | 44.8KB | 0B | False
versioning-poll.png | 100.7KB | 48.2KB | 52.5KB | True
weather.png | 13.9KB | 6.8KB | 7.1KB | True
wolfenstein_react.png | 120.8KB | 110.9KB | 9.9KB | True
xoxo2013.png | 245.6KB | 168.3KB | 77.3KB | True
xreact.png | 7.7KB | 3.2KB | 4.6KB | True
compiled-successfully.png | 80.7KB | 50KB | 30.6KB | True
compiled-with-warnings.png | 186.1KB | 135.1KB | 51KB | True
created-folder.png | 191.8KB | 136KB | 55.9KB | True
failed-to-compile.png | 189KB | 136.5KB | 52.5KB | True
npm-run-build.png | 171.9KB | 122.1KB | 49.8KB | True
relay-architecture.png | 130.8KB | 55.1KB | 75.7KB | True
relay-containers-data-flow.png | 69.4KB | 27.3KB | 42.1KB | True
relay-containers.png | 38.1KB | 13.9KB | 24.3KB | True
sample-newsfeed.png | 118.6KB | 56.9KB | 61.7KB | True
cdn-cors-header.png | 64.4KB | 42.5KB | 21.9KB | True
codewinds-004.png | 5.6KB | 2.3KB | 3.4KB | True
devtools-dev.png | 80.5KB | 51.6KB | 29KB | True
devtools-prod.png | 44.6KB | 27.1KB | 17.5KB | True
granular-dom-updates.gif | 124.2KB | 124.2KB | 0B | True
implementation-notes-tree.png | 58.5KB | 51KB | 7.5KB | True
javascript-jabber.png | 9.4KB | 1.6KB | 7.8KB | True
keyboard-focus.png | 7.1KB | 1.7KB | 5.4KB | True
perf-dom.png | 14.5KB | 7.3KB | 7.2KB | True
perf-exclusive.png | 18.1KB | 9.3KB | 8.8KB | True
perf-inclusive.png | 22.5KB | 12.2KB | 10.3KB | True
perf-wasted.png | 27.9KB | 16KB | 11.9KB | True
react-devtools-state.gif | 567.3KB | 567.3KB | 0B | True
should-component-update.png | 44.3KB | 23.9KB | 20.4KB | True
thinking-in-react-tagtree.png | 14.2KB | 14.2KB | 0B | False
devtools.png | 23.6KB | 23.4KB | 221B | True
tictac-empty.png | 10.9KB | 10.9KB | 0B | False
tictac-numbers.png | 16.4KB | 16.4KB | 0B | False
grayarrow.gif | 111B | 111B | 0B | True
logo.png | 274B | 218B | 56B | True

### CODE REVIEW

**Comment by devedse** [comment]
This is actually the first project that got optimized by the 'Web Optimization Project'. Feel free to leave any suggestions, ideas or general feedback.

**Comment by gaearon** [comment]
This looks great. Thanks!

**Comment by syranide** [comment]
Note that the color reproduction of the first image actually differs from the optimized one.

**Comment by syranide** [comment]
@devedse Weird, it doesn't show up anymore, I even sampled the image yesterday and it showed them as different colors. But they both have the same color profile (which I assumed as missing) and same content so yeah, and they look identical today... So yeah, sorry, my bad :+1:

**Comment by Mathspy** [comment]
@syranide I DID read your comment last time I saw this thread and some of the images were indeed not identical...

**Comment by syranide** [comment]
@Mathspy Oh, I was looking for that one but couldn't find it so I assumed it didn't exist. Perhaps I was mistakenly looking at that one then and commenting here 😄

**Comment by Mathspy** [comment]
@syanide Ohh okay, that's probably it. Almost felt like GitHub ghosts there for a second, right?

**Comment by devedse** [comment]
Lol, if you can find the image that differs, please post it here and I'll investigate :)

**Pull request merged**
