### PR TITLE
Fix Component Stacks for IE and Native Classes in Safari

### PR DESCRIPTION
**Pull request by sebmarkbage**
This is a follow up to https://github.com/facebook/react/pull/18561

It adds more test cases and includes a fix to Safari since Safari adds another stack frame for the construct call. Polyfills might do something similar so this tries to be resilient by skipping over those.

### Chrome:
```

    at Lazy
    at Component (http://localhost:8000/fixtures/stacks/Components.js:7:50)
    at div
    at Suspense
    at BabelClassWithFields (http://localhost:8000/fixtures/stacks/BabelClasses-compiled.js:54:31)
    at BabelClass (http://localhost:8000/fixtures/stacks/BabelClasses-compiled.js:36:29)
    at FrozenClass (http://localhost:8000/fixtures/stacks/Components.js:24:5)
    at NativeClass (http://localhost:8000/fixtures/stacks/Components.js:16:1)
    at SuspenseList
    at Custom Name (http://localhost:8000/fixtures/stacks/Components.js:11:23)
    at ErrorBoundary (http://localhost:8000/fixtures/stacks/Example.js:5:1)
    at Example (http://localhost:8000/fixtures/stacks/Example.js:33:21)
```
### Firefox:
```

Lazy
Component@http://localhost:8000/fixtures/stacks/Components.js:7:1
div
Suspense
BabelClassWithFields@http://localhost:8000/fixtures/stacks/BabelClasses-compiled.js:54:31
BabelClass@http://localhost:8000/fixtures/stacks/BabelClasses-compiled.js:36:29
FrozenClass@http://localhost:8000/fixtures/stacks/Components.js:24:5
NativeClass@http://localhost:8000/fixtures/stacks/Components.js:16:49
SuspenseList
DisplayName@http://localhost:8000/fixtures/stacks/Components.js:11:1
ErrorBoundary@http://localhost:8000/fixtures/stacks/Example.js:5:49
Example@http://localhost:8000/fixtures/stacks/Example.js:33:21
```
Note: Firefox doesn't respect displayName in stack traces.

### Safari:
```

Lazy
Component@http://localhost:8000/fixtures/stacks/Components.js:7:48
div
Suspense
BabelClassWithFields@http://localhost:8000/fixtures/stacks/BabelClasses-compiled.js:54:35
BabelClass@http://localhost:8000/fixtures/stacks/BabelClasses-compiled.js:36:34
FrozenClass@http://localhost:8000/fixtures/stacks/Components.js:24:10
NativeClass
SuspenseList
Custom Name@http://localhost:8000/fixtures/stacks/Components.js:11:21
ErrorBoundary
Example@http://localhost:8000/fixtures/stacks/Example.js:33:29
```

Note: Safari doesn't give us a line number for native classes without an explicit constructor.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
There's still one more issue to solve after this. Internet Explorer requires an error to be thrown before it gets a stack. So I'll need to throw instead of just creating the controls.

**Comment by sebmarkbage** [comment]
Ok after these changes it works in IE/Edge.

### Edge
```

   at Lazy
   at Component (http://localhost:8000/fixtures/stacks/Components.js:7:49)
   at div
   at Suspense
   at BabelClassWithFields (http://localhost:8000/fixtures/stacks/BabelClasses-compiled.js:54:5)
   at BabelClass (http://localhost:8000/fixtures/stacks/BabelClasses-compiled.js:36:5)
   at FrozenClass (http://localhost:8000/fixtures/stacks/Components.js:24:5)
   at NativeClass (http://localhost:8000/fixtures/stacks/Components.js:16:43)
   at SuspenseList
   at DisplayName (http://localhost:8000/fixtures/stacks/Components.js:11:22)
   at ErrorBoundary (http://localhost:8000/fixtures/stacks/Example.js:5:45)
   at Example (http://localhost:8000/fixtures/stacks/Example.js:33:3)
```

### IE10/11

After adjusting the fixtures to avoid ES2015 features.

```

   at Lazy
   at Component (http://localhost:8000/fixtures/stacks/Components.js:8:3)
   at div
   at Suspense
   at BabelClassWithFields (http://localhost:8000/fixtures/stacks/BabelClasses-compiled.js:54:5)
   at BabelClass (http://localhost:8000/fixtures/stacks/BabelClasses-compiled.js:36:5)
   at FrozenClass (http://localhost:8000/fixtures/stacks/Components.js:25:3)
   at NativeClass (http://localhost:8000/fixtures/stacks/Components.js:17:3)
   at SuspenseList
   at DisplayName (http://localhost:8000/fixtures/stacks/Components.js:12:3)
   at ErrorBoundary (http://localhost:8000/fixtures/stacks/Example.js:6:3)
   at Example (http://localhost:8000/fixtures/stacks/Example.js:36:3)
```

Notably IE8/9 doesn't give you a stack on errors.

**Comment by sebmarkbage** [comment]
Ok, this turned out to be a bit more code than I had originally hoped. I think we can still shave some bytes off from this implementation but it's still reasonable and much better than people adding meta data to code like displayName or line numbers since that doesn't scale.

**Comment by bvaughn** [comment]
Nice!

**Pull request merged**
