### PR TITLE
Add ReactFoo 2017 to list of upcoming conferences

### PR DESCRIPTION
**Pull request by karthikb351**
A conference on React and React Native in Bangalore.

[Website](https://reactfoo.in/2017/)

### CODE REVIEW

**Comment by nhunzaker** [comment]
Looks fun. Thanks!

**Comment by karthikb351** [comment]
@nhunzaker Hi Nathan - Any idea when this will be deployed?

**Comment by gaearon** [comment]
@nhunzaker I think we should make sure we cherry-pick to `15-stable` for time sensitive stuff like conferences in the future. :-)

I'll do this now.

**Comment by nhunzaker** [comment]
Ooooh. I had no idea this was how was done. Sorry sorry sorry.

**Comment by gaearon** [comment]
No worries! This is a really broken system IMO and we plan to get rid of it. Right now I try to work through the queue once in a while but I don't really do a good job at it.

**Pull request merged**
