### PR TITLE
Assert instance type using internal constructor

### PR DESCRIPTION
**Pull request by troutowicz**
Support type testing of factory based components.

### CODE REVIEW

**Comment by ericelliott** [comment]
:+1:

**Comment by zpao** [comment]
Can you clarify a bit what you're expecting to work that isn't?

**Comment by troutowicz** [comment]
@zpao 
The constructor method on a component instance's prototype references the function that created the instance's prototype. When testing a component instance produced by a factory, that prototype producing method is an internal function of the factory. The constructor method on the instances prototype will be what's expected, but it will not be equal to the factory function.

```js
// class
class Foo {}

//factory
const foo = function () {
  function F() {}
  
  return new F(); 
}

assert.equal(new Foo().constructor, Foo);
  >> ok
assert.equal(foo().constructor, foo);
  >> AssertionError: [Function: F] == [Function: foo]
```

**Comment by troutowicz** [comment]
@zpao Update?

**Comment by sebmarkbage** [comment]
Makes sense! Flagging it for merge but looks like there are some Travis problem.

**Comment by zpao** [comment]
Looks like Travis was just the webworker test. Thanks @troutowicz!

**Comment by troutowicz** [comment]
Sure thing!

**Pull request merged**
