### PR TITLE
[Not for merge] Debug logging

### PR DESCRIPTION
**Pull request by gaearon**
This is @bvaughn's branch. Just gonna try to use it to debug some stuff.

### CODE REVIEW

**Comment by bvaughn** [comment]
Ah. Sorry. I could rebase and push my branch if you're using it. I assumed you'd forgotten about it.

**Comment by gaearon** [comment]
It's behind two or three other things on the list, but the priority bumped because we got another possible Suspense bug. A rebase would be great, yes!

**Comment by bvaughn** [comment]
Ok Dan, rebased and force pushed.

**Comment by bvaughn** [comment]
It's a little confusing that pushing my branch updates someone else's PR so I'm just going to close this and open my own where I can leave notes.

**Pull request closed without merging**
