### PR TITLE
check that React is generating a closing tag for menuitem

### PR DESCRIPTION
**Pull request by HurricaneJames**
Currently the React tests check that the dom produces the correct `innerHTML` containing a closing `</menuitem>` tag. However, this is against spec, and jsdom 1.0+ automatically strips out the closing tag because it should not be in the dom. This is the only failing test when upgrading Jest to the latest version of jsdom that still supports Node.js (3.1.2).

As discussed in #2266, apparently some older browsers have an issue with the menuitem void element not having a closing tag. So, since it is important to keep it around, but modern browsers are going to strip it anyway, I propose spying on the `mountComponent` function to see if it is trying to output the closing tag. That way we can be certain to attempt to inject a closing tag, but are not relying on the DOM implementation to verify that it worked.

This pull request contains my implementation of how to spy on, call through, and verify that the returned string is what we want. It is pretty ugly, but I'm not sure there is a better way to implement it. That said, I am very open to suggestions on better ways to do it.

### CODE REVIEW

**Comment by spicyj** [comment]
Let's just use React.renderToString here.

**Comment by HurricaneJames** [comment]
Yeah, that would make a lot more sense. Done.

**Comment by spicyj** [comment]
renderToString just takes one argument; no need to pass container. Other than that, this looks good. Mind fixing and squashing your commits into one?

**Comment by HurricaneJames** [comment]
Not at all, I'll get right on that.

**Comment by HurricaneJames** [comment]
the rebase just made things more complicated, probably because I had merged in changes from upstream. I think I'll close this request, delete my repo, recreate it and open a new pull request from that so it will have a simple commit.

**Comment by spicyj** [comment]
If you do an interactive rebase (git rebase -i) then you can delete all the lines that don't correspond to your commits and then you can force-push to the same branch to update this PR – no need to delete your repo. A new PR is also okay though.

**Comment by HurricaneJames** [comment]
Yeah, I tried, and thought I had succeeded. If there were more changes in this request, I would fight with Git more, but for 2 lines... I'm just going to create a new PR.

**Pull request closed without merging**
