### PR TITLE
Run Jest in production mode

### PR DESCRIPTION
**Pull request by gaearon**
Supersedes https://github.com/facebook/react/pull/10273.

See individual commits as there’s quite a bit here.

This is almost ready. The rest are actual small differences (e.g. less detailed messages) that I’ll need to fix in the tests themselves. After those are fixed, I’ll add `yarn test-prod` to the CI runs.

```
Test Suites: 17 failed, 104 passed, 121 total
Tests:       41 failed, 26 skipped, 2489 passed, 2556 total
```

### CODE REVIEW

**Comment by bvaughn** [comment]
I see a couple of failures from `yarn test-prod` that I wouldn't expect to be related to this change, eg: "_should throw with non-object in the initial state property_"
```
    Expected value to be (using ===):
      "span"
    Received:
      "SPAN"
```
That's a bit odd though b'c you didn't even change [this line](https://github.com/gaearon/react/blob/6e34120074c8018ed8803f7a0a71c8e64d4325d2/packages/react/src/__tests__/ReactCoffeeScriptClass-test.coffee#L162) with the diff.

**Comment by bvaughn** [comment]
There's almost no differences between `scripts/jest/dev` and `scripts/jest/prod` except for `process.env.NODE_ENV` in `processor.js` and some lines in `test-framework-setup.js`.

I wonder if you considered using a `shared` folder for `config.js`, `environment.js`, `preprocessor.js`, `setup.js` to make maintenance easier later?

I know our team generally seems to be in favor of forking things but that still sits weirdly with me.

**Comment by bvaughn** [comment]
I think CI might be failing because you added `require('shared/ReactFeatureFlags').enableUserTimingAPI` to `ReactIncrementalPerf-test.js` and `packages/shared/ReactFeatureFlags.js` uses ES module imports?

**Comment by gaearon** [comment]
>I wonder if you considered using a shared folder for config.js, environment.js, preprocessor.js, setup.js to make maintenance easier later?

That was the plan per our earlier conversation in the chat—to unify shared parts after we know everything works (it doesn't yet). Thanks for reviewing!

**Comment by gaearon** [comment]
To clarify, the outstanding TODOs as I see them in the scope of this PR:

- [ ] Fix CI
- [ ] Fix remaining tests in PROD mode
- [ ] Remove duplication between configurations

**Comment by gaearon** [comment]
>I think CI might be failing because you added require('shared/ReactFeatureFlags').enableUserTimingAPI to ReactIncrementalPerf-test.js and packages/shared/ReactFeatureFlags.js uses ES module imports?

Can you expand on this? We override feature flags this way in a few other tests and it seems to work. `npm test` also passes locally.

**Comment by bvaughn** [comment]
> To clarify, the outstanding TODOs as I see them in the scope of this PR...

Those TODOs look good.

> Can you expand on this? We override feature flags this way in a few other tests and it seems to work.

Shoot. You're right. I was mistaken about that. ☹️  Sorry!

**Comment by gaearon** [comment]
Filed https://github.com/facebook/react/issues/11626 and https://github.com/facebook/react/issues/11618 as followups.

**Pull request merged**
