### PR TITLE
Chore/setup ci to run dev tools tests

### PR DESCRIPTION
**Pull request by ktfth**
## Summary

The solution is to setup ci for devtools test for every version of react.

## Test Plan

A change is made to build code without a inconsistence on check names on build.

### CODE REVIEW

**Comment by bvaughn** [comment]
Seems like something didn't work right on CI. Looks like most of the tests didn't run.

**Comment by ktfth** [comment]
Have some leads and clues to go on?

**Comment by ktfth** [comment]
@bvaughn any updates?

**Comment by workbee49** [comment]
Good

**Pull request closed without merging**
