### PR TITLE
Fix:- clarified Eslint message

### PR DESCRIPTION
**Pull request by Biki-das**
Kinda confusing the part where it is called `at the top level`, this seems a bit confusing, i have changed it to mean `outside of a function` .

### CODE REVIEW

**Comment by Biki-das** [comment]
cc @hoxyq @notEpsilon

**Review by hoxyq — COMMENTED** [review]
I am not sure about this one. Top level here is referring to top level of JavaScript module. I don't know if there is precise definition somewhere of what is "top level" for the module.

It is also used for other features, like [top level await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#top_level_await).

Even if it can be unclear to the user what top level is, the next sentence in this message is explaining where hooks can be called.

**Comment by Biki-das** [comment]
the `top level` in the context of a React function seems a bit confusing, anyways if you would like me to close this, will close this one.

**Comment by hoxyq** [comment]
> the `top level` in the context of a React function seems a bit confusing, anyways if you would like me to close this, will close this one.

What is React function? The error is about calling React hooks from the top level of JavaScript module,.

Calling from top level already implies that you are calling outside of any function, not only React function components or React hook functions.

**Comment by Biki-das** [comment]
hmm seems valid!

**Pull request closed without merging**
