### PR TITLE
Remove deprecated function from tests

### PR DESCRIPTION
**Pull request by apaatsio**
This has been deprecated since 2013 so it's about time to remove it.

### CODE REVIEW

**Comment by jimfb** [comment]
@zpao Looks like these are super easy to find+fix, so it might not be terrible to just break this.  On the other hand, we haven't warned for a release and there is no harm in leaving the code here.  Honestly, I don't care what we do here; do you have any thoughts/preferences?

**Comment by zpao** [comment]
Yea, we never actually respected the `@deprecated` in JSDocs, nice find :). We should warn for 15 but it would be safe to remove like this in 16.

So this is actually an interesting case and will need a slight bit more thought on the best way to do this since we need a different change to made for the 15-stable branch. This is totally fine to go into master as is so I'm going to accept but let's hold off on merging until we document the exact process (would hate for us to lose track of this)

**Comment by facebook-github-bot-5** [comment]
@apaatsio updated the pull request.

**Comment by gaearon** [comment]
Ping @zpao—what’s the solution here?

**Comment by zpao** [comment]
Do we expose reactComponentExpect publicly? I don't think we do, in which case we can probably actually just land this whenever. Otherwise we might want to do a separate PR to land first which adds the warning, then we can take that over to stable.

**Comment by spicyj** [comment]
We don't.

**Comment by gaearon** [comment]
Getting it in as it's not exposed.

**Pull request merged**
