### PR TITLE
Added unit test that would have caught the recent error code transform regression

### PR DESCRIPTION
**Pull request by bvaughn**
Added an automated test that would have caught the regression introduced with #11291 and fixed by #11350.

The new test verifies that this:
```js
invariant(condition, 'This is not a real error message.');
```

Gets transformed to this:
```js
!condition ? invariant(false, 'This is not a real error message.') : void 0;
```

Prior to #11291 it would not have been transformed (and so would have been slightly less efficient). After #11291 (with the regression) it would have failed with:
```js
+ !condition ? __DEV__ ? invariant(false, 'This is not a real error message.') : 'This is not a real error message.' : void 0;
```

### CODE REVIEW

**Comment by gaearon** [comment]
Tangential but one downside of more efficient code is now we exercise the argument calculation code path less in tests. Which means that if it throws with some unusual inputs we might not know now. Because we'll only get invariant when we test specifically for it failing.

On the other hand as far as I understand this was already happening as soon as a code was recorded anyway. 

Perhaps we should make an exception for tests and never wrap for them at all?

**Comment by gaearon** [comment]
While we're at it let's rename the test to match the transform new name?

**Comment by bvaughn** [comment]
> Perhaps we should make an exception for tests and never wrap for them at all?

In general, I dig this suggestion, but I'm not sure how we'd make it work with tests like `ReactDOMProduction` "_should throw with an error code in production_". The transform runs on the code _before_ the tests `beforeEach` hook sets the fake `NODE_ENV`.

I think we'd actually need to run against the production _build_ (eg `react-dom.production.min`) which sounds nicer than mocking `NODE_ENV` but I'm not sure how to accomplish it. Maybe we could circle back here as a follow up after chatting?

> While we're at it let's rename the test to match the transform new name?

Sure.

**Comment by gaearon** [comment]
Sounds good.

**Pull request merged**
