### PR TITLE
Fix typo 

### PR DESCRIPTION
**Pull request by mehmeteyupoglu**

### CODE REVIEW

**Comment by jstejada** [comment]
thanks for the contribution! however i don't thin this is a typo, i think the grammar here is correct

**Comment by shmuli9** [comment]
@jstejada you are mistaken. The grammar is incorrect

**Comment by mehmeteyupoglu** [comment]
Depending on the information given in the image, the word **element** takes the article **_an_**. Please consider this when handling the contribution.

REF: https://owl.purdue.edu/owl/general_writing/grammar/using_articles.html

2021-11-28_17h55_01

**Comment by jstejada** [comment]
my apologies, i misread the changes at first!

**Comment by bvaughn** [comment]
Thank you for taking the time to post this PR 🙇🏼 

Because of the high volume of PRs this project gets, we've decided to stop merging typo PRs unless the change is use-facing (aka in documentation). Thanks for understanding!

**Pull request closed without merging**
