### PR TITLE
hax to make jest fast

### PR DESCRIPTION
**Pull request by spicyj**
Turns out jest is _incredibly_ slow at resolving require paths like `require('fbjs/lib/foo')`. Like several milliseconds per require. Really adds up when all our files require `invariant` and `warning`. Here's a temporary hack to make things fast again.

Test Plan:
```
npm test src/renderers/shared/reconciler/__tests__/ReactCompositeComponent-test.js
```

has a self-proclaimed runtime of ~8 seconds now instead of ~35 seconds.

### CODE REVIEW

**Comment by zpao** [comment]
JFC @cpojer fix jest. This is ridiculous.

@spicyj - did you by chance test with iojs+jest@0.5 first?

**Comment by spicyj** [comment]
Didn't try. (Filing a jest issue as we type.)

**Comment by spicyj** [comment]
(Would like to land this to save myself minutes every day, despite my half-joking title.)

**Comment by zpao** [comment]
do it

**Comment by cpojer** [comment]
woah. thanks for digging into the slowness. How did you figure it out?

I'll investigate.

**Comment by spicyj** [comment]
printf debugging in HasteModuleLoader.

**Pull request merged**
