### PR TITLE
Update AUTHORS for 0.13

### PR DESCRIPTION
**Pull request by zpao**
Lots of updates! Wooooo!

I had to do some mapping so I'd like to get confirmation from people about what they would like for their name/email.

- [x] @ianobermiller - you have 2 emails in there now, I changed to use the personal one.
- [x] @amykyta - You commit(s) didn't have your name, so I used the one on your GitHub profile
- [ ] @jeffmo - you have a million email addresses now, still pointing at anafx one, but can change.
- [x] @graue - ditto
- [x] @steveluscher - ditto
- [ ] @kikyous - let me know if you would like a different name in there than "chen"
- [x] @chicoxyzzy - I pulled your name from your profile, let me know if you'd like something else
- [x] @Pouja - I pulled your name from your email address, let me know if that's ok
- [ ] @brafdlog - Let me know if you'd like a real name in there

### CODE REVIEW

**Comment by ianobermiller** [comment]
Personal one is good, thanks @zpao.

**Comment by steveluscher** [comment]
Steven Luscher <react@steveluscher.com>

**Comment by graue** [comment]
The oceanbase one is fine for me. What's .mailmap?

**Comment by zpao** [comment]
The .mailmap gets automatically used by `git shortlog`, which is what we use to generate the AUTHORS file (https://github.com/facebook/react/blob/master/scripts/authors)

**Comment by chicoxyzzy** [comment]
change my name to Sergey Rubanov please

**Comment by amykyta** [comment]
Alex Mykyta as my name is fine. Thank you @zpao.

**Comment by Pouja** [comment]
@zpao Yeah that is fine by me :)

**Comment by zpao** [comment]
Alright, calling it. We can do any other updates later.

**Pull request merged**
