### PR TITLE
avoid the phrase "key property"

### PR DESCRIPTION
**Pull request by matchu**
React components can be assigned a special property named `key`. Therefore, it's helpful to avoid the phrase "key property" unless you're talking about the `key` property :)

I'm not sold on the replacement phrase, though... I think it's solid, but two fancy words like "fundamental" and "invariant" next to each other just seem a bit unwelcoming xP then again, we're talking about some heavy technical stuff; if there aren't any lighter words that are equally precise, then these should probably stand.

### CODE REVIEW

**Comment by zpao** [comment]
Heh, sure. Thanks. Generally we try to use `prop` when talking about `key` but I can see this being a potentially confusing point.

**Comment by spicyj** [comment]
@zpao But `key` isn't a prop!

**Comment by matchu** [comment]
Yeah, when writing this I got a bit curious about what actually happens there. We pass it to the component in the same way that we pass props (in JSX anyway; not sure about the native JS API), but it probably doesn't get passed to the component as a prop, right? Is there an actual word for "things you pass to a component" versus "things that get passed to a component"?

Incidentally, I made it here because I was looking for documentation on what constitutes a valid key value (string, any object, etc). Do the docs cover that anywhere? Where in the API is key actually processed? Do the corresponding API docs talk about that special handling?

**Comment by matchu** [comment]
aaand I just now found https://facebook.github.io/react/docs/special-non-dom-attributes.html, so I'm guessing `key` is an attribute but not a prop? Should the `createElement` docs say that it accepts attributes rather than props?

**Comment by spicyj** [comment]
String. And iunno.

**Pull request merged**
