### PR TITLE
Improved for a better understanding

### PR DESCRIPTION
**Pull request by DanZeuss**
that code shouldn't name this parameter onchange. It is so confusing for a starter of ReactJs like me. It looks like that the onChange is an common event from props.

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`).
6. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
7. If you added or removed any tests, run `./scripts/fiber/record-tests` before submitting the pull request, and commit the resulting changes.
8. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

### CODE REVIEW

**Comment by gaearon** [comment]
Thanks for the PR, but I don't think this is an appropriate fix. Using `onChange` as a custom prop name is extremely common in React apps and third-party React components. Maybe we could fix it with a sentence in text?

**Comment by DanZeuss** [comment]
Hi @gaearon. Thank you for your feedback. I understand that it's extremely common in React apps, however, for those that are starting on it, it isn't clear and looks like that is a function/eventhandler from props. 

Someone did a question on [stackoverflow](http://stackoverflow.com/questions/41018261/what-is-the-purpose-of-this-props-onchange) as the same question I had on my mind while trying to understand that line of the code.

Please, just confirm to me to close this PR.

**Comment by gaearon** [comment]
I recognize the problem but I don’t agree it is a right solution. It wouldn’t help anyone reading similar code in the future (of which there is plenty). We should address the root of the problem, not a symptom.

>Please, just confirm to me to close this PR.

As I said earlier, can you try to rephrase or add some wording to the text instead? There is no need to close the PR. I think I explained above why changing the prop name doesn’t fix the underlying problem—it would be better to fix that instead.

**Comment by gaearon** [comment]
The underlying problem here is that we first show the new `TemperatureInput` with `this.props.onChange(e.target.value);` call, but we only show how it's used a few paragraphs below:

screen shot 2017-02-09 at 17 07 10

The proper fix would be either to reorder those sections (and change the text), or to add a comment to the source, or to add a sentence right after the first code snippet to clarify `onChange` gets specified in the second one.

**Comment by gaearon** [comment]
Yet another option is to add a step-by-step explainer, like https://github.com/facebook/react/pull/8346 did in another docs section.

**Comment by DanZeuss** [comment]
Thank you for your feedback @gaearon. I tried a new change. Please, take a look and let me know if I need to improve that. I'm still learning so, take it easy :D

**Comment by DanZeuss** [comment]
@gaearon please, let me know if it is something that you are looking for.

**Comment by gaearon** [comment]
Thanks for getting the ball rolling. I actually came back to this and tried to rewrite this in more detail.
I hope this helps!

**Pull request merged**
