### PR TITLE
Devtool: `$r` should contain `hooks` property when it is forwardRef or memo component

### PR DESCRIPTION
**Pull request by meowtec**
## Summary

When inspect using `$r`, `Memo(Component)` should have `hooks` property.

## Test Plan
Nothing

### CODE REVIEW

**Review by Archish27 — COMMENTED** [review]
LGTM 🚀

**Review by bvaughn — APPROVED** [review]
Seems good. Thanks 👍

**Review by bvaughn — APPROVED** [review]
Seems good. Thanks 👍

**Review by bvaughn — APPROVED** [review]
Seems good. Thanks 👍

**Review by bvaughn — APPROVED** [review]
Seems good. Thanks 👍

**Review by bvaughn — APPROVED** [review]
Seems good. Thanks 👍

**Comment by rickhanlonii** [comment]
Seems good. Thanks 👍

**Comment by bvaughn** [comment]
Get outta here Ricky

**Pull request merged**
