### PR TITLE
Translate thinking-in-react.md to Japanese

### PR DESCRIPTION
**Pull request by sottar**

### CODE REVIEW

**Comment by jimfb** [comment]
This seems reasonable, CLA required (https://code.facebook.com/cla).

**Comment by sottar** [comment]
@jimfb 
I guess I agreed CLA just after I received facebook-github-bot 19hours ago.
I want you to see my CLA account.

**Comment by zpao** [comment]
Thanks, looks like the CLA bot didn't followup correctly. I can see that the CLA is signed.

**Comment by sottar** [comment]
@zpao 
Thanks a lot !

**Pull request merged**
