### PR TITLE
15.6 - Add controlList to DOM property whitelist

### PR DESCRIPTION
**Pull request by nhunzaker**
Adds 331ef3ec913f867159b6178ef35f8a0b4472ab4f to the 15.6 branch.

`controlsList` is a new attribute for media elements:

- https://github.com/WICG/controls-list/blob/gh-pages/explainer.md
- https://developers.google.com/web/updates/2017/03/chrome-58-media-updates#controlslist

### CODE REVIEW

**Comment by gaearon** [comment]
We’ve mostly frozen 15.6 except for addons (which will get a 15.6 release a few days after the main release), but maybe @flarnie doesn’t mind taking it.

**Comment by nhunzaker** [comment]
Ah, no problem!

**Comment by flarnie** [comment]
Yea - I should have mentioned the timeline to you @nhunzaker. I started preparing the `15-dev` and `15-stable` branches yesterday to release from. I'm sure we'll quickly collect enough bug fixes for a 15.6.1 release, so whatever lands on `15.6-dev` can go into that.

**Comment by nhunzaker** [comment]
No problem at all. That sounds like a great plan.

**Comment by nhunzaker** [comment]
I'll close this out and send out a new PR in a bit.

**Pull request closed without merging**
