### PR TITLE
Update zh-CN docs.

### PR DESCRIPTION
**Pull request by iamchenxin**
To keep up with en docs.

### CODE REVIEW

**Comment by zpao** [comment]
Thanks! Heads up: we should have a number of changes coming up in the near future as we prepare for launching v0.14. So there will always be more translations to do if you're interested :)

**Comment by iamchenxin** [comment]
I'm learning React this week,it is absolutely right and elegance concept for internet.
May i shift the github pages(facebook.github.io/react) from Jekyll to react based page?
So that it will be a self-contained example for learning react and better for display multiple language ,and multi-language display will be more intuitively for someone like me not good at English.

**Comment by zpao** [comment]
We're going to do an overhaul of the underlying technology (and want to do it across our projects). Improving i18n support is very important for this (I have some in-progress work for that using Jekyll in #4633) which we may just use before switching underlying tech. I'd prefer you didn't do that yourself but would be interested to hear your thoughts.

**Comment by iamchenxin** [comment]
There is a thought .
Since all i18n source file are Markdown. may be there need some specification that force other i18n files "line to line corresponding " to en docs (do not modify <newline> in translation docs).
That will be fit for  Contrast Display for multi-language. like en vs ko (can be 100%  precisely displayed as unified or split ).
I will move to #4633 to comment.

**Pull request merged**
