### PR TITLE
Revert "Revert "Use `act()` in ReactFabric tests""

### PR DESCRIPTION
**Pull request by sujatakhadka111**
Reverts facebook/react#21840

### CODE REVIEW

**Comment by bvaughn** [comment]
@sujatakhadka111 Why? Some explanation is generally required for any PR, include reverts.

**Comment by yungsters** [comment]
@acdlite already re-landed these changes using `jest-react`.

**Comment by bvaughn** [comment]
So this PR can be closed?

**Comment by yungsters** [comment]
I think so…

**Comment by bvaughn** [comment]
Okay. Closing for now then unless I hear otherwise from @sujatakhadka111.

**Pull request closed without merging**
