### PR TITLE
Double compress using GCC

### PR DESCRIPTION
**Pull request by sebmarkbage**
Let's see what sizebot says about this.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
ffs

**Comment by acdlite** [comment]
Well there goes my theory that CircleCI would be more reliable than Paul's server :D  https://14437-10270250-gh.circle-artifacts.com/3/home/circleci/project/scripts/rollup/results.json

**Comment by sebmarkbage** [comment]
Locally it seems dom prod min CJS goes from 106606 -> 106547 (34083 -> 34006 gzip). Not much, but the question still remains if it's worth it due to any future feature flags we might add, and whether it impacts runtime perf.

**Comment by trueadm** [comment]
@sebmarkbage There's also the case that it will probably break the readability of the FB prod bundles. What do you they look like after? Also what impact is there on the bundle build times? It's already pretty slow.

**Comment by threepointone** [comment]
Closing since we're not doing this (Please reopen if I'm wrong)

**Comment by gaearon** [comment]
I think we could? If it saves size. Just need to compare the output manually.

**Comment by sebmarkbage** [comment]
We probably shouldn't do this for FB bundles since we expect a second pass by our bundler anyway and we already compromise if that one is not smart enough. Basically, we could solve it by compiling it again in FB infra. I guess the file size there is just noisy variables.

There's still an increase in the "react" package which is interesting to look at.

**Comment by threepointone** [comment]
omg 🤪

**Pull request closed without merging**
