### PR TITLE
Handle composition events in ChangeEventPlugin

### LINKED ISSUE #3926: Change event fires too much when inputing Chinese characters.
When I was trying this [example](https://jsfiddle.net/reactjs/n47gckhr/light/) from https://facebook.github.io/react/blog/2013/11/05/thinking-in-react.html, any Chinese characters inputted by Chinese pinyin input method would fire too many renders like:

screen shot 2015-05-21 at 14 04 36

Actually I would expect those not to fire before I confirm the Chinese character.

Then I tried another kind of input method - wubi input method, I got this:

screen shot 2015-05-21 at 14 17 15

It's weird too. So I did a test [in jQuery](http://jsbin.com/yepogahobo/1/edit?html,js,console,output):

screen shot 2015-05-21 at 14 05 12

Only after I press the space bar to confirm the character, the `keyup` event would fire.

I know it might be different between the implementation of jQuery `keyup` and react `onChange` , but I would expect the way how jQuery `keyup` handles Chinese characters instead of react's `onChange`.

### PR DESCRIPTION
**Pull request by yesmeck**
This PR attempts to fix #3926.

### CODE REVIEW

**Comment by yesmeck** [comment]
How can I make CI green?

**Comment by gaearon** [comment]
Please run `./scripts/fiber/record-tests` and add that to the commit.

**Comment by yesmeck** [comment]
Added.

**Comment by paranoidjk** [comment]
Any update？ can we get this merged?

**Comment by paranoidjk** [comment]
@yesmeck  There may be a problem.

On mobile device,  such as iphone, chinese IME, we have something call **Word prediction**
from https://en.wikipedia.org/wiki/Pinyin_input_method
> Word prediction (simplified Chinese: 联想; traditional Chinese: 聯想; pinyin: liánxiǎng; literally: "association") is a feature of an input method that attempts to guess the next series of characters that the user is attempting to enter. This feature is often used to refer to two different mechanisms that have similar functions.

so the events fire sequence will be：
compositionstart --> compositionupdate --> onChange --> compositionstart --> compositionupdate...

There will be no **compositionend** until the **Word prediction** is ended.

**Comment by johnnyshields** [comment]
Please merge this is affecting us as well.

**Comment by gaearon** [comment]
Thanks for the PR. It's not obvious to me whether this works or not.

I think we could take a fix like this if you can demonstrate you've done exhaustive testing of this. It's a pretty risky change though so I don't feel comfortable merging it.

Let's continue the discussion in https://github.com/facebook/react/issues/3926. If somebody can take ownership of this and demonstrate they've tested a wide range of cases, and also explain in detail *why* this solution works, maybe we can get it in.

**Pull request closed without merging**
