### PR TITLE
feat(docs): Add Table of Contents

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Included contents section for easy navigation.

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @aweary

**Comment by jamesgeorge007** [comment]
cc @aweary @gaearon

**Comment by jamesgeorge007** [comment]
cc @threepointone @trueadm

**Comment by threepointone** [comment]
Thanks for this, but the README file is already very short so it can be quickly glanced, with links to reactjs.org for more. I don't think we should add a TOC.

**Comment by jamesgeorge007** [comment]
@threepointone Just take the case of the [[react-native](https://github.com/facebook/react-native/blob/master/README.md) repo. It still has a TOC offering better navigation experience and I guess the same is applicable here as well.
Thoughts :thinking:

**Comment by threepointone** [comment]
Closing since I expressed how I think about it, but happy to revisit if this comes up again.

**Pull request closed without merging**
