### PR TITLE
Remove 'require' to fix an error message

### PR DESCRIPTION
**Pull request by CorainChicago**
using 'require' results in this error message: "Uncaught ReferenceError: require is not defined"

### CODE REVIEW

**Comment by blainekasten** [comment]
I don't understand how this would be fixing it. The code you changed is markdown, not actual runnable javascript.

**Comment by jimfb** [comment]
Yeah, this makes no sense, correct as-is.

**Comment by CorainChicago** [comment]
I tried the code out using the html from the tutorial, adding the needed
ReactDom.render code and it wouldn't render with the 'require' on line 20.

**Comment by CorainChicago** [comment]
While markdown, the code in a sample should run when cut and pasted into a
javascript file.  A code sample with an error is worse than none at all in
documentation.

"var ReactCSSTransitionGroup = require('react-addons-css-transition-group'
);"

The line of code raises an error in the Chrome console and stops the
component from rendering.  The code runs without the word 'require' and by
adding the needed ReactDOM.render works.

**Comment by jimfb** [comment]
Yeah, I wish we did a better job of making examples runnable directly in the browser.  However, that current code assumes you have a commonjs module system that provides a require function.  It's rather complex to setup (I had a teammate do it for me on my machine).

**Comment by jimfb** [comment]
Anyway, just removing the require token might avoid the error message, but it won't make it "work".

**Comment by CorainChicago** [comment]
That makes more sense, still annoying to look up animation in the
documentation and not find a full picture of how to implement it.  A
reference to needing a commonjs module system to implement the animation
somewhere on the page would be helpful (and maybe a link to docs on
commonjs too).

**Pull request closed without merging**
