### PR TITLE
Add link to docs for update function

### PR DESCRIPTION
**Pull request by dmnd**
This makes it easier to figure out where the docs live. 

Searching for `react-addons-update` also works, but this should make it easier for people that go to the source first.

### CODE REVIEW

**Comment by jimfb** [comment]
If we're going to do this, it seems like we should be consistent with doing it for all the addons.  But I'm not sure I understand who the target audience is, because anyone touching that code will almost certainly know where those docs are located.

@dmnd How did you run into this being an issue?

**Comment by dmnd** [comment]
A new engineer just started. He was trying to discover what this very generally named "`update`" function was doing. He [hyperclicked](https://atom.io/packages/js-hyperclick) the function, then the import, and eventually ended up at the declaration here, but there's no pointer to the docs. I figured others might find a link to the docs to be useful.

**Comment by jimfb** [comment]
Hmm.  I think I could be ok with it if we documented all the jump points (the most critical ones being the React core API, and all the addons).

**Comment by dmnd** [comment]
Ok @jimfb, I added links for all addons and all functions in the top-level API.

I skipped the component API because I don't think it's possible to hyperclick to those functions.

**Comment by facebook-github-bot-3** [comment]
@dmnd updated the pull request.

**Comment by jimfb** [comment]
Yeah, ok, seems fine.  Thanks!

**Pull request merged**
