### PR TITLE
Add a note about react classe name convention

### PR DESCRIPTION
**Pull request by AoDev**
I lost quite some time trying to figure out what was happening. No error in console and nothing showing up. Turns out it was only because of not using uppercase first letter for my classes names. So I'd like to add it in this tutorial as a note.

### CODE REVIEW

**Comment by spicyj** [comment]
Curious: Were you using JSX? Either way, I'd expect at least _some_ sort of error…

**Comment by AoDev** [comment]
Yes, I was using JSX. 

```
  <!-- The core React library -->
  <script src="http://fb.me/react-0.13.0.js"></script>
  <!-- In-browser JSX transformer, remove when pre-compiling JSX. -->
  <script src="http://fb.me/JSXTransformer-0.13.0.js"></script>
  <script type="text/jsx" src="/scripts/app.jsx"></script>
```

But I have this Mime Type error in the console though: 
```
Resource interpreted as Script but transferred with MIME type application/octet-stream: "http://localhost:8080/scripts/app.jsx"
```
I used node-static for the local server.

**Comment by zpao** [comment]
@spicyj I guess there wouldn't be an error if you write `<mycomponent>` because we just assume that's DOM now and innerHTML it. No more whitelist means we can't really warn about this :/.

**Comment by spicyj** [comment]
Wonder if there's a way to test if a browser understands a tag name.

**Comment by bloodyowl** [comment]
something like this might work

```javascript
let UnknownConstructor
if(typeof HTMLGenericElement !== "undefined") {
  // IE8
  UnknownConstructor = HTMLGenericElement
} else {
  UnknownConstructor = HTMLUnknownElement
}

var isKnownElement = (tagName) => {
  return !(document.createElement(tagName) instanceof UnknownConstructor)
}
```

**Comment by spicyj** [comment]
In any event, we can take this. Thanks for sending this in!

**Pull request merged**
