### PR TITLE
Add support for SVG stroke-linejoin prop

### PR DESCRIPTION
**Pull request by joaomilho**
This is related to #1657 .

### CODE REVIEW

**Comment by gustavoguichard** [comment]
+1

**Comment by scgilardi** [comment]
I'd appreciate having this merged as well.

**Comment by gaearon** [comment]
Thanks for the PR! Now that #5714 is merged, all attributes on SVG elements will be passed through as is, with no need for the whitelist. I'm closing but let me know if you still have problems with master.

**Comment by joaomilho** [comment]
Sure.

**Pull request closed without merging**
