### PR TITLE
Fix context warning with non-pure getChildContext

### LINKED ISSUE #3709: Spurious context warning when getChildContext isn't pure
@sahrens found a case where we had a component that was creating a new object each time getChildContext was called. This isn't optimal for performance because getChildContext is called for each render, but it looks like we're actually calling it *twice* for each render and warning if the two results aren't the same. This code

```
var Parent = React.createClass({
  childContextTypes: {
    x: React.PropTypes.number
  },
  getChildContext: function() {
    return {x: Math.random()};
  },
  render: function() {
    return <Child />;
  }
});

var Child = React.createClass({
  contextTypes: {
    x: React.PropTypes.number
  },
  render: function() {
    return <div>x: {this.context.x}</div>;
  }
});

React.render(<Parent />, document.body);
```

produces warnings like

```
Warning: owner-based and parent-based contexts differ (values: `0.9166603954508901` vs `0.3767729678656906`) for key (x) while mounting Child (see: http://fb.me/react-context-by-parent)
```

### PR DESCRIPTION
**Pull request by spicyj**
(Requesting merge to 0.13-stable.)

Fixes #3709.

### CODE REVIEW

**Comment by zpao** [comment]
lgtm, will let @jsfb do a review as well.

Let's not merge this until we're ready to ship a 0.13.3 (would like to keep the branch build ready, which is why I did 405346545ffdc066d00949e7602b2a73f14335db)

**Comment by jsfb** [comment]
It's a little hard for me to tell exactly why this is working/fixed, but it looks like there is a change in functionality here... Is ReactContext.current is getting merged when it wasn't before?  Have we thought through the ramifications of that?  Specifically, with regards to when the child warnings fire (or don't fire) based on the presence/value of a context variable?  Is that the only functionality change?

I'm not entirely convinced this is correct.  Might be worth running through it in person?

**Comment by spicyj** [comment]
No, the merge happened before too; here I split _processChildContext into _getValidatedChildContext and _mergeChildContext.

**Comment by jsfb** [comment]
It looks like before the context was just from the element: https://github.com/facebook/react/pull/3711/files#diff-2ee62d642502ef4bdc3a6b3d18cd4f99R807  Where/how was it being merged before?

Can you briefly describe why this works (ie. what did actually change)?

**Comment by jsfb** [comment]
Oh, no, you're right, there is a process context there.

**Comment by spicyj** [comment]
_processChildContext previously called getChildContext, then merged the result on top of its argument (which was either owner-based `this._currentElement._context` or parent-based `context`). mountComponent called _processChildContext directly as well as indirectly via _renderValidatedComponent, causing getChildContext to be called twice. Here, I call it once and use it when determining owner-based and parent-based context to pass down. Same for updates in _updateRenderedComponent.

**Comment by jsfb** [comment]
Ah, got it.  You're right, child context doesn't need to be called twice because it's part of the current component.  Duh; I was thinking about the wrong invocations of getChildContext.  Ok, lgtm.

**Comment by zpao** [comment]
Pulled in here: 80ea01d364b62542fb4c9a68863132642bd9dbc7

**Pull request closed without merging**
