### PR TITLE
[Docs] Community section

### PR DESCRIPTION
**Pull request by joecritch**
- A "Community" section has been created, to house both the previous "Support" section and "Community Resources" docs category
- Separates the concerns of *documentation* vs. *community*, with the primary goal of **cleaning up the docs nav** (See #1669)
- Old permalinks supported via `redirect_from` field
- **Note:** Recommended to merge #6090 first, so we get icons for external pages.

screen shot 2016-02-23 at 13 33 47

### CODE REVIEW

**Comment by yaycmyk** [comment]
I think the nav title should be "Community & Help" - I wouldn't looked to "Community" for support-related stuff as a first instinct.

**Comment by joecritch** [comment]
I personally disagree, as 'Community & Help' signifies that the help wouldn't be coming from the community. Also, FWIW, Ember.js has support inside of Community.

**Comment by yaycmyk** [comment]
I wouldn't consider Ember website the gold standard of information design.

**Comment by joecritch** [comment]
Me neither, but convention goes a long way.

**Comment by winkler1** [comment]
Community is one word like all the other heading in that section, seems like a good thing..

**Comment by joecritch** [comment]
Added a "More From Facebook" category, similar to "Complementary" on the Flux site. (I went with "More From Facebook" to distinguish against non-Facebook led projects)

screen shot 2016-02-24 at 23 23 18

**Comment by gaearon** [comment]
Thanks for the PR. I'm closing because we released new version of docs with a Community tab:
https://facebook.github.io/react/community/support.html

If you have ideas about improving it, please submit a PR against master and assign it to @lacker. Thanks!

**Pull request closed without merging**
