### PR TITLE
toggle consoleManagedByDevToolsDuringStrictMode flag for native

### PR DESCRIPTION
**Pull request by hoxyq**
## Summary

Stacked on https://github.com/facebook/react/pull/29873, please review only [the last commit](https://github.com/facebook/react/pull/29887/commits/7fba323a6f9e6245ea54d9f97cb888463564a637).

The stack
1. This diff
2. https://github.com/facebook/react/pull/29873
3. https://github.com/facebook/react/pull/29869
4. https://github.com/facebook/react/pull/29856

This enables `consoleManagedByDevToolsDuringStrictMode` flag for native.

> [!CAUTION]
> Only land this and sync the renderers for Native once React DevTools backend version is updated.

### CODE REVIEW

**Comment by hoxyq** [comment]
@yungsters Could you please help me clarifying something?

1. Is [this](https://github.com/facebook/react/pull/29887/commits/7fba323a6f9e6245ea54d9f97cb888463564a637) the right configuration, so that the flag will be enabled with the next renderers sync for 0.75?
2. Will we be able to remove the corresponding gk for it after this PR lands and we sync renderers for Native?

Screenshot 2024-06-13 at 15 55 26

**Review by rickhanlonii — APPROVED** [review]
🎉

**Comment by hoxyq** [comment]
Looks like this flag [was enabled](https://github.com/facebook/react/pull/29903) for OSS renderers, and we still rely on gk for internal one.

Then I would change the approach, we can gradually roll out the internal gk, and then move the flag from the list of dynamic ones to the static, with a default value of `true`. Then we can remove the gk and everything else related.

cc @yungsters Is my thinking correct?

**Comment by yungsters** [comment]
> Then I would change the approach, we can gradually roll out the internal gk, and then move the flag from the list of dynamic ones to the static, with a default value of `true`. Then we can remove the gk and everything else related.

Yes, that is correct. Thanks, @hoxyq.

**Comment by hoxyq** [comment]
`consoleManagedByDevToolsDuringStrictMode` has been rolled out and removed in https://github.com/facebook/react/pull/31755.

**Pull request closed without merging**
