### PR TITLE
Listen to encrypted event, not onencrypted

### PR DESCRIPTION
**Pull request by zpao**
Followup to #4370

### CODE REVIEW

**Comment by spicyj** [comment]
topEncrypted please.

**Comment by zpao** [comment]
Left unsorted because there were more changes to make. Will followup with a sort later.

Now as @jimfb mentioned in another place, MDN does list a `onencrypted` and `encrypted` as event names. That's dumb. Let's support the one that makes sense.

**Comment by jimfb** [comment]
@zpao I think they serve subtly different functions?  Furthermore, `encrypted` is experimental and onEncrypted is the standard/supported one.

**Comment by spicyj** [comment]
@jimfb Where do you get that?

**Comment by jimfb** [comment]
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events

**Comment by zpao** [comment]
Just tested Firefox (Nightly, v42) and Chrome (beta, v44) on http://testdrive-eme.azurewebsites.net/ (thanks @patrickkettner!). `addEventListener('encrypted')` worked and fired events. `addEventListener('onencrypted')` did not. That matches the spec. I'm going to move forward with this as is now.

**Pull request merged**
