### PR TITLE
Fix website font flicker

### PR DESCRIPTION
**Pull request by bvaughn**
I tried moving the TypeKit tag from the bottom of the `<body>` to the `<head>` but this didn't resolve the flicker. According to [the docs](https://helpx.adobe.com/typekit/using/embed-codes.html) this is actually expected. TBH this flicker existed on the legacy site as well so I'm not sure how high-priority it is but it _is_ annoying.

So I'm now leaning towards removing TypeKit entirely and just using `sans-serif` font. Joe is going to circle back to this tomorrow and try out some other fonts that don't require using TypeKit (eg San Francisco). I think we could merge this PR for now (to remove the flicker) and then merge his later (to make things look better).

Netlify preview: https://59ce854bdf99532e00fdf5d0--reactjs.netlify.com/

cc @vjeux

### CODE REVIEW

**Comment by bvaughn** [comment]
This doesn't seem to have fixed the font-flicker. I believe it's caused by the `async` option.

https://helpx.adobe.com/typekit/using/embed-codes.html

> Adding the CSS to the page asynchronously can introduce a flash of unstyled text (FOUT) text while fonts are loading, though. Most browsers do a good job of hiding the FOUT by default, and any remaining issues can be controlled using font events once the script has finished loading and executing.

> If you would prefer to have the page wait for the fonts from Typekit to be available, you can use the <script> tag to block the page render and prevent any chance of FOUT; remove the {async: true} option or set it to false.

This doesn't seem like a great solution either TBH. I'm leaning towards removing TypeKit entirely. I wanted to do this already 😄

**Comment by bvaughn** [comment]
I'm going to take a stab at removing TypeKit for now. Joe will probably take a stab at doing this better but I'll at least get it started. 😄

**Comment by KyleAMathews** [comment]
https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/ is a pretty popular setup.

**Comment by KyleAMathews** [comment]
Removing custom fonts plus blocking scripts in the `<head>` would probably drop the Speed Index by at least 500ms http://www.webpagetest.org/result/170929_H4_ecb8e1a242c834ae6306f0f675c5bf81/3/details/#waterfall_view_step1

**Comment by bvaughn** [comment]
Closing in favor of #10988 😄

**Comment by bvaughn** [comment]
> Removing custom fonts plus blocking scripts in the <head> would probably drop the Speed Index by at least 500ms 

FWIW I filed a follow up issue earlier about removing Babel from the head and lazy-loading it only when needed.

**Pull request closed without merging**
