### PR TITLE
Fix for #6275

### PR DESCRIPTION
**Pull request by troydemonbreun**
Fix for #6275 - Add warning for onFocusIn and onFocusOut.

### CODE REVIEW

**Comment by troydemonbreun** [comment]
Sorry for the commit noise.  It's really only 2 files changed. Had another proposed fix in my master and it was unintentionally pulled into my branch.

**Comment by sarbbottam** [comment]
@troydemonbreun you might want to update your `git config user.name` and `git config user.email`, the commits are being credited to [www](https://github.com/www)

**Comment by troydemonbreun** [comment]
@sarbbottam Ah, that is the issue.  Goggled the "www" and found no answer why my Github Desktop commits were all www. Mystery solved, thanks!

**Comment by troydemonbreun** [comment]
@sarbbottam Ah, that is the issue.  Goggled the "www" and found no answer why my Github Desktop commits were all www. Mystery solved, thanks!

**Comment by troydemonbreun** [comment]
@sarbbottam Ah, that is the issue.  Goggled the "www" and found no answer why my Github Desktop commits were all www. Mystery solved, thanks!

**Comment by troydemonbreun** [comment]
@sarbbottam Thanks, for some reason Github Desktop is not updating my git config, even though I updated it in the UI.  I'll go to shell to check it.

**Pull request closed without merging**
