### PR TITLE
Feat:- Inspect react devtools keyboard shortcut added for chrome

### PR DESCRIPTION
**Pull request by Biki-das**
While Tinkering with the Devtools, i sort of come out with this shortcut key command to inspect react dev tools element directly, cmd/ctrl +shift+x works , on pressing it activates the inspect mode and on pressing again it deactivates the same!
This can come very handy while working with dev tools!

Demo below!

https://github.com/facebook/react/assets/72331432/af579c82-ec74-463a-9d5c-869a486a75a8

### CODE REVIEW

**Comment by Biki-das** [comment]
thoughts @hoxyq! I am pretty excited to see this landing!!

**Comment by hoxyq** [comment]
Hey, thanks for working on this!

Q1: When I am inspecting via shortcut and clicking on some element, will this open the DevTools "Components" tab?
Q2: If not, the main use case here is to inspect names of the highlighted components only?

If we want to use it as a separate way to inspect React components, this feature should work same way as it works with current implementation.

**Comment by Biki-das** [comment]
> Hey, thanks for working on this!
> 
> Q1: When I am inspecting via shortcut and clicking on some element, will this open the DevTools "Components" tab? Q2: If not, the main use case here is to inspect names of the highlighted components only?
> 
> If we want to use it as a separate way to inspect React components, this feature should work same way as it works with current implementation.

@hoxyq to answer you actually gave me a right direction , this does not currently open the component tab, and we should make it that way, this would then complete the functionality!

**Comment by Biki-das** [comment]
@hoxyq 

> Hey, thanks for working on this!
> 
> Q1: When I am inspecting via shortcut and clicking on some element, will this open the DevTools "Components" tab? Q2: If not, the main use case here is to inspect names of the highlighted components only?
> 
> If we want to use it as a separate way to inspect React components, this feature should work same way as it works with current implementation.

@hoxyq currently upon clicking the component from the inpsect option list it opens the react tree components and then we need to select the inspect button to select it, this one just adds a small keyboard component which would help to activate the inspector tool!

https://github.com/facebook/react/assets/72331432/59c60ccf-be2f-4fb2-85ae-41350beb4382

**Comment by Biki-das** [comment]
@hoxyq ping!

**Comment by hoxyq** [comment]
> @hoxyq
> 
> > Hey, thanks for working on this!
> > Q1: When I am inspecting via shortcut and clicking on some element, will this open the DevTools "Components" tab? Q2: If not, the main use case here is to inspect names of the highlighted components only?
> > If we want to use it as a separate way to inspect React components, this feature should work same way as it works with current implementation.
> 
> @hoxyq currently upon clicking the component from the inpsect option list it opens the react tree components and then we need to select the inspect button to select it, this one just adds a small keyboard component which would help to activate the inspector tool!
> 
>  Untitled.mp4

To add this small feature, we need to make quite some changes in code, and specifically these:
https://github.com/facebook/react/blob/f44c40dcf67c6f39fa544062de8be4f70f0fefe0/packages/react-devtools-shared/src/backend/views/Highlighter/index.js#L37-L38

I don't think we should do it this way, but at the same time I understand that current architecture of the extension will not allow us to make it in some easy way. 

It's just number of changes (and potential drawbacks from them) outweighs the proposed feature.

If you are looking for some other ways on how to contribute to DevTools, I can work on putting up a list of things you can work on, but I will need to invest some time for it.

**Comment by hoxyq** [comment]
> > > @hoxyq
> > > > Hey, thanks for working on this!
> > > > Q1: When I am inspecting via shortcut and clicking on some element, will this open the DevTools "Components" tab? Q2: If not, the main use case here is to inspect names of the highlighted components only?
> > > > If we want to use it as a separate way to inspect React components, this feature should work same way as it works with current implementation.
> > > 
> > > 
> > > @hoxyq currently upon clicking the component from the inpsect option list it opens the react tree components and then we need to select the inspect button to select it, this one just adds a small keyboard component which would help to activate the inspector tool!
> > > Untitled.mp4
> > 
> > 
> > To add this small feature, we need to make quite some changes in code, and specifically these:
> > https://github.com/facebook/react/blob/f44c40dcf67c6f39fa544062de8be4f70f0fefe0/packages/react-devtools-shared/src/backend/views/Highlighter/index.js#L37-L38
> > 
> > I don't think we should do it this way, but at the same time I understand that current architecture of the extension will not allow us to make it in some easy way.
> > It's just number of changes (and potential drawbacks from them) outweighs the proposed feature.
> > If you are looking for some other ways on how to contribute to DevTools, I can work on putting up a list of things you can work on, but I will need to invest some time for it.
> 
> @hoxyq i got you! but what's exactly the problem with this solution? backwards compatibility or future code changes would be hard to make in?

The biggest problem here is the way how we expose methods `startInspectingNative` & `stopInspectingNative` with `agent`. IMO, right way here is to have some event-based model, exactly how `agent` works. I am not sure if this can be implemented with the way how `Highlighter` feature works now, maybe some decent amount of refactoring will be needed.

**Comment by Biki-das** [comment]
> > > > @hoxyq
> > > > > Hey, thanks for working on this!
> > > > > Q1: When I am inspecting via shortcut and clicking on some element, will this open the DevTools "Components" tab? Q2: If not, the main use case here is to inspect names of the highlighted components only?
> > > > > If we want to use it as a separate way to inspect React components, this feature should work same way as it works with current implementation.
> > > > 
> > > > 
> > > > @hoxyq currently upon clicking the component from the inpsect option list it opens the react tree components and then we need to select the inspect button to select it, this one just adds a small keyboard component which would help to activate the inspector tool!
> > > > Untitled.mp4
> > > 
> > > 
> > > To add this small feature, we need to make quite some changes in code, and specifically these:
> > > https://github.com/facebook/react/blob/f44c40dcf67c6f39fa544062de8be4f70f0fefe0/packages/react-devtools-shared/src/backend/views/Highlighter/index.js#L37-L38
> > > 
> > > I don't think we should do it this way, but at the same time I understand that current architecture of the extension will not allow us to make it in some easy way.
> > > It's just number of changes (and potential drawbacks from them) outweighs the proposed feature.
> > > If you are looking for some other ways on how to contribute to DevTools, I can work on putting up a list of things you can work on, but I will need to invest some time for it.
> > 
> > 
> > @hoxyq i got you! but what's exactly the problem with this solution? backwards compatibility or future code changes would be hard to make in?
> 
> The biggest problem here is the way how we expose methods `startInspectingNative` & `stopInspectingNative` with `agent`. IMO, right way here is to have some event-based model, exactly how `agent` works. I am not sure if this can be implemented with the way how `Highlighter` feature works now, maybe some decent amount of refactoring will be needed.

Got you!

**Comment by Biki-das** [comment]
looking forward to help as you said , you could put forward something i can help with :-)

**Comment by hoxyq** [comment]
> looking forward to help as you said , you could put forward something i can help with :-)

Awesome, thanks. I will work on it this week and will return with more details / plans probably next one.

**Pull request closed without merging**
