### PR TITLE
Remove the Mixin layer of indirection on ReactMultiChild

### PR DESCRIPTION
**Pull request by vjeux**
As mentioned in https://github.com/facebook/react/pull/7581#issuecomment-242952042 we can remove the Mixin layer of indirection as it only exports a Mixin and I find it confusing.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
You'll need to update ReactART in its repo too: https://github.com/reactjs/react-art/blob/master/src/ReactART.js#L96

**Comment by gaearon** [comment]
What is the plan for ReactART? Now that we moved it here, do we just copy stuff into the separate repo once in a while?

**Comment by spicyj** [comment]
The copy here is only for backwards-compat unit tests. The other repo is the source of truth.

**Comment by spicyj** [comment]
Also, this is not semver-exempt because it breaks react-art. It should be major.

**Comment by spicyj** [comment]
(When you need to change the copy of ReactART in this repo to make tests pass, it's a major change.)

**Comment by gaearon** [comment]
Oh, okay, sorry.
Isn’t the plan to release ReactART that contains a reconciler copy in the next version, like RN?

**Comment by spicyj** [comment]
That's probably a good idea but someone needs to make it happen. :)

**Comment by sebmarkbage** [comment]
The way it works now, it is integrated with the DOM renderer. It will simply move its dependency to `react-dom/lib`. When we move it to fiber it'll get its fully own renderer though.

**Pull request merged**
