### PR TITLE
Remove "construct" call except on composites

### PR DESCRIPTION
**Pull request by spicyj**
This is a little simpler (and a teeny tiny bit faster). The one in ReactCompositeComponent stays because of the way we create ReactCompositeComponentWrapper inside instantiateReactComponent.

### CODE REVIEW

**Comment by RoyMontoya** [comment]
nice fix, constructing the componentWrapper object inside ReactCompositeComponentWrapper makes way more sense than initializing it as an empty object and return it to instantiateReactComponent and call construct from there.

this line was hard to relate to the componentWrapper without debugging it
instance.construct(node);

**Comment by sebmarkbage** [comment]
Fix ART etc. if needed.

**Comment by jimfb** [comment]
Ping @spicyj

**Comment by jimfb** [comment]
Ping @spicyj - deadline is getting awfully close if we want this in the 0.15 milestone.

**Pull request merged**
