### PR TITLE
ensure tags are upperCase before comparing. #4388

### LINKED ISSUE #4388: Unexpected behavior of `findRenderedDOMComponentWithTag` in React 0.14-beta1
After migrating from 0.13 to 0.14-beta1, some of our unit tests are reporting false positive failures. It seems as though `findRenderedDOMComponentWithTag` is no longer able to find elements inside components.

```javascript
// Create simple component
const test = React.createClass({
	render: () => {
		return <div><svg /></div>;
	}
});

// Render into document
const MyElement = ReactTestUtils.renderIntoDocument(<test />);

// Make sure component has an SVG element
const svg = ReactTestUtils.findRenderedDOMComponentWithTag(MyElement, 'svg');
// OOPS! This fails in 0.14 with:
// > Did not find exactly one match for tag:svg

// However, this works just fine
console.log(findDOMNode(MyElement).childNodes[0]);
// => Returns "<svg/>" element
```

### PR DESCRIPTION
**Pull request by dmatteo**
Fix #4388 where `svg` was lower case

### CODE REVIEW

**Comment by zpao** [comment]
Does casing matter for any SVG tags? I vaguely recall something about that but not sure.

**Comment by dmatteo** [comment]
I've tried searching through W3 docs but I couldn't find any reference to this.

The only mention I found is about SVG properties: http://www.w3.org/TR/SVG/styling.html#CaseSensitivity

**Comment by zpao** [comment]
I played around a bit more and it's definitely the case that SVG elements have case sensitive tagNames (eg `linearGradient`) but perhaps we don't really care and this is *ok* (even if not perfect). Any opinions @spicyj?

**Comment by spicyj** [comment]
I think this change is good. @sebmarkbage said that e.g., `<lineargradient>` in your HTML is valid.

**Comment by zpao** [comment]
Ok cool, merging then. Thanks @dmatteo!

**Comment by dmatteo** [comment]
Cool, thanks.

See you guys

**Pull request merged**
