### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by TheAPratap**
Small changes to the README.md

Screenshot 2022-09-02 at 12 05 53 AM

### CODE REVIEW

**Comment by TheAPratap** [comment]
CLA signed

**Comment by TheAPratap** [comment]
#CLASigned

**Comment by TheAPratap** [comment]
CLA Signed

**Comment by TheAPratap** [comment]
@facebook-github-bot CLA Signed

**Comment by eps1lon** [comment]
Since these are all subjective nits that don't seem to alter or clarify the original meaning, I'm going to close. But thanks for your suggestions.

**Pull request closed without merging**
