### PR TITLE
Show full path for location of error

### LINKED ISSUE #11519: Consider including directory name into the stack trace for some files
See https://twitter.com/deadcoder0904/status/929050109425229824

Maybe if the file is called `index.js` (pretty common with some directory structures) we should include the directory name into the short component stack trace.

### PR DESCRIPTION
**Pull request by xjlim**
Fix #11519

### CODE REVIEW

**Comment by gaearon** [comment]
We can also try stripping shared common ancestor directory from all lines in the stack.

**Comment by xjlim** [comment]
image
@gaearon I tried removing the common head of the files in stacktrace, is this what you meant?

**Comment by xjlim** [comment]
Alternative is to include app's root directory in element.__source and stripping that off the filename but that require changing babel-plugin-transform-react-jsx-source.

**Comment by gaearon** [comment]
We can't reliably detect app directory since people run Babel in all sorts of configurations.

I think this is an interesting approach. I'm going to be away this week but I'll review when I get back.

**Comment by gaearon** [comment]
Sorry—we're stretched really thin and don't have the bandwidth for reviewing community PRs until much later this year 😞

**Comment by xjlim** [comment]
No worries. I should have followed up sooner.

**Pull request closed without merging**
