### PR TITLE
Warn that ReactPerf does not work in the production build

### PR DESCRIPTION
**Pull request by gaearon**
This takes #6884 and adds small stylistic changes on top.

### CODE REVIEW

**Comment by gaearon** [comment]
Ugh, I thought that would preserve @sashashakun as the commit author because all commits except the last one were his 😞

**Comment by gaearon** [comment]
Reverted so that we preserve original contributor as author.

**Comment by sashashakun** [comment]
@gaearon should i do one more commit?

**Comment by gaearon** [comment]
@sashashakun I merged it separately now, don’t worry 😄 . Thanks for contributing!

**Pull request merged**
