### PR TITLE
build: add exports field for useSES

### PR DESCRIPTION
**Pull request by huozhi**
## Summary

Add `exports` field to use-sync-external-store for usage in esm modules (.mjs).

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '...blabla/node_modules/use-sync-external-store/with-selector' imported from ...`
Did you mean to import use-sync-external-store/with-selector.js?
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:318:11)
    at moduleResolve (internal/modules/esm/resolve.js:776:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  type: 'NodeError',
  code: 'ERR_MODULE_NOT_FOUND'
}
```

## How did you test this change?

We added useESE in swr for react 18 support, and trying to test it with next.js, I got the above error when running `next build`. The reason seems because of `exports` field is missing in useESE that break the subpath imports

### CODE REVIEW

**Comment by huozhi** [comment]
Hi react folks, any idea which subpath exports is missing that lead to this error in test? Wanna get some hints to fix them

**Comment by huozhi** [comment]
cc @acdlite do you have any insights what's missing in the PR?

**Comment by gaearon** [comment]
There's an existing PR in https://github.com/facebook/react/pull/24440 so we should probably merge that one. But the author says it's a breaking change. Why is it?

**Comment by huozhi** [comment]
Thanks for referencing the existing one! I'm not sure the reason why is that. I can close this one and we continue the discussion there

**Pull request closed without merging**
