### PR TITLE
Adds a minimum indentation size for components with extremely long names.

### PR DESCRIPTION
**Pull request by coreyleelarson**
Fixes https://github.com/facebook/react/issues/16742

In extreme cases, components with names that exceed the DevTools window width cause the dynamic indentation calculation to equal 0, flattening the entire component hierarchy. When this happens, it is difficult to discern between parent, sibling, and child components. This PR adds a minimum indentation size to ensure the tree is still visually usable in extreme cases, while preserving the regular dynamic indentation functionality under normal circumstances.

**Before:**

before

**After:**

after

**Happy Path:**

normal

### CODE REVIEW

**Comment by bvaughn** [comment]
This doesn't look sufficient. Deep trees would expand horizontally past the viewport and leave unscrollable white space.

**Comment by coreyleelarson** [comment]
@bvaughn - You're absolutely right, I had not considered that scenario.

Removing the `.List { overflow-x: hidden !important }` seems to be the likely first step, however because `react-window` renders the container/elements with fixed widths and absolute positioning, the Active/Inactive background highlighting does not behave as desired.

 I'll have to think on this a bit when I've got more time.

Thanks for the feedback!

**Comment by bvaughn** [comment]
Another thing to keep in mind is that re-enabling horizontal scroll means that we would need to restore measuring on-mount and remembering the widest measured item so that horizontal scroll didn't grow-and-shrink-and-grow as you scrolled vertically. (That is a bad UX.)

Here's how we used to do this:
https://github.com/bvaughn/react-devtools-experimental/commit/49f6a22b5b8a1b7d5e2a774262357e2992ad0ca0#diff-483c2df20fea61bc9557723ea45b633b

**Comment by coreyleelarson** [comment]
Closing this pull request until I can rethink the implementation based on @bvaughn comments above. Wouldn't want this to be accidentally merged.

**Pull request closed without merging**
