### PR TITLE
Add unpkg field to support unpkg.com

### PR DESCRIPTION
**Pull request by porsager**
It would be great to be able to use react directly through https://unpkg.com/react

### CODE REVIEW

**Comment by MartinKolarik** [comment]
Would you also set a `jsdelivr` field for [jsDelivr CDN](https://www.jsdelivr.com/package/npm/react)? It's a similar service but built for production usage and react actually gets about 3x more requests there compared to unpkg.

**Comment by gaearon** [comment]
Please see the discussion in https://github.com/facebook/react/pull/10597.

While I agree a short URL would be nice, the fact that people can’t agree whether it should point to a development or a production version means some people will make a mistake either way. I don’t think savings to typing are worth losing explicitness for such an important difference.

**Comment by porsager** [comment]
Sorry, I tried searching for it, but didn't find any results. Thanks for taking the time pointing me to it.

**Comment by MartinKolarik** [comment]
@gaearon I understand the problem discussed in #10597 but I'm not sure if having a default that's wrong for *everyone* is better than having a default that might be wrong for *someone*.

Both jsdelivr and unpkg use `main` if there isn't a more specific field, and at jsdelivr we also use this field to hint the correct file at our website: https://www.jsdelivr.com/package/npm/react. We actually recommend always using full links and show the full file name, but we need to know which one that is (and it definitely isn't `main` in this case).

**Comment by porsager** [comment]
@gaearon I've had some time to check out the thread now as well, and I'd have to agree with @MartinKolarik that it's a pity not to have something that works in 99% of the cases, instead of having a barrier to entry by not making the easy option available. 

I know you wrote it's only 20 seconds more to type it, but that doesn't include having to look up where the full path is. I'd rather have the computer do that job for me ;)

In this case of react I understand your issue between choosing either the production / development, and you are probably the best to make that decision, but I think not choosing at all isn't the best solution either. 

I also didn't see that much lack of consensus in the other thread. So going with the dev build and adding a `jsdelivr` field as well would by the best solution in my opinion.

**Comment by gaearon** [comment]
>if having a default that's wrong for everyone is better than having a default that might be wrong for someone.

Why not? If the default is not working you will be forced to look at the file path and learn the difference between production and development versions. Especially since in React 16 they are called `.development.js` and `.production.min.js`. I think the “default” that is broken is exactly the right solution in this case because now you can’t avoid learning about it.

To mitigate the annoyance of seeing a file that’s not helpful at all, we can warn early in the `main` entry point if `module` is not available with a nice message. Then people who accidentally use it in the browser will know what to do. Would you like to make a PR for this?

**Comment by gaearon** [comment]
>I know you wrote it's only 20 seconds more to type it, but that doesn't include having to look up where the full path is. I'd rather have the computer do that job for me ;)

The computer can’t know which version you intend to use. With a history of embarrassingly large and popular sites shipping development version of React to production, we don’t want to make this mistake easier than it already is.

**Comment by MartinKolarik** [comment]
>Why not? If the default is not working you will be forced to look at the file path and learn the difference between production and development versions. Especially since in React 16 they are called .development.js and .production.min.js. I think the “default” that is broken is exactly the right solution in this case because now you can’t avoid learning about it.

I suppose you are right with regard to the short links without a file name, but as I mentioned before, jsDelivr uses this primarily to suggest the correct file [here](https://www.jsdelivr.com/package/npm/react). You can still see the file name there so it doesn't matter which version you would pick as default - some people would be able to use it right away, and the other would immediately know they need to look for something else. Compare that with the current situation, where `react.min.js` looks like the correct file and there's nothing indicating there's actually a separate development and a separate production version.

**Comment by gaearon** [comment]
I don't think we'll be adding any fields for specific CDNs like jsDelivr.

**Comment by porsager** [comment]
Yeah, I see your reasoning behind it, and it's commendable that you want to go that far in helping users make the right choice.

Your suggestion about a warning is a good idea. I'd love to do a pull request for that. Would you like it on the version 16 branch?

**Pull request closed without merging**
