### PR TITLE
Clarify dependency installation

### PR DESCRIPTION
**Pull request by applegrain**
- Split browserify and webpack to separate sections
- Remove `babelify` from the webpack section since it's only for browserify

### CODE REVIEW

**Comment by applegrain** [comment]
This PR is replacing https://github.com/facebook/react/pull/5648

**Comment by jimfb** [comment]
The "getting started" guide is intended to provide a minimal example to get the user off the ground, and the existing example already does that.  Providing too many examples/alternatives is just confusing, and makes the section too long.  That's my two cents.  cc @zpao for thoughts.

**Comment by zpao** [comment]
I like it, let's do it.

**Comment by zpao** [comment]
Thanks!

**Pull request merged**
