### PR TITLE
[fiber-debugger] Fix the debugger to match changes to Fiber

### PR DESCRIPTION
**Pull request by pomber**
[`formatPriority`](https://github.com/facebook/react/blob/master/fixtures/fiber-debugger/src/Fibers.js#L253) was throwing "Unknown priority." when `fiber.progressedPriority` is undefined (which happens as soon as you run the app).

```
Uncaught Error: Unknown priority.
    at formatPriority (Fibers.js:253)
    at Fibers.js:317
    at Array.map (<anonymous>)
    at Fibers (Fibers.js:282)
    at mountIndeterminateComponent (react-dom.development.js:9774)
    at beginWork (react-dom.development.js:9972)
    at performUnitOfWork (react-dom.development.js:11932)
    at workLoop (react-dom.development.js:12042)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1304)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:1343)
```

### CODE REVIEW

**Comment by gaearon** [comment]
I think you can just remove it along with other fields that don't exist anymore on ReactFiber type (you can open its file and check). There's a bunch that were removed but still exist in debugger. That confuses it.

**Comment by pomber** [comment]
Oh, I didn't realize that the property was gone. I'll play with the debugger during the weekend, I'll update the PR then.

**Comment by gaearon** [comment]
Might also want to change `describeFibers`.

**Comment by pomber** [comment]
I removed `progressedChild`, `progressedFirstDeletion `and `progressedLastDeletion `from `decribeFibers`. Did I miss anything else?

**Comment by gaearon** [comment]
Thanks.

**Pull request merged**
