### PR TITLE
Add Lane labels to scheduling profiler marks

### LINKED ISSUE #20767: Scheduling profiler: Unrecognized event type from Chrome Canary
Importing a profile recorded with Chrome Canary (v90) triggers this error check code:
https://github.com/facebook/react/blob/6c526c5153bc350d2a62c7dcbc698be77d3f2439/packages/react-devtools-scheduling-profiler/src/import-worker/preprocessData.js#L371-L378

Here's one such example event:
```json
{
  "args": {},
  "cat": "blink.user_timing",
  "name": "requestStart",
  "ph": "I",
  "pid": 64032,
  "s": "t",
  "tid": 775,
  "ts": 25788659448
}
```

Looks like there's at least one new type, "I", which I assume will eventually affect Chrome stable (currently v88).

### PR DESCRIPTION
**Pull request by bvaughn**
This PR is for discussion purposes. The suggestion was from ad hoc user feedback from Rick.

This PR changes profiler marks from a format like `"--schedule-render-1"` to `"--schedule-render-1-Sync"` which will enable the profiler itself to show more meaningful labels for updates and render work.

There are a couple of downsides to this proposed change:
1. It requires maintaining a map of bitmask range to string/label in `ReactFiberLane`. Hopefully not a huge burden but something we would need to remember to keep in sync.
2. It increases the size of User Timing data logged by the profiler during render. (I don't think there's a way around this since there's no initialization event where we can log a standalone mapping). Perhaps we could log a mapping with each commit or something but that doesn't seem like an obvious improvement.

This PR also refactors and cleans up a few of the scheduling profiler tests to rely less on hard-coded data and formats and verify the current source code behavior.

---

This PR also resolves #20767. I just fixed it while I was in there testing.

### CODE REVIEW

**Comment by bvaughn** [comment]
The main thing I wish I could do here was write a test using external React APIs that scheduled work in each lane so that I could have snapshots that remind us to update the lane-to-label function whenever we change the lanes too. Not sure if that's possible though really.

**Comment by bvaughn** [comment]
Okay I think this is ready for initial review/feedback.

Specifically I'm wondering if the new regression test seems okay and worth doing. If so I'll add a few more lane types to it.

**Comment by bvaughn** [comment]
Ping @acdlite @rickhanlonii for review :)

**Review by rickhanlonii — APPROVED** [review]
Changes look good and @bvaughn confirmed offline that @acdlite is cool with exposing lane names here.

**Comment by bvaughn** [comment]
Thanks for the review Rick.

**Comment by bvaughn** [comment]
I'm going to do a cleanup pas here for some related tests (like the `preprocessorData-test`)

**Comment by anumthapa** [comment]
Va noita ko humxa hou

**Comment by bvaughn** [comment]
Here's how the new labels will be surfaced in the UI. Seems like a nice improvement over what it showed previous.

Screen Shot 2021-02-23 at 10 28 55 AM

Screen Shot 2021-02-23 at 10 29 21 AM

**Comment by bvaughn** [comment]
Okay. I think I'm done pushing tweaks to this branch now. Just updated it one more time so it supports the older profile JSON format too (the one without labels). Once CI is done, I'll merge and deploy the update.

**Comment by bvaughn** [comment]
Uh.... weird. I `git push` an update here and the PR got closed.

**Comment by bvaughn** [comment]
The one failing CI task is a false positive b'c master danger stats were broken on the latest commit.

**Pull request merged**
