### PR TITLE
Using https URLs for embedded fiddles

### PR DESCRIPTION
**Pull request by cody**
Official announcement from jsfiddle:
https://twitter.com/jsfiddle/status/565041134435852289

### CODE REVIEW

**Comment by jsfb** [comment]
@cody Thanks for helping move this forward!  Looks good.

> the Result tab is empty, because the external resources for the fiddles work only with http. So I guess facebook needs to update the fiddles first and then the docs can get changed to https. (https://github.com/facebook/react/issues/3153)

As per above, **we may want to update the fiddles (and potentially the CDN) before merging this**.  But this moves us in the right direction.  One potential issue is that the fb.me url does support https, but redirects to FBCDN which does not support https (yet/ever?).  We really should move react to a secure CDN, but that's a longer / more-involved task and probably won't happen over night.  Until we're hosting React on a secure CDN, my guess is that the empty results will remain an issue on https.  Having said all that, if we're only using jsfiddle to embed code snippets (ie. we don't care about the renderable results on jsfiddle), than I see no reason this commit can't be merged immediately (even before the fiddle and CDN are updated).  @zpao, thoughts?  Would it make sense to switch the fb.me urls to point to a copy of react on facebook.github.io instead of the http-only fbcdn?  Or would it make more sense to get fbcdn fixed?  Regardless, we really shouldn't be serving javascript code over an insecure connection anyway.

The `//` prefix is intended for resources that need to be loaded using both protocols.  For instance, if we were developing a service that needed to run in an https production environment and an http development environment.  In this case, we are only hitting the production jsfiddle (even when the site is served from localhost/dev), and the production jsfiddle does now support https.  For this reason, the prefix should be `https://` instead of `//`.  I would request that we update the PR now (to use `https://` instead of `//`), except that we still have the issue of FBCDN serving over http and thus such a change might cause the results tab to fail rendering when it would have succeeded over http.

@vjeux, looks like you own the fiddles.  Can you update them to point to the HTTPS versions of the domains? (they should all already exist).

**Comment by jsfb** [comment]
Having said all that, and having thought about it for a couple more minutes, I think my vote would be to merge this pull request immediately (since it makes things strictly better), and file a new issue to have these urls updated to `https://` instead of `//` once the fiddles (and potential CDN issue) are resolved.

That said, I'll let @zpao or @spicyj sanity check this idea, in case I'm missing a subtlety here.

**Comment by zpao** [comment]
We can update the fiddles owned by reactjs (which is us) and @vjeux's to use cdnjs over https, but not most of the others.

So now that I've thought about it a little bit more and seen the extent of the embeds, I think we should just focus on ours and leave the rest alone. We already left the "thinking in react" blog post with the old embeds and only updated the more permanent docs page.

Also, I guess I was wrong about the `//` vs just using `https`, so let's do that. And then let's also update the links on "getting started" (in Chinese too) so those go to `https` (might as well).

**Comment by cody** [comment]
I have updated it to use `https`, just in case this is useful.

**Pull request merged**
