### PR TITLE
Remove mocks that are already packaged by InitializeJavaScriptAppEngine

### PR DESCRIPTION
**Pull request by javache**
* Remove non-React specific requires from ReactNativeDefaultInjection.
* Make ReactNativeEventEmitter do it's own registration with BatchedBridge, so `ReactNative` can set up all of its dependencies on its own.

When syncing this down to react-native, I'll need to remove RCTEventEmitter so we don't register this module twice.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
I would like to keep the surface area that we expose to React as minimal as possible. E.g. UIManager, FocusState. Would you mind creating an indirection like `ReactNativeEvent.listen()` or something? I just don't want to take on all of BatchedBridge if that makes sense.

**Comment by javache** [comment]
Could you go in a bit more detail of what `ReactNativeEvent.listen` would look like? Or do you mean something like moving the `BatchedBridge.register` call to something like `RCTEventEmitter.register(ReactNativeEventEmitter)`, where we keep the `RCTEventEmitter` mock in react and provide the implementation in react-native?

**Comment by sebmarkbage** [comment]
Yea. That would work. I just want to make sure that people submitting PRs to React Core realize that all of BatchedBridge is not available.

Basically this is the equivalent of adding eventlisteners in document.body and we have an opportunity to unify these if we don't take on too many more dependencies.

**Comment by javache** [comment]
We could further simplify this and have one bridging module/interface for both UIManager and other callable module configuration, but it seems cleaner to split them out by area for now.

**Comment by facebook-github-bot-1** [comment]
@javache updated the pull request.

**Comment by facebook-github-bot-0** [comment]
@javache updated the pull request.

**Pull request merged**
