### PR TITLE
Remove unnecessary type cast

### PR DESCRIPTION
**Pull request by eps1lon**
## Summary
<details>
<summary>Increases type coverage from 82.50% to 82.66% :muscle: ... </summary>

... just because we got rid of one expression.

```bash
$ git checkout master
$ npx flow coverage packages/react-dom/src/client/ReactDOMLegacy.js
Covered: 82.50% (429 of 520 expressions)

$ git checkout eps1lon/chore/root-coverage
$ npx flow coverage packages/react-dom/src/client/ReactDOMLegacy.js 
Covered: 82.66% (429 of 519 expressions)
```
</details>

TODO comment was added in 1b55ad2a4b24b06ce34f77a943396228641d74a1. The flow bug was likely fixed during an update to flow since the type didn't change in the meantime.

## Test Plan

- [x] CI green

### CODE REVIEW

**Comment by eps1lon** [comment]
Same failures reported on `master`

**Comment by eps1lon** [comment]
This PR should be good but I don't think there's a point in me trying to get `master` into a better shape.

Even with a naive 

```diff
diff --git a/packages/react-server-dom-relay/src/ReactServerStreamConfigFB.js b/packages/react-server-dom-relay/src/ReactServerStreamConfigFB.js
index e0477fd619..b13e5f3792 100644
--- a/packages/react-server-dom-relay/src/ReactServerStreamConfigFB.js
+++ b/packages/react-server-dom-relay/src/ReactServerStreamConfigFB.js
@@ -17,6 +17,8 @@ export type Destination = {
 export type PrecomputedChunk = string;
 export type Chunk = string;
 
+export const isPrimaryStreamConfig = true;
+
 export function scheduleWork(callback: () => void) {
   // We don't schedule work in this model, and instead expect performWork to always be called repeatedly.
 }
```

`yarn build-combined` still breaks with

```bash

/home/eps1lon/Development/forks/react/scripts/rollup/build.js:44
  throw err;
  ^

Error: Cannot find module 'react-server-dom-webpack/node-loader'
Require stack:
```

**Comment by eps1lon** [comment]
> Even with a naive
> 
> ```diff
> diff --git a/packages/react-server-dom-relay/src/ReactServerStreamConfigFB.js b/packages/react-server-dom-relay/src/ReactServerStreamConfigFB.js
> index e0477fd619..b13e5f3792 100644
> --- a/packages/react-server-dom-relay/src/ReactServerStreamConfigFB.js
> +++ b/packages/react-server-dom-relay/src/ReactServerStreamConfigFB.js
> @@ -17,6 +17,8 @@ export type Destination = {
>  export type PrecomputedChunk = string;
>  export type Chunk = string;
>  
> +export const isPrimaryStreamConfig = true;
> +
>  export function scheduleWork(callback: () => void) {
>    // We don't schedule work in this model, and instead expect performWork to always be called repeatedly.
>  }
> ```
> 
> `yarn build-combined` still breaks with
> 
> ```shell
> /home/eps1lon/Development/forks/react/scripts/rollup/build.js:44
>   throw err;
>   ^
> 
> Error: Cannot find module 'react-server-dom-webpack/node-loader'
> Require stack:
> ```

That was caused by me using `node@12.16.0` with `node@^12.20.0` everything is fine.

**Review by bvaughn — APPROVED** [review]

**Comment by bvaughn** [comment]
Thanks!

**Pull request merged**
