### PR TITLE
React DevTools 6.0.0 -> 6.0.1

### PR DESCRIPTION
**Pull request by hoxyq**
Changes in this release:

* Fix React Compiler badging ([poteto](https://github.com/poteto) in [#31196](https://github.com/facebook/react/pull/31196))
* fix[react-devtools]: fixed timeline profiler tests ([hoxyq](https://github.com/hoxyq) in [#31261](https://github.com/facebook/react/pull/31261))
* fix[react-devtools]: record timeline data only when supported ([hoxyq](https://github.com/hoxyq) in [#31154](https://github.com/facebook/react/pull/31154))
* refactor[react-devtools]: flatten reload and profile config ([hoxyq](https://github.com/hoxyq) in [#31132](https://github.com/facebook/react/pull/31132))
* fix[react-devtools]: remove all listeners when Agent is shutdown ([hoxyq](https://github.com/hoxyq) in [#31151](https://github.com/facebook/react/pull/31151))
* fix[react-devtools]: removed redundant startProfiling call ([hoxyq](https://github.com/hoxyq) in [#31131](https://github.com/facebook/react/pull/31131))
* refactor[react-devtools/fiber/renderer]: optimize durations resolution ([hoxyq](https://github.com/hoxyq) in [#31118](https://github.com/facebook/react/pull/31118))
* fix[react-devtools]: update profiling status before receiving response from backend ([hoxyq](https://github.com/hoxyq) in [#31117](https://github.com/facebook/react/pull/31117))
* fix[react-devtools]: wrap key string in preformatted text html element ([hoxyq](https://github.com/hoxyq) in [#31153](https://github.com/facebook/react/pull/31153))
* chore[react-devtools]: drop legacy context tests ([hoxyq](https://github.com/hoxyq) in [#31059](https://github.com/facebook/react/pull/31059))
* chore[react-devtools]: add legacy mode error message to the ignore list for tests ([hoxyq](https://github.com/hoxyq) in [#31060](https://github.com/facebook/react/pull/31060))
* fix[react-devtools]: request hook initialization inside http server response ([hoxyq](https://github.com/hoxyq) in [#31102](https://github.com/facebook/react/pull/31102))
* [Flight] Serialize Server Components Props in DEV ([sebmarkbage](https://github.com/sebmarkbage) in [#31105](https://github.com/facebook/react/pull/31105))
* Add: reload to profile for Fusebox ([EdmondChuiHW](https://github.com/EdmondChuiHW) in [#31021](https://github.com/facebook/react/pull/31021))
* refactor: allow custom impl of backend realod-to-profile support check ([EdmondChuiHW](https://github.com/EdmondChuiHW) in [#31048](https://github.com/facebook/react/pull/31048))
* fix: use public instance in Fiber renderer and expose it from getInspectorDataForViewAtPoint ([hoxyq](https://github.com/hoxyq) in [#31068](https://github.com/facebook/react/pull/31068))

### CODE REVIEW

**Comment by SimenB** [comment]
👋 

This update doesn't appear in Firefox - is that known?

https://addons.mozilla.org/en-US/firefox/addon/react-devtools/

image

**Comment by hoxyq** [comment]
> 👋 
> 
> 
> 
> This update doesn't appear in Firefox - is that known?
> 
> 
> 
> https://addons.mozilla.org/en-US/firefox/addon/react-devtools/
> 
> 
> 
> image
> 
> 

Hi @SimenB, thanks for pointing this out. Looks like this release was rejected by Firefox team, because they couldn't reproduce the build. I will be back from leave in December and will get this sorted.

**Comment by fazo96** [comment]
hi @hoxyq, on the [Mozilla Addons platform](https://addons.mozilla.org/en-US/firefox/addon/react-devtools) the version of this extension is still 6.0.0

**Comment by SimenB** [comment]
@hoxyq this is still an issue, unfortunately

**Comment by hoxyq** [comment]
> @hoxyq this is still an issue, unfortunately 

The release process in Firefox extensions store has been really problematic recently. I am aware of the fact that few last releases are not available for Firefox and been trying to fix this for the past weeks.

The release of 6.1.1 has been delayed for about 4 weeks, because of the bug on Firefox side, which blocked the review team from uploading a build script error.

Unfortunately, now Firefox is not happy about React DevTools using React from source. This technically violates one of their policies, but doesn't make much sense for an extension such as React DevTools. In order to comply with this policy, we would need to have some decent changes in our build infra. I am currently exploring other potential solutions, will post an update here once I have more clarity.

**Pull request merged**
