### PR TITLE
"transient dependencies" -> "transitive dependencies"

### PR DESCRIPTION
**Pull request by amasad**
I think that's what you meant -- although with npm dependencies are kind of transient :P

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by amasad** [comment]
CLA form seems to be down.

**Comment by gaearon** [comment]
Oh thanks :P
Can you send a PR against the repo as well?

**Comment by amasad** [comment]
https://github.com/facebookincubator/create-react-app/pull/187

**Comment by zpao** [comment]
(y) thanks!

**Pull request merged**
