### PR TITLE
Use local `grunt` executable on Travis

### PR DESCRIPTION
**Pull request by spicyj**
Builds have been flaky lately. Maybe this will help?

### CODE REVIEW

**Comment by spicyj** [comment]
Apparently not…

```
/home/travis/build.sh: line 66: ./node_modules/.bin/grunt: No such file or directory
```

**Comment by zpao** [comment]
I cleared the caches. I don't think that's really going to help since this seems really sporadic but it's worth a shot.

**Comment by spicyj** [comment]
I did that too and it fixed it once.

**Comment by zpao** [comment]
Blanket accept to do whatever you need to fix this.

**Comment by spicyj** [comment]
Maybe this'll stick.

**Pull request merged**
