### PR TITLE
Kill global queue in ReactMultiChild

### PR DESCRIPTION
**Pull request by spicyj**
As we move away from using HTML for updates, this becomes less useful.

### CODE REVIEW

**Comment by spicyj** [comment]
@sebmarkbage I think this is most of the contortions we had to support HTML batching. I took the opportunity to make it a little more functional since I was changing it.

**Comment by sebmarkbage** [comment]
I'll trade you some green for your red.

**Comment by troydemonbreun** [comment]
@spicyj it seems that propName warnings don't trigger now due to `useCreateElement `default change?  I think because `_createOpenTagMarkupAndPutListeners` is not called which triggers the warning event.

**Comment by spicyj** [comment]
@troydemonbreun Do you mean like if you miscapitalize a prop name?

**Comment by troydemonbreun** [comment]
Right

**Comment by spicyj** [comment]
Thanks, I see that #6585 fails on my machine. @jimfb Can you take a look at this?

**Comment by jimfb** [comment]
Yep, assigned to self.

**Pull request merged**
