### PR TITLE
Remove getTextContentAccessor

### PR DESCRIPTION
**Pull request by aweary**
[According to caniuse](https://caniuse.com/#search=textContent) the only browsers that don't support `textContent` are IE versions 8 and older, which we no longer support.

This is most likely safe to merge, but we should probably do a little browser testing with selection events if we aren't confident in caniuse.

### CODE REVIEW

**Comment by react-linter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  node` failed.
  </td>
    </tr>
  </tbody>
</table>



### Log


```sh
Error:  { FetchError: invalid json response body at http://react.zpao.com/builds/master/_commits/a869f992a88692f9d9a964e20ee7dc844bc7760a/results.json reason: Unexpected token < in JSON at position 0
    at /home/circleci/project/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'FetchError',
  message: 'invalid json response body at http://react.zpao.com/builds/master/_commits/a869f992a88692f9d9a964e20ee7dc844bc7760a/results.json reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }

```

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by aweary** [comment]
Looks like there's some trouble with the API dangerJS is using @gaearon @zpao ^

**Comment by gaearon** [comment]
Please check git history in case we tried to remove this before. I'm not sure.

**Comment by aweary** [comment]
@gaearon [doesn't look like it](https://github.com/facebook/react/pulls?utf8=%E2%9C%93&q=getTextContentAccessor)

**Comment by gaearon** [comment]
Just to be clear, were you testing SVG specifically? The comment says SVG behaves differently.

**Pull request merged**
