### PR TITLE
Add a test for non-passive event handlers for events affected by the browsers' intervention

### PR DESCRIPTION
**Pull request by koba04**
## Summary

This adds a test @trueadm has commented at https://github.com/facebook/react/pull/19654#issuecomment-676610859.
The test ensures that `unstable_createEventHandle` isn't affected by browsers' intervention #19654 mentioned.

### CODE REVIEW

**Comment by koba04** [comment]
My Circle CI builds are blocked and didn't run all builds I expect.. I'm not sure why this happens, so I have to investigate it.
https://app.circleci.com/pipelines/github/koba04/react?branch=add-test-for-non-passive-event-handlers

**Comment by koba04** [comment]
image

**Comment by koba04** [comment]
I've posted the issue on CircleCI's discuss.
https://discuss.circleci.com/t/builds-for-facebook-react-are-blocked-due-to-parallelism/37139

**Comment by koba04** [comment]
OK, I've fixed the problem, so this PR is ready for review.

**Comment by gaearon** [comment]
thx

**Pull request merged**
