### PR TITLE
JSDocs fixes

### PR DESCRIPTION
**Pull request by mhujer**
For finding those issues I've used `eslint-plugin-jsdoc` as it allows more granular enabling of checks (compared with `valid-jsdoc` rule in the eslint itself).

I've not yet added those checks into `.eslintrc`, because there are more JSDocs issues which need to be fixed first. You can see the eslint changes in my other [branch](https://github.com/mhujer/react/commits/eslint).

Note: I understand that this is a massive change that can cause conflicts with other PRs, but I think it is worth it.

### CODE REVIEW

**Comment by DeveloperCaladan** [comment]
wrong....
 Try again

**Comment by DeveloperCaladan** [comment]
Im so sorry, was not meant for this post..

**Comment by jimfb** [comment]
Seems reasonable to me.  I'm a little surprised eslint is so concerned about case sensitivity, and that it seems inconsistent with regards to the capitalization of `string` and `Array`.  cc @zpao for a sanity check.

**Comment by zpao** [comment]
That's just a jsdoc-ism, probably because of this:

```js
"" instanceof String === false
[] instanceof Array === true
```

We shouold make sure this won't break any internal tooling before merging. I don't care too much about enforcing JSDocs via lint, they aren't used for anything here and we'll probably eventually start using Flow annotations. But it could be good to enforce in the meantime so we have fewer PRs fixing them up.

**Comment by gaearon** [comment]
This doesn’t merge cleanly now. I think there isn’t enough either internal or external interest to get this fixed so I’ll close it but if somebody opens another PR maybe we’ll merge it quick enough before it’s outdated again :smile: . Sorry for the long response, and thanks for contributing!

**Pull request closed without merging**
