### PR TITLE
[Fiber] setState inside componentDidMount/Update should be sync and batched

### PR DESCRIPTION
**Pull request by acdlite**
I believe I did this right, though it's possible I misunderstood what the correct behavior is supposed to be.

### CODE REVIEW

**Comment by acdlite** [comment]
Oops hit some regressions when I rebased. Investigating,

**Comment by acdlite** [comment]
Oh, the regressions are due to the test Dan added against not scheduling redundant callbacks.

**Comment by acdlite** [comment]
Change of plans. Going to introduce a new type priority level, provisionally called **Task** priority (we'll think of a better name).

- Work with the **Task** priority should be performed within the current tick, but at the end of the batch work.
- Work with the **Synchronous** priority should be performed immediately. E.g. a synchronous `setState` will perform all its work before the `setState` call exits.

In https://github.com/facebook/react/pull/8127, these two types of work priority were both considered "synchronous." Splitting them into separate concepts will make it easier to schedule and batch things correctly.

**Comment by gaearon** [comment]
>the regressions are due to the test Dan added re: not scheduling redundant callbacks.

Feel free to disable if they get in the way, or document the new behavior in them. I wanted to make sure that things scheduled when we're inside browser callback don't get lost. However this seems tricky to test because I used lifecycles but they have special behavior now.

**Comment by acdlite** [comment]
Closing in favor of https://github.com/facebook/react/pull/8167

**Pull request closed without merging**
