### PR TITLE
Remove JSX propTypes validation

### PR DESCRIPTION
**Pull request by gaearon**
This removes the remaining `propTypes` validation calls, making declaring `propTypes` a no-op. In other words, React itself will no longer validate the `propTypes` that you declare on your components.

In general, our recommendation is to use static type checking (e.g. TypeScript). If you'd like to still run propTypes checks, you can do so manually, same as you'd do outside React:

```js
import checkPropTypes from 'prop-types/checkPropTypes';

function Button(props) {
  checkPropTypes(Button.propTypes, prop, 'prop', Button.name)
  // ...
}
```

This could be automated as a Babel plugin if you want to keep these checks implicit. (We will not be providing such a plugin, but someone in community might be interested in building or maintaining one.)

### CODE REVIEW

**Review by rickhanlonii — APPROVED** [review]

**Comment by ericfortis** [comment]
Hey @gaearon I’d like to know if you have some advice for overriding `render()` without Babel.

Since there’s no `React.Component.prototype.render`, I can’t simply:

```js
const oldRender = React.Component.prototype.render
React.Component.prototype.render = function () {
  checkPropTypes(this.constructor.propTypes, this.props, 'prop', this.constructor.name)
  oldRender()
}
```

…so I can only think of tediously adding a function to  every `render`, as such:

```js
import { checkPropTypes } from 'prop-types'

React.Component.prototype.checkTypes = function () {
  checkPropTypes(this.constructor.propTypes, this.props, 'prop', this.constructor.name)
}
```

```js
class Foo extends React.Component {
  render() {
    this.checkTypes()
    return null
  }
}
Foo.propTypes = {
  myProp: PropTypes.string
}
```

---

I know you suggested using TypeScript, but TypeScript doesn’t support custom validators as PropTypes do. Also, my project uses integer props names (for performance and obfuscation) so props names are dynamic and proxied, which can’t be done with TS either.

Thanks in advance
Eric

**Comment by gaearon** [comment]
I can't think of a seamless way to hack it in — your suggestion above with the manual call per render seems like the easiest way to me. If this is intolerable, then a Babel transform or an equivalent solution seems like the next thing to try. I'd expect a Babel plugin injecting this to take ~30 lines of code.

**Comment by gaearon** [comment]
I asked Claude to write a little Babel plugin that does this, here's a [bit of code](https://astexplorer.net/#/gist/4e0a7f21b01f31f9c9c5bc833f1d7351/b7d40a9c531a9a61eb5d8f473c364ec2ceb1748b).

```js
module.exports = function(babel) {
  const { types: t } = babel;

  function isReactComponent(node) {
    if (t.isIdentifier(node)) {
      return node.name === 'Component' || node.name === 'PureComponent';
    }
    if (t.isMemberExpression(node)) {
      return (
        t.isIdentifier(node.object) &&
        node.object.name === 'React' &&
        t.isIdentifier(node.property) &&
        (node.property.name === 'Component' || node.property.name === 'PureComponent')
      );
    }
    return false;
  }

  return {
    name: "add-prop-types-check",
    visitor: {
      Program: {
        enter(path, state) {
          state.checkPropTypesIdentifier = path.scope.generateUidIdentifier("checkPropTypes");
        },
        exit(path, state) {
          const newImport = t.importDeclaration(
            [t.importDefaultSpecifier(state.checkPropTypesIdentifier)],
            t.stringLiteral("prop-types/checkPropTypes")
          );
          path.node.body.unshift(newImport);
        }
      },
      ClassDeclaration(path, state) {
        if (path.node.superClass && isReactComponent(path.node.superClass)) {
          const renderMethod = path.node.body.body.find(
            node => t.isClassMethod(node) && node.key.name === "render"
          );

          if (renderMethod) {
            const checkPropsCall = t.expressionStatement(
              t.callExpression(
                state.checkPropTypesIdentifier,
                [
                  t.memberExpression(
                    t.memberExpression(t.thisExpression(), t.identifier("constructor")),
                    t.identifier("propTypes")
                  ),
                  t.memberExpression(t.thisExpression(), t.identifier("props")),
                  t.stringLiteral("prop"),
                  t.memberExpression(
                    t.memberExpression(t.thisExpression(), t.identifier("constructor")),
                    t.identifier("name")
                  )
                ]
              )
            );

            renderMethod.body.body.unshift(checkPropsCall);
          }
        }
      }
    }
  };
};
```

Might need some tweaking but hope this helps. If you don't use Babel, you might want to port this to a different transform engine.

**Comment by ericfortis** [comment]
thank you Dan!

**Comment by matyasf** [comment]
Are propType checks removed from functional components only or from class-based ones too? The RC release notes just speaks about removal from functional components: https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops

**Comment by ericfortis** [comment]
@matyasf Yes, in 19, `React.Component` doesn‘t support `propTypes`.

@rickhanlonii The release notes say "…for functions"

**Comment by rickhanlonii** [comment]
the "from functions" is for default props

**Comment by mqklin** [comment]
Has someone already created this babel plugin?

**Comment by gaearon** [comment]
>Has someone already created this babel plugin?

https://github.com/facebook/react/pull/28328#issuecomment-2261837798

**Comment by mqklin** [comment]
> > Has someone already created this babel plugin?
> 
> [#28328 (comment)](https://github.com/facebook/react/pull/28328#issuecomment-2261837798)

Thank you! Yep, trying to adjust this now. I use not just `prop-types`, but `forbidExtraProps` from `airbnb-prop-types`, so maybe I need to tweak it more.

**Comment by mqklin** [comment]
Claude couldn't help me, but ChatGPT made exactly what I needed: 
<details><summary>propTypesPlugin.js</summary>
<p>

```javascript
module.exports = function ({ types: t }) {
  return {
    visitor: {
      Program(path) {
        let usesPropTypes = false;

        // Check if `propTypes` or `forbidExtraProps` is used anywhere in the file
        path.traverse({
          AssignmentExpression(assignPath) {
            if (
              t.isMemberExpression(assignPath.node.left) &&
              assignPath.node.left.property.name === "propTypes"
            ) {
              usesPropTypes = true;
            }
          },
        });

        if (usesPropTypes) {
          // Add `_checkPropTypes` import at the top of the file
          const importDeclaration = t.importDeclaration(
            [t.importDefaultSpecifier(t.identifier("_checkPropTypes"))],
            t.stringLiteral("prop-types/checkPropTypes")
          );
          path.unshiftContainer("body", importDeclaration);
        }
      },
      FunctionDeclaration(path) {
        insertPropTypesCheck(path, t);
      },
      VariableDeclarator(path) {
        // Handle arrow functions assigned to variables
        if (t.isArrowFunctionExpression(path.node.init)) {
          insertPropTypesCheck(path, t);
        }
      },
    },
  };

  function insertPropTypesCheck(path, t) {
    const node = path.node;
    let componentName;

    // Determine the component name
    if (t.isFunctionDeclaration(node)) {
      componentName = node.id.name;
    } else if (t.isVariableDeclarator(node)) {
      componentName = node.id.name;
    } else {
      return;
    }

    // Traverse the program body to find the `propTypes` assignment
    const programNode = path.findParent((parentPath) =>
      t.isProgram(parentPath.node)
    );

    if (!programNode || !programNode.node.body) {
      return; // Exit if the program body is not found
    }

    const programBody = programNode.node.body;

    const propTypesAssignment = programBody.find(
      (n) =>
        t.isExpressionStatement(n) &&
        t.isAssignmentExpression(n.expression) &&
        t.isMemberExpression(n.expression.left) &&
        n.expression.left.object.name === componentName &&
        n.expression.left.property.name === "propTypes"
    );

    if (!propTypesAssignment) {
      return; // Skip if no propTypes assignment found
    }

    let propTypesNode = propTypesAssignment.expression.right;

    // Check if propTypes is wrapped in forbidExtraProps
    if (
      t.isCallExpression(propTypesNode) &&
      t.isIdentifier(propTypesNode.callee) &&
      propTypesNode.callee.name === "forbidExtraProps"
    ) {
      // Insert the _checkPropTypes call with the wrapped propTypes
      const checkPropTypesCall = t.expressionStatement(
        t.callExpression(t.identifier("_checkPropTypes"), [
          t.cloneNode(propTypesNode), // Pass the wrapped propTypes (the result of forbidExtraProps)
          t.identifier("arguments[0]"),
          t.stringLiteral("prop"),
          t.stringLiteral(componentName),
        ])
      );

      // Insert `_checkPropTypes` call at the start of the component
      const functionBody =
        t.isFunctionDeclaration(node)
          ? node.body.body
          : node.init.body.body;

      functionBody.unshift(checkPropTypesCall);
    } else {
      // If not wrapped in forbidExtraProps, handle normally
      const checkPropTypesCall = t.expressionStatement(
        t.callExpression(t.identifier("_checkPropTypes"), [
          t.cloneNode(propTypesNode),
          t.identifier("arguments[0]"),
          t.stringLiteral("prop"),
          t.stringLiteral(componentName),
        ])
      );

      const functionBody =
        t.isFunctionDeclaration(node)
          ? node.body.body
          : node.init.body.body;

      functionBody.unshift(checkPropTypesCall);
    }
  }
};


``` 

</p>
</details>

**Pull request merged**
