### PR TITLE
Handle nested Fragments in toTree (#12106)

### PR DESCRIPTION
**Pull request by maciej-ka**
Resolves #12107

### CODE REVIEW

**Comment by gaearon** [comment]
This was not a sufficient fix. Please see https://github.com/facebook/react/pull/12154.

**Comment by aweary** [comment]
Woops 😬

**Comment by maciej-ka** [comment]
I'm feeling worse about this than I probably should.

**Comment by aweary** [comment]
@maciej-ka don't feel bad at all! This was a great start and it was my responsibility to review and help you. This is solely my fault, and we really appreciate the contribution 🙂

**Comment by gaearon** [comment]
Yeah this was a comment for @aweary 😛 Didn't mean to make you feel bad, thank you for helping! This is kind of a thorny issue and the code is not easiest to follow.

**Pull request merged**
