### PR TITLE
[wip] Grunt -> Gulp

### LINKED ISSUE #4927: Switch entirely to gulp
Our build process sort of resembles Frankenstein's monster at this point. My bad. We shouldn't shell out to gulp from grunt and move utils out to `fbjs`.

@zertosh is already working on this.

### PR DESCRIPTION
**Pull request by zertosh**
Fixes #4927

### CODE REVIEW

**Comment by zpao** [comment]
cc @nickdima.

@zertosh - is this something you're going to continue working on? I think @nickdima had also started so I'd like to make sure we aren't wasting anybody's time…

**Comment by zertosh** [comment]
@zpao, this is the first pass, where it's mostly a 1:1 grunt to gulp port. the 2nd pass will be to improve things once they're in gulp (e.g. not spawning processes for linting, jest, etc... reuse result streams instead of reading from disk). I worked on this this weekend, and I can wrap it up next week. Not sure how much @nickdima has already.

**Comment by nickdima** [comment]
I didn't have too much time yet to actually implement something, just figuring out everything that's going on with the current build process alone took quite some time. :)
@zertosh your approach sounds good. I'll follow this PR in case I can help with anything.

**Comment by jimfb** [comment]
No activity in a couple of months, all checks failed, merge conflicts.  I'm going to close this out.  We can re-examine if/when the PR is in a better state.

**Comment by zertosh** [comment]
:blush: totally forgot about this PR... i don't want to abandon it. i'll open a new one

**Pull request closed without merging**
