### PR TITLE
Remove functions marked as undocumented and unused

### PR DESCRIPTION
**Pull request by BenBrostoff**
Hey @gaearon - saw you [added these TODOs in this commit](https://github.com/facebook/react/commit/3e2680411efa3b478afc1f26057f417c7aae7915) about 8 months ago. Figured I'd open a PR if this can now be completed.

### CODE REVIEW

**Comment by gaearon** [comment]
I wouldn't mind deprecating but we need to make sure they're not used by Enzyme.

**Comment by BenBrostoff** [comment]
@gaearon / @aweary Took my best shot at deprecating these. @gaearon - re: clear migration path, my deprecation warning obviously does not describe what this path should be, so this PR is definitely incomplete at this point.

**Comment by aweary** [comment]
@gaearon we only [import and re-export](https://github.com/airbnb/enzyme/blob/1a70e321886245e502e08b73add628330bea831b/src/react-compat.js#L184) `isCompositeComponentElement` so it should be safe. We can just remove that unused import. The [rewrite](https://github.com/airbnb/enzyme/pull/1007) also doesn't use these APIs.

**Comment by gaearon** [comment]
Mind sending a PR to Enzyme to stop importing it?

**Comment by aweary** [comment]
@gaearon opened at https://github.com/airbnb/enzyme/pull/1023, though the rewrite doesn't contain this import/export so it might just be removed when that's merged instead.

**Comment by aweary** [comment]
@gaearon the export will be removed in the next major release when https://github.com/airbnb/enzyme/pull/1007 is merged.

**Comment by gaearon** [comment]
I deleted them in the end.

**Pull request closed without merging**
