### PR TITLE
Update addons-animation.md

### PR DESCRIPTION
**Pull request by tai2**
Add a link to new documentation.

### CODE REVIEW

**Comment by gaearon** [comment]
IMO this is a bit confusing because our page is only for people who are looking for old docs.

**Comment by tai2** [comment]
Searching for react animation by some keywords like "react animation", the old doc is still listed on top. This can lead people to misunderstand ReactTransitionGroup's latest function. At least, I misunderstood it. 

For example, someone might convince himself that ReactTransitionGroup cannot use native animation event. It's false, of cause. 

Adding the link will prevent readers to have wrong impression.

**Comment by tai2** [comment]
I also think my writing may be confusing because I'm not a native speaker.
I will appreciate it if you correct it appropriately.

My hope is that people can easily reach the current official documentation.

**Comment by stvkoch** [comment]
I

Em 11/07/2017 3:00 da tarde, "Taiju Muto" <notifications@github.com>
escreveu:

I also think my writing may be confusing because I'm not a native speaker.
I will appreciate it if you correct it appropriately.

My hope is that people can easily reach the current official documentation.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/facebook/react/pull/10144#issuecomment-314452851>, or mute
the thread

**Comment by bvaughn** [comment]
Thank you for filing this PR!

I'm sorry to be the bearer of bad news, but the documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

Would you be willing to re-open this PR on the new repo? I promise we'll review it quickly!

**Pull request closed without merging**
