### PR TITLE
 For better to read the source code

### PR DESCRIPTION
**Pull request by lanzhiheng**
1. Add comments for `traverseContextPool` and `POOL_SIZE`.
2. Change param variable name `callback` => `traverseCallback`.

### CODE REVIEW

**Comment by lanzhiheng** [comment]
I think the variable name `callback` is too generic, so when I first to read the source code, I mistake it for the `func` which pass by `React.Children.map(children, function() {})` I think it will be better to let the variable name more special in this file. It will be good for the developer who like to read the source code.

**Comment by react-linter** [comment]
<details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 15767a8f8f798f0d80df4ddbc7cfaebdc29996a8...a680cd0d6a8abcb2818b24fd93e624d3e5c2991c</p>


  
## react
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react.development.js | +0.6% | +0.7% | 57.77 KB | 58.12 KB | 15.95 KB | 16.06 KB | UMD_DEV
react.development.js | +0.7% | +0.8% | 48.41 KB | 48.76 KB | 13.59 KB | 13.71 KB | NODE_DEV
React-dev.js | +0.8% | +0.9% | 48.67 KB | 49.04 KB | 13.28 KB | 13.4 KB | FB_WWW_DEV
**React-prod.js** | **:small_red_triangle:+0.4%** | **:small_red_triangle:+0.1%** | **13.39 KB** | **13.44 KB** | **3.75 KB** | **3.75 KB** | **FB_WWW_PROD**

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by nhunzaker** [comment]
Hey @lanzhiheng!

Thank you for sending this in, however we generally try to avoid code style-only changes unless they also fix bugs. We appreciate the PR though!

**Comment by lanzhiheng** [comment]
@nhunzaker Understand it.

**Pull request closed without merging**
