### PR TITLE
Update index.html in transitions example

### PR DESCRIPTION
**Pull request by tonyspiro**
'current' makes more sense than 'start' as the value increments passed its start value.

### CODE REVIEW

**Comment by zpao** [comment]
Hey @tonyspiro - if you can sign the CLA I'll merge this. I agree these changes make sense.

**Comment by tonyspiro** [comment]
I did sign the CLA with my fb account email.  I just sent cla@fb.com a request to add my github email tspiro@tonyspiro.com.  Please let me know if I need to do anytting else.

**Comment by zpao** [comment]
:thumbsup: thanks! Yea the bot gets a bit finicky - it usually responds to the PR, though perhaps only when the email it has matches the github email. Either way, this is good.

**Comment by tonyspiro** [comment]
Thanks @zpao !

**Pull request merged**
