### PR TITLE
When a root expires, flush all expired work in a single batch

### PR DESCRIPTION
**Pull request by acdlite**
Still need to add some Suspense tests, and some comments. Pushing so Dan can test if it fixes the issue in the fixture.

### CODE REVIEW

**Comment by react-linter** [comment]
ReactDOM: size: :small_red_triangle:+0.2%, gzip: :small_red_triangle:+0.2%


  <details>
  <summary>Details of bundled changes.</summary>

  <p>Comparing: 5cefd9b1e230fbf680ffbe86362387749f584386...2be6cfb9e99ceb6d6875f5bb60c0890ce632e450</p>


  
## react-dom
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-dom.development.js | +0.2% | +0.1% | 649.5 KB | 650.59 KB | 152.6 KB | 152.81 KB | UMD_DEV
**react-dom.production.min.js** | **:small_red_triangle:+0.2%** | **:small_red_triangle:+0.2%** | **95.38 KB** | **95.59 KB** | **31.18 KB** | **31.24 KB** | **UMD_PROD**
react-dom.development.js | +0.2% | +0.1% | 645.64 KB | 646.73 KB | 151.49 KB | 151.71 KB | NODE_DEV
**react-dom.production.min.js** | **:small_red_triangle:+0.2%** | **:small_red_triangle:+0.2%** | **95.37 KB** | **95.57 KB** | **30.91 KB** | **30.98 KB** | **NODE_PROD**
ReactDOM-dev.js | +0.2% | +0.1% | 652.67 KB | 653.79 KB | 149.5 KB | 149.71 KB | FB_WWW_DEV
**ReactDOM-prod.js** | **:small_red_triangle:+0.2%** | **:small_red_triangle:+0.2%** | **288.17 KB** | **288.87 KB** | **53.32 KB** | **53.41 KB** | **FB_WWW_PROD**
react-dom.profiling.min.js | +0.2% | +0.2% | 96.56 KB | 96.77 KB | 31.31 KB | 31.38 KB | NODE_PROFILING
ReactDOM-profiling.js | +0.2% | +0.2% | 290.52 KB | 291.21 KB | 53.93 KB | 54.01 KB | FB_WWW_PROFILING

## react-art
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-art.development.js | +0.2% | +0.2% | 441.74 KB | 442.83 KB | 99.92 KB | 100.12 KB | UMD_DEV
**react-art.production.min.js** | **:small_red_triangle:+0.2%** | **:small_red_triangle:+0.3%** | **86.62 KB** | **86.82 KB** | **26.73 KB** | **26.81 KB** | **UMD_PROD**
react-art.development.js | +0.3% | +0.2% | 374.28 KB | 375.37 KB | 82.82 KB | 83.03 KB | NODE_DEV
**react-art.production.min.js** | **:small_red_triangle:+0.4%** | **:small_red_triangle:+0.4%** | **51.61 KB** | **51.81 KB** | **16.11 KB** | **16.17 KB** | **NODE_PROD**
ReactART-dev.js | +0.3% | +0.3% | 364.38 KB | 365.5 KB | 77.54 KB | 77.75 KB | FB_WWW_DEV
**ReactART-prod.js** | **:small_red_triangle:+0.4%** | **:small_red_triangle:+0.3%** | **159.79 KB** | **160.48 KB** | **27.1 KB** | **27.19 KB** | **FB_WWW_PROD**

## react-test-renderer
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-test-renderer.development.js | +0.3% | +0.3% | 371.11 KB | 372.2 KB | 81.21 KB | 81.42 KB | UMD_DEV
**react-test-renderer.production.min.js** | **:small_red_triangle:+0.4%** | **:small_red_triangle:+0.5%** | **50.73 KB** | **50.92 KB** | **15.5 KB** | **15.57 KB** | **UMD_PROD**
react-test-renderer.development.js | +0.3% | +0.3% | 367.24 KB | 368.33 KB | 80.26 KB | 80.46 KB | NODE_DEV
**react-test-renderer.production.min.js** | **:small_red_triangle:+0.4%** | **:small_red_triangle:+0.4%** | **50.43 KB** | **50.63 KB** | **15.35 KB** | **15.41 KB** | **NODE_PROD**
ReactTestRenderer-dev.js | +0.3% | +0.3% | 372.04 KB | 373.16 KB | 79.21 KB | 79.43 KB | FB_WWW_DEV

## react-noop-renderer
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-noop-renderer.development.js | +1.9% | +1.8% | 23.35 KB | 23.79 KB | 5.33 KB | 5.42 KB | NODE_DEV
**react-noop-renderer.production.min.js** | **:small_red_triangle:+1.3%** | **:small_red_triangle:+1.4%** | **8.75 KB** | **8.86 KB** | **3.04 KB** | **3.08 KB** | **NODE_PROD**
react-noop-renderer-persistent.development.js | +1.9% | +1.8% | 23.46 KB | 23.9 KB | 5.34 KB | 5.44 KB | NODE_DEV
**react-noop-renderer-persistent.production.min.js** | **:small_red_triangle:+1.3%** | **:small_red_triangle:+1.5%** | **8.77 KB** | **8.88 KB** | **3.04 KB** | **3.09 KB** | **NODE_PROD**

## react-reconciler
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
react-reconciler.development.js | +0.3% | +0.3% | 355.25 KB | 356.34 KB | 76.88 KB | 77.09 KB | NODE_DEV
**react-reconciler.production.min.js** | **:small_red_triangle:+0.4%** | **:small_red_triangle:+0.4%** | **49.07 KB** | **49.27 KB** | **14.72 KB** | **14.78 KB** | **NODE_PROD**
react-reconciler-persistent.development.js | +0.3% | +0.3% | 353.82 KB | 354.91 KB | 76.3 KB | 76.51 KB | NODE_DEV
**react-reconciler-persistent.production.min.js** | **:small_red_triangle:+0.4%** | **:small_red_triangle:+0.4%** | **49.08 KB** | **49.28 KB** | **14.73 KB** | **14.78 KB** | **NODE_PROD**

## react-native-renderer
File | Filesize Diff | Gzip Diff | Prev Size | Current Size | Prev Gzip | Current Gzip | ENV
 ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  ---  |  --- 
ReactNativeRenderer-dev.js | +0.2% | +0.2% | 485.92 KB | 487.05 KB | 107.52 KB | 107.73 KB | RN_FB_DEV
**ReactNativeRenderer-prod.js** | **:small_red_triangle:+0.3%** | **:small_red_triangle:+0.2%** | **214.53 KB** | **215.22 KB** | **37.41 KB** | **37.5 KB** | **RN_FB_PROD**
ReactNativeRenderer-dev.js | +0.2% | +0.2% | 485.66 KB | 486.78 KB | 107.46 KB | 107.67 KB | RN_OSS_DEV
**ReactNativeRenderer-prod.js** | **:small_red_triangle:+0.3%** | **:small_red_triangle:+0.3%** | **204.34 KB** | **205.03 KB** | **35.75 KB** | **35.86 KB** | **RN_OSS_PROD**
ReactFabric-dev.js | +0.2% | +0.2% | 476.11 KB | 477.23 KB | 105.09 KB | 105.31 KB | RN_FB_DEV
**ReactFabric-prod.js** | **:small_red_triangle:+0.4%** | **:small_red_triangle:+0.3%** | **196.76 KB** | **197.45 KB** | **34.27 KB** | **34.37 KB** | **RN_FB_PROD**
ReactFabric-dev.js | +0.2% | +0.2% | 476.14 KB | 477.26 KB | 105.11 KB | 105.32 KB | RN_OSS_DEV
**ReactFabric-prod.js** | **:small_red_triangle:+0.4%** | **:small_red_triangle:+0.3%** | **196.79 KB** | **197.49 KB** | **34.29 KB** | **34.38 KB** | **RN_OSS_PROD**
ReactNativeRenderer-profiling.js | +0.3% | +0.3% | 207.76 KB | 208.46 KB | 36.41 KB | 36.53 KB | RN_OSS_PROFILING
ReactFabric-profiling.js | +0.3% | +0.3% | 199.76 KB | 200.45 KB | 34.84 KB | 34.95 KB | RN_OSS_PROFILING
ReactNativeRenderer-profiling.js | +0.3% | +0.2% | 217.93 KB | 218.63 KB | 38.06 KB | 38.15 KB | RN_FB_PROFILING
ReactFabric-profiling.js | +0.3% | +0.3% | 199.72 KB | 200.41 KB | 34.82 KB | 34.93 KB | RN_FB_PROFILING

  </details>
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by gaearon** [comment]
It looks like it's helping. Still gets stuck sometimes but I suppose it's just two expirations happening one after the other (because the commit itself took a long time). But nothing like it was getting stuck before.

**Comment by acdlite** [comment]
@gaearon Ready for review

**Comment by gaearon** [comment]
Let's get this fix in, but we'll need a follow-up for scheduler itself.

**Pull request merged**
