### PR TITLE
Pass prevContext param to componentDidUpdate

### PR DESCRIPTION
**Pull request by bvaughn**
**See [this comment](https://github.com/facebook/react/pull/8631#issuecomment-270450606) for my latest thoughts about this issue.**

This PR adds the missing `prevContext` param to `componentDidUpdate` calls. Tracking previous `context` is done by way of an expando property (`__reactInternalPrevContext`) on the `stateNode`. An instance attribute was used instead of a Fiber attribute because:
1) Conditional fields on fibers would break monomorphism.
2) Adding to all fibers would bloat types that don't use context.

Note that this approach is support option A below.

### Options Considered

It seems like we have a high-level decision to make regarding how and if we support the `prevContext` parameter going forward. Options include:

1. **Drop support for it**: If we do this we should update the `ReactContextValidator-test` test to assert that the `prevContext` parameter is not passed and update to Stack to mirror this behavior.
2. **Support it (option A)**: Store it as an expando property on instance (eg `__reactInternalPrevContext`). Adding to the instance avoids bloating Fibers for all of the types that don't need this property _and_ keeps our Fiber-consuming functions monomorphic.
2. **Support it (option B)**: Use `stateNode` to store a wrapper object around instance and previous context for the case of `ClassComponent`s. This prevents all non-`ClassComponent` fibers from growing while also keeping fiber-consuming methods monomorphic. Since this only impacts `ClassComponent` it should hopefully introduce minimal forking.

Regarding continued support: At this time it does not seem like this parameter is being used by React components within Facebook but a quick [Github search](https://github.com/search?utf8=%E2%9C%93&q=componentDidUpdate+prevContext&type=Code&ref=searchresults) seems to suggest the parameter is being used externally (eg [1](https://github.com/bogus34/react-form-components/blob/63597b6ef9e0e1d817a4562be6c5f0dad542caf8/src/select_component.coffee#L19), [2](https://github.com/PBRT/PBRT/blob/671a19fdea48216b5d0cc650c3364a76590bd919/client/components/heroshot/heroshot.jsx#L13), [3](https://github.com/roparat/PicasaGalleryReact/blob/cc5a37c089c5c59d4cf26d0b6828f5fff952bfd5/src/AllGallery.js#L44), etc.).

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Sorry. We explicitly did not choose this strategy for the reason that it doesn't make sense to add to everything when only a few places change and it can be recreated while traversing anyway.

**Comment by bvaughn** [comment]
I've updated this PR description with some more context based on our face-to-face chat about this.

**Comment by gaearon** [comment]
>a quick Github search seems to suggest the parameter is being used externally (eg 1, 2, 3, etc.).

Most of these appear to be copies of React, type definitions, and a few one-off projects with no community activity that use context directly despite us explicitly saying in the docs that it’s not supported. I wouldn’t worry too much about them because updates are already broken for context.

**Comment by gaearon** [comment]
"But there still exist some problems" — is this ready to get merged or do you want to add failing cases?

**Comment by gaearon** [comment]
Yea, no rush, just curious.
I’m inclined towards either this fix or not fixing it at all.

**Comment by bvaughn** [comment]
No worries. I should have left a clearer status on the PR before heading out.

I was starting to feel bike-sheddy about this on Thursday and I was hoping a few days away from it might lend some clarity.

**Comment by bvaughn** [comment]
Note to self: PR #8655 has implications on this that probably pushes us toward option B.

I haven't wrapped my head fully around this yet but I think that if it's possible for `instance.props` and `instance.state` inputs to be invalidated by swapping `child` and `progressedChild` then the same applies to any property stored on the instance.

**Comment by bvaughn** [comment]
I've been thinking more about the lifecycle methods and specific concerns about `context` in fiber.

First some assumptions I have:
* `componentWillReceiveProps` only exists to enable components to update `state` in reaction to a change in inputs (`props` and, unofficially, `context`).
* `componentWillUpdate` only exists to enable components to compare prev/next inputs to decide if anything internally needs to be set/reset in response to a specific input change (eg in react-virtualized I reset cached size and position data if certain inputs change).
* `componentDidUpdate` exists to enable components to do side-effect things like DOM manipulations (that rely on a render having already been done) or network requests (in response to a change in inputs).

Assuming the above assumptions are correct, I have some concerns about fiber and `context`.

I think it's not controversial to say that side-effect things (eg DOM manipulation, network requests) should _only_ be done in `componentDidUpdate`. Other lifecycle methods (eg `componentWillUpdate`) can't be relied on because the work they do may be bailed out on.

What about other instance attributes? Using react-virtualized as an example again- I store some derived data on the instance. This data is outside of React's management/awareness and so it won't be reset when a Fiber is bailed out on. I think that PR #8655 mitigates this by explicitly resetting `instance.props` and `instance.state` before calling lifecycle hooks (or at least it will by the time it is merged). As long as I'm using the correct lifecycle methods, my instance attributes will be eventually consistent with inputs.

But what about instance attributes that are derived from `context`?
* If we remove the `prevContext` parameter from `componentDidUpdate` then how can a component safely react to a change in `context`?
* Even with that parameter present- if `context` isn't managed in the same way as `props` and `state` (PR #8655) then it could be inconsistent between the instance and the fiber.

I believe @sebmarkbage has some ideas/plans for `context` going forward that are pretty different from the current, unstable implementation. Hopefully these ideas do away with the way we're managing next/prev `context` and this whole comment becomes invalid- but I wanted to write it down while it was in my mind in case. @sebmarkbage, maybe we can chat more about this topic next week when you're back?

**Comment by bvaughn** [comment]
I want to expand on my concern about instance attributes a little more while I'm thinking about it.

I think it's unsafe to do _anything with side effects_ (even setting or updating "private" instance attributes) in `componentWillReceiveProps`; this method should _only_ be used for updating `state` in response to a change in `props`. Anything else can be problematic.

(There may be operations that should only be done _once_- when an input changes from X to Y. Because we might call `componentWillReceiveProps` on the same instance _twice_ with the same X-to-Y transition- due to how we reset inputs a la PR #8655- this type of operation is unsafe.)

This is also a potential problem if we store anything references to non-primitive types in `state`. Because our instance may run `componentWillReceiveProps` more than once for the same previous inputs- it's possible we take an action too many times (eg increment a counter more than once).

@sebmarkbage I'd like to chat with you about this next week if you're available. 😄

**Comment by bvaughn** [comment]
Ping @sebmarkbage. Now that you're back, can we chat about this?

**Comment by bvaughn** [comment]
During the weekly sync this week we rashly agreed to just drop the `prevContext` param from `componentDidUpdate`. I think @sebmarkbage still has some reservations about doing this that warrant talking through- so I will sync up with him this week to talk more. In the meanwhile though, I've updated this PR to _remove_ that parameter (for now) in case we decide to go through with that change after all.

**Comment by gaearon** [comment]
Let’s bring this up to date and merge? @bvaughn

**Comment by bvaughn** [comment]
Happy too, @gaearon.

**Comment by sebmarkbage** [comment]
What's the upgrade path (both internally and externally)? Break it and see what happens?

**Comment by bvaughn** [comment]
If people were depending on the `prevContext` param before, wasn't their code already kind of broken?

**Comment by sebmarkbage** [comment]
No, it worked as long as you didn't use `shouldComponentUpdate` so that `componentDidUpdate` actually fired.

**Comment by bvaughn** [comment]
I guess I should have said "potentially broken".

**Comment by bvaughn** [comment]
Dan voted to merge (in the PR above). Ben and Andrew voted in-person. So~ I'm going to move forward with this. Let's revisit later if we decide it was a mistake.

**Comment by bvaughn** [comment]
cc @flarnie, @lelandrichardson

**Pull request merged**
