### PR TITLE
Make jsfiddle iframes work on https pages

### PR DESCRIPTION
**Pull request by streeter**
When viewing https://facebook.github.io/react/blog/2013/11/05/thinking-in-react.html, none of the jsfiddle iframes show up because they are pointing to http links. Using a protocol-relative URL works for both http and https access.

### CODE REVIEW

**Comment by jsfb** [comment]
Please use `https://` instead of `//` as per the conversation here: https://github.com/facebook/react/pull/3180#issuecomment-74939014

Also, we should be aware this PR is subject to the same merging discussion mentioned in cody's PR: https://github.com/facebook/react/pull/3180

**Comment by streeter** [comment]
Sounds good. I updated the embedded URLs to use https.

**Comment by zpao** [comment]
Probably going to just take #3180 instead. I actually think we should leave this page alone, add a link at the top of this blog post to the updated location, and then only update that page.

**Comment by jsfb** [comment]
Closing in favor of https://github.com/facebook/react/pull/3180, which is now merged.

**Pull request closed without merging**
