### PR TITLE
webpack 2 isn't in beta anymore

### PR DESCRIPTION
**Pull request by oscar-b**
Minor doc update

### CODE REVIEW

**Comment by gaearon** [comment]
We can just remove the notice since it's the latest stable version I think.

**Comment by oscar-b** [comment]
Maybe, but a lot of people will probably stay on webpack 1? Perhaps not *ahem CRA* ;)

**Comment by gaearon** [comment]
At this point Webpack itself has switched to the new website on its GH page so I think it's fine.

**Comment by gaearon** [comment]
Actually, could you search the docs for occurrences of the old website and replace it with the new website?

**Comment by oscar-b** [comment]
@gaearon sure, but it will be later tonight (in 6h or so)

**Comment by gaearon** [comment]
Sounds good!

**Comment by oscar-b** [comment]
@gaearon Only found URLs in installation.md. There are references in some blog posts though (but https://webpack.github.io/ still works as a landing page)?

There are references to `Webpack` instead of `webpack`, not sure if that's to much nitpicking to change.

**Comment by gaearon** [comment]
>There are references in a blog post though (but https://webpack.github.io/ still works as a landing page)?

Let's change them to the new link since people still read blog posts.

>There are references to Webpack instead of webpack, not sure if that's to much nitpicking to change.

Meh, let's not worry about this.

**Comment by gaearon** [comment]
Thanks!

**Pull request merged**
