### PR TITLE
Mouse enter leave

### PR DESCRIPTION
**Pull request by jquense**
Updated version of #5762 maybe there is a new failing test tho with fiber?

cc @nhunzaker

### CODE REVIEW

**Comment by nhunzaker** [comment]
Thanks for reviving this! On the surface, this looks great. Looks like CI is just failing because of a linting issue. 

I'll be able to dig in for a deeper review on Friday. I'll setup a DOM test fixture and do some browser QA. From there, we just need to figure out what's going on with Fiber. 

@spicyj Could you take a look at this?

**Comment by jquense** [comment]
If I'm remembering correctly from way back when I originally did this, the other approach is to use the plugin add/remove listener hooks to circumvent the top level delegate for the polyfill (and attach a listener directly to the node). This may be a preferable approach judging from @sebmarkbage comment in the old PR.

**Comment by jquense** [comment]
So I'm revisiting this. From what I can tell **native** mouseenter and mouseleave are supported on all modern (and not modern) browsers. https://developer.mozilla.org/en-US/docs/Web/Events/mouseleave

Why is there a polyfill to begin with? Can we just remove at this point?

**Comment by sebmarkbage** [comment]
WebKit browsers (including Chrome at the time) didn't get support for it until late 2013. After React. There was also a long tail of upgrades that took a while but I think we can remove it now.

Similarly focusin/out wasn't supported in Firefox until this year(!) but once it has enough adoption we can kill the polyfilling around that too. However, that one is a bit different since we have slightly different behavior.

Also, Portals currently support bubbling through to the parent. That can be replicated in other ways though (e.g. redispatching the event).

**Comment by sebmarkbage** [comment]
Another feature of portals is that the events *don't* fire when you move between the parent and the portal. That bit might need a bit more complicated logic.

**Comment by gaearon** [comment]
Closing as stale.

**Pull request closed without merging**
