### PR TITLE
Refactored how React/DevTools log Timeline performance data

### PR DESCRIPTION
**Pull request by bvaughn**
Until now, DEV and PROFILING builds of React recorded Timeline profiling data using the [User Timing API](https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API). This commit changes things so that React records this data by calling methods on the DevTools hook. (For now, DevTools still records that data using the User Timing API, to match previous behavior.)

This commit is large but most of it is just moving things around:
* New methods have been added to the DevTools hook (in `"backend/profilingHooks"`) for recording the Timeline performance events.
* Reconciler's "ReactFiberDevToolsHook" has been updated to call these new methods (when they're present).
* User Timing method calls in `"SchedulingProfiler"` have been moved to DevTools `"backend/profilingHooks"` (to match previous behavior, for now).
* The old reconciler tests, `"SchedulingProfiler-test"` and `"SchedulingProfilerLabels-test"`, have been moved into DevTools `"TimelineProfiler-test"` to ensure behavior didn't change unexpectedly.
* Two new methods have been added to the injected renderer interface: `injectProfilingHooks()` and `getLaneLabelMap()`.

Relates to #22529.

### CODE REVIEW

**Comment by bvaughn** [comment]
Note to self: Need to migrate the `preprocessData-test` as well. Will do that this afternoon.

**Review by lunaruan — APPROVED** [review]
These changes looks good minus the `preprocesssData-test` still uses  the `react-reconciler/src/SchedulingProfiler` file, which is what's causing the tests to fail.

You'll also need to update your inline snapshots in your `timelineProfiler-test.js` test because right now they point to React 17 rather than `react-version-18.0.0-rc.0-experimental-b59af8410-20220112`. Maybe there's a better way to write these tests so they don't change every time the version does?

 Approving pending that!

**Comment by bvaughn** [comment]
Thanks for the review, Luna!

> These changes looks good minus the `preprocesssData-test` still uses  the `react-reconciler/src/SchedulingProfiler` file, which is what's causing the tests to fail.

In the process of migrating this one over. One test is failing for reasons I'm not sure I understand yet but the rest are okay.

> You'll also need to update your inline snapshots in your `timelineProfiler-test.js` test because right now they point to React 17 rather than `react-version-18.0.0-rc.0-experimental-b59af8410-20220112`. Maybe there's a better way to write these tests so they don't change every time the version does?

Oh good call! Thanks for pointing that out.

**Comment by bvaughn** [comment]
I'll dig into the `ReactUpdaters` test failure tomorrow morning.

**Comment by bvaughn** [comment]
Okay, I _think_ all unit tests are passing now.

I also just did a little smoke testing:
- [x] When DevTools is installed, Timeline profiling data looks the same as before.
- [x] When DevTools is not install, Chrome tracing data doesn't have timeline marks.

I think we're good to land as soon as CI finishes.

**Comment by bvaughn** [comment]
CI error is not related to this change:
Screen Shot 2022-01-13 at 11 17 42 AM

Not sure what's going on.

**Pull request merged**
