### PR TITLE
white-listed wrap attribute, addresses #4226

### PR DESCRIPTION
**Pull request by jscheel**
Not entirely sure I understand the MUST_USE_ATTRIBUTE mask, but I assume it can't hurt to require the value to be get/set through getAttribute() and setAttribute(). Tests passed, but I didn't add any new ones for such a minor, granular change. First-time PR, so completed the CLA as well.

### CODE REVIEW

**Comment by jimfb** [comment]
I don't fully understand the ramifications of using attribute vs. property flags.  @spicyj?  Is there a reason one would be preferable over the other?  Any objections to this diff?

**Comment by zpao** [comment]
#4237 is already in progress for the same thing, let's just follow through on that PR

**Comment by zpao** [comment]
Sorry to close this but definitely appreciated! Hopefully we'll see you in some more PRs :)

**Comment by jscheel** [comment]
@zpao no worries, it's one line :) Before
Merging the other PR, might want to make sure the docs are updated too (the other two files). I'll dig in some more to find other issues to get started with.

**Pull request closed without merging**
