### PR TITLE
Remove unnecessary null

### PR DESCRIPTION
**Pull request by edvinerikson**
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`).
6. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
7. If you added or removed any tests, run `./scripts/fiber/record-tests` before submitting the pull request, and commit the resulting changes.
8. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

### CODE REVIEW

**Comment by gaearon** [comment]
Now that I think of it why do we ever return null now? Let's change it to always fall back to "Component".

**Comment by edvinerikson** [comment]
Not sure what circleci is up to but I ran the tests and flow locally without any errors

**Comment by gaearon** [comment]
k

**Comment by spicyj** [comment]
You don't think `Unknown` is nicer? We use that as a fallback for the stack, for instance.

**Comment by edvinerikson** [comment]
should I send a PR?

**Comment by gaearon** [comment]
Please do

**Pull request merged**
