### PR TITLE
PropTypes type checking: Add additional check to UnionType checker

### PR DESCRIPTION
**Pull request by johann-sonntagbauer**
PropTypes type checking: Add additional check to UnionType checker to ensure only functions are used as argument of oneOfType.

This is especially handy to catch typos during PropType definition like for example:
```javascript
Greeting.propTypes = {
  name: React.PropTypes.oneOfType([React.PropTypes.sting, React.PropTypes.func])
};
```

The pull request will print a warning 
`Invalid argument supplied to oneOfType, expected an array containing check functions.`

### CODE REVIEW

**Comment by hellonewbie** [comment]
Sure will (try ) DO :) I see long start but for now it can be any start
without master admin - console.


18.01.2017 22:18 "Johann Hubert Sonntagbauer" <notifications@github.com>
napisał(a):

**Comment by aweary** [comment]
@johann-sonntagbauer per the PR template, can you run the Fiber test script? Otherwise CI will fail

> If you added or removed any tests, run ./scripts/fiber/record-tests before submitting the pull request, and commit the resulting changes.

**Comment by johann-sonntagbauer** [comment]
@aweary sorry I misunderstood that part. I've added the test summary.

**Comment by aweary** [comment]
PropTypes have been removed from React core and now exist as a separate package `prop-types`. Any future feature requests, bug reports, or changes should be directed to the new repo at https://github.com/reactjs/prop-types.

@johann-sonntagbauer sorry about that!

**Comment by johann-sonntagbauer** [comment]
@aweary, no problem.
Does it make sense to pull this change over? If I get green lights from you I will do it :)

**Comment by aweary** [comment]
@johann-sonntagbauer yeah, I think it's a good improvement. Feel free to ping me when you open a PR in `prop-types`!

**Pull request closed without merging**
