### PR TITLE
Added support for the 'low', 'high', and 'optimum' attributes that are missing from the <meter> tag.

### PR DESCRIPTION
**Pull request by agelter**

### CODE REVIEW

**Comment by zpao** [comment]
Yea, this seems fine. Can you actually remove the last 2 commits? We'll update docs manually with other attributes and the merge is extraneous since we'll just merge this back.

**Comment by agelter** [comment]
CLA signed.
Sorry about my ignorance, but I can't seem to figure out how to remove the last two commits? Is there an easy way to do this or do I need to create a new branch and apply just the changes from the first commit.

**Comment by zpao** [comment]
```sh
# move back 2 commits
git reset --hard HEAD~2
# force push since you're changing history in the remote
git push -f
```

I won't lie and say those aren't risky operations, especially with a merge in ther :) There's a chance you'll screw it all up (I certainly have). Luckily it's a smaller change so easily reproducible. In the future you'll probably want to do PRs in a branch anyway (and not on master).

If you don't feel comfortable, then no worries at all. I can grab the code commit and push that with you as the author.

**Comment by agelter** [comment]
Thanks!  I think it updated properly?  Let me know if there are still issues.

**Comment by zpao** [comment]
Awesome, thanks!. Don't worry about the failing test, that's not you.

**Pull request merged**
