### PR TITLE
Fix incorrect markup for ie10 in docs footer.

### LINKED ISSUE #8875: your website page not working properly in ie10
**Do you want to request a *feature* or report a *bug*?**
I have attached a screen short. check please. 80% people in the world use ie built in browser. 
ie10 b

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

**What is the expected behavior?**

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

### PR DESCRIPTION
**Pull request by Rastopyr**
This PR resolve #8875

As noted by the @nhunzaker, scss not contain `-ms` prefixes for flexbox. This PR add their.

### CODE REVIEW

**Comment by nhunzaker** [comment]
Looks like the CI fail is unrelated. Happy to do browser testing on this, but I'm not sure how to setup the website locally.

Gonna figure that out...

**Comment by Rastopyr** [comment]
@nhunzaker 

Looks like this related with fail in #8884. But @gaearon approved it.

**Comment by aweary** [comment]
That's fine for now, if we can verify that this fixes #8875 I can just merge it and we can get CI fixed later.

**Comment by nhunzaker** [comment]
Checked in:

- IE10,11,14
- Safari 10
- Chrome (Latest)
- Firefox (Latest)

Looks legit to me!

**Comment by aweary** [comment]
Thanks @Rastopyr and @nhunzaker!

**Pull request merged**
