### PR TITLE
Improve devtools image size for the tutorial

### PR DESCRIPTION
**Pull request by ivanzotov**
Before:
screen shot 2016-10-26 at 10 50 59 pm

After:
screen shot 2016-10-26 at 10 54 28 pm

### CODE REVIEW

**Comment by gaearon** [comment]
How does it look on desktop?

**Comment by ivanzotov** [comment]
screen shot 2016-10-27 at 3 39 07 pm

**Comment by ivanzotov** [comment]
screen shot 2016-10-27 at 3 40 41 pm

**Comment by gaearon** [comment]
Thanks!

**Pull request merged**
