### PR TITLE
Importing React for the first example.

### PR DESCRIPTION
**Pull request by devrchancay**
Importing react in the example to have consistency in relation to the others.

### CODE REVIEW

**Comment by devrchancay** [comment]
what do you think about this PR @JoeCortopassi ?

**Comment by JoeCortopassi** [comment]
@devrchancay looks good to me. This just fixes the omission from the first example to make it consistent with the examples directly below it

**Comment by devrchancay** [comment]
Of course, you can try copying and pasting.

I hope you approve the PR: D

**Comment by devrchancay** [comment]
@gaearon good to merge for consistency?

**Comment by threepointone** [comment]
Seems reasonable to me, I'm going to approve/merge this in. Thanks @devrchancay!

**Pull request merged**
