### PR TITLE
Use hardcoded value for PropType secret

### PR DESCRIPTION
**Pull request by Aweary**
Addresses @spicyj's concern https://github.com/facebook/react/pull/7132#issuecomment-230585137

cc @gaearon

### CODE REVIEW

**Comment by gaearon** [comment]
If I were third party lib author I wouldn’t feel guilty about passing a string like this.
I’m serious: let’s call it `SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED`.

**Comment by spicyj** [comment]
`'I_PROMISE_I_WILL_ONLY_CALL_THESE_PROPTYPES_CHECKERS_IN_DEV_MODE'`.

**Comment by spicyj** [comment]
Whichever.

**Comment by maxdeviant** [comment]
There are already firing warnings elsewhere in the code, and I think it would make for a good running joke in the codebase :smile:

**Comment by Aweary** [comment]
> If I were third party lib author I wouldn’t feel guilty about passing a string like this.
I’m serious: let’s call it SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED.

I went with this one, for consistency 😉

**Comment by zpao** [comment]
→ semver-minor since it depends on another semver-minor (good edge case testing for my tool, but going to be hard to make work well when trying to do patch-only releases)

**Comment by ljharb** [comment]
Our tests fail on console warnings, so sadly this causes a semver-minor React update to break things :-/ Also, https://facebook.github.io/react/warnings/dont-call-proptypes.html 404s so I'm not even sure why.

**Comment by gaearon** [comment]
>Our tests fail on console warnings

This puts us in a very difficult position because this effectively means we can’t introduce new deprecations without doing a major release. Unfortunately this would slow down our development way too much, and for the benefit of the community we can’t do it this way. When we introduced our new versioning strategy with 15.0.0, we clearly said that [we ship deprecation warnings in minor releases](https://facebook.github.io/react/blog/2016/02/19/new-versioning-scheme.html#breaking-changes). This does not technically contradict semver.

The decision to fail tests on console warnings is yours. I can see why this is reasonable, but in this case you’ll want to use `~` instead of `^` since you intentionally want to be more conservative about the updates.

>Also, https://facebook.github.io/react/warnings/dont-call-proptypes.html 404s so I'm not even sure why.

That’s bad, probably CI is stuck. I’ll look into why this happened, thanks for flagging.

**Comment by ljharb** [comment]
@gaearon Understood. However, our tests aren't run in production mode nor run with a production build of react, so I'm not sure why they'd be issuing warnings, since the point of the original issue was to deprecate calling them directly in production. We're still looking into it, and I'll update when I have more info.

**Comment by gaearon** [comment]
>However, our tests aren't run in production mode nor run with a production build of react, so I'm not sure why they'd be issuing warnings, since the point of the original issue was to deprecate calling them directly in production.

Many people won’t notice warnings that happen only in production builds. Our intention is to deprecate *the pattern of calling them directly per se* because we want to treat them more as metadata. So we want the libraries that use `PropTypes` e.g. for API validation to use some fork (or a better system like [tcomb](https://github.com/gcanti/tcomb)) instead. Making them noops in production is a part of that, but the bigger issue is we want people to stop calling them manually at all.

**Comment by ljharb** [comment]
We use them to build custom propType validators on top of them - that are also stripped in production. What should we use instead if we want identical behavior as React's native PropTypes?

**Comment by gaearon** [comment]
>We use them to build custom propType validators on top of them - that are also stripped in production.

This is still supported.
Please see: https://facebook.github.io/react/warnings/dont-call-proptypes.html#fixing-the-false-positive-in-third-party-proptypes

(The link is up now.)

**Comment by ljharb** [comment]
Thanks, that will likely resolve our problem :-)

**Comment by eugenebauling** [comment]
I know this is a long standing hard coded value, but is there a way we can change the value to exclude the word "Secret"? Our security scans are picking this up as a hard coded password/secret due to the value and naming. Unfortunately we cannot change the config of the security scans or flag this as a false positive as the config of the security scanning software is defined by the client.

**Comment by ljharb** [comment]
The client should change their config to not pick up false positives, or the software shouldn't be scanning third-party code for secrets ¯\\\_(ツ)_/¯

**Pull request merged**
