### PR TITLE
clarify the two main ideas behind react.

### PR DESCRIPTION
**Pull request by mikrofusion**
"To do this, React uses two main ideas." is currently followed by a list of five paragraphs with headers.  This PR clarifies that "two main ideas" is referring to the first two paragraphs (Simple & Declarative).

### CODE REVIEW

**Comment by jimfb** [comment]
Wow, that is confusing.  That's what happens when documentation is maintained over time and people keep making changes.

@zpao  I think one of the main ideas is also to "Build Composable Components".  So maybe there are three main ideas?  The main ideas are little more than a sentence each; maybe we make the three ideas be bullet points:
* **Keep things Simple** - Simply express how your app should look at any given point in time, and React will automatically manage all UI updates when your underlying data changes.
* **Keep things Declarative** - When the data changes, React conceptually hits the "refresh" button, and knows to only update the changed parts.
* **Build Composable Components** - React is all about building reusable components. In fact, with React the only thing you do is build components. Since they're so encapsulated, components make code reuse, testing, and separation of concerns easy.

That's my two cents.  We'll let @zpao gatekeep this change.

**Comment by mikrofusion** [comment]
Thanks @jimfb.  I'd be glad to change this to the 3 bullet points you mention, pending any comments from @zpao or @spicyj.

**Comment by zpao** [comment]
Another option is that we just remove the whole "React has N main ideas" sentence and let it flow into the next heading.

**Comment by jimfb** [comment]
Ok, let's do that.  Ping @mikrofusion

**Comment by mikrofusion** [comment]
@jimfb as suggested I made the change to remove the sentence indicating "there are N main ideas".  I've rebased and squashed my commit.  
Please let me know if you have any feedback.

**Comment by jimfb** [comment]
Ok, looks good, thanks!

**Pull request merged**
