### PR TITLE
Remove spread operator

### PR DESCRIPTION
**Pull request by devtanc**
I believe what was meant here was to express that you would create the new player object _with all the previous properties of the existing player object_ in addition to now updating the score value. That being said, this is a simple example, and the player object clearly has no other values. Objects are not (by default) iterable using this operator, so this little piece does more harm than good for those who are new to the `...` operator.

### CODE REVIEW

**Comment by Aweary** [comment]
Thanks for the PR @devtanc! As you mentioned, the idea here is that we're using the spread operator to demonstrate how you can add/update properties and maintain all other existing properties without mutating.

I think that demonstration is more important than efficiency in this case. It might be a better idea to add some additional properties to the `player` object so the demonstration is clearer

> Objects are not (by default) iterable using this operator, so this little piece does more harm than good for those who are new to the ... operator.

That's a good point and I believe there has been discussion around using `Object.assign` instead, or adding a section explaining how to get object spread working first.

cc @lacker

**Comment by devtanc** [comment]
I thought that as well @Aweary, but with my lack of experience in React I wasn't 100% sure where things were going here. Either one of those options is good, maybe even both. I'll update to reflect that.

**Comment by devtanc** [comment]
Maybe a link of some sort that gives them the option to look over a separate page regarding getting object spread working would be useful, since it does clean up the code. That way it's there for further reading, but doesn't detract from the tutorial flow.

**Comment by lacker** [comment]
This looks pretty good. I tweaked it a bit to use semicolons and other little style bits. Thanks for submitting this pull request!

**Pull request merged**
