### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by exiadbq**
- remove function scope that not needed 
- don't have access to code pen though. todo for @gaearon 

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`).
6. Format your code with [prettier](https://github.com/prettier/prettier) (`npm run prettier`).
7. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
8. If you added or removed any tests, run `./scripts/fiber/record-tests` before submitting the pull request, and commit the resulting changes.
9. If you haven't already, complete the CLA.

### CODE REVIEW

**Comment by gaearon** [comment]
@brigand Can you look at this?

**Comment by brigand** [comment]
@exiadbq thanks! I added these changes to the [main tutorial PR](https://github.com/facebook/react/pull/9454).

I'm not sure how to give you credit for the commit.

**Comment by exiadbq** [comment]
@brigand nps, didn't know there was PR for that, otherwise I can commit there.

Closing this one for now.

**Comment by gaearon** [comment]
@brigand and I rewrote some parts of the tutorial in https://github.com/facebook/react/issues/9454, and following along should be easier now. Let us know if you're still struggling! We’re happy to look at remaining issues in case we missed anything.

https://facebook.github.io/react/tutorial/tutorial.html

**Comment by exiadbq** [comment]
Hi @gaearon what was your consideration not including this change?

```This event handler calls `this.props.onClick()`.``` 
Technically, the event handler calls  `onClick` rather than the result of `onClick()`. And `i` is a fixed value from the scope of `onClick={() => this.handleClick(i)}`

**Comment by gaearon** [comment]
Can you send another PR on top of the current changes, and I’ll take a look? Thanks!

**Pull request closed without merging**
