### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by urbanvikingr**
Added getDOMNode() in four statements where variables author and text were set.

E.g.
var author = this.refs.author.value.trim();
var text = this.refs.text.value.trim();

### CODE REVIEW

**Comment by yaycmyk** [comment]
@urbanvikingr It's not an error. Refs that are not composite components don't need `findDOMNode` anymore.

**Comment by zpao** [comment]
Yes, this is correct as written for v0.14. I appreciate the initiative though!

**Comment by urbanvikingr** [comment]
In that case, shouldn't the think like react example be updated?

**Comment by zpao** [comment]
Good catch. I just updated step 5 to remove those calls.

**Pull request closed without merging**
