### PR TITLE
[DevTools] Optimize Images (part 1)

### PR DESCRIPTION
**Pull request by ilhamsyahids**
## Summary

Image file size has been reduced by **25%** 

Details

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /packages/react-devtools-extensions/icons/128-development.png | 5.08kb | 2.28kb | 55.20% |
| /packages/react-devtools-extensions/icons/128-unminified.png | 5.08kb | 2.28kb | 55.20% |
| /packages/react-devtools-extensions/icons/128-deadcode.png | 5.08kb | 2.28kb | 55.20% |
| /packages/react-devtools/icons/icon128.png | 4.47kb | 2.10kb | 53.03% |
| /packages/react-devtools-extensions/icons/128-production.png | 4.47kb | 2.10kb | 53.03% |
| /packages/react-devtools-extensions/icons/48-unminified.png | 1.95kb | 1.03kb | 47.38% |
| /packages/react-devtools-extensions/icons/48-deadcode.png | 1.95kb | 1.03kb | 47.38% |
| /packages/react-devtools-extensions/icons/48-development.png | 1.95kb | 1.03kb | 47.38% |
| /packages/react-devtools-extensions/icons/128-outdated.png | 4.06kb | 2.17kb | 46.71% |
| /packages/react-devtools-extensions/icons/128-disabled.png | 4.68kb | 2.63kb | 43.76% |
| /packages/react-devtools-extensions/icons/48-production.png | 1.63kb | 0.92kb | 43.55% |
| /packages/react-devtools-extensions/icons/32-deadcode.png | 1.29kb | 0.77kb | 40.21% |
| /packages/react-devtools-extensions/icons/32-development.png | 1.29kb | 0.77kb | 40.21% |
| /packages/react-devtools-extensions/icons/32-unminified.png | 1.29kb | 0.77kb | 40.21% |
| /packages/react-devtools-extensions/icons/48-outdated.png | 1.53kb | 0.99kb | 35.48% |
| /packages/react-devtools-extensions/icons/32-production.png | 1.04kb | 0.69kb | 34.08% |
| /packages/react-devtools-extensions/icons/32-outdated.png | 1.07kb | 0.76kb | 29.04% |
| /packages/react-devtools-extensions/icons/48-disabled.png | 1.53kb | 1.11kb | 27.17% |
| /packages/react-devtools-extensions/icons/32-disabled.png | 1.07kb | 0.84kb | 21.61% |
| /packages/react-devtools-extensions/icons/16-development.png | 0.62kb | 0.55kb | 11.60% |
| /packages/react-devtools-extensions/icons/16-deadcode.png | 0.62kb | 0.55kb | 11.60% |
| /packages/react-devtools-extensions/icons/16-unminified.png | 0.62kb | 0.55kb | 11.60% |
| /packages/react-devtools-scheduling-profiler/src/assets/profilerBrowser.png | 75.65kb | 67.21kb | 11.16% |
| /packages/react-devtools-extensions/icons/16-production.png | 0.53kb | 0.49kb | 8.06% |
| /packages/react-devtools-extensions/icons/16-outdated.png | 0.54kb | 0.53kb | 3.41% |
| | | | |
| **Total :** | **129.12kb** | **96.40kb** | **25.34%** |

### CODE REVIEW

**Comment by gaearon** [comment]
How do we know this is correct? Can you provide screenshots before and after?

**Comment by IDrissAitHafid** [comment]
@gaearon, you can see the difference by viewing the changed files, and click on **Display on rich diff** for each file:
image

**Comment by eps1lon** [comment]
Execute `document.querySelectorAll('[aria-label*="rich diff"]').forEach((btn, i) => setTimeout(() => btn.click(), i * 1000))` in the chrome devtools console for https://github.com/facebook/react/pull/19972/files for easier review. 

These look all fine to me.

**Comment by ilhamsyahids** [comment]
@gaearon yes, you can always check it in files changes and check for **Display on rich diff** 

Thanks to @IDrissAitHafid for answering it and @eps1lon for providing easier code to check it.

**Comment by ilhamsyahids** [comment]
@gaearon is there anything that I should change?

**Comment by bvaughn** [comment]
@ilhamsyahids How'd you generate these?

**Comment by ilhamsyahids** [comment]
@bvaughn using bot/plugin that scan the images in the project and change them one by one with simplified size

**Comment by bvaughn** [comment]
@ilhamsyahids Which bot? (Is this reproducible when we need to update the images.)

**Comment by ilhamsyahids** [comment]
@bvaughn Imgbot

**Comment by kachkaev** [comment]
@ilhamsyahids could you share reproducible commands or instructions?

**Comment by ilhamsyahids** [comment]
@kachkaev I'm not sure, because its integrated with my account and its generated automatically

**Comment by ilhamsyahids** [comment]
@bvaughn @kachkaev is there any new image? Or there is something wrong using bot in this case?

**Comment by bvaughn** [comment]
> @bvaughn @kachkaev is there any new image? Or there is something wrong using bot in this case?

@ilhamsyahids There will likely be new images, yes.

The concern behind these questions are: How does someone else reproduce this result if you're unavailable.

**Comment by ilhamsyahids** [comment]
@bvaughn for instructions bot itself can be access in the website, and its completely free for open source.

**Comment by ilhamsyahids** [comment]
@bvaughn anyway, do you find something wrong in this PR or the result? Bot only work for images, in this PR I also restyle svg file. Before add new images, maybe we can optimize the old images.

**Comment by IDrissAitHafid** [comment]
@ilhamsyahids I think there may be some security concerns like steganography or some hidden script especially because we have no clue what algorithms that bot uses or what it is doing with the images.
I may be exaggerating, but I think I should mention this.

**Comment by ilhamsyahids** [comment]
> @ilhamsyahids I think there may be some security concerns like steganography or some hidden script especially because we have no clue what algorithms that bot uses or what it is doing with the images.
> I may be exaggerating, but I think I should mention this.

@IDrissAitHafid  For code itself, you can check here https://github.com/dabutvin/Imgbot and it has been offered by Github Student Developer, check this out https://education.github.com/pack?tag=Infrastructure+%26+APIs 
Also in the official website, it says that it has been used in several company.

**Comment by ilhamsyahids** [comment]
Hi, is there anything that I can update for this PR?

**Comment by bvaughn** [comment]
@ilhamsyahids We'd need a Node script to run that automatically generates/updates these images, so that it could be done (in CI) as part of our build and release process.

**Review by bvaughn — CHANGES_REQUESTED** [review]
@ilhamsyahids We'd need a Node script to run that automatically generates/updates these images, so that it could be done (in CI) as part of our build and release process. Unfortunately visiting a website and manually updating the images doesn't really fit with how we manage releases, at this scale.

**Comment by ilhamsyahids** [comment]
@bvaughn We shouldn't visit the web and manually update. Only add [it](https://github.com/marketplace/imgbot) to the repo and it works as a trigger to create PR for optimized images. But, if we want to create Node script, alternatively, we can use Imagemin. What do you think?

**Comment by bvaughn** [comment]
I think I'm open for either, so long as it's an automated thing.

**Comment by ilhamsyahids** [comment]
For option one, I cant proceed (only who is part of the organization), let me try the second one.

**Comment by ilhamsyahids** [comment]
I made another PR, #21968 for automated optimized images. Please kindly check it.

cc: @bvaughn

**Pull request closed without merging**
