### PR TITLE
Add basic issue and PR templates

### PR DESCRIPTION
**Pull request by maxdeviant**
Happy to discuss and tweak the templates, as desired. This PR is more to get the general subject of adding GitHub issue and PR templates on the table.

I adapted the issue template from the [Angular](https://github.com/angular/angular.js/blob/master/.github/ISSUE_TEMPLATE.md) one, and adapted the PR template from the PR guidelines in CONTRIBUTING.md.

### CODE REVIEW

**Comment by jimfb** [comment]
Seems like a reasonable start.  I know @zpao has given some thoughts to templates.

**Comment by jimfb** [comment]
@zpao Accept / decline?

**Comment by maxdeviant** [comment]
@jimfb @zpao Any word on this?

**Comment by zpao** [comment]
We'll probably change it later but this seems like a good place to start. Thanks!

**Pull request merged**
