### PR TITLE
Remove error reference to the 'render' function

### PR DESCRIPTION
**Pull request by Volga**
What is the `render` function of a functional component?

### CODE REVIEW

**Comment by gaearon** [comment]
@aweary Btw feel free to run the sync script any time you like. I try to do that once in a while but would be cool if somebody else did too. 😄

**Comment by aweary** [comment]
@gaearon awesome, thanks. I was curious if there was a schedule or something for it. I'm happy to take that over so you can focus elsewhere 😃

**Comment by gaearon** [comment]
Thanks! No real schedule, once in a few days would be nice. Thank you so much!

**Comment by gaearon** [comment]
Our building hook is broken right now but we'll soon get it fixed.

**Pull request merged**
