### PR TITLE
[Gatsby] Darkened line-highlight to increase contrast

### LINKED ISSUE #10925: [website] highlighted lines in code snippets don't have enough contrast
**Do you want to request a *feature* or report a *bug*?**
This is an accessibility issue with the new documentation website.

It's a clear-cut problem, but the solution is pretty open ended and ill defined. Might be difficult, and could use some design creativity.

**What is the current behavior?**
We are using [Prism.js](http://prismjs.com/) for the syntax highlighting styles of our code snippets. We also sometimes want to "highlight" a certain line, so we lighten the background of that line. With the lighter background, many of the font colors don't provide enough contrast.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/ebsrpraL/).**

You can verify this by [running the aXe a11y audit](https://www.deque.com/products/axe/) on this page: https://reactjs.org/docs/introducing-jsx.html

**What is the expected behavior?**

We need a way to highlight a line without losing so much contrast.

BUT choosing a different hue without making it lighter looks bad in my opinion, and I would rather not fiddle with the various font colors used in the syntax highlighting.

We should either collaborate with the Prism project to add a 'highlight' option with enough contrast, or find another library/system to use for syntax highlighting.

### PR DESCRIPTION
**Pull request by joecritch**
cc @flarnie @bvaughn 

fixes #10925

### CODE REVIEW

**Comment by gaearon** [comment]
It feels a bit unusual but I agree it makes those blocks jump out more, and that's probably good.
Leaving to @bvaughn

**Comment by joecritch** [comment]
@gaearon I know what you mean about it feeling unusual. FWIW, here's an option, with a blue "current" line on the left. Thoughts? (Indentation would be fixed if I implemented it.) 

screen shot 2017-09-28 at 20 20 25

**Comment by gaearon** [comment]
Yea, maybe this would work better.

**Comment by joecritch** [comment]
@gaearon https://deploy-preview-10931--reactjs.netlify.com/docs/composition-vs-inheritance.html

**Comment by gaearon** [comment]
I'll let @bvaughn make the final call on this. I'm not sure.

**Comment by joecritch** [comment]
Sweet, I'm not particularly opinionated on this either :) Happy to remove the blue.

**Comment by bvaughn** [comment]
Subjectively, I strongly dislike the left blue border 😄  I don't think it looks very IDE-like.

I'm not a huge fan of the super-dark highlight either, but it does make things pop more and if it helps with accessibility I think it's okay 👍

**Comment by joecritch** [comment]
@bvaughn The border is officially gone 💥

**Pull request merged**
