### PR TITLE
Gatsby fix embedded videos

### PR DESCRIPTION
**Pull request by bvaughn**
Added explicit widths (as required by `gatsby-remark-responsive-iframe`) to all embedded videos:
https://www.gatsbyjs.org/packages/gatsby-remark-responsive-iframe/

### CODE REVIEW

**Comment by flarnie** [comment]
PS I haven't manually tested yet - doing that now.

**Comment by bvaughn** [comment]
It's responsive. This just sets the width that governs the aspect ratio.

**Comment by flarnie** [comment]
Ah - disregard my concerns, looks like that plugin makes the videos behave in a responsive way. They look great!

happyjello

**Comment by bvaughn** [comment]
Cool beans, thanks!

**Pull request merged**
