### PR TITLE
Replace KeyboardEvent.key 'Dead*' with 'Dead' (FireFox)

### PR DESCRIPTION
**Pull request by syranide**
What the title says.

http://www.w3.org/TR/DOM-Level-3-Events-key/#keys-composition

### CODE REVIEW

**Comment by zpao** [comment]
I don't care a bit about extra weight. I'm not sure how much of an issue it is or if the `Dead*` list browsers will disappear quickly. cc @salier because IME.

**Comment by sebmarkbage** [comment]
I don't think we should add it until someone asks for it or needs a workaround.

**Comment by zpao** [comment]
Ok fine by me.

**Comment by syranide** [comment]
:+1:

For posterity, this PR is only for FF misbehaving (even latest IIRC) and I believe the support is shoddy across the browsers anyway, so no loss.

**Pull request closed without merging**
