### PR TITLE
Avoid "Member not found" error in IE

### PR DESCRIPTION
**Pull request by g-palmer**
Explanation, discussion, and similar change as #7343

Addresses #7320

### CODE REVIEW

**Comment by facebook-github-bot-8** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by g-palmer** [comment]
Don't mean to bug you guys and apologies in advance if I am, but is there anything I specifically need to do to get this reviewed?

**Comment by Aweary** [comment]
@g-palmer hey, we appreciate being bugged here and there. It's easy for stuff to fall through the cracks, so thanks for the reminder.

This seems like a good and safe change 👍  thanks!

**Comment by gaearon** [comment]
Would be nice to add an explanatory comment linking to the issue everywhere we do this.

**Comment by g-palmer** [comment]
Sure thing. Would it make sense if I just updated this same branch with the additional comment(s) and opened a new PR? Or do you prefer a new branch as well as a new PR?

**Comment by gaearon** [comment]
Since this is already merged I think new branch would make more sense.

**Pull request merged**
