### PR TITLE
Add Popover API support

### LINKED ISSUE #27479: Bug: Popover API not supported
About this API:  https://developer.mozilla.org/en-US/docs/Web/API/Popover_API

React version: any

## Steps To Reproduce
```jsx
      <div popover id="my-popover">
        Greetings, one and all!
      </div>
      <button popovertarget="my-popover" popovertargetaction="show">
        Open Popover
      </button>
      <input
        type="button"
        popovertarget="my-popover"
        popovertargetaction="hide"
        value="Close Popover"
      />
```

Link to code example: https://codesandbox.io/s/popover-api-8x5nfq?file=/src/App.js

## The current behavior
- Error in console:
  > Warning: Received `true` for a non-boolean attribute `popover`.

- `popover` attribute wasn't added to `div`

It works if I change boolean atribute `popover` to `popover="yes"`.

Also ESLint fails on unknown `popover`, `popovertarget`, `popovertargetaction` attributes.

### PR DESCRIPTION
**Pull request by Semigradsky**
## Summary

Closes #27479

I tried to update `fixtures/attribute-behavior/AttributeTableSnapshot.md` but I got error in browser console:
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'unstable_cancelCallback')

### CODE REVIEW

**Comment by Semigradsky** [comment]
@jackpope Now in `main` branch I have new error in console:
```
App.js:359 Uncaught (in promise) Error: Tag mismatch. Expected: img
    at getRenderedAttributeValue (App.js:359:1)
    at getRenderedAttributeValues (App.js:416:1)
    at prepareState (App.js:454:1)
    at App._callee$ (App.js:823:1)
    at tryCatch (runtime.js:65:1)
    at Generator.invoke [as _invoke] (runtime.js:303:1)
    at prototype.<computed> [as next] (runtime.js:117:1)
    at step (fetch.js:461:1)
    at fetch.js:461:1
```

Document title is `src (string)`

**Comment by Semigradsky** [comment]
@jackpope I have tried several times (more than 5 already) and I always have this error.

**Comment by acusti** [comment]
i’m very excited for this to land! the browser console errors and linting errors are painful. @Semigradsky @jackpope do either of you know how much of a lift it would be to extend support to include the new [`toggle` and `beforetoggle` events](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API#events) associated with the Popover API?

**Comment by eps1lon** [comment]
Alternate with proper overrides for the attribute-behavior fixture: https://github.com/facebook/react/pull/27981

**Comment by eps1lon** [comment]
Fixed in https://github.com/facebook/react/pull/27981

**Comment by dominictobias** [comment]
Would be great if this was added to React 18

**Pull request closed without merging**
