### PR TITLE
Calculate build sizes relative to merge base

### PR DESCRIPTION
**Pull request by gaearon**
See https://github.com/facebook/react/pull/11882#issuecomment-352539331.

### CODE REVIEW

**Comment by gaearon** [comment]
Hmm, we don't want the merge base here. We want the branch that the PR was sent against.
I'm not sure how to get that.

**Comment by sophiebits** [comment]
maybe CIRCLE_COMPARE_URL?

**Comment by gaearon** [comment]
Seems like that's just a URL so we'd have to parse it.

Also not sure what this means:

>Not present for builds that are triggered by GitHub pushes.

Aren't all builds triggered by pushes?

**Comment by sophiebits** [comment]
Yeah, PR vs push.

**Comment by gaearon** [comment]
Even CIRCLE_COMPARE_URL isn't helpful 😞 
It only shows the last commit, e.g. https://github.com/facebook/react/compare/af469c440b8e...27836c787e99 for the last run.
Not the actual PR's base.

**Comment by gaearon** [comment]
Looks like @orta also bumped into this. https://github.com/danger/danger/issues/45

**Comment by orta** [comment]
Yeah, Circle can be real tricky to gather this kind of information - in Danger Ruby we use the [Circle API](https://github.com/danger/danger/blob/master/lib/danger/ci_source/circle_api.rb) to grab [the PR](https://github.com/danger/danger/blob/master/lib/danger/ci_source/circle.rb#L59-L84) and then use that to pull out the metadata like base/head.

**Comment by zpao** [comment]
One thing worth noting - if we still aren't doing builds for docs, the merge base might be a commit that we don't have a build for.

Otherwise, I made it possible to jump straight to the commit without needing to look at the commit time. Just /builds/branch/_commits/SHA eg: http://react.zpao.com/builds/master/_commits/247c5241706356033cd5bf1dc31197e058853e13/

**Comment by gaearon** [comment]
Closing since this is broken.

**Comment by sophiebits** [comment]
@gaearon We can use GitHub's API as @orta described, right? Maybe we can goodfirsttask it if you don't have time to follow up.

**Comment by gaearon** [comment]
I think @orta did something in https://github.com/facebook/react/pull/11865 that fixes this.

**Pull request closed without merging**
