### PR TITLE
Pass event obj to the method

### PR DESCRIPTION
**Pull request by mitenka**
*Before* submitting a pull request, please make sure the following is done...

1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`) - we've done our best to make sure these rules match our internal linting guidelines.
6. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

### CODE REVIEW

**Comment by aweary** [comment]
Thanks for the PR @mitenka! I think the change is good (as it demonstrates the argument is passed on the the class method), but it feels weird not actually using it. Can you think of a way we can update the example so it actually *uses* the `e` argument? (maybe logging out `e.target.value` along with `this`)?

**Comment by gaearon** [comment]
Let's not add "needs merge to stable" until we merge to master? Otherwise it's easy to accidentally get it merged before it's approved.

**Comment by aweary** [comment]
My bad, I usually add labels after merge, guess it's a habit adding both at once

**Comment by mitenka** [comment]
@aweary, maybe it would be better to remove `e` argument from `this.handleClick(e)` calling in the arrow function?

**Comment by kkemple** [comment]
@aweary is there any more work to do on this, or is this just in need of review?

**Comment by bvaughn** [comment]
Thank you for submitting this PR! 😄 

Unfortunately the documentation and source code for reactjs.org has been moved to a different repository: https://github.com/reactjs/reactjs.org

If you are willing, please open a new PR there. Sorry for the inconvenience!

(For more backstory on why we moved to a new repo, see issue #11075)

**Pull request closed without merging**
