### PR TITLE
fix: calling onblur event on unmount

### PR DESCRIPTION
**Pull request by Biki-das**
Working wit React, there was a small bug i discovered, related to unmounting off a particular element in the DOM, in vanilla JS whenever a particular item gets removed from the DOM, an `onBlur` event is triggered automatically, as said in MDN 
Screenshot 2024-03-05 at 6 30 36 PM
[MDN LINK](https://developer.mozilla.org/en-US/docs/Web/API/Element/blur_event)
React simply does not seem to call this `onBlur` event when a particular element is unmounted, i might be wrong to judge why the same wasn't implemented in the context of react, anyways this would mean a learning opportunity for me to understand react design principles more better.

here is a Vanilla Js repro of the onBlur being called

https://github.com/facebook/react/assets/72331432/71764d95-8cf1-46f4-870c-7260496eb4ed

[Vanilla JS codesandbox repro](https://codesandbox.io/p/sandbox/thirsty-dew-m3c9rw?file=%2Fsrc%2Findex.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltebycuk00063b7gmdoekmb7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltebycuk00023b7gkqj1jfl5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltebycuk00033b7g0lpr7ihd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltebycuk00053b7giz3n0fay%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltebycuk00023b7gkqj1jfl5%2522%253A%257B%2522id%2522%253A%2522cltebycuk00023b7gkqj1jfl5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltecjrm500023b7gfcgihboa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltecjrm500023b7gfcgihboa%2522%257D%252C%2522cltebycuk00053b7giz3n0fay%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltebycuk00043b7gf3vg0hzn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltebycuk00053b7giz3n0fay%2522%252C%2522activeTabId%2522%253A%2522cltebycuk00043b7gf3vg0hzn%2522%257D%252C%2522cltebycuk00033b7g0lpr7ihd%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltebycuk00033b7g0lpr7ihd%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257Dl)

here is the React Codesandbox example, check console as the `onBlur` is not called

https://github.com/facebook/react/assets/72331432/f12b66bf-5bb9-4a0b-a0f5-aa37c57c3119

[React Sandbox Link](https://codesandbox.io/p/sandbox/react-blur-cyffzf?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltecd0id00063b7g9dw8muas%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltecd0ic00023b7gfaq73wrr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltecd0ic00033b7gu9schf65%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltecd0ic00053b7gw8foqyy4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltecd0ic00023b7gfaq73wrr%2522%253A%257B%2522id%2522%253A%2522cltecd0ic00023b7gfaq73wrr%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltecd0ic00053b7gw8foqyy4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltecd0ic00043b7gtgtst7qn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltecd0ic00053b7gw8foqyy4%2522%252C%2522activeTabId%2522%253A%2522cltecd0ic00043b7gtgtst7qn%2522%257D%252C%2522cltecd0ic00033b7gu9schf65%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltecd0ic00033b7gu9schf65%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

The fix i proposed here is  if the deletedFiber object has `memoizedProps` and if those `memoizedProps` contain an `onBlur` property. If both conditions are true, it calls the onBlur function with a new blur event.
I have added a test for the same, to not allow regression to occur

Tested on the fixtures file after running `yarn build` 
Passing Test
Screenshot 2024-03-07 at 1 48 03 PM

https://github.com/facebook/react/assets/72331432/badedda2-94fa-46b0-a1e7-3c24e9dd26ae

This Behaviour falls under the category where React and Vanilla JS act differently , earlier i raised #27016 , reviewed by sophie , which concluded to refer away from custom event logic as of now, as the future of react seems to get rid of  React event system logic and rely on browser event system.

tagging @sebmarkbage @sophiebits @acdlite @rickhanlonii  , would love to know all of your thoughts and what you feel about this.

### CODE REVIEW

**Comment by Biki-das** [comment]
@hoxyq , would love to also know your thoughts

**Comment by Biki-das** [comment]
@sophiebits could you provide some feedback on this? mostly i feel this might not be appropriate though i don have much clarity compared to the core team!

**Comment by sophiebits** [comment]
hi @Biki-das — in a future React release we'll likely add React event listeners directly to DOM nodes so we would inherit the browser behavior with no additional work. it sounds like in this case we have an onBlur event that is fired by the browser after we remove the node, which means that by the time React processes it, the tree is fully unmounted and so we ignore the event

a proper fix here would need to somehow change that so that the event gets through — the implementation as you have it (a) would not bubble the event correctly to any ancestor nodes, (b) is DOM-specific but is in a file that is shared across renderers, so it definitely can't be landed in this state. as a result, I'm going to close this PR since it would need to be implemented in a very different way to make sense with the current codebase and I'm not sure offhand if/how we could do that

thanks for taking a look!

**Comment by Biki-das** [comment]
got it and thanks for the detailed feedback, so the concept of synthetic events are kinda non existent now @sophiebits ?

**Pull request closed without merging**
