### PR TITLE
Upgrade devtools extension manifest to version 3

### LINKED ISSUE #24522: [DevTools] Manifest version 2 is deprecated
### Website or app

https://developer.chrome.com/blog/mv2-transition/

### Repro steps

Use latest React DevTools with Electron (Chromium) (18.2.0 / Chromium 100)

```
  (node:80082) ExtensionLoadWarning: Warnings loading extension at ./node_modules/electron-devtools-vendor/extensions/react-developer-tools:
    Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
```

### How often does this bug happen?

Every time

### DevTools package (automated)

_No response_

### DevTools version (automated)

_No response_

### Error message (automated)

_No response_

### Error call stack (automated)

_No response_

### Error component stack (automated)

_No response_

### GitHub query string (automated)

_No response_

### PR DESCRIPTION
**Pull request by AnmolBansalDEV**
resolves #24522 

## Summary
since google is pulling the plug on manifestV2, I upgraded the manifest.json files for chrome, edge, and firefox to V3

## How did you test this change?
I checked against the [google guide](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/) for all changes being made.

### CODE REVIEW

**Comment by mondaychen** [comment]
Thanks for the contribution!
I'll look into this on Monday. Just FYI it might take some time before we can merge this, because we need to make sure all the features still work fine with V3, on all 3 browsers we support.

I'm actually surprised no JS file needed to be changed. For example, according to [this section](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#action-api-unification), `chrome.browserAction` needs to be changed to `chrome.action`.

**Comment by chapmanm3** [comment]
To add to @mondaychen 's comment I took a look into this issue and I think because of the switch from background pages to service workers with V3 [link](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#background-service-workers) There is no longer access to `XMLHttpRequest` which happens [here](https://github.com/facebook/react/blob/17e2a15bea2df9232411a35c6d967fa18f6e8b25/packages/react-devtools-extensions/src/injectGlobalHook.js#L124), that logic may also need to be updated.

**Comment by mondaychen** [comment]
How did you test the extension? I'm getting this error when loading the local build
image

**Comment by mondaychen** [comment]
@AnmolBansalDEV You can just ask in the original issue. In fact, I'd recommend you to figure out how to test the extension before you create a PR about it. I'll close it for now since it looks like you need to get a lot done before it's ready for review.

**Comment by mondaychen** [comment]
To answer your question regarding XHR, you can wrap the logic into the `then` of the Promise

**Pull request closed without merging**
