### PR TITLE
Add startOffset to supported SVG Attributes

### PR DESCRIPTION
**Pull request by iuriikozuliak**
It's really handy for axis labels in pie/radar/etc charts.

### CODE REVIEW

**Comment by zpao** [comment]
cc @gaearon - I'm going to put you in charge of making sure anything else that isn't normal/hyphenated works :)

cf. #5714

**Comment by gaearon** [comment]
This will "just work" after #5714.
Everything that's not on our list will just pass through as is so I think we can safely close this.

**Comment by gaearon** [comment]
Verified that `startOffset` is passed through in the master.

**Comment by tnrich** [comment]
Hey @gaearon , thanks for all the awesome work improving React's handling of SVG's. I'm running into an issue where it doesn't appear my startOffset is making it through to the dom: 

Here's my JSX element with a startOffset attribute:
```js
<text x='0' y='0'>
                             <textPath xlinkHref={`#${id}`} startOffset={"50%"}>
                                 {label}
                             </textPath>
                         </text>
```

And here's a snapshot of the DOM:

image

The xlink:href seems to make it through, but the startOffset doesn't. I'm using "react": "^0.14.3". Any ideas as to what might be going wrong? Thanks!

**Comment by gaearon** [comment]
>I'm using "react": "^0.14.3".

This is fixed in master, but that master refers to v15 release.
It’s going to drop very soon so stay tuned!

Cheers.

**Comment by tnrich** [comment]
Good to hear, thanks very much! Until then your:
```
ref={(node) => {
                                      node && node.setAttribute("startOffset", '24%')
                                    }}
```
trick is working well :)

**Pull request closed without merging**
