### PR TITLE
Use CommonJS outside of src

### PR DESCRIPTION
**Pull request by gaearon**
This might help fix the issue @trueadm was seeing when upgrading Jest.

### CODE REVIEW

**Comment by gaearon** [comment]
I guess this breaks the build. :-(

@trueadm If you prepare a PR with Jest upgrade, I can look at it.

**Comment by acdlite** [comment]
Hmm is this because we don't run Babel on those files? Curious why this changed between Jest versions

**Comment by necolas** [comment]
https://github.com/facebook/react/pull/17896

**Comment by trueadm** [comment]
This isn't needed anymore. Thanks for the help anyway!

**Pull request closed without merging**
