### PR TITLE
refactor[shared]: some changes from let to const

### PR DESCRIPTION
**Pull request by luas10c**
## Summary

improve code readability, change from conventional if to ternary.

## How did you test this change?

I performed all the tests with yarn test --prod, as there are no visual modifications I didn't see the need to test on screens, the modification is not visual, it is just performance and readability.

### CODE REVIEW

**Comment by poteto** [comment]
hey! thanks for the PR. generally we don't accept syntax refactors like this as readability is subjective

**Comment by DarkCat5501** [comment]
PR de merda TNC, tava uma merda, ficou uma bosta

**Comment by lucasferreiralimax** [comment]
> ## Summary
> improve code readability, change from conventional if to ternary.
> 
> ## How did you test this change?
> I performed all the tests with yarn test --prod, as there are no visual modifications I didn't see the need to test on screens, the modification is not visual, it is just performance and readability.

Great change! Using the ternary operator made the code more concise and readable. I love how the logic is now clearer and easier to follow while maintaining performance. Kudos for taking the initiative to enhance the code quality!

**Comment by DarkCat5501** [comment]
@poteto I so sorry that my friend bothered you, he just wanted to contribute to some project to be hired as junior

**Pull request closed without merging**
