### PR TITLE
Update example to ES6 syntax

### PR DESCRIPTION
**Pull request by ZakariaRidouh**
This PR updates the example found in the README file to ES6. If you guys are interested in updating all the examples to ES6, just ping me and I can help out 😄 

Thanks!

### CODE REVIEW

**Comment by ZakariaRidouh** [comment]
any news about this getting merged?

cheers!

**Comment by brigand** [comment]
The readme should probably stay es5 for noob friendliest. Slightly off topic, but maybe the docs should have a switch for code blocks to make them es6, but maybe that's too much to maintain and set up.

**Comment by syranide** [comment]
The only thing that strikes me as odd about the current setup is, sure it is beginner-friendly, but it's also kind of alienating to experienced people who start using `React.createClass` without knowing ES6 is an option until much later and then you feel kind of cheated. If we believe that ES6 is the future then we should at least make it obvious, but recommend less experienced people to use `React.createClass`?

**Comment by gaearon** [comment]
Please see https://github.com/facebook/react/issues/3710#issuecomment-233420752 — we’ll consider this as part of a larger effort later.

**Comment by ZakariaRidouh** [comment]
@brigand, The React Native docs are already using ES6 in their examples. Just wanted to throw it into the discussion. Also, does the React team plan to eventually remove `React.createClass` in the future? If so, I think this would be optimal to start the transition. 

Cheers!

**Comment by gaearon** [comment]
@ZakariaRidouh Can you please also update examples on the homepage? Currently they are implied to be in sync, but they are not.

**Comment by gaearon** [comment]
I wanted to tweak this but the fork is no longer available so I can’t make changes outside of GH interface. I’ll close this PR. Sorry we didn’t get this merged earlier!

**Pull request closed without merging**
