### PR TITLE
Float: Stringify `crossorigin="anonymous"`

### PR DESCRIPTION
**Pull request by eps1lon**
## Summary

`` now creates the corresponding `<link rel="preload" />` tag preserving `crossOrigin` since [`anonymous` is a valid value for `crossOrigin`](https://html.spec.whatwg.org/multipage/urls-and-fetching.html#cors-settings-attributes). 

It doesn't change production behavior since it results in the same state. Mainly to just reduce confusion but then `crossOrigin="some-non-existing-value"` would also result in `crossorigin=""` so maybe that's fine?

## How did you test this change?

Added test for ``. Other tests were also updated so I'm curious if ignoring `anonymous` is intended for `preconnect`.

I also added a test showing how `crossOrigin` doesn't factor into keying. Mostly to show the difference between how Float and `next/legacy/image` differs with regard to preloading. `next/legacy/image` currently adds a `<link rel="preload" />` matching `crossOrigin` of the **last** `` with the same key whereas Float uses `crossOrigin` from the **first** image.

### CODE REVIEW

**Comment by gnoff** [comment]
The spec doesn't show it clearly but the invalid value state is also anonymous so conceptually I've been thinking about crossorigin as just a tri-value. missing, "", and "use-credentials" to map to no cors, anon cors, and credentials

The other reason to use empty string aggressively is that it's just shorter. Are you concerned that folks will look at the tag and think something is wrong? or that the spec might change in the future and make this optimization semantically breaking? (I doubt they could do the latter given the hesitance to break the web so I feel pretty confident we can leave this be)

**Comment by eps1lon** [comment]
> The other reason to use empty string aggressively is that it's just shorter. Are you concerned that folks will look at the tag and think something is wrong? 

I did 😅 Mainly because I got confused by the spec (empty value and `crossorigin` meaning the same thing) but also because it differs from how we SSR ``.

I wouldn't have filed this if I understood that the empty value is the same as `crossorigin="anonymous"`. But now that it's open, and in the light of how difficult it is to land new attribute (values) in React, I'm wondering if we should optimize for bytes saved or future compatibility (i.e. don't normalize the string value at all and stringify it as-is). In the end, people can still opt for bytes saved by passing `crossOrigin: ''`, no?

**Comment by gnoff** [comment]
Well, the thing that is different here is you aren't rendering the preload link yourself. This tag is owned by the react runtime so we're not really altering a user value. I suppose you could argue that `ReactDOM.preload(..., { crossOrigin: "anonymous" })` is a user value but even still I think you are saying you want anonymous CORS mode not that you want a specific tag with a specific attribute.

So I don't think we need to extrapolate too much that we're different if you render  you get one serialization but the preload link doesn't match

**Comment by eps1lon** [comment]
Yeah makes sense

**Pull request closed without merging**
