### PR TITLE
do not validate propTypes in production

### PR DESCRIPTION
**Pull request by jergason**
Fixes issue #2938

### CODE REVIEW

**Comment by zpao** [comment]
cc @sebmarkbage

**Comment by sebmarkbage** [comment]
Our policy is that execution flows shouldn't differ between `__DEV__` and production modes. This will throw on an invalid prop type in `__DEV__` but not in production. This can have unforseen consequences. E.g. a component only shows up in production but is completely hidden in development.

If you switch to use the `warning` module instead of an `invariant`, like checkPropTypes does, you can avoid that problem. Also, make sure that nothing along the way to the warning throws.

**Comment by jergason** [comment]
@sebmarkbage Thanks for the hand-holding. I'll tweak this!

**Comment by kentcdodds** [comment]
Is there a reason we don't just put the `__DEV__` check in the `validateTypeDef` function rather than wrapping every invocation to it? Or even adding a wrapper function called `validateTypeDefDev` or something. Maybe that's an unnecessary abstraction or I'm missing some design principle. I just personally prefer typing less :-)

**Comment by chicoxyzzy** [comment]
> Our policy is that execution flows shouldn't differ between __DEV__ and production modes. This will throw on an invalid prop type in __DEV__ but not in production.
@sebmarkbage BTW that's not always true. see #2864 and #2868

**Comment by jergason** [comment]
Okay, I swapped it to use `warning`, fixed the tests, and rebased in master. @sebmarkbage looks ok now?

**Comment by sebmarkbage** [comment]
Looks good to me!

**Pull request merged**
