### PR TITLE
Remove sliceChildren

### PR DESCRIPTION
**Pull request by aweary**
Another file that looks unused. It's not exposed via any public API like `React.Children` and is not required anywhere internally in react, react-native, or react-art.

Similar situation as https://github.com/facebook/react/pull/9107. Looks unused, but maybe not 😄

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Well this is used by code internally at FB so maybe we __should__ expose it publicly rather than just keeping it as an internal helper?

**Comment by gaearon** [comment]
It predated `toArray`. I think we should just change internal callers to use `toArray` instead.

**Comment by sebmarkbage** [comment]
Currently the helper is simple but we could optimize it more on our end since we don't have to first create a large array with adjusted keys and then take a small subset of those.

**Comment by sebmarkbage** [comment]
Like one of our use cases is:

```js
<div>
  {sliceChildren(this.props.children, 0, 1)}
</div>
<div>
  {sliceChildren(this.props.children, 1)}
</div>
```

This is really inefficient for any significant number of children. Especially if they're nested.

The `toArray` helper was not added as a best-practice but more as a compromise to make it easy when it doesn't matter but it is still terrible for perf.

**Comment by gaearon** [comment]
>The toArray helper was not added as a best-practice but more as a compromise to make it easy when it doesn't matter but it is still terrible for perf.

Ah okay. My concern was the opposite: the method <s>really</s> makes you think it's optimized but uses `toArray` under the hood.

**Comment by sebmarkbage** [comment]
Maybe we should just unify on lodash's lazy evaluation chained "Seq Methods".

**Pull request merged**
