### PR TITLE
More conservative dependency update.

### PR DESCRIPTION
**Pull request by bhamodi**
@zpao - this is a more conservative approach to updating some of the dependencies. Let me know what you think!

### CODE REVIEW

**Comment by mathieumg** [comment]
I think this does the opposite of what you think, see http://stackoverflow.com/a/22345808/564163

**Comment by jimfb** [comment]
@zpao is out of town.  I suspect that @mathieumg is correct and this does not do what we want, but @spicyj understands our build/packaging so we'll let him weigh in.

**Comment by bhamodi** [comment]
Ohhh I see what you guys are saying. I didn't mean conservative as in tilde versus hat. My bad in word choice. I was actually referring to being more conservative in how I attempted to update dependencies  compared to my previous PR #4125. I do understand that `^` will update both minor and patch as opposed to `~` just updating patch versions. :) :+1:

**Comment by zpao** [comment]
Yea this is fine. `coverify` is the only one that looks like it has any risk (but not sure if we actually even run the coverage builds right now), the rest are close enough.

**Comment by bhamodi** [comment]
:+1:

**Comment by jimfb** [comment]
@zpao I noticed you accepted but didn't merge.  Is this blocking on anything?

**Comment by zpao** [comment]
Nope! Merged now

**Pull request merged**
