### PR TITLE
Missing a space for error 125

### PR DESCRIPTION
**Pull request by philraj**
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).
5. Make sure your code lints (`npm run lint`).
6. Run the [Flow](https://flowtype.org/) typechecks (`npm run flow`).
7. If you added or removed any tests, run `./scripts/fiber/record-tests` before submitting the pull request, and commit the resulting changes.
8. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

### CODE REVIEW

**Comment by aweary** [comment]
Thanks for the PR @philraj! This is a generated file that pulls out invariant messages from the codebase for production, so generally, we wouldn't want to edit this file directly. In this case, this the error was actually removed in https://github.com/facebook/react/pull/8176 so it shouldn't even be there in the first place. I'll look into why its not being removed.

Thanks again though!

**Comment by aweary** [comment]
Alright, so per the script's [`README`](https://github.com/facebook/react/blob/master/scripts/error-codes/README.md#note-for-cutting-a-new-react-release) it is not supposed to delete old errors (make sense, as we still want to be able to report the production error message for applications running older versions that still have the invariant).

I think editing it in this case is fine since the actual error itself does not exist in the source anymore, but we want to preserve it. Re-opening and merging 👍

**Comment by gaearon** [comment]
I reverted in https://github.com/facebook/react/pull/8994—this is an autogenerated file. 😉

**Comment by gaearon** [comment]
Oh wait, I missed the part about this error being removed in the source. You're right it should be fine then.
My bad 😞

**Comment by aweary** [comment]
No worries! I thought the same when I saw this. I opened a PR to revert the revert: https://github.com/facebook/react/pull/8995

**Comment by philraj** [comment]
Happy to help, minor as it may be 😌. Keep up the good work on React.

**Pull request merged**
