### PR TITLE
Scheduler: Unref the MessageChannel instance and allow the thread to exit

### LINKED ISSUE #26608: Bug: MessageChannel in Scheduler prevents Jest test from exiting
React version: any
Scheduler version: any up to current (0.23.0)

## Steps To Reproduce

1. Create Jest unit test.
2. Select JSDom as test environment so that runtime will not have `setImmediate` function.
3. JSDom still does not implement `MessageChannel` https://github.com/jsdom/jsdom/issues/2448. If `MessageChannel` is required to test some important functionality, one can add an implementation from Node.js as recommended in comment https://github.com/jsdom/jsdom/issues/2448#issuecomment-536242756
    ```js
    window.MessageChannel = require('node:worker_threads').MessageChannel;
    ```
4. Add Scheduler or React as a dependency and require it in the test or one of the files under test.
5. Run test

Link to code example: https://github.com/victor-homyakov/scheduler-jest-jsdom-example

## The current behavior

Test is endless. Jest won't stop. Console shows a message
```
Jest did not exit one second after the test run has completed.

'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

Running Jest with `--detectOpenHandles` outputs:

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  MESSAGEPORT

    > 1 | require('scheduler');
        |                     ^

      at node_modules/scheduler/cjs/scheduler.development.js:569:17
```

## The expected behavior

Code at https://github.com/facebook/react/blob/5426af3d50ff706f3ebeb4764f838e0a3812bf9a/packages/scheduler/src/forks/Scheduler.js#L621 should `unref` the handle:

```js
  channel.port1.onmessage = performWorkUntilDeadline;
  // Allow the thread to exit if this is the only active handle in the event system
  if (channel.port1.unref) {
    channel.port1.unref();
  }
```

### PR DESCRIPTION
**Pull request by victor-homyakov**
## Summary

Fixes #26608 

## How did you test this change?

It is still unclear to me how to test this because test requires separate Jest setup.

### CODE REVIEW

**Comment by s100** [comment]
Bump, yes, I would still like this fix to be applied, we are currently having to apply a [quite ugly workaround](https://github.com/facebook/react/issues/26608#issuecomment-1734172596) to get the behaviour we actually want.

**Comment by s100** [comment]
I would have bumped this PR when I was prompted but you had the permissions configured to make it impossible for me to do that.

**Comment by victor-homyakov** [comment]
Reopen, please. It's a nice trick to close during summer vacations.

**Comment by victor-homyakov** [comment]
Reopen, please

**Pull request closed without merging**
