### PR TITLE
Add hasOwnProperty check inside for..in loops.

### PR DESCRIPTION
**Pull request by dompuiu**
React initialization will fail if the JS Object prototype is extended
before React is loaded. I've added hasOwnProperty checks in the `for..in` loops that were triggering the exception.

You can check this example: https://jsfiddle.net/cpjnq10z/

### CODE REVIEW

**Comment by jimfb** [comment]
@spicyj @sebmarkbage Thoughts?

**Comment by spicyj** [comment]
Like most libraries (e.g., jQuery), we don't support extending Object.prototype.

**Comment by dompuiu** [comment]
@spicyj: In DOMProperty.js there are already places where `hasOwnProperty` checks are used. Why are you allowing those there?

**Comment by spicyj** [comment]
I assume the intention was to support properties with names that happen to match ones in Object.prototype, so that our config could support properties with names like `toString`. We're not super consistent about this but supporting extension of Object.prototype is a pain and we don't have any plans to support it right now.

**Pull request closed without merging**
