### PR TITLE
[docs] Link to mixins considered harmful

### PR DESCRIPTION
**Pull request by tomkel**
Extend the knowledge about mixins contained in [reusable components](https://facebook.github.io/react/docs/reusable-components.html) to include [mixins considered harmful](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html).

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by tomkel** [comment]
I've completed the CLA.

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by aweary** [comment]
Since this doc page doesn't exist anymore I'm going to go ahead and close this 😄

**Pull request closed without merging**
