### PR TITLE
Fix #9122

### LINKED ISSUE #9122: Missing /> in tic tac toe tutorial throws errors on codepen
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

This line -> `<button className="square" onClick={() => alert('click')}>` located [here](https://facebook.github.io/react/tutorial/tutorial.html#an-interactive-component) throws errors in codepen as it's missing a closing tag `/>`.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

Using the [starter code](https://codepen.io/ericnakagawa/pen/vXpjwZ?editors=0010) so using

- `https://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-with-addons.js`
- `https://cdnjs.cloudflare.com/ajax/libs/react/0.14.7/react-dom.js`

### PR DESCRIPTION
**Pull request by acz13**
alternatively it could just tell you to the whole tag with

```html
<button className="square" onClick={() => alert('click')}>
  {/* TODO */}
</button>
```
or something like that

### CODE REVIEW

**Comment by acz13** [comment]
Of note, the tutorial probably needs [an overhaul](https://github.com/facebook/react/issues/9162)

**Comment by gaearon** [comment]
Thanks! There are other PRs addressing this in more detail so going to use them instead.

**Comment by gaearon** [comment]
@brigand and I rewrote some parts of the tutorial in https://github.com/facebook/react/issues/9454, and following along should be easier now. Let us know if you're still struggling! We’re happy to look at remaining issues in case we missed anything.

https://facebook.github.io/react/tutorial/tutorial.html

**Comment by acz13** [comment]
Good work 👍

**Pull request closed without merging**
