### PR TITLE
fix textarea does not respond to value prop changing to null (issue #2533)

### PR DESCRIPTION
**Pull request by rszewczyk**
Issue #2533 

I've completed the CLA.

### CODE REVIEW

**Comment by martinstein** [comment]
I'm trying to understand your fix: I get the logic behind having a `valueIsBlank` boolean that tells us whether to do the DOMPropertyOperations-part.

But why are you looking at `this.props.children` and `this.props.defaultValue` to determine that? Shouldn't we rather look at `this.state.initialValue`? That tells us, whether a previous value was set, which in turn means that a current value of `null`/`undefined` should now clear the textarea content.

So, shouldn't it be like this instead:

    var valueIsBlank = this.state.initialValue && value == null;

?

**Comment by syranide** [comment]
Can't test right now... but if I'm understanding it correctly it shouldn't even work correctly. The logic can be simplified and `this.props.children` isn't actually supported by textarea AFAIK?

**Comment by martinstein** [comment]
`this.props.children` is currently supported by textarea, but that's already deprecated and will be removed (according to the source comments).

I also think the fix doesn't work correctly. I have a working fix (both for `<textarea>` and `<select>`, but I need to get the grunt test environment to work before I can submit a pull request (which apparently means I need to install the MSVC Compiler).

**Comment by jimfb** [comment]
Superseded by https://github.com/facebook/react/issues/5013

**Pull request closed without merging**
