### PR TITLE
documentation: designers are friends, not fodder for jokes

### PR DESCRIPTION
**Pull request by feministy**
hello friends 👋 

i don't particularly like it when documentation makes jokes at the expense of my colleagues, so i've gone ahead and removed this unnecessary nugget.

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Sorry about that. I believe @petehunt meant it as self-deprecating towards himself, not being a professional designer like his colleagues, and not towards designers in general. That said, since this can be interpreted and doesn't add any value other than a colloquialism we can just remove it.

Please let us know if you find anything else. We hold the designer profession in very high regard and in fact make a point to not have exclusionary language since we believe that React is about letting different roles collaborate in one code base rather than separate them.

**Comment by ohwellthatwentverybadly** [comment]
It's sad we can't stand up for common sense in this case. This is clearly a self-deprecating joke and not aimed *at* designers. The author is making fun of his own mockup, saying he's a bad designer.

Must all our documentation be robotic and humourless :/

I hate the alt-right, 'anti-sjw' movement that gave birth to that Milo/Breitbart asshat as much as any rational person, but when we have examples like this, basically misguided nitpicking, we give fodder to people like him.

Please defend common sense.

If all comedians suddenly started apologising and retracting their comedy because it 'could be misinterpreted' it'd be a sorry world to live in.

Please give us some reason to carry on in this post-truth society :)

**Comment by spicyj** [comment]
@ohwellthatwentverybadly I am sure that the people who have read this text negatively were not _trying_ to misinterpret it. What's "clearly" a self-deprecating joke to you is something that was literally interpreted by many other people as putting down designers. It's true that your interpretation of it was the one that the author intended, but that doesn't mean it's the only way to read this. Everyone reading the docs comes with different context and different preconceptions which cause people to read the same words in different ways.

We lose nothing by changing these words to be clearer, and if it means that even one fewer person will come along and think that we're putting down our coworkers, that seems like a no-brainer to me. We'd rather err on the side of inclusivity and avoid turning people away. And we have plenty of other jokes in our docs and don't need to keep this one.

**Comment by sebmarkbage** [comment]
For example, I've seen other tool chains and libraries use descriptions like "even a designer can use it" or "your templates are so simple that a designer can iterate on it". Even though those are also meant to be helpful to designers I've personally found that kind of descriptions completely underestimating the technical skills of modern UX designers. I can definitely see how with that background context, it can be read like this.

**Pull request merged**
