### PR TITLE
Update tutorial.md. [skip ci]

### PR DESCRIPTION
**Pull request by bogdanvlviv**
changed row   `<CommentBox url="/api/comments" />` to   `<CommentBox url="/api/comments.json" />`.

### CODE REVIEW

**Comment by zpao** [comment]
This is actually correct as is - the tutorial is designed to be run with one of the servers in the tutorial repository. These are all essentially API servers where `api/comments` will return json.

**Comment by jimfb** [comment]
@zpao Might as well add the additional `.json`, right?  It doesn't hurt anything and it does add to clarity?  And makes it compatible with any server that won't automatically serve up a file without the suffix.

**Comment by bogdanvlviv** [comment]
I have problem when passing this tutorial with server.rb (ruby).

**Comment by bogdanvlviv** [comment]
I see bug in server.rb
`server.mount_proc '/api/comments' do |req, res|`
`  comments = JSON.parse(File.read('./comments.json', encoding: 'UTF-8'))`
i can change it there?


i think it this tutorial file can be better when this changes will be fixed

**Comment by jimfb** [comment]
My personal preference is to fix everywhere to have the `.json` suffix.  I don't see why a user should need to do anything more than drop the tutorial files into a simple http server (for the purposes of the tutorial).  But let's wait and see what @zpao thinks of that before we invest any further work one way or the other.

**Comment by bogdanvlviv** [comment]
all fine. i have problem because i didn't see this notice ` changing the comments.json file (in the same directory as your server)`. i am sorry

**Comment by bogdanvlviv** [comment]
but i think, what about to make servers more flexible and put file a`app/comments.json` in `public/` folder this will be correctly?

**Comment by zpao** [comment]
@jimfb no, while the server does essentially just load the file and send that out, it's specifically meant to simulate a real-life API server. We changed to this from serving the file directly since we needed to handle POST and it got confusing. Consistently having an API is cleaner and less confusing in the long run.

**Pull request closed without merging**
