### PR TITLE
Optimize createElement

### PR DESCRIPTION
**Pull request by zackasaurus**
## Summary

I created this PR in response to the https://github.com/facebook/react/issues/27216 issue I opened.

## How did you test this change?

I created a sandbox which renders a large React DOM tree with a configurable number of elements and props. These are broken up by LIST, DEPTH, and PROPS. I used the settings LIST = 500, DEPTH = 20, PROPS = 30 to emulate a complex react app and saw a 30-40% reduction in script. 

For benchmarking, I used the production version of both the current 18.2.0 `createElement` and the production-built custom version of the modified `createElement` as seen in the PR.

Sandbox link:

https://codesandbox.io/s/react-create-element-performance-comparison-tpp5cl?file=/src/App.js

What the UI looks like:

image

What the F12 Performance Trace looks like:

image

### CODE REVIEW

**Comment by V01D-NULL** [comment]
any updates on this?

**Comment by zackasaurus** [comment]
See: https://github.com/reactjs/rfcs/pull/107

**Comment by V01D-NULL** [comment]
thank you

**Comment by sophiebits** [comment]
Wow! This is a big improvement. It is hard to know how this will translate to a real app since the engine performance characteristics will be different for this case with only a few component types and props shapes vs a real app with many types of components and many shapes of props. But hopefully we can ship all the changes in https://github.com/reactjs/rfcs/pull/107 which would have even a bigger impact than this.

**Comment by kurtextrem** [comment]
this still looks like something worth merging, so "bump" from my side.

**Comment by kurtextrem** [comment]
actually, looks like this could be closed because of https://github.com/facebook/react/pull/28768

**Comment by sophiebits** [comment]
@zackasaurus Thanks for sending this in! This helped kick-start the work to get #28768 and friends landed for real. Hopefully you will see even larger gains from that set of changes once they’re released (note they’re still behind a feature flag on main for now).

**Pull request closed without merging**
