### PR TITLE
[idea] Remove data-reactid and traverse immediately after insertion instead (nope, still lazy!)

### PR DESCRIPTION
**Pull request by syranide**
Part 1 of #1550

This PR removes `data-reactid` from the DOM and reconstructs it on-demand, then storing it as a hidden property `__reactID` on the node instead. Nodes and instances are traversed as pairs, in sync, when reconstructing.

**Peformance comparison:**
We have the option to choose between keeping the current on-demand traversal of nodes, or switching to immediate traversal after insertion into the DOM. Running my old super synthetic benchmark, creating 11 level deep trees of plain divs, measuring mount+unmount. The lazy method is roughly 15% faster it seems, adding just one attribute to all nodes reduces it to about 9%, adding one more reduces it to about 5% (for IE8 and Chrome).

However, it is important to note that these numbers are significantly inflated as they do _not_ include reflow (which seems to increase running time of my tests by about 75%), actual rendering nor any other common React overhead such as composite components, handling event listeners, etc. It should also be noted that as of current, React will immediately traverse to any node containing an onClick-listener or an image with onLoad/onError-listeners or if you call getDOMNode in componentDidMount. Additionally, any updates applied to the DOM also require traversal to each affected node. None of which are included in this benchmark.

So while end-user measurable performance impact is hard to quantify, I think it's safe to say that at worst it may be effectively increased by 5% (excluding rendering), add a bunch of attributes, add some React overhead, onClick-listeners and we're down to perhaps 1-3%? In that context, I think it's important to consider that there are important real-life implications of on-demand traversal:

**For immediate traversal;** testing whether a node is a React-node is always O(1). We also avoid a lot of complex code that is otherwise there to ensure that a node exists in the cache, which means that going from node to instance to node is super cheap, which may open up some interesting potential down the road. We also detect invalid DOM nesting on insertion (for free). The size of React decreases "measurably" and code complexity is decreased.

**For on-demand traversal;** we must be able to traverse up the component instance parent tree and each node instance must immediately register itself with ReactMount. Testing whether a node is a React node is O(1) for cached React nodes and "up to" O(depth) for uncached React nodes or non-React nodes. We also lose the guaranteed/immediate validation of DOM nesting (although we can enable it for DEV).

There are a lot of improvements that this PR enables that is independent of immediate or on-demand traversal, but lets not make this wall of text any longer. I can see the benefit of both methods, but I think immediate traversal intrigues me the most given its modest cost, it's also _uniform_ and deterministic during insertion and over time (not that it really matters given the modest performance implications, perhaps).

---
#1568 and #1569 must be fixed before this PR can be taken (or simple temporary workarounds have to be put in place). Add #1578 too and React leaves no lasting print in the visible DOM.

This PR has commits for both the immediate and on-demand traversal, both are fairly final implementations (obviously pending some decisions / feedback though).

---
- [ ] Waiting for #1434 to land (intersecting code refactored)
- [ ] Depends on #1568 to land
- [ ] Depends on fix for #1569 (@sebmarkbage?)
- [ ] Lazy or immediate traversal?

### CODE REVIEW

**Comment by gaearon** [comment]
What is the status of this? Are there plans to eventually get rid of `data-reactid`? Is this on hold due to more pressing issues? Thanks!

**Comment by syranide** [comment]
@gaearon There's a PR (can't find it) for adding internal parent references which is necessary for the event system to work without `data-reactid` and there is one or two bugs in React which conflicts (but they can be workaround if they are willing). There is one alternative method that can be implemented without parent references, but... they expressed a desire to extensively benchmark and compare the various approaches before moving ahead.

As for server-side rendering without `data-reactid`, reconstructing `data-reactid` client-side is doable today and shouldn't come at a significant cost (and certainly favorable if you can drop `data-reactid` from the server-side generated markup). I've brought this up before but no one really seemed to care much so I never moved ahead with it.

**Comment by callmevlad** [comment]
>  I've brought this up before but no one really seemed to care much so I never moved ahead with it.

@syranide I care a lot and willing to put up a sizable bounty to get this implemented. I'd love to hear your thoughts on what remaining bits remain to hide `data-reactid` from the DOM. (My email is in my profile just in case.)

**Comment by spicyj** [comment]
@callmevlad Curious: Why do you care?

**Comment by callmevlad** [comment]
@spicyj At [Webflow](https://webflow.com) we have a design interface that wraps web inspector-type tools around an iframe that contains a website's actual DOM (as it will be published to the final hosted production environment). A huge selling point of Webflow has been that the contents of that iframe are 100% what-you-see-is-what-you-get and the-same-code-your-developer-would-write, and we routinely demo this in pitches by inspecting elements live as they are modified with Webflow's tools. It goes a long way to convince stubborn frontend developers at larger companies who believe that generating great code is not possible - by directly demonstrating it to them by looking at the DOM.

Now that we're shifting the rendering of the site canvas to React, that "WYSIWYG" property no longer holds true. Inspecting the DOM is decorated heavily with `data-reactids`, which now makes the code "look generated" and we start hearing things like "that's not how I would write the HTML, therefore we should stick to hand-coding our websites" from potential users/customers. We'd love to avoid that as much as possible.

Also, it just looks much nicer without all the IDs inside DevTools since you can see much more of the DOM in the same amount of real estate :)

**Comment by spicyj** [comment]
Cool, thanks for the context. Webflow looks sweet. :)

**Comment by syranide** [comment]
@callmevlad What can be done somewhat non-invasively (i.e. an easy to maintain fork) at the moment is the "immediate traversal" version of this PR. There are two alternatives:

1. The very simplest being to simply immediately traverse any rendered nodes, copy `data-reactid` into `node.reactid`, remove `data-reactid` and update `internalGetID` to read from `node.reactid` instead (more or less). You still have to ship `data-reactid` with server-side markup though.

2. Again, immediately traverse any rendered nodes but reconstruct `data-reactid` (quite easy too) instead and store it in `node.reactid`. The rest is same as above, but this doesn't require you to ship `data-reactid` with the server-side markup.

I can't imagine the devs being OK with having this "hack" in the release version so it would have to be in a separate fork. But as I said earlier I could imagine the server-side part of alternative 2 being shipped though (but not my call) which would make the client-side fork near trivial. I don't imagine the performance impact of this being significant.

For reference, most of the changes in this PR is because of the lazy traversal and updated tests. It's possible I overlooked something minor above, but this PR was functional so it's definitely doable.

**Comment by natew** [comment]
@syranide Sorry to bring up a possible dead issue, but this is also desirable to me / my team. It seems like your summary is that it's doable, why would devs not be ok with this? Anyway, just wanted to voice more support for this, for a similar reason to Webflow.

**Comment by syranide** [comment]
@natew Good news #5190 #5205

**Comment by Chyzwar** [comment]
Is there is any chance this will land in 0.15 or 0.16?

**Comment by zpao** [comment]
It will be a part of 0.15

**Comment by callmevlad** [comment]
So glad this finally landed - thanks @syranide @spicyj @gaearon @zpao for helping push this through! :clap: :clap: :clap:

**Pull request closed without merging**
