### PR TITLE
Examples add Ajax and Jsx

### PR DESCRIPTION
**Pull request by yasaricli**

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Is this safe or is this potentially an XSS hole in hour demo? E.g. if the domain gets compromised.

**Comment by sebmarkbage** [comment]
we can rely on a server running this demo. I believe some other demos doesn't work without a simple http server. We could just store this in a JSON file.

**Comment by zpao** [comment]
Meh, I don't really care about hitting a random API server. It looks like it's only setting and image src which is escaped (unlike the element case). We could also change it entirely so it hits a service we trust more - could make it get an provided user's public github information.

I would probably do this differently though and only initiate the request on a button, with a clear "this is going to make a request to <endpoint> and load some data when you click here".

That said, requesting a local file is ok too. That would definitely require a running server in some browsers.

I didn't look at this much when it came in because our tutorial does XHR so we already provide code doing this.

**Comment by spicyj** [comment]
The issue is that $.getJSON does an indirect eval via JSONP. Probably.

**Comment by zpao** [comment]
http://api.jquery.com/jquery.getjson/ seems to say that JSONP is only used if there is a `callback` query param.

**Comment by zpao** [comment]
Meh, our tutorial does pretty much exactly this already so I'm just going to close out. Thanks anyway!

**Pull request closed without merging**
