### PR TITLE
Introduce search

### PR DESCRIPTION
**Pull request by vjeux**
Powered by the awesome Algolia :)

### CODE REVIEW

**Comment by cpojer** [comment]
#paternityleave

**Comment by bjrmatos** [comment]
:tada:

**Comment by vjeux** [comment]
- Made it look more like a search box
- Increased the contrast for the row highlight
- Removed the space between the header and the dropdown

**Comment by aleclarson** [comment]
+1 :smile:

**Comment by zpao** [comment]
Let's do it. If we want to tweak anything more we can do it live.

**Comment by vjeux** [comment]
Ping :)

**Comment by zpao** [comment]
Sorry, been out of town. It's all up now.

**Pull request merged**
