### PR TITLE
Fix for #5957: Bug on resolving default props (HTMLAllCollection)

### PR DESCRIPTION
**Pull request by karczk**
Fix for #5957

### CODE REVIEW

**Comment by jimfb** [comment]
This looks good.  There are a bunch of others I mentioned in that bug.  Can you go through them (there are less than a dozen) and fix the ones that follow this same pattern (binding exists, but we are using typeof anyway)?

**Comment by karczk** [comment]
I fixed all the unnecessary occurrences, i.e. function parameter, previously declared variable, variable properties.

**Comment by jimfb** [comment]
Looks great, thanks!

I'll leave it open for a day to see if anyone has any other feedback, and then we can merge!

**Comment by jimfb** [comment]
Thanks @karczk!

**Pull request merged**
