### PR TITLE
Add missing index for array in tutorial

### PR DESCRIPTION
**Pull request by romainneutron**
Hello, I was reading and following steps in the tutorial. I realised the example missed an `key` property, otherwise I got this error in the console:

`Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of CommentList. See https://fb.me/react-warning-keys for more information.`

### CODE REVIEW

**Comment by BatenkovT** [comment]
Hello, add index on your tutorial page too: facebook.github.io/react/docs/tutorial.html.

**Comment by romainneutron** [comment]
Hello, sorry for the delay. 

I've updated the PR according to your comment and found another typo.

**Comment by spicyj** [comment]
Hm. We should probably introduce some sort of `id` property here. We shouldn't use the text of the message. I could see arguing for skipping over this and leaving the warning, but understanding `key` is fundamental to using React effectively so we should probably work it in properly.

@zpao What do you think?

**Comment by zpao** [comment]
Yea, we really should have ids, I was just looking at this - looks like this warning has been around in the tutorial here for a while but in our finished product we use array index. https://github.com/reactjs/react-tutorial/blame/master/public/scripts/example.js#L87

We could make the servers generate ids, maybe be really dumb and use timestamps? Or we could change the format so it's like an autoinc column and store the last id (`{id: 5, data: [{id: 1, name: 'Pete' ...}]}`). API endpoint still works identically just has an extra id field.

As for this PR… let's keep it focused on the tutorial and not make changes to any other pieces of documentation. Not clear what we'll change it to yet though.

**Comment by bcomnes** [comment]
Having just gone through the tutorial, and trying to piece together why keys are necessary, this seems like one of the better places to introduce them, as it's the first place I looked when I came across the key warning (only to find the omission).

It seems like using the map index to illustrate how to use keys would be sufficient, but I'm new to this so ` ¯\_(ツ)_/¯`.  Adding a tutorial grade explanation to supplement the example would be important as well.  I took a stab at it in https://github.com/facebook/react/pull/5374 but I'm sure it can be improved upon.

**Comment by romainneutron** [comment]
I can change the PR and use the array index. WDYT?

**Comment by jimfb** [comment]
The problem with index is that if a comment gets added/deleted from anywhere except the end, the indexes all shift.  It works, but is perhaps not the best practice.  Normally you would want to use a commentId of some sort.  Just using `index` sends a suboptimal message.  Anyway, I'll let @spicyj and @zpao make the final call here.

**Comment by bcomnes** [comment]
> The problem with index is that if a comment gets added/deleted from anywhere except the end, the indexes all shift.
Oh yeah good point.

**Comment by jimfb** [comment]
The problem is that if we just use `index` and add a note saying "actually, this is wrong, don't do this", that's almost worse than not saying anything and leaving it as a warning (user is still equally confused about what they **should** do, and we haven't actually made the code any better).  Adding real IDs means that the example becomes unnecessarily complex and the ID logic is distracting.  That's why we're not entirely sure how to fix this, and why it might be ok to leave this as a warning and let people learn about keys later.

**Comment by zpao** [comment]
We're going to add real ids. See my in-progress update in the tutorial repo - the changes to the actual code here is pretty minimal. https://github.com/reactjs/react-tutorial/pull/96/files#diff-43fd6de5aa6bfed98ce8f78b5494a419R47

**Comment by zpao** [comment]
Thanks for the PR and sparking a good discussion. It was a bit easier for me to make the changes in both places and coordinate any updates so I have #5444. As a result I'm going to close this out. Thanks again!

**Comment by bcomnes** [comment]
:beers:

**Pull request closed without merging**
