### PR TITLE
ReactLink for radio buttons (radioLink)

### PR DESCRIPTION
**Pull request by guybenron**
Adresses #3573 .

I modified LinkedValueUtils.js to add support for the following syntax:

    <input type="radio" name="mygroup" value="value1" radioLink={this.linkState("myval")}/>
    <input type="radio" name="mygroup" value="value2" radioLink={this.linkState("myval")}/>

State will have a variable named `myval` that will hold the radio buttons `value` attribute (e.g., `value1` or `value2`). Setting this state variable to a specific value will cause the corresponding radio button to be selected. If there is no corresponding radio button, all will be deselected.

Also updated documentation.

### CODE REVIEW

**Comment by guybenron** [comment]
So ummmm... what's the next step?

**Comment by tobia** [comment]
I'm already using this patch, so I hope it will be merged soon

@guybenron maybe they are waiting for you to solve the merge conflicts

**Comment by syranide** [comment]
#2302, ReactLink is probably going to be deprecated so possibly never, but that's not my call. You can easily provide your own enhanced `input`-component wrapper which provides this behavior rather than having it be supported by React core, that's my recommendation.

PS. It really should be called `checkedLink` (the property is called `checked`), not `radioLink`.

**Comment by sebmarkbage** [comment]
Yea, sorry. I recommend that you implement a wrapper component and publish it to npm.

**Pull request closed without merging**
