### PR TITLE
Add recommended config for eslint-plugin-react-hooks

### LINKED ISSUE #16872: Proposal of recommended config in `eslint-plugin-react-hooks`
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
If you are using `eslint-plugin-react-hooks` you need to put rules configuration manually. What if in the next version you will add some more rules?
Should everyone who use it after future release add all the **new** rules to config manually?

**What is the expected behavior?**
I propose instead of instructing on every new rule to create `recommended` [config](https://eslint.org/docs/developer-guide/working-with-plugins#configs-in-plugins) as in `eslint-plugin-react`, as follows:
```
export default {
  rules: {
    'rules-of-hooks': RuleOfHooks,
    'exhaustive-deps': ExhaustiveDeps
  },
  configs: {
    recommended: {
      plugins: [ 'react-hooks' ],
      parserOptions: {
        ecmaFeatures: { jsx: true }
      },
      rules: {
        'react-hooks/rules-of-hooks': 'error',
        'react-hooks/exhaustive-deps': 'warn'
      }
    }
  }
};
```
Also, to instruct to extend instead:
```
extends: [
  'eslint:recommended',
  'plugin:react/recommended',
  'plugin:react-hooks/recommended'
],
```

### PR DESCRIPTION
**Pull request by silvenon**
## Summary

Recommended configs are a common practice with ESLint plugins, they offer a quick way to add the plugin and configure basic rules. eslint-plugin-react-hooks is especially straightforward in that regard.

With these changes extending `plugin:react-hooks/recommended` would be equivalent to:

```json
{
  "plugins": [
    "react-hooks"
  ],
  "rules": {
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn"
  }
}
```

## Test Plan

I tested the config using ESLint's `CLIEngine`, that seemed to strike a balance between clean and easy.

Fixes #16872.

### CODE REVIEW

**Comment by silvenon** [comment]
Added tests. ✅

**Comment by silvenon** [comment]
I don't think these failures are caused by my changes. 🤷‍♂

**Comment by Mathspy** [comment]
Just a heads up that this has already been merged in https://github.com/facebook/react/pull/14762

**Comment by silvenon** [comment]
Thanks!

**Pull request closed without merging**
