### PR TITLE
blog post: Discontinuing IE 8 Support in React DOM

### PR DESCRIPTION
**Pull request by spicyj**

### CODE REVIEW

**Comment by zpao** [comment]
👍

**Comment by SimenB** [comment]
The link provided here (https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support) seems dead.

image

It's the same link as the top google search result though, so I don't know what else to link

**Comment by spicyj** [comment]
The link works for me. Not sure what's up.

**Comment by spicyj** [comment]
Maybe some crappy geolocation or something?

**Comment by jimfb** [comment]
The URL appears to have been down temporarily, but it looks like it's up now.

**Comment by SimenB** [comment]
Ah, yeah it works now. People are so excited Microsoft's servers can't keep up it seems

**Pull request merged**
