### PR TITLE
Move Past Confs, add React Conf Brazil 2017

### PR DESCRIPTION
**Pull request by danvitoriano**
**Update community/conferences.md**:
- Move React London e React Amsterdam to Past Conferences
- Add React Conf Brazil to October, 07, 2017
<http://reactconfbr.com.br>

### CODE REVIEW

**Comment by nhunzaker** [comment]
This looks good to me. @gaearon For documentation PRs, is there anything additional we should do before merge?

**Comment by trueadm** [comment]
There are conflicts on this PR. Please can you resolve? :)

**Comment by danvitoriano** [comment]
Now it is ok @trueadm ! tks!!!

**Comment by gaearon** [comment]
Thanks!

**Comment by danvitoriano** [comment]
Hey @gaearon! Thank you! By the way, don't you wanna come to Brazil and talk to us?

**Comment by xgqfrms-GitHub** [comment]
good job!

**Pull request merged**
