### PR TITLE
Add Netlify integration for DOM Fixtures folder

### PR DESCRIPTION
**Pull request by klamping**
In issue #11079, @nhunzaker mentions that it would be nice to have an automatic deployment of [the DOM Fixtures folder](https://github.com/facebook/react/tree/master/fixtures/dom) for manual and automated testing purposes.

Since [Netlify offers their services for free to open source projects](https://www.netlify.com/open-source/) (an account for this will need to be set up), I thought it would be a great fit. 

This commit adds a `netlify.toml` file to the repo, allowing easier deployment out to the service.

This file will do two things:
1. On master branch update, it deploys the latest code to the main linked netlify site. For example: https://musing-lewin-a6efa4.netlify.com/
2. For every PR opened, creates a 'Deploy Preview' site for validating that PR's changes. For example: https://deploy-preview-1--musing-lewin-a6efa4.netlify.com/
The preview site is linked via GitHub in the PR. 
image

**Test Plan:**
Create a Netlify account and [connect the github repo you're testing to it](https://app.netlify.com/start).
After connection, Netlify should deploy the DOM fixtures build folder to a live site for you to use.

### CODE REVIEW

**Comment by aweary** [comment]
This is very cool, thank you for doing this @klamping! The React website is powered by Netlify, so we may already have an official account. cc @gaearon

**Comment by nhunzaker** [comment]
Wow. This is so cool; thank you so much!!

Let's get the account stuff setup!

**Comment by jquense** [comment]
awesome!

**Comment by klamping** [comment]
Any chance I can get an update on the status of this?

**Comment by gaearon** [comment]
@klamping Hey sorry for no response, we're pretty swamped by some longer term projects and so everything related to infra like testing is on a backburner. We really appreciate the PR but realistically we don't have enough time to review DOM-related changes either so it's not urgent to get in. When we get closer to working on these changes, we'll definitely check it out. Thanks!

**Comment by klamping** [comment]
@gaearon thanks for getting back with me and the explanation on it all!

**Pull request merged**
