### PR TITLE
Fix event handling when input name='nodeName'

### PR DESCRIPTION
**Pull request by jimfb**
Fix event handling when input name='nodeName'.  Fixes https://github.com/facebook/react/issues/6284

cc @zpao

### CODE REVIEW

**Comment by zpao** [comment]
Let's figure out the solution first and then fix the whole class of issues, whack-a-mole isn't fun (there's another method in that file which needs to be fixed anyway).

**Comment by jimfb** [comment]
@zpao Just fixed the other method (I assume that's the one you were referring to), also switched to the `instanceof` solution you preferred.  Tested it here: http://jsfiddle.net/r0espr50/

**Comment by zpao** [comment]
There are still a bunch of other uses of `nodeName` used in the exact same pattern that aren't covered here (just grep for it). Again though, we should make sure that's a good solution to the problem and not opening us up to other problems (eg, do you have any insight into the perf tradeoff, are there other things we should look out for?)

**Comment by jimfb** [comment]
> There are still a bunch of other uses of nodeName used in the exact same pattern that aren't covered here (just grep for it).

Yeah, nodeName is mostly used for unit tests.  It's only a problem when we're potentially going to run up against a form element (or window, with Ids).  If you spot another one that you think will have a similar issue, feel free to flag it.  At least this makes things incrementally better.

 > Again though, we should make sure that's a good solution to the problem and not opening us up to other problems (eg, do you have any insight into the perf tradeoff, are there other things we should look out for?)

instanceof is faster than doing a typeof check (http://jsperf.com/wgerherherh/2), so this seems fine from a perf perspective.  It's a pretty straight forward diff, so I think we should just push it forward.  If we happen to discover that it's bad, we can always revert, but I think it's fine.  If you have an idea of an alternative you would prefer, just say so.

**Comment by zpao** [comment]
>  If you spot another one that you think will have a similar issue, feel free to flag it.

Might not have the same issue, but we should just use the same pattern. No point doing the same thing different ways when we know 1 has an issue and there are supposedly no tradeoffs. https://github.com/facebook/react/blob/c528732504959711655c9bded98c6943f7461d6f/src/renderers/dom/client/ReactInputSelection.js#L33-L36 (another case in that file).

Also https://github.com/facebook/react/blob/c528732504959711655c9bded98c6943f7461d6f/src/renderers/dom/shared/ReactDOMContainerInfo.js#L25 which we have to do differently since we want the tag name. We can probably just check we have a string and not care too much in this specific case. That was trivial to repro: http://jsfiddle.net/nf8tr6k9/

**Comment by jimfb** [comment]
> No point doing the same thing different ways when we know 1 has an issue and there are supposedly no tradeoffs.

To be clear: doing an instanceof check is slightly more expensive than doing a strcmp check.  It's just much cheaper than doing a typeof.

 > Might not have the same issue, but we should just use the same pattern

We should avoid adding an instanceof check if we don't have a reason to believe we need it.

 > We can probably just check we have a string and not care too much in this specific case.

No, the point was that it's more expensive to first check that we have a string.  We could probably add a devmode warning there if we wanted to.  But in the 99% case, that container is going to be a `div` or similar; people are unlikely to mount into a form component, and if they do, they are further unlikely to give their fields a conflicting name.

The reason it made sense in the cases that I fixed is because we are traversing the DOM and if any of the nodes are forms with this problem, we fatal.  In `ReactDOMContainerInfo.js`, we aren't traversing (so lower probability of being hit) and we aren't likely to be mounting into a `form` node that suffers from having it's attributes expando'd away, so the value add is asymptotically close to zero.

**Comment by zpao** [comment]
👍

**Comment by gaearon** [comment]
Aren’t `instanceof` checks with `window` going to [give false negatives in iframes](http://stackoverflow.com/questions/26248599/instanceof-htmlelement-in-iframe-is-not-element-or-object)?

**Comment by gaearon** [comment]
Here’s a repro case for when the new version reports `false` for inputs inside iframes whereas the original version reported `true`: https://jsfiddle.net/h0L5vLkw/1/

**Comment by aweary** [comment]
@gaearon https://github.com/facebook/react/pull/7936 is meant to address selection handling with iframes. If `instanceof` would break with iframes, would it make more sense to get https://github.com/facebook/react/pull/7936 in then address the issue with those changes merged?

**Comment by nhunzaker** [comment]
@jimfb Are you game for making the requested changes? Otherwise, I'm happy to pick this up.

**Comment by nhunzaker** [comment]
Closing this out, rebased and upstreamed in https://github.com/facebook/react/pull/10076. Thanks @jimfb for all of your hard work!

**Pull request closed without merging**
