### PR TITLE
Removed _debugID field from Fiber - Issue #21558

### LINKED ISSUE #21558: Remove _debugID field from Fiber
This DEV-only field was added in 836331ba5f69f2cc53b273ec073fae116db14302 by @sebmarkbage but it's not being used anymore to my knowledge.

### PR DESCRIPTION
**Pull request by Pulkit3234**
Removed `_debugID` field from Fiber

Resolves #21558

### CODE REVIEW

**Comment by bvaughn** [comment]
Hey @Pulkit3234! Nice work!

CI is failing for a couple of reasons though. Should be easy to fix:

First, lint/styling. To fix this, just run:
```sh
yarn prettier
```
Then you can commit the minor formatting changes (mostly just spacing, I think).

Secondly, the `debugCounter` variable in `ReactFiber.new.js` (and `ReactFiber.old.js`) is no longer used, so you can delete it.

Lastly a couple of tests are now failing CI. This is a little bit more tricky I think. These tests verified that we deduplicate warnings so they're only shown once per component type. Some of these warnings (like "_Function components cannot be given ref_" for example) do their de-duplicating using `fiber.type.displayName || fiber.type.name || fiber._debugID || ''` so if a component doesn't have a _name_ (if it's anonymous) we'll no longer log a unique warning for it.

I _think_ that's probably okay to be honest, but maybe someone else might disagree.

**Comment by Pulkit3234** [comment]
Yes sir, I am fixing the first two things that you told :)

**Comment by bvaughn** [comment]
CI is still failing b'c of formatting:
https://app.circleci.com/pipelines/github/facebook/react/14042/workflows/63b2ef2f-d01a-46ed-b670-e75d8311929a/jobs/321219

Try running:
```sh
yarn prettier-all
```

Only a single test is failing:
https://github.com/facebook/react/blob/bb1c8215569f59b70276e8939bd8a59aa7f28f53/packages/react-dom/src/__tests__/ReactFunctionComponent-test.js#L245-L309

You can change this test from `it(...)` to `xit(...)` for now to disable it. Then I can raise this discussion point with the team to see if there are concerns.

**Comment by Pulkit3234** [comment]
Thanks a lot @bvaughn sir for guiding and correcting me while I was working on this issue 😄. I can't tell at this moment that how much delighted I am as its the first successful pr that I made on my favorite Javascript library React. I am new to open source and I think I have learnt so much working on this single issue, but I wanted to know that how do all the react maintainers like you and Dan sir add new features or improve the existing ones, like how do you notice bugs in such a huge codebase?

**Review by bvaughn — APPROVED** [review]
I think this change is fine, but I'm going to run it by the team and see if anyone else thinks the downside (DEV warning de-duping) is worrisome.

**Comment by bvaughn** [comment]
I'm going to go ahead and land this change 👍🏼  Thanks!

**Comment by Pulkit3234** [comment]
@bvaughn sir, thank you so much for mentioning me as well in the final commits, that means a lot 😄. Looking forward to make some awesome contributions to react in future!, with your help and guidance!

**Pull request merged**
