### PR TITLE
Update 2015-06-12-deprecating-jstransform-and-react-tools.md

### PR DESCRIPTION
**Pull request by RReverser**
Add paragraph about parsing JSX after deprecation of esprima-fb.

### CODE REVIEW

**Comment by spicyj** [comment]
Curious: does acorn support all the latest ES6 syntax or are there many constructs that only acorn-babel supports?

**Comment by RReverser** [comment]
@spicyj Yes, Acorn supports complete ES6 for a very long time now ([most of it](https://github.com/marijnh/acorn/pull/110) was added by me about a year ago and other final fixes / additions were being added in sync with ES6+ESTree specs after that).

**Comment by spicyj** [comment]
Sweet, thank you.

**Comment by RReverser** [comment]
Thanks for merging!

**Comment by zpao** [comment]
If we're going to call out Acorn, it would feel remiss to not mention Espree, which also parses JSX.

**Comment by RReverser** [comment]
Maybe, although Acorn is the underhood of now-official-transpiler and Espree is considering [switch to Acorn](https://github.com/eslint/espree/pull/143) as well. In any case, I don't have any strong opinion on this.

**Comment by zpao** [comment]
Oh nice, I didn't realize that was under consideration. I think we're probably fine as is then.

**Pull request merged**
