### PR TITLE
Fixed some comment punctuation in ReactDOMComponent.js

### PR DESCRIPTION
**Pull request by TracyJordan**

### CODE REVIEW

**Comment by jimfb** [comment]
Sure, can you squash these two commits into a single commit?

**Comment by TracyJordan** [comment]
@jimfb Just squashed the two commits into a single commit!

**Comment by jimfb** [comment]
Looks good, thanks!

**Comment by zpao** [comment]
Bah, this isn't the website and didn't need to get merged to stable…

**Pull request merged**
