### PR TITLE
Adds a Stack-based Sierpinski triangle demo to compare with Fiber ✨

### PR DESCRIPTION
**Pull request by claudiopro**
Hi!
I'd like to contribute to the main repo a Stack-based Sierpinski triangle visualization demo that I used to compare with the Fiber demo and show the advantages of using Fiber to avoid dropping frames.

### CODE REVIEW

**Comment by acdlite** [comment]
Hey thanks for the PR! I have a suggestion.

It would be even better if we could add a toggle to the Triangle demo that switches between the two modes.

I don't think you really need to compare Stack and Fiber to make this worthwhile. Instead, you can compare Fiber with time-slicing to Fiber without it. Fiber without time-slicing will look essentially identical to the Stack implementation, so the effect will still be visible.

You can switch between the two modes in this demo by either wrapping or not wrapping the `setState` inside `tick()` in `unstable_deferredUpdates`:

```js
tick() {
  if (this.state.useTimeSlicing) {
    // Update is time-sliced.
    ReactDOM.unstable_deferredUpdates(() => {
      this.setState(state => ({ seconds: (state.seconds % 10) + 1 }));
    });
  } else {
    // Update is not time-sliced. Causes demo to stutter.
    this.setState(state => ({ seconds: (state.seconds % 10) + 1 }));
  }
}
```

**Comment by trueadm** [comment]
I think we should be avoiding the use of the inline Babel browser transformer in such example as it has a major impact on runtime performance. Maybe an example using CRA would be better?

**Comment by claudiopro** [comment]
@acdlite good point, since Stack is going away soon (right?) your suggestion makes more sense in the long run. My demo compared Fiber with Stack, but as far as React examples are concerned, if you say Stack and Fiber with time-slicing off are _essentially identical_ I trust you 😅 

@trueadm that's a good suggestion, I'll try and look at that in the background.

**Comment by madeinfree** [comment]
I love this compare to know how the fiber timeSlice work, maybe can just change original example file into:
```javascript
this.state = {
  seconds: 0,
  useTimeSlicing: false
};

return (
  <div>
    <div>
      <button onClick={ () => this.setState(state => { return { useTimeSlicing: !state.useTimeSlicing } } ) }>Change Mode: { this.state.useTimeSlicing ? 'useTimeSlicing' : 'unUseTimeSlicing' }</button>
    </div>
    <div style={{ ...containerStyle, transform }}>
      <div>
        <SierpinskiTriangle x={0} y={0} s={1000}>
          {this.state.seconds}
        </SierpinskiTriangle>
      </div>
    </div>
  </div>
);
```
just my personal suggestion 🤔

**Comment by acdlite** [comment]
@giamir Closed by #9262. Thanks for the contribution!

**Pull request closed without merging**
