### PR TITLE
Upgrade art fixtures to babel 7

### PR DESCRIPTION
**Pull request by epicfaace**
Part of #12548.

### CODE REVIEW

**Comment by epicfaace** [comment]
I'm not sure whom to ask to review this, maybe @gaearon ?

**Comment by ahtee** [comment]
> I'm not sure whom to ask to review this, maybe @gaearon ?

@acdlite :)

**Comment by threepointone** [comment]
This seems fine to me, could you rebase and verify it's still all ok?

**Comment by ahtee** [comment]
Is `plugin-proposal-class-properties` included with the `@babel/preset-env` already? I'd have to check, but Im assuming yes..

**Comment by epicfaace** [comment]
@acdlite ?

**Comment by epicfaace** [comment]
bump

**Comment by epicfaace** [comment]
Bump

**Comment by ahtee** [comment]
@epicfaace please stop bumping the issue. The team will get to the issue when possible.

**Comment by epicfaace** [comment]
@ahtee just making sure it doesn't get closed by stale bot ... ¯\_(ツ)_/¯

**Comment by rickhanlonii** [comment]
@epicfaace no worry, the stalebot message above specifically asks you to bump it if it's still relevant 👍

**Comment by rickhanlonii** [comment]
@epicfaace thanks again for submitting this, since this is so old could you rebase and update to the latest versions?

I'll make sure to get this in, ping me when it's done!

**Comment by epicfaace** [comment]
@rickhanlonii should be ready now -- thanks!

**Comment by epicfaace** [comment]
@rickhanlonii should be ready now.

**Comment by rickhanlonii** [comment]
Thanks!

**Pull request merged**
