### PR TITLE
Remove unnecessary var declaration

### PR DESCRIPTION
**Pull request by NameFILIP**

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by NameFILIP** [comment]
Thank you @kentcdodds for inspiring to contribute (https://www.youtube.com/watch?v=dRo_egw7tBc)

**Comment by NameFILIP** [comment]
@facebook-github-bot-4 you are a bot and you are wrong :-) I've signed the cla right before creating the PR

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by gaearon** [comment]
Thank you!

**Comment by kentcdodds** [comment]
applause-ancient-brief-F9DzQnxx6ZZNm

😄

**Pull request merged**
