### PR TITLE
Fix broken link to TypeScript docs

### PR DESCRIPTION
**Pull request by kevinSuttle**

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by DanielRosenwasser** [comment]
Sorry about the link break - thanks for sending out a PR @kevinSuttle! 👍

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by jimfb** [comment]
Looks good, thanks!

**Pull request merged**
