### PR TITLE
Provide error handling for non-extensible ref assignment

### LINKED ISSUE #16365: ErrorBoundary rendering multiple copies of itself
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When a error occurs during the assignment of a `ref` (and maybe other conditions), a error boundary wrapping that error may get confused and it would renders itself multiple times inside the same parent. See https://codesandbox.io/s/stoic-fermi-6etqb which renders:

```html
<div id="root">
  <div class="boundary"><span>content</span></div>
  <div class="boundary"><span>error</span></div>
</div>
```

**What is the expected behavior?**

```html
<div id="root">
  <div class="boundary"><span>error</span></div>
</div>
```

### PR DESCRIPTION
**Pull request by bl00mber**
fix #16365, related #7136

### CODE REVIEW

**Comment by bl00mber** [comment]
Because only assignment is wrapped, it should throw as usual. The ref itself is not wrapped to try...catch statement and not executed.

Screenshot from 2020-04-05

**Comment by gaearon** [comment]
I mean a case like this:

```js
<div ref={() => {
  throw new Error('hi')
} />
```

Does it trigger the same problem with error boundaries?

If yes, we need to fix both.

If not, why?

**Comment by bl00mber** [comment]
`throw...` throws in ref like in `componentDidMount`. The incorrect mechanics is probably related to duplicate of `The above error...` message. These messages are thrown from refs in both **commitAttachRef** and **safelyDetachRef** methods. One excessive message is thrown from **safelyDetachRef** which is called before **safelyCallComponentWillUnmount**. The problem may be in the fact that the ref is attached _despite_ throwing an error and then called again within **safelyDetachRef**. I've tried to fix it by removing incorrect ref from `finishedWork` so it not needs to be detached because nothing was attached.

For example, if ref throws is such a way
`(elem) => {this.inputField = elem; throw new Error('error')}`
it needs to detached through `ref(null)` anyway because it throws after ref attachment.

Does it seems correct?

## Before

1  Screenshot from 2020-04-05 errors

2  Screenshot from 2020-04-05 stacks

## After

3  Screenshot from 2020-04-06 CallbackThrowUpdated

**Comment by bl00mber** [comment]
up

**Review by 53jk1 — APPROVED** [review]

**Pull request closed without merging**
