### PR TITLE
 Add docs for publishing a react component

### PR DESCRIPTION
**Pull request by laumair**
Related to: https://github.com/facebook/react/issues/7882 and https://github.com/facebook/react/issues/8060

### CODE REVIEW

**Comment by laumair** [comment]
@gaearon

**Comment by gaearon** [comment]
The style of the page doesn't look similar to how all the other doc pages are laid out. Can you please start by making it consistent with other doc pages?

**Comment by laumair** [comment]
@gaearon Sure. thing

**Comment by laumair** [comment]
@gaearon I have made an attempt to make the  style of page consistent with the other pages. Please let me know if  there is  any other thing that needs to be addressed. Thanks

**Comment by sw-yx** [comment]
reviving. how did documentation fail on circle ci? can this be merged?

**Comment by bvaughn** [comment]
Thank you for filing this PR!

I'm sorry to be the bearer of bad news, but the documentation and source code for [reactjs.org](https://reactjs.org/) now lives in a different repository: [reactjs/reactjs.org](github.com/reactjs/reactjs.org). (For more info on why we made this move, see issue #11075.)

Would you be willing to re-open this PR on the new repo? I promise we'll review it quickly!

**Pull request closed without merging**
